{"metadata":{"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(im)initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:","kind":"identifier"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"comHeaderAndDataGroupPresenceInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":", ","kind":"text"},{"text":"sodDocumentSecurityObject","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"text":", ","kind":"text"},{"text":"dg1MachineReadableZoneInformation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dg2EncodedIdentificationFeaturesFace","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":", "},{"text":"dg3AdditionalIdentificationFeatureFingers","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg4AdditionalIdentificationFeatureIrises"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg5DisplayedPortrait","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg8DataFeatures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg9StructureFeatures"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?, "},{"text":"dg10SubstanceFeatures","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"dg11AdditionalPersonalDetails","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg12AdditionalDocumentDetails"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg13OptionalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg14SecurityOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"dg16PersonsToNotify"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?)","kind":"text"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false,"name":"iOS"}],"title":"init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"comHeaderAndDataGroupPresenceInformation"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":", ","kind":"text"},{"text":"sodDocumentSecurityObject","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dg1MachineReadableZoneInformation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dg2EncodedIdentificationFeaturesFace"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dg3AdditionalIdentificationFeatureFingers","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"dg4AdditionalIdentificationFeatureIrises"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg5DisplayedPortrait","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?, "},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg8DataFeatures"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg9StructureFeatures","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg10SubstanceFeatures"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg11AdditionalPersonalDetails"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg12AdditionalDocumentDetails","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg13OptionalDetails"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg14SecurityOptions","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg15ActiveAuthenticationPublicKeyInfo"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"text":"?)","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/init(comheaderanddatagrouppresenceinformation:soddocumentsecurityobject:dg1machinereadablezoneinformation:dg2encodedidentificationfeaturesface:dg3additionalidentificationfeaturefingers:dg4additionalidentificationfeatureirises:dg5displayedpo-4j37l"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/init(comheaderanddatagrouppresenceinformation:soddocumentsecurityobject:dg1machinereadablezoneinformation:dg2encodedidentificationfeaturesface:dg3additionalidentificationfeaturefingers:dg4additionalidentificationfeatureirises:dg5displayedpo-4j37l"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"url":"\/documentation\/dotnfc\/traveldocument","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"title":"Lds1ElementaryFile","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfile"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication","title":"Lds1eMrtdApplication","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)":{"kind":"symbol","navigatorTitle":[{"text":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:","kind":"identifier"}],"title":"init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"comHeaderAndDataGroupPresenceInformation"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":", "},{"text":"sodDocumentSecurityObject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dg1MachineReadableZoneInformation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dg2EncodedIdentificationFeaturesFace","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dg3AdditionalIdentificationFeatureFingers"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg4AdditionalIdentificationFeatureIrises"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"dg5DisplayedPortrait","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"dg7DisplayedSignatureOrUsualMark"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg8DataFeatures","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg9StructureFeatures","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg10SubstanceFeatures"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg11AdditionalPersonalDetails"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dg12AdditionalDocumentDetails"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"dg13OptionalDetails"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg14SecurityOptions","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?, ","kind":"text"},{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?, "},{"text":"dg16PersonsToNotify","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/init(comheaderanddatagrouppresenceinformation:soddocumentsecurityobject:dg1machinereadablezoneinformation:dg2encodedidentificationfeaturesface:dg3additionalidentificationfeaturefingers:dg4additionalidentificationfeatureirises:dg5displayedpo-4j37l","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"kind":"symbol","type":"topic","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithComHeaderAndDataGroupPresenceInformation:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"comHeaderAndDataGroupPresenceInformation"},{"text":" ","kind":"text"},{"text":"sodDocumentSecurityObject:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTNLds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sodDocumentSecurityObject"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg1MachineReadableZoneInformation:"},{"kind":"text","text":"("},{"text":"DOTNLds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":" *) "},{"text":"dg1MachineReadableZoneInformation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dg2EncodedIdentificationFeaturesFace:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dg2EncodedIdentificationFeaturesFace"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":" *) ","kind":"text"},{"text":"dg3AdditionalIdentificationFeatureFingers","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg4AdditionalIdentificationFeatureIrises:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dg5DisplayedPortrait:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dg5DisplayedPortrait"},{"text":" ","kind":"text"},{"text":"dg7DisplayedSignatureOrUsualMark:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile"},{"text":" *) ","kind":"text"},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dg8DataFeatures:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":" *) "},{"text":"dg8DataFeatures","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dg9StructureFeatures:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dg9StructureFeatures"},{"kind":"text","text":" "},{"text":"dg10SubstanceFeatures:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":" *) ","kind":"text"},{"text":"dg10SubstanceFeatures","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dg11AdditionalPersonalDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"DOTNLds1ElementaryFile"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dg11AdditionalPersonalDetails"},{"text":" ","kind":"text"},{"text":"dg12AdditionalDocumentDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":" *) "},{"text":"dg12AdditionalDocumentDetails","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg13OptionalDetails:"},{"text":"(","kind":"text"},{"text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dg13OptionalDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dg14SecurityOptions:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dg14SecurityOptions","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dg15ActiveAuthenticationPublicKeyInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dg16PersonsToNotify:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTNLds1ElementaryFile","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":" *) ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","value":"DOTNLds1ElementaryFile","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","op":"replace","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","value":"DOTNLds1eMrtdApplication"},{"value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments"},{"value":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}