{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init(maxEdgeLengthToImageShorterSideRatioThreshold:)"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/init(maxedgelengthtoimageshortersideratiothreshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/init(maxedgelengthtoimageshortersideratiothreshold:)"]}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"metadata":{"roleHeading":"Initializer","role":"symbol","symbolKind":"init","title":"init(maxEdgeLengthToImageShorterSideRatioThreshold:)","navigatorTitle":[{"text":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooLargeValidator(im)initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","type":"topic","abstract":[{"text":"Validate whether the size of the detected palm is too large.","type":"text"}],"kind":"symbol","title":"SizeTooLargeValidator","role":"symbol","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/init(maxEdgeLengthToImageShorterSideRatioThreshold:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"title":"init(maxEdgeLengthToImageShorterSideRatioThreshold:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init(maxEdgeLengthToImageShorterSideRatioThreshold:)","navigatorTitle":[{"text":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/init(maxedgelengthtoimageshortersideratiothreshold:)"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"title":"PalmAutoCaptureController","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","value":"DOTPSizeTooLargeValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/navigatorTitle","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1init(maxEdgeLengthToImageShorterSideRatioThreshold:)\/title","value":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1init(maxEdgeLengthToImageShorterSideRatioThreshold:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}