{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"kind":"symbol","metadata":{"symbolKind":"class","role":"symbol","title":"DotFacePassiveLivenessModuleConfiguration","modules":[{"name":"DotNfc"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration"]}],"abstract":[{"type":"text","text":"Face passive liveness module."}],"references":{"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration/init":{"title":"init","url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration\/init"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration":{"abstract":[{"text":"Face passive liveness module.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"title":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"role":"symbol","type":"topic"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFacePassiveLivenessModuleConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration\/init"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}