{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"sections":[],"abstract":[{"text":"NFC library configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotnfclibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotnfclibraryconfiguration"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","role":"symbol","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"title":"DotNfcLibraryConfiguration"},"references":{"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotNfcLibraryConfiguration":{"abstract":[{"type":"text","text":"NFC library configuration."}],"kind":"symbol","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotnfclibraryconfiguration","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","title":"DotNfcLibraryConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/DotNfcLibraryConfiguration/init":{"url":"\/documentation\/dotnfc\/dotnfclibraryconfiguration\/init","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration\/init","abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DotNfcLibraryConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}]},{"path":"\/topicSections","op":"add","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration\/init"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/title","op":"replace","value":"DotNfcLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}