{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTTd2MachineReadableZone) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"},"kind":"symbol","sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td2machinereadablezone"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/compositeCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfBirth","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfExpiry","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentCode","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/issuingStateOrOrganization","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/name","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/nationality","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/optionalData","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/sex"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","title":"Td2MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"role":"symbol","symbolKind":"class","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/issuingStateOrOrganization":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone\/issuingstateororganization","abstract":[],"navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/issuingStateOrOrganization","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"title":"issuingStateOrOrganization"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/documentNumber":{"url":"\/documentation\/dotnfc\/td2machinereadablezone\/documentnumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"title":"documentNumber","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentNumber"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"title":"Td2MachineReadableZone","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotnfc\/td2machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","kind":"symbol","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/documentCode":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone\/documentcode","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentCode","title":"documentCode"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/dateOfBirth":{"navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfBirth","kind":"symbol","abstract":[],"title":"dateOfBirth","role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone\/dateofbirth"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/td2machinereadablezone\/isequal(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/isEqual(_:)","title":"isEqual(_:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/sex":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/sex","navigatorTitle":[{"text":"sex","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone\/sex","abstract":[],"kind":"symbol","title":"sex","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/compositeCheckDigit":{"url":"\/documentation\/dotnfc\/td2machinereadablezone\/compositecheckdigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/compositeCheckDigit","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[],"title":"compositeCheckDigit","navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/optionalData":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"kind":"text","text":"?"}],"title":"optionalData","navigatorTitle":[{"kind":"identifier","text":"optionalData"}],"url":"\/documentation\/dotnfc\/td2machinereadablezone\/optionaldata","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/optionalData","abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/nationality":{"abstract":[],"navigatorTitle":[{"text":"nationality","kind":"identifier"}],"title":"nationality","type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone\/nationality","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/nationality","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/dateOfExpiry":{"url":"\/documentation\/dotnfc\/td2machinereadablezone\/dateofexpiry","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfExpiry","kind":"symbol","title":"dateOfExpiry","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"dateOfExpiry","kind":"identifier"}]},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/name":{"abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone\/name","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/name","type":"topic","title":"name"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/hash":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/hash","role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/description":{"title":"description","type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone\/description","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)":{"title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"optionalData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/compositeCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfBirth","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfExpiry","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentCode","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/issuingStateOrOrganization","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/name","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/nationality","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/optionalData","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/sex"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/isEqual(_:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTTd2MachineReadableZone","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"issuingStateOrOrganization","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1issuingStateOrOrganization\/title","op":"replace"},{"value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1issuingStateOrOrganization\/fragments","op":"replace"},{"value":"documentNumber","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentNumber\/title","op":"replace"},{"value":[{"kind":"identifier","text":"documentNumber"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentNumber\/fragments","op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/navigatorTitle","op":"replace"},{"value":"documentCode","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentCode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"documentCode"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentCode\/fragments","op":"replace"},{"value":"dateOfBirth","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfBirth\/title","op":"replace"},{"value":[{"text":"dateOfBirth","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfBirth\/fragments","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1isEqual(_:)\/fragments","op":"replace"},{"value":"sex","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1sex\/title","op":"replace"},{"value":[{"text":"sex","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1sex\/fragments","op":"replace"},{"value":"compositeCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1compositeCheckDigit\/title","op":"replace"},{"value":[{"text":"compositeCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1compositeCheckDigit\/fragments","op":"replace"},{"value":"optionalData","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1optionalData\/title","op":"replace"},{"value":[{"kind":"identifier","text":"optionalData"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1optionalData\/fragments","op":"replace"},{"value":"nationality","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1nationality\/title","op":"replace"},{"value":[{"text":"nationality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1nationality\/fragments","op":"replace"},{"value":"dateOfExpiry","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfExpiry\/title","op":"replace"},{"value":[{"text":"dateOfExpiry","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfExpiry\/fragments","op":"replace"},{"value":"name","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1name\/title","op":"replace"},{"value":[{"kind":"identifier","text":"name"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1name\/fragments","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1hash\/title","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1hash\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1description\/fragments","op":"replace"},{"value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/fragments","op":"replace"}]}]}