{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotface\/deinitialize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotface\/deinitialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/deinitialize()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method will deinitialize the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework and free up allocated memory asynchronously. This method will fire delegate callback after it will finish."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"deinitialize"}],"role":"symbol","title":"deinitialize()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DotFace(im)deinitialize","modules":[{"name":"DotFaceCore"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibrary instead."}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace/deinitialize()":{"deprecated":true,"role":"symbol","title":"deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method will deinitialize the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework and free up allocated memory asynchronously. This method will fire delegate callback after it will finish."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/deinitialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deinitialize"}],"url":"\/documentation\/dotfacecore\/dotface\/deinitialize()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace":{"deprecated":true,"role":"symbol","title":"DotFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFace"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFace"}],"url":"\/documentation\/dotfacecore\/dotface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"DotFaceCore is a part of DotFace framework group which provides components for the digital onboarding process using the latest Innovatrics IFace image processing library. It wraps the core functionality of IFace library to a higher-level module which is easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deinitialize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitialize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1deinitialize()\/title","value":"deinitialize"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitialize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/title","value":"DotFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/fragments","value":[{"kind":"identifier","text":"DotFace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}