{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceaspects"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceaspects"]}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/init(eyeDistanceToImageShorterSideRatio:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/eyeDistanceToImageShorterSideRatio"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFFaceAspects) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAspects"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"anchor":"Face-evaluation","title":"Face evaluation"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAspects"}],"title":"FaceAspects","role":"symbol","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"title":"Expression","kind":"symbol","type":"topic","abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","url":"\/documentation\/dotfacecore\/expression","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Expression"}],"navigatorTitle":[{"kind":"identifier","text":"Expression"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects/description":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/description","type":"topic","url":"\/documentation\/dotfacecore\/faceaspects\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects/eyeDistanceToImageShorterSideRatio":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeDistanceToImageShorterSideRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"eyeDistanceToImageShorterSideRatio"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/eyeDistanceToImageShorterSideRatio","abstract":[{"type":"text","text":"Eye distance ratio to image shorter side."}],"url":"\/documentation\/dotfacecore\/faceaspects\/eyedistancetoimageshortersideratio","title":"eyeDistanceToImageShorterSideRatio"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","url":"\/documentation\/dotfacecore\/glasses","kind":"symbol","type":"topic","title":"Glasses","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"abstract":[{"type":"text","text":"Face attribute for the glasses."}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","role":"symbol","title":"EyesExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpression"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}],"type":"topic","title":"EyesExpression","abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"url":"\/documentation\/dotfacecore\/eyesexpression","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"title":"FaceImageQualityQuery","abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"kind":"symbol","url":"\/documentation\/dotfacecore\/faceaspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","role":"symbol","title":"FaceAspects","type":"topic","abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","title":"FaceAttribute","role":"symbol","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"url":"\/documentation\/dotfacecore\/headposequery","title":"HeadPoseQuery","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseQuery"}],"kind":"symbol","abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HeadPoseQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQualityQuery"}],"type":"topic","abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"title":"FaceQualityQuery","kind":"symbol","url":"\/documentation\/dotfacecore\/facequalityquery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects/init(eyeDistanceToImageShorterSideRatio:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"eyeDistanceToImageShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceaspects\/init(eyedistancetoimageshortersideratio:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/init(eyeDistanceToImageShorterSideRatio:)","abstract":[],"type":"topic","title":"init(eyeDistanceToImageShorterSideRatio:)","navigatorTitle":[{"text":"initWithEyeDistanceToImageShorterSideRatio:","kind":"identifier"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"type":"topic","url":"\/documentation\/dotfacecore\/wearablesquery","title":"WearablesQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WearablesQuery"}],"abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"kind":"symbol","abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/faceimagequality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"type":"topic","title":"FaceImageQuality","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseAttribute"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","kind":"symbol","type":"topic","title":"HeadPoseAttribute","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}],"abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressionQuery"}],"title":"ExpressionQuery","url":"\/documentation\/dotfacecore\/expressionquery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"url":"\/documentation\/dotfacecore\/wearables","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"title":"Wearables","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Wearables"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"navigatorTitle":[{"kind":"identifier","text":"HeadPose"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}],"title":"HeadPose","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/headpose"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"role":"symbol","title":"FaceQuality","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceAspects"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/eyeDistanceToImageShorterSideRatio"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/init(eyeDistanceToImageShorterSideRatio:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"title":"Face evaluation","generated":true,"anchor":"Face-evaluation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceAspects","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"op":"replace","value":[{"text":"DOTFExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments"},{"op":"replace","value":[{"text":"DOTFExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1description\/fragments"},{"op":"replace","value":"eyeDistanceToImageShorterSideRatio","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1eyeDistanceToImageShorterSideRatio\/title"},{"op":"replace","value":[{"text":"eyeDistanceToImageShorterSideRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1eyeDistanceToImageShorterSideRatio\/fragments"},{"op":"replace","value":"DOTFGlasses","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGlasses"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGlasses"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/navigatorTitle"},{"op":"replace","value":"DOTFEyesExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title"},{"op":"replace","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/navigatorTitle"},{"op":"replace","value":"DOTFEyesExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title"},{"op":"replace","value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpression"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/navigatorTitle"},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/navigatorTitle"},{"op":"replace","value":"DOTFFaceAspects","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title"},{"op":"replace","value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/navigatorTitle"},{"op":"replace","value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle"},{"op":"replace","value":"DOTFHeadPoseQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"},{"op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/navigatorTitle"},{"op":"replace","value":"DOTFFaceQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/navigatorTitle"},{"op":"replace","value":"initWithEyeDistanceToImageShorterSideRatio:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1init(eyeDistanceToImageShorterSideRatio:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithEyeDistanceToImageShorterSideRatio:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1init(eyeDistanceToImageShorterSideRatio:)\/fragments"},{"op":"replace","value":"DOTFWearablesQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title"},{"op":"replace","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/navigatorTitle"},{"op":"replace","value":"DOTFFaceImageQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"op":"replace","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/navigatorTitle"},{"op":"replace","value":"DOTFHeadPoseAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"op":"replace","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"op":"replace","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/navigatorTitle"},{"op":"replace","value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title"},{"op":"replace","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/navigatorTitle"},{"op":"replace","value":"DOTFWearables","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFWearables"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFWearables"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/navigatorTitle"},{"op":"replace","value":"DOTFHeadPose","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title"},{"op":"replace","value":[{"text":"DOTFHeadPose","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/navigatorTitle"},{"op":"replace","value":"DOTFFaceQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle"}]}]}