{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceKeypoints) ","kind":"text"},{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"title":"FaceKeypoints","role":"symbol","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","roleHeading":"Class","modules":[{"name":"DotFaceCore"}]},"abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/chinTip","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeCenter","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeInnerCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeOuterCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyebrowInnerEnd","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyebrowOuterEnd","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthCenter","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLeftCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLowerEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthRightCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthUpperEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseBottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseLeftBottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseRightBottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseRoot","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseTip","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeCenter","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeInnerCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeOuterCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowInnerEnd","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowOuterEnd"],"generated":true,"anchor":"Instance-Properties"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facekeypoints"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facekeypoints"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEdge":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEdge","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEdge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","title":"leftEdge","role":"symbol","abstract":[{"text":"Left edge of the face.","type":"text"}],"navigatorTitle":[{"text":"leftEdge","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints\/leftedge"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)":{"url":"\/documentation\/dotfacecore\/facekeypoints\/init(righteyeoutercorner:righteyecenter:righteyeinnercorner:lefteyeinnercorner:lefteyecenter:lefteyeoutercorner:noseroot:noserightbottom:nosetip:noseleftbottom:nosebottom:mouthrightcorner:mouthcenter:mouthleftcorner:mouthupperedge:mouthlowe-7q6zy","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rightEyeOuterCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyeCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyeInnerCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyeInnerCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyeCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseRoot","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseRightBottom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseTip","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseLeftBottom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseBottom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthRightCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthLeftCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthUpperEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthLowerEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyebrowOuterEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyebrowInnerEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyebrowInnerEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyebrowOuterEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"chinTip","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?)","kind":"text"}],"title":"init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthLeftCorner":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthLeftCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","abstract":[{"text":"Left corner of the mouth.","type":"text"}],"navigatorTitle":[{"text":"mouthLeftCorner","kind":"identifier"}],"title":"mouthLeftCorner","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLeftCorner","url":"\/documentation\/dotfacecore\/facekeypoints\/mouthleftcorner"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyeInnerCorner":{"title":"rightEyeInnerCorner","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyeinnercorner","role":"symbol","abstract":[{"text":"Right eye inner corner.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeInnerCorner","navigatorTitle":[{"text":"rightEyeInnerCorner","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeInnerCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthCenter":{"title":"mouthCenter","navigatorTitle":[{"text":"mouthCenter","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/mouthcenter","type":"topic","abstract":[{"text":"Mouth center.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthCenter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthCenter"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthUpperEdge":{"role":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints\/mouthupperedge","type":"topic","kind":"symbol","title":"mouthUpperEdge","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthUpperEdge","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthUpperEdge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mouthUpperEdge"}],"abstract":[{"text":"Upper edge of the mouth.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyeCenter":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeCenter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeCenter","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyecenter","role":"symbol","navigatorTitle":[{"text":"rightEyeCenter","kind":"identifier"}],"title":"rightEyeCenter","abstract":[{"text":"Right eye center.","type":"text"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthLowerEdge":{"navigatorTitle":[{"text":"mouthLowerEdge","kind":"identifier"}],"title":"mouthLowerEdge","kind":"symbol","abstract":[{"text":"Lower edge of the mouth.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoints\/mouthloweredge","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLowerEdge","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthLowerEdge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEdge":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEdge","url":"\/documentation\/dotfacecore\/facekeypoints\/rightedge","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEdge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"title":"rightEdge","abstract":[{"text":"Right edge of the face.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"rightEdge","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/noseRoot":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseRoot","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"title":"noseRoot","url":"\/documentation\/dotfacecore\/facekeypoints\/noseroot","role":"symbol","abstract":[{"text":"Nose root.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseRoot","type":"topic","kind":"symbol","navigatorTitle":[{"text":"noseRoot","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/noseRightBottom":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseRightBottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseRightBottom","url":"\/documentation\/dotfacecore\/facekeypoints\/noserightbottom","role":"symbol","navigatorTitle":[{"text":"noseRightBottom","kind":"identifier"}],"title":"noseRightBottom","abstract":[{"text":"Right bottom nose.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyebrowInnerEnd":{"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyebrowInnerEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowInnerEnd","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyebrowinnerend","title":"rightEyebrowInnerEnd","navigatorTitle":[{"text":"rightEyebrowInnerEnd","kind":"identifier"}],"abstract":[{"text":"Right eyebrow inner end.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEyebrowInnerEnd":{"role":"symbol","title":"leftEyebrowInnerEnd","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyebrowInnerEnd","kind":"symbol","navigatorTitle":[{"text":"leftEyebrowInnerEnd","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyebrowInnerEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Left eyebrow inner end.","type":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/lefteyebrowinnerend"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthRightCorner":{"title":"mouthRightCorner","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthRightCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/mouthrightcorner","navigatorTitle":[{"text":"mouthRightCorner","kind":"identifier"}],"abstract":[{"text":"Right corner of the mouth.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthRightCorner"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEyeCenter":{"navigatorTitle":[{"text":"leftEyeCenter","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/lefteyecenter","type":"topic","title":"leftEyeCenter","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeCenter","abstract":[{"text":"Left eye center.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeCenter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","url":"\/documentation\/dotfacecore\/facekeypoints","role":"symbol","abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"title":"FaceKeypoints","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoints"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoints"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyeOuterCorner":{"abstract":[{"text":"Right eye outer corner.","type":"text"}],"title":"rightEyeOuterCorner","role":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyeoutercorner","navigatorTitle":[{"text":"rightEyeOuterCorner","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeOuterCorner","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeOuterCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/chinTip":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/chinTip","title":"chinTip","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chinTip","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/chintip","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"chinTip","kind":"identifier"}],"abstract":[{"text":"Chin tip.","type":"text"}]},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/noseBottom":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseBottom","navigatorTitle":[{"text":"noseBottom","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseBottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoints\/nosebottom","kind":"symbol","role":"symbol","title":"noseBottom","abstract":[{"text":"Bottom nose.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEyeInnerCorner":{"abstract":[{"text":"Left eye inner corner.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeInnerCorner","role":"symbol","title":"leftEyeInnerCorner","navigatorTitle":[{"text":"leftEyeInnerCorner","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/lefteyeinnercorner","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeInnerCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/description","url":"\/documentation\/dotfacecore\/facekeypoints\/description","type":"topic","title":"description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEyeOuterCorner":{"abstract":[{"text":"Left eye outer corner.","type":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/lefteyeoutercorner","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"leftEyeOuterCorner","kind":"identifier"}],"title":"leftEyeOuterCorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeOuterCorner","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyebrowOuterEnd":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowOuterEnd","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyebrowOuterEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/righteyebrowouterend","role":"symbol","navigatorTitle":[{"text":"rightEyebrowOuterEnd","kind":"identifier"}],"abstract":[{"text":"Right eyebrow outer end.","type":"text"}],"kind":"symbol","title":"rightEyebrowOuterEnd"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/noseLeftBottom":{"abstract":[{"text":"Left bottom nose.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints\/noseleftbottom","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseLeftBottom","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseLeftBottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"noseLeftBottom","kind":"identifier"}],"role":"symbol","title":"noseLeftBottom"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEyebrowOuterEnd":{"navigatorTitle":[{"text":"leftEyebrowOuterEnd","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyebrowOuterEnd","abstract":[{"text":"Left eyebrow outer end.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyebrowOuterEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"role":"symbol","title":"leftEyebrowOuterEnd","url":"\/documentation\/dotfacecore\/facekeypoints\/lefteyebrowouterend"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/noseTip":{"role":"symbol","navigatorTitle":[{"text":"noseTip","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseTip","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"text":"Nose tip.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseTip","url":"\/documentation\/dotfacecore\/facekeypoints\/nosetip","title":"noseTip"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFFaceKeypoints","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/chinTip","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeCenter","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeInnerCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeOuterCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyebrowInnerEnd","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyebrowOuterEnd","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthCenter","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLeftCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthLowerEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthRightCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthUpperEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseBottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseLeftBottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseRightBottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseRoot","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseTip","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEdge","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeCenter","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeInnerCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeOuterCorner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowInnerEnd","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowOuterEnd"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFFaceKeypoints"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"leftEdge","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEdge\/title","op":"replace"},{"value":[{"text":"leftEdge","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEdge\/fragments","op":"replace"},{"value":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)\/fragments","op":"replace"},{"value":"mouthLeftCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthLeftCorner\/title","op":"replace"},{"value":[{"text":"mouthLeftCorner","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthLeftCorner\/fragments","op":"replace"},{"value":"rightEyeInnerCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeInnerCorner\/title","op":"replace"},{"value":[{"text":"rightEyeInnerCorner","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeInnerCorner\/fragments","op":"replace"},{"value":"mouthCenter","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthCenter\/title","op":"replace"},{"value":[{"kind":"identifier","text":"mouthCenter"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthCenter\/fragments","op":"replace"},{"value":"mouthUpperEdge","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthUpperEdge\/title","op":"replace"},{"value":[{"text":"mouthUpperEdge","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthUpperEdge\/fragments","op":"replace"},{"value":"rightEyeCenter","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeCenter\/title","op":"replace"},{"value":[{"text":"rightEyeCenter","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeCenter\/fragments","op":"replace"},{"value":"mouthLowerEdge","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthLowerEdge\/title","op":"replace"},{"value":[{"kind":"identifier","text":"mouthLowerEdge"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthLowerEdge\/fragments","op":"replace"},{"value":"rightEdge","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEdge\/title","op":"replace"},{"value":[{"text":"rightEdge","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEdge\/fragments","op":"replace"},{"value":"noseRoot","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseRoot\/title","op":"replace"},{"value":[{"text":"noseRoot","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseRoot\/fragments","op":"replace"},{"value":"noseRightBottom","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseRightBottom\/title","op":"replace"},{"value":[{"kind":"identifier","text":"noseRightBottom"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseRightBottom\/fragments","op":"replace"},{"value":"rightEyebrowInnerEnd","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyebrowInnerEnd\/title","op":"replace"},{"value":[{"text":"rightEyebrowInnerEnd","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyebrowInnerEnd\/fragments","op":"replace"},{"value":"leftEyebrowInnerEnd","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyebrowInnerEnd\/title","op":"replace"},{"value":[{"text":"leftEyebrowInnerEnd","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyebrowInnerEnd\/fragments","op":"replace"},{"value":"mouthRightCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthRightCorner\/title","op":"replace"},{"value":[{"text":"mouthRightCorner","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthRightCorner\/fragments","op":"replace"},{"value":"leftEyeCenter","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeCenter\/title","op":"replace"},{"value":[{"text":"leftEyeCenter","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeCenter\/fragments","op":"replace"},{"value":"DOTFFaceKeypoints","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","op":"replace"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle","op":"replace"},{"value":"rightEyeOuterCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeOuterCorner\/title","op":"replace"},{"value":[{"kind":"identifier","text":"rightEyeOuterCorner"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeOuterCorner\/fragments","op":"replace"},{"value":"chinTip","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1chinTip\/title","op":"replace"},{"value":[{"text":"chinTip","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1chinTip\/fragments","op":"replace"},{"value":"noseBottom","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseBottom\/title","op":"replace"},{"value":[{"kind":"identifier","text":"noseBottom"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseBottom\/fragments","op":"replace"},{"value":"leftEyeInnerCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeInnerCorner\/title","op":"replace"},{"value":[{"text":"leftEyeInnerCorner","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeInnerCorner\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1description\/fragments","op":"replace"},{"value":"leftEyeOuterCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeOuterCorner\/title","op":"replace"},{"value":[{"text":"leftEyeOuterCorner","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeOuterCorner\/fragments","op":"replace"},{"value":"rightEyebrowOuterEnd","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyebrowOuterEnd\/title","op":"replace"},{"value":[{"text":"rightEyebrowOuterEnd","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyebrowOuterEnd\/fragments","op":"replace"},{"value":"noseLeftBottom","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseLeftBottom\/title","op":"replace"},{"value":[{"text":"noseLeftBottom","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseLeftBottom\/fragments","op":"replace"},{"value":"leftEyebrowOuterEnd","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyebrowOuterEnd\/title","op":"replace"},{"value":[{"kind":"identifier","text":"leftEyebrowOuterEnd"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyebrowOuterEnd\/fragments","op":"replace"},{"value":"noseTip","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseTip\/title","op":"replace"},{"value":[{"kind":"identifier","text":"noseTip"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseTip\/fragments","op":"replace"}]}]}