{"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery(py)evaluateShadow","title":"evaluateShadow","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateShadow"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"evaluateShadow","kind":"identifier"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Shadow evaluation flag."}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateShadow","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateShadow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateshadow"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateshadow"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"url":"\/documentation\/dotfacecore\/faceimagequalityquery","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","title":"FaceImageQualityQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"role":"symbol","abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.9.0","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateShadow":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateShadow","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateshadow","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"evaluateShadow","kind":"identifier"}],"abstract":[{"text":"Shadow evaluation flag.","type":"text"}],"title":"evaluateShadow","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateShadow"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"evaluateShadow","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"evaluateShadow","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateShadow"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateShadow\/title","value":"evaluateShadow"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateShadow\/fragments","value":[{"text":"evaluateShadow","kind":"identifier"}]}]}]}