{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/transformation","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","role":"symbol","symbolKind":"case","modules":[{"name":"DotPalmCore"}],"title":"DotFingersModuleId.transformation","externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdTransformation","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfingersmoduleid\/transformation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfingersmoduleid\/transformation"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId":{"role":"symbol","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingersmoduleid","abstract":[{"type":"codeVoice","code":"DotFingers"},{"text":" feature module identifier.","type":"text"}],"kind":"symbol","title":"DotFingersModuleId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/transformation":{"title":"DotFingersModuleId.transformation","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/transformation","navigatorTitle":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/transformation","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DotFingersModuleIdTransformation","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace"},{"op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1transformation\/title","value":"DotFingersModuleIdTransformation","op":"replace"},{"op":"replace","value":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1transformation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}