{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","text":"PlaceholderType","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/type","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Placeholder type. Default is "},{"code":".circle","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/dotfacelite\/placeholder\/visible\/type"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"type","externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC4typeAA0D4TypeOvp","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","text":"PlaceholderType"}],"symbolKind":"property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType":{"url":"\/documentation\/dotfacelite\/placeholdertype","title":"PlaceholderType","abstract":[{"type":"text","text":"Type of placeholder."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible":{"title":"Placeholder.Visible","navigatorTitle":[{"text":"Visible","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Visible placeholder."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/placeholder\/visible"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible/type":{"url":"\/documentation\/dotfacelite\/placeholder\/visible\/type","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/type","kind":"symbol","abstract":[{"text":"Placeholder type. Default is ","type":"text"},{"type":"codeVoice","code":".circle"},{"text":".","type":"text"}],"title":"type","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","text":"PlaceholderType"}]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"url":"\/documentation\/dotfacelite\/placeholder","abstract":[{"type":"text","text":"Placeholder."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"title":"Placeholder","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPlaceholderType","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPlaceholderType"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPlaceholderType"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/navigatorTitle","op":"replace"},{"value":"DOTPlaceholder","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title","op":"replace"},{"value":[{"text":"DOTPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","op":"replace"},{"value":[{"text":"DOTPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle","op":"replace"}]}]}