{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentDetector","text":"DocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC","text":"Result"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/init(documentdetectorresult:validatoridentifiers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/init(documentdetectorresult:validatoridentifiers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/init(documentDetectorResult:validatorIdentifiers:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"title":"init(documentDetectorResult:validatorIdentifiers:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureDetection(im)initWithDocumentDetectorResult:validatorIdentifiers:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentDetectorResult:validatorIdentifiers:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection":{"role":"symbol","title":"DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection/init(documentDetectorResult:validatorIdentifiers:)":{"role":"symbol","title":"init(documentDetectorResult:validatorIdentifiers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/init(documentDetectorResult:validatorIdentifiers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentDetectorResult:validatorIdentifiers:"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection\/init(documentdetectorresult:validatoridentifiers:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDocumentDetectorResult":{"role":"symbol","title":"DOTDocumentDetectorResult","fragments":[{"kind":"identifier","text":"DOTDocumentDetectorResult"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDocumentDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdocumentdetectorresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result":{"role":"symbol","title":"DocumentDetector.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/documentdetector\/result"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocumentDetectorResult:validatorIdentifiers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentDetectorResult:validatorIdentifiers:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocumentDetectorResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDocumentDetectorResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentDetectorResult","text":"DOTDocumentDetectorResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"documentDetectorResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"validatorIdentifiers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"validatorIdentifiers"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDocumentAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1init(documentDetectorResult:validatorIdentifiers:)\/title","value":"initWithDocumentDetectorResult:validatorIdentifiers:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1init(documentDetectorResult:validatorIdentifiers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentDetectorResult:validatorIdentifiers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}