{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DotDocument"}],"title":"RawRepresentable Implementations","role":"collectionGroup","roleHeading":"API Collection"},"variants":[{"paths":["\/documentation\/dotdocument\/camerapreviewscaletype\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType"]]},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType\/hashValue"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType\/hash(into:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"title":"CameraPreviewScaleType","type":"topic","url":"\/documentation\/dotdocument\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"kind":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType/hash(into:)":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype\/hash(into:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType\/hash(into:)","role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"kind":"symbol","title":"hash(into:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType/hashValue":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"hashValue","url":"\/documentation\/dotdocument\/camerapreviewscaletype\/hashvalue","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType\/hashValue","abstract":[],"type":"topic","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}