{"variants":[{"paths":["\/documentation\/dotpalmcore\/tiltangles\/pitch"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/tiltangles\/pitch"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees."}],"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"pitch","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"pitch","kind":"identifier"}],"externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(py)pitch"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles\/pitch","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/TiltAngles/pitch":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles\/pitch","url":"\/documentation\/dotpalmcore\/tiltangles\/pitch","role":"symbol","title":"pitch","abstract":[{"text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pitch","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/TiltAngles":{"type":"topic","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"text":"Also see ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/tiltangles","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"title":"TiltAngles","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"title":"Sensor Coordinate System"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pitch","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"pitch","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pitch"}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles~1pitch\/title","value":"pitch","op":"replace"},{"value":[{"text":"pitch","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles~1pitch\/fragments","op":"replace"},{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles\/title"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles\/fragments"}]}]}