{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults\/minvalidsamplesinrowtostartcandidateselection"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV45minValidSamplesInRowToStartCandidateSelectionSivpZ","title":"minValidSamplesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property"},"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing document images with customizable UI.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"title":"BaseDocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/Defaults":{"abstract":[],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults","title":"BaseDocumentAutoCaptureViewController.Configuration.Defaults","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"title":"BaseDocumentAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/Defaults/minValidSamplesInRowToStartCandidateSelection":{"title":"minValidSamplesInRowToStartCandidateSelection","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults\/minvalidsamplesinrowtostartcandidateselection","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","value":"DOTDBaseDocumentAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}