{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"rawLines","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"machineReadableZone","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/init(rawLines:machineReadableZone:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawLines","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"machineReadableZone"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithRawLines:machineReadableZone:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(rawLines:machineReadableZone:)","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult(im)initWithRawLines:machineReadableZone:","role":"symbol"},"variants":[{"paths":["\/documentation\/dotdocument\/mrzrecognitionresult\/init(rawlines:machinereadablezone:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzrecognitionresult\/init(rawlines:machinereadablezone:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult":{"abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}],"title":"MrzRecognitionResult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzRecognitionResult"}],"navigatorTitle":[{"kind":"identifier","text":"MrzRecognitionResult"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","url":"\/documentation\/dotdocument\/mrzrecognitionresult","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","title":"MachineReadableZone","type":"topic","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"url":"\/documentation\/dotdocument\/machinereadablezone","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.7.1","type":"text"}],"type":"topic","role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult/init(rawLines:machineReadableZone:)":{"url":"\/documentation\/dotdocument\/mrzrecognitionresult\/init(rawlines:machinereadablezone:)","title":"init(rawLines:machineReadableZone:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rawLines","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"machineReadableZone"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithRawLines:machineReadableZone:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/init(rawLines:machineReadableZone:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithRawLines:machineReadableZone:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithRawLines:machineReadableZone:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithRawLines:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rawLines"},{"text":" ","kind":"text"},{"kind":"identifier","text":"machineReadableZone:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTMachineReadableZone","text":"DOTMachineReadableZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"machineReadableZone"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","value":"DOTDMrzRecognitionResult","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzRecognitionResult"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1init(rawLines:machineReadableZone:)\/title","value":"initWithRawLines:machineReadableZone:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithRawLines:machineReadableZone:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1init(rawLines:machineReadableZone:)\/fragments"}]}]}