{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(faceLiteAutoCaptureViewControllerViewWillTransition:) ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillTransition"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillTransition(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"faceAutoCaptureViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureViewControllerDelegate(im)faceLiteAutoCaptureViewControllerViewWillTransition:","symbolKind":"method","title":"faceAutoCaptureViewControllerViewWillTransition(_:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"faceLiteAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilltransition(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilltransition(_:)"]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate","kind":"symbol","title":"FaceAutoCaptureViewControllerDelegate","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate","abstract":[{"text":"Implement this delegate to handle the face auto capture events.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewWillTransition(_:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillTransition(_:)","kind":"symbol","title":"faceAutoCaptureViewControllerViewWillTransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"faceLiteAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilltransition(_:)","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceLiteAutoCaptureViewControllerViewWillTransition:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"faceLiteAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerViewWillTransition:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","text":"DOTFLFaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFLFaceAutoCaptureViewControllerDelegate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewControllerDelegate"}]},{"value":"DOTFLFaceAutoCaptureViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillTransition(_:)\/title","value":"faceLiteAutoCaptureViewControllerViewWillTransition:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillTransition(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"faceLiteAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}