{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:processed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:processed:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"processed","kind":"externalParam"},{"kind":"text","text":" "},{"text":"detection","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","kind":"typeIdentifier","text":"DocumentAutoCaptureDetection"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate(im)documentAutoCaptureViewController:processed:","roleHeading":"Instance Method","title":"documentAutoCaptureViewController(_:processed:)","navigatorTitle":[{"text":"documentAutoCaptureViewController:processed:","kind":"identifier"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","text":"DocumentAutoCaptureViewController"},{"kind":"text","text":", "},{"text":"processed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"DotDocument"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:processed:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Tells the delegate that the new detection was processed.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"title":"DocumentAutoCaptureDetection","abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"navigatorTitle":[{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturedetection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","type":"topic","kind":"symbol","title":"DocumentAutoCaptureViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewController(_:processed:)":{"title":"documentAutoCaptureViewController(_:processed:)","navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureViewController:processed:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:processed:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:processed:)","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"abstract":[{"text":"Implement this delegate to handle the document auto capture events.","type":"text"}],"role":"symbol","title":"DocumentAutoCaptureViewControllerDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.7.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"documentAutoCaptureViewController:processed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"documentAutoCaptureViewController:processed:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewController:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","text":"DOTDDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"processed:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTDDocumentAutoCaptureDetection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"DOTDDocumentAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:processed:)\/title","value":"documentAutoCaptureViewController:processed:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewController:processed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:processed:)\/fragments"},{"value":"DOTDDocumentAutoCaptureViewControllerDelegate","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments"}]}]}