{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]]},"metadata":{"externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate(im)documentAutoCaptureViewControllerViewDidDisappear:","roleHeading":"Instance Method","symbolKind":"method","required":true,"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"title":"documentAutoCaptureViewControllerViewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentAutoCaptureViewControllerViewDidDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"DocumentAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},{"text":")","kind":"text"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidDisappear(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentAutoCaptureViewControllerViewDidDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","text":"DocumentAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdiddisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdiddisappear(_:)"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewDidDisappear(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","text":"DocumentAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidDisappear:"}],"title":"documentAutoCaptureViewControllerViewDidDisappear(_:)","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdiddisappear(_:)","kind":"symbol","required":true,"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidDisappear(_:)","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"title":"DocumentAutoCaptureViewControllerDelegate","navigatorTitle":[{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.1.0"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"title":"DocumentAutoCaptureViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"documentAutoCaptureViewControllerViewDidDisappear:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"documentAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidDisappear:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","text":"DOTDDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidDisappear(_:)\/title","value":"documentAutoCaptureViewControllerViewDidDisappear:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"documentAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title","value":"DOTDDocumentAutoCaptureViewControllerDelegate"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]}]}]}