{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"documentAutoCaptureViewControllerViewDidLoad(_:)","modules":[{"name":"DotDocument"}],"symbolKind":"method","externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate(im)documentAutoCaptureViewControllerViewDidLoad:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidLoad:","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLoad(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidload(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidload(_:)"]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","title":"DocumentAutoCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewDidLoad(_:)":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidload(_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLoad(_:)","title":"documentAutoCaptureViewControllerViewDidLoad(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidLoad:","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","title":"BaseDocumentAutoCaptureViewController","kind":"symbol","abstract":[{"text":"UI component for capturing document images with customizable UI.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"documentAutoCaptureViewControllerViewDidLoad:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLoad:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLoad:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTDBaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDDocumentAutoCaptureViewControllerDelegate","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/navigatorTitle"},{"op":"replace","value":"documentAutoCaptureViewControllerViewDidLoad:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidLoad(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLoad:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidLoad(_:)\/fragments"},{"op":"replace","value":"DOTDBaseDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle"}]}]}