{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:uiStateUpdated:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Tells the delegate that the UI state was updated."}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:uistateupdated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:uistateupdated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureViewController:uiStateUpdated:"}],"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"documentAutoCaptureViewController(_:uiStateUpdated:)","externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate(im)documentAutoCaptureViewController:uiStateUpdated:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseDocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiStateUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureUiState","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiState"},{"kind":"text","text":")"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiStateUpdated"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uiState"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiState","text":"DocumentAutoCaptureUiState"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate","title":"DocumentAutoCaptureUiState","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing document images with customizable UI.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"title":"BaseDocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewController(_:uiStateUpdated:)":{"role":"symbol","type":"topic","kind":"symbol","title":"documentAutoCaptureViewController(_:uiStateUpdated:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:uiStateUpdated:)","abstract":[{"text":"Tells the delegate that the UI state was updated.","type":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:uistateupdated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiState"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","abstract":[{"text":"UI Document Auto Capture component","type":"text"},{"text":" ","type":"text"},{"text":"A visual component for capturing good quality document images suitable for optical character recognition. This component provides an UI.","type":"text"},{"text":" ","type":"text"},{"text":"It includes a placeholder for the document, a detection layer that displays the tracking rectangle and an instruction.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","title":"DocumentAutoCaptureViewController","kind":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","title":"DocumentAutoCaptureViewControllerDelegate","abstract":[{"text":"Implement this delegate to handle the document auto capture events.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"documentAutoCaptureViewController:uiStateUpdated:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentAutoCaptureViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","text":"DOTDBaseDocumentAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiStateUpdated:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiState","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureUiState"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uiState"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle"},{"value":"DOTDBaseDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title"},{"value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle"},{"value":"documentAutoCaptureViewController:uiStateUpdated:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:uiStateUpdated:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:uiStateUpdated:)\/fragments"},{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/navigatorTitle"},{"value":"DOTDDocumentAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}