{"metadata":{"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotDocument"}],"title":"documentAutoCaptureViewControllerViewDidAppear(_:)","externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate(im)documentAutoCaptureViewControllerViewDidAppear:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidAppear(_:)"},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidAppear"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewDidAppear(_:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidAppear:"}],"title":"documentAutoCaptureViewControllerViewDidAppear(_:)","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidappear(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidAppear"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","kind":"typeIdentifier","text":"DocumentAutoCaptureViewController"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidAppear(_:)","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"title":"DocumentAutoCaptureViewController"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"title":"DocumentAutoCaptureViewControllerDelegate","navigatorTitle":[{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.1.0"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"documentAutoCaptureViewControllerViewDidAppear:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"documentAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidAppear:"},{"kind":"text","text":"("},{"text":"DOTDDocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidAppear(_:)\/title","value":"documentAutoCaptureViewControllerViewDidAppear:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title","value":"DOTDDocumentAutoCaptureViewControllerDelegate","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewControllerDelegate"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments"}]}]}