{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewwillappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewwillappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillAppear(_:)"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"title":"documentAutoCaptureViewControllerViewWillAppear(_:)","required":true,"externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate(im)documentAutoCaptureViewControllerViewWillAppear:","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureViewControllerViewWillAppear:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewWillAppear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewWillAppear"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewWillAppear(_:)":{"required":true,"type":"topic","title":"documentAutoCaptureViewControllerViewWillAppear(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillAppear","kind":"identifier"},{"kind":"text","text":"("},{"text":"DocumentAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewwillappear(_:)","role":"symbol","navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewWillAppear:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillAppear(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","type":"topic","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","kind":"symbol","title":"DocumentAutoCaptureViewControllerDelegate","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"documentAutoCaptureViewControllerViewWillAppear:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewWillAppear:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillAppear(_:)\/title","value":"documentAutoCaptureViewControllerViewWillAppear:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillAppear:","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title","value":"DOTDDocumentAutoCaptureViewControllerDelegate"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}