{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules\/initWithDetection:"},"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(im)initWithDetection:","title":"initWithDetection:","navigatorTitle":[{"text":"initWithDetection:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules\/initwithdetection:"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotfingerscore\/dotpalmdetectionmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration","title":"DotPalmDetectionModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Palm detection module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfigurationModules/initWithDetection:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:"}],"navigatorTitle":[{"text":"initWithDetection:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules\/initwithdetection:","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules\/initWithDetection:","title":"initWithDetection:","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules","title":"DotPalmLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}