{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"]]},"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooLargeValidator(py)maxEdgeLengthToImageShorterSideRatioThreshold","title":"maxEdgeLengthToImageShorterSideRatioThreshold","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxEdgeLengthToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/maxedgelengthtoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/maxedgelengthtoimageshortersideratiothreshold"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/maxEdgeLengthToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"abstract":[{"text":"Current maximal edge length to image shorter side ratio threshold.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","abstract":[{"text":"Validate whether the size of the detected palm is too large.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","title":"SizeTooLargeValidator","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"text":"version: 8.6.1","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/maxEdgeLengthToImageShorterSideRatioThreshold":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/maxedgelengthtoimageshortersideratiothreshold","abstract":[{"text":"Current maximal edge length to image shorter side ratio threshold.","type":"text"}],"title":"maxEdgeLengthToImageShorterSideRatioThreshold","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/maxEdgeLengthToImageShorterSideRatioThreshold","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxEdgeLengthToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","navigatorTitle":[{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"kind":"symbol","title":"PalmAutoCaptureController","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"maxEdgeLengthToImageShorterSideRatioThreshold","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxEdgeLengthToImageShorterSideRatioThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxEdgeLengthToImageShorterSideRatioThreshold"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","op":"replace","value":"DOTPSizeTooLargeValidator"},{"value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1maxEdgeLengthToImageShorterSideRatioThreshold\/title","value":"maxEdgeLengthToImageShorterSideRatioThreshold","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1maxEdgeLengthToImageShorterSideRatioThreshold\/fragments","value":[{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}]},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]}]}]}