{"metadata":{"title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"generated":true,"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/!=(_:_:)"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturephase\/equatable-implementations"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCapturePhase"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCapturePhase"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"type":"text","text":"Phase of the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","title":"FingersAutoCapturePhase","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/!=(_:_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","value":"DOTFGFingersAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title","value":"DOTFGFingersAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]}]}]}