{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/rectangledouble\/height"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/rectangledouble\/height"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/height"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(py)height","modules":[{"relatedModules":["DotCore"],"name":"DotFaceLite"}],"title":"height","extendedModule":"DotCore","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble/height":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"height","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/height","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/height","type":"topic","title":"height","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"url":"\/documentation\/dotfacelite\/facedetector","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"title":"FaceDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"url":"\/documentation\/dotfacelite\/rectangledouble","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.13.0","type":"text"}],"type":"topic","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"height","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"height","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1height\/title","value":"height"},{"value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1height\/fragments","op":"replace"},{"op":"replace","value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","op":"replace"}]}]}