{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/intervalfloat\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/intervalfloat\/hash"]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(py)hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"hash","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"symbolKind":"property","modules":[{"name":"DotDocument"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/hash","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/IntervalFloat":{"title":"IntervalFloat","url":"\/documentation\/dotdocument\/intervalfloat","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/IntervalFloat/hash":{"type":"topic","url":"\/documentation\/dotdocument\/intervalfloat\/hash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","title":"hash","abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat~1hash\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"}]}]}