{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"]]},"metadata":{"extendedModule":"DotCore","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"modules":[{"relatedModules":["DotCore"],"name":"DotPalmCore"}],"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(im)mirrored","title":"mirrored()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/rectangledouble\/mirrored()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/rectangledouble\/mirrored()"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/mirrored()"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/mirrored()":{"kind":"symbol","title":"mirrored()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"url":"\/documentation\/dotpalmcore\/rectangledouble\/mirrored()","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/mirrored()"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"title":"PalmDetector","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"url":"\/documentation\/dotpalmcore\/palmdetector","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"type":"topic","title":"RectangleDouble","url":"\/documentation\/dotpalmcore\/rectangledouble","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mirrored"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1mirrored()\/title","op":"replace","value":"mirrored"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1mirrored()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}]},{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle"}]}]}