{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"externalID":"c:@CM@DotCore@objc(cs)DOTPointDouble(im)rebasedWithParentRectangle:","symbolKind":"method","title":"rebased(parentRectangle:)","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"extendedModule":"DotCore","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/rebased(parentRectangle:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","text":"PointDouble"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointdouble\/rebased(parentrectangle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/pointdouble\/rebased(parentrectangle:)"]}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/PointDouble":{"url":"\/documentation\/dotnfc\/pointdouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"title":"PointDouble"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol","title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","type":"topic","url":"\/documentation\/dotnfc\/rectangledouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}]},"doc://DotNfc/documentation/DotNfc/PointDouble/rebased(parentRectangle:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"title":"rebased(parentRectangle:)","type":"topic","url":"\/documentation\/dotnfc\/pointdouble\/rebased(parentrectangle:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/rebased(parentRectangle:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rebasedWithParentRectangle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rebasedWithParentRectangle:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentRectangle"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1rebased(parentRectangle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}