{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturestyle\/defaults"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/backgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/detectionLayerColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionBackgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionCandidateSelectionBackgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionCandidateSelectionTextColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionFont","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionTextColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/overlayColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/placeholderCandidateSelectionColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/placeholderColor"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"title":"FaceAutoCaptureStyle.Defaults","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:11DotFaceLite0B16AutoCaptureStyleC8DefaultsV","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/instructionCandidateSelectionTextColor":{"role":"symbol","title":"instructionCandidateSelectionTextColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionCandidateSelectionTextColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/instructioncandidateselectiontextcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/instructionTextColor":{"role":"symbol","title":"instructionTextColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionTextColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/instructiontextcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/instructionBackgroundColor":{"role":"symbol","title":"instructionBackgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionBackgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/instructionbackgroundcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle":{"role":"symbol","title":"FaceAutoCaptureStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureStyle"}],"abstract":[{"type":"text","text":"Customization options for the face auto capture user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureStyle"}],"url":"\/documentation\/dotfacelite\/faceautocapturestyle"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/backgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/backgroundcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/instructionCandidateSelectionBackgroundColor":{"role":"symbol","title":"instructionCandidateSelectionBackgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionCandidateSelectionBackgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/instructioncandidateselectionbackgroundcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/instructionFont":{"role":"symbol","title":"instructionFont","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/instructionFont","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/instructionfont"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/detectionLayerColor":{"role":"symbol","title":"detectionLayerColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/detectionLayerColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/detectionlayercolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/overlayColor":{"role":"symbol","title":"overlayColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/overlayColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/overlaycolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 7.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults":{"role":"symbol","title":"FaceAutoCaptureStyle.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/placeholderCandidateSelectionColor":{"role":"symbol","title":"placeholderCandidateSelectionColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/placeholderCandidateSelectionColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/placeholdercandidateselectioncolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureStyle/Defaults/placeholderColor":{"role":"symbol","title":"placeholderColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureStyle\/Defaults\/placeholderColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturestyle\/defaults\/placeholdercolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureStyle\/title","value":"DOTFLFaceAutoCaptureStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureStyle\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}