{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration\/init","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacebackgrounduniformitymoduleconfiguration\/init"]}],"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration(im)init","symbolKind":"method"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DotFaceBackgroundUniformityModuleConfiguration/init":{"abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration\/init","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacebackgrounduniformitymoduleconfiguration\/init","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceBackgroundUniformityModuleConfiguration":{"url":"\/documentation\/dotdocument\/dotfacebackgrounduniformitymoduleconfiguration","title":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Face background uniformity module."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"}]}]}