{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/read(bgraRawImage:document:travelDocumentType:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"},{"text":", ","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"kind":"text","text":"."},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result","text":"Result"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"text":"Image to perform the MRZ reading on.","type":"text"}]}]},{"name":"document","content":[{"type":"paragraph","inlineContent":[{"text":"Detection result for the document present in the image.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Specify travel document type to improve MRZ reading accuracy. If travel document type is unknown, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"travelDocumentType"}]},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of MRZ reading."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader\/read(bgrarawimage:document:traveldocumenttype:)"]},{"paths":["\/documentation\/dotdocument\/mrzreader\/read(bgrarawimage:document:traveldocumenttype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Read MRZ in an image and return the result."}],"sections":[],"metadata":{"title":"read(bgraRawImage:document:travelDocumentType:)","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzReader(im)readWithBgraRawImage:document:travelDocumentType:","navigatorTitle":[{"kind":"identifier","text":"readWithBgraRawImage:document:travelDocumentType:"}],"role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"read","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":", ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC","text":"Result","kind":"typeIdentifier"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotdocument\/bgrarawimage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","abstract":[{"text":"Result of the document detection process.","type":"text"}],"role":"symbol","title":"DOTDDocumentDetectorDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}]},"doc://DotDocument/documentation/DotDocument/MrzReader/read(bgraRawImage:document:travelDocumentType:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":", "},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC","kind":"typeIdentifier","text":"Result"}],"navigatorTitle":[{"kind":"identifier","text":"readWithBgraRawImage:document:travelDocumentType:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/read(bgraRawImage:document:travelDocumentType:)","role":"symbol","type":"topic","title":"read(bgraRawImage:document:travelDocumentType:)","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/read(bgrarawimage:document:traveldocumenttype:)","abstract":[{"type":"text","text":"Read MRZ in an image and return the result."}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","title":"TravelDocumentTypeWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"TravelDocumentType"},{"text":" for Objective-C support.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper"},"doc://DotDocument/documentation/DotDocument/DOTDMrzReaderResult":{"url":"\/documentation\/dotdocument\/dotdmrzreaderresult","abstract":[{"type":"text","text":"MRZ reading result."}],"type":"topic","title":"DOTDMrzReaderResult","fragments":[{"kind":"identifier","text":"DOTDMrzReaderResult"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDMrzReaderResult"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result","title":"MrzReader.Result","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Result","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Result","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"MRZ reading result.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/result"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","title":"DocumentDetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document","abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Document"}],"navigatorTitle":[{"text":"Document","kind":"identifier"}],"role":"symbol","title":"DocumentDetector.Document"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"readWithBgraRawImage:document:travelDocumentType:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"readWithBgraRawImage:document:travelDocumentType:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzReaderResult","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDMrzReaderResult","text":"DOTDMrzReaderResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"readWithBgraRawImage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":" "},{"text":"document:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTDDocumentDetectorDocument","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocumentType:"},{"text":"(","kind":"text"},{"text":"DOTTravelDocumentTypeWrapper","preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"travelDocumentType"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments"},{"op":"replace","value":"readWithBgraRawImage:document:travelDocumentType:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader~1read(bgraRawImage:document:travelDocumentType:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader~1read(bgraRawImage:document:travelDocumentType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"readWithBgraRawImage:document:travelDocumentType:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","op":"replace","value":"DOTTravelDocumentTypeWrapper"},{"op":"replace","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"}]}]}