{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/hotspotsscorehighvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/hotspotsscorehighvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreHighValidator\/defaultThreshold","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"defaultThreshold","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTHotspotsScoreHighValidator(cpy)defaultThreshold","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreHighValidator"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreHighValidator":{"role":"symbol","title":"HotspotsScoreHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HotspotsScoreHighValidator"}],"abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreHighValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreHighValidator"}],"url":"\/documentation\/dotdocument\/hotspotsscorehighvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreHighValidator/defaultThreshold":{"role":"symbol","title":"defaultThreshold","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreHighValidator\/defaultThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"url":"\/documentation\/dotdocument\/hotspotsscorehighvalidator\/defaultthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreHighValidator\/title","value":"DOTHotspotsScoreHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTHotspotsScoreHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreHighValidator~1defaultThreshold\/title","value":"defaultThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreHighValidator~1defaultThreshold\/fragments","value":[{"kind":"identifier","text":"defaultThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}