{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/delegate","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"delegate","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController(py)delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Set this delegate to handle the fingers auto capture events."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/delegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/delegate"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/delegate":{"type":"topic","abstract":[{"text":"Set this delegate to handle the fingers auto capture events.","type":"text"}],"title":"delegate","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/delegate","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/delegate","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the fingers auto capture events."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","title":"FingersAutoCaptureViewControllerDelegate","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","type":"topic","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"kind":"symbol","abstract":[{"text":"UI component for capturing fingers images with customizable UI.","type":"text"}],"title":"BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":") ","kind":"text"},{"text":"id<DOTFGFingersAutoCaptureViewControllerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1delegate\/title","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/title","value":"DOTFGFingersAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title","value":"DOTFGBaseFingersAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}]}]}]}