{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerSample\/initWithImage:timestampMillis:","interfaceLanguage":"occ"},"metadata":{"symbolKind":"method","title":"initWithImage:timestampMillis:","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerSample(im)initWithImage:timestampMillis:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:timestampMillis:"}],"modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:timestampMillis:","kind":"identifier"}],"roleHeading":"Instance Method"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollersample\/initwithimage:timestampmillis:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerSample"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timestampMillis:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"timestampMillis","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerSample/initWithImage:timestampMillis:":{"type":"topic","title":"initWithImage:timestampMillis:","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollersample\/initwithimage:timestampmillis:","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerSample\/initWithImage:timestampMillis:","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:timestampMillis:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:timestampMillis:"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"kind":"symbol","abstract":[{"text":"version: 9.5.0","type":"text"}],"url":"\/documentation\/dotfingerscore","title":"DotFingersCore","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","role":"collection"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerSample":{"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollersample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the fingers auto capture process.","type":"text"}],"title":"DOTFGFingersAutoCaptureControllerSample","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerSample","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureControllerSample"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]}]}]}