{"sections":[],"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithImageQuality:","kind":"identifier"}],"role":"symbol","title":"init(imageQuality:)","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality(im)initWithImageQuality:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentImageQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality"},{"text":")","kind":"text"}],"symbolKind":"init","modules":[{"name":"DotDocument"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/init(imageQuality:)"},"variants":[{"paths":["\/documentation\/dotdocument\/documentquality\/init(imagequality:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentquality\/init(imagequality:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"imageQuality"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality","kind":"typeIdentifier","text":"DocumentImageQuality","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DocumentQuality/init(imageQuality:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/init(imageQuality:)","title":"init(imageQuality:)","url":"\/documentation\/dotdocument\/documentquality\/init(imagequality:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality","kind":"typeIdentifier","text":"DocumentImageQuality"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:"}]},"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"abstract":[{"text":"Document quality.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentQuality"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","kind":"symbol","url":"\/documentation\/dotdocument\/documentquality","title":"DocumentQuality","navigatorTitle":[{"kind":"identifier","text":"DocumentQuality"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality":{"kind":"symbol","title":"DocumentImageQuality","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentImageQuality","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentImageQuality"}],"type":"topic","abstract":[{"text":"Document image quality.","type":"text"}],"url":"\/documentation\/dotdocument\/documentimagequality","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithImageQuality:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithImageQuality:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithImageQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality","text":"DOTDDocumentImageQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageQuality"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1init(imageQuality:)\/title","value":"initWithImageQuality:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithImageQuality:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1init(imageQuality:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title","value":"DOTDDocumentQuality"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments","value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle"},{"op":"replace","value":"DOTDDocumentImageQuality","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/fragments","value":[{"text":"DOTDDocumentImageQuality","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/navigatorTitle","value":[{"text":"DOTDDocumentImageQuality","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}