{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenVerificationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"case","title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenVerificationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"role":"symbol","externalID":"s:7DotCore0A3SdkC5ErrorO42transactionCountingTokenVerificationFailedyAEsAD_p_tcAEmF","roleHeading":"Case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)"]}],"sections":[],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotSdk/Error":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotdocument\/dotsdk\/error","title":"DotSdk.Error","abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk":{"abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotsdk","title":"DotSdk"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/transactionCountingTokenVerificationFailed(internalError:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenVerificationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle"}]}]}