{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/finger\/init()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Finger"]]},"kind":"symbol","metadata":{"roleHeading":"Initializer","title":"init()","symbolKind":"init","externalID":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC6FingerCAEycfc","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Finger\/init()","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Finger/init()":{"title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/finger\/init()","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Finger\/init()"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Finger":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Finger","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Finger","kind":"identifier"}],"title":"FingersAutoCaptureQualityAttributeThresholds.Finger","navigatorTitle":[{"text":"Finger","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/finger","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title","value":"DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}]}]}]}