{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/camerapreviewscaletype\/fill"]},{"paths":["\/documentation\/dotfacelite\/camerapreviewscaletype\/fill"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fill","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"modules":[{"name":"DotFaceLite"}],"title":"CameraPreviewScaleType.fill","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}],"externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFill","roleHeading":"Case"},"abstract":[{"type":"text","text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds."},{"text":" ","type":"text"},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"code":"fit","type":"codeVoice"},{"text":" case) during an auto capture process.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/fill":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fill","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/fill","title":"CameraPreviewScaleType.fill","abstract":[{"type":"text","text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds."},{"type":"text","text":" "},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"text":" case) during an auto capture process.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 8.15.0","type":"text"}],"type":"topic","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/camerapreviewscaletype","title":"CameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","role":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"DOTCameraPreviewScaleTypeFill","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","value":"DOTCameraPreviewScaleTypeFill","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fill\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fill\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}