{"metadata":{"navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}],"symbolKind":"case","title":"CameraPreviewScaleType.fit","role":"symbol","roleHeading":"Case","externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFit","modules":[{"name":"DotFaceLite"}]},"abstract":[{"type":"text","text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds."},{"type":"text","text":" "},{"type":"text","text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fit"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/camerapreviewscaletype\/fit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/camerapreviewscaletype\/fit"]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fit","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/fit":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"type":"topic","title":"CameraPreviewScaleType.fit","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/fit","abstract":[{"text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.12.0"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","title":"CameraPreviewScaleType","kind":"symbol","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTCameraPreviewScaleTypeFit","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTCameraPreviewScaleTypeFit","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fit\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"}]}]}