{"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(py)barcode","fragments":[{"kind":"identifier","text":"barcode"}],"title":"barcode","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"barcode"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules\/barcode"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentlibraryconfigurationmodules\/barcode"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules"]]},"sections":[],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfigurationModules":{"type":"topic","kind":"symbol","title":"DotDocumentLibraryConfigurationModules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules","abstract":[{"type":"text","text":"Document library module configuration."}],"role":"symbol","fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfigurationmodules"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfigurationModules/barcode":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfigurationmodules\/barcode","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules\/barcode","title":"barcode","fragments":[{"kind":"identifier","text":"barcode"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentBarcodeModuleConfiguration":{"navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotdocumentbarcodemoduleconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration","kind":"symbol","type":"topic","title":"DotDocumentBarcodeModuleConfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace","value":"DotDocumentBarcodeModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}