{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules"]]},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcode:"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(im)initWithBarcode:","symbolKind":"method","title":"initWithBarcode:","navigatorTitle":[{"text":"initWithBarcode:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBarcode:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules\/initWithBarcode:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfigurationModules":{"type":"topic","kind":"symbol","title":"DotDocumentLibraryConfigurationModules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules","abstract":[{"type":"text","text":"Document library module configuration."}],"role":"symbol","fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfigurationmodules"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentBarcodeModuleConfiguration":{"navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotdocumentbarcodemoduleconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration","kind":"symbol","type":"topic","title":"DotDocumentBarcodeModuleConfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfigurationModules/initWithBarcode:":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBarcode:"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:","navigatorTitle":[{"kind":"identifier","text":"initWithBarcode:"}],"title":"initWithBarcode:","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfigurationModules\/initWithBarcode:","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]}]}]}