{"seeAlsoSections":[{"title":"NFC protocols","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"role":"symbol","title":"PassiveAuthenticationStatus","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"symbolKind":"enum","externalID":"c:@M@DotNfc@E@DOTPassiveAuthenticationStatus","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"abstract":[{"type":"text","text":"The resulting status of Passive Authentication."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH","doc:\/\/com.innovatrics.dot.nfc\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/authorityCertificatesNotProvided","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/failed","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/notSupported","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/success"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/dotnfc\/passiveauthenticationstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/passiveauthenticationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPassiveAuthenticationStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The purpose of Passive Authentication is to validate the integrity of data stored in the NFC chip of the travel document. In other words, it verifies that data stored in the NFC chip has not been altered."}]}]}],"references":{"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus":{"role":"symbol","title":"PassiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"DotNfc provides a component for NFC reading which is easy to integrate into an iOS application. Supported documents are those which implement Machine Readable Travel Document (MRTD) standards as specified by International Civil Aviation Organization (ICAO)."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SY"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/equatable-implementations"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/description"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/init(rawvalue:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/notSupported":{"role":"symbol","title":"PassiveAuthenticationStatus.notSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"abstract":[{"type":"text","text":"Passive Authentication is not supported for the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/notSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusNotSupported"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/notsupported"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/failed":{"role":"symbol","title":"PassiveAuthenticationStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"Travel document has not passed Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusFailed"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/failed"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus":{"role":"symbol","title":"ActiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/success":{"role":"symbol","title":"PassiveAuthenticationStatus.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"abstract":[{"type":"text","text":"Travel document has passed Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/success","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusSuccess"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/success"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/authorityCertificatesNotProvided":{"role":"symbol","title":"PassiveAuthenticationStatus.authorityCertificatesNotProvided","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"authorityCertificatesNotProvided"}],"abstract":[{"type":"text","text":"Authority certificates were not provided for Passive Authentication of the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/authorityCertificatesNotProvided","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusAuthorityCertificatesNotProvided"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/authoritycertificatesnotprovided"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AccessControlProtocol":{"role":"symbol","title":"AccessControlProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"abstract":[{"type":"text","text":"Access Control protocol."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/passiveauthenticationstatus\/rawrepresentable-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTPassiveAuthenticationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/authorityCertificatesNotProvided","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/failed","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/notSupported","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus\/success"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"NFC protocols","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPassiveAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/title","value":"DOTPassiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1notSupported\/title","value":"DOTPassiveAuthenticationStatusNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1notSupported\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1failed\/title","value":"DOTPassiveAuthenticationStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1failed\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/title","value":"DOTActiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1success\/title","value":"DOTPassiveAuthenticationStatusSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1success\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1authorityCertificatesNotProvided\/title","value":"DOTPassiveAuthenticationStatusAuthorityCertificatesNotProvided"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus~1authorityCertificatesNotProvided\/fragments","value":[{"kind":"identifier","text":"DOTPassiveAuthenticationStatusAuthorityCertificatesNotProvided"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/title","value":"DOTAccessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","value":[{"kind":"identifier","text":"DOTAccessControlProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}