{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/errorMessage","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"DotSdkError.errorMessage"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/errormessage"]}],"kind":"symbol","metadata":{"symbolKind":"property","externalID":"s:6DotNfc27MachineReadableZonePasswordC5ErrorO12errorMessageSSvp","title":"errorMessage","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorMessage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","type":"topic","abstract":[],"kind":"symbol","title":"MachineReadableZonePassword.Error","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","type":"topic","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"kind":"symbol","title":"MachineReadableZonePassword","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZonePassword"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/errorMessage":{"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/errormessage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/errorMessage","type":"topic","abstract":[],"kind":"symbol","title":"errorMessage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","type":"topic","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"kind":"symbol","title":"NfcTravelDocumentReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","value":"DOTNMachineReadableZonePassword"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}