{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"travelDocumentReaderPassword"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","text":"TravelDocumentReaderPassword","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/init(traveldocumentreaderpassword:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/init(traveldocumentreaderpassword:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithTravelDocumentReaderPassword:","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"travelDocumentReaderPassword","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","text":"TravelDocumentReaderPassword"},{"kind":"text","text":")"}],"platforms":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false}],"title":"init(travelDocumentReaderPassword:)","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocumentReaderPasswordWrapper(im)initWithTravelDocumentReaderPassword:"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/init(travelDocumentReaderPassword:)"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper/init(travelDocumentReaderPassword:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTravelDocumentReaderPassword:"}],"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocumentReaderPassword"},{"text":": ","kind":"text"},{"text":"TravelDocumentReaderPassword","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/init(travelDocumentReaderPassword:)","url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/init(traveldocumentreaderpassword:)","title":"init(travelDocumentReaderPassword:)","type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"navigatorTitle":[{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"kind":"symbol","title":"TravelDocumentReaderPassword","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword","abstract":[{"type":"text","text":"Password for accessing the chip."}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper":{"url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper","role":"symbol","navigatorTitle":[{"text":"TravelDocumentReaderPasswordWrapper","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","abstract":[],"title":"TravelDocumentReaderPasswordWrapper","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPasswordWrapper","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithTravelDocumentReaderPassword:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTravelDocumentReaderPassword:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithTravelDocumentReaderPassword:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","text":"id<DOTNTravelDocumentReaderPassword>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"travelDocumentReaderPassword"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithTravelDocumentReaderPassword:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1init(travelDocumentReaderPassword:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithTravelDocumentReaderPassword:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1init(travelDocumentReaderPassword:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","value":"DOTNTravelDocumentReaderPassword"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments","op":"replace","value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/title","value":"DOTNTravelDocumentReaderPasswordWrapper"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/fragments","value":[{"text":"DOTNTravelDocumentReaderPasswordWrapper","kind":"identifier"}]}]}]}