{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Idle\/init(preview:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Idle"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate\/idle\/init(preview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","kind":"typeIdentifier","text":"FaceAutoCapturePreview"},{"kind":"text","text":")"}],"title":"init(preview:)","symbolKind":"init","modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer","role":"symbol","externalID":"s:11DotFaceLite0B18AutoCaptureUiStateC4IdleC7previewAE0aB7Commons0bdE7PreviewC_tcfc"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Idle/init(preview:)":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Idle\/init(preview:)","type":"topic","title":"init(preview:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"FaceAutoCapturePreview","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/idle\/init(preview:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Idle":{"title":"FaceAutoCaptureUiState.Idle","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}],"abstract":[{"text":"Idle state.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/idle","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Idle","navigatorTitle":[{"text":"Idle","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"title":"FaceAutoCaptureUiState","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","type":"topic","title":"FaceAutoCapturePreview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.2.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title","value":"DOTFLFaceAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","value":"DOTFaceAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}