{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLMagnifEyeLivenessStyle) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"title":"MagnifEyeLivenessStyle","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessStyle","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessStyle"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/Defaults"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/init()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/backgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/detectionLayerColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionBackgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionCandidateSelectionBackgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionCandidateSelectionTextColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionFont","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionTextColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/overlayColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/placeholderCandidateSelectionColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/placeholderColor"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/detectionLayerColor":{"role":"symbol","title":"detectionLayerColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Detection layer color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/detectionLayerColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectionLayerColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/detectionlayercolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/init()"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/placeholderCandidateSelectionColor":{"role":"symbol","title":"placeholderCandidateSelectionColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Placeholder color during candidate selection phase."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/placeholderCandidateSelectionColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholderCandidateSelectionColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/placeholdercandidateselectioncolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/instructionCandidateSelectionBackgroundColor":{"role":"symbol","title":"instructionCandidateSelectionBackgroundColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Instruction background color during candidate selection phase."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionCandidateSelectionBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionCandidateSelectionBackgroundColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/instructioncandidateselectionbackgroundcolor"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/placeholderColor":{"role":"symbol","title":"placeholderColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Placeholder color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/placeholderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholderColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/placeholdercolor"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/overlayColor":{"role":"symbol","title":"overlayColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Overlay color, semi-transparent color is recommended."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/overlayColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"overlayColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/overlaycolor"},"doc://com.innovatrics.dot.face.lite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/instructionTextColor":{"role":"symbol","title":"instructionTextColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Instruction label text color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionTextColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/instructiontextcolor"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 5.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Background color of top level view."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/backgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/backgroundcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/Defaults":{"role":"symbol","title":"MagnifEyeLivenessStyle.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/defaults"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/instructionFont":{"role":"symbol","title":"instructionFont","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"Instruction label font."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionFont","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionFont"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/instructionfont"},"doc://com.innovatrics.dot.face.lite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/instructionCandidateSelectionTextColor":{"role":"symbol","title":"instructionCandidateSelectionTextColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Instruction label text color during candidate selection phase."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionCandidateSelectionTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionCandidateSelectionTextColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/instructioncandidateselectiontextcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/instructionBackgroundColor":{"role":"symbol","title":"instructionBackgroundColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Instruction background color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionBackgroundColor"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/instructionbackgroundcolor"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle":{"role":"symbol","title":"MagnifEyeLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)":{"role":"symbol","title":"init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-qhwu"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLMagnifEyeLivenessStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/backgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/detectionLayerColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionBackgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionCandidateSelectionBackgroundColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionCandidateSelectionTextColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionFont","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/instructionTextColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/overlayColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/placeholderCandidateSelectionColor","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/placeholderColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/init()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFLMagnifEyeLivenessStyle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1detectionLayerColor\/title","value":"detectionLayerColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1detectionLayerColor\/fragments","value":[{"kind":"identifier","text":"detectionLayerColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1placeholderCandidateSelectionColor\/title","value":"placeholderCandidateSelectionColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1placeholderCandidateSelectionColor\/fragments","value":[{"kind":"identifier","text":"placeholderCandidateSelectionColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionCandidateSelectionBackgroundColor\/title","value":"instructionCandidateSelectionBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionCandidateSelectionBackgroundColor\/fragments","value":[{"kind":"identifier","text":"instructionCandidateSelectionBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1placeholderColor\/title","value":"placeholderColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1placeholderColor\/fragments","value":[{"kind":"identifier","text":"placeholderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1overlayColor\/title","value":"overlayColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1overlayColor\/fragments","value":[{"kind":"identifier","text":"overlayColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionTextColor\/title","value":"instructionTextColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionTextColor\/fragments","value":[{"kind":"identifier","text":"instructionTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionFont\/title","value":"instructionFont"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionFont\/fragments","value":[{"kind":"identifier","text":"instructionFont"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionCandidateSelectionTextColor\/title","value":"instructionCandidateSelectionTextColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionCandidateSelectionTextColor\/fragments","value":[{"kind":"identifier","text":"instructionCandidateSelectionTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionBackgroundColor\/title","value":"instructionBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1instructionBackgroundColor\/fragments","value":[{"kind":"identifier","text":"instructionBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle\/title","value":"DOTFLMagnifEyeLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)\/title","value":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:overlayColor:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}