{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/init(bytesPointer:size:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bgrrawimage\/init(bytespointer:size:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrrawimage\/init(bytespointer:size:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"init","navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(im)initWithBytesPointer:size:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":")","kind":"text"}],"title":"init(bytesPointer:size:)","roleHeading":"Initializer"},"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgrRawImageFactory"},{"text":" to create ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"type":"topic","role":"symbol","title":"ImageSize","kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imagesize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage/init(bytesPointer:size:)":{"url":"\/documentation\/dotpalmcore\/bgrrawimage\/init(bytespointer:size:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/init(bytesPointer:size:)","role":"symbol","navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":")","kind":"text"}],"title":"init(bytesPointer:size:)","type":"topic","abstract":[{"text":"Do not use this, use ","type":"text"},{"code":"BgrRawImageFactory","type":"codeVoice"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage":{"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"type":"topic","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","title":"BgrRawImage","url":"\/documentation\/dotpalmcore\/bgrrawimage","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithBytesPointer:size:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBytesPointer:size:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithBytesPointer:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t","text":"uint8_t"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bytesPointer"},{"kind":"text","text":" "},{"kind":"identifier","text":"size:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"size"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1init(bytesPointer:size:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBytesPointer:size:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/title","op":"replace","value":"DOTBgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]}]}]}