{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"_RawImage.size","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/size"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"size","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(py)size","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"size"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bgrrawimage\/size"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrrawimage\/size"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","title":"BgrRawImage","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"url":"\/documentation\/dotpalmcore\/bgrrawimage","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","type":"topic","title":"ImageSize","abstract":[{"text":"Image size in pixels.","type":"text"}],"url":"\/documentation\/dotpalmcore\/imagesize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage/size":{"role":"symbol","title":"size","url":"\/documentation\/dotpalmcore\/bgrrawimage\/size","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"type":"topic","navigatorTitle":[{"text":"size","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage\/size"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"title":"DotPalmCore","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"size"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"size"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},{"kind":"text","text":" * "},{"kind":"identifier","text":"size"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/fragments"},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments"},{"value":"size","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1size\/title","op":"replace"},{"value":[{"kind":"identifier","text":"size"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage~1size\/fragments"}]}]}