{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wearablesquery\/evaluateglasses"]},{"paths":["\/documentation\/dotfacecore\/wearablesquery\/evaluateglasses"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery"]]},"abstract":[{"type":"text","text":"Glasses evaluation flag."}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery(py)evaluateGlasses","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","roleHeading":"Instance Property","title":"evaluateGlasses","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateGlasses"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"evaluateGlasses"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateGlasses"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateGlasses"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery/evaluateGlasses":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"evaluateGlasses","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Glasses evaluation flag.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateGlasses","title":"evaluateGlasses","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"evaluateGlasses"}],"role":"symbol","url":"\/documentation\/dotfacecore\/wearablesquery\/evaluateglasses"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WearablesQuery"}],"url":"\/documentation\/dotfacecore\/wearablesquery","type":"topic","navigatorTitle":[{"text":"WearablesQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"title":"WearablesQuery","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"evaluateGlasses","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"evaluateGlasses","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateGlasses"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1evaluateGlasses\/title","value":"evaluateGlasses"},{"op":"replace","value":[{"text":"evaluateGlasses","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1evaluateGlasses\/fragments"},{"value":"DOTFWearablesQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}