{"variants":[{"paths":["\/documentation\/dotfacecore\/dotface\/dotfacelibrarydelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotface\/dotfacelibrarydelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/DotFaceLibraryDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/dotFaceLibraryDeinitializationFinished(_:result:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/dotFaceLibraryInitializationFinished(_:result:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"DotFaceCore"}],"role":"collectionGroup","title":"DotFaceLibraryDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace":{"deprecated":true,"role":"symbol","title":"DotFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFace"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFace"}],"url":"\/documentation\/dotfacecore\/dotface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace/dotFaceLibraryDeinitializationFinished(_:result:)":{"role":"symbol","title":"dotFaceLibraryDeinitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceLibraryDeinitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB7LibraryC6ResultC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework deinitialization has finished with "},{"type":"codeVoice","code":"result"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/dotFaceLibraryDeinitializationFinished(_:result:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dotFaceLibraryDeinitializationFinished:result:"}],"url":"\/documentation\/dotfacecore\/dotface\/dotfacelibrarydeinitializationfinished(_:result:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.10.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace/dotFaceLibraryInitializationFinished(_:result:)":{"role":"symbol","title":"dotFaceLibraryInitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB7LibraryC6ResultC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework initialization has finished with "},{"type":"codeVoice","code":"result"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/dotFaceLibraryInitializationFinished(_:result:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}],"url":"\/documentation\/dotfacecore\/dotface\/dotfacelibraryinitializationfinished(_:result:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/dotFaceLibraryDeinitializationFinished(_:result:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/dotFaceLibraryInitializationFinished(_:result:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/title","value":"DotFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/fragments","value":[{"kind":"identifier","text":"DotFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1dotFaceLibraryDeinitializationFinished(_:result:)\/title","value":"dotFaceLibraryDeinitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1dotFaceLibraryDeinitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceLibraryDeinitializationFinished:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1dotFaceLibraryInitializationFinished(_:result:)\/title","value":"dotFaceLibraryInitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1dotFaceLibraryInitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}