{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpplaceholdervisible\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Placeholder type. Default is ","type":"text"},{"text":".left","type":"text"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","kind":"typeIdentifier","text":"DOTPPlaceholderType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/type","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"type","role":"symbol","modules":[{"name":"DotPalmCore"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholderVisible(py)type","navigatorTitle":[{"text":"type","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"type"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"kind":"symbol","role":"symbol","abstract":[{"text":"Type of placeholder.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/placeholdertype","title":"PlaceholderType"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible","fragments":[{"text":"DOTPPlaceholderVisible","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DOTPPlaceholderVisible","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible","abstract":[{"type":"text","text":"Visible placeholder."}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible/type":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible\/type","fragments":[{"text":"type","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"type","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/type","abstract":[{"type":"text","text":"Placeholder type. Default is "},{"type":"text","text":".left"},{"type":"text","text":"."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 9.2.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"}},"variantOverrides":[{"patch":[{"value":"DOTPPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title"},{"value":[{"kind":"identifier","text":"DOTPPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}