{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/passiveLiveness","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/passiveliveness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/passiveliveness"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Case","role":"symbol","title":"DotFaceModuleId.passiveLiveness","symbolKind":"case","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdPassiveLiveness"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"kind":"symbol","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"url":"\/documentation\/dotpalmcore\/dotfacemoduleid","title":"DotFaceModuleId"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/passiveLiveness":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/passiveliveness","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"title":"DotFaceModuleId.passiveLiveness","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/passiveLiveness","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleIdPassiveLiveness","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/navigatorTitle","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1passiveLiveness\/title","value":"DotFaceModuleIdPassiveLiveness"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1passiveLiveness\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}