{"metadata":{"roleHeading":"Instance Property","title":"imageParameters","externalID":"s:11DotPalmCore0B8DetectorC0B0C15imageParametersAA05ImageF0Cvp","symbolKind":"property","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageParameters","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"imageParameters","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","text":"ImageParameters"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/imageParameters"},"abstract":[{"type":"text","text":"Image parameters calculated from the area of the detected palm."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/imageparameters"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/imageParameters":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"imageParameters","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","text":"ImageParameters","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/imageParameters","abstract":[{"type":"text","text":"Image parameters calculated from the area of the detected palm."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/imageparameters","role":"symbol","title":"imageParameters"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm","kind":"symbol","abstract":[{"type":"text","text":"Result of the palm detection process."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Palm"}],"navigatorTitle":[{"kind":"identifier","text":"Palm"}],"title":"PalmDetector.Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"kind":"symbol","abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"url":"\/documentation\/dotpalmcore\/imageparameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"role":"symbol","type":"topic","title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"},{"value":"DOTPImageParameters","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments","value":[{"text":"DOTPImageParameters","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}