{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"metadata":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder(im)init","title":"init"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotplaceholder\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholder\/init","interfaceLanguage":"occ"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"title":"Placeholder","url":"\/documentation\/dotfacecore\/placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholder/init":{"title":"init","abstract":[],"url":"\/documentation\/dotfacecore\/dotplaceholder\/init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholder\/init","kind":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title","value":"DOTPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholder"}]},{"value":[{"text":"DOTPlaceholder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}