{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imagesize\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/imagesize\/description"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/description","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(py)description","navigatorTitle":[{"text":"description","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/imagesize","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"type":"topic","abstract":[{"text":"Image size in pixels.","type":"text"}],"title":"ImageSize","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/description":{"type":"topic","title":"description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotfacecore\/imagesize\/description","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/description","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1description\/fragments"}]}]}