{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","text":"Face"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"text":"Detected face.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/face"},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/face"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/face"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection(py)face","navigatorTitle":[{"text":"face","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"face","roleHeading":"Instance Property"},"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"url":"\/documentation\/dotfacecore\/facedetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"kind":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacecore\/faceautocapturedetection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"type":"topic","title":"FaceAutoCaptureDetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SmileLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","title":"SmileLivenessViewController","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"kind":"symbol","title":"MagnifEyeLivenessViewController","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"url":"\/documentation\/dotfacecore\/face","kind":"symbol","title":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","abstract":[{"text":"Detected face in the image.","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"Face"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"title":"FaceDetector.Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","url":"\/documentation\/dotfacecore\/facedetector\/face","kind":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Face"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/face":{"url":"\/documentation\/dotfacecore\/faceautocapturedetection\/face","abstract":[{"text":"Detected face.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"face","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/face","title":"face","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"face","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"face","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","text":"Face"},{"text":" * ","kind":"text"},{"text":"face","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1face\/title","value":"face","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1face\/fragments","value":[{"text":"face","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}