{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/placeholder\/visible\/description"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/description","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"description","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"s:11DotDocument11PlaceholderC7VisibleC11descriptionSSvp","role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/Placeholder":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","title":"Placeholder","url":"\/documentation\/dotdocument\/placeholder","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"abstract":[{"text":"Placeholder.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}]},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible","title":"Placeholder.Visible","url":"\/documentation\/dotdocument\/placeholder\/visible","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"abstract":[{"text":"Visible placeholder.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Visible"}]},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible/description":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/description","title":"description","url":"\/documentation\/dotdocument\/placeholder\/visible\/description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title","value":"DOTDPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments","value":[{"text":"DOTDPlaceholder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle","value":[{"text":"DOTDPlaceholder","kind":"identifier"}]}]}]}