{"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/bgrarawimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bgrarawimagefactory\/create(bgrrawimage:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bgrRawImage","content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" instance.","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(bgrRawImage:)"},"abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"kind":"symbol","metadata":{"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"kind":"text","text":") -> "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithBgrRawImage:","title":"create(bgrRawImage:)","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgrRawImage":{"type":"topic","role":"symbol","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"url":"\/documentation\/dotfacelite\/bgrrawimage","title":"BgrRawImage"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","role":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage","kind":"symbol","type":"topic","title":"BgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImageFactory/create(bgrRawImage:)":{"navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"url":"\/documentation\/dotfacelite\/bgrarawimagefactory\/create(bgrrawimage:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(bgrRawImage:)","type":"topic","role":"symbol","title":"create(bgrRawImage:)","kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImageFactory":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimagefactory","kind":"symbol","type":"topic","title":"BgraRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"createWithBgrRawImage:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTBgraRawImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithBgrRawImage:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"DOTBgrRawImage"},{"kind":"text","text":" *) "},{"text":"bgrRawImage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(bgrRawImage:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory","op":"replace"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory\/fragments","op":"replace"}]}]}