{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facequality\/imagequality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/facequality\/imagequality"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality"]]},"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality(py)imageQuality","title":"imageQuality","roleHeading":"Instance Property","navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","text":"FaceImageQuality","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/imageQuality"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Image quality.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","text":"FaceImageQuality","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality":{"role":"symbol","url":"\/documentation\/dotfacelite\/faceimagequality","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality","kind":"symbol","abstract":[{"type":"text","text":"Face image quality."}],"type":"topic","title":"FaceImageQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"role":"symbol","url":"\/documentation\/dotfacelite\/facequality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","kind":"symbol","abstract":[{"type":"text","text":"Face quality."}],"type":"topic","title":"FaceQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/imageQuality":{"url":"\/documentation\/dotfacelite\/facequality\/imagequality","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/imageQuality","abstract":[{"type":"text","text":"Image quality."}],"title":"imageQuality","navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","text":"FaceImageQuality","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"imageQuality","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"imageQuality","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","text":"DOTFLFaceImageQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality"},{"text":" * ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFLFaceImageQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/title"},{"value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/fragments"},{"value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/navigatorTitle"},{"value":"DOTFLFaceQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title"},{"value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments"},{"value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1imageQuality\/title","value":"imageQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1imageQuality\/fragments","value":[{"text":"imageQuality","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}