{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/facequality\/init(imagequality:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/facequality\/init(imagequality:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/init(imageQuality:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceImageQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality"},{"text":")","kind":"text"}],"title":"init(imageQuality:)","role":"symbol","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality(im)initWithImageQuality:","roleHeading":"Initializer","symbolKind":"init"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceImageQuality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"abstract":[{"text":"Face quality.","type":"text"}],"url":"\/documentation\/dotfacelite\/facequality","title":"FaceQuality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality":{"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceimagequality","title":"FaceImageQuality","abstract":[{"text":"Face image quality.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/init(imageQuality:)":{"url":"\/documentation\/dotfacelite\/facequality\/init(imagequality:)","title":"init(imageQuality:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","text":"FaceImageQuality"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/init(imageQuality:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImageQuality:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLFaceImageQuality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageQuality","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFLFaceQuality","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title","op":"replace"},{"value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments","op":"replace"},{"value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle","op":"replace"},{"value":"DOTFLFaceImageQuality","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/title","op":"replace"},{"value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/fragments","op":"replace"},{"value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/navigatorTitle","op":"replace"},{"value":"initWithImageQuality:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1init(imageQuality:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1init(imageQuality:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}