{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Default threshold."}],"metadata":{"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","navigatorTitle":[{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersOutOfBoundsValidator(cpy)defaultMinCornerDistanceToImageShorterSideRatioThreshold","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"roleHeading":"Type Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/defaultMinCornerDistanceToImageShorterSideRatioThreshold":{"abstract":[{"type":"text","text":"Default threshold."}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"type":"topic","title":"FingersOutOfBoundsValidator","navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersOutOfBoundsValidator"}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/title","value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","value":"DOTFGFingersOutOfBoundsValidator"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}