{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","kind":"typeIdentifier","text":"FingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fingersAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"text":"Frame parameters to validate.","type":"text"}]}]}]},{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" for out of bounds fingers."}]}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/validate(fingersautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/validate(fingersautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"validate(fingersAutoCaptureFrameParameters:)","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersOutOfBoundsValidator(im)validateWithFingersAutoCaptureFrameParameters:","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/validate(fingersAutoCaptureFrameParameters:)"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/validate(fingersAutoCaptureFrameParameters:)":{"title":"validate(fingersAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"abstract":[{"text":"Validate if the detected fingers are within the bounds of the image.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/validate(fingersautocaptureframeparameters:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/validate(fingersAutoCaptureFrameParameters:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"title":"FingersAutoCaptureFrameParameters","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information from the detection process about the detected fingers.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"type":"topic","title":"FingersOutOfBoundsValidator","navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersOutOfBoundsValidator"}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"validateWithFingersAutoCaptureFrameParameters:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","text":"DOTFGFingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":" *) ","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"fingersAutoCaptureFrameParameters","content":[{"inlineContent":[{"type":"text","text":"Frame parameters to validate."}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" for out of bounds fingers.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1validate(fingersAutoCaptureFrameParameters:)\/title","value":"validateWithFingersAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title","value":"DOTFGFingersAutoCaptureFrameParameters"},{"value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","value":"DOTFGFingersOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle"}]}]}