{"metadata":{"title":"init(modules:)","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","text":"Modules"},{"text":")","kind":"text"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(im)initWithModules:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class"},{"text":" = .init())","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/init(modules:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration/init(modules:)":{"navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/init(modules:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/init(modules:)","title":"init(modules:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration":{"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration","title":"DotDocumentLibraryConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration/Modules-swift.class":{"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfigurationModules":{"url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfigurationmodules","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules","type":"topic","kind":"symbol","fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}],"role":"symbol","title":"DotDocumentLibraryConfigurationModules"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithModules:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithModules:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules","kind":"typeIdentifier","text":"DotDocumentLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modules"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration~1init(modules:)\/title","op":"replace","value":"initWithModules:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration~1init(modules:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/title","op":"replace","value":"DotDocumentLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}]}]}