{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/init"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"title":"DotDocumentLibraryConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration/init":{"type":"topic","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/init","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/init","title":"init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}