{"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceImageQuality(py)brightness","title":"brightness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"brightness"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality\/brightness"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Brightness value in range [0, 1.0]."}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/faceimagequality\/brightness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceimagequality\/brightness"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQuality"}],"title":"FaceImageQuality","type":"topic","url":"\/documentation\/dotfacelite\/faceimagequality","abstract":[{"type":"text","text":"Face image quality."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceImageQuality/brightness":{"url":"\/documentation\/dotfacelite\/faceimagequality\/brightness","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Brightness value in range [0, 1.0]."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"brightness","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceImageQuality\/brightness","navigatorTitle":[{"text":"brightness","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"brightness"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"brightness"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/title","op":"replace","value":"DOTFLFaceImageQuality"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/fragments","op":"replace","value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}]},{"value":[{"text":"DOTFLFaceImageQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality\/navigatorTitle","op":"replace"},{"value":"brightness","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality~1brightness\/title","op":"replace"},{"value":[{"text":"brightness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceImageQuality~1brightness\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}