{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"center","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble"},{"text":", ","kind":"text"},{"text":"sizeToImageShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/detectionposition\/init(center:sizetoimageshortersideratio:)"]},{"paths":["\/documentation\/dotfacelite\/detectionposition\/init(center:sizetoimageshortersideratio:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithCenter:sizeToImageShorterSideRatio:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"center","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"sizeToImageShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition(im)initWithCenter:sizeToImageShorterSideRatio:","title":"init(center:sizeToImageShorterSideRatio:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition":{"abstract":[{"type":"text","text":"The position of the detected face in the image."}],"url":"\/documentation\/dotfacelite\/detectionposition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol","title":"DetectionPosition"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/pointdouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble","role":"symbol","title":"PointDouble","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition/init(center:sizeToImageShorterSideRatio:)":{"navigatorTitle":[{"text":"initWithCenter:sizeToImageShorterSideRatio:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"center","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"sizeToImageShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/detectionposition\/init(center:sizetoimageshortersideratio:)","title":"init(center:sizeToImageShorterSideRatio:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithCenter:sizeToImageShorterSideRatio:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithCenter:sizeToImageShorterSideRatio:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCenter:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPointDouble","preciseIdentifier":"c:objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"center","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sizeToImageShorterSideRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sizeToImageShorterSideRatio","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/title","op":"replace","value":"DOTDetectionPosition"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1init(center:sizeToImageShorterSideRatio:)\/title","op":"replace","value":"initWithCenter:sizeToImageShorterSideRatio:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition~1init(center:sizeToImageShorterSideRatio:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCenter:sizeToImageShorterSideRatio:"}]}]}]}