{"sections":[],"metadata":{"navigatorTitle":[{"text":"faceImage","kind":"identifier"}],"title":"faceImage","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace(py)faceImage","role":"symbol","platforms":[{"deprecated":false,"name":"iOS","introducedAt":"13.0","beta":false,"unavailable":false}]},"abstract":[{"type":"text","text":"Face image of document holder."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/faceimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/faceimage"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceImage","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/faceImage"},"references":{"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"title":"EncodedIdentificationFeaturesFace","role":"symbol","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","kind":"symbol","abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"type":"topic","navigatorTitle":[{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","title":"DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/Image":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","type":"topic","url":"\/documentation\/dotnfc\/image","title":"Image","abstract":[{"text":"Raw image data representation.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Image","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/faceImage":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceImage"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"kind":"text","text":"?"}],"title":"faceImage","role":"symbol","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/faceimage","kind":"symbol","abstract":[{"text":"Face image of document holder.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"faceImage","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/faceImage"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"role":"symbol","title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"faceImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"faceImage"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"DOTNImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"kind":"text","text":" * "},{"text":"faceImage","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTNEncodedIdentificationFeaturesFace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","value":"DOTNImage"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","op":"replace","value":[{"text":"DOTNImage","kind":"identifier"}]},{"op":"replace","value":"faceImage","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1faceImage\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1faceImage\/fragments","value":[{"kind":"identifier","text":"faceImage"}],"op":"replace"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]}]}]}