{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace"]]},"sections":[],"metadata":{"title":"init(faceImage:)","symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace(im)initWithFaceImage:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFaceImage:"}],"roleHeading":"Initializer","modules":[{"name":"DotNfc"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/init(faceimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/init(faceimage:)"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/init(faceImage:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/init(faceImage:)":{"abstract":[],"title":"init(faceImage:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/init(faceImage:)","kind":"symbol","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/init(faceimage:)","type":"topic","navigatorTitle":[{"text":"initWithFaceImage:","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"kind":"symbol","abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"type":"topic","title":"EncodedIdentificationFeaturesFace","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"navigatorTitle":[{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface"},"doc://DotNfc/documentation/DotNfc/Image":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","url":"\/documentation\/dotnfc\/image","abstract":[],"title":"Image","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithFaceImage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFaceImage:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithFaceImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"faceImage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithFaceImage:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1init(faceImage:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFaceImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1init(faceImage:)\/fragments"},{"value":"DOTNEncodedIdentificationFeaturesFace","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title"},{"value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments"},{"value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}