{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/isequal(_:)"]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace(im)isEqual:","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/isEqual(_:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","title":"EncodedIdentificationFeaturesFace","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/isEqual(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/isequal(_:)","type":"topic","title":"isEqual(_:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","op":"replace","value":"DOTNEncodedIdentificationFeaturesFace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]}]}]}