{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkLicenseProxyProtocol.isNfcEnabled"},{"type":"text","text":"."}],"sections":[],"metadata":{"title":"isNfcEnabled","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@M@DotDocument@objc(cs)DotSdkLicenseProxy(py)isNfcEnabled","navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isNfcEnabled","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/isnfcenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/isnfcenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy":{"kind":"symbol","type":"topic","title":"DotSdkLicenseProxy","url":"\/documentation\/dotdocument\/dotsdklicenseproxy","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isNfcEnabled":{"kind":"symbol","abstract":[],"title":"isNfcEnabled","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isnfcenabled","navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isNfcEnabled","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isNfcEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"isNfcEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/title","op":"replace","value":"DotSdkLicenseProxy"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"op":"replace"},{"value":"isNfcEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isNfcEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isNfcEnabled\/fragments","op":"replace","value":[{"text":"isNfcEnabled","kind":"identifier"}]}]}]}