{"metadata":{"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","symbolKind":"class","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LdsMasterFile"}],"title":"LdsMasterFile","navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNLdsMasterFile) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LdsMasterFile"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"Raw content","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile"],"generated":true}],"variants":[{"paths":["\/documentation\/dotnfc\/ldsmasterfile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/ldsmasterfile"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/init(lds1eMrtdApplication:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/lds1eMrtdApplication"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/isEqual(_:)"]}],"kind":"symbol","sections":[],"references":{"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","url":"\/documentation\/dotnfc\/ldsmasterfile\/isequal(_:)","abstract":[],"role":"symbol","title":"isEqual(_:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"LdsMasterFile","kind":"identifier"}],"abstract":[{"text":"Raw represenation of the whole content stored in the NFC chip of the travel document.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile","title":"LdsMasterFile","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/ldsmasterfile","kind":"symbol","navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile/init(lds1eMrtdApplication:)":{"url":"\/documentation\/dotnfc\/ldsmasterfile\/init(lds1emrtdapplication:)","title":"init(lds1eMrtdApplication:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"lds1eMrtdApplication","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication","text":"Lds1eMrtdApplication"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithLds1eMrtdApplication:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/init(lds1eMrtdApplication:)","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","role":"symbol","title":"TravelDocument","abstract":[{"text":"Result of NFC reading.","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile/description":{"url":"\/documentation\/dotnfc\/ldsmasterfile\/description","title":"description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/description","role":"symbol"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile/lds1eMrtdApplication":{"url":"\/documentation\/dotnfc\/ldsmasterfile\/lds1emrtdapplication","title":"lds1eMrtdApplication","abstract":[{"type":"text","text":"Raw LDS1 eMRTD application content."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lds1eMrtdApplication"},{"text":": ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication"}],"navigatorTitle":[{"kind":"identifier","text":"lds1eMrtdApplication"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/lds1eMrtdApplication","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","title":"Lds1ElementaryFile","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfile","kind":"symbol","navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"text":"version: 8.3.0","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/LdsMasterFile/hash":{"url":"\/documentation\/dotnfc\/ldsmasterfile\/hash","title":"hash","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/hash","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1eMrtdApplication":{"url":"\/documentation\/dotnfc\/lds1emrtdapplication","role":"symbol","navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"title":"Lds1eMrtdApplication","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"role":"symbol","title":"NfcTravelDocumentReader","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTNLdsMasterFile"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLdsMasterFile"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/lds1eMrtdApplication"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/init(lds1eMrtdApplication:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/LdsMasterFile\/isEqual(_:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile"],"title":"Raw content"}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTNLdsMasterFile","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1isEqual(_:)\/fragments"},{"value":"DOTNLdsMasterFile","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}]},{"op":"replace","value":"initWithLds1eMrtdApplication:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1init(lds1eMrtdApplication:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLds1eMrtdApplication:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1init(lds1eMrtdApplication:)\/fragments"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1description\/title","op":"replace","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1description\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1lds1eMrtdApplication\/title","value":"lds1eMrtdApplication"},{"value":[{"kind":"identifier","text":"lds1eMrtdApplication"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1lds1eMrtdApplication\/fragments","op":"replace"},{"value":"DOTNLds1ElementaryFile","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1hash\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1LdsMasterFile~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNLds1eMrtdApplication","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace"}]}]}