{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/corners\/init(topleft:topright:bottomright:bottomleft:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/corners\/init(topleft:topright:bottomright:bottomleft:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","kind":"typeIdentifier","text":"PointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRight"},{"text":": ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"init(topLeft:topRight:bottomRight:bottomLeft:)","navigatorTitle":[{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomRight","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTCorners(im)initWithTopLeft:topRight:bottomRight:bottomLeft:"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/corners","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners","kind":"symbol","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"title":"Corners"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"title":"init(topLeft:topRight:bottomRight:bottomLeft:)","url":"\/documentation\/dotfacelite\/corners\/init(topleft:topright:bottomright:bottomleft:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"text":"bottomRight","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":", "},{"text":"bottomLeft","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","abstract":[],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/PointDouble":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","title":"PointDouble","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotfacelite\/pointdouble"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopLeft:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topLeft"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight:"},{"text":"(","kind":"text"},{"text":"DOTPointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topRight"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomRight:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","kind":"typeIdentifier","text":"DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bottomRight"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"kind":"text","text":" *) "},{"text":"bottomLeft","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTCorners","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}]},{"value":"DOTPointDouble","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1PointDouble\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace"}]}]}