{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle\/isEqual(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"method","externalID":"s:11DotFaceCore0B18AutoCaptureUiStateC4IdleC7isEqualySbypSgF","title":"isEqual(_:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate\/idle\/isequal(_:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Idle":{"navigatorTitle":[{"kind":"identifier","text":"Idle"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/idle","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Idle state."}],"kind":"symbol","title":"FaceAutoCaptureUiState.Idle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Idle"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"role":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureuistate","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"kind":"symbol","title":"FaceAutoCaptureUiState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Idle/isEqual(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle\/isEqual(_:)","role":"symbol","kind":"symbol","title":"isEqual(_:)","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/idle\/isequal(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title","value":"DOTFFaceAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]}]}]}