{"metadata":{"platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false}],"title":"isEqual(_:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile(im)isEqual:","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/ldsmasterfile\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/ldsmasterfile\/isequal(_:)"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/isEqual(_:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"role":"symbol","url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile/isEqual(_:)":{"url":"\/documentation\/dotnfc\/ldsmasterfile\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","title":"isEqual(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/isEqual(_:)"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"url":"\/documentation\/dotnfc\/ldsmasterfile","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LdsMasterFile","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}],"abstract":[{"text":"Raw represenation of the whole content stored in the NFC chip of the travel document.","type":"text"}],"role":"symbol","type":"topic","title":"LdsMasterFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"isEqual:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"value":"DOTNLdsMasterFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNLdsMasterFile"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}