{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc","relatedModules":["Foundation"]}],"platforms":[{"unavailable":false,"introducedAt":"8.0","name":"iOS","beta":false,"deprecated":false},{"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"8.0","deprecated":false},{"introducedAt":"10.10","unavailable":false,"deprecated":false,"beta":false,"name":"macOS"},{"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"9.0","unavailable":false},{"name":"watchOS","deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false}],"externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:6DotNfc24CardAccessNumberPasswordC5ErrorO","extendedModule":"Foundation","roleHeading":"Instance Property","title":"failureReason","symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/failureReason"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/failurereason"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.failureReason","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/failureReason":{"title":"failureReason","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/failurereason","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/failureReason"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","role":"symbol","title":"CardAccessNumberPassword.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword","abstract":[{"type":"text","text":"Card Access Number as a password."}],"navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"title":"CardAccessNumberPassword"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}]}]}]}