{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/backgroundUniformity"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/backgrounduniformity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/backgrounduniformity"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdBackgroundUniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"roleHeading":"Case","symbolKind":"case","title":"DotFaceModuleId.backgroundUniformity","role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"url":"\/documentation\/dotdocument\/dotfacemoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"kind":"symbol","title":"DotFaceModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/backgroundUniformity":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/backgroundUniformity","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/backgrounduniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"kind":"symbol","title":"DotFaceModuleId.backgroundUniformity","role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DotFaceModuleIdBackgroundUniformity"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/title","op":"replace","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/fragments","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/navigatorTitle","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1backgroundUniformity\/title","op":"replace","value":"DotFaceModuleIdBackgroundUniformity"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1backgroundUniformity\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}