{"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionBalanced","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/detectionbalanced"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/detectionbalanced"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId"]]},"kind":"symbol","metadata":{"roleHeading":"Case","title":"DotFaceModuleId.detectionBalanced","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdDetectionBalanced","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacemoduleid","role":"symbol","type":"topic","kind":"symbol","title":"DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/detectionBalanced":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionBalanced","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"kind":"symbol","type":"topic","title":"DotFaceModuleId.detectionBalanced","url":"\/documentation\/dotdocument\/dotfacemoduleid\/detectionbalanced","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleIdDetectionBalanced","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/navigatorTitle"},{"op":"replace","value":"DotFaceModuleIdDetectionBalanced","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionBalanced\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionBalanced\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}