{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidappear(_:)"]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(magnifEyeLivenessViewControllerViewDidAppear:) ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidAppear(_:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier","text":"MagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","title":"magnifEyeLivenessViewControllerViewDidAppear(_:)","required":true,"externalID":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessViewControllerViewDidAppear:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"magnifEyeLivenessViewControllerViewDidAppear:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.9.0","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"role":"symbol","abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate","type":"topic","kind":"symbol","title":"MagnifEyeLivenessViewControllerDelegate","navigatorTitle":[{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"type":"topic","title":"MagnifEyeLivenessViewController","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidAppear(_:)":{"required":true,"title":"magnifEyeLivenessViewControllerViewDidAppear(_:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"magnifEyeLivenessViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidAppear(_:)","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidappear(_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"magnifEyeLivenessViewControllerViewDidAppear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"magnifEyeLivenessViewControllerViewDidAppear:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","text":"DOTFMagnifEyeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFMagnifEyeLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController","op":"replace"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidAppear(_:)\/title","value":"magnifEyeLivenessViewControllerViewDidAppear:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidAppear(_:)\/fragments","op":"replace"}]}]}