{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","symbolKind":"property","title":"description","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)description","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/description"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/rectangledouble\/description"]},{"paths":["\/documentation\/dotfacelite\/rectangledouble\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"title":"FaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","type":"topic","url":"\/documentation\/dotfacelite\/facedetector"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble/description":{"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/description","url":"\/documentation\/dotfacelite\/rectangledouble\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.7.0"}],"title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","url":"\/documentation\/dotfacelite\/rectangledouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"description","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","op":"replace","value":"DOTFLFaceDetector"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1description\/title","op":"replace","value":"description"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1description\/fragments"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}