{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules\/detection"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"detection","kind":"identifier"}],"roleHeading":"Instance Property","title":"detection","navigatorTitle":[{"text":"detection","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(py)detection","symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotPalmDetectionModuleConfiguration":{"title":"DotPalmDetectionModuleConfiguration","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotpalmdetectionmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"abstract":[{"type":"text","text":"Palm detection module configuration."}]},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfigurationModules":{"title":"DotPalmLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules","fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules","abstract":[{"type":"text","text":"Palm library module configuration."}]},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfigurationModules/detection":{"role":"symbol","url":"\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules\/detection","title":"detection","fragments":[{"text":"detection","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules\/detection","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}