{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules\/initwithdetection:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithDetection:"}],"symbolKind":"method","title":"initWithDetection:","role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(im)initWithDetection:","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules\/initWithDetection:"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfigurationModules/initWithDetection:":{"title":"initWithDetection:","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules\/initWithDetection:","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithDetection:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules\/initwithdetection:","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotPalmDetectionModuleConfiguration":{"type":"topic","navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration","role":"symbol","kind":"symbol","title":"DotPalmDetectionModuleConfiguration","url":"\/documentation\/dotdocument\/dotpalmdetectionmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Palm detection module configuration."}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfigurationModules":{"type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"abstract":[{"text":"Palm library module configuration.","type":"text"}],"title":"DotPalmLibraryConfigurationModules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules","url":"\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/title","op":"replace","value":"DotPalmDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}