{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"start()","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController(im)start","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"start","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"modules":[{"name":"DotPalmCore"}]},"abstract":[{"type":"text","text":"Start the palm auto capture process."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/start()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/start()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/start()","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"title":"PalmAutoCaptureViewController","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/start()":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/start()","kind":"symbol","title":"start()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"start"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/start()","abstract":[{"text":"Start the palm auto capture process.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"start"},{"text":"()","kind":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","url":"\/documentation\/dotpalmcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"start","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"start"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1start()\/title","op":"replace","value":"start"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"start"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1start()\/fragments"}]}]}