{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/hash","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/placeholder\/hidden\/hash"]}],"metadata":{"externalID":"s:14DotFaceCommons11PlaceholderC6HiddenC4hashSivp","role":"symbol","roleHeading":"Instance Property","title":"hash","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.1.0"}],"title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Hidden":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Hidden placeholder."}],"navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/placeholder\/hidden","role":"symbol","title":"Placeholder.Hidden","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Hidden/hash":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/hash","url":"\/documentation\/dotfacecore\/placeholder\/hidden\/hash","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hash","abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"type":"topic","title":"Placeholder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","role":"symbol","url":"\/documentation\/dotfacecore\/placeholder","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Placeholder."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTPlaceholder","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title"},{"op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}