{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}]}]}],"metadata":{"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"DotPalmCore"}],"roleHeading":"Enumeration","title":"DotLibraryId","role":"symbol","externalID":"c:@M@DotCore@E@DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"kind":"symbol","topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/document","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/face","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/faceLite","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/nfc","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/palm"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/description"],"generated":true,"anchor":"Instance-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/RawRepresentable-Implementations":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/rawrepresentable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/init(rawValue:)":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/init(rawvalue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/init(rawValue:)","title":"init(rawValue:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/description":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/description","role":"symbol","title":"description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/description","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","title":"DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid","role":"symbol"},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SY"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/faceLite":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/facelite","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/faceLite","title":"DotLibraryId.faceLite","kind":"symbol","navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"type":"text","text":" identifier."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/face":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/face","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/face","title":"DotLibraryId.face","kind":"symbol","navigatorTitle":[{"text":"DotLibraryIdFace","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" identifier."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/Equatable-Implementations":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","abstract":[],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/document":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/document","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/document","title":"DotLibraryId.document","kind":"symbol","navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"type":"text","text":" identifier."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/palm":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/palm","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/palm","title":"DotLibraryId.palm","kind":"symbol","navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotPalmLibrary"},{"type":"text","text":" identifier."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/nfc":{"url":"\/documentation\/dotpalmcore\/dotlibraryid\/nfc","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/nfc","title":"DotLibraryId.nfc","kind":"symbol","navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"type":"text","text":" identifier."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DotLibraryId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/document","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/face","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/faceLite","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/nfc","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/palm"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/navigatorTitle","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1faceLite\/title","op":"replace","value":"DotLibraryIdFaceLite"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1faceLite\/fragments","op":"replace","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1face\/title","op":"replace","value":"DotLibraryIdFace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1face\/fragments","op":"replace","value":[{"text":"DotLibraryIdFace","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1document\/title","op":"replace","value":"DotLibraryIdDocument"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1document\/fragments","op":"replace","value":[{"text":"DotLibraryIdDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1palm\/title","op":"replace","value":"DotLibraryIdPalm"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1palm\/fragments","op":"replace","value":[{"text":"DotLibraryIdPalm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1nfc\/title","op":"replace","value":"DotLibraryIdNfc"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1nfc\/fragments","op":"replace","value":[{"text":"DotLibraryIdNfc","kind":"identifier"}]}]}]}