{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","roleHeading":"Class","title":"DotNfcLibraryConfiguration","modules":[{"name":"DotPalmCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotnfclibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotnfclibraryconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"abstract":[{"type":"text","text":"NFC library configuration."}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DotNfcLibraryConfiguration/init":{"kind":"symbol","title":"init","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration\/init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotpalmcore\/dotnfclibraryconfiguration\/init","abstract":[]},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/DotNfcLibraryConfiguration":{"kind":"symbol","title":"DotNfcLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","role":"symbol","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotnfclibraryconfiguration","abstract":[{"text":"NFC library configuration.","type":"text"}]},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration\/init"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}