{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmImageQuality) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmImageQuality"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/init(brightness:sharpness:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/brightness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/sharpness"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/isEqual(_:)"],"generated":true}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmImageQuality"}],"navigatorTitle":[{"kind":"identifier","text":"PalmImageQuality"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","roleHeading":"Class","title":"PalmImageQuality","modules":[{"name":"DotPalmCore"}]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmimagequality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmimagequality"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"abstract":[{"type":"text","text":"Palm image quality."}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmimagequality\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/description","title":"description","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/isEqual(_:)":{"kind":"symbol","title":"isEqual(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/isEqual(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotpalmcore\/palmimagequality\/isequal(_:)","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/brightness":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotpalmcore\/palmimagequality\/brightness","title":"brightness","abstract":[{"type":"text","text":"Brightness value in range [0, 1.0]."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/brightness","type":"topic","role":"symbol","navigatorTitle":[{"text":"brightness","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/sharpness":{"url":"\/documentation\/dotpalmcore\/palmimagequality\/sharpness","role":"symbol","title":"sharpness","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/sharpness","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sharpness"}],"abstract":[{"text":"Sharpness value in range [0, 1.0].","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/hash":{"kind":"symbol","type":"topic","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotpalmcore\/palmimagequality\/hash","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/init(brightness:sharpness:)":{"kind":"symbol","title":"init(brightness:sharpness:)","url":"\/documentation\/dotpalmcore\/palmimagequality\/init(brightness:sharpness:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/init(brightness:sharpness:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"brightness","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBrightness:sharpness:"}],"abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmImageQuality"}],"url":"\/documentation\/dotpalmcore\/palmimagequality","title":"PalmImageQuality","abstract":[{"type":"text","text":"Palm image quality."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmImageQuality"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTPPalmImageQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPPalmImageQuality"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmImageQuality"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/brightness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/sharpness"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/init(brightness:sharpness:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/isEqual(_:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmImageQuality"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1brightness\/title","op":"replace","value":"brightness"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1brightness\/fragments","op":"replace","value":[{"text":"brightness","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1sharpness\/title","op":"replace","value":"sharpness"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1sharpness\/fragments","op":"replace","value":[{"text":"sharpness","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1init(brightness:sharpness:)\/title","op":"replace","value":"initWithBrightness:sharpness:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1init(brightness:sharpness:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBrightness:sharpness:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/title","op":"replace","value":"DOTPPalmImageQuality"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/fragments","op":"replace","value":[{"text":"DOTPPalmImageQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmImageQuality","kind":"identifier"}]}]}]}