{"metadata":{"modules":[{"name":"DotNfc"}],"title":"accessControlProtocol","externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)accessControlProtocol","roleHeading":"Instance Property","navigatorTitle":[{"text":"accessControlProtocol","kind":"identifier"}],"role":"symbol","symbolKind":"property","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"13.0","unavailable":false,"beta":false}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessControlProtocol","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper","text":"AccessControlProtocolWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"accessControlProtocol","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper","text":"AccessControlProtocolWrapper"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/accessControlProtocol"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debuginfo\/accesscontrolprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debuginfo\/accesscontrolprotocol"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper":{"url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper","title":"AccessControlProtocolWrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","type":"topic","abstract":[{"type":"text","text":"Access Control protocol wrapper."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AccessControlProtocolWrapper","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocolWrapper"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DebugInfo/accessControlProtocol":{"kind":"symbol","url":"\/documentation\/dotnfc\/debuginfo\/accesscontrolprotocol","type":"topic","title":"accessControlProtocol","navigatorTitle":[{"text":"accessControlProtocol","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/accessControlProtocol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"accessControlProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper","text":"AccessControlProtocolWrapper"},{"kind":"text","text":"?"}]},"doc://DotNfc/documentation/DotNfc/DebugInfo":{"type":"topic","navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugInfo"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","title":"DebugInfo","url":"\/documentation\/dotnfc\/debuginfo","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"accessControlProtocol"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"accessControlProtocol","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","text":"DOTNAccessControlProtocolWrapper","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper"},{"text":" * ","kind":"text"},{"text":"accessControlProtocol","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/title","value":"DOTNAccessControlProtocolWrapper","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/fragments","value":[{"kind":"identifier","text":"DOTNAccessControlProtocolWrapper"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1accessControlProtocol\/title","value":"accessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1accessControlProtocol\/fragments","value":[{"text":"accessControlProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","value":"DOTNDebugInfo"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}