{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rightEyeOuterCorner"},{"kind":"text","text":": "},{"text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyeCenter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":"?, "},{"text":"rightEyeInnerCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"leftEyeInnerCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?, "},{"text":"leftEyeCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?, "},{"text":"leftEyeOuterCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"noseRoot"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"kind":"text","text":"?, "},{"text":"noseRightBottom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"noseTip"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseLeftBottom","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseBottom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"kind":"text","text":"?, "},{"text":"mouthRightCorner","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthCenter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mouthLeftCorner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?, "},{"text":"mouthUpperEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":"?, "},{"text":"mouthLowerEdge","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rightEyebrowOuterEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyebrowInnerEnd","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"leftEyebrowInnerEnd"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyebrowOuterEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEdge","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"chinTip"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":"?, "},{"text":"leftEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/facekeypoints\/init(righteyeoutercorner:righteyecenter:righteyeinnercorner:lefteyeinnercorner:lefteyecenter:lefteyeoutercorner:noseroot:noserightbottom:nosetip:noseleftbottom:nosebottom:mouthrightcorner:mouthcenter:mouthleftcorner:mouthupperedge:mouthlowe-7q6zy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/init(righteyeoutercorner:righteyecenter:righteyeinnercorner:lefteyeinnercorner:lefteyecenter:lefteyeoutercorner:noseroot:noserightbottom:nosetip:noseleftbottom:nosebottom:mouthrightcorner:mouthcenter:mouthleftcorner:mouthupperedge:mouthlowe-7q6zy"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rightEyeOuterCorner"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rightEyeCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"rightEyeInnerCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?, "},{"text":"leftEyeInnerCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"leftEyeCenter"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"noseRoot","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"noseRightBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseTip","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"noseLeftBottom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseBottom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthRightCorner","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthCenter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mouthLeftCorner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mouthUpperEdge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthLowerEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"rightEyebrowOuterEnd","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"rightEyebrowInnerEnd"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"kind":"text","text":"?, "},{"text":"leftEyebrowInnerEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"leftEyebrowOuterEnd"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"chinTip","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"leftEdge"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(im)initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:","roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"title":"init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)","role":"symbol","navigatorTitle":[{"text":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:","kind":"identifier"}],"symbolKind":"init"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rightEyeOuterCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyeCenter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"rightEyeInnerCorner"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"leftEyeInnerCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyeCenter","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?, "},{"text":"leftEyeOuterCorner","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseRoot","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"noseRightBottom"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"noseTip"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"noseLeftBottom"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"noseBottom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mouthRightCorner"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mouthCenter"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mouthLeftCorner"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"mouthUpperEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mouthLowerEdge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyebrowOuterEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"rightEyebrowInnerEnd","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"leftEyebrowInnerEnd","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEyebrowOuterEnd","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?, "},{"text":"rightEdge","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"chinTip"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"text":"?, ","kind":"text"},{"text":"leftEdge","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/init(righteyeoutercorner:righteyecenter:righteyeinnercorner:lefteyeinnercorner:lefteyecenter:lefteyeoutercorner:noseroot:noserightbottom:nosetip:noseleftbottom:nosebottom:mouthrightcorner:mouthcenter:mouthleftcorner:mouthupperedge:mouthlowe-7q6zy","type":"topic","title":"init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)","kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)","navigatorTitle":[{"kind":"identifier","text":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"url":"\/documentation\/dotfacecore\/facekeypoint","role":"symbol","abstract":[{"type":"text","text":"Face Keypoint"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"title":"FaceKeypoint","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoint","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","title":"FaceKeypoints","url":"\/documentation\/dotfacecore\/facekeypoints","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithRightEyeOuterCorner:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":" *) "},{"text":"rightEyeOuterCorner","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyeCenter:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint"},{"kind":"text","text":" *) "},{"text":"rightEyeCenter","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyeInnerCorner:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rightEyeInnerCorner"},{"text":" ","kind":"text"},{"text":"leftEyeInnerCorner:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"leftEyeInnerCorner"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeCenter:"},{"kind":"text","text":"("},{"text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":" *) ","kind":"text"},{"text":"leftEyeCenter","kind":"internalParam"},{"kind":"text","text":" "},{"text":"leftEyeOuterCorner:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"leftEyeOuterCorner"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noseRoot:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"noseRoot","kind":"internalParam"},{"kind":"text","text":" "},{"text":"noseRightBottom:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"noseRightBottom"},{"kind":"text","text":" "},{"text":"noseTip:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"noseTip","kind":"internalParam"},{"kind":"text","text":" "},{"text":"noseLeftBottom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"noseLeftBottom"},{"kind":"text","text":" "},{"text":"noseBottom:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"noseBottom","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mouthRightCorner:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"DOTFFaceKeypoint"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mouthRightCorner"},{"text":" ","kind":"text"},{"text":"mouthCenter:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mouthCenter","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mouthLeftCorner:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint"},{"text":" *) ","kind":"text"},{"text":"mouthLeftCorner","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mouthUpperEdge:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"mouthUpperEdge"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthLowerEdge:"},{"text":"(","kind":"text"},{"text":"DOTFFaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mouthLowerEdge","kind":"internalParam"},{"kind":"text","text":" "},{"text":"rightEyebrowOuterEnd:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"text":" *) ","kind":"text"},{"text":"rightEyebrowOuterEnd","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"rightEyebrowInnerEnd:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":" *) ","kind":"text"},{"text":"rightEyebrowInnerEnd","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyebrowInnerEnd:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"leftEyebrowInnerEnd"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyebrowOuterEnd:"},{"text":"(","kind":"text"},{"text":"DOTFFaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"leftEyebrowOuterEnd"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEdge:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"rightEdge","kind":"internalParam"},{"kind":"text","text":" "},{"text":"chinTip:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"chinTip"},{"text":" ","kind":"text"},{"text":"leftEdge:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"DOTFFaceKeypoint"},{"text":" *) ","kind":"text"},{"text":"leftEdge","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)\/title","value":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1init(rightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithRightEyeOuterCorner:rightEyeCenter:rightEyeInnerCorner:leftEyeInnerCorner:leftEyeCenter:leftEyeOuterCorner:noseRoot:noseRightBottom:noseTip:noseLeftBottom:noseBottom:mouthRightCorner:mouthCenter:mouthLeftCorner:mouthUpperEdge:mouthLowerEdge:rightEyebrowOuterEnd:rightEyebrowInnerEnd:leftEyebrowInnerEnd:leftEyebrowOuterEnd:rightEdge:chinTip:leftEdge:","kind":"identifier"}]},{"value":"DOTFFaceKeypoint","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","value":"DOTFFaceKeypoints","op":"replace"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace"}]}]}