{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeOuterCorner","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/lefteyeoutercorner"]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/lefteyeoutercorner"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Left eye outer corner."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeOuterCorner"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"leftEyeOuterCorner","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)leftEyeOuterCorner","title":"leftEyeOuterCorner"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}],"role":"collection","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEyeOuterCorner":{"abstract":[{"type":"text","text":"Left eye outer corner."}],"type":"topic","title":"leftEyeOuterCorner","url":"\/documentation\/dotfacecore\/facekeypoints\/lefteyeoutercorner","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"leftEyeOuterCorner"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeOuterCorner","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeOuterCorner"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"url":"\/documentation\/dotfacecore\/facekeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","role":"symbol","title":"FaceKeypoints","type":"topic","abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoints"}],"kind":"symbol","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"url":"\/documentation\/dotfacecore\/facekeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","role":"symbol","title":"FaceKeypoint","type":"topic","abstract":[{"type":"text","text":"Face Keypoint"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceKeypoint","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"leftEyeOuterCorner","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"leftEyeOuterCorner"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint"},{"text":" * ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"leftEyeOuterCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeOuterCorner\/title"},{"value":[{"text":"leftEyeOuterCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeOuterCorner\/fragments"},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"op":"replace","value":"DOTFFaceKeypoint","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}