{"variants":[{"paths":["\/documentation\/dotfacecore\/facekeypoints\/mouthcenter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/mouthcenter"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouthCenter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)mouthCenter","role":"symbol","title":"mouthCenter","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"mouthCenter"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthCenter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Mouth center."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","title":"FaceKeypoints","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoint","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","abstract":[{"text":"Face Keypoint","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"kind":"symbol","title":"FaceKeypoint"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthCenter":{"url":"\/documentation\/dotfacecore\/facekeypoints\/mouthcenter","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthCenter","title":"mouthCenter","kind":"symbol","role":"symbol","abstract":[{"text":"Mouth center.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthCenter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mouthCenter","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"mouthCenter"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"mouthCenter"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"text":" * ","kind":"text"},{"text":"mouthCenter","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle"},{"value":"DOTFFaceKeypoint","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments"},{"value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle"},{"value":"mouthCenter","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthCenter\/title"},{"value":[{"kind":"identifier","text":"mouthCenter"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthCenter\/fragments"}]}]}