{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseTip","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Nose tip.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/facekeypoints\/nosetip"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/nosetip"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noseTip"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)noseTip","roleHeading":"Instance Property","title":"noseTip","navigatorTitle":[{"text":"noseTip","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noseTip"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"kind":"text","text":"?"}],"symbolKind":"property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"url":"\/documentation\/dotfacecore\/facekeypoints","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoints"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"navigatorTitle":[{"kind":"identifier","text":"FaceKeypoints"}],"title":"FaceKeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/noseTip":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseTip","url":"\/documentation\/dotfacecore\/facekeypoints\/nosetip","abstract":[{"type":"text","text":"Nose tip."}],"type":"topic","role":"symbol","kind":"symbol","title":"noseTip","navigatorTitle":[{"kind":"identifier","text":"noseTip"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noseTip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"url":"\/documentation\/dotfacecore\/facekeypoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoint","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face Keypoint"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","title":"FaceKeypoint","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"noseTip","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"noseTip","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","text":"DOTFFaceKeypoint"},{"kind":"text","text":" * "},{"text":"noseTip","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseTip\/title","op":"replace","value":"noseTip"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseTip\/fragments","op":"replace","value":[{"kind":"identifier","text":"noseTip"}]},{"value":"DOTFFaceKeypoint","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}]},{"value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle"}]}]}