{"sections":[],"abstract":[{"text":"Right eyebrow outer end.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"rightEyebrowOuterEnd","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightEyebrowOuterEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"rightEyebrowOuterEnd","symbolKind":"property","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)rightEyebrowOuterEnd"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightEyebrowOuterEnd"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowOuterEnd"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyebrowouterend"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyebrowouterend"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"url":"\/documentation\/dotfacecore\/facekeypoint","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoint"}],"type":"topic","title":"FaceKeypoint","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoint"}],"abstract":[{"text":"Face Keypoint","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"url":"\/documentation\/dotfacecore\/facekeypoints","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoints"}],"type":"topic","title":"FaceKeypoints","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoints"}],"abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyebrowOuterEnd":{"navigatorTitle":[{"text":"rightEyebrowOuterEnd","kind":"identifier"}],"abstract":[{"text":"Right eyebrow outer end.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyebrowOuterEnd","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyebrowOuterEnd","title":"rightEyebrowOuterEnd","kind":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyebrowouterend","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"rightEyebrowOuterEnd"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"rightEyebrowOuterEnd"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"rightEyebrowOuterEnd"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","op":"replace","value":"DOTFFaceKeypoint"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}]},{"value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle"},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle"},{"op":"replace","value":"rightEyebrowOuterEnd","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyebrowOuterEnd\/title"},{"value":[{"text":"rightEyebrowOuterEnd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyebrowOuterEnd\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}