{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyeoutercorner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyeoutercorner"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"metadata":{"navigatorTitle":[{"text":"rightEyeOuterCorner","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"rightEyeOuterCorner","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)rightEyeOuterCorner","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightEyeOuterCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"kind":"text","text":"?"}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeOuterCorner"},"abstract":[{"text":"Right eye outer corner.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightEyeOuterCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoints","abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"role":"symbol","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","kind":"symbol","title":"FaceKeypoints","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","url":"\/documentation\/dotfacecore\/facekeypoint","type":"topic","title":"FaceKeypoint","abstract":[{"text":"Face Keypoint","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoint"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoint"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyeOuterCorner":{"title":"rightEyeOuterCorner","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Right eye outer corner."}],"role":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyeoutercorner","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeOuterCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"rightEyeOuterCorner","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeOuterCorner"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"rightEyeOuterCorner"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"rightEyeOuterCorner"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint"},{"text":" * ","kind":"text"},{"text":"rightEyeOuterCorner","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","op":"replace","value":"DOTFFaceKeypoints"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","value":"DOTFFaceKeypoint"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeOuterCorner\/title","value":"rightEyeOuterCorner"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeOuterCorner\/fragments","value":[{"kind":"identifier","text":"rightEyeOuterCorner"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}