{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validateAlways","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/validateAlways","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzvalidation\/validatealways"]},{"paths":["\/documentation\/dotdocument\/mrzvalidation\/validatealways"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"MRZ is always validated.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@E@DOTDMrzValidation@DOTDMrzValidationValidateAlways","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"validateAlways","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationValidateAlways"}],"symbolKind":"case","roleHeading":"Case","title":"MrzValidation.validateAlways"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"]]},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/MrzValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzValidation","kind":"identifier"}],"title":"MrzValidation","type":"topic","url":"\/documentation\/dotdocument\/mrzvalidation"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzValidation/validateAlways":{"role":"symbol","navigatorTitle":[{"text":"DOTDMrzValidationValidateAlways","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validateAlways"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzvalidation\/validatealways","type":"topic","abstract":[{"text":"MRZ is always validated.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/validateAlways","title":"MrzValidation.validateAlways"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTDMrzValidationValidateAlways"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"DOTDMrzValidationValidateAlways","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTDMrzValidationValidateAlways","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1validateAlways\/title","value":"DOTDMrzValidationValidateAlways"},{"value":[{"text":"DOTDMrzValidationValidateAlways","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1validateAlways\/fragments"}]}]}