{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/detect(image:limit:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"detectWithImage:limit:error:"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector(im)detectWithImage:limit:error:","title":"detect(image:limit:)","modules":[{"name":"DotPalmCore"}]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmdetector\/detect(image:limit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmdetector\/detect(image:limit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limit"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = 1) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Palm","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"]","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Image on which is performed the detection. Terminates if "},{"code":"image","type":"codeVoice"},{"type":"text","text":" is not in "},{"code":".rawBgra","type":"codeVoice"},{"type":"text","text":" format."}],"type":"paragraph"}],"name":"image"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limit the number of palms to detect. Currently is supported to detect only one palm."}]}],"name":"limit"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Array of detected palms."}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This method should be called on the background thread.","type":"text"}]},{"style":"note","content":[{"inlineContent":[{"text":"Throws an error if ","type":"text"},{"type":"codeVoice","code":"PalmDetector"},{"text":" fails to execute palm detection.","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Throws"}]}],"kind":"symbol","abstract":[{"text":"Detect palms in an image.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"title":"PalmDetector","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/detect(image:limit:)":{"url":"\/documentation\/dotpalmcore\/palmdetector\/detect(image:limit:)","title":"detect(image:limit:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/detect(image:limit:)","role":"symbol","abstract":[{"type":"text","text":"Detect palms in an image."}],"navigatorTitle":[{"text":"detectWithImage:limit:error:","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"title":"Image","type":"topic","url":"\/documentation\/dotpalmcore\/image","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"title":"PalmDetector.Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","type":"topic","abstract":[{"type":"text","text":"Result of the palm detection process."}],"kind":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"detectWithImage:limit:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithImage:limit:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTPPalmDetectorPalm *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"limit:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Image on which is performed the detection. Terminates if ","type":"text"},{"type":"codeVoice","code":"image"},{"text":" is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}]}],"name":"image"},{"content":[{"inlineContent":[{"type":"text","text":"Limit the number of palms to detect. Currently is supported to detect only one palm."}],"type":"paragraph"}],"name":"limit"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter."}]}],"name":"error"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of detected palms."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"},{"value":"detectWithImage:limit:error:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1detect(image:limit:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithImage:limit:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1detect(image:limit:)\/fragments"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}