{"sections":[],"metadata":{"symbolKind":"method","externalID":"c:@CM@DotDocument@objc(cs)DOTDDetectionPosition(cm)fromRectangle:","modules":[{"name":"DotDocument"}],"title":"from(rectangle:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"role":"symbol","navigatorTitle":[{"text":"fromRectangle:","kind":"identifier"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/detectionposition\/from(rectangle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/detectionposition\/from(rectangle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/from(rectangle:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.12.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/from(rectangle:)":{"title":"from(rectangle:)","navigatorTitle":[{"text":"fromRectangle:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/detectionposition\/from(rectangle:)","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/from(rectangle:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"text":"rectangle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"abstract":[]},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","abstract":[{"type":"text","text":"Position of the document card in the image."}],"url":"\/documentation\/dotdocument\/detectionposition","kind":"symbol","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotdocument\/rectangledouble","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"title":"DocumentDetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDetector"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","url":"\/documentation\/dotdocument\/documentdetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"fromRectangle:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"fromRectangle:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"typeIdentifier","text":"DOTDDetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromRectangle:"},{"text":"(","kind":"text"},{"text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rectangle"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"fromRectangle:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1from(rectangle:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1from(rectangle:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromRectangle:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDDetectionPosition"},{"value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","value":"DOTDDocumentDetector","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}