{"metadata":{"externalID":"s:11DotFaceCore0B8KeypointC8position5scoreAC0aC011PointDoubleC_SdSgtcfc","title":"init(position:score:)","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"text":"score","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":"?)","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/init(position:score:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","text":"PointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"score"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoint\/init(position:score:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}],"role":"collection","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"url":"\/documentation\/dotfacecore\/pointdouble","role":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","title":"PointDouble"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint/init(position:score:)":{"abstract":[],"role":"symbol","kind":"symbol","type":"topic","title":"init(position:score:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/init(position:score:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"score"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"?)","kind":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoint\/init(position:score:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"url":"\/documentation\/dotfacecore\/facekeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","role":"symbol","title":"FaceKeypoint","type":"topic","abstract":[{"type":"text","text":"Face Keypoint"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceKeypoint","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","value":"DOTFFaceKeypoint"},{"value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}