{"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/!=(_:_:)"],"generated":true,"title":"Operators"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfckey\/error\/equatable-implementations"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"DotNfc"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","title":"NfcKey.Error","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error","url":"\/documentation\/dotnfc\/nfckey\/error","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey":{"url":"\/documentation\/dotnfc\/nfckey","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcKey"}],"abstract":[{"type":"text","text":"NFC key created from document number, date of expiry and date of birth."}],"type":"topic","role":"symbol","title":"NfcKey","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","navigatorTitle":[{"text":"NfcKey","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error/!=(_:_:)":{"url":"\/documentation\/dotnfc\/nfckey\/error\/!=(_:_:)","type":"topic","role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/!=(_:_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace"}]}]}