{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init","interfaceLanguage":"occ"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration"]]},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"symbolKind":"method","title":"init","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration(im)init","role":"symbol","roleHeading":"Instance Method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfaceeyegazelivenessmoduleconfiguration\/init"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceEyeGazeLivenessModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotfaceeyegazelivenessmoduleconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"kind":"symbol","title":"DotFaceEyeGazeLivenessModuleConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceEyeGazeLivenessModuleConfiguration/init":{"title":"init","abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfaceeyegazelivenessmoduleconfiguration\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DotFaceEyeGazeLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}