{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Result","preciseIdentifier":"s:11DotFaceLite0B8DetectorC6ResultC","text":"Result"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/facedetectorresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/facedetectorresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/faceDetectorResult","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Face detection result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceLite0B8DetectorC6ResultC"}],"title":"faceDetectorResult","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters(py)faceDetectorResult","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"faceDetectorResult"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 6.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Result":{"role":"symbol","title":"FaceDetector.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the face detection operation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotfacelite\/facedetector\/result"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"role":"symbol","title":"FaceAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/faceDetectorResult":{"role":"symbol","title":"faceDetectorResult","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceLite0B8DetectorC6ResultC"}],"abstract":[{"type":"text","text":"Face detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/faceDetectorResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceDetectorResult"}],"url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/facedetectorresult"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"role":"symbol","title":"FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect face in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"url":"\/documentation\/dotfacelite\/facedetector"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceDetectorResult":{"role":"symbol","title":"DOTFLFaceDetectorResult","fragments":[{"kind":"identifier","text":"DOTFLFaceDetectorResult"}],"abstract":[{"type":"text","text":"Result of the face detection operation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotflfacedetectorresult"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","title":"FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"faceDetectorResult"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"faceDetectorResult"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorResult","text":"DOTFLFaceDetectorResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"faceDetectorResult"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","value":"DOTFLFaceAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1faceDetectorResult\/title","value":"faceDetectorResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1faceDetectorResult\/fragments","value":[{"kind":"identifier","text":"faceDetectorResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}