{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus(py)hash","title":"hash","symbolKind":"property","modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"platforms":[{"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"iOS","beta":false}]},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/hash","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/hash"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataAuthenticationStatus"}],"abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"kind":"symbol","role":"symbol","title":"DataAuthenticationStatus","url":"\/documentation\/dotnfc\/dataauthenticationstatus"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/hash":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/hash","title":"hash","type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/hash","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hash"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DOTNDataAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","op":"replace","value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}