{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCaptureMode","text":"CaptureMode","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CaptureMode"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults"]]},"sections":[],"metadata":{"roleHeading":"Type Property","title":"captureMode","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCaptureMode","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC8DefaultsV11captureModeAA0eK0OvpZ"},"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults\/capturemode"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults\/captureMode"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/Defaults":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Defaults"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults","role":"symbol","navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration.Defaults","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CaptureMode":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Capture mode."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CaptureMode","url":"\/documentation\/dotfacelite\/capturemode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"title":"CaptureMode"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/Defaults/captureMode":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults\/captureMode","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults\/capturemode","title":"captureMode","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCaptureMode","text":"CaptureMode","kind":"typeIdentifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"FaceAutoCaptureViewController.Configuration","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"type":"topic","title":"FaceAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","abstract":[{"text":"version: 8.3.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTCaptureMode","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CaptureMode\/title"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CaptureMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}