{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration"]]},"sections":[],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration(im)init","role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration\/init"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"type":"topic","kind":"symbol","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","abstract":[{"type":"text","text":"version: 9.5.0"}],"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentBarcodeModuleConfiguration":{"role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentBarcodeModuleConfiguration/init":{"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration\/init","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration\/init","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}]}]}