{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageformat\/jpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageformat\/jpeg"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"roleHeading":"Case","title":"ImageFormat.jpeg","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg","modules":[{"name":"DotDocument"}]},"abstract":[{"text":"JPEG compressed image format","type":"text"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/ImageFormat/jpeg":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}],"type":"topic","title":"ImageFormat.jpeg","abstract":[{"type":"text","text":"JPEG compressed image format"}],"url":"\/documentation\/dotdocument\/imageformat\/jpeg","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]},"doc://DotDocument/documentation/DotDocument/ImageFormat":{"navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageformat","title":"ImageFormat","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat","abstract":[{"type":"text","text":"Supported image formats."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTImageFormatJpeg"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg\/title","op":"replace","value":"DOTImageFormatJpeg"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg\/fragments","op":"replace","value":[{"text":"DOTImageFormatJpeg","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/fragments","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]}]}]}