{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgr","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The 3 bytes of color image pixel:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"0th byte: BB - blue","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"1st byte: GG - green","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"2nd byte: RR - red","type":"text"}]}]}],"type":"unorderedList"}],"kind":"content"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgr","role":"symbol","title":"ImageFormat.rawBgr","modules":[{"name":"DotDocument"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}]},"variants":[{"paths":["\/documentation\/dotdocument\/imageformat\/rawbgr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/imageformat\/rawbgr"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgr","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/ImageFormat/rawBgr":{"role":"symbol","navigatorTitle":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}],"kind":"symbol","title":"ImageFormat.rawBgr","url":"\/documentation\/dotdocument\/imageformat\/rawbgr","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/rawBgr","abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgr","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageFormat":{"navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageformat","title":"ImageFormat","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat","abstract":[{"type":"text","text":"Supported image formats."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTImageFormatRawBgr"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgr\/title","op":"replace","value":"DOTImageFormatRawBgr"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1rawBgr\/fragments","op":"replace","value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/navigatorTitle","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]}]}]}