{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/configuration-swift.property"},"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"kind":"symbol","abstract":[{"text":"Current configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.property"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"configuration","platforms":[{"message":"Use MultiRangeLivenessViewController instead.","beta":false,"deprecated":true,"unavailable":false}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC","text":"Configuration"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController(py)configuration","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the UI Eye Gaze Liveness component."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessConfiguration"}],"type":"topic","title":"DOTFEyeGazeLivenessConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/configuration-swift.property":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.property","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/configuration-swift.property","abstract":[{"text":"Current configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"type":"topic","title":"configuration"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","title":"EyeGazeLivenessViewController","abstract":[{"text":"UI Eye Gaze Liveness component.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"role":"symbol","deprecated":true},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","abstract":[{"text":"Configuration options for the UI Eye Gaze Liveness component.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","title":"EyeGazeLivenessViewController.Configuration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"deprecated":true,"unavailable":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"configuration","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"configuration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","text":"DOTFEyeGazeLivenessConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"path":"\/deprecationSummary"},{"op":"replace","value":"configuration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1configuration-swift.property\/title"},{"op":"replace","value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1configuration-swift.property\/fragments"},{"op":"replace","value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}