{"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/stop()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/stop()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/stop()"},"abstract":[{"type":"text","text":"Stop the eye gaze liveness process."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"role":"symbol","platforms":[{"deprecated":true,"message":"Use MultiRangeLivenessViewController instead.","unavailable":false,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"stop"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController(im)stop","title":"stop()"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/stop()":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/stop()","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stop"}],"deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/stop()","abstract":[{"text":"Stop the eye gaze liveness process.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"type":"topic","title":"stop()"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","title":"EyeGazeLivenessViewController","abstract":[{"text":"UI Eye Gaze Liveness component.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"role":"symbol","deprecated":true},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"deprecated":true,"unavailable":false,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"stop","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"op":"replace","path":"\/deprecationSummary"},{"value":"stop","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1stop()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1stop()\/fragments"},{"value":"DOTFEyeGazeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle"}]}]}