{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFaceDetectionModuleConfiguration","externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"class"},"abstract":[{"text":"Face detection module configuration.","type":"text"}],"topicSections":[{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Fast"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Fast"],"type":"inheritedBy"},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration"},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfigurationFast":{"fragments":[{"text":"DotFaceDetectionModuleConfigurationFast","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationFast","abstract":[{"text":"Face detection fast module.","type":"text"}],"type":"topic","title":"DotFaceDetectionModuleConfigurationFast","role":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfigurationfast","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration/Balanced":{"navigatorTitle":[{"kind":"identifier","text":"Balanced"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Balanced","type":"topic","title":"DotFaceDetectionModuleConfiguration.Balanced","abstract":[{"text":"Face detection balanced module.","type":"text"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/balanced","kind":"symbol"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration/Fast":{"navigatorTitle":[{"text":"Fast","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Fast","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Fast","type":"topic","title":"DotFaceDetectionModuleConfiguration.Fast","abstract":[{"type":"text","text":"Face detection fast module."}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/fast","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration":{"kind":"symbol","role":"symbol","title":"DotFaceDetectionModuleConfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"type":"topic","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration"},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfigurationBalanced":{"kind":"symbol","role":"symbol","title":"DotFaceDetectionModuleConfigurationBalanced","abstract":[{"type":"text","text":"Face detection balanced module."}],"type":"topic","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfigurationbalanced","fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationBalanced"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceDetectionModuleConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},{"op":"replace","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationBalanced","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationFast"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}]}]}