{"metadata":{"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionalDetails","kind":"identifier"}],"role":"symbol","roleHeading":"Class","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}],"title":"OptionalDetails"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/optionaldetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/optionaldetails"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"text":"Contents of DG13 - Optional details.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","title":"Conforms To"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/init(content:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/content","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/hash"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNOptionalDetails) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalDetails"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Structured content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"],"anchor":"Structured-content"}],"references":{"doc://DotNfc/documentation/DotNfc/OptionalDetails/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/description","abstract":[],"type":"topic","title":"description","role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails\/description","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"title":"AdditionalPersonalDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails","role":"symbol","navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","abstract":[{"text":"Contents of DG12 - Additional document details.","type":"text"}],"type":"topic","title":"AdditionalDocumentDetails","role":"symbol","url":"\/documentation\/dotnfc\/additionaldocumentdetails","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/OptionalDetails/content":{"navigatorTitle":[{"kind":"identifier","text":"content"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/content","abstract":[{"text":"Raw content.","type":"text"}],"type":"topic","title":"content","role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails\/content","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","abstract":[{"text":"Contents of DG7 - Displayed signature or usual mark.","type":"text"}],"type":"topic","title":"DisplayedSignatureOrUsualMark","role":"symbol","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/OptionalDetails/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/hash","abstract":[],"type":"topic","title":"hash","role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails\/hash","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/OptionalDetails/init(content:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithContent:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/init(content:)","abstract":[],"type":"topic","title":"init(content:)","role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails\/init(content:)","kind":"symbol"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"title":"MachineReadableZoneInformation","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/machinereadablezoneinformation","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","abstract":[{"text":"Contents of DG13 - Optional details.","type":"text"}],"type":"topic","title":"OptionalDetails","role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"abstract":[{"text":"Contents of DG2 - Face image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"title":"EncodedIdentificationFeaturesFace","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace"},"doc://DotNfc/documentation/DotNfc/OptionalDetails/isEqual(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/isEqual(_:)","abstract":[],"type":"topic","title":"isEqual(_:)","role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails\/isequal(_:)","kind":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTNOptionalDetails"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}]},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/content","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/hash"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/init(content:)","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/isEqual(_:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"],"generated":true,"title":"Structured content","anchor":"Structured-content"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNOptionalDetails","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1description\/fragments","op":"replace"},{"value":"DOTNAdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/navigatorTitle","op":"replace"},{"value":"DOTNAdditionalDocumentDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","op":"replace"},{"value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNAdditionalDocumentDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1content\/title","value":"content"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1content\/fragments","value":[{"kind":"identifier","text":"content"}]},{"value":"DOTNDisplayedSignatureOrUsualMark","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1init(content:)\/title","value":"initWithContent:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1init(content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithContent:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNOptionalDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTNEncodedIdentificationFeaturesFace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/navigatorTitle","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}]}]}