{"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","role":"collectionGroup","title":"DotSdkError Implementations"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervaldouble\/error\/dotsdkerror-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/errorDescription"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/composeWithInternalError()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error/composeWithInternalError()":{"kind":"symbol","role":"symbol","title":"composeWithInternalError()","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/intervaldouble\/error\/composewithinternalerror()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/composeWithInternalError()"},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error/description":{"kind":"symbol","role":"symbol","title":"description","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/intervaldouble\/error\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/description"},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error":{"kind":"symbol","role":"symbol","title":"IntervalDouble.Error","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/intervaldouble\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error"},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error/errorDescription":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/errorDescription","type":"topic","title":"errorDescription","abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/intervaldouble\/error\/errordescription","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/IntervalDouble":{"kind":"symbol","role":"symbol","title":"IntervalDouble","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotnfc\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}