{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacebackgrounduniformitymoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration\/init","interfaceLanguage":"occ"},"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration(im)init","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceBackgroundUniformityModuleConfiguration/init":{"role":"symbol","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration\/init","url":"\/documentation\/dotpalmcore\/dotfacebackgrounduniformitymoduleconfiguration\/init","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceBackgroundUniformityModuleConfiguration":{"title":"DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotpalmcore\/dotfacebackgrounduniformitymoduleconfiguration","type":"topic","abstract":[{"type":"text","text":"Face background uniformity module."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/title","op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}