{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/ldsMasterFile","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"ldsMasterFile","kind":"identifier"},{"kind":"text","text":": "},{"text":"LdsMasterFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debuginfo\/ldsmasterfile"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debuginfo\/ldsmasterfile"]}],"kind":"symbol","metadata":{"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"13.0","beta":false}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)ldsMasterFile","role":"symbol","title":"ldsMasterFile","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ldsMasterFile","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","kind":"typeIdentifier","text":"LdsMasterFile"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"ldsMasterFile"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo"]]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DebugInfo":{"navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"abstract":[],"title":"DebugInfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DebugInfo","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/debuginfo","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DebugInfo/ldsMasterFile":{"navigatorTitle":[{"kind":"identifier","text":"ldsMasterFile"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ldsMasterFile","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/ldsMasterFile","role":"symbol","url":"\/documentation\/dotnfc\/debuginfo\/ldsmasterfile","abstract":[],"title":"ldsMasterFile","type":"topic"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"LdsMasterFile","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","type":"topic","title":"LdsMasterFile","abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/ldsmasterfile","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LdsMasterFile"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ldsMasterFile","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"ldsMasterFile","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"DOTNLdsMasterFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"ldsMasterFile"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DOTNDebugInfo","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","op":"replace"},{"value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments"},{"value":"ldsMasterFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1ldsMasterFile\/title","op":"replace"},{"op":"replace","value":[{"text":"ldsMasterFile","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1ldsMasterFile\/fragments"},{"op":"replace","value":"DOTNLdsMasterFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace"}]}]}