{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"roleHeading":"Instance Property","symbolKind":"property","title":"dateOfExpiry","modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone(py)dateOfExpiry","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dateOfExpiry","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/dateofexpiry"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/dateofexpiry"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfExpiry","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/dateOfExpiry":{"navigatorTitle":[{"text":"dateOfExpiry","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfExpiry","title":"dateOfExpiry","url":"\/documentation\/dotnfc\/td3machinereadablezone\/dateofexpiry","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"}],"abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","kind":"symbol","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","role":"symbol","title":"MrzDateElementWithCheckDigit"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"title":"Td3MachineReadableZone"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"dateOfExpiry","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"dateOfExpiry","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dateOfExpiry"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfExpiry\/title","value":"dateOfExpiry"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfExpiry\/fragments","value":[{"text":"dateOfExpiry","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone","op":"replace"},{"op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}