{"variants":[{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/documentcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/documentcode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)documentCode","title":"documentCode","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"documentCode","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/documentCode"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}],"title":"Td3MachineReadableZone","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"kind":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone/documentCode":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentCode"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"title":"documentCode","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/documentCode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentCode"}],"abstract":[],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/documentcode"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","url":"\/documentation\/dotnfc\/mrzelement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"title":"MrzElement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"documentCode"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"documentCode","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentCode"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1documentCode\/title","value":"documentCode"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1documentCode\/fragments","value":[{"kind":"identifier","text":"documentCode"}]},{"value":"DOTMrzElement","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]}]}]}