{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/hash"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/hash"]},{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)hash","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone/hash":{"kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/hash","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone","type":"topic","title":"Td3MachineReadableZone","role":"symbol","kind":"symbol","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"hash"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1hash\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}