{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"documentCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement"},{"text":", ","kind":"text"},{"text":"passportNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"sex","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"personalNumberOrOtherOptionalData","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzCheckDigit"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)"},"variants":[{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"text":", ","kind":"text"},{"text":"passportNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"personalNumberOrOtherOptionalData","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone(im)initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}],"title":"init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","symbolKind":"init"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElementWithCheckDigit":{"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"title":"MrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzCheckDigit":{"navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzCheckDigit","kind":"symbol","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"title":"MrzCheckDigit","url":"\/documentation\/dotnfc\/mrzcheckdigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"title":"MrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/mrzelement"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)":{"abstract":[],"title":"init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzNameElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passportNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier","text":"MrzElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"personalNumberOrOtherOptionalData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"title":"Td3MachineReadableZone"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","kind":"symbol","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","role":"symbol","title":"MrzDateElementWithCheckDigit"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement":{"navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"title":"MrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrznameelement","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithDocumentCode:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"documentCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"DOTMrzElement"},{"text":" *) ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","kind":"typeIdentifier","text":"DOTMrzNameElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"passportNumber:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"passportNumber","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","text":"DOTMrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"nationality","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dateOfBirth:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dateOfBirth"},{"kind":"text","text":" "},{"text":"sex:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"sex","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dateOfExpiry:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":" *) "},{"text":"dateOfExpiry","kind":"internalParam"},{"kind":"text","text":" "},{"text":"personalNumberOrOtherOptionalData:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit"},{"kind":"text","text":" *) "},{"text":"personalNumberOrOtherOptionalData","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compositeCheckDigit:"},{"text":"(","kind":"text"},{"text":"DOTMrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzCheckDigit"},{"kind":"text","text":" *) "},{"text":"compositeCheckDigit","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title","op":"replace","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","op":"replace","value":"DOTTd3MachineReadableZone"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/title","value":"DOTMrzNameElement","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/fragments"}]}]}