{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/issuingstateororganization"]},{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/issuingstateororganization"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"title":"issuingStateOrOrganization","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"}],"externalID":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone(py)issuingStateOrOrganization"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/issuingStateOrOrganization","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone":{"url":"\/documentation\/dotnfc\/td3machinereadablezone","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"title":"Td3MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"kind":"symbol","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/issuingStateOrOrganization":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"title":"issuingStateOrOrganization","url":"\/documentation\/dotnfc\/td3machinereadablezone\/issuingstateororganization","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/issuingStateOrOrganization","navigatorTitle":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/mrzelement","type":"topic","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"issuingStateOrOrganization","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"issuingStateOrOrganization","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1issuingStateOrOrganization\/title","op":"replace","value":"issuingStateOrOrganization"},{"value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1issuingStateOrOrganization\/fragments","op":"replace"},{"op":"replace","value":"DOTMrzElement","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}