{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/name"},"variants":[{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"title":"name","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)name","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"title":"Td3MachineReadableZone","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/td3machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}],"abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/MrzNameElement":{"abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"title":"MrzNameElement","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/mrznameelement","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement"},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone/name":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/name","url":"\/documentation\/dotnfc\/td3machinereadablezone\/name","navigatorTitle":[{"kind":"identifier","text":"name"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","kind":"typeIdentifier","text":"MrzNameElement"}],"abstract":[],"title":"name","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"name","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"DOTMrzNameElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","op":"replace","value":"DOTTd3MachineReadableZone"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/title","op":"replace","value":"DOTMrzNameElement"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzNameElement"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTMrzNameElement"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1name\/title","op":"replace","value":"name"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1name\/fragments","op":"replace","value":[{"kind":"identifier","text":"name"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}