{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passportNumber"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone(py)passportNumber","role":"symbol","title":"passportNumber","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"passportNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"passportNumber","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/passportnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/passportnumber"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/passportNumber"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/passportNumber":{"type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passportNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/passportnumber","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/passportNumber","title":"passportNumber","navigatorTitle":[{"kind":"identifier","text":"passportNumber"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.2.0","type":"text"}],"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone":{"url":"\/documentation\/dotnfc\/td3machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","title":"Td3MachineReadableZone","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElementWithCheckDigit":{"kind":"symbol","title":"MrzElementWithCheckDigit","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithCheckDigit"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"passportNumber","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"passportNumber"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"passportNumber"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1passportNumber\/title","value":"passportNumber"},{"op":"replace","value":[{"kind":"identifier","text":"passportNumber"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1passportNumber\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title","op":"replace","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}