{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecapturestyle\/defaults"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/Defaults","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/Defaults\/backgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/Defaults\/trackingCircleColor"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"title":"FaceSimpleCaptureStyle.Defaults","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:11DotFaceCore0B18SimpleCaptureStyleC8DefaultsV","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureStyle/Defaults/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/Defaults\/backgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facesimplecapturestyle\/defaults\/backgroundcolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureStyle":{"role":"symbol","title":"FaceSimpleCaptureStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureStyle"}],"abstract":[{"type":"text","text":"Customization options for the face simple capture user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureStyle"}],"url":"\/documentation\/dotfacecore\/facesimplecapturestyle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureStyle/Defaults":{"role":"symbol","title":"FaceSimpleCaptureStyle.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacecore\/facesimplecapturestyle\/defaults"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureStyle/Defaults/trackingCircleColor":{"role":"symbol","title":"trackingCircleColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingCircleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/Defaults\/trackingCircleColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facesimplecapturestyle\/defaults\/trackingcirclecolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureStyle\/title","value":"DOTFFaceSimpleCaptureStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureStyle\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}