{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingCircleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecapturestyle\/trackingcirclecolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facesimplecapturestyle\/trackingcirclecolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/trackingCircleColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tracking circle color."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingCircleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"trackingCircleColor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureStyle(py)trackingCircleColor","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"trackingCircleColor"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureStyle/trackingCircleColor":{"role":"symbol","title":"trackingCircleColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"trackingCircleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Tracking circle color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle\/trackingCircleColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"trackingCircleColor"}],"url":"\/documentation\/dotfacecore\/facesimplecapturestyle\/trackingcirclecolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureStyle":{"role":"symbol","title":"FaceSimpleCaptureStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureStyle"}],"abstract":[{"type":"text","text":"Customization options for the face simple capture user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureStyle"}],"url":"\/documentation\/dotfacecore\/facesimplecapturestyle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.0.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"trackingCircleColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"trackingCircleColor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"trackingCircleColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureStyle~1trackingCircleColor\/title","value":"trackingCircleColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureStyle~1trackingCircleColor\/fragments","value":[{"kind":"identifier","text":"trackingCircleColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureStyle\/title","value":"DOTFFaceSimpleCaptureStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureStyle\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}