{"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topRight"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"symbolKind":"property","title":"topRight","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)topRight"},"variants":[{"paths":["\/documentation\/dotfacelite\/corners\/topright"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/corners\/topright"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Top right corner point."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble","text":"PointDouble"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/topRight","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Corners":{"role":"symbol","url":"\/documentation\/dotfacelite\/corners","type":"topic","title":"Corners","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners"},"doc://DotFaceLite/documentation/DotFaceLite/Corners/topRight":{"navigatorTitle":[{"text":"topRight","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Top right corner point."}],"role":"symbol","title":"topRight","kind":"symbol","url":"\/documentation\/dotfacelite\/corners\/topright","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/topRight","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 8.8.0","type":"text"}],"type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotfacelite\/pointdouble","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble","type":"topic","title":"PointDouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"topRight","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"topRight","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"topRight","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace"},{"value":"topRight","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1topRight\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1topRight\/fragments","value":[{"kind":"identifier","text":"topRight"}]},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/title"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/fragments"}]}]}