{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"required":true,"role":"symbol","title":"dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureFrameParametersValidator(py)dependencyIdentifiers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator\/dependencyIdentifiers"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator\/dependencyidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator\/dependencyidentifiers"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"> { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParametersValidator":{"title":"FaceAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParametersValidator"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParametersValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParametersValidator/dependencyIdentifiers":{"url":"\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator\/dependencyidentifiers","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","role":"symbol","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic","kind":"symbol","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"title":"FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dependencyIdentifiers","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFLFaceAutoCaptureFrameParametersValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureFrameParametersValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParametersValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/navigatorTitle"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/title"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/fragments"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"}]}]}