{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minTemplateExtractionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"navigatorTitle":[{"text":"minTemplateExtractionQuality","kind":"identifier"}],"symbolKind":"property","title":"minTemplateExtractionQuality","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds(py)minTemplateExtractionQuality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minTemplateExtractionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/mintemplateextractionquality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/mintemplateextractionquality"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minTemplateExtractionQuality","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Minimal valid template extraction quality of the detected palm.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low template extraction quality.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high template extraction quality.","type":"text"}],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/minTemplateExtractionQuality":{"navigatorTitle":[{"kind":"identifier","text":"minTemplateExtractionQuality"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minTemplateExtractionQuality","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/mintemplateextractionquality","title":"minTemplateExtractionQuality","type":"topic","abstract":[{"text":"Minimal valid template extraction quality of the detected palm.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low template extraction quality.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high template extraction quality.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minTemplateExtractionQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}]},"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"title":"WrappedDouble","url":"\/documentation\/dotpalmcore\/wrappeddouble","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","title":"PalmAutoCaptureQualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","type":"topic","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minTemplateExtractionQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"minTemplateExtractionQuality","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","text":"DOTWrappedDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"minTemplateExtractionQuality"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minTemplateExtractionQuality\/title","value":"minTemplateExtractionQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minTemplateExtractionQuality\/fragments","value":[{"kind":"identifier","text":"minTemplateExtractionQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/fragments","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","value":"DOTPPalmAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholds"}],"op":"replace"}]}]}