{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/init(score:preconditionsMet:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/preconditionsMet","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/score"],"title":"Instance Properties"}],"seeAlsoSections":[{"generated":true,"title":"Face evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceattribute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceattribute"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceAttribute) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","role":"symbol","roleHeading":"Class","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAttribute"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"title":"FaceAttribute","symbolKind":"class"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"role":"symbol","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"title":"HeadPose","url":"\/documentation\/dotfacecore\/headpose","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"kind":"symbol","title":"FaceQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQualityQuery"}],"abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/facequalityquery","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAttribute"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"url":"\/documentation\/dotfacecore\/faceattribute","type":"topic","title":"FaceAttribute"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"url":"\/documentation\/dotfacecore\/faceimagequality","type":"topic","title":"FaceImageQuality"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/init(score:preconditionsMet:)":{"title":"init(score:preconditionsMet:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"score","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"preconditionsMet","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithScore:preconditionsMet:"}],"url":"\/documentation\/dotfacecore\/faceattribute\/init(score:preconditionsmet:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/init(score:preconditionsMet:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"title":"FaceQuality","url":"\/documentation\/dotfacecore\/facequality","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/score":{"abstract":[{"text":"Face attribute score.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/score","role":"symbol","navigatorTitle":[{"text":"score","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceattribute\/score","title":"score","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"score"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAspects","kind":"identifier"}],"title":"FaceAspects","url":"\/documentation\/dotfacecore\/faceaspects","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/preconditionsMet":{"type":"topic","abstract":[{"type":"text","text":"This is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"preconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"preconditionsMet","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/preconditionsMet","kind":"symbol","url":"\/documentation\/dotfacecore\/faceattribute\/preconditionsmet","navigatorTitle":[{"text":"preconditionsMet","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"role":"symbol","navigatorTitle":[{"text":"Expression","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Expression","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"url":"\/documentation\/dotfacecore\/expression","type":"topic","title":"Expression"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseAttribute"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"title":"HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPoseQuery"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HeadPoseQuery","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"title":"HeadPoseQuery","url":"\/documentation\/dotfacecore\/headposequery","type":"topic"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WearablesQuery","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/wearablesquery","type":"topic","title":"WearablesQuery"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/description","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/faceattribute\/description","navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"role":"symbol","url":"\/documentation\/dotfacecore\/glasses","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","abstract":[{"text":"Face attribute for the glasses.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}],"navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"kind":"symbol","title":"Glasses"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","kind":"symbol","type":"topic","title":"FaceImageQualityQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"text":"version: 8.13.0","type":"text"}],"role":"collection","type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyesExpression","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"url":"\/documentation\/dotfacecore\/eyesexpression","type":"topic","title":"EyesExpression"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/expressionquery","type":"topic","title":"ExpressionQuery"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","abstract":[{"text":"Eyes expression query specifies which eye expression face attributes should be evaluated.","type":"text"}],"title":"EyesExpressionQuery","url":"\/documentation\/dotfacecore\/eyesexpressionquery","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"url":"\/documentation\/dotfacecore\/wearables","type":"topic","title":"Wearables"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFFaceAttribute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/preconditionsMet","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/score"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/init(score:preconditionsMet:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"title":"Face evaluation"}],"op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTFFaceAttribute","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","value":"DOTFHeadPose","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"text":"DOTFHeadPose","kind":"identifier"}]},{"value":"DOTFFaceQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"value":"DOTFFaceAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","value":"DOTFFaceImageQuality","op":"replace"},{"value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","op":"replace"},{"value":"initWithScore:preconditionsMet:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1init(score:preconditionsMet:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1init(score:preconditionsMet:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithScore:preconditionsMet:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"text":"DOTFFaceQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1score\/title","value":"score","op":"replace"},{"value":[{"text":"score","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1score\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1preconditionsMet\/title","value":"preconditionsMet"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1preconditionsMet\/fragments","value":[{"kind":"identifier","text":"preconditionsMet"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","op":"replace","value":"DOTFExpression"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","op":"replace","value":[{"text":"DOTFExpression","kind":"identifier"}]},{"value":"DOTFHeadPoseAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace","value":"DOTFHeadPoseQuery"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGlasses"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments"},{"value":"DOTFFaceImageQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","value":"DOTFEyesExpression"},{"value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace","value":"DOTFEyesExpressionQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFWearables","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}