{"variants":[{"paths":["\/documentation\/dotfacecore\/libraries\/document"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/libraries\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/document","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","title":"document","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"document","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)Libraries(py)document"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Document library configuration."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Libraries":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries","title":"Libraries","url":"\/documentation\/dotfacecore\/libraries","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Container for library configurations."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Document library configuration."}],"title":"DotDocumentLibraryConfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/document":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"document"}],"url":"\/documentation\/dotfacecore\/libraries\/document","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"kind":"text","text":"?"}],"kind":"symbol","title":"document","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/document","abstract":[{"text":"Document library configuration.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"document","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"document"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"text":" * ","kind":"text"},{"text":"document","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/title"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/fragments"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/navigatorTitle"},{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"document","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1document\/title"},{"op":"replace","value":[{"kind":"identifier","text":"document"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1document\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}