{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/libraries\/fingers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/libraries\/fingers"]}],"kind":"symbol","abstract":[{"text":"Fingers library configuration.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)Libraries(py)fingers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","kind":"typeIdentifier","text":"DotFingersLibraryConfiguration"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","navigatorTitle":[{"text":"fingers","kind":"identifier"}],"symbolKind":"property","title":"fingers"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/fingers","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration","abstract":[{"type":"text","text":"Fingers library configuration."}],"role":"symbol","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration","kind":"symbol","title":"DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Libraries":{"type":"topic","abstract":[{"type":"text","text":"Container for library configurations."}],"url":"\/documentation\/dotfacecore\/libraries","role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries","kind":"symbol","title":"Libraries","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/fingers":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fingers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","title":"fingers","kind":"symbol","url":"\/documentation\/dotfacecore\/libraries\/fingers","abstract":[{"text":"Fingers library configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/fingers","navigatorTitle":[{"kind":"identifier","text":"fingers"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fingers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"fingers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFingersLibraryConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"text":" * ","kind":"text"},{"text":"fingers","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/fragments","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/navigatorTitle","value":[{"text":"Libraries","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1fingers\/title","value":"fingers"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1fingers\/fragments","value":[{"text":"fingers","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}