{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrznameelement\/hash"]},{"paths":["\/documentation\/dotdocument\/mrznameelement\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement(py)hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"property","role":"symbol","title":"hash","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/hash","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/MrzNameElement/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrznameelement\/hash","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/hash","title":"hash","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"title":"MrzNameElement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzNameElement","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"url":"\/documentation\/dotdocument\/mrznameelement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"hash","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1hash\/title","value":"hash"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"value":"DOTMrzNameElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]}]}]}