{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"primaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?, ","kind":"text"},{"text":"secondaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"]]},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"primaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?, ","kind":"text"},{"text":"secondaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement(im)initWithPrimaryIdentifier:secondaryIdentifier:","title":"init(primaryIdentifier:secondaryIdentifier:)","role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrznameelement\/init(primaryidentifier:secondaryidentifier:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrznameelement\/init(primaryidentifier:secondaryidentifier:)"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzNameElement/init(primaryIdentifier:secondaryIdentifier:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"primaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?, ","kind":"text"},{"text":"secondaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)","abstract":[],"title":"init(primaryIdentifier:secondaryIdentifier:)","role":"symbol","url":"\/documentation\/dotdocument\/mrznameelement\/init(primaryidentifier:secondaryidentifier:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNameElement"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"title":"MrzNameElement","role":"symbol","url":"\/documentation\/dotdocument\/mrznameelement","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzElement":{"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","type":"topic","title":"MrzElement","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzelement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithPrimaryIdentifier:secondaryIdentifier:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPrimaryIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"primaryIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"secondaryIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"secondaryIdentifier","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithPrimaryIdentifier:secondaryIdentifier:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1init(primaryIdentifier:secondaryIdentifier:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1init(primaryIdentifier:secondaryIdentifier:)\/fragments"},{"value":"DOTMrzNameElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title"},{"value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments"},{"value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/navigatorTitle"},{"value":"DOTMrzElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/navigatorTitle"}]}]}