{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"]]},"variants":[{"paths":["\/documentation\/dotdocument\/mrznameelement\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrznameelement\/isequal(_:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","role":"symbol","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement(im)isEqual:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/isEqual(_:)"},"references":{"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"kind":"symbol","url":"\/documentation\/dotdocument\/mrznameelement","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"title":"MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzNameElement/isEqual(_:)":{"url":"\/documentation\/dotdocument\/mrznameelement\/isequal(_:)","title":"isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/isEqual(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","op":"replace","value":"DOTMrzNameElement"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}]}]}