{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/secondaryIdentifier"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"]]},"abstract":[{"type":"text","text":"Secondary identifier usually represents given names."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"secondaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/mrznameelement\/secondaryidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrznameelement\/secondaryidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"kind":"text","text":"?"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement(py)secondaryIdentifier","role":"symbol","title":"secondaryIdentifier","navigatorTitle":[{"text":"secondaryIdentifier","kind":"identifier"}],"symbolKind":"property"},"references":{"doc://DotDocument/documentation/DotDocument/MrzNameElement/secondaryIdentifier":{"title":"secondaryIdentifier","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"secondaryIdentifier"}],"url":"\/documentation\/dotdocument\/mrznameelement\/secondaryidentifier","kind":"symbol","abstract":[{"text":"Secondary identifier usually represents given names.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/secondaryIdentifier","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"kind":"symbol","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"title":"MrzElement","role":"symbol","url":"\/documentation\/dotdocument\/mrzelement","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"url":"\/documentation\/dotdocument\/mrznameelement","title":"MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"secondaryIdentifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"secondaryIdentifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"secondaryIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1secondaryIdentifier\/title","value":"secondaryIdentifier"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1secondaryIdentifier\/fragments","value":[{"kind":"identifier","text":"secondaryIdentifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMrzNameElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}