{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"abstract":[{"type":"text","text":"Current configuration."}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/configuration-swift.property","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class","kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","title":"configuration","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader(py)configuration"},"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/configuration-swift.property":{"type":"topic","title":"configuration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/configuration-swift.property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.property","kind":"symbol","abstract":[{"text":"Current configuration.","type":"text"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfiguration":{"url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration","role":"symbol","type":"topic","title":"DOTNNfcTravelDocumentReaderConfiguration","fragments":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for "},{"type":"text","text":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class":{"abstract":[{"text":"Configuration options for ","type":"text"},{"code":"NfcTravelDocumentReader","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","title":"NfcTravelDocumentReader.Configuration","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","title":"NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"configuration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration","text":"DOTNNfcTravelDocumentReaderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1configuration-swift.property\/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace"}]}]}