{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/init(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/init(configuration:)"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/init(configuration:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Initialize and configure "},{"code":"NfcTravelDocumentReader","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"title":"init(configuration:)","symbolKind":"init","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","role":"symbol","platforms":[{"unavailable":false,"introducedAt":"13.0","deprecated":false,"name":"iOS","beta":false}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC"},{"kind":"text","text":")"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader(im)initWithConfiguration:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/init(configuration:)":{"title":"init(configuration:)","abstract":[{"text":"Initialize and configure ","type":"text"},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/init(configuration:)","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/init(configuration:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC","text":"Configuration"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.2.0","type":"text"}],"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfiguration":{"title":"DOTNNfcTravelDocumentReaderConfiguration","abstract":[{"text":"Configuration options for ","type":"text"},{"text":"NfcTravelDocumentReader","type":"text"},{"text":".","type":"text"}],"url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration","kind":"symbol","type":"topic","fragments":[{"text":"DOTNNfcTravelDocumentReaderConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class":{"title":"NfcTravelDocumentReader.Configuration","abstract":[{"text":"Configuration options for ","type":"text"},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithConfiguration:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration","text":"DOTNNfcTravelDocumentReaderConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1init(configuration:)\/title","value":"initWithConfiguration:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1init(configuration:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}