{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Read passport using NFC key."}],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/read(nfckey:activeauthenticationchallenge:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/read(nfckey:activeauthenticationchallenge:)"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use method `read(password: TravelDocumentReaderPassword, activeAuthenticationChallenge: Data? = nil)` instead.)"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(nfcKey:activeAuthenticationChallenge:)","interfaceLanguage":"swift"},"metadata":{"title":"read(nfcKey:activeAuthenticationChallenge:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"text":"nfcKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","text":"NfcKey","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeAuthenticationChallenge"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"readWithNfcKey:activeAuthenticationChallenge:","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader(im)readWithNfcKey:activeAuthenticationChallenge:","platforms":[{"introducedAt":"13.0","unavailable":false,"name":"iOS","beta":false,"deprecated":false}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nfcKey"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","text":"NfcKey"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"activeAuthenticationChallenge"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"nfcKey","content":[{"type":"paragraph","inlineContent":[{"text":"NFC key created from the document number, date of expiry and date of birth.","type":"text"}]}]},{"name":"activeAuthenticationChallenge","content":[{"inlineContent":[{"type":"text","text":"Random 8 bytes. If the Active Authentication challenge is set,"},{"text":" ","type":"text"},{"type":"text","text":"Active Authentication protocol will be used for the authentication of the chip (if supported by the chip)."},{"text":" ","type":"text"},{"type":"text","text":"Response (signature) will be returned in the result of the read operation. This response should be validated"},{"type":"text","text":" "},{"type":"text","text":"by the application server to verify the authenticity of the chip. In case when the Active Authentication"},{"text":" ","type":"text"},{"type":"text","text":"protocol is not supported by the chip, the chip will be authenticated the same way as if the argument"},{"type":"text","text":" "},{"type":"codeVoice","code":"activeAuthenticationChallenge"},{"type":"text","text":" is not set."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"You can handle success or failure of NFC reading by implementing the delegate methods."}],"type":"paragraph"}]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcKey":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","kind":"symbol","abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"role":"symbol","deprecated":true,"navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcKey","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/nfckey","title":"NfcKey"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/read(nfcKey:activeAuthenticationChallenge:)":{"title":"read(nfcKey:activeAuthenticationChallenge:)","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/read(nfckey:activeauthenticationchallenge:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(nfcKey:activeAuthenticationChallenge:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Read passport using NFC key."}],"navigatorTitle":[{"kind":"identifier","text":"readWithNfcKey:activeAuthenticationChallenge:"}],"deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"text":"nfcKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","text":"NfcKey"},{"kind":"text","text":", "},{"text":"activeAuthenticationChallenge","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"type":"topic","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"readWithNfcKey:activeAuthenticationChallenge:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readWithNfcKey:activeAuthenticationChallenge:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"readWithNfcKey:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","text":"DOTNNfcKey","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey"},{"kind":"text","text":" *) "},{"text":"nfcKey","kind":"internalParam"},{"kind":"text","text":" "},{"text":"activeAuthenticationChallenge:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"activeAuthenticationChallenge"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(nfcKey:activeAuthenticationChallenge:)\/title","op":"replace","value":"readWithNfcKey:activeAuthenticationChallenge:"},{"value":[{"kind":"text","text":"- "},{"text":"readWithNfcKey:activeAuthenticationChallenge:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(nfcKey:activeAuthenticationChallenge:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}