{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"title":"cameraPreviewScaleType","role":"symbol","symbolKind":"property","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC8DefaultsV22cameraPreviewScaleTypeAA06CamerajkL0OvpZ","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/Defaults":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureViewController.Configuration.Defaults","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Defaults","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureViewController.Configuration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/Defaults/cameraPreviewScaleType":{"kind":"symbol","abstract":[],"title":"cameraPreviewScaleType","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol","url":"\/documentation\/dotdocument\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]}]}]}