{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults"]]},"metadata":{"externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC8DefaultsV12cameraFacing0A6Camera0kJ0OvpZ","roleHeading":"Type Property","role":"symbol","symbolKind":"property","title":"cameraFacing","modules":[{"name":"DotDocument"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","text":"CameraFacing"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraFacing","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","title":"DocumentAutoCaptureViewController","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/Defaults":{"title":"DocumentAutoCaptureViewController.Configuration.Defaults","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/Defaults/cameraFacing":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraFacing","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerafacing","title":"cameraFacing","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"title":"DocumentAutoCaptureViewController.Configuration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"title":"CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/camerafacing"}},"variantOverrides":[{"patch":[{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"op":"replace"},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","op":"replace"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}