{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults\/placeholdertype"]}],"metadata":{"roleHeading":"Type Property","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC8DefaultsV15placeholderTypeAA011PlaceholderJ0OvpZ","symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier","text":"PlaceholderType"}],"role":"symbol","title":"placeholderType"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"placeholderType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults\/placeholderType"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlaceholderType"}],"kind":"symbol","abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","title":"PlaceholderType","role":"symbol","url":"\/documentation\/dotdocument\/placeholdertype"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/Defaults/placeholderType":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults\/placeholderType","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"placeholderType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults\/placeholdertype","role":"symbol","title":"placeholderType"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","title":"DocumentAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/Defaults":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Defaults","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/defaults","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/Defaults","kind":"symbol","title":"DocumentAutoCaptureViewController.Configuration.Defaults","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"role":"symbol","title":"DocumentAutoCaptureViewController","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTDPlaceholderType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title"},{"value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","op":"replace"},{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace"}]}]}