{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"td1","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/traveldocumenttype\/td1"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocumenttype\/td1"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td1","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td1"}],"symbolKind":"case","externalID":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType@DOTTravelDocumentTypeTd1","roleHeading":"Case","role":"symbol","title":"TravelDocumentType.td1","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd1"}]},"references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentType"}],"abstract":[{"text":"Travel document type according to ICAO Doc 9303 specification.","type":"text"}],"url":"\/documentation\/dotnfc\/traveldocumenttype","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType","role":"symbol","title":"TravelDocumentType"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/td1":{"navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd1"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"td1","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td1","abstract":[],"kind":"symbol","role":"symbol","title":"TravelDocumentType.td1","url":"\/documentation\/dotnfc\/traveldocumenttype\/td1","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"DOTTravelDocumentTypeTd1","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd1"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd1"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/title","op":"replace","value":"DOTTravelDocumentType"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td1\/title","value":"DOTTravelDocumentTypeTd1"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td1\/fragments","value":[{"text":"DOTTravelDocumentTypeTd1","kind":"identifier"}]}]}]}