{"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error"]]},"metadata":{"role":"collectionGroup","title":"LocalizedError Implementations","modules":[{"name":"DotPalmCore"}],"roleHeading":"API Collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/intervaldouble\/error\/localizederror-implementations"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/LocalizedError-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/failureReason","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/helpAnchor","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/recoverySuggestion"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/recoverySuggestion":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/recoverySuggestion","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"recoverySuggestion","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/recoverysuggestion"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"IntervalDouble.Error","url":"\/documentation\/dotpalmcore\/intervaldouble\/error"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/helpAnchor":{"kind":"symbol","abstract":[],"title":"helpAnchor","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/helpanchor","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/helpAnchor"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"title":"IntervalDouble","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotpalmcore\/intervaldouble","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 9.2.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/failureReason":{"type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/failurereason","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","title":"failureReason","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}