{"metadata":{"externalID":"s:14DotFaceCommons31AnyMultiRangeLivenessControllerC9imageSize0A4Core05ImageJ0CSgvp","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"imageSize","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMultiRangeLivenessController\/imageSize"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/anymultirangelivenesscontroller\/imagesize"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMultiRangeLivenessController"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/AnyMultiRangeLivenessController/imageSize":{"url":"\/documentation\/dotfacelite\/anymultirangelivenesscontroller\/imagesize","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMultiRangeLivenessController\/imageSize","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"},{"kind":"text","text":"?"}],"role":"symbol","title":"imageSize"},"doc://DotFaceLite/documentation/DotFaceLite/AnyMultiRangeLivenessController":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnyMultiRangeLivenessController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/anymultirangelivenesscontroller","abstract":[],"navigatorTitle":[{"text":"AnyMultiRangeLivenessController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMultiRangeLivenessController","role":"symbol","title":"AnyMultiRangeLivenessController","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/imagesize","title":"ImageSize","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"patch":[{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}