{"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentCode"}],"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)documentCode","roleHeading":"Instance Property","title":"documentCode","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentCode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/documentcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/documentcode"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/documentCode","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone/documentCode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/documentCode","abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone\/documentcode","navigatorTitle":[{"kind":"identifier","text":"documentCode"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"kind":"symbol","type":"topic","title":"documentCode"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"kind":"symbol","type":"topic","title":"Td1MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td1MachineReadableZone"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"type":"topic","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelement","title":"MrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"documentCode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"documentCode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"DOTMrzElement"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"documentCode"}],"languages":["occ"]}]},"op":"replace"},{"value":"documentCode","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1documentCode\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1documentCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"documentCode"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","op":"replace","value":"DOTTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","op":"replace","value":"DOTMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}