{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/uniqueIntensityLevels"},"abstract":[{"text":"Face image unique intensity levels.","type":"text"}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality(py)uniqueIntensityLevels","title":"uniqueIntensityLevels","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uniqueIntensityLevels"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier","text":"FaceAttribute"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"uniqueIntensityLevels"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimagequality\/uniqueintensitylevels"]},{"paths":["\/documentation\/dotfacecore\/faceimagequality\/uniqueintensitylevels"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"uniqueIntensityLevels","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/uniqueIntensityLevels":{"navigatorTitle":[{"kind":"identifier","text":"uniqueIntensityLevels"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceimagequality\/uniqueintensitylevels","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/uniqueIntensityLevels","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uniqueIntensityLevels","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","title":"uniqueIntensityLevels","abstract":[{"type":"text","text":"Face image unique intensity levels."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"title":"FaceImageQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImageQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/faceimagequality","kind":"symbol","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"title":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"uniqueIntensityLevels","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"uniqueIntensityLevels"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","text":"DOTFFaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"uniqueIntensityLevels"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1uniqueIntensityLevels\/title","value":"uniqueIntensityLevels","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"uniqueIntensityLevels"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1uniqueIntensityLevels\/fragments"},{"value":"DOTFFaceImageQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}