{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"symbolKind":"property","modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument0B16AutoCapturePhaseO11descriptionSSvp","roleHeading":"Instance Property","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturephase\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"kind":"symbol","abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"title":"DocumentAutoCapturePhase","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturephase","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/description":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"title":"description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/description","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturephase\/description","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title","value":"DOTDDocumentAutoCapturePhase"},{"value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}