{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/init(rawValue:)"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturephase\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:11DotDocument0B16AutoCapturePhaseO8rawValueACSgSi_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","title":"init(rawValue:)","symbolKind":"init","modules":[{"name":"DotDocument"}],"role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 9.0.2","type":"text"}],"title":"DotDocument","role":"collection","kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/init(rawValue:)":{"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/dotdocument\/documentautocapturephase\/init(rawvalue:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturephase","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"title":"DocumentAutoCapturePhase"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title","op":"replace","value":"DOTDDocumentAutoCapturePhase"},{"value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments"},{"value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}