{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface\/description"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/description"},"sections":[],"metadata":{"role":"symbol","title":"description","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace(py)description","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false}]},"references":{"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/description","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/description","title":"description","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"navigatorTitle":[{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"title":"EncodedIdentificationFeaturesFace","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.9.0"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1description\/title","value":"description","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1description\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTNEncodedIdentificationFeaturesFace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}],"op":"replace"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}