{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/rawBgra"},"abstract":[{"type":"text","text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgra"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The 4 bytes of color image pixel:"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"0th byte: BB - blue"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"1st byte: GG - green","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"2nd byte: RR - red","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"3rd byte: 0  - alpha","type":"text"}]}]}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imageformat\/rawbgra"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imageformat\/rawbgra"]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgra","roleHeading":"Case","title":"ImageFormat.rawBgra","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgra"}],"navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"symbolKind":"case"},"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/ImageFormat/rawBgra":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgra"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/rawBgra","url":"\/documentation\/dotnfc\/imageformat\/rawbgra","title":"ImageFormat.rawBgra"},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","title":"ImageFormat","abstract":[{"type":"text","text":"Supported image formats."}],"url":"\/documentation\/dotnfc\/imageformat","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTImageFormatRawBgra","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1rawBgra\/title","value":"DOTImageFormatRawBgra","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1rawBgra\/fragments","value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","value":"DOTImageFormat","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace"}]}]}