{"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"DotSdkError.composeWithInternalError()"},{"text":".","type":"text"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"extendedModule":"DotCore","externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"composeWithInternalError()","modules":[{"relatedModules":["DotCore"],"name":"DotFaceLite"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/intervalfloat\/error\/composewithinternalerror()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/composeWithInternalError()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/DotSdkError-Implementations"]]},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error/DotSdkError-Implementations":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/DotSdkError-Implementations","title":"DotSdkError Implementations","kind":"article","role":"collectionGroup","abstract":[],"url":"\/documentation\/dotfacelite\/intervalfloat\/error\/dotsdkerror-implementations"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat":{"url":"\/documentation\/dotfacelite\/intervalfloat","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","title":"IntervalFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error":{"title":"IntervalFloat.Error","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","url":"\/documentation\/dotfacelite\/intervalfloat\/error","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error/composeWithInternalError()":{"title":"composeWithInternalError()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/intervalfloat\/error\/composewithinternalerror()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/composeWithInternalError()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/fragments","op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}]}]}