{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/Error-Implementations"]]},"metadata":{"platforms":[{"name":"iOS","introducedAt":"8.0","unavailable":false,"deprecated":false,"beta":false},{"name":"iPadOS","introducedAt":"8.0","unavailable":false,"deprecated":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"8.0","unavailable":false,"deprecated":false,"beta":false},{"name":"macOS","introducedAt":"10.10","unavailable":false,"deprecated":false,"beta":false},{"name":"tvOS","introducedAt":"9.0","unavailable":false,"deprecated":false,"beta":false},{"name":"watchOS","introducedAt":"2.0","unavailable":false,"deprecated":false,"beta":false}],"role":"symbol","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","symbolKind":"property","modules":[{"name":"DotFaceLite","relatedModules":["Swift"]}],"roleHeading":"Instance Property","extendedModule":"Swift","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"localizedDescription"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Error.localizedDescription"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/localizedDescription","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/intervalfloat\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error/Error-Implementations":{"url":"\/documentation\/dotfacelite\/intervalfloat\/error\/error-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/Error-Implementations","type":"topic","kind":"article","title":"Error Implementations"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error":{"url":"\/documentation\/dotfacelite\/intervalfloat\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error","title":"IntervalFloat.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error/localizedDescription":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/localizedDescription","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/intervalfloat\/error\/localizeddescription","role":"symbol","type":"topic","title":"localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat":{"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","url":"\/documentation\/dotfacelite\/intervalfloat","title":"IntervalFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/title"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/fragments"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/navigatorTitle"}]}]}