{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/identifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/identifier"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"role":"symbol","title":"identifier","externalID":"c:@M@DotDocument@objc(cs)DOTDSharpnessTooLowValidator(py)identifier","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessTooLowValidator"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessTooLowValidator\/identifier","interfaceLanguage":"swift"},"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/SharpnessTooLowValidator/identifier":{"type":"topic","role":"symbol","title":"identifier","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessTooLowValidator\/identifier","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/SharpnessTooLowValidator":{"role":"symbol","type":"topic","title":"SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessTooLowValidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"identifier","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"text":"identifier","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"identifier","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessTooLowValidator~1identifier\/title","value":"identifier","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessTooLowValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}]}]}]}