{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/capturemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/capturemode"]}],"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/autoCapture","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/waitForRequest"]},{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/description"]},{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTCaptureMode) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Capture mode."}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"],"kind":"relationships","type":"conformsTo"}],"metadata":{"externalID":"c:@M@DotCapture@E@DOTCaptureMode","role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode":{"type":"topic","abstract":[{"type":"text","text":"Capture mode."}],"url":"\/documentation\/dotpalmcore\/capturemode","navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"title":"CaptureMode"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/waitForRequest":{"kind":"symbol","title":"CaptureMode.waitForRequest","navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/capturemode\/waitforrequest","abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waitForRequest"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/waitForRequest"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","url":"\/documentation\/dotpalmcore\/capturemode\/equatable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/Equatable-Implementations"},"doc://DotPalmCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/DotPalmCore\/SY","type":"unresolvable"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/autoCapture":{"kind":"symbol","title":"CaptureMode.autoCapture","navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/capturemode\/autocapture","abstract":[{"text":"Auto capture mode (automatic mode).","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoCapture"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/autoCapture"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotpalmcore\/capturemode\/init(rawvalue:)","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/init(rawValue:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.14.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/RawRepresentable-Implementations":{"kind":"article","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/dotpalmcore\/capturemode\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/RawRepresentable-Implementations","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/description":{"kind":"symbol","title":"description","url":"\/documentation\/dotpalmcore\/capturemode\/description","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/autoCapture","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/waitForRequest"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTCaptureMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCaptureMode"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1waitForRequest\/title","op":"replace","value":"DOTCaptureModeWaitForRequest"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1waitForRequest\/fragments","op":"replace","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1autoCapture\/title","value":"DOTCaptureModeAutoCapture"},{"value":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1autoCapture\/fragments"}]}]}