{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/initwithpreview:phase:detection:result:"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiStateRunning(im)initWithPreview:phase:detection:result:","title":"initWithPreview:phase:detection:result:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFaceAutoCapturePreview","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview"},{"text":" *) ","kind":"text"},{"text":"preview","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"phase:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFaceAutoCapturePhaseWrapped","preciseIdentifier":"c:objc(cs)DOTFaceAutoCapturePhaseWrapped","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"phase","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLFaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"DOTFLFaceAutoCaptureResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning":{"type":"topic","fragments":[{"text":"DOTFLFaceAutoCaptureUiStateRunning","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning","kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning","title":"DOTFLFaceAutoCaptureUiStateRunning","role":"symbol","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning/initWithPreview:phase:detection:result:":{"abstract":[],"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/initwithpreview:phase:detection:result:","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"title":"initWithPreview:phase:detection:result:","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","title":"FaceAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview","kind":"symbol","title":"FaceAutoCapturePreview","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","kind":"symbol","role":"symbol","title":"FaceAutoCaptureResult","type":"topic","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"url":"\/documentation\/dotfacelite\/faceautocaptureresult"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","op":"replace","value":"DOTFLFaceAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","op":"replace","value":"DOTFaceAutoCapturePreview"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","op":"replace","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","op":"replace","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","op":"replace","value":"DOTFLFaceAutoCaptureResult"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}