{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/preview"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Preview information."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/preview","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFaceAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview"},{"text":" * ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"preview","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiStateRunning(py)preview","title":"preview","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"preview"}],"role":"symbol","modules":[{"name":"DotFaceLite"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning","title":"DOTFLFaceAutoCaptureUiStateRunning","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiStateRunning"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"type":"topic","title":"FaceAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCapturePreview","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning/preview":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/preview","title":"preview","abstract":[{"type":"text","text":"Preview information."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/preview","type":"topic","kind":"symbol","fragments":[{"text":"preview","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","value":"DOTFaceAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}