{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)hash","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/hash","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"role":"symbol","type":"topic","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","kind":"symbol","title":"AutoCaptureConfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotfacelite\/autocaptureconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/hash":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/hash","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/hash","title":"hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hash"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1hash\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}