{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacepassivelivenessenabled"]},{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacepassivelivenessenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isFacePassiveLivenessEnabled","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DotSdkLicenseProxy(py)isFacePassiveLivenessEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"roleHeading":"Instance Property","title":"isFacePassiveLivenessEnabled","role":"symbol","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFacePassiveLivenessEnabled":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacepassivelivenessenabled","title":"isFacePassiveLivenessEnabled","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"isFacePassiveLivenessEnabled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}]}]}},{"value":"isFacePassiveLivenessEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/fragments","op":"replace","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}