{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"title":"isFaceMatchingEnabled","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DotSdkLicenseProxy(py)isFaceMatchingEnabled","symbolKind":"property","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isFaceMatchingEnabled","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacematchingenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacematchingenabled"]}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFaceMatchingEnabled":{"title":"isFaceMatchingEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacematchingenabled","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","type":"topic","navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"isFaceMatchingEnabled","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DotSdkLicenseProxy","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/title","op":"replace","value":"isFaceMatchingEnabled"},{"value":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/fragments"}]}]}