{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"]]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkLicenseProxyProtocol.isFaceLiteEnabled"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceliteenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceliteenabled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceLiteEnabled"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DotSdkLicenseProxy(py)isFaceLiteEnabled","title":"isFaceLiteEnabled"},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFaceLiteEnabled":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceLiteEnabled","role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceliteenabled","abstract":[],"title":"isFaceLiteEnabled"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isFaceLiteEnabled"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title","op":"replace","value":"isFaceLiteEnabled"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments","value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"op":"replace","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}