{"metadata":{"title":"FaceFeature.faceChinTip","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"faceChinTip","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureFaceChinTip","role":"symbol","navigatorTitle":[{"text":"DOTFFaceFeatureFaceChinTip","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Case","symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/facechintip"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/facechintip"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/faceChinTip","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceChinTip","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"abstract":[{"type":"text","text":"Available face features."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceFeature","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature/faceChinTip":{"title":"FaceFeature.faceChinTip","navigatorTitle":[{"text":"DOTFFaceFeatureFaceChinTip","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/faceChinTip","role":"symbol","url":"\/documentation\/dotfacecore\/facefeature\/facechintip","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"faceChinTip","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.6.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceFeatureFaceChinTip"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureFaceChinTip"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureFaceChinTip","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DOTFFaceFeature","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments","value":[{"text":"DOTFFaceFeature","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1faceChinTip\/title","op":"replace","value":"DOTFFaceFeatureFaceChinTip"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1faceChinTip\/fragments","value":[{"text":"DOTFFaceFeatureFaceChinTip","kind":"identifier"}],"op":"replace"}]}]}