{"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftEyebrowInnerEdge","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowInnerEdge"}],"title":"FaceFeature.leftEyebrowInnerEdge","roleHeading":"Case","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureLeftEyebrowInnerEdge"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"leftEyebrowInnerEdge","kind":"identifier"}]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyebrowinneredge"]},{"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyebrowinneredge"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowInnerEdge"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyebrowInnerEdge":{"abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftEyebrowInnerEdge","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature\/lefteyebrowinneredge","navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyebrowInnerEdge","kind":"identifier"}],"title":"FaceFeature.leftEyebrowInnerEdge","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowInnerEdge","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.0.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"abstract":[{"text":"Available face features.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceFeature","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature","navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"type":"topic","title":"FaceFeature","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTFFaceFeatureLeftEyebrowInnerEdge"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowInnerEdge"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTFFaceFeatureLeftEyebrowInnerEdge","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowInnerEdge\/title","value":"DOTFFaceFeatureLeftEyebrowInnerEdge"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowInnerEdge\/fragments","op":"replace","value":[{"text":"DOTFFaceFeatureLeftEyebrowInnerEdge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}]}]}