{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftEyeCenter","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeCenter","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyecenter"]},{"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyecenter"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"FaceFeature.leftEyeCenter","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureLeftEyeCenter","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeCenter"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyeCenter"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"symbolKind":"case"},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyeCenter":{"type":"topic","url":"\/documentation\/dotfacecore\/facefeature\/lefteyecenter","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeCenter","abstract":[],"title":"FaceFeature.leftEyeCenter","navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyeCenter","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeCenter"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"type":"topic","url":"\/documentation\/dotfacecore\/facefeature","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","abstract":[{"type":"text","text":"Available face features."}],"title":"FaceFeature","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTFFaceFeatureLeftEyeCenter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyeCenter"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureLeftEyeCenter","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeCenter\/title","value":"DOTFFaceFeatureLeftEyeCenter"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeCenter\/fragments","op":"replace","value":[{"text":"DOTFFaceFeatureLeftEyeCenter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}