{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthrightcorner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthrightcorner"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthRightCorner"}],"roleHeading":"Case","title":"FaceFeature.mouthRightCorner","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureMouthRightCorner","symbolKind":"case","role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DOTFFaceFeatureMouthRightCorner","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/mouthRightCorner","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mouthRightCorner"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"abstract":[{"text":"Available face features.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature/mouthRightCorner":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthRightCorner","kind":"identifier"}],"kind":"symbol","title":"FaceFeature.mouthRightCorner","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/facefeature\/mouthrightcorner","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthRightCorner"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/mouthRightCorner"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DOTFFaceFeatureMouthRightCorner","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFFaceFeatureMouthRightCorner","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTFFaceFeatureMouthRightCorner","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]},{"op":"replace","value":"DOTFFaceFeatureMouthRightCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1mouthRightCorner\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1mouthRightCorner\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureMouthRightCorner"}]}]}]}