{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noseRoot","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"title":"FaceFeature.noseRoot","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureNoseRoot","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRoot"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noseRoot","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/noseroot"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/noseroot"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/noseRoot","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature/noseRoot":{"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRoot"}],"role":"symbol","title":"FaceFeature.noseRoot","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/noseRoot","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"noseRoot","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facefeature\/noseroot","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"title":"FaceFeature","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceFeature","kind":"identifier"}],"navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"abstract":[{"text":"Available face features.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","url":"\/documentation\/dotfacecore\/facefeature","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceFeatureNoseRoot"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"DOTFFaceFeatureNoseRoot","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRoot"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1noseRoot\/title","value":"DOTFFaceFeatureNoseRoot"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRoot"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1noseRoot\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments"}]}]}