{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseLeftBottom","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseLeftBottom","kind":"identifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/noseleftbottom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/noseleftbottom"]}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseLeftBottom"}],"role":"symbol","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureNoseLeftBottom","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noseLeftBottom"}],"title":"FaceFeature.noseLeftBottom","roleHeading":"Case"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/noseLeftBottom":{"url":"\/documentation\/dotfacecore\/facefeature\/noseleftbottom","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseLeftBottom","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noseLeftBottom"}],"title":"FaceFeature.noseLeftBottom","navigatorTitle":[{"text":"DOTFFaceFeatureNoseLeftBottom","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"url":"\/documentation\/dotfacecore\/facefeature","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","role":"symbol","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"title":"FaceFeature","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeature"}],"abstract":[{"text":"Available face features.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFFaceFeatureNoseLeftBottom","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFFaceFeatureNoseLeftBottom","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTFFaceFeatureNoseLeftBottom"}]}]},"op":"replace"},{"op":"replace","value":"DOTFFaceFeatureNoseLeftBottom","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseLeftBottom\/title"},{"value":[{"text":"DOTFFaceFeatureNoseLeftBottom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseLeftBottom\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}