{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noseBottom","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"FaceFeature.noseBottom","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureNoseBottom","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noseBottom"}],"role":"symbol","symbolKind":"case","modules":[{"name":"DotFaceCore"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseBottom"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/facefeature\/nosebottom"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/nosebottom"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseBottom","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/noseBottom":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noseBottom"}],"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"DOTFFaceFeatureNoseBottom","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature\/nosebottom","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseBottom","kind":"symbol","title":"FaceFeature.noseBottom"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"abstract":[{"type":"text","text":"Available face features."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","role":"symbol","url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTFFaceFeatureNoseBottom","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DOTFFaceFeatureNoseBottom","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DOTFFaceFeatureNoseBottom","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseBottom\/title","value":"DOTFFaceFeatureNoseBottom","op":"replace"},{"op":"replace","value":[{"text":"DOTFFaceFeatureNoseBottom","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseBottom\/fragments"},{"value":"DOTFFaceFeature","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeature"}]}]}]}