{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeCenter","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeCenter"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/righteyecenter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/righteyecenter"]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyeCenter"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rightEyeCenter","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureRightEyeCenter","title":"FaceFeature.rightEyeCenter","roleHeading":"Case"},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyeCenter":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyeCenter"}],"navigatorTitle":[{"text":"DOTFFaceFeatureRightEyeCenter","kind":"identifier"}],"title":"FaceFeature.rightEyeCenter","abstract":[],"url":"\/documentation\/dotfacecore\/facefeature\/righteyecenter","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeCenter"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"abstract":[{"text":"Available face features.","type":"text"}],"role":"symbol","title":"FaceFeature","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"DOTFFaceFeatureRightEyeCenter","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFFaceFeatureRightEyeCenter","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureRightEyeCenter","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTFFaceFeatureRightEyeCenter","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeCenter\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeCenter\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyeCenter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","value":[{"text":"DOTFFaceFeature","kind":"identifier"}],"op":"replace"}]}]}