{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyebrowInnerEdge"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowInnerEdge"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightEyebrowInnerEdge","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFFaceFeatureRightEyebrowInnerEdge","kind":"identifier"}],"title":"FaceFeature.rightEyebrowInnerEdge","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureRightEyebrowInnerEdge","symbolKind":"case","roleHeading":"Case","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/righteyebrowinneredge"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/righteyebrowinneredge"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyebrowInnerEdge":{"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyebrowInnerEdge"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/facefeature\/righteyebrowinneredge","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowInnerEdge","role":"symbol","type":"topic","title":"FaceFeature.rightEyebrowInnerEdge","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyebrowInnerEdge"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"abstract":[{"type":"text","text":"Available face features."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","role":"symbol","url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"DOTFFaceFeatureRightEyebrowInnerEdge","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyebrowInnerEdge"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyebrowInnerEdge"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowInnerEdge\/title","op":"replace","value":"DOTFFaceFeatureRightEyebrowInnerEdge"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowInnerEdge\/fragments","value":[{"text":"DOTFFaceFeatureRightEyebrowInnerEdge","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}