{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rightEyeInnerCorner","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/righteyeinnercorner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/righteyeinnercorner"]}],"metadata":{"navigatorTitle":[{"text":"DOTFFaceFeatureRightEyeInnerCorner","kind":"identifier"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyeInnerCorner"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureRightEyeInnerCorner","symbolKind":"case","title":"FaceFeature.rightEyeInnerCorner"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeInnerCorner"},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeature"}],"navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"abstract":[{"type":"text","text":"Available face features."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","type":"topic","title":"FaceFeature","url":"\/documentation\/dotfacecore\/facefeature"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyeInnerCorner":{"title":"FaceFeature.rightEyeInnerCorner","abstract":[],"navigatorTitle":[{"text":"DOTFFaceFeatureRightEyeInnerCorner","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeInnerCorner","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightEyeInnerCorner","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature\/righteyeinnercorner","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotFaceCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"DOTFFaceFeatureRightEyeInnerCorner","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFFaceFeatureRightEyeInnerCorner","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTFFaceFeatureRightEyeInnerCorner","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTFFaceFeature","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeInnerCorner\/title","value":"DOTFFaceFeatureRightEyeInnerCorner","op":"replace"},{"value":[{"text":"DOTFFaceFeatureRightEyeInnerCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeInnerCorner\/fragments"}]}]}