{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/modules-swift.property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.property"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(py)modules","modules":[{"name":"DotFaceCore"}],"title":"modules","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","text":"Modules"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","text":"Modules"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration"]]},"abstract":[{"text":"Module configuration.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","role":"symbol","type":"topic","title":"DotDocumentLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class","abstract":[{"text":"Document library module configuration.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","role":"symbol","type":"topic","title":"DotDocumentLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration","abstract":[{"type":"text","text":"Document library configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/modules-swift.property":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/modules-swift.property","role":"symbol","type":"topic","title":"modules","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"modules"}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.property","abstract":[{"type":"text","text":"Module configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfigurationModules":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules","title":"DotDocumentLibraryConfigurationModules","fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Document library module configuration.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"modules"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"modules"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules","kind":"typeIdentifier","text":"DotDocumentLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modules"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/title","op":"replace","value":"DotDocumentLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration~1modules-swift.property\/title","op":"replace","value":"modules"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration~1modules-swift.property\/fragments","op":"replace","value":[{"text":"modules","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}