{"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","externalID":"s:14DotFingersCore0B18AutoCaptureUiStateC12InitializingC11descriptionSSvp","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing\/description"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/description","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing/description":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing\/description","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Initializing","kind":"identifier"}],"title":"FingersAutoCaptureUiState.Initializing","navigatorTitle":[{"text":"Initializing","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing","kind":"symbol","abstract":[{"type":"text","text":"Initializing state."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState":{"kind":"symbol","title":"FingersAutoCaptureUiState","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/title","value":"DOTFGFingersAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}]}]}]}