{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotNfcLibraryConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotnfclibraryconfiguration\/init"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotNfcLibraryConfiguration"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration(im)init","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotNfcLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotnfclibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"title":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotNfcLibraryConfiguration","role":"symbol","abstract":[{"text":"NFC library configuration.","type":"text"}],"navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotNfcLibraryConfiguration/init":{"url":"\/documentation\/dotfingerscore\/dotnfclibraryconfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotNfcLibraryConfiguration\/init","title":"init","role":"symbol","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotNfcLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotNfcLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotNfcLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotNfcLibraryConfiguration\/navigatorTitle","op":"replace"}]}]}