{"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@M@DotFaceLite@E@DOTLoggerLogLevel@DOTLoggerLogLevelError","title":"LoggerLogLevel.error","navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Case"},"variants":[{"paths":["\/documentation\/dotfacelite\/loggerloglevel\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/loggerloglevel\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel\/error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Logs failed operations and other errors."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/LoggerLogLevel/error":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel\/error","type":"topic","url":"\/documentation\/dotfacelite\/loggerloglevel\/error","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"kind":"symbol","role":"symbol","title":"LoggerLogLevel.error","navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/LoggerLogLevel":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/loggerloglevel","abstract":[{"type":"text","text":"Available log levels."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"LoggerLogLevel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTLoggerLogLevelError"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel~1error\/title","value":"DOTLoggerLogLevelError","op":"replace"},{"value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel~1error\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]}]}]}