{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/hash(into:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotCore@E@DOTLoggerLogLevel","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"Swift","roleHeading":"Instance Method","title":"hash(into:)","role":"symbol","modules":[{"relatedModules":["Swift"],"name":"DotFaceLite"}],"symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/RawRepresentable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/loggerloglevel\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/hash(into:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/hash(into:)","abstract":[],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"type":"topic","title":"hash(into:)","url":"\/documentation\/dotfacelite\/loggerloglevel\/hash(into:)"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Available log levels."}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/loggerloglevel","title":"LoggerLogLevel"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/dotfacelite\/loggerloglevel\/rawrepresentable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/title"},{"op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/navigatorTitle"}]}]}