{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@E@DOTLoggerLogLevel@DOTLoggerLogLevelInfo","title":"LoggerLogLevel.info","modules":[{"name":"DotFaceLite"}],"symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/loggerloglevel\/info"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/loggerloglevel\/info"]}],"abstract":[{"text":"Logs informative events.","type":"text"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel\/info","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 8.1.0"}],"kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/LoggerLogLevel":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/loggerloglevel","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"abstract":[{"type":"text","text":"Available log levels."}],"title":"LoggerLogLevel","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/LoggerLogLevel/info":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"type":"topic","abstract":[{"type":"text","text":"Logs informative events."}],"title":"LoggerLogLevel.info","url":"\/documentation\/dotfacelite\/loggerloglevel\/info","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel\/info"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevelInfo"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel~1info\/title","value":"DOTLoggerLogLevelInfo"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel~1info\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}