{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/init(rawValue:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"init(rawValue:)","symbolKind":"init","roleHeading":"Initializer","externalID":"s:7DotCore14LoggerLogLevelO8rawValueACSgSi_tcfc","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/loggerloglevel\/init(rawvalue:)"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"title":"LoggerLogLevel","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","url":"\/documentation\/dotfacelite\/loggerloglevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/init(rawValue:)":{"url":"\/documentation\/dotfacelite\/loggerloglevel\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/navigatorTitle"}]}]}