{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","metadata":{"extendedModule":"Swift","role":"symbol","modules":[{"name":"DotFaceCore","relatedModules":["Swift"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"roleHeading":"Instance Property","title":"hashValue","symbolKind":"property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::s:11DotFaceCore10ValueRangeC6StatusO"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/valuerange\/status\/hashvalue"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/RawRepresentable-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/hashValue","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/dotfacecore\/valuerange\/status\/rawrepresentable-implementations","kind":"article","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status":{"abstract":[{"text":"Status of a value with respect to a range.","type":"text"}],"title":"ValueRange.Status","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Status"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"url":"\/documentation\/dotfacecore\/valuerange\/status","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValueRange","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" range, compatible with Objective-C."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","title":"ValueRange","navigatorTitle":[{"text":"ValueRange","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/hashValue":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/hashValue","url":"\/documentation\/dotfacecore\/valuerange\/status\/hashvalue","role":"symbol","abstract":[],"title":"hashValue","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]}}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title","value":"DOTFValueRange","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments","value":[{"text":"DOTFValueRange","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFValueRange"}],"op":"replace"}]}]}