{"metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inRange","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"s:11DotFaceCore10ValueRangeC6StatusO02inE0yA2EmF","title":"ValueRange.Status.inRange","roleHeading":"Case"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inRange","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/valuerange\/status\/inrange"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/inRange"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/inRange":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/inRange","role":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/status\/inrange","type":"topic","kind":"symbol","title":"ValueRange.Status.inRange","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inRange","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValueRange","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" range, compatible with Objective-C."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","title":"ValueRange","navigatorTitle":[{"text":"ValueRange","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status":{"abstract":[{"text":"Status of a value with respect to a range.","type":"text"}],"title":"ValueRange.Status","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Status"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"url":"\/documentation\/dotfacecore\/valuerange\/status","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title","value":"DOTFValueRange"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments","value":[{"text":"DOTFValueRange","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/navigatorTitle","value":[{"text":"DOTFValueRange","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}