{"abstract":[{"type":"text","text":"JPEG compressed image format"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/imageformat\/jpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imageformat\/jpeg"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Case","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg","symbolKind":"case","title":"ImageFormat.jpeg"},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"title":"ImageFormat","url":"\/documentation\/dotpalmcore\/imageformat","role":"symbol","abstract":[{"type":"text","text":"Supported image formats."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/jpeg":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"jpeg","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/imageformat\/jpeg","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg","title":"ImageFormat.jpeg","navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"JPEG compressed image format","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTImageFormatJpeg"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg\/title","op":"replace","value":"DOTImageFormatJpeg"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]}]}]}