{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/common"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"s:14DotFingersCore0B21AutoCaptureControllerC13ConfigurationC6common0aC006CommonG0Cvp","title":"common","roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"}]}]}],"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"type":"codeVoice","code":".init()"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/common"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class/common":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/common","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"kind":"symbol","role":"symbol","title":"common","abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"type":"codeVoice","code":".init()"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/common"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureController.Configuration","abstract":[{"text":"Configuration of the fingers auto capture non-UI component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore/CommonConfiguration":{"url":"\/documentation\/dotfingerscore\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CommonConfiguration","title":"CommonConfiguration","role":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","value":"DOTFGFingersAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}