{"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:14DotFingersCore0B21AutoCaptureControllerC13ConfigurationC10validatorsSayAA0bdE24FrameParametersValidator_pGvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"kind":"text","text":": ["},{"text":"FingersAutoCaptureFrameParametersValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator"},{"kind":"text","text":"]"}],"title":"validators","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"validators","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator","kind":"typeIdentifier","text":"FingersAutoCaptureFrameParametersValidator","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Array of validators which will be used to validate input image."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/validators","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/validators"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class/validators":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/validators","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FingersAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/validators","title":"validators","role":"symbol","abstract":[{"text":"Array of validators which will be used to validate input image.","type":"text"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureController.Configuration","abstract":[{"text":"Configuration of the fingers auto capture non-UI component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}],"navigatorTitle":[{"text":"FingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","value":"DOTFGFingersAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title","value":"DOTFGFingersAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}