{"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC12sessionToken23isDetectionLayerVisible0L12TorchEnabled12cameraFacing0R16PreviewScaleTypeAESSSg_S2bAA06CameraS0OAA0wtuV0Otcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"},{"text":")","kind":"text"}],"role":"symbol","title":"init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","roleHeading":"Initializer","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType)"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)":{"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","title":"init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing":{"url":"\/documentation\/dotfacelite\/camerafacing","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","abstract":[{"text":"version: 8.4.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraPreviewScaleType":{"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/camerapreviewscaletype","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","title":"MagnifEyeLivenessViewController.Configuration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","title":"MagnifEyeLivenessViewController","role":"symbol","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/title","value":"DOTCameraFacing"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/fragments"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}