{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td3:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/machinereadablezone\/init(lines:td3:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/machinereadablezone\/init(lines:td3:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"td3","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone"]]},"metadata":{"role":"symbol","title":"init(lines:td3:)","roleHeading":"Initializer","modules":[{"name":"DotDocument"}],"symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone(im)initWithLines:td3:","navigatorTitle":[{"text":"initWithLines:td3:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"td3","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone"},{"kind":"text","text":")"}]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone/init(lines:td3:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithLines:td3:"}],"type":"topic","url":"\/documentation\/dotdocument\/machinereadablezone\/init(lines:td3:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td3:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td3"},{"text":": ","kind":"text"},{"text":"Td3MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(lines:td3:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","type":"topic","url":"\/documentation\/dotdocument\/td3machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"title":"Td3MachineReadableZone","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","type":"topic","url":"\/documentation\/dotdocument\/machinereadablezone","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"title":"MachineReadableZone","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithLines:td3:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLines:td3:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithLines:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"text":"lines","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"td3:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone","text":"DOTTd3MachineReadableZone"},{"text":" *) ","kind":"text"},{"text":"td3","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td3:)\/title","value":"initWithLines:td3:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLines:td3:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td3:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}