{"sections":[],"metadata":{"required":true,"role":"symbol","navigatorTitle":[{"text":"palmAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"title":"palmAutoCaptureViewControllerViewWillTransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillTransition"},{"text":"(","kind":"text"},{"text":"PalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate(im)palmAutoCaptureViewControllerViewWillTransition:","roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillTransition(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"palmAutoCaptureViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController","text":"PalmAutoCaptureViewController","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilltransition(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilltransition(_:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewWillTransition(_:)":{"title":"palmAutoCaptureViewControllerViewWillTransition(_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillTransition(_:)","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilltransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"PalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"palmAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"role":"symbol","kind":"symbol","required":true},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","title":"PalmAutoCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the palm auto capture events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","role":"symbol","title":"PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"palmAutoCaptureViewControllerViewWillTransition:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillTransition:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewWillTransition:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController","kind":"typeIdentifier","text":"DOTPPalmAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"palmAutoCaptureViewControllerViewWillTransition:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillTransition(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillTransition:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillTransition(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/title","value":"DOTPPalmAutoCaptureViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","op":"replace","value":"DOTPPalmAutoCaptureViewController"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"}]}]}