{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFQualityAttributeThresholds) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration"]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/brightnessInterval","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/contrastInterval","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/hash","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxDevicePitchAngle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxGlassesPresenceScore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxMaskPresenceScore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxShadow","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minBackgroundUniformity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minConfidence","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minEyesStatusScore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minMouthStatusScore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minSharpness","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minUniqueIntensityLevels","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/pitchAngleInterval","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/sizeInterval","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/yawAngleInterval"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/isEqual(_:)"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration":{"role":"symbol","title":"FaceAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/yawAngleInterval":{"role":"symbol","title":"yawAngleInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"yawAngleInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalFloat","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalFloat"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Valid interval of rotation of the yaw of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value -90.0 represents left rotated yaw of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Vaue 90.0 represents right rotated yaw of the detected face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/yawAngleInterval","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/yawangleinterval"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/description"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/isEqual(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/isequal(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/minSharpness":{"role":"symbol","title":"minSharpness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Minimal valid sharpness of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents blurry face."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents sharp face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minSharpness","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/minsharpness"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/minEyesStatusScore":{"role":"symbol","title":"minEyesStatusScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Minimal valid eyes status score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with eyes closed."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with eyes opened."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minEyesStatusScore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/mineyesstatusscore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/maxDevicePitchAngle":{"role":"symbol","title":"maxDevicePitchAngle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDevicePitchAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedFloat","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedFloat"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Maximal pitch angle of the device."},{"type":"text","text":" "},{"type":"text","text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxDevicePitchAngle","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/maxdevicepitchangle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/minUniqueIntensityLevels":{"role":"symbol","title":"minUniqueIntensityLevels","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minUniqueIntensityLevels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Minimal valid unique intensity levels of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low unique intensity levels."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high unique intensity levels."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minUniqueIntensityLevels","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/minuniqueintensitylevels"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds.Builder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/minMouthStatusScore":{"role":"symbol","title":"minMouthStatusScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minMouthStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Minimal valid mouth status score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with mouth opened."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with mouth closed."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minMouthStatusScore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/minmouthstatusscore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/pitchAngleInterval":{"role":"symbol","title":"pitchAngleInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitchAngleInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalFloat","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalFloat"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Valid interval of rotation of the pitch of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value -90.0 represents down rotated pitch of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Vaue 90.0 represents up rotated pitch of the detected face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/pitchAngleInterval","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/pitchangleinterval"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/hash":{"role":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/hash","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/hash"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/contrastInterval":{"role":"symbol","title":"contrastInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contrastInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Valid interval of contrast of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low contrast."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high contrast."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/contrastInterval","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/contrastinterval"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/minBackgroundUniformity":{"role":"symbol","title":"minBackgroundUniformity","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minBackgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Minimal valid level of the background uniformity of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low background uniformity."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high background uniformity."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minBackgroundUniformity","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/minbackgrounduniformity"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/maxGlassesPresenceScore":{"role":"symbol","title":"maxGlassesPresenceScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxGlassesPresenceScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Maximal valid glasses presence score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with no glasses."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with glasses."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxGlassesPresenceScore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/maxglassespresencescore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/sizeInterval":{"role":"symbol","title":"sizeInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Valid interval of size of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents small size."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents large size."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/sizeInterval","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/sizeinterval"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/minConfidence":{"role":"symbol","title":"minConfidence","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Minimal valid confidence of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low confidence."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high confidence."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/minConfidence","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/minconfidence"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/maxShadow":{"role":"symbol","title":"maxShadow","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxShadow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Maximal valid shadow of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face without shadows."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with shadows."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxShadow","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/maxshadow"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/maxMaskPresenceScore":{"role":"symbol","title":"maxMaskPresenceScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMaskPresenceScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Maximal valid mask presence score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with no mask."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with mask."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/maxMaskPresenceScore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/maxmaskpresencescore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/brightnessInterval":{"role":"symbol","title":"brightnessInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Valid interval of brightness of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low brightness."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high brightness."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/brightnessInterval","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/brightnessinterval"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/title","value":"DOTFFaceAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}