{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessConfiguration(im)initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"},"abstract":[{"text":"Create the smile liveness configuration.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"text":"faceSizeRatioInterval:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTIntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":" *) "},{"text":"faceSizeRatioInterval","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"query:"},{"kind":"text","text":"("},{"text":"FaceDetectionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"text":" *) ","kind":"text"},{"text":"query","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isTorchEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTCameraFacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration"]]},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration","abstract":[{"type":"text","text":"Configuration options for the smile liveness process."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration","role":"symbol","fragments":[{"text":"DOTFSmileLivenessConfiguration","kind":"identifier"}],"kind":"symbol","title":"DOTFSmileLivenessConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","title":"CameraPreviewScaleType","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.8.0"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:":{"url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"text":"Create the smile liveness configuration.","type":"text"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"}],"title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facedetectionquery","kind":"symbol","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","title":"FaceDetectionQuery","role":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","title":"IntervalDouble","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/camerafacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing","role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace"},{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}]}]}