{"sections":[],"metadata":{"title":"Equatable Implementations","modules":[{"name":"DotFaceCore"}],"role":"collectionGroup","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotlibraryid\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/Equatable-Implementations"},"kind":"article","topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/!=(_:_:)"],"anchor":"Operators"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"url":"\/documentation\/dotfacecore\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/!=(_:_:)":{"type":"topic","url":"\/documentation\/dotfacecore\/dotlibraryid\/!=(_:_:)","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}