{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/fingers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/fingers"]}],"metadata":{"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFingers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"title":"DotLibraryId.fingers","symbolKind":"case","modules":[{"name":"DotFaceCore"}],"role":"symbol","navigatorTitle":[{"text":"DotLibraryIdFingers","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fingers"}],"languages":["swift"]}]}],"abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/fingers","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"url":"\/documentation\/dotfacecore\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/fingers":{"url":"\/documentation\/dotfacecore\/dotlibraryid\/fingers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"title":"DotLibraryId.fingers","abstract":[{"code":"DotFingersLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibraryIdFingers","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/fingers"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotLibraryIdFingers","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotLibraryIdFingers","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/navigatorTitle","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1fingers\/title","op":"replace","value":"DotLibraryIdFingers"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1fingers\/fragments","op":"replace","value":[{"text":"DotLibraryIdFingers","kind":"identifier"}]}]}]}