{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/dateOfBirth"},"variants":[{"paths":["\/documentation\/dotnfc\/nfckey\/dateofbirth"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfckey\/dateofbirth"]}],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcKey(py)dateOfBirth","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"title":"dateOfBirth","platforms":[{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"iOS","unavailable":false}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Date of birth in MRZ format [yyMMdd]."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"languages":["swift"]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use classes of `TravelDocumentReaderPassword` protocol instead.)"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","kind":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcKey/dateOfBirth":{"deprecated":true,"abstract":[{"type":"text","text":"Date of birth in MRZ format [yyMMdd]."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/nfckey\/dateofbirth","title":"dateOfBirth","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/dateOfBirth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://DotNfc/documentation/DotNfc/NfcKey":{"title":"NfcKey","kind":"symbol","navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfckey","type":"topic","abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"dateOfBirth","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"dateOfBirth"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dateOfBirth"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"op":"replace","value":"dateOfBirth","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1dateOfBirth\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1dateOfBirth\/fragments","value":[{"text":"dateOfBirth","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","op":"replace","value":"DOTNNfcKey"},{"value":[{"text":"DOTNNfcKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments"}]}]}