{"metadata":{"navigatorTitle":[{"text":"initWithCommon:camera:isDetectionLayerVisible:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"method","roleHeading":"Instance Method","title":"initWithCommon:camera:isDetectionLayerVisible:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:isDetectionLayerVisible:","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration(im)initWithCommon:camera:isDetectionLayerVisible:"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithCommon:camera:isDetectionLayerVisible:","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTCommonConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"common","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"camera:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithcommon:camera:isdetectionlayervisible:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"url":"\/documentation\/dotfacelite\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration/initWithCommon:camera:isDetectionLayerVisible:":{"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithcommon:camera:isdetectionlayervisible:","role":"symbol","navigatorTitle":[{"text":"initWithCommon:camera:isDetectionLayerVisible:","kind":"identifier"}],"abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithCommon:camera:isDetectionLayerVisible:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:isDetectionLayerVisible:","kind":"identifier"}],"title":"initWithCommon:camera:isDetectionLayerVisible:","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"title":"DOTFLMagnifEyeLivenessConfiguration","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","fragments":[{"text":"DOTFLMagnifEyeLivenessConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/cameraconfiguration","title":"CameraConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","kind":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}