{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/defaultThreshold","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Default threshold is 0.9."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/defaultthreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/defaultthreshold"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooHighValidator(cpy)defaultThreshold","modules":[{"name":"DotDocument"}],"title":"defaultThreshold","role":"symbol","roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/defaultThreshold":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/defaultthreshold","title":"defaultThreshold","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/defaultThreshold","navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Default threshold is 0.9.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","kind":"symbol","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"type":"topic","role":"symbol","title":"BrightnessTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","title":"DotDocument","kind":"symbol","abstract":[{"text":"version: 8.14.1","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"defaultThreshold","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"defaultThreshold","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1defaultThreshold\/title","op":"replace","value":"defaultThreshold"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1defaultThreshold\/fragments","value":[{"text":"defaultThreshold","kind":"identifier"}],"op":"replace"},{"value":"DOTDBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}