{"variants":[{"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooHighValidator"]]},"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"sections":[],"metadata":{"role":"symbol","title":"init(threshold:)","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooHighValidator(im)initWithThreshold:error:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"symbolKind":"init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooHighValidator\/init(threshold:)"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooHighValidator/init(threshold:)":{"role":"symbol","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/init(threshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"title":"init(threshold:)","type":"topic","navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooHighValidator\/init(threshold:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","role":"collection","abstract":[{"text":"version: 8.2.1","type":"text"}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooHighValidator":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"kind":"symbol","abstract":[{"text":"Validate maximum brightness of the detected document.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooHighValidator","type":"topic","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","title":"BrightnessTooHighValidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithThreshold:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithThreshold:error:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"threshold","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithThreshold:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooHighValidator~1init(threshold:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithThreshold:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooHighValidator~1init(threshold:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","value":"DOTDBrightnessTooHighValidator","op":"replace"},{"value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}