{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraFacing"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/defaults\/camerafacing"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"}],"symbolKind":"property","title":"cameraFacing","modules":[{"name":"DotFaceLite"}],"roleHeading":"Type Property","externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC8DefaultsV12cameraFacing0A6Camera0mL0OvpZ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"url":"\/documentation\/dotfacelite\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"type":"topic","title":"CameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.7.1"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/Defaults/cameraFacing":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/defaults\/camerafacing","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraFacing","title":"cameraFacing","abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/Defaults":{"abstract":[],"title":"MagnifEyeLivenessViewController.Configuration.Defaults","role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/defaults","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/Defaults","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"abstract":[{"text":"Configuration options for the MagnifEye liveness process.","type":"text"}],"title":"MagnifEyeLivenessViewController.Configuration","role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","role":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","title":"MagnifEyeLivenessViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","op":"replace"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","op":"replace"},{"value":"DOTFLMagnifEyeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]}]}]}