{"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DotSdkLicenseProxy(py)isPalmEnabled","roleHeading":"Instance Property","title":"isPalmEnabled","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"property","navigatorTitle":[{"text":"isPalmEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPalmEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isPalmEnabled","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/ispalmenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/ispalmenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isPalmEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isPalmEnabled"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxy","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","title":"DotSdkLicenseProxy","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isPalmEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPalmEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isPalmEnabled","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isPalmEnabled","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/ispalmenabled","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"isPalmEnabled","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"isPalmEnabled"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPalmEnabled"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/title","op":"replace","value":"DotSdkLicenseProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},{"value":"isPalmEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isPalmEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isPalmEnabled\/fragments","value":[{"kind":"identifier","text":"isPalmEnabled"}]}]}]}