{"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)"]}],"metadata":{"symbolKind":"init","title":"init(value:positions:checkDigit:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"kind":"text","text":": ["},{"text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"checkDigit"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit(im)initWithValue:positions:checkDigit:","roleHeading":"Initializer","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:checkDigit:"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"checkDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"]]},"references":{"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"role":"symbol","title":"MrzElementWithCheckDigit","kind":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit/init(value:positions:checkDigit:)":{"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)","navigatorTitle":[{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"positions","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"checkDigit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(value:positions:checkDigit:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"title":"MrzStringPosition","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzStringPosition","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","type":"topic","url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}]},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"title":"MrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","role":"symbol","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"type":"topic","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzcheckdigit","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithValue:positions:checkDigit:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":" ","kind":"text"},{"text":"positions:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTMrzStringPosition *>"},{"kind":"text","text":" *) "},{"text":"positions","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigit:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","kind":"typeIdentifier","text":"DOTMrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":" *) "},{"text":"checkDigit","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","op":"replace","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"value":"initWithValue:positions:checkDigit:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}],"op":"replace"},{"value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments","op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]}]}]}