{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/anymagnifeyelivenesscontroller\/imagesize"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMagnifEyeLivenessController\/imageSize"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMagnifEyeLivenessController"]]},"metadata":{"externalID":"s:14DotFaceCommons30AnyMagnifEyeLivenessControllerC9imageSize0A4Core05ImageJ0CSgvp","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":"?"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","title":"imageSize","symbolKind":"property"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/AnyMagnifEyeLivenessController/imageSize":{"url":"\/documentation\/dotfacelite\/anymagnifeyelivenesscontroller\/imagesize","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMagnifEyeLivenessController\/imageSize","title":"imageSize","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"role":"symbol","url":"\/documentation\/dotfacelite\/imagesize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"type":"topic","title":"ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}]},"doc://DotFaceLite/documentation/DotFaceLite/AnyMagnifEyeLivenessController":{"navigatorTitle":[{"text":"AnyMagnifEyeLivenessController","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnyMagnifEyeLivenessController","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyMagnifEyeLivenessController","type":"topic","title":"AnyMagnifEyeLivenessController","url":"\/documentation\/dotfacelite\/anymagnifeyelivenesscontroller"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}