{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"},{"kind":"text","text":": "},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/corners\/bottomright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/corners\/bottomright"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomRight","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"bottomRight","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)bottomRight","title":"bottomRight","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"},{"kind":"text","text":": "},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}]},"abstract":[{"text":"Bottom right corner point.","type":"text"}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.15.0"}],"title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/Corners":{"kind":"symbol","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","title":"Corners","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotfacecore\/corners","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/bottomRight":{"kind":"symbol","abstract":[{"type":"text","text":"Bottom right corner point."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomRight","title":"bottomRight","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"url":"\/documentation\/dotfacecore\/corners\/bottomright","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","url":"\/documentation\/dotfacecore\/pointdouble","kind":"symbol","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"bottomRight","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"bottomRight","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bottomRight"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/title","value":"DOTCorners","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]},{"value":"bottomRight","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomRight\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bottomRight"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomRight\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}