{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners"]]},"metadata":{"title":"topRight","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)topRight","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topRight"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Top right corner point.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topRight","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/corners\/topright"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/corners\/topright"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/topRight":{"navigatorTitle":[{"text":"topRight","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/corners\/topright","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topRight","title":"topRight","type":"topic","role":"symbol","abstract":[{"text":"Top right corner point.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble":{"title":"PointDouble","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotfacecore\/pointdouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}]},"doc://DotFaceCore/documentation/DotFaceCore/Corners":{"title":"Corners","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"url":"\/documentation\/dotfacecore\/corners","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"topRight","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"topRight","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPointDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"topRight","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1topRight\/title"},{"op":"replace","value":[{"kind":"identifier","text":"topRight"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1topRight\/fragments"},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/navigatorTitle"},{"op":"replace","value":"DOTCorners","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/title"},{"op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/fragments"},{"op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}