{"metadata":{"navigatorTitle":[{"text":"initWithValue:error:","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","title":"init(value:)","externalID":"c:@M@DotNfc@objc(cs)DOTNCardAccessNumberPassword(im)initWithValue:error:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/init(value:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/init(value:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/init(value:)"},"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"title":"NfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"title":"CardAccessNumberPassword","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CardAccessNumberPassword"}],"abstract":[{"type":"text","text":"Card Access Number as a password."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/init(value:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithValue:error:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/init(value:)","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/init(value:)","title":"init(value:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithValue:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace"},{"value":"DOTNCardAccessNumberPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle","op":"replace"},{"value":"initWithValue:error:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1init(value:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:error:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1init(value:)\/fragments","op":"replace"}]}]}