{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"title":"value","externalID":"c:@M@DotNfc@objc(cs)DOTNCardAccessNumberPassword(py)value","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"value","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","modules":[{"name":"DotNfc"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/value","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"]]},"kind":"symbol","abstract":[{"type":"text","text":"Card Access Number in the 6-digits format."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/value"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"abstract":[{"type":"text","text":"Card Access Number as a password."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","title":"CardAccessNumberPassword","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/value":{"title":"value","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/value","abstract":[{"text":"Card Access Number in the 6-digits format.","type":"text"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/value","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"value","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"value","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"value","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1value\/title","value":"value"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1value\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}