{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration"]]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration\/init"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration(im)init","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotDocument"}],"title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentbarcodemoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentBarcodeModuleConfiguration/init":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration\/init","title":"init","url":"\/documentation\/dotdocument\/dotdocumentbarcodemoduleconfiguration\/init"},"doc://DotDocument/documentation/DotDocument/DotDocumentBarcodeModuleConfiguration":{"type":"topic","kind":"symbol","title":"DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotdocument\/dotdocumentbarcodemoduleconfiguration","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}