{"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkConfiguration\/init(licenseBytes:libraries:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DotLibrary","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"text":"])","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkConfiguration"]]},"kind":"symbol","metadata":{"externalID":"c:@M@DotNfc@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"kind":"text","text":"])"}],"modules":[{"name":"DotNfc"}],"title":"init(licenseBytes:libraries:)","role":"symbol","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/dotsdkconfiguration\/init(licensebytes:libraries:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotsdkconfiguration\/init(licensebytes:libraries:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","url":"\/documentation\/dotnfc\/dotlibrary","role":"symbol","title":"DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","title":"DotNfc","role":"collection"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkConfiguration/init(licenseBytes:libraries:)":{"kind":"symbol","title":"init(licenseBytes:libraries:)","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotsdkconfiguration\/init(licensebytes:libraries:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkConfiguration\/init(licenseBytes:libraries:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkConfiguration":{"kind":"symbol","title":"DotSdkConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"type":"topic","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotsdkconfiguration","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithLicenseBytes:libraries:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithLicenseBytes:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>"},{"text":" *) ","kind":"text"},{"text":"libraries","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/title","op":"replace"},{"op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/fragments"},{"value":"initWithLicenseBytes:libraries:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DotSdkConfiguration","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkConfiguration\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkConfiguration\/fragments","value":[{"text":"DotSdkConfiguration","kind":"identifier"}],"op":"replace"}]}]}