{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/init(maxdetectionsizetoimageshortersideratiothreshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/init(maxdetectionsizetoimageshortersideratiothreshold:)"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:"}],"title":"init(maxDetectionSizeToImageShorterSideRatioThreshold:)","symbolKind":"init","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooLargeValidator(im)initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/init(maxDetectionSizeToImageShorterSideRatioThreshold:)":{"kind":"symbol","type":"topic","title":"init(maxDetectionSizeToImageShorterSideRatioThreshold:)","navigatorTitle":[{"text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/init(maxdetectionsizetoimageshortersideratiothreshold:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","abstract":[{"type":"text","text":"Validate size of the detected face."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SizeTooLargeValidator","kind":"identifier"}],"title":"SizeTooLargeValidator","kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoolargevalidator"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.15.1"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace"},{"op":"replace","value":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1init(maxDetectionSizeToImageShorterSideRatioThreshold:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1init(maxDetectionSizeToImageShorterSideRatioThreshold:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","value":"DOTFLSizeTooLargeValidator"},{"value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}