{"abstract":[{"type":"text","text":"Wearables query."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery\/wearables","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery(py)wearables","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wearables"},{"text":": ","kind":"text"},{"text":"WearablesQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"wearables","kind":"identifier"}],"title":"wearables"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/facequalityquery\/wearables"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facequalityquery\/wearables"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"wearables","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery","text":"WearablesQuery","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery/wearables":{"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery\/wearables","kind":"symbol","abstract":[{"text":"Wearables query.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery\/wearables","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wearables","kind":"identifier"},{"kind":"text","text":": "},{"text":"WearablesQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery"}],"title":"wearables","navigatorTitle":[{"text":"wearables","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery":{"url":"\/documentation\/dotfacecore\/facequalityquery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","role":"symbol","title":"FaceQualityQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQualityQuery"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WearablesQuery":{"type":"topic","navigatorTitle":[{"text":"WearablesQuery","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","url":"\/documentation\/dotfacecore\/wearablesquery","abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"WearablesQuery","kind":"identifier"}],"title":"WearablesQuery"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"wearables"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"wearables"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery","text":"DOTFWearablesQuery","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"wearables"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery~1wearables\/title","value":"wearables","op":"replace"},{"value":[{"kind":"identifier","text":"wearables"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery~1wearables\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/title","op":"replace","value":"DOTFFaceQualityQuery"},{"value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"value":[{"text":"DOTFWearablesQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}