{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenIsNil"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenIsNil","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error"]]},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenIsNil","kind":"identifier"}],"externalID":"s:7DotCore0A3SdkC5ErrorO29transactionCountingTokenIsNilyA2EmF","title":"DotSdk.Error.transactionCountingTokenIsNil","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Case","symbolKind":"case"},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/error\/transactioncountingtokenisnil"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotSdk":{"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","type":"topic","title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotsdk"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/transactionCountingTokenIsNil":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenIsNil"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenIsNil","title":"DotSdk.Error.transactionCountingTokenIsNil","abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/error\/transactioncountingtokenisnil","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotSdk/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"DotSdk.Error","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error","url":"\/documentation\/dotdocument\/dotsdk\/error"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle"}]}]}