{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/eyegazeliveness"]}],"kind":"symbol","metadata":{"modules":[{"name":"DotPalmCore"}],"title":"eyeGazeLiveness","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"identifier","text":"eyeGazeLiveness"}],"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLiveness"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)eyeGazeLiveness"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceEyeGazeLivenessModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotfaceeyegazelivenessmoduleconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration","title":"DotFaceEyeGazeLivenessModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules/eyeGazeLiveness":{"title":"eyeGazeLiveness","fragments":[{"kind":"identifier","text":"eyeGazeLiveness"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/eyegazeliveness","abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules","type":"topic","title":"DotFaceLibraryConfigurationModules","abstract":[{"text":"Face library module configuration.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DotFaceEyeGazeLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}