{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/facequality\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/facequality\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality(py)hash"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/hash","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality/hash":{"url":"\/documentation\/dotfacelite\/facequality\/hash","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality\/hash","role":"symbol","abstract":[],"title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"url":"\/documentation\/dotfacelite\/facequality","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","abstract":[{"type":"text","text":"Face quality."}],"title":"FaceQuality"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"hash","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title","value":"DOTFLFaceQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments","value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle","value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}