{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfidence:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"confidence"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedRectangle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"normalizedRectangle"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters","text":"DOTFLImageParameters"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageParameters"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflfacedetectorresult\/initwithconfidence:normalizedrectangle:imageparameters:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorResult\/initWithConfidence:normalizedRectangle:imageParameters:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidence:normalizedRectangle:imageParameters:"}],"title":"initWithConfidence:normalizedRectangle:imageParameters:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorResult(im)initWithConfidence:normalizedRectangle:imageParameters:","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:normalizedRectangle:imageParameters:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorResult"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceDetectorResult":{"role":"symbol","title":"DOTFLFaceDetectorResult","fragments":[{"kind":"identifier","text":"DOTFLFaceDetectorResult"}],"abstract":[{"type":"text","text":"Result of the face detection operation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotflfacedetectorresult"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotfacelite\/rectangledouble"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ImageParameters":{"role":"symbol","title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"abstract":[{"type":"text","text":"Parameters of the image which was used for the face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotfacelite\/imageparameters"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 7.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceDetectorResult/initWithConfidence:normalizedRectangle:imageParameters:":{"role":"symbol","title":"initWithConfidence:normalizedRectangle:imageParameters:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidence:normalizedRectangle:imageParameters:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorResult\/initWithConfidence:normalizedRectangle:imageParameters:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:normalizedRectangle:imageParameters:"}],"url":"\/documentation\/dotfacelite\/dotflfacedetectorresult\/initwithconfidence:normalizedrectangle:imageparameters:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/title","value":"DOTFLImageParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLImageParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}