{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"title":"initWithPreview:phase:detection:result:","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiStateRunning(im)initWithPreview:phase:detection:result:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/initwithpreview:phase:detection:result:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning"]]},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPreview:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DOTDDocumentAutoCapturePreview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preview"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTDDocumentAutoCapturePhaseWrapped","text":"DOTDDocumentAutoCapturePhaseWrapped"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"phase"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DOTDDocumentAutoCaptureDetection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DOTDDocumentAutoCaptureResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning/initWithPreview:phase:detection:result:":{"navigatorTitle":[{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"title":"initWithPreview:phase:detection:result:","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/initwithpreview:phase:detection:result:","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePreview"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","title":"DocumentAutoCapturePreview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePreview"}],"abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturepreview"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning":{"kind":"symbol","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"text":" method is called and before the process finishes.","type":"text"}],"title":"DOTDDocumentAutoCaptureUiStateRunning","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning","fragments":[{"text":"DOTDDocumentAutoCaptureUiStateRunning","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturedetection","abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","role":"symbol","title":"DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"type":"topic","abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureresult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","title":"DocumentAutoCaptureResult"}},"variantOverrides":[{"patch":[{"value":"DOTDDocumentAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title"},{"value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments"},{"value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle"},{"value":"DOTDDocumentAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle"},{"value":"DOTDDocumentAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}