{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/preview","interfaceLanguage":"occ"},"abstract":[{"text":"Preview information.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTDDocumentAutoCapturePreview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview"},{"kind":"text","text":" * "},{"kind":"identifier","text":"preview"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/preview"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"preview","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiStateRunning(py)preview","symbolKind":"property","title":"preview","fragments":[{"kind":"identifier","text":"preview"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning/preview":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/preview","title":"preview","abstract":[{"text":"Preview information.","type":"text"}],"fragments":[{"text":"preview","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/preview","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePreview"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePreview"}],"title":"DocumentAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocapturepreview","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning":{"fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiStateRunning"}],"title":"DOTDDocumentAutoCaptureUiStateRunning","type":"topic","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"type":"text","text":" method is called and before the process finishes."}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title","value":"DOTDDocumentAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}],"op":"replace"}]}]}