{"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiStateRunning(py)result","fragments":[{"kind":"identifier","text":"result"}],"navigatorTitle":[{"kind":"identifier","text":"result"}],"title":"result","role":"symbol","symbolKind":"property"},"abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/result"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/result"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DOTDDocumentAutoCaptureResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"result","kind":"identifier"},{"text":";","kind":"text"}]}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning/result":{"type":"topic","abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"kind":"symbol","title":"result","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/result","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/result","role":"symbol","fragments":[{"kind":"identifier","text":"result"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"kind":"symbol","title":"DocumentAutoCaptureResult","url":"\/documentation\/dotdocument\/documentautocaptureresult"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning":{"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiStateRunning"}],"title":"DOTDDocumentAutoCaptureUiStateRunning"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","value":"DOTDDocumentAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}],"op":"replace"}]}]}