{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentmoduleid\/rawrepresentable-implementations"]}],"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","role":"collectionGroup","modules":[{"name":"DotDocument"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/hashValue"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/hash(into:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"kind":"article","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/hash(into:)":{"title":"hash(into:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/hash(into:)","type":"topic","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/hash(into:)","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"title":"DotDocumentModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotdocument\/dotdocumentmoduleid","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/hashValue":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/hashvalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/hashValue","role":"symbol","kind":"symbol","type":"topic","abstract":[],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"title":"hashValue"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/title","op":"replace"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/fragments","op":"replace"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/navigatorTitle","op":"replace"}]}]}