{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/!=(_:_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotdocumentmoduleid\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"op","title":"!=(_:_:)","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCore@E@DotDocumentModuleId","extendedModule":"Swift","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Operator","modules":[{"name":"DotFaceCore","relatedModules":["Swift"]}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/!=(_:_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/!=(_:_:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId","title":"DotDocumentModuleId","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid","type":"topic","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentModuleId","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/navigatorTitle"}]}]}