{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/cameraimagesource"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/cameraimagesource"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSource","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/init(configuration:videoQueue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/delegate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/orientation","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/previewView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/startSession()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/stopSession()"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/Error"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"}],"title":"CameraImageSource","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)CameraImageSource","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"CameraImageSource"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"references":{"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/delegate":{"role":"symbol","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSourceDelegate","preciseIdentifier":"s:11DotDocument19ImageSourceDelegateP"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/delegate","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/cameraimagesource\/delegate"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/stopSession()":{"role":"symbol","title":"stopSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopSession"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stops camera session and stops producing images. This method should be called on the background thread."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/stopSession()","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/cameraimagesource\/stopsession()"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/init(configuration:videoQueue:)":{"role":"symbol","title":"init(configuration:videoQueue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraImageSourceConfiguration","preciseIdentifier":"s:11DotDocument30CameraImageSourceConfigurationV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"videoQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/init(configuration:videoQueue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/cameraimagesource\/init(configuration:videoqueue:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/orientation":{"role":"symbol","title":"orientation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"orientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSourceOrientation","preciseIdentifier":"s:11DotDocument22ImageSourceOrientationO"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/orientation","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/cameraimagesource\/orientation"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/startSession()":{"role":"symbol","title":"startSession()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startSession"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Starts camera session and starts producing images. This method should be called on the background thread."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/startSession()","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/cameraimagesource\/startsession()"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations":{"role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotdocument\/cameraimagesource\/avcapturevideodataoutputsamplebufferdelegate-implementations"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate":{"type":"unresolvable","title":"AVFoundation.AVCaptureVideoDataOutputSampleBufferDelegate","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)AVCaptureVideoDataOutputSampleBufferDelegate"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/previewView":{"role":"symbol","title":"previewView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/previewView","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/cameraimagesource\/previewview"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource":{"role":"symbol","title":"CameraImageSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraImageSource"}],"url":"\/documentation\/dotdocument\/cameraimagesource"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageSource":{"role":"symbol","title":"ImageSource","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSource"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSource"}],"url":"\/documentation\/dotdocument\/imagesource"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraImageSource/Error":{"role":"symbol","title":"CameraImageSource.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotdocument\/cameraimagesource\/error"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"CameraImageSource"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"CameraImageSource"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"CameraImageSource"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraImageSource\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraImageSource\/title","value":"CameraImageSource"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraImageSource\/fragments","value":[{"kind":"identifier","text":"CameraImageSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}