{"variants":[{"paths":["\/documentation\/dotnfc\/ciimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/ciimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CIImageFactory"]]},"metadata":{"title":"create(bgraRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"roleHeading":"Type Method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotNfc"}]},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgraRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}]}],"name":"bgraRawImage"}],"kind":"parameters"},{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" instance."}]}],"kind":"content"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CIImageFactory\/create(bgraRawImage:)"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/CIImageFactory":{"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/ciimagefactory","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CIImageFactory","role":"symbol","title":"CIImageFactory"},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"type":"topic","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrarawimage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","role":"symbol","title":"BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/CIImageFactory/create(bgraRawImage:)":{"role":"symbol","url":"\/documentation\/dotnfc\/ciimagefactory\/create(bgrarawimage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CIImageFactory\/create(bgraRawImage:)","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"kind":"symbol","title":"create(bgraRawImage:)","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createWithBgraRawImage:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}]}],"name":"bgraRawImage"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"DOTCIImageFactory","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CIImageFactory\/title"},{"value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CIImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CIImageFactory\/navigatorTitle"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/navigatorTitle"},{"value":"createWithBgraRawImage:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CIImageFactory~1create(bgraRawImage:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CIImageFactory~1create(bgraRawImage:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}