{"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","symbolKind":"property","title":"left","externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)left","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"left"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/left"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Left edge."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/left"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/left"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble/left":{"navigatorTitle":[{"text":"left","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/left","kind":"symbol","abstract":[{"type":"text","text":"Left edge."}],"title":"left","url":"\/documentation\/dotfacecore\/rectangledouble\/left","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.9.0","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","url":"\/documentation\/dotfacecore\/rectangledouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"left"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"left","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"kind":"identifier","text":"left"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"left","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1left\/title"},{"value":[{"kind":"identifier","text":"left"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1left\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}