{"variants":[{"paths":["\/documentation\/dotfacecore\/detectionposition\/center"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/detectionposition\/center"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"center"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"center"}],"roleHeading":"Instance Property","title":"center","externalID":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition(py)center","role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition\/center","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"center"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Center of the face in the image."}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","abstract":[{"type":"text","text":"The position of the detected face in the image."}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"title":"DetectionPosition","url":"\/documentation\/dotfacecore\/detectionposition","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble":{"kind":"symbol","url":"\/documentation\/dotfacecore\/pointdouble","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition/center":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition\/center","kind":"symbol","navigatorTitle":[{"text":"center","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Center of the face in the image.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/detectionposition\/center","title":"center","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"title":"MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"title":"SmileLivenessViewController","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"kind":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"title":"FaceSimpleCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing face images."}],"navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","role":"symbol","kind":"symbol","deprecated":true,"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"center","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"center","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPointDouble","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTPointDouble"},{"text":" * ","kind":"text"},{"text":"center","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/navigatorTitle"},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/title"},{"op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/navigatorTitle"},{"op":"replace","value":"center","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition~1center\/title"},{"op":"replace","value":[{"text":"center","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition~1center\/fragments"},{"op":"replace","value":"DOTFMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle"},{"op":"replace","value":"DOTFSmileLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle"},{"op":"replace","value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}