{"abstract":[{"type":"text","text":"Diameter of the face circle represented as a ratio to the image shorter side."}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition\/sizeToImageShorterSideRatio","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/detectionposition\/sizetoimageshortersideratio"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/detectionposition\/sizetoimageshortersideratio"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"sizeToImageShorterSideRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"sizeToImageShorterSideRatio","externalID":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition(py)sizeToImageShorterSideRatio","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeToImageShorterSideRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"sizeToImageShorterSideRatio","kind":"identifier"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"type":"text","text":"version: 8.6.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"title":"FaceAutoCaptureViewController","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"abstract":[{"type":"text","text":"The position of the detected face in the image."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"title":"DetectionPosition","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","url":"\/documentation\/dotfacecore\/detectionposition","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"deprecated":true,"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","abstract":[{"type":"text","text":"UI component for capturing face images."}],"title":"FaceSimpleCaptureViewController","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition/sizeToImageShorterSideRatio":{"url":"\/documentation\/dotfacecore\/detectionposition\/sizetoimageshortersideratio","kind":"symbol","title":"sizeToImageShorterSideRatio","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition\/sizeToImageShorterSideRatio","navigatorTitle":[{"text":"sizeToImageShorterSideRatio","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeToImageShorterSideRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[{"text":"Diameter of the face circle represented as a ratio to the image shorter side.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"title":"SmileLivenessViewController","navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"kind":"symbol","type":"topic","title":"MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"sizeToImageShorterSideRatio"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sizeToImageShorterSideRatio"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"sizeToImageShorterSideRatio","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"value":"DOTDetectionPosition","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]},{"value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition~1sizeToImageShorterSideRatio\/title","value":"sizeToImageShorterSideRatio","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition~1sizeToImageShorterSideRatio\/fragments","value":[{"kind":"identifier","text":"sizeToImageShorterSideRatio"}]},{"value":"DOTFSmileLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}