{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidBounds","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervaldouble\/error\/invalidbounds"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidBounds","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","externalID":"s:7DotCore14IntervalDoubleC5ErrorO13invalidBoundsyA2EmF","role":"symbol","title":"IntervalDouble.Error.invalidBounds"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/invalidBounds"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/IntervalDouble":{"kind":"symbol","role":"symbol","title":"IntervalDouble","type":"topic","url":"\/documentation\/dotnfc\/intervaldouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error":{"kind":"symbol","role":"symbol","title":"IntervalDouble.Error","type":"topic","url":"\/documentation\/dotnfc\/intervaldouble\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error/invalidBounds":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidBounds"}],"type":"topic","url":"\/documentation\/dotnfc\/intervaldouble\/error\/invalidbounds","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/invalidBounds","abstract":[],"kind":"symbol","title":"IntervalDouble.Error.invalidBounds"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/title"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/fragments"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}