{"metadata":{"externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC19maxDevicePitchAngleAA12WrappedFloatCSgvp","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDevicePitchAngle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat","text":"WrappedFloat"},{"text":"?","kind":"text"}],"title":"maxDevicePitchAngle","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"text":"Maximal pitch angle of the device.","type":"text"},{"type":"text","text":" "},{"text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/maxDevicePitchAngle"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/maxdevicepitchangle"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"maxDevicePitchAngle","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat","kind":"typeIdentifier","text":"WrappedFloat"},{"kind":"text","text":"?"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat":{"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WrappedFloat","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"WrappedFloat","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"url":"\/documentation\/dotfacelite\/wrappedfloat"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/maxDevicePitchAngle":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/maxDevicePitchAngle","kind":"symbol","abstract":[{"text":"Maximal pitch angle of the device.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"maxDevicePitchAngle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WrappedFloat","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat"},{"kind":"text","text":"?"}],"title":"maxDevicePitchAngle","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/maxdevicepitchangle","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/title","value":"DOTWrappedFloat","op":"replace"},{"value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFLFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}