{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId"]]},"sections":[],"metadata":{"symbolKind":"property","role":"symbol","title":"description","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Instance Property","externalID":"s:7DotCore0A15FingersModuleIdO11descriptionSSvp"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfingersmoduleid\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/description"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/description":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/description","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/description","kind":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"url":"\/documentation\/dotfacecore\/dotfingersmoduleid","title":"DotFingersModuleId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId","abstract":[{"code":"DotFingers","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersModuleId","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/title"},{"value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/fragments"},{"value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/navigatorTitle"}]}]}