{"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"middle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ring"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"little"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithIndex:middle:ring:little:"}],"title":"init(index:middle:ring:little:)","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages(im)initWithIndex:middle:ring:little:","symbolKind":"init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"index","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?, ","kind":"text"},{"text":"middle","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?, ","kind":"text"},{"text":"ring","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?, ","kind":"text"},{"text":"little","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?)","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingerprintimages\/init(index:middle:ring:little:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingerprintimages\/init(index:middle:ring:little:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/init(index:middle:ring:little:)"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfingerscore\/image","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/init(index:middle:ring:little:)":{"title":"init(index:middle:ring:little:)","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingerprintimages\/init(index:middle:ring:little:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"middle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ring"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"little"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithIndex:middle:ring:little:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/init(index:middle:ring:little:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages","type":"topic","title":"FingerprintImages","url":"\/documentation\/dotfingerscore\/fingerprintimages","abstract":[{"text":"Fingerprint images of four fingers.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerprintImages"}],"navigatorTitle":[{"kind":"identifier","text":"FingerprintImages"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithIndex:middle:ring:little:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIndex:middle:ring:little:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"index"},{"kind":"text","text":" "},{"kind":"identifier","text":"middle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"middle"},{"kind":"text","text":" "},{"kind":"identifier","text":"ring:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ring"},{"kind":"text","text":" "},{"kind":"identifier","text":"little:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"little"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]},{"value":"initWithIndex:middle:ring:little:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1init(index:middle:ring:little:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIndex:middle:ring:little:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1init(index:middle:ring:little:)\/fragments"},{"op":"replace","value":"DOTFGFingerprintImages","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}