{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)","interfaceLanguage":"swift"},"metadata":{"title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"case","modules":[{"name":"DotFaceCore"}],"externalID":"s:7DotCore0A3SdkC5ErrorO19failedToLoadLibraryyAeA0aH2IdO_tcAEmF","roleHeading":"Case"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdk\/error\/failedtoloadlibrary(libraryid:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/failedToLoadLibrary(libraryId:)":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)","type":"topic","url":"\/documentation\/dotfacecore\/dotsdk\/error\/failedtoloadlibrary(libraryid:)","role":"symbol","title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"role":"symbol","title":"DotSdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotsdk","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error":{"role":"symbol","title":"DotSdk.Error","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error","url":"\/documentation\/dotfacecore\/dotsdk\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotlibraryid","kind":"symbol","title":"DotLibraryId","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle"},{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments"},{"value":[{"kind":"identifier","text":"DotLibraryId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/navigatorTitle"}]}]}