{"abstract":[{"text":"Current phase of the fingers auto capture process.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"phase"}],"navigatorTitle":[{"kind":"identifier","text":"phase"}],"title":"phase","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerProcessingResult(py)phase","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTFGFingersAutoCapturePhase","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerprocessingresult\/phase"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult\/phase","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerProcessingResult":{"kind":"symbol","title":"DOTFGFingersAutoCaptureControllerProcessingResult","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerprocessingresult","fragments":[{"text":"DOTFGFingersAutoCaptureControllerProcessingResult","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The result returned from the processing of one image during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"text":"Phase of the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePhase","kind":"identifier"}],"title":"FingersAutoCapturePhase","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerProcessingResult/phase":{"kind":"symbol","title":"phase","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerprocessingresult\/phase","fragments":[{"kind":"identifier","text":"phase"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Current phase of the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult\/phase"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingersAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle"}]}]}