{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessConfiguration(py)cameraPreviewScaleType","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"cameraPreviewScaleType","kind":"identifier"}],"fragments":[{"text":"cameraPreviewScaleType","kind":"identifier"}],"title":"cameraPreviewScaleType"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraPreviewScaleType","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Specify camera preview scale type. Default is "},{"type":"text","text":".fit"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/cameraPreviewScaleType"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration/cameraPreviewScaleType":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/cameraPreviewScaleType","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/camerapreviewscaletype","fragments":[{"text":"cameraPreviewScaleType","kind":"identifier"}],"title":"cameraPreviewScaleType","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Specify camera preview scale type. Default is "},{"type":"text","text":".fit"},{"type":"text","text":"."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration":{"url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration","abstract":[{"text":"Configuration options for the Multi-Range Liveness process.","type":"text"}],"role":"symbol","fragments":[{"text":"DOTFLMultiRangeLivenessConfiguration","kind":"identifier"}],"type":"topic","title":"DOTFLMultiRangeLivenessConfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}