{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessConfiguration(im)initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:"}],"symbolKind":"method","title":"initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration"]]},"sections":[],"abstract":[{"text":"Create the Multi-Range Liveness configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"challengeSequence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DOTWrappedMultiRangeLivenessChallengeItem *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"challengeSequence"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","kind":"typeIdentifier","text":"DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","kind":"typeIdentifier","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCameraPreviewVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isCameraPreviewVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/initwithsessiontoken:challengesequence:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:error:"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration":{"url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration","abstract":[{"text":"Configuration options for the Multi-Range Liveness process.","type":"text"}],"role":"symbol","fragments":[{"text":"DOTFLMultiRangeLivenessConfiguration","kind":"identifier"}],"type":"topic","title":"DOTFLMultiRangeLivenessConfiguration","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"title":"CameraFacing","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacelite\/camerafacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","kind":"symbol","abstract":[{"type":"text","text":"Facing of the camera on the device."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration/initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Create the Multi-Range Liveness configuration."}],"role":"symbol","navigatorTitle":[{"text":"initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","type":"topic","title":"initWithSessionToken:challengeSequence:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/initwithsessiontoken:challengesequence:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:error:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}