{"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessConfiguration(im)initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:","modules":[{"name":"DotFaceLite"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:","kind":"identifier"}],"role":"symbol","title":"initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCommon:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","kind":"typeIdentifier","text":"DOTCommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration"},{"text":" *) ","kind":"text"},{"text":"camera","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"challengeSequence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTWrappedMultiRangeLivenessChallengeItem *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"challengeSequence","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Create the Multi-Range Liveness configuration."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/initwithcommon:camera:challengesequence:isdetectionlayervisible:error:"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration"]]},"sections":[],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration","role":"symbol","fragments":[{"text":"DOTFLMultiRangeLivenessConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration","type":"topic","title":"DOTFLMultiRangeLivenessConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"url":"\/documentation\/dotfacelite\/commonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","type":"topic","kind":"symbol","abstract":[{"text":"Common configuration for all components.","type":"text"}],"title":"CommonConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/cameraconfiguration","title":"CameraConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration/initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:","kind":"identifier"}],"abstract":[{"text":"Create the Multi-Range Liveness configuration.","type":"text"}],"navigatorTitle":[{"text":"initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:","kind":"symbol","role":"symbol","title":"initWithCommon:camera:challengeSequence:isDetectionLayerVisible:error:","type":"topic","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/initwithcommon:camera:challengesequence:isdetectionlayervisible:error:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle","op":"replace"},{"value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","op":"replace"}]}]}