{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error\/licenseDataNotSet","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotsdk\/error\/licensedatanotset"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseDataNotSet"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseDataNotSet","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}],"title":"DotSdk.Error.licenseDataNotSet","externalID":"s:7DotCore0A3SdkC5ErrorO17licenseDataNotSetyA2EmF","roleHeading":"Case"},"references":{"doc://DotNfc/documentation/DotNfc/DotSdk/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/dotsdk\/error","title":"DotSdk.Error","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error","type":"topic","kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdk":{"type":"topic","url":"\/documentation\/dotnfc\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotSdk/Error/licenseDataNotSet":{"url":"\/documentation\/dotnfc\/dotsdk\/error\/licensedatanotset","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseDataNotSet"}],"kind":"symbol","title":"DotSdk.Error.licenseDataNotSet","abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error\/licenseDataNotSet"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"}]}]}