{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:cameraprevi-4q0q7"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","interfaceLanguage":"occ"},"metadata":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","modules":[{"name":"DotDocument"}],"title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTDQualityAttributeThresholds","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDQualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDQualityAttributeThresholds"},{"kind":"text","text":" *) "},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"kind":"text","text":" "},{"text":"minValidFramesInRowToStartCandidateSelection:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"text":" ","kind":"text"},{"kind":"identifier","text":"candidateSelectionDurationMillis:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationMode:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"DOTDValidationMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"validationMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mrzValidation:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTDMrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"mrzValidation"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isTorchEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","text":"DOTCameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":") "},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraPreviewScaleType","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderType:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"DOTDPlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"placeholderType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCameraPreviewVisible:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isCameraPreviewVisible"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DOTDQualityAttributeThresholds":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","title":"DOTDQualityAttributeThresholds","fragments":[{"text":"DOTDQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdqualityattributethresholds"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"text":"version: 8.13.0","type":"text"}],"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration":{"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration","kind":"symbol","title":"DOTDDocumentAutoCaptureConfiguration","role":"symbol","fragments":[{"text":"DOTDDocumentAutoCaptureConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration","type":"topic","abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:cameraprevi-4q0q7","title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:error:","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","type":"topic","abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"title":"PlaceholderType","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotdocument\/placeholdertype","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzValidation"}],"navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"type":"topic","abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzvalidation","title":"MrzValidation","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"url":"\/documentation\/dotdocument\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","role":"symbol"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"title":"ValidationMode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/validationmode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"title":"CameraPreviewScaleType","url":"\/documentation\/dotdocument\/camerapreviewscaletype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}]}},"variantOverrides":[{"patch":[{"value":"DOTDPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"op":"replace"},{"value":"DOTDMrzValidation","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","op":"replace","value":"DOTDValidationMode"},{"value":[{"text":"DOTDValidationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}