{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPreview:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview","text":"DOTPPalmAutoCapturePreview"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preview"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiStateIdle(im)initWithPreview:","title":"initWithPreview:","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithPreview:","kind":"identifier"}],"symbolKind":"method"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureuistateidle\/initwithpreview:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle\/initWithPreview:"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateIdle/initWithPreview:":{"title":"initWithPreview:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle\/initWithPreview:","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistateidle\/initwithpreview:","type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturepreview","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCapturePreview","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"type":"topic","title":"PalmAutoCapturePreview"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateIdle":{"title":"DOTPPalmAutoCaptureUiStateIdle","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiStateIdle"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistateidle","type":"topic","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title","op":"replace","value":"DOTPPalmAutoCapturePreview"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}