{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle\/preview"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureuistateidle\/preview"]}],"abstract":[{"text":"Preview information.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"preview","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiStateIdle(py)preview","symbolKind":"property","title":"preview","fragments":[{"kind":"identifier","text":"preview"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTPPalmAutoCapturePreview","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview"},{"kind":"text","text":" * "},{"kind":"identifier","text":"preview"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateIdle/preview":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle\/preview","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Preview information."}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistateidle\/preview","title":"preview","fragments":[{"kind":"identifier","text":"preview"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateIdle":{"role":"symbol","type":"topic","title":"DOTPPalmAutoCaptureUiStateIdle","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistateidle","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiStateIdle"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"role":"symbol","type":"topic","title":"PalmAutoCapturePreview","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturepreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCapturePreview"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCapturePreview"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","title":"DotPalmCore","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.2.2"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title","value":"DOTPPalmAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}