{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSizeTooLargeValidator(cpy)defaultMaxDetectionSizeToImageShorterSideRatioThreshold","navigatorTitle":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}],"roleHeading":"Type Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Default threshold."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"kind":"symbol","role":"symbol","title":"SizeTooLargeValidator","abstract":[{"text":"Validate whether the size of the detected fingers is too large.","type":"text"}],"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sizetoolargevalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/defaultMaxDetectionSizeToImageShorterSideRatioThreshold":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","role":"symbol","title":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","abstract":[{"type":"text","text":"Default threshold."}],"navigatorTitle":[{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title","value":"DOTFGSizeTooLargeValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/title","value":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}]}]}]}