{"metadata":{"navigatorTitle":[{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSizeTooLargeValidator(py)maxDetectionSizeToImageShorterSideRatioThreshold","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"maxDetectionSizeToImageShorterSideRatioThreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Current maximal detection size to image shorter side ratio threshold.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/maxDetectionSizeToImageShorterSideRatioThreshold":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold","abstract":[{"type":"text","text":"Current maximal detection size to image shorter side ratio threshold."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold","title":"maxDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"kind":"symbol","role":"symbol","title":"SizeTooLargeValidator","abstract":[{"text":"Validate whether the size of the detected fingers is too large.","type":"text"}],"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sizetoolargevalidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/title","value":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title","value":"DOTFGSizeTooLargeValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments","value":[{"text":"DOTFGSizeTooLargeValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle","value":[{"text":"DOTFGSizeTooLargeValidator","kind":"identifier"}]}]}]}