{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isPreviewVisible","kind":"identifier"}],"title":"isPreviewVisible","symbolKind":"property","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isPreviewVisible"},"kind":"symbol","sections":[],"abstract":[{"text":"Use this flag to show\/hide camera preview. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/isPreviewVisible"},"variants":[{"paths":["\/documentation\/dotdocument\/cameraconfiguration\/ispreviewvisible"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/cameraconfiguration\/ispreviewvisible"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"url":"\/documentation\/dotdocument\/cameraconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"title":"CameraConfiguration","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration/isPreviewVisible":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isPreviewVisible","kind":"identifier"}],"title":"isPreviewVisible","url":"\/documentation\/dotdocument\/cameraconfiguration\/ispreviewvisible","abstract":[{"text":"Use this flag to show\/hide camera preview. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/isPreviewVisible"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isPreviewVisible"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isPreviewVisible","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/fragments","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1isPreviewVisible\/title","op":"replace","value":"isPreviewVisible"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1isPreviewVisible\/fragments","op":"replace","value":[{"text":"isPreviewVisible","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}