{"metadata":{"fragments":[{"text":"verification","kind":"identifier"}],"navigatorTitle":[{"text":"verification","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"title":"verification","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)verification","symbolKind":"property","role":"symbol"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/verification"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"verification"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/verification"]}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","abstract":[{"text":"Face library module configuration.","type":"text"}],"kind":"symbol","title":"DotFaceLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceVerificationModuleConfiguration":{"type":"topic","title":"DotFaceVerificationModuleConfiguration","url":"\/documentation\/dotnfc\/dotfaceverificationmoduleconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Face verification module."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules/verification":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/verification","type":"topic","abstract":[],"fragments":[{"text":"verification","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/verification","title":"verification"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/title","op":"replace","value":"DotFaceVerificationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}]}]}