{"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]]},"metadata":{"title":"faceAutoCaptureViewControllerViewDidDisappear(_:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceAutoCaptureViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate(im)faceAutoCaptureViewControllerViewDidDisappear:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidDisappear:"}]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidDisappear(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidDisappear"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewDidDisappear(_:)":{"abstract":[],"title":"faceAutoCaptureViewControllerViewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidDisappear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdiddisappear(_:)","role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"faceAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidDisappear(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"type":"topic","role":"symbol","title":"FaceAutoCaptureViewControllerDelegate","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"abstract":[{"text":"Implement this delegate to handle the face auto capture events.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"faceAutoCaptureViewControllerViewDidDisappear:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidDisappear:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"faceAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","value":"faceAutoCaptureViewControllerViewDidDisappear:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidDisappear(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidDisappear:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidDisappear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFFaceAutoCaptureViewControllerDelegate","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments"}]}]}