{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"? = nil, "},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"},{"text":" = QualityAttributeThresholdPresets.standard.build(), ","kind":"text"},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = DocumentAutoCaptureController.Configuration.Defaults\n                .minValidFramesInRowToStartCandidateSelection, "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = DocumentAutoCaptureController.Configuration.Defaults.candidateSelectionDurationMillis, ","kind":"text"},{"kind":"externalParam","text":"validationMode"},{"text":": ","kind":"text"},{"text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode"},{"text":" = Defaults.validationMode, ","kind":"text"},{"text":"mrzValidation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzValidation","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":" = Defaults.mrzValidation, ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = Defaults.isVideoCaptureEnabled, ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","text":"CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"text":"placeholderType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType"},{"kind":"text","text":" = Defaults.placeholderType, "},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = Defaults.isCameraPreviewVisible) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviews-37u46"]}],"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","kind":"typeIdentifier","text":"QualityAttributeThresholds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"kind":"text","text":", "},{"text":"mrzValidation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"kind":"text","text":", "},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Initializer","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds44minValidFramesInRowToStartCandidateSelection09candidateU14DurationMillis14validationMode13mrzValidation23isDetectionLayerVisible14isTorchEnabled07isVideoD7Enabled12cameraFacing22cameraPreviewScaleType15placeholderType22isCameraPreviewVisibleAESSSg_AE07QualitykL0CS2iAA010ValidationZ0OAA13MrzValidationOS3b0A6Camera12CameraFacingOAZ22CameraPreviewScaleTypeOAA15PlaceholderTypeOSbtKcfc","modules":[{"name":"DotDocument"}],"symbolKind":"init","title":"init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","title":"DocumentAutoCaptureViewController.Configuration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"title":"CameraPreviewScaleType","url":"\/documentation\/dotdocument\/camerapreviewscaletype","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"url":"\/documentation\/dotdocument\/mrzvalidation","title":"MrzValidation","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds","role":"symbol","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"QualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"type":"topic","abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"url":"\/documentation\/dotdocument\/placeholdertype","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"title":"PlaceholderType"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"role":"symbol","kind":"symbol","type":"topic","title":"CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotdocument\/camerafacing"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)":{"kind":"symbol","abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"text":", ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"text":": ","kind":"text"},{"text":"ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"kind":"text","text":", "},{"text":"mrzValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placeholderType"},{"text":": ","kind":"text"},{"text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)","type":"topic","title":"init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviews-37u46"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"title":"ValidationMode","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/validationmode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationMode"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments"},{"value":"DOTDMrzValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","op":"replace"},{"value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","op":"replace","value":"DOTDPlaceholderType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"value":"DOTDValidationMode","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title"},{"value":[{"text":"DOTDValidationMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}