{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BezierPathFactory","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTBezierPathFactory","symbolKind":"class","title":"BezierPathFactory"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTBezierPathFactory) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"languages":["swift"]}]}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/bezierpathfactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/bezierpathfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"type":"topic","title":"createDetectionPath(corners:cornerRadius:)","navigatorTitle":[{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","kind":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTCorners","kind":"typeIdentifier","text":"Corners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}]},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"text":"version: 8.4.1","type":"text"}]},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BezierPathFactory":{"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}],"title":"BezierPathFactory","url":"\/documentation\/dotfacecore\/bezierpathfactory","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}]},"doc://com.innovatrics.dot.face.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"title":"createPlaceholderPath(rect:cornerRadius:)","url":"\/documentation\/dotfacecore\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createPlaceholderPath","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rect"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}]},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTBezierPathFactory","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTBezierPathFactory"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTBezierPathFactory"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","op":"replace","value":"createDetectionPathWithCorners:cornerRadius:"},{"value":[{"text":"+ ","kind":"text"},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory\/title","value":"DOTBezierPathFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory\/fragments","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}]},{"value":"createPlaceholderPathWithRect:cornerRadius:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}]}]}]}