{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"size","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)size","navigatorTitle":[{"text":"size","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/size"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"_RawImage.size"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/bgrarawimage\/size"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/bgrarawimage\/size"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"url":"\/documentation\/dotfacecore\/bgrarawimage","kind":"symbol","title":"BgraRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage/size":{"navigatorTitle":[{"text":"size","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfacecore\/bgrarawimage\/size","kind":"symbol","title":"size","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/size","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","role":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"kind":"symbol","type":"topic","title":"ImageSize","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/imagesize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"size"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"size"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DOTImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"},{"text":" * ","kind":"text"},{"text":"size","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1size\/title","op":"replace","value":"size"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1size\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"}]}]}