{"metadata":{"roleHeading":"Instance Method","title":"requestCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"()"}],"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController(im)requestCapture","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"requestCapture"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Request capture of the next detection."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/requestcapture()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/requestcapture()"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/requestCapture()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"type":"topic","title":"BasePalmAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/requestCapture()":{"type":"topic","title":"requestCapture()","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/requestCapture()","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/requestcapture()","kind":"symbol","navigatorTitle":[{"text":"requestCapture","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"requestCapture","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCapture","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPBasePalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"requestCapture","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1requestCapture()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1requestCapture()\/fragments"}]}]}