{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running\/confirmedfingertypes"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Confirmed finger types. These finger types have completed their candidate-selection animation and are marked in the UI.","type":"text"}],"metadata":{"title":"confirmedFingerTypes","externalID":"s:14DotFingersCore0B18AutoCaptureUiStateC7RunningC20confirmedFingerTypesSayAA0J4TypeO7WrappedCGvp","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmedFingerTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"FingerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmedFingerTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"},{"text":".","kind":"text"},{"text":"Wrapped","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped"},{"text":"]","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running\/confirmedFingerTypes"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Running/confirmedFingerTypes":{"title":"confirmedFingerTypes","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running\/confirmedfingertypes","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confirmedFingerTypes","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","text":"Wrapped"},{"text":"]","kind":"text"}],"role":"symbol","type":"topic","abstract":[{"text":"Confirmed finger types. These finger types have completed their candidate-selection animation and are marked in the UI.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running\/confirmedFingerTypes"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/Wrapped":{"type":"topic","kind":"symbol","title":"FingerType.Wrapped","url":"\/documentation\/dotfingerscore\/fingertype\/wrapped","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState":{"kind":"symbol","title":"FingersAutoCaptureUiState","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Running":{"title":"FingersAutoCaptureUiState.Running","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Running","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Running state."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/title","op":"replace","value":"DOTFGFingersAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/fragments","op":"replace","value":[{"text":"DOTFGFingersAutoCaptureUiState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"text":"DOTFGFingersAutoCaptureUiState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","op":"replace","value":"DOTFGFingerType"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","op":"replace","value":[{"text":"DOTFGFingerType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","op":"replace","value":[{"text":"DOTFGFingerType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}