{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview","kind":"typeIdentifier","text":"FingersAutoCapturePreview","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview"},{"kind":"text","text":", "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","kind":"typeIdentifier","text":"FingersAutoCapturePhase","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14DotFingersCore0B16AutoCapturePhaseO7WrappedC","kind":"typeIdentifier","text":"Wrapped","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection","kind":"typeIdentifier","text":"FingersAutoCaptureDetection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","text":"FingerType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","kind":"typeIdentifier","text":"Wrapped","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"confirmedFingerTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","text":"Wrapped"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","kind":"typeIdentifier","text":"FingersAutoCaptureResult","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult"},{"text":"?)","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running\/init(preview:phase:detection:selectedfingertypes:confirmedfingertypes:result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"init(preview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:)","externalID":"s:14DotFingersCore0B18AutoCaptureUiStateC7RunningC7preview5phase9detection19selectedFingerTypes09confirmedmN06resultAeA0bdE7PreviewC_AA0bdE5PhaseO7WrappedCSgAA0bdE9DetectionCSgSayAA0M4TypeOAPCGAyA0bdE6ResultCSgtcfc","roleHeading":"Initializer","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview","kind":"typeIdentifier","text":"FingersAutoCapturePreview"},{"kind":"text","text":", "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","kind":"typeIdentifier","text":"FingersAutoCapturePhase"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14DotFingersCore0B16AutoCapturePhaseO7WrappedC","kind":"typeIdentifier","text":"Wrapped"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection","kind":"typeIdentifier","text":"FingersAutoCaptureDetection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","text":"FingerType"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","kind":"typeIdentifier","text":"Wrapped"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"confirmedFingerTypes"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","text":"FingerType"},{"kind":"text","text":"."},{"preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","kind":"typeIdentifier","text":"Wrapped"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","kind":"typeIdentifier","text":"FingersAutoCaptureResult"},{"kind":"text","text":"?)"}],"symbolKind":"init","modules":[{"name":"DotFingersCore"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running\/init(preview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"role":"symbol","title":"FingersAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the fingers auto capture process."}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePreview","kind":"identifier"}],"title":"FingersAutoCapturePreview","navigatorTitle":[{"text":"FingersAutoCapturePreview","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview","kind":"symbol","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Running":{"title":"FingersAutoCaptureUiState.Running","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Running","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Running state."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState":{"kind":"symbol","title":"FingersAutoCaptureUiState","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureUiState","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Running/init(preview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:)":{"role":"symbol","title":"init(preview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:)","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running\/init(preview:phase:detection:selectedfingertypes:confirmedfingertypes:result:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview","kind":"typeIdentifier","text":"FingersAutoCapturePreview"},{"kind":"text","text":", "},{"kind":"externalParam","text":"phase"},{"text":": ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B16AutoCapturePhaseO7WrappedC","text":"Wrapped"},{"kind":"text","text":"?, "},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection"},{"text":"?, ","kind":"text"},{"text":"selectedFingerTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Wrapped","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"confirmedFingerTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"},{"kind":"text","text":"."},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"text":"FingersAutoCaptureResult","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running\/init(preview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/Wrapped":{"title":"FingersAutoCapturePhase.Wrapped","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/wrapped","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"text":"Phase of the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePhase","kind":"identifier"}],"title":"FingersAutoCapturePhase","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/Wrapped":{"type":"topic","kind":"symbol","title":"FingerType.Wrapped","url":"\/documentation\/dotfingerscore\/fingertype\/wrapped","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"kind":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"DOTFGFingersAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle"},{"value":"DOTFGFingersAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/title","value":"DOTFGFingersAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCapturePhase","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle"},{"value":"DOTFGFingersAutoCaptureDetection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}