{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"variants":[{"paths":["\/documentation\/dotnfc\/loggerloglevel\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/loggerloglevel\/warning"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"DotNfc"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"title":"LoggerLogLevel.warning","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelWarning","navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/warning"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"title":"LoggerLogLevel","type":"topic","abstract":[{"text":"Available log levels.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"url":"\/documentation\/dotnfc\/loggerloglevel"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/warning":{"type":"topic","url":"\/documentation\/dotnfc\/loggerloglevel\/warning","title":"LoggerLogLevel.warning","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/warning","abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTLoggerLogLevelWarning"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1warning\/title","value":"DOTLoggerLogLevelWarning","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1warning\/fragments","value":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}