{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureuistate\/init"]}],"metadata":{"title":"init","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiState(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiState\/init"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiState/init":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistate\/init","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiState\/init","title":"init"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"title":"FaceAutoCaptureUiState","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureuistate","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFLFaceAutoCaptureUiState","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}