{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluatePassiveLiveness"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method requires "},{"type":"codeVoice","code":"DotFacePassiveLiveness"},{"type":"text","text":" module to be active. This method should be called on the background thread."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/detectedface\/evaluatepassiveliveness()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/detectedface\/evaluatepassiveliveness()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace\/evaluatePassiveLiveness()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Evaluation of passive liveness."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluatePassiveLiveness"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"}],"title":"evaluatePassiveLiveness()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace(im)evaluatePassiveLivenessAndReturnError:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"evaluatePassiveLivenessAndReturnError:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace"],["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectedFace/evaluatePassiveLiveness()":{"role":"symbol","title":"evaluatePassiveLiveness()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluatePassiveLiveness"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"}],"abstract":[{"type":"text","text":"Evaluation of passive liveness."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace\/evaluatePassiveLiveness()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"evaluatePassiveLivenessAndReturnError:"}],"url":"\/documentation\/dotfacecore\/detectedface\/evaluatepassiveliveness()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector":{"role":"symbol","title":"FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"url":"\/documentation\/dotfacecore\/facedetector"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAttribute":{"role":"symbol","title":"FaceAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}],"abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"url":"\/documentation\/dotfacecore\/faceattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectedFace":{"role":"symbol","title":"DetectedFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectedFace"}],"abstract":[{"type":"text","text":"Result of face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectedFace"}],"url":"\/documentation\/dotfacecore\/detectedface"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"evaluatePassiveLivenessAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"evaluatePassiveLivenessAndReturnError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"evaluatePassiveLivenessAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace~1evaluatePassiveLiveness()\/title","value":"evaluatePassiveLivenessAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace~1evaluatePassiveLiveness()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"evaluatePassiveLivenessAndReturnError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/title","value":"DOTFDetectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/fragments","value":[{"kind":"identifier","text":"DOTFDetectedFace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}