{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointInt"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/pointint\/x"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/pointint\/x"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"x","externalID":"c:@M@DotCore@objc(cs)DOTPointInt(py)x","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"x"}],"symbolKind":"property","modules":[{"name":"DotFingersCore"}]},"abstract":[{"text":"X coordinate.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointInt\/x","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/PointInt":{"kind":"symbol","title":"PointInt","url":"\/documentation\/dotfingerscore\/pointint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointInt"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/PointInt/x":{"kind":"symbol","title":"x","url":"\/documentation\/dotfingerscore\/pointint\/x","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"x"}],"type":"topic","abstract":[{"type":"text","text":"X coordinate."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PointInt\/x"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"x","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"x","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPointInt","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointInt\/title"},{"op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointInt\/fragments"},{"value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointInt\/navigatorTitle","op":"replace"},{"value":"x","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointInt~1x\/title","op":"replace"},{"value":[{"kind":"identifier","text":"x"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PointInt~1x\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}