{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"text":"detection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"detection"}],"title":"detection","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiStateRunning(py)detection"},"kind":"symbol","sections":[],"abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","text":"DOTDDocumentAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/detection"},"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning"]]},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"DOTDDocumentAutoCaptureUiStateRunning","kind":"identifier"}],"title":"DOTDDocumentAutoCaptureUiStateRunning","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning","abstract":[{"text":"Running state.","type":"text"},{"type":"text","text":" "},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"title":"DocumentAutoCaptureDetection","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateRunning/detection":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"detection"}],"title":"detection","url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistaterunning\/detection","abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateRunning\/detection"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentAutoCaptureDetection","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle","op":"replace"}]}]}