{"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode\/!=(_:_:)"],"title":"Operators","generated":true}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"article","variants":[{"paths":["\/documentation\/dotfacecore\/capturemode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode/!=(_:_:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/capturemode\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode\/!=(_:_:)","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"url":"\/documentation\/dotfacecore\/capturemode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"kind":"symbol","type":"topic","abstract":[{"text":"Capture mode.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","title":"CaptureMode","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/navigatorTitle","value":[{"text":"DOTCaptureMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}