{"abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The process remains in a waiting state until the "},{"code":"requestCapture()","type":"codeVoice"},{"type":"text","text":" call is invoked, signaling the request of the capture event."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/capturemode\/waitforrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/capturemode\/waitforrequest"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}],"roleHeading":"Case","externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeWaitForRequest","title":"CaptureMode.waitForRequest","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode\/waitForRequest"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode/waitForRequest":{"abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}],"url":"\/documentation\/dotfacecore\/capturemode\/waitforrequest","title":"CaptureMode.waitForRequest","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode\/waitForRequest","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"abstract":[{"type":"text","text":"Capture mode."}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/capturemode","title":"CaptureMode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTCaptureModeWaitForRequest","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode~1waitForRequest\/title","value":"DOTCaptureModeWaitForRequest"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode~1waitForRequest\/fragments","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCaptureMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}