{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(magnifEyeLivenessLiteViewController:processed:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},{"text":", ","kind":"text"},{"text":"processed","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:processed:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:processed:"}],"title":"magnifEyeLivenessViewController(_:processed:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection"},{"kind":"text","text":")"}],"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessLiteViewController:processed:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:processed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:processed:)"]}],"sections":[],"abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 8.17.1","type":"text"}],"title":"DotFaceLite","role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"title":"MagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","type":"topic","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"role":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate":{"type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate","role":"symbol","abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"title":"MagnifEyeLivenessViewControllerDelegate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewController(_:processed:)":{"kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:processed:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:processed:)","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:processed:"}],"type":"topic","title":"magnifEyeLivenessViewController(_:processed:)"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","type":"topic","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"title":"FaceAutoCaptureDetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"magnifEyeLivenessLiteViewController:processed:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:processed:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"magnifEyeLivenessLiteViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"DOTFLMagnifEyeLivenessViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"processed:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFLMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFLMagnifEyeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:processed:)\/title","value":"magnifEyeLivenessLiteViewController:processed:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:processed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:processed:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]}]}]}