{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/localization\/uselocalizationdictionary"]},{"paths":["\/documentation\/dotpalmcore\/localization\/uselocalizationdictionary"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/useLocalizationDictionary"},"abstract":[{"text":"If you set this to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", "},{"code":"localizationDictionary","type":"codeVoice"},{"type":"text","text":" will be used to localize strings. Default value is "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"metadata":{"modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useLocalizationDictionary"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Type Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"title":"useLocalizationDictionary","externalID":"c:@M@DotPalmCore@objc(cs)DOTPLocalization(cpy)useLocalizationDictionary"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Localization":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Localization"}],"role":"symbol","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization","url":"\/documentation\/dotpalmcore\/localization","title":"Localization","type":"topic","kind":"symbol","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/Localization/useLocalizationDictionary":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"useLocalizationDictionary","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/useLocalizationDictionary","type":"topic","url":"\/documentation\/dotpalmcore\/localization\/uselocalizationdictionary","kind":"symbol","title":"useLocalizationDictionary","abstract":[{"text":"If you set this to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizationDictionary"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"useLocalizationDictionary","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"useLocalizationDictionary","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/title","value":"DOTPLocalization"},{"value":[{"text":"DOTPLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1useLocalizationDictionary\/title","value":"useLocalizationDictionary","op":"replace"},{"op":"replace","value":[{"text":"useLocalizationDictionary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1useLocalizationDictionary\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}