{"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"class","externalID":"c:@M@DotNfc@objc(cs)DotSdk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","role":"symbol","roleHeading":"Class"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk"]},{"paths":["\/documentation\/dotnfc\/dotsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk"},"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/bundleId","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isEvaluation","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isInitialized","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/licenseCustomer","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/versionName"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/deinitialize()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/initialize(configuration:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isLibraryActive(libraryId:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/shared"],"title":"Type Properties"}],"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/licenseCustomer":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseCustomer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/dotsdk\/licensecustomer","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/licenseCustomer","title":"licenseCustomer","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/isEvaluation":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEvaluation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotnfc\/dotsdk\/isevaluation","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isEvaluation","title":"isEvaluation","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/deinitialize()":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotsdk\/deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/deinitialize()","title":"deinitialize()","abstract":[{"type":"text","text":"Deinitialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/shared":{"url":"\/documentation\/dotnfc\/dotsdk\/shared","navigatorTitle":[{"kind":"identifier","text":"shared"}],"title":"shared","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdk","text":"DotSdk","kind":"typeIdentifier"}],"abstract":[{"text":"Shared singleton instance.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/shared"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/bundleId":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bundleId"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/bundleId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"bundleId","type":"topic","abstract":[{"type":"text","text":"Application Bundle ID."}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotsdk\/bundleid"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/versionName":{"abstract":[{"code":"DotSdk","type":"codeVoice"},{"text":" version.","type":"text"}],"url":"\/documentation\/dotnfc\/dotsdk\/versionname","navigatorTitle":[{"text":"versionName","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/versionName","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"versionName","type":"topic","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/isRealTimeTransactionReportingEnabled":{"type":"topic","url":"\/documentation\/dotnfc\/dotsdk\/isrealtimetransactionreportingenabled","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isRealTimeTransactionReportingEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"title":"isRealTimeTransactionReportingEnabled","role":"symbol"},"doc://com.innovatrics.dot.nfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk":{"url":"\/documentation\/dotnfc\/dotsdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/isFaceEyeGazeLivenessScoreEnabled":{"type":"topic","url":"\/documentation\/dotnfc\/dotsdk\/isfaceeyegazelivenessscoreenabled","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isFaceEyeGazeLivenessScoreEnabled","abstract":[],"title":"isFaceEyeGazeLivenessScoreEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/isLibraryActive(libraryId:)":{"title":"isLibraryActive(libraryId:)","navigatorTitle":[{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isLibraryActive","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","abstract":[{"text":"Check whether ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library is active."}],"url":"\/documentation\/dotnfc\/dotsdk\/islibraryactive(libraryid:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isLibraryActive(libraryId:)","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/isInitialized":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/dotnfc\/dotsdk\/isinitialized","abstract":[{"text":"Flag to determine if ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" is initialized."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isInitialized","navigatorTitle":[{"kind":"identifier","text":"isInitialized"}],"title":"isInitialized","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdk/initialize(configuration:)":{"url":"\/documentation\/dotnfc\/dotsdk\/initialize(configuration:)","title":"initialize(configuration:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/initialize(configuration:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DotSdkConfiguration"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","abstract":[{"type":"text","text":"Initialize "},{"code":"DotSdk","type":"codeVoice"},{"text":" with configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DotSdk","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/bundleId","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isInitialized","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/versionName"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/deinitialize()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/initialize(configuration:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/isLibraryActive(libraryId:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdk\/shared"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1deinitialize()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1shared\/title","value":"shared"},{"value":[{"kind":"identifier","text":"shared"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1shared\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1bundleId\/title","op":"replace","value":"bundleId"},{"value":[{"text":"bundleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1bundleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1versionName\/title","value":"versionName"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1versionName\/fragments","value":[{"kind":"identifier","text":"versionName"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk","op":"replace"},{"value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk\/fragments","op":"replace"},{"value":"isLibraryActiveWithLibraryId:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1isLibraryActive(libraryId:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1isLibraryActive(libraryId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1isInitialized\/title","value":"isInitialized"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1isInitialized\/fragments","op":"replace","value":[{"text":"isInitialized","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1initialize(configuration:)\/title","value":"initializeWithConfiguration:error:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdk~1initialize(configuration:)\/fragments","op":"replace"}]}]}