{"variants":[{"paths":["\/documentation\/dotnfc\/mrznameelement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/mrznameelement"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/primaryIdentifier","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/secondaryIdentifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/isEqual(_:)"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMrzNameElement) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNameElement"}]}]}],"metadata":{"roleHeading":"Class","role":"symbol","modules":[{"name":"DotNfc"}],"title":"MrzNameElement","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"externalID":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"references":{"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement/init(primaryIdentifier:secondaryIdentifier:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)","type":"topic","url":"\/documentation\/dotnfc\/mrznameelement\/init(primaryidentifier:secondaryidentifier:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"primaryIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"secondaryIdentifier"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"abstract":[],"title":"init(primaryIdentifier:secondaryIdentifier:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPrimaryIdentifier:secondaryIdentifier:"}]},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement/secondaryIdentifier":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/secondaryIdentifier","url":"\/documentation\/dotnfc\/mrznameelement\/secondaryidentifier","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"secondaryIdentifier"}],"role":"symbol","abstract":[{"text":"Secondary identifier usually represents given names.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secondaryIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"kind":"text","text":"?"}],"title":"secondaryIdentifier","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement/primaryIdentifier":{"navigatorTitle":[{"text":"primaryIdentifier","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/primaryIdentifier","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Primary identifier usually represents surname."}],"title":"primaryIdentifier","type":"topic","url":"\/documentation\/dotnfc\/mrznameelement\/primaryidentifier"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement/hash":{"title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/hash","url":"\/documentation\/dotnfc\/mrznameelement\/hash"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement/isEqual(_:)":{"kind":"symbol","url":"\/documentation\/dotnfc\/mrznameelement\/isequal(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/isEqual(_:)","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"url":"\/documentation\/dotnfc\/mrznameelement","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"title":"MrzNameElement","role":"symbol"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/mrznameelement\/description","title":"description","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTMrzNameElement","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/primaryIdentifier","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/secondaryIdentifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/init(primaryIdentifier:secondaryIdentifier:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/isEqual(_:)"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTMrzNameElement"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"initWithPrimaryIdentifier:secondaryIdentifier:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1init(primaryIdentifier:secondaryIdentifier:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1init(primaryIdentifier:secondaryIdentifier:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPrimaryIdentifier:secondaryIdentifier:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1secondaryIdentifier\/title","value":"secondaryIdentifier"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1secondaryIdentifier\/fragments","value":[{"kind":"identifier","text":"secondaryIdentifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1primaryIdentifier\/title","value":"primaryIdentifier"},{"value":[{"text":"primaryIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1primaryIdentifier\/fragments"},{"value":"hash","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1hash\/title","op":"replace"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1hash\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/fragments","op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}