{"abstract":[{"type":"text","text":"Bottom right corner point."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/corners\/bottomright"]},{"paths":["\/documentation\/dotfacelite\/corners\/bottomright"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomRight"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"title":"bottomRight","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTCorners(py)bottomRight","symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/bottomRight":{"title":"bottomRight","kind":"symbol","abstract":[{"text":"Bottom right corner point.","type":"text"}],"url":"\/documentation\/dotfacelite\/corners\/bottomright","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomRight","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/PointDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/pointdouble","title":"PointDouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"version: 8.3.0","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"role":"symbol","abstract":[{"type":"text","text":"Four detected corners in an image."}],"url":"\/documentation\/dotfacelite\/corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"title":"Corners"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"bottomRight","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"bottomRight","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/PointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bottomRight"}]}],"kind":"declarations"}},{"value":"bottomRight","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1bottomRight\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1bottomRight\/fragments","op":"replace","value":[{"text":"bottomRight","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1PointDouble\/fragments","op":"replace"},{"value":"DOTCorners","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/title","op":"replace"},{"value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}