{"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Top left corner point."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"}],"externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)topLeft","title":"topLeft","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topLeft"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/corners\/topleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/corners\/topleft"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/topLeft"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/Corners/topLeft":{"url":"\/documentation\/dotfacelite\/corners\/topleft","abstract":[{"type":"text","text":"Top left corner point."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/topLeft","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}],"kind":"symbol","title":"topLeft","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topLeft"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Corners":{"title":"Corners","type":"topic","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/corners","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble":{"title":"PointDouble","type":"topic","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/pointdouble","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"topLeft","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topLeft"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1topLeft\/title","value":"topLeft","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"topLeft"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1topLeft\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/title","value":"DOTCorners","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}