{"abstract":[{"text":"Face keypoints.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/keypoints","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)Face(py)keypoints","title":"keypoints","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"keypoints","kind":"identifier"}],"fragments":[{"text":"keypoints","kind":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"DOTFFaceKeypoints","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"},{"text":" * ","kind":"text"},{"text":"keypoints","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/face\/keypoints"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Face/keypoints":{"url":"\/documentation\/dotfacecore\/face\/keypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/keypoints","role":"symbol","fragments":[{"text":"keypoints","kind":"identifier"}],"type":"topic","abstract":[{"text":"Face keypoints.","type":"text"}],"title":"keypoints","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","fragments":[{"text":"Face","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/face","abstract":[{"text":"Detected face in the image.","type":"text"}],"title":"Face","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","role":"symbol","type":"topic","title":"FaceKeypoints","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}