{"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFFaceAutoCaptureQualityAttributeThresholds) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/brightnessInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/contrastInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxDevicePitchAngle","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxGlassesPresenceScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxMaskPresenceScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxShadow","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minBackgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minConfidence","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEdgeDistanceToImageShorterSideRatioThreshold","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesDetectionScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesStatusScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minMouthDetectionScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minMouthStatusScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minSharpness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minUniqueIntensityLevels","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/pitchAngleInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/sizeInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/yawAngleInterval"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","symbolKind":"class","roleHeading":"Class","title":"FaceAutoCaptureQualityAttributeThresholds"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds"]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minSharpness":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minSharpness","navigatorTitle":[{"kind":"identifier","text":"minSharpness"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSharpness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Minimal valid sharpness of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents blurry face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents sharp face.","type":"text"}],"title":"minSharpness","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minsharpness","kind":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minEyesStatusScore":{"kind":"symbol","role":"symbol","abstract":[{"text":"Minimal valid eyes status score of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents face with eyes closed.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents face with eyes opened.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesstatusscore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"type":"topic","title":"minEyesStatusScore","navigatorTitle":[{"kind":"identifier","text":"minEyesStatusScore"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesStatusScore"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/maxShadow":{"kind":"symbol","role":"symbol","abstract":[{"text":"Maximal valid shadow of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents face without shadows.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents face with shadows.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/maxshadow","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxShadow"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"type":"topic","title":"maxShadow","navigatorTitle":[{"kind":"identifier","text":"maxShadow"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxShadow"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minUniqueIntensityLevels":{"kind":"symbol","role":"symbol","abstract":[{"text":"Minimal valid unique intensity levels of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low unique intensity levels.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high unique intensity levels.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minuniqueintensitylevels","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minUniqueIntensityLevels"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"type":"topic","title":"minUniqueIntensityLevels","navigatorTitle":[{"kind":"identifier","text":"minUniqueIntensityLevels"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minUniqueIntensityLevels"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minBackgroundUniformity":{"kind":"symbol","role":"symbol","abstract":[{"text":"Minimal valid level of the background uniformity of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low background uniformity.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high background uniformity.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minbackgrounduniformity","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minBackgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"type":"topic","title":"minBackgroundUniformity","navigatorTitle":[{"kind":"identifier","text":"minBackgroundUniformity"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minBackgroundUniformity"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","abstract":[],"title":"description","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/description","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minEyesDetectionScore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesDetectionScore","navigatorTitle":[{"kind":"identifier","text":"minEyesDetectionScore"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesDetectionScore"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Minimal valid eyes detection score of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low eyes detection score.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high eyes detection score.","type":"text"}],"title":"minEyesDetectionScore","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesdetectionscore","kind":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Builder":{"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder","abstract":[],"title":"FaceAutoCaptureQualityAttributeThresholds.Builder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Builder","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minEdgeDistanceToImageShorterSideRatioThreshold":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEdgeDistanceToImageShorterSideRatioThreshold","navigatorTitle":[{"kind":"identifier","text":"minEdgeDistanceToImageShorterSideRatioThreshold"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEdgeDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Minimum ratio of the edge distance to image shorter side threshold.","type":"text"},{"text":" ","type":"text"},{"text":"Valid closed interval of ratio values is from 0.0 to 1.0","type":"text"}],"title":"minEdgeDistanceToImageShorterSideRatioThreshold","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minedgedistancetoimageshortersideratiothreshold","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minMouthStatusScore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minMouthStatusScore","navigatorTitle":[{"kind":"identifier","text":"minMouthStatusScore"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minMouthStatusScore","kind":"identifier"},{"kind":"text","text":": "},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Minimal valid mouth status score of the detected face.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with mouth opened."},{"type":"text","text":" "},{"text":"Value 1.0 represents face with mouth closed.","type":"text"}],"title":"minMouthStatusScore","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minmouthstatusscore","kind":"symbol"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/hash":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/hash","title":"hash","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minMouthDetectionScore":{"navigatorTitle":[{"kind":"identifier","text":"minMouthDetectionScore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minMouthDetectionScore"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minMouthDetectionScore","kind":"symbol","abstract":[{"type":"text","text":"Minimal valid mouth detection score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low mouth detection score."},{"text":" ","type":"text"},{"type":"text","text":"Value 1.0 represents high mouth detection score."}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minmouthdetectionscore","title":"minMouthDetectionScore","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","title":"FaceAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/isEqual(_:)":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/isEqual(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/maxDevicePitchAngle":{"navigatorTitle":[{"kind":"identifier","text":"maxDevicePitchAngle"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxDevicePitchAngle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","kind":"typeIdentifier","text":"WrappedFloat"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxDevicePitchAngle","kind":"symbol","abstract":[{"type":"text","text":"Maximal pitch angle of the device."},{"type":"text","text":" "},{"type":"text","text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees."}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/maxdevicepitchangle","title":"maxDevicePitchAngle","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/brightnessInterval":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Valid interval of brightness of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low brightness."},{"type":"text","text":" "},{"text":"Value 1.0 represents high brightness.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/brightnessinterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"brightnessInterval","navigatorTitle":[{"kind":"identifier","text":"brightnessInterval"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/brightnessInterval"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/pitchAngleInterval":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/pitchAngleInterval","navigatorTitle":[{"kind":"identifier","text":"pitchAngleInterval"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pitchAngleInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat","text":"IntervalFloat","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Valid interval of rotation of the pitch of the detected face.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Value -90.0 represents down rotated pitch of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 90.0 represents up rotated pitch of the detected face."}],"title":"pitchAngleInterval","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/pitchangleinterval","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/maxGlassesPresenceScore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxGlassesPresenceScore","navigatorTitle":[{"kind":"identifier","text":"maxGlassesPresenceScore"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxGlassesPresenceScore"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"Maximal valid glasses presence score of the detected face."},{"text":" ","type":"text"},{"text":"Value 0.0 represents face with no glasses.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents face with glasses."}],"title":"maxGlassesPresenceScore","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/maxglassespresencescore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/contrastInterval":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/contrastInterval","navigatorTitle":[{"kind":"identifier","text":"contrastInterval"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contrastInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Valid interval of contrast of the detected face.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Value 0.0 represents low contrast."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents high contrast."}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/contrastinterval","title":"contrastInterval","kind":"symbol"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/maxMaskPresenceScore":{"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/maxmaskpresencescore","abstract":[{"type":"text","text":"Maximal valid mask presence score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with no mask."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents face with mask."}],"title":"maxMaskPresenceScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMaskPresenceScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxMaskPresenceScore","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxMaskPresenceScore"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/yawAngleInterval":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/yawAngleInterval","navigatorTitle":[{"kind":"identifier","text":"yawAngleInterval"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"yawAngleInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"Valid interval of rotation of the yaw of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value -90.0 represents left rotated yaw of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 90.0 represents right rotated yaw of the detected face."}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/yawangleinterval","title":"yawAngleInterval","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minConfidence":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minConfidence","navigatorTitle":[{"kind":"identifier","text":"minConfidence"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidence"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"type":"text","text":"Minimal valid confidence of the detected face."},{"type":"text","text":" "},{"text":"Value 0.0 represents low confidence.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high confidence.","type":"text"}],"title":"minConfidence","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minconfidence","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/sizeInterval":{"navigatorTitle":[{"kind":"identifier","text":"sizeInterval"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/sizeInterval","kind":"symbol","abstract":[{"type":"text","text":"Valid interval of size of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents small size."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents large size."}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/sizeinterval","title":"sizeInterval","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Presets":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Presets","navigatorTitle":[{"kind":"identifier","text":"Presets"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presets"}],"role":"symbol","abstract":[{"text":"Presets for the quality attributes thresholds of the face auto capture result.","type":"text"}],"title":"FaceAutoCaptureQualityAttributeThresholds.Presets","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/presets","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFFaceAutoCaptureQualityAttributeThresholds","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}]},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/brightnessInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/contrastInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxDevicePitchAngle","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxGlassesPresenceScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxMaskPresenceScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/maxShadow","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minBackgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minConfidence","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEdgeDistanceToImageShorterSideRatioThreshold","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesDetectionScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesStatusScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minMouthDetectionScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minMouthStatusScore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minSharpness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minUniqueIntensityLevels","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/pitchAngleInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/sizeInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/yawAngleInterval"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/isEqual(_:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"minSharpness","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minSharpness\/title"},{"value":[{"text":"minSharpness","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minSharpness\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesStatusScore\/title","value":"minEyesStatusScore"},{"value":[{"kind":"identifier","text":"minEyesStatusScore"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesStatusScore\/fragments"},{"value":"maxShadow","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxShadow\/title"},{"value":[{"kind":"identifier","text":"maxShadow"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxShadow\/fragments"},{"value":"minUniqueIntensityLevels","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minUniqueIntensityLevels\/title"},{"value":[{"kind":"identifier","text":"minUniqueIntensityLevels"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minUniqueIntensityLevels\/fragments"},{"value":"minBackgroundUniformity","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minBackgroundUniformity\/title"},{"value":[{"text":"minBackgroundUniformity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minBackgroundUniformity\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1description\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesDetectionScore\/title","value":"minEyesDetectionScore","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesDetectionScore\/fragments","value":[{"kind":"identifier","text":"minEyesDetectionScore"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEdgeDistanceToImageShorterSideRatioThreshold\/title","value":"minEdgeDistanceToImageShorterSideRatioThreshold","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEdgeDistanceToImageShorterSideRatioThreshold\/fragments","value":[{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minMouthStatusScore\/title","value":"minMouthStatusScore","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minMouthStatusScore\/fragments","value":[{"kind":"identifier","text":"minMouthStatusScore"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minMouthDetectionScore\/title","value":"minMouthDetectionScore","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minMouthDetectionScore\/fragments","value":[{"text":"minMouthDetectionScore","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFFaceAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxDevicePitchAngle\/title","value":"maxDevicePitchAngle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxDevicePitchAngle\/fragments","value":[{"text":"maxDevicePitchAngle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1brightnessInterval\/title","value":"brightnessInterval"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1brightnessInterval\/fragments","value":[{"kind":"identifier","text":"brightnessInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1pitchAngleInterval\/title","value":"pitchAngleInterval"},{"value":[{"text":"pitchAngleInterval","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1pitchAngleInterval\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxGlassesPresenceScore\/title","value":"maxGlassesPresenceScore"},{"value":[{"kind":"identifier","text":"maxGlassesPresenceScore"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxGlassesPresenceScore\/fragments"},{"value":"contrastInterval","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1contrastInterval\/title"},{"value":[{"kind":"identifier","text":"contrastInterval"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1contrastInterval\/fragments"},{"value":"maxMaskPresenceScore","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxMaskPresenceScore\/title"},{"value":[{"kind":"identifier","text":"maxMaskPresenceScore"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1maxMaskPresenceScore\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1yawAngleInterval\/title","value":"yawAngleInterval"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1yawAngleInterval\/fragments","value":[{"kind":"identifier","text":"yawAngleInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minConfidence\/title","value":"minConfidence"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minConfidence\/fragments","value":[{"kind":"identifier","text":"minConfidence"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1sizeInterval\/title","value":"sizeInterval","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1sizeInterval\/fragments","value":[{"kind":"identifier","text":"sizeInterval"}]}]}]}