{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Initializing","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running"],"title":"Classes","generated":true,"anchor":"Classes"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"kind":"symbol","metadata":{"title":"FaceAutoCaptureUiState","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiState","symbolKind":"class","roleHeading":"Class","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Initializing","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFFaceAutoCaptureUiState) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Idle":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Idle"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Idle"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle","title":"FaceAutoCaptureUiState.Idle","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/idle","abstract":[{"text":"Idle state.","type":"text"}]},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateInitializing":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateInitializing","type":"topic","fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiStateInitializing"}],"role":"symbol","abstract":[{"type":"text","text":"Initializing state."},{"type":"text","text":" "},{"type":"text","text":"This state is active right after the component is created for a short period of time."}],"title":"DOTFFaceAutoCaptureUiStateInitializing","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateinitializing","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning":{"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"title":"DOTFFaceAutoCaptureUiStateRunning","fragments":[{"text":"DOTFFaceAutoCaptureUiStateRunning","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiState/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistate\/init","title":"init","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiState\/init"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running":{"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running","abstract":[{"text":"Running state.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"navigatorTitle":[{"text":"Running","kind":"identifier"}],"title":"FaceAutoCaptureUiState.Running"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Initializing":{"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/initializing","abstract":[{"text":"Initializing state.","type":"text"}],"title":"FaceAutoCaptureUiState.Initializing","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Initializing","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Initializing"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"role":"symbol","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"title":"FaceAutoCaptureUiState","url":"\/documentation\/dotfacecore\/faceautocaptureuistate","kind":"symbol"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateIdle":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle","type":"topic","fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiStateIdle"}],"role":"symbol","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"title":"DOTFFaceAutoCaptureUiStateIdle","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle","kind":"symbol"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFFaceAutoCaptureUiState","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiState\/init"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateInitializing","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning"],"type":"inheritedBy"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFFaceAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}