{"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"UI Smile Liveness component."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFSmileLivenessViewController) "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SmileLivenessViewController","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"type":"text","text":"A visual component which performs a liveness check based on the changes in the face expression."}],"type":"paragraph"},{"inlineContent":[{"type":"text","text":"This component requires the "},{"type":"codeVoice","code":"DotFaceExpressionNeutral"},{"text":" module to be active.","type":"text"}],"type":"paragraph"}]}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"],"title":"Style and configuration","anchor":"Style-and-configuration"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"],"title":"Delegate","anchor":"Delegate"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"title":"Smile liveness result","anchor":"Smile-liveness-result"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/init(configuration:style:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/style-swift.property"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/stop()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"symbolKind":"class","title":"SmileLivenessViewController","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","roleHeading":"Class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSCoding","doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer","doc:\/\/DotFaceCore\/objc(pl)UIContentContainer","doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring","doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"anchor":"UI-components","title":"UI components","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"]}],"kind":"symbol","references":{"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewDidLoad()":{"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidLoad()","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewdidload()","title":"viewDidLoad()","role":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/init(configuration:style:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/init(configuration:style:)","role":"symbol","abstract":[{"type":"text","text":"Create new "},{"code":"SmileLivenessViewController","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/init(configuration:style:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"Style","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"init(configuration:style:)","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"title":"MagnifEyeLivenessViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/configuration-swift.property":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/configuration-swift.property","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Current configuration."}],"title":"configuration","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.property","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/delegate":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/delegate","role":"symbol","abstract":[{"type":"text","text":"Set this delegate to handle the smile liveness events."}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/delegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFSmileLivenessViewControllerDelegate","text":"SmileLivenessViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class","navigatorTitle":[{"kind":"identifier","text":"Style"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"role":"symbol","abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"title":"SmileLivenessViewController.Style","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewDidLayoutSubviews()":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewdidlayoutsubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"type":"topic","title":"viewDidLayoutSubviews()","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidLayoutSubviews()"},"doc://DotFaceCore/objc(cs)UIViewController":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"title":"FaceAutoCaptureDetection","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacecore\/faceautocapturedetection"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewDidDisappear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidDisappear(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewdiddisappear(_:)","title":"viewDidDisappear(_:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewWillDisappear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillDisappear(_:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwilldisappear(_:)","title":"viewWillDisappear(_:)","abstract":[]},"doc://DotFaceCore/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://DotFaceCore/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://DotFaceCore/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://DotFaceCore/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","kind":"symbol","abstract":[{"type":"text","text":"The position of the detected face in the image."}],"url":"\/documentation\/dotfacecore\/detectionposition","title":"DetectionPosition","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the UI Smile Liveness component."}],"title":"SmileLivenessViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewWillAppear(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillAppear(_:)","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwillappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","title":"viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"role":"symbol","abstract":[{"type":"text","text":"UI Smile Liveness component."}],"title":"SmileLivenessViewController","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewWillTransition(to:with:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillTransition(to:with:)","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwilltransition(to:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"type":"topic","title":"viewWillTransition(to:with:)","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/start()":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/start()","abstract":[{"text":"Start the smile liveness process.","type":"text"}],"title":"start()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/start()","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"start","kind":"identifier"}]},"doc://DotFaceCore/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://DotFaceCore/objc(pl)UIContentContainer":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"kind":"symbol","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"UI Eye Gaze Liveness component."}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"type":"topic","title":"EyeGazeLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},"doc://DotFaceCore/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"role":"symbol","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"title":"MultiRangeLivenessViewController","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to the handle smile liveness events."}],"title":"SmileLivenessViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/stop()":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/stop()","abstract":[{"text":"Stop the smile liveness process.","type":"text"}],"title":"stop()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/stop()","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stop"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessResult"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessResult"}],"role":"symbol","abstract":[{"text":"The result of smile liveness process.","type":"text"}],"title":"SmileLivenessResult","url":"\/documentation\/dotfacecore\/smilelivenessresult","kind":"symbol"},"doc://DotFaceCore/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/style-swift.property":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.property","abstract":[{"type":"text","text":"Current style."}],"title":"style","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/style-swift.property","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"style"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewDidAppear(_:)":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewdidappear(_:)","abstract":[],"title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidAppear(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","role":"symbol"},"doc://DotFaceCore/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/objc(pl)NSCoding":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://DotFaceCore/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTFSmileLivenessViewController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"],"anchor":"Delegate","title":"Delegate"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"anchor":"Smile-liveness-result","title":"Smile liveness result"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/style-swift.property"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/init(configuration:style:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/stop()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillTransition(to:with:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"],"anchor":"UI-components","generated":true,"title":"UI components"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFSmileLivenessViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1init(configuration:style:)\/title","value":"initWithConfiguration:style:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1init(configuration:style:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1configuration-swift.property\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidLayoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","value":"DOTDetectionPosition","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1start()\/title","value":"start","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1start()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","value":"DOTFMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/title","value":"DOTFSmileLivenessViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1stop()\/title","value":"stop","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1stop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/title","value":"DOTFSmileLivenessResult","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFSmileLivenessResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1style-swift.property\/title","value":"style","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1style-swift.property\/fragments","value":[{"kind":"identifier","text":"style"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace"}]}]}