{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerViewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"text":"SmileLivenessViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidlayoutsubviews(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidlayoutsubviews(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFSmileLivenessViewControllerDelegate(im)smileLivenessViewControllerViewDidLayoutSubviews:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileLivenessViewControllerViewDidLayoutSubviews"},{"kind":"text","text":"("},{"text":"SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"smileLivenessViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"smileLivenessViewControllerViewDidLayoutSubviews(_:)"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLayoutSubviews(_:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","title":"SmileLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"UI Smile Liveness component.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to the handle smile liveness events."}],"title":"SmileLivenessViewControllerDelegate","navigatorTitle":[{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewDidLayoutSubviews(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLayoutSubviews(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileLivenessViewControllerViewDidLayoutSubviews"},{"kind":"text","text":"("},{"text":"SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidlayoutsubviews(_:)","abstract":[],"title":"smileLivenessViewControllerViewDidLayoutSubviews(_:)","navigatorTitle":[{"kind":"identifier","text":"smileLivenessViewControllerViewDidLayoutSubviews:"}],"role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"smileLivenessViewControllerViewDidLayoutSubviews:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"smileLivenessViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"smileLivenessViewControllerViewDidLayoutSubviews:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"DOTFSmileLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/title","value":"DOTFSmileLivenessViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidLayoutSubviews(_:)\/title","value":"smileLivenessViewControllerViewDidLayoutSubviews:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"smileLivenessViewControllerViewDidLayoutSubviews:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}