{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Unique intensity levels evaluation flag.","type":"text"}],"metadata":{"symbolKind":"property","title":"evaluateUniqueIntensityLevels","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery(py)evaluateUniqueIntensityLevels","roleHeading":"Instance Property","navigatorTitle":[{"text":"evaluateUniqueIntensityLevels","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateUniqueIntensityLevels"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateuniqueintensitylevels"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateuniqueintensitylevels"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"evaluateUniqueIntensityLevels","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateUniqueIntensityLevels"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateUniqueIntensityLevels":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateUniqueIntensityLevels"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","title":"evaluateUniqueIntensityLevels","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateuniqueintensitylevels","abstract":[{"type":"text","text":"Unique intensity levels evaluation flag."}],"navigatorTitle":[{"text":"evaluateUniqueIntensityLevels","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateUniqueIntensityLevels","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","title":"FaceImageQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"evaluateUniqueIntensityLevels","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"evaluateUniqueIntensityLevels","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateUniqueIntensityLevels"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"evaluateUniqueIntensityLevels","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateUniqueIntensityLevels\/title"},{"value":[{"text":"evaluateUniqueIntensityLevels","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateUniqueIntensityLevels\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","op":"replace","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}]}]}]}