{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBrightness","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Brightness evaluation flag."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateBrightness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebrightness"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebrightness"]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateBrightness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","title":"evaluateBrightness","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery(py)evaluateBrightness","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"evaluateBrightness"}],"role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"title":"FaceImageQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateBrightness":{"url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebrightness","type":"topic","title":"evaluateBrightness","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateBrightness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"evaluateBrightness","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Brightness evaluation flag.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBrightness"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"evaluateBrightness","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"evaluateBrightness","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"evaluateBrightness","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","op":"replace"},{"value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/navigatorTitle","op":"replace"},{"value":"evaluateBrightness","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBrightness\/title","op":"replace"},{"value":[{"text":"evaluateBrightness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBrightness\/fragments","op":"replace"}]}]}