{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)","interfaceLanguage":"swift"},"metadata":{"title":"init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery(im)initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:","kind":"identifier"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"evaluateSharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"evaluateBrightness","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateContrast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"evaluateUniqueIntensityLevels","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"evaluateShadow","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"evaluateSpecularity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluateBackgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol"},"variants":[{"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/init(evaluatesharpness:evaluatebrightness:evaluatecontrast:evaluateuniqueintensitylevels:evaluateshadow:evaluatespecularity:evaluatebackgrounduniformity:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/init(evaluatesharpness:evaluatebrightness:evaluatecontrast:evaluateuniqueintensitylevels:evaluateshadow:evaluatespecularity:evaluatebackgrounduniformity:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"evaluateSharpness"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"evaluateBrightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false, "},{"text":"evaluateContrast","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"evaluateUniqueIntensityLevels","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"evaluateShadow","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"evaluateSpecularity"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"text":"evaluateBackgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false)"}]}]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","role":"symbol","title":"FaceImageQualityQuery","abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)":{"abstract":[],"kind":"symbol","title":"init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)","type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/init(evaluatesharpness:evaluatebrightness:evaluatecontrast:evaluateuniqueintensitylevels:evaluateshadow:evaluatespecularity:evaluatebackgrounduniformity:)","navigatorTitle":[{"kind":"identifier","text":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"evaluateSharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"evaluateBrightness","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"evaluateContrast"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateUniqueIntensityLevels"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluateShadow","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateSpecularity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"evaluateBackgroundUniformity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithEvaluateSharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"evaluateSharpness","kind":"internalParam"},{"kind":"text","text":" "},{"text":"evaluateBrightness:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"evaluateBrightness","kind":"internalParam"},{"kind":"text","text":" "},{"text":"evaluateContrast:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"evaluateContrast"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateUniqueIntensityLevels:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"evaluateUniqueIntensityLevels","kind":"internalParam"},{"kind":"text","text":" "},{"text":"evaluateShadow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"evaluateShadow","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateSpecularity:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"evaluateSpecularity"},{"text":" ","kind":"text"},{"text":"evaluateBackgroundUniformity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"evaluateBackgroundUniformity","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]},{"value":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}