{"variants":[{"paths":["\/documentation\/dotdocument\/imagesize\/shorterside"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagesize\/shorterside"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/shorterSide"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shorterSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shorterSide","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTImageSize(py)shorterSide","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}],"title":"shorterSide","extendedModule":"DotCore"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"]]},"references":{"doc://DotDocument/documentation/DotDocument/ImageSize":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/imagesize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","title":"ImageSize","abstract":[{"text":"Image size in pixels.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.14.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/ImageSize/shorterSide":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/shorterSide","navigatorTitle":[{"text":"shorterSide","kind":"identifier"}],"title":"shorterSide","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shorterSide","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/imagesize\/shorterside"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"shorterSide"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"shorterSide","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shorterSide"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1shorterSide\/title","value":"shorterSide"},{"op":"replace","value":[{"text":"shorterSide","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1shorterSide\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}