{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangleint\/from(cgrect:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangleint\/from(cgrect:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt"]]},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"roleHeading":"Type Method","extendedModule":"DotCore","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"title":"from(cgRect:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"cgRect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","kind":"typeIdentifier","text":"RectangleInt"}],"role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(cm)fromCgRect:","symbolKind":"method"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/from(cgRect:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/from(cgRect:)":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/rectangleint\/from(cgrect:)","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/from(cgRect:)","title":"from(cgRect:)"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt":{"title":"RectangleInt","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"url":"\/documentation\/dotfacecore\/rectangleint","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleInt","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"fromCgRect:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"fromCgRect:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTRectangleInt","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"fromCgRect:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") ","kind":"text"},{"text":"cgRect","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1from(cgRect:)\/title","value":"fromCgRect:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"fromCgRect:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1from(cgRect:)\/fragments"},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/title"},{"op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/fragments"}]}]}