{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory\/create(bgraRawImage:)"},"metadata":{"roleHeading":"Type Method","title":"create(bgraRawImage:)","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/ciimagefactory\/create(bgrarawimage:)"]},{"paths":["\/documentation\/dotdocument\/ciimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.14.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/CIImageFactory":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/ciimagefactory","abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CIImageFactory","kind":"identifier"}],"title":"CIImageFactory","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/CIImageFactory/create(bgraRawImage:)":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CIImageFactory\/create(bgraRawImage:)","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/ciimagefactory\/create(bgrarawimage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"title":"create(bgraRawImage:)","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"url":"\/documentation\/dotdocument\/bgrarawimage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","title":"BgraRawImage","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"createWithBgraRawImage:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:"},{"text":"(","kind":"text"},{"text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgraRawImage"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory\/fragments","op":"replace","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory~1create(bgraRawImage:)\/title","op":"replace","value":"createWithBgraRawImage:"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CIImageFactory~1create(bgraRawImage:)\/fragments"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]}]}]}