{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/description"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/eyesexpression\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyesexpression\/description"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression(py)description","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpression"}],"url":"\/documentation\/dotfacecore\/eyesexpression","title":"EyesExpression","kind":"symbol","navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression/description":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/description","type":"topic","url":"\/documentation\/dotfacecore\/eyesexpression\/description","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTFEyesExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace"},{"value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1description\/fragments","value":[{"text":"description","kind":"identifier"}]}]}]}