{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" license."}]}],"name":"license"}]}],"sections":[],"abstract":[{"text":"Initialize library with license.","type":"text"}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary(im)initializeWithLicense:error:","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"title":"initialize(license:)","roleHeading":"Instance Method"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/initialize(license:)","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary":{"abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"role":"symbol","title":"DotFaceLibrary","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibrary"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","url":"\/documentation\/dotfacecore\/dotfacelibrary","navigatorTitle":[{"text":"DotFaceLibrary","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","title":"DotSdkLicenseProxyProtocol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/initialize(license:)":{"navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrary\/initialize(license:)","kind":"symbol","abstract":[{"type":"text","text":"Initialize library with license."}],"title":"initialize(license:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier","text":"DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/initialize(license:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initializeWithLicense:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithLicense:error:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@DotFaceCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier","text":"id<DotSdkLicenseProxyProtocol>"},{"text":" *) ","kind":"text"},{"text":"license","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","value":[{"text":"DotFaceLibrary","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments","op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"value":"initializeWithLicense:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1initialize(license:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1initialize(license:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeWithLicense:error:","kind":"identifier"}]}]}]}