{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"title":"mirrored()","externalID":"c:@CM@DotCore@objc(cs)DOTPointDouble(im)mirrored","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"mirrored"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/mirrored()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"text":"() -> ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointdouble\/mirrored()"]},{"paths":["\/documentation\/dotnfc\/pointdouble\/mirrored()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","type":"topic","abstract":[{"text":"version: 8.6.1","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/PointDouble/mirrored()":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/mirrored()","title":"mirrored()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"url":"\/documentation\/dotnfc\/pointdouble\/mirrored()","navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/PointDouble":{"type":"topic","url":"\/documentation\/dotnfc\/pointdouble","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","title":"PointDouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mirrored"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"mirrored","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"DOTPointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"},{"text":" *) ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"mirrored","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1mirrored()\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1mirrored()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}