{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"y"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"type":"text","text":"Y coordinate."}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/y","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointdouble\/y"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/pointdouble\/y"]}],"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"y"}],"externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(py)y","roleHeading":"Instance Property","symbolKind":"property","title":"y"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/PointDouble/y":{"url":"\/documentation\/dotnfc\/pointdouble\/y","type":"topic","navigatorTitle":[{"text":"y","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Y coordinate.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/y","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"y","role":"symbol"},"doc://DotNfc/documentation/DotNfc/PointDouble":{"title":"PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","url":"\/documentation\/dotnfc\/pointdouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"y","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"y","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"text":"y","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"y","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1y\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"y"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1y\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}