{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/versionname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/versionname"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/versionName","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Version of the "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" framework."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"versionName","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DotDocumentLibrary(cpy)versionName","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"versionName"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/versionName":{"role":"symbol","title":"versionName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Version of the "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/versionName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"versionName"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary\/versionname"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary":{"role":"symbol","title":"DotDocumentLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibrary"}],"abstract":[{"type":"text","text":"Class storing the global properties of the "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibrary"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"versionName"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"versionName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"versionName"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1versionName\/title","value":"versionName"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1versionName\/fragments","value":[{"kind":"identifier","text":"versionName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/title","value":"DotDocumentLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibrary"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}