{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Current configuration.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/baseConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController(py)baseConfiguration","role":"symbol","title":"baseConfiguration","roleHeading":"Instance Property","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/baseconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/baseconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","title":"BaseDocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"title":"BaseDocumentAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"title":"DOTDBaseDocumentAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureConfiguration"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/baseConfiguration":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"abstract":[{"text":"Current configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/baseconfiguration","title":"baseConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/baseConfiguration","role":"symbol","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"baseConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"baseConfiguration"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration","text":"DOTDBaseDocumentAutoCaptureConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDBaseDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1baseConfiguration\/title","op":"replace","value":"baseConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1baseConfiguration\/fragments","op":"replace","value":[{"text":"baseConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}