{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"role":"symbol","title":"viewDidLoad()","externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController(im)viewDidLoad","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLoad()"},"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","title":"BaseDocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewDidLoad()":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidLoad()","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidload()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"title":"viewDidLoad()","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","value":"DOTDBaseDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}