{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:7DotCore0A3SdkC5ErrorO20initializationFailedyAEsAD_p_tcAEmF","modules":[{"name":"DotNfc"}],"title":"DotSdk.Error.initializationFailed(internalError:)","roleHeading":"Case","symbolKind":"case","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error\/initializationFailed(internalError:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/error\/initializationfailed(internalerror:)"]}],"sections":[],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DotSdk/Error/initializationFailed(internalError:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error\/initializationFailed(internalError:)","title":"DotSdk.Error.initializationFailed(internalError:)","url":"\/documentation\/dotnfc\/dotsdk\/error\/initializationfailed(internalerror:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}]},"doc://DotNfc/documentation/DotNfc/DotSdk":{"kind":"symbol","type":"topic","title":"DotSdk","url":"\/documentation\/dotnfc\/dotsdk","role":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk"},"doc://DotNfc/documentation/DotNfc/DotSdk/Error":{"url":"\/documentation\/dotnfc\/dotsdk\/error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error","abstract":[],"title":"DotSdk.Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"}]}]}