{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/authenticationstatus\/chip"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/authenticationstatus\/chip"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chip"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","text":"ChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus(py)chip","platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.0"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus"}],"role":"symbol","title":"chip","navigatorTitle":[{"kind":"identifier","text":"chip"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Chip authentication status (using either PACE - Chip Authentication Mapping, Chip Authentication or Active Authentication protocol).","type":"text"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/chip","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","type":"topic","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.6.1"}]},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"url":"\/documentation\/dotnfc\/authenticationstatus","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationStatus","kind":"identifier"}],"navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}],"type":"topic","title":"AuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of data and chip."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/chip":{"type":"topic","title":"chip","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chip"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","kind":"typeIdentifier","text":"ChipAuthenticationStatus"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"chip"}],"url":"\/documentation\/dotnfc\/authenticationstatus\/chip","abstract":[{"type":"text","text":"Chip authentication status (using either PACE - Chip Authentication Mapping, Chip Authentication or Active Authentication protocol)."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/chip","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"url":"\/documentation\/dotnfc\/chipauthenticationstatus","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","kind":"symbol","navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"title":"ChipAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"chip"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"chip","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","text":"DOTNChipAuthenticationStatus","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"chip"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTNAuthenticationStatus","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}]},{"value":"chip","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1chip\/title"},{"value":[{"text":"chip","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1chip\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}