{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.internalError"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Error"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"role":"symbol","title":"internalError","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC5ErrorO08internalG0sAD_pSgvp","symbolKind":"property","modules":[{"name":"DotPalmCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Error\/internalError"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/error\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Error":{"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Error","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"PalmAutoCaptureController.Error"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Error/internalError":{"title":"internalError","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Error\/internalError","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/error\/internalerror","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"type":"topic","title":"PalmAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]}]}]}