{"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"max","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble(py)max","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"max"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble\/max","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/intervaldouble\/max"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/intervaldouble\/max"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Maximal interval value."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol","title":"IntervalDouble"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble/max":{"url":"\/documentation\/dotfacecore\/intervaldouble\/max","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"max","navigatorTitle":[{"kind":"identifier","text":"max"}],"abstract":[{"type":"text","text":"Maximal interval value."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble\/max","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"max","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"max"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle"},{"op":"replace","value":"max","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble~1max\/title"},{"op":"replace","value":[{"kind":"identifier","text":"max"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble~1max\/fragments"}]}]}