{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"init(modules:faceDetectionConfidenceThreshold:)","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(im)initWithModules:faceDetectionConfidenceThreshold:error:","navigatorTitle":[{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"modules"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":" = 0.06) ","kind":"text"},{"text":"throws","kind":"keyword"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","role":"symbol","title":"init(modules:faceDetectionConfidenceThreshold:)","abstract":[],"navigatorTitle":[{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","title":"DotFaceLibraryConfiguration.Modules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithModules:faceDetectionConfidenceThreshold:error:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"initWithModules:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","text":"DotFaceLibraryConfigurationModules","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules"},{"kind":"text","text":" *) "},{"text":"modules","kind":"internalParam"},{"kind":"text","text":" "},{"text":"faceDetectionConfidenceThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title","value":"initWithModules:faceDetectionConfidenceThreshold:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}]}]}