{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/info","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel\/info"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel\/info"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelInfo","title":"LoggerLogLevel.info","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info"}],"role":"symbol","symbolKind":"case","roleHeading":"Case"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel"]]},"abstract":[{"text":"Logs informative events.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/loggerloglevel","abstract":[{"type":"text","text":"Available log levels."}],"title":"LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/info":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/info","role":"symbol","type":"topic","title":"LoggerLogLevel.info","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/loggerloglevel\/info","abstract":[{"text":"Logs informative events.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevelInfo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/navigatorTitle","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1info\/title","op":"replace","value":"DOTLoggerLogLevelInfo"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1info\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}]}]}]}