{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/activeauthentication"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAuthentication","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Active Authentication protocol. Used if neither PACE-CAM nor Chip Authentication protocol is supported."}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAuthentication","kind":"identifier"}],"role":"symbol","roleHeading":"Case","modules":[{"name":"DotNfc"}],"externalID":"s:6DotNfc24ChipAuthenticationStatusC0D8ProtocolO06activeD0yA2EmF","title":"ChipAuthenticationStatus.AuthenticationProtocol.activeAuthentication"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/activeAuthentication"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"kind":"symbol","role":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol","type":"topic","abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/activeAuthentication":{"abstract":[{"type":"text","text":"Active Authentication protocol. Used if neither PACE-CAM nor Chip Authentication protocol is supported."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAuthentication","kind":"identifier"}],"title":"ChipAuthenticationStatus.AuthenticationProtocol.activeAuthentication","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/activeauthentication","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/activeAuthentication"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChipAuthenticationStatus","kind":"identifier"}],"navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"title":"ChipAuthenticationStatus","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}