{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"kind":"text","text":" = QualityAttributeThresholdPresets.standard.build(), "},{"text":"captureMode","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CaptureMode","kind":"typeIdentifier","text":"CaptureMode","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCaptureMode"},{"kind":"text","text":" = Defaults.captureMode, "},{"text":"isPlaceholderVisible","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.isPlaceholderVisible, "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"text":" = Defaults.cameraPreviewScaleType)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"]}],"metadata":{"title":"init(sessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"captureMode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCaptureMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isPlaceholderVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"},{"text":")","kind":"text"}],"externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds11captureMode20isPlaceholderVisible0p14DetectionLayerR00P12TorchEnabled12cameraFacing0W16PreviewScaleTypeAESSSg_AE07QualitylM0CAA0eO0OS3bAA06CameraX0OAA06CamerayZ4TypeOtcfc"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","url":"\/documentation\/dotfacelite\/camerafacing","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CaptureMode":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CaptureMode","abstract":[{"type":"text","text":"Capture mode."}],"url":"\/documentation\/dotfacelite\/capturemode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"type":"topic","title":"CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","kind":"typeIdentifier","text":"QualityAttributeThresholds"},{"kind":"text","text":", "},{"text":"captureMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCaptureMode"},{"text":", ","kind":"text"},{"text":"isPlaceholderVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"title":"init(sessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"type":"topic","kind":"symbol","title":"FaceAutoCaptureViewController","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraPreviewScaleType":{"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","kind":"symbol","type":"topic","role":"symbol","title":"CameraPreviewScaleType","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QualityAttributeThresholds"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CaptureMode\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]},{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]}]}]}