{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/result","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","text":"DOTPPalmAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"},{"text":" * ","kind":"text"},{"text":"result","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"result","navigatorTitle":[{"kind":"identifier","text":"result"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"text":"result","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiStateRunning(py)result","symbolKind":"property"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/result"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning","fragments":[{"text":"DOTPPalmAutoCaptureUiStateRunning","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning","kind":"symbol","title":"DOTPPalmAutoCaptureUiStateRunning","role":"symbol","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","title":"PalmAutoCaptureResult","abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/result":{"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/result","title":"result","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/result","abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"result","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title","value":"DOTPPalmAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"op":"replace"}]}]}