{"sections":[],"metadata":{"symbolKind":"property","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC14validationModeAA010ValidationI0Ovp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"validationMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"}],"title":"validationMode","role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Specify validation mode. Default is ","type":"text"},{"type":"codeVoice","code":".standard"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/validationmode"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/validationMode"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode"},{"kind":"text","text":": "},{"text":"ValidationMode","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","kind":"symbol","abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.12.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/validationMode":{"type":"topic","abstract":[{"text":"Specify validation mode. Default is ","type":"text"},{"code":".standard","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/validationMode","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"validationMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"}],"title":"validationMode","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/validationmode"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","title":"ValidationMode","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationMode"}],"url":"\/documentation\/dotdocument\/validationmode","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTDValidationMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}