{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/init(configuration:style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/init(configuration:style:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"metadata":{"title":"init(configuration:style:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC"},{"kind":"text","text":")"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(im)initWithConfiguration:style:","symbolKind":"init","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotDocument"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Create new ","type":"text"},{"type":"codeVoice","code":"DocumentAutoCaptureViewController"},{"text":".","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"},{"text":" = .init(), ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class"},{"text":" = .init())","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the capture process."}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize user interface."}]}],"name":"style"}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/init(configuration:style:)"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the UI Document Auto Capture component."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration":{"abstract":[{"text":"Configuration options for the UI Document Auto Capture component.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration","role":"symbol","type":"topic","fragments":[{"text":"DOTDDocumentAutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration","kind":"symbol","title":"DOTDDocumentAutoCaptureConfiguration"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/init(configuration:style:)":{"abstract":[{"text":"Create new ","type":"text"},{"code":"DocumentAutoCaptureViewController","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/init(configuration:style:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC","text":"Style"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"title":"init(configuration:style:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/init(configuration:style:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Style-swift.class":{"kind":"symbol","abstract":[{"text":"Customization options for the document auto capture user interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class","navigatorTitle":[{"text":"Style","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController.Style","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"kind":"symbol","abstract":[{"text":"UI Document Auto Capture component","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureStyle":{"kind":"symbol","abstract":[{"type":"text","text":"Customization options for the document auto capture user interface."}],"fragments":[{"text":"DOTDDocumentAutoCaptureStyle","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocapturestyle","type":"topic","role":"symbol","title":"DOTDDocumentAutoCaptureStyle","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureStyle"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithConfiguration:style:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration","text":"DOTDDocumentAutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"style:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureStyle","text":"DOTDDocumentAutoCaptureStyle","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureStyle"},{"text":" *) ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Configure the capture process.","type":"text"}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Customize user interface.","type":"text"}]}],"name":"style"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"initWithConfiguration:style:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1init(configuration:style:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1init(configuration:style:)\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}