{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary\/verifyIsActive()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibrary\/verifyisactive()"]},{"paths":["\/documentation\/dotfacecore\/dotlibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(pl)DotLibrary(im)verifyIsActiveAndReturnError:","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","role":"symbol","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"verifyIsActive","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"verifyIsActive()"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyIsActive","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary":{"url":"\/documentation\/dotfacecore\/dotlibrary","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary","title":"DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary/verifyIsActive()":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"required":true,"url":"\/documentation\/dotfacecore\/dotlibrary\/verifyisactive()","title":"verifyIsActive()","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary\/verifyIsActive()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"verifyIsActiveAndReturnError:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/title"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/fragments","op":"replace"},{"op":"replace","value":"verifyIsActiveAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary~1verifyIsActive()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary~1verifyIsActive()\/fragments","value":[{"kind":"text","text":"- "},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}