{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/brightnessinterval(_:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","text":"Builder"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"DotPalmCore"}],"externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC18brightnessIntervalyAI0aC00N6DoubleCSgKF","title":"brightnessInterval(_:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"brightnessInterval","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"brightnessInterval","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","text":"IntervalDouble"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/brightnessInterval(_:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","type":"topic","title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder/brightnessInterval(_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/brightnessInterval(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"brightnessInterval","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","text":"Builder"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/brightnessinterval(_:)","type":"topic","title":"brightnessInterval(_:)","abstract":[],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Builder"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder","type":"topic","title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds.Builder","abstract":[],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"title":"PalmAutoCaptureViewController","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"title":"PalmAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","type":"topic","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"url":"\/documentation\/dotpalmcore\/intervaldouble","type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"},{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments"}]}]}