{"sections":[],"metadata":{"externalID":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC10validatorsSayAA0bdE24FrameParametersValidator_pGvp","roleHeading":"Instance Property","title":"validators","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"kind":"text","text":": ["},{"text":"PalmAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotPalmCore"}]},"abstract":[{"text":"Array of validators which will be used to validate input image.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validators","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator","text":"PalmAutoCaptureFrameParametersValidator","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/validators"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/validators","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"type":"topic","abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}],"role":"symbol","title":"PalmAutoCaptureController.Configuration","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"type":"topic","title":"PalmAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"role":"symbol","kind":"symbol","title":"PalmAutoCaptureFrameParametersValidator","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class/validators":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validators","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"validators","abstract":[{"type":"text","text":"Array of validators which will be used to validate input image."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/validators","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/validators","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"DOTPPalmAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle"}]}]}