{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/backgroundUniformity"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/backgrounduniformity"]}],"sections":[],"kind":"symbol","metadata":{"title":"backgroundUniformity","navigatorTitle":[{"kind":"identifier","text":"backgroundUniformity"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)backgroundUniformity","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules/backgroundUniformity":{"type":"topic","fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/backgrounduniformity","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/backgroundUniformity","role":"symbol","title":"backgroundUniformity","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules":{"title":"DotFaceLibraryConfigurationModules","url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules","role":"symbol","abstract":[{"text":"Face library module configuration.","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceBackgroundUniformityModuleConfiguration":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotfacebackgrounduniformitymoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"abstract":[{"text":"Face background uniformity module.","type":"text"}],"role":"symbol","title":"DotFaceBackgroundUniformityModuleConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"patch":[{"value":"DotFaceBackgroundUniformityModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}