{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/detection","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"detection"}],"fragments":[{"text":"detection","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)detection","roleHeading":"Instance Property","title":"detection","symbolKind":"property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules","role":"symbol","abstract":[{"text":"Face library module configuration.","type":"text"}],"title":"DotFaceLibraryConfigurationModules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules","type":"topic","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration","abstract":[{"text":"Face detection module configuration.","type":"text"}],"title":"DotFaceDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules/detection":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"detection","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/detection","url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/detection","title":"detection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}