{"metadata":{"fragments":[{"text":"expressionNeutral","kind":"identifier"}],"symbolKind":"property","title":"expressionNeutral","roleHeading":"Instance Property","navigatorTitle":[{"text":"expressionNeutral","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)expressionNeutral"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/expressionNeutral","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/expressionneutral"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules/expressionNeutral":{"abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/expressionneutral","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/expressionNeutral","title":"expressionNeutral","kind":"symbol","role":"symbol","fragments":[{"text":"expressionNeutral","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules":{"abstract":[{"type":"text","text":"Face library module configuration."}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","kind":"symbol","role":"symbol","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceExpressionNeutralModuleConfiguration":{"abstract":[{"type":"text","text":"Face expression neutral module."}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfaceexpressionneutralmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration","title":"DotFaceExpressionNeutralModuleConfiguration","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFaceExpressionNeutralModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}