{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expressionNeutral:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"expressionNeutral","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundUniformity:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"backgroundUniformity","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceEyeGazeLivenessModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"eyeGazeLiveness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"passiveLiveness:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"passiveLiveness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"verification:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"verification","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(im)initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","navigatorTitle":[{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:","navigatorTitle":[{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","abstract":[],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceBackgroundUniformityModuleConfiguration":{"abstract":[{"type":"text","text":"Face background uniformity module."}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacebackgrounduniformitymoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration","title":"DotFaceBackgroundUniformityModuleConfiguration","navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceVerificationModuleConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","type":"topic","abstract":[{"text":"Face verification module.","type":"text"}],"title":"DotFaceVerificationModuleConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules":{"abstract":[{"type":"text","text":"Face library module configuration."}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","kind":"symbol","role":"symbol","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceExpressionNeutralModuleConfiguration":{"abstract":[{"type":"text","text":"Face expression neutral module."}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfaceexpressionneutralmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration","title":"DotFaceExpressionNeutralModuleConfiguration","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceEyeGazeLivenessModuleConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfaceeyegazelivenessmoduleconfiguration","navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"symbol","type":"topic","title":"DotFaceEyeGazeLivenessModuleConfiguration","abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration":{"abstract":[{"type":"text","text":"Face passive liveness module."}],"url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","title":"DotFacePassiveLivenessModuleConfiguration","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/title","value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/title","op":"replace","value":"DotFaceVerificationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/title","op":"replace","value":"DotFaceExpressionNeutralModuleConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFacePassiveLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}