{"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/intervalfloat\/error\/invalidbounds"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/invalidBounds","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidBounds"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error"]]},"metadata":{"role":"symbol","externalID":"s:7DotCore13IntervalFloatC5ErrorO13invalidBoundsyA2EmF","symbolKind":"case","modules":[{"name":"DotPalmCore"}],"title":"IntervalFloat.Error.invalidBounds","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidBounds"}],"roleHeading":"Case"},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"IntervalFloat.Error","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/intervalfloat\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat":{"navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"url":"\/documentation\/dotpalmcore\/intervalfloat","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error/invalidBounds":{"url":"\/documentation\/dotpalmcore\/intervalfloat\/error\/invalidbounds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/invalidBounds","kind":"symbol","type":"topic","abstract":[],"title":"IntervalFloat.Error.invalidBounds","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidBounds"}]}},"variantOverrides":[{"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}