{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/init(image:timestampMillis:depthImage:cameraCalibrationData:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample\/init(image:timestampmillis:depthimage:cameracalibrationdata:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample"]]},"metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"s:14DotFingersCore0B21AutoCaptureControllerC11PhotoSampleC5image15timestampMillis10depthImage21cameraCalibrationDataAE0aC00M0C_SiSo7CIImageCSgSo08AVCameraoP0CSgtcfc","role":"symbol","title":"init(image:timestampMillis:depthImage:cameraCalibrationData:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"depthImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cameraCalibrationData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCameraCalibrationData","kind":"typeIdentifier","text":"AVCameraCalibrationData"},{"kind":"text","text":"?)"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"depthImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cameraCalibrationData"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCameraCalibrationData","kind":"typeIdentifier","text":"AVCameraCalibrationData"},{"kind":"text","text":"?)"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"role":"symbol","title":"FingersAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureController"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample/init(image:timestampMillis:depthImage:cameraCalibrationData:)":{"role":"symbol","title":"init(image:timestampMillis:depthImage:cameraCalibrationData:)","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample\/init(image:timestampmillis:depthimage:cameracalibrationdata:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"text":"timestampMillis","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"depthImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cameraCalibrationData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCameraCalibrationData","text":"AVCameraCalibrationData","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/init(image:timestampMillis:depthImage:cameraCalibrationData:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample":{"title":"FingersAutoCaptureController.PhotoSample","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PhotoSample"}],"type":"topic","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"type":"codeVoice","code":".captureDepth"},{"type":"text","text":" event during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfingerscore\/image","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle"}]}]}