{"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/camera"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"}],"platforms":[{"deprecated":true,"message":"Use MultiRangeLivenessViewController instead.","unavailable":false,"beta":false}],"externalID":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC6camera0A7Capture06CameraI0Cvp","modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"camera","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"typeIdentifier","text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"Default is:","type":"text"}],"type":"paragraph"},{"code":[".init(cameraFacing: .front)"],"type":"codeListing","syntax":null},{"inlineContent":[{"text":"This component does not have camera preview, therefore these properties are ignored: ","type":"text"},{"code":"previewScaleType","type":"codeVoice"},{"type":"text","text":", "},{"code":"isPreviewVisible","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/camera","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"abstract":[{"type":"text","text":"UI Eye Gaze Liveness component."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"title":"EyeGazeLivenessViewController","role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"role":"symbol","deprecated":true,"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"type":"topic","title":"EyeGazeLivenessViewController.Configuration","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration options for the UI Eye Gaze Liveness component.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"title":"CameraConfiguration","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"type":"topic","role":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/camera":{"title":"camera","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/camera","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration","kind":"typeIdentifier"}],"type":"topic","deprecated":true,"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/camera"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}