{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/transitionType-swift.property"},"metadata":{"role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14transitionTypeAE010TransitionK0Ovp","modules":[{"name":"DotFaceCore"}],"platforms":[{"beta":false,"deprecated":true,"unavailable":false,"message":"Use MultiRangeLivenessViewController instead."}],"roleHeading":"Instance Property","title":"transitionType","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"transitionType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO","kind":"typeIdentifier","text":"TransitionType"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionType","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO","text":"TransitionType","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}]}],"abstract":[{"type":"text","text":"Corner transition type. Default is "},{"type":"codeVoice","code":".move"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/transitiontype-swift.property"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"abstract":[{"type":"text","text":"UI Eye Gaze Liveness component."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"deprecated":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"title":"EyeGazeLivenessViewController","role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"role":"symbol","deprecated":true,"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"type":"topic","title":"EyeGazeLivenessViewController.Configuration","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration options for the UI Eye Gaze Liveness component.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/TransitionType-swift.enum":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionType"}],"navigatorTitle":[{"kind":"identifier","text":"TransitionType"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/transitiontype-swift.enum","abstract":[{"text":"Eye gaze liveness available corner transition types.","type":"text"}],"kind":"symbol","deprecated":true,"type":"topic","title":"EyeGazeLivenessViewController.Configuration.TransitionType"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/transitionType-swift.property":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transitionType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TransitionType","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/transitionType-swift.property","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/transitiontype-swift.property","abstract":[{"type":"text","text":"Corner transition type. Default is "},{"code":".move","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","deprecated":true,"type":"topic","title":"transitionType"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}