{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/palm"},"metadata":{"navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdPalm","roleHeading":"Case","symbolKind":"case","title":"DotLibraryId.palm","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}]},"abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/dotlibraryid\/palm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotlibraryid\/palm"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotLibraryId/palm":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId\/palm","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"title":"DotLibraryId.palm","abstract":[{"type":"codeVoice","code":"DotPalmLibrary"},{"type":"text","text":" identifier."}],"url":"\/documentation\/dotdocument\/dotlibraryid\/palm","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"role":"symbol","kind":"symbol","title":"DotLibraryId","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdPalm"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdPalm","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1palm\/title","value":"DotLibraryIdPalm"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId~1palm\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdPalm"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/navigatorTitle","value":[{"kind":"identifier","text":"DotLibraryId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}