{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/isequal(_:)"]},{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/isEqual(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation"]]},"sections":[],"kind":"symbol","metadata":{"platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"modules":[{"name":"DotNfc"}],"symbolKind":"method","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation(im)isEqual:"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Result of NFC reading."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation/isEqual(_:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/isEqual(_:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.3.2"}],"url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation":{"navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MachineReadableZoneInformation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZoneInformation","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"type":"topic","url":"\/documentation\/dotnfc\/machinereadablezoneinformation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}