{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/failureReason","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/intervalfloat\/error\/failurereason"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error"]]},"metadata":{"platforms":[{"beta":false,"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"8.0"},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"8.0"},{"beta":false,"deprecated":false,"name":"Mac Catalyst","unavailable":false,"introducedAt":"8.0"},{"beta":false,"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.10"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0"},{"beta":false,"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0"}],"role":"symbol","extendedModule":"Foundation","modules":[{"name":"DotFaceLite","relatedModules":["Foundation"]}],"title":"failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error":{"role":"symbol","url":"\/documentation\/dotfacelite\/intervalfloat\/error","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error","abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"IntervalFloat.Error"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error/failureReason":{"title":"failureReason","role":"symbol","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/failureReason","url":"\/documentation\/dotfacelite\/intervalfloat\/error\/failurereason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat":{"role":"symbol","url":"\/documentation\/dotfacelite\/intervalfloat","kind":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"title":"IntervalFloat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/navigatorTitle"}]}]}