{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"]}],"abstract":[{"text":"Request capture of the next detection.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"isFacePresenceRequired","content":[{"inlineContent":[{"type":"text","text":"If true, the result will be captured only if a face is detected with defined quality attributes."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the result will be captured regardless of the face presence. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"type":"paragraph"}]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"title":"requestCapture(isFacePresenceRequired:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isFacePresenceRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController(im)requestCaptureWithIsFacePresenceRequired:"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isFacePresenceRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"requestCapture(isFacePresenceRequired:)"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"title":"BaseFaceAutoCaptureViewController","type":"topic","abstract":[{"type":"text","text":"UI component for capturing face images with customizable UI."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"requestCaptureWithIsFacePresenceRequired:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isFacePresenceRequired","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"If true, the result will be captured only if a face is detected with defined quality attributes.","type":"text"},{"text":" ","type":"text"},{"text":"Otherwise, the result will be captured regardless of the face presence. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"isFacePresenceRequired"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","op":"replace","value":"requestCaptureWithIsFacePresenceRequired:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFLBaseFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}