{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfacematchingenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfacematchingenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceMatchingEnabled","role":"symbol","required":true,"title":"isFaceMatchingEnabled","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"role":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"title":"DotSdkLicenseProxyProtocol","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"role":"symbol","navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isFaceMatchingEnabled","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfacematchingenabled"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.3.1"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"isFaceMatchingEnabled","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title","value":"isFaceMatchingEnabled","op":"replace"},{"op":"replace","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments"}]}]}