{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxy\/isfacepassivelivenessenabled"]},{"paths":["\/documentation\/dotnfc\/dotsdklicenseproxy\/isfacepassivelivenessenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"DotSdkLicenseProxyProtocol.isFacePassiveLivenessEnabled"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy"]]},"metadata":{"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DotSdkLicenseProxy(py)isFacePassiveLivenessEnabled","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"role":"symbol","title":"isFacePassiveLivenessEnabled","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isFacePassiveLivenessEnabled":{"url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isfacepassivelivenessenabled","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"title":"isFacePassiveLivenessEnabled"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy":{"navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"kind":"symbol","title":"DotSdkLicenseProxy","url":"\/documentation\/dotnfc\/dotsdklicenseproxy","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isFacePassiveLivenessEnabled"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/title","op":"replace","value":"isFacePassiveLivenessEnabled"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/fragments","value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"op":"replace"},{"value":"DotSdkLicenseProxy","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace"}]}]}