{"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkLicenseProxyProtocol.isFaceLiteEnabled","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotNfc"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isFaceLiteEnabled","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DotSdkLicenseProxy(py)isFaceLiteEnabled","navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotnfc\/dotsdklicenseproxy\/isfaceliteenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotsdklicenseproxy\/isfaceliteenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceLiteEnabled","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"role":"symbol","title":"DotSdkLicenseProxy","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxy"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isFaceLiteEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isfaceliteenabled","navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"title":"isFaceLiteEnabled","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceLiteEnabled"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isFaceLiteEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},{"value":"isFaceLiteEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title","op":"replace"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}