{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Candidate selection is running."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturephase\/candidateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturephase\/candidateselection"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/candidateSelection","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelection","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Case","externalID":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase@DOTDDocumentAutoCapturePhaseCandidateSelection","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePhaseCandidateSelection"}],"title":"DocumentAutoCapturePhase.candidateSelection"},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"url":"\/documentation\/dotdocument\/documentautocapturephase","role":"symbol","abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"identifier"}],"type":"topic","title":"DocumentAutoCapturePhase","kind":"symbol","navigatorTitle":[{"text":"DocumentAutoCapturePhase","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/candidateSelection":{"title":"DocumentAutoCapturePhase.candidateSelection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/candidateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelection","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturephase\/candidateselection","role":"symbol","type":"topic","navigatorTitle":[{"text":"DOTDDocumentAutoCapturePhaseCandidateSelection","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Candidate selection is running."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTDDocumentAutoCapturePhaseCandidateSelection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTDDocumentAutoCapturePhaseCandidateSelection","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DOTDDocumentAutoCapturePhaseCandidateSelection","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title","value":"DOTDDocumentAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1candidateSelection\/title","value":"DOTDDocumentAutoCapturePhaseCandidateSelection"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1candidateSelection\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhaseCandidateSelection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}