{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectFacesFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/facedetector\/error\/detectfacesfailed(internalerror:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore0B8DetectorC5ErrorO17detectFacesFailedyAEsAD_p_tcAEmF","symbolKind":"case","title":"FaceDetector.Error.detectFacesFailed(internalError:)","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectFacesFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error\/detectFacesFailed(internalError:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Error/detectFacesFailed(internalError:)":{"abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectFacesFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error\/detectFacesFailed(internalError:)","title":"FaceDetector.Error.detectFacesFailed(internalError:)","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/error\/detectfacesfailed(internalerror:)","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Error":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"FaceDetector.Error","url":"\/documentation\/dotfacecore\/facedetector\/error","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"url":"\/documentation\/dotfacecore\/facedetector","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"type":"topic","title":"FaceDetector","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}