{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/error\/recoverysuggestion"]}],"metadata":{"title":"recoverySuggestion","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"modules":[{"relatedModules":["Foundation"],"name":"DotFaceCore"}],"platforms":[{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"iPadOS"},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"Mac Catalyst"},{"deprecated":false,"introducedAt":"10.10","unavailable":false,"beta":false,"name":"macOS"},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"beta":false,"name":"tvOS"},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false,"name":"watchOS"}],"extendedModule":"Foundation","roleHeading":"Instance Property","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:11DotFaceCore0B8DetectorC5ErrorO","symbolKind":"property"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error\/recoverySuggestion","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Error":{"abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"FaceDetector.Error","url":"\/documentation\/dotfacecore\/facedetector\/error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Error/recoverySuggestion":{"abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/facedetector\/error\/recoverysuggestion","title":"recoverySuggestion","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error\/recoverySuggestion","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace","value":"DOTFFaceDetector"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]}]}]}