{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfcTravelDocumentReader","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"nfcTravelDocumentReader"},{"text":": ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"kind":"text","text":", "},{"text":"succeeded","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"travelDocument","kind":"internalParam"},{"kind":"text","text":": "},{"text":"TravelDocument","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Tells the delegate that NFC reading has finished successfully with travel document as a result."}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nfcTravelDocumentReader","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"succeeded"},{"text":": ","kind":"text"},{"text":"TravelDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument"},{"text":")","kind":"text"}],"role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0","name":"iOS"}],"symbolKind":"method","roleHeading":"Instance Method","title":"nfcTravelDocumentReader(_:succeeded:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"nfcTravelDocumentReader:succeeded:"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate(im)nfcTravelDocumentReader:succeeded:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:succeeded:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:succeeded:)"]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:succeeded:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate/nfcTravelDocumentReader(_:succeeded:)":{"kind":"symbol","type":"topic","role":"symbol","title":"nfcTravelDocumentReader(_:succeeded:)","required":true,"abstract":[{"text":"Tells the delegate that NFC reading has finished successfully with travel document as a result.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:succeeded:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:succeeded:)","navigatorTitle":[{"kind":"identifier","text":"nfcTravelDocumentReader:succeeded:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"nfcTravelDocumentReader","kind":"identifier"},{"kind":"text","text":"("},{"text":"NfcTravelDocumentReader","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"text":", ","kind":"text"},{"text":"succeeded","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TravelDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"role":"symbol","type":"topic","title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","abstract":[{"type":"text","text":"Result of NFC reading."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"text":"version: 8.4.1","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate":{"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate","navigatorTitle":[{"text":"NfcTravelDocumentReaderDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this delegate to handle the NFC reading events.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReaderDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","title":"NfcTravelDocumentReaderDelegate","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"role":"symbol","type":"topic","title":"NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"nfcTravelDocumentReader:succeeded:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nfcTravelDocumentReader:succeeded:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"nfcTravelDocumentReader:"},{"text":"(","kind":"text"},{"text":"DOTNNfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nfcTravelDocumentReader"},{"kind":"text","text":" "},{"kind":"identifier","text":"succeeded:"},{"text":"(","kind":"text"},{"text":"DOTNTravelDocument","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"travelDocument","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:succeeded:)\/title","value":"nfcTravelDocumentReader:succeeded:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:succeeded:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"nfcTravelDocumentReader:succeeded:","kind":"identifier"}]},{"value":"DOTNTravelDocument","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/title","value":"DOTNNfcTravelDocumentReaderDelegate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}]},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"}]}]}