{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults"]]},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","text":"IntervalDouble"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults\/facesizeratiointerval"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/faceSizeRatioInterval"},"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC8DefaultsV21faceSizeRatioInterval0aC00N6DoubleCvpZ","title":"faceSizeRatioInterval"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class/Defaults":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"type":"topic","role":"symbol","title":"MultiRangeLivenessViewController.Configuration.Defaults","kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults","navigatorTitle":[{"text":"Defaults","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","kind":"symbol","title":"MultiRangeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfacecore\/intervaldouble","role":"symbol","kind":"symbol","title":"IntervalDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"type":"topic","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"MultiRangeLivenessViewController.Configuration","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class/Defaults/faceSizeRatioInterval":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"}],"type":"topic","role":"symbol","title":"faceSizeRatioInterval","kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults\/facesizeratiointerval","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/faceSizeRatioInterval"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFMultiRangeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle"},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle"}]}]}