{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"]]},"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"}],"symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration(im)initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"title":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"DOTCameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType"},{"kind":"text","text":") "},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithsessiontoken:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","url":"\/documentation\/dotfacelite\/camerapreviewscaletype","kind":"symbol","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"url":"\/documentation\/dotfacelite\/camerafacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:":{"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithsessiontoken:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"}],"title":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"fragments":[{"text":"DOTFLMagnifEyeLivenessConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","type":"topic","title":"DOTFLMagnifEyeLivenessConfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}]}]}