{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/balanced\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC8BalancedCAEycfc","role":"symbol","title":"init()","roleHeading":"Initializer","modules":[{"name":"DotDocument"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced\/init()"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration":{"title":"DotFaceDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection module configuration."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Balanced/init()":{"type":"topic","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/balanced\/init()","title":"init()","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceDetectionModuleConfiguration/Balanced":{"abstract":[{"type":"text","text":"Face detection balanced module."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceDetectionModuleConfiguration\/Balanced","url":"\/documentation\/dotdocument\/dotfacedetectionmoduleconfiguration\/balanced","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}],"navigatorTitle":[{"kind":"identifier","text":"Balanced"}],"kind":"symbol","type":"topic","role":"symbol","title":"DotFaceDetectionModuleConfiguration.Balanced"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceDetectionModuleConfiguration\/navigatorTitle"}]}]}