{"abstract":[{"type":"text","text":"Builder for "},{"type":"codeVoice","code":"FaceAutoCaptureQualityAttributeThresholds"},{"text":" recommended for standard use cases, for example matching.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Presets"]]},"kind":"symbol","metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":"."},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"externalID":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7PresetsC8standardAC7BuilderCvpZ","role":"symbol","roleHeading":"Type Property","title":"standard","modules":[{"name":"DotFaceLite"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/presets\/standard"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder","text":"Builder","preciseIdentifier":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minConfidence"},{"type":"text","text":" value is 0.12."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"sizeInterval"},{"type":"text","text":" value is [0.16, 0.2]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"maxDevicePitchAngle"},{"type":"text","text":" value is 30."}]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Presets\/standard","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Presets/standard":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Presets\/standard","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/presets\/standard","type":"topic","title":"standard","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Builder for "},{"type":"codeVoice","code":"FaceAutoCaptureQualityAttributeThresholds"},{"type":"text","text":" recommended for standard use cases, for example matching."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Builder":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/builder","navigatorTitle":[{"text":"Builder","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Builder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"title":"FaceAutoCaptureQualityAttributeThresholds.Builder","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds","role":"symbol","title":"FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/Presets":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/presets","navigatorTitle":[{"kind":"identifier","text":"Presets"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/Presets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presets"}],"title":"FaceAutoCaptureQualityAttributeThresholds.Presets","abstract":[{"text":"Presets for the quality attributes thresholds of the face auto capture result.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFLFaceAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle"}]}]}