{"metadata":{"roleHeading":"API Collection","title":"CustomStringConvertible Implementations","role":"collectionGroup","modules":[{"name":"DotNfc"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser\/error\/customstringconvertible-implementations"]}],"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error"]]},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/description"]}],"references":{"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error":{"abstract":[],"kind":"symbol","type":"topic","title":"FlatTagStructureParser.Error","url":"\/documentation\/dotnfc\/flattagstructureparser\/error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"title":"FlatTagStructureParser","role":"symbol","navigatorTitle":[{"text":"FlatTagStructureParser","kind":"identifier"}],"url":"\/documentation\/dotnfc\/flattagstructureparser","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","abstract":[{"type":"text","text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse "},{"type":"codeVoice","code":"OptionalDetails.content"},{"type":"text","text":" of some documents."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FlatTagStructureParser","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/description":{"abstract":[],"kind":"symbol","title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/description","role":"symbol","url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","value":"DOTNFlatTagStructureParser"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/navigatorTitle","value":[{"text":"DOTNFlatTagStructureParser","kind":"identifier"}]}]}]}