{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/recoverySuggestion"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/LocalizedError-Implementations"]]},"metadata":{"modules":[{"relatedModules":["Foundation"],"name":"DotNfc"}],"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:6DotNfc22FlatTagStructureParserC5ErrorO","title":"recoverySuggestion","extendedModule":"Foundation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","platforms":[{"beta":false,"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"iOS"},{"beta":false,"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"iPadOS"},{"beta":false,"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"Mac Catalyst"},{"beta":false,"deprecated":false,"introducedAt":"10.10","unavailable":false,"name":"macOS"},{"beta":false,"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"tvOS"},{"beta":false,"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS"}],"roleHeading":"Instance Property"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/flattagstructureparser\/error\/recoverysuggestion"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/recoverySuggestion":{"title":"recoverySuggestion","url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/recoverysuggestion","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/recoverySuggestion","abstract":[],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","url":"\/documentation\/dotnfc\/flattagstructureparser","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlatTagStructureParser"}],"title":"FlatTagStructureParser","abstract":[{"type":"text","text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse "},{"type":"codeVoice","code":"OptionalDetails.content"},{"type":"text","text":" of some documents."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FlatTagStructureParser"}]},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error":{"url":"\/documentation\/dotnfc\/flattagstructureparser\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"FlatTagStructureParser.Error","abstract":[]},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser/Error/LocalizedError-Implementations":{"role":"collectionGroup","kind":"article","abstract":[],"title":"LocalizedError Implementations","url":"\/documentation\/dotnfc\/flattagstructureparser\/error\/localizederror-implementations","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error\/LocalizedError-Implementations"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","value":"DOTNFlatTagStructureParser","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}],"op":"replace"},{"value":[{"text":"DOTNFlatTagStructureParser","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/navigatorTitle"}]}]}