{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary\/id"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotlibrary\/id"]},{"paths":["\/documentation\/dotdocument\/dotlibrary\/id"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"required":true,"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"id","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(pl)DotLibrary(py)id"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibrary":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","title":"DotLibrary","url":"\/documentation\/dotdocument\/dotlibrary","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibrary/id":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary\/id","abstract":[],"title":"id","url":"\/documentation\/dotdocument\/dotlibrary\/id","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId"}],"role":"symbol","kind":"symbol","required":true,"navigatorTitle":[{"text":"id","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId":{"kind":"symbol","url":"\/documentation\/dotdocument\/dotlibraryid","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"title":"DotLibraryId","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"id","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"id","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/title"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary~1id\/title","value":"id"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary~1id\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/fragments"}]}]}