{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"roleHeading":"Instance Method","symbolKind":"method","title":"verifyIsActive()","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyIsActive","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(pl)DotLibrary(im)verifyIsActiveAndReturnError:"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/dotlibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotlibrary\/verifyisactive()"]}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary\/verifyIsActive()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"verifyIsActive","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibrary/verifyIsActive()":{"navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"type":"topic","title":"verifyIsActive()","kind":"symbol","required":true,"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyIsActive"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotlibrary\/verifyisactive()","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary\/verifyIsActive()"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibrary":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","title":"DotLibrary","url":"\/documentation\/dotdocument\/dotlibrary","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"verifyIsActiveAndReturnError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"verifyIsActiveAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary~1verifyIsActive()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary~1verifyIsActive()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/title","value":"DotLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}