{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(cgImage:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithCgImage:","modules":[{"name":"DotPalmCore"}],"roleHeading":"Type Method","role":"symbol","title":"create(cgImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"cgImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}],"symbolKind":"method"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"cgImage","content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory"]]},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(cgimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(cgimage:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory/create(cgImage:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(cgImage:)","title":"create(cgImage:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(cgimage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"type":"topic","url":"\/documentation\/dotpalmcore\/bgrarawimage","title":"BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory":{"title":"BgraRawImageFactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}],"url":"\/documentation\/dotpalmcore\/bgrarawimagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"createWithCgImage:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithCgImage:"},{"kind":"text","text":"("},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImage","preciseIdentifier":"c:@S@CGImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"cgImage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithCgImage:","kind":"identifier"}],"op":"replace"},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/title","op":"replace","value":"DOTBgraRawImageFactory"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/fragments","op":"replace"}]}]}