{"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSessionToken:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityAttributeThresholds:"},{"kind":"text","text":"("},{"text":"DOTFLQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","interfaceLanguage":"occ"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"symbolKind":"method","title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","modules":[{"name":"DotFaceLite"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration":{"fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureConfiguration"}],"role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration","kind":"symbol","title":"DOTFLFaceAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLQualityAttributeThresholds":{"type":"topic","url":"\/documentation\/dotfacelite\/dotflqualityattributethresholds","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLQualityAttributeThresholds","kind":"symbol","role":"symbol","fragments":[{"text":"DOTFLQualityAttributeThresholds","kind":"identifier"}],"abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"}],"title":"DOTFLQualityAttributeThresholds"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing":{"role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerafacing","type":"topic","title":"CameraFacing","kind":"symbol","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraPreviewScaleType":{"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","type":"topic","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"kind":"symbol","title":"CameraPreviewScaleType"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:","type":"topic","title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/title"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/fragments"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"}]}]}