{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/init(value:isvalid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/init(value:isvalid:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit"]]},"kind":"symbol","metadata":{"symbolKind":"init","role":"symbol","roleHeading":"Initializer","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit(im)initWithValue:isValid:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"initWithValue:isValid:","kind":"identifier"}],"title":"init(value:isValid:)"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/init(value:isValid:)"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.17.1"}]},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"title":"MrzCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/mrzcheckdigit"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/init(value:isValid:)":{"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/mrzcheckdigit\/init(value:isvalid:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/init(value:isValid:)","title":"init(value:isValid:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithValue:isValid:"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithValue:isValid:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:isValid:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isValid:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isValid","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTMrzCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title"},{"value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1init(value:isValid:)\/title","op":"replace","value":"initWithValue:isValid:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1init(value:isValid:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:isValid:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}