{"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isEqual(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit"]]},"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit(im)isEqual:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","modules":[{"name":"DotNfc"}],"title":"isEqual(_:)"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/isequal(_:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/isEqual(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isEqual(_:)","url":"\/documentation\/dotnfc\/mrzcheckdigit\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isEqual(_:)"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.10.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","type":"topic","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","url":"\/documentation\/dotnfc\/mrzcheckdigit","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"type":"topic","title":"MrzCheckDigit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","op":"replace","value":"DOTMrzCheckDigit"},{"value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments"}]}]}