{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/isvalid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/isvalid"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isValid","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit"]]},"metadata":{"role":"symbol","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"isValid"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit(py)isValid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isValid","symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"abstract":[{"text":"Denotes whether a checksum of a particular MRZ element is valid.","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/isValid":{"navigatorTitle":[{"kind":"identifier","text":"isValid"}],"url":"\/documentation\/dotnfc\/mrzcheckdigit\/isvalid","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isValid","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isValid","abstract":[{"type":"text","text":"Denotes whether a checksum of a particular MRZ element is valid."}],"type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"url":"\/documentation\/dotnfc\/mrzcheckdigit","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","title":"MrzCheckDigit","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzCheckDigit"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isValid","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"isValid"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isValid"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isValid","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isValid\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isValid"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isValid\/fragments","op":"replace"},{"value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/navigatorTitle","op":"replace"}]}]}