{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:)"},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:"}],"role":"symbol","title":"init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:)","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(im)initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mrzRecognitionResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzRecognitionResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Barcode","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode"},{"kind":"text","text":"?)"}],"symbolKind":"init","modules":[{"name":"DotDocument"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detectionAreaImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector"},{"kind":"text","text":"."},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"mrzRecognitionResult"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","text":"MrzRecognitionResult"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","text":"Barcode"},{"kind":"text","text":"? = nil)"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(detectionareaimagesize:document:traveldocumenttype:mrzrecognitionresult:barcode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(detectionareaimagesize:document:traveldocumenttype:mrzrecognitionresult:barcode:)"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","kind":"symbol","title":"DocumentDetector.Document","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"abstract":[{"text":"Result of the document detection process.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Document"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:"}],"type":"topic","role":"symbol","title":"init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":", "},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"mrzRecognitionResult","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult"},{"text":"?, ","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Barcode","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(detectionareaimagesize:document:traveldocumenttype:mrzrecognitionresult:barcode:)"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","abstract":[{"text":"Result of the document detection process.","type":"text"}],"type":"topic","role":"symbol","title":"DOTDDocumentDetectorDocument","kind":"symbol","fragments":[{"text":"DOTDDocumentDetectorDocument","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument"},"doc://DotDocument/documentation/DotDocument/ImageSize":{"type":"topic","title":"ImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","url":"\/documentation\/dotdocument\/imagesize","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Barcode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","title":"Barcode","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"type":"topic","abstract":[{"type":"text","text":"Result of barcode detection process."}],"url":"\/documentation\/dotdocument\/barcode","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","title":"DocumentDetector","type":"topic","url":"\/documentation\/dotdocument\/documentdetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"kind":"symbol","title":"TravelDocumentTypeWrapper","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"type":"topic","abstract":[{"type":"text","text":"Wrapped "},{"code":"TravelDocumentType","type":"codeVoice"},{"type":"text","text":" for Objective-C support."}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureFrameParameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}],"navigatorTitle":[{"kind":"identifier","text":"MrzRecognitionResult"}],"type":"topic","role":"symbol","title":"MrzRecognitionResult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzRecognitionResult","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzrecognitionresult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetectionAreaImageSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","text":"DOTImageSize"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detectionAreaImageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"document:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","text":"DOTDDocumentDetectorDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"text":"travelDocumentType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTTravelDocumentTypeWrapper","preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"travelDocumentType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mrzRecognitionResult:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","text":"DOTDMrzRecognitionResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mrzRecognitionResult","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcode:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcode","text":"DOTDBarcode","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:barcode:)\/fragments"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","value":"DOTDBarcode","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","value":[{"text":"DOTDBarcode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTTravelDocumentTypeWrapper","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/navigatorTitle"},{"value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle"},{"value":"DOTDMrzRecognitionResult","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/title"},{"value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/fragments"},{"value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/navigatorTitle"}]}]}