{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"title":"DotFaceVerificationModuleConfiguration","roleHeading":"Class","role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},"abstract":[{"type":"text","text":"Face verification module."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"references":{"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceVerificationModuleConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Face verification module."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","role":"symbol","title":"DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceVerificationModuleConfiguration/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration\/init","url":"\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","title":"init"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceVerificationModuleConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration\/init"],"anchor":"Instance-Methods"}],"op":"add"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/title","value":"DotFaceVerificationModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace"}]}]}