{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId"},"metadata":{"navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"symbolKind":"enum","title":"DotPalmModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"roleHeading":"Enumeration","role":"symbol","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@E@DotPalmModuleId"},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotpalmmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotpalmmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/detection"],"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/description"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"code":"DotPalm","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"sections":[],"references":{"doc://DotFaceLite/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotFaceLite\/SY"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/dotpalmmoduleid","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId","title":"DotPalmModuleId","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/detection":{"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/detection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/detection","title":"DotPalmModuleId.detection","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"type":"topic"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/init(rawValue:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/equatable-implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/Equatable-Implementations"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/description":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/description","abstract":[],"title":"description","url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/description","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotPalmModuleId","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/detection"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotPalmModuleId","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/title"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/navigatorTitle"},{"value":"DotPalmModuleIdDetection","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId~1detection\/title"},{"value":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId~1detection\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}