{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrzelementwithchecksum\/init(value:positions:hasvalidchecksum:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzelementwithchecksum\/init(value:positions:hasvalidchecksum:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/init(value:positions:hasValidChecksum:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzStringPosition"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(value:positions:hasValidChecksum:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTMrzElementWithChecksum(im)initWithValue:positions:hasValidChecksum:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:hasValidChecksum:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum/init(value:positions:hasValidChecksum:)":{"role":"symbol","title":"init(value:positions:hasValidChecksum:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzStringPosition"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/init(value:positions:hasValidChecksum:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:hasValidChecksum:"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum\/init(value:positions:hasvalidchecksum:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzStringPosition":{"role":"symbol","title":"MrzStringPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"url":"\/documentation\/dotdocument\/mrzstringposition"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum":{"role":"symbol","title":"MrzElementWithChecksum","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithChecksum"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with checksum validity flag."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithChecksum"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithValue:positions:hasValidChecksum:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:positions:hasValidChecksum:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"kind":"identifier","text":"positions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DOTMrzStringPosition *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"positions"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasValidChecksum:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hasValidChecksum"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1init(value:positions:hasValidChecksum:)\/title","value":"initWithValue:positions:hasValidChecksum:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1init(value:positions:hasValidChecksum:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:positions:hasValidChecksum:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/fragments","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum\/title","value":"DOTMrzElementWithChecksum"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum\/fragments","value":[{"kind":"identifier","text":"DOTMrzElementWithChecksum"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}