{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"}],"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","roleHeading":"Instance Property","title":"detection","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class\/detection"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","title":"detection","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"title":"DotPalmLibraryConfiguration","type":"topic","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","kind":"symbol","abstract":[{"text":"Palm library module configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class","title":"DotPalmLibraryConfiguration.Modules","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmDetectionModuleConfiguration":{"abstract":[{"type":"text","text":"Palm detection module configuration."}],"title":"DotPalmDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","url":"\/documentation\/dotfacelite\/dotpalmdetectionmoduleconfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}