{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"metadata":{"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAeA0ac15DetectionModuleE0C_tcfc","symbolKind":"init","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}],"roleHeading":"Initializer","role":"symbol","title":"init(detection:)"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmDetectionModuleConfiguration":{"abstract":[{"text":"Palm detection module configuration.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"title":"DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotpalmdetectionmoduleconfiguration","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}],"role":"symbol","title":"init(detection:)"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"abstract":[{"text":"Palm library configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration","title":"DotPalmLibraryConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Palm library module configuration.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"title":"DotPalmLibraryConfiguration.Modules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"patch":[{"value":"DotPalmDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/title"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/fragments"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/navigatorTitle"},{"value":"DotPalmLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/title"},{"value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/fragments"},{"value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}