{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/build"]}],"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"build"}],"title":"build","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder(im)build","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"text":"build","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/build","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder/build":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"build"}],"title":"build","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"build"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/build","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/build","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"title":"DocumentAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"navigatorTitle":[{"text":"DocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder":{"fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"}],"title":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","value":"DOTDDocumentAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}]}]}]}