{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/RawRepresentable-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/hash(into:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/hash(into:)"},"metadata":{"modules":[{"relatedModules":["Swift"],"name":"DotDocument"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotDocument@E@DOTTravelDocumentType","symbolKind":"method","extendedModule":"Swift","title":"hash(into:)","roleHeading":"Instance Method","role":"symbol","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType":{"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocumentType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/traveldocumenttype","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"title":"TravelDocumentType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/RawRepresentable-Implementations","url":"\/documentation\/dotdocument\/traveldocumenttype\/rawrepresentable-implementations","abstract":[],"title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/hash(into:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"text":")","kind":"text"}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/hash(into:)","url":"\/documentation\/dotdocument\/traveldocumenttype\/hash(into:)","abstract":[],"title":"hash(into:)","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.1.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType\/title","value":"DOTTravelDocumentType"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType\/fragments"},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"}]}]}