{"kind":"symbol","metadata":{"externalID":"c:@M@DotDocument@E@DOTTravelDocumentType@DOTTravelDocumentTypeTd2","roleHeading":"Case","symbolKind":"case","modules":[{"name":"DotDocument"}],"title":"TravelDocumentType.td2","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"td2","kind":"identifier"}],"navigatorTitle":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttype\/td2"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/td2"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType"]]},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td2","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td2"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.1.0"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType/td2":{"role":"symbol","abstract":[],"kind":"symbol","title":"TravelDocumentType.td2","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType\/td2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td2","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttype\/td2","navigatorTitle":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentType":{"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocumentType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/traveldocumenttype","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"title":"TravelDocumentType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentType","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"DOTTravelDocumentTypeTd2","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd2"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd2"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTTravelDocumentTypeTd2","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td2\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType~1td2\/fragments","value":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType\/title","value":"DOTTravelDocumentType"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentType\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}