{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectionArea"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Normalized rectangle which represents the region in the image which will be used for the fingers detection.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerconfiguration\/detectionarea"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration"]]},"sections":[],"metadata":{"title":"detectionArea","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerConfiguration(py)detectionArea","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"detectionArea"}],"navigatorTitle":[{"kind":"identifier","text":"detectionArea"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration\/detectionArea","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerConfiguration":{"title":"DOTFGFingersAutoCaptureControllerConfiguration","fragments":[{"text":"DOTFGFingersAutoCaptureControllerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the fingers auto capture non-UI component."}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerConfiguration/detectionArea":{"kind":"symbol","title":"detectionArea","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerconfiguration\/detectionarea","fragments":[{"text":"detectionArea","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"Normalized rectangle which represents the region in the image which will be used for the fingers detection.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration\/detectionArea"}},"variantOverrides":[{"patch":[{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}