{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":" * "},{"kind":"identifier","text":"qualityAttributeThresholds"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"text","text":".standard"},{"type":"text","text":" preset."}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerconfiguration\/qualityattributethresholds"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration"]]},"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerConfiguration(py)qualityAttributeThresholds","role":"symbol","title":"qualityAttributeThresholds","navigatorTitle":[{"text":"qualityAttributeThresholds","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"qualityAttributeThresholds"}],"modules":[{"name":"DotFingersCore"}]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration\/qualityAttributeThresholds"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerConfiguration":{"title":"DOTFGFingersAutoCaptureControllerConfiguration","fragments":[{"text":"DOTFGFingersAutoCaptureControllerConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the fingers auto capture non-UI component."}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerConfiguration/qualityAttributeThresholds":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerConfiguration\/qualityAttributeThresholds","title":"qualityAttributeThresholds","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerconfiguration\/qualityattributethresholds","abstract":[{"text":"Customize thresholds for the quality attributes of the capture result. Default is ","type":"text"},{"text":".standard","type":"text"},{"text":" preset.","type":"text"}],"role":"symbol","fragments":[{"text":"qualityAttributeThresholds","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTFGFingersAutoCaptureQualityAttributeThresholds","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}