{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdkconfiguration\/init(licensebytes:libraries:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdkconfiguration\/init(licensebytes:libraries:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"text":"])","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(licenseBytes:libraries:)","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:","modules":[{"name":"DotPalmCore"}],"role":"symbol","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/init(licenseBytes:libraries:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"url":"\/documentation\/dotpalmcore\/dotsdkconfiguration","kind":"symbol","title":"DotSdkConfiguration","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration/init(licenseBytes:libraries:)":{"navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/init(licenseBytes:libraries:)","abstract":[],"title":"init(licenseBytes:libraries:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"])","kind":"text"}],"url":"\/documentation\/dotpalmcore\/dotsdkconfiguration\/init(licensebytes:libraries:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","abstract":[],"url":"\/documentation\/dotpalmcore\/dotlibrary","kind":"symbol","title":"DotLibrary","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithLicenseBytes:libraries:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLicenseBytes:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<DotLibrary>>"},{"text":" *) ","kind":"text"},{"text":"libraries","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"DotSdkConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/title"},{"value":[{"text":"DotSdkConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/title","op":"replace","value":"initWithLicenseBytes:libraries:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/fragments","op":"replace"},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/title"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}