{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Corners","text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTCorners"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory"]]},"metadata":{"navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"role":"symbol","title":"createDetectionPath(corners:cornerRadius:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"externalID":"c:@M@DotDocument@objc(cs)DOTBezierPathFactory(cm)createDetectionPathWithCorners:cornerRadius:","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"DotDocument"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createDetectionPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTCorners"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","title":"createDetectionPath(corners:cornerRadius:)","navigatorTitle":[{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory","kind":"symbol","type":"topic","title":"BezierPathFactory","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bezierpathfactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Corners":{"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"url":"\/documentation\/dotdocument\/corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"type":"topic","title":"Corners","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Corners","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"createDetectionPathWithCorners:cornerRadius:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"createDetectionPathWithCorners:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTCorners","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Corners","text":"DOTCorners"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"corners"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","value":"createDetectionPathWithCorners:cornerRadius:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},{"value":"DOTBezierPathFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/title"},{"value":[{"kind":"identifier","text":"DOTBezierPathFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}