{"sections":[],"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcodevalidation\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation"]]},"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"DotDocument"}],"role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/Equatable-Implementations"},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/!=(_:_:)"],"anchor":"Operators"}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","title":"BarcodeValidation","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeValidation","kind":"identifier"}],"abstract":[{"text":"Mode of barcode validation.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"BarcodeValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcodevalidation"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/!=(_:_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/!=(_:_:)","title":"!=(_:_:)","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/barcodevalidation\/!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTDBarcodeValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title"},{"op":"replace","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments"},{"op":"replace","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle"}]}]}