{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects(py)eyeDistanceToImageShorterSideRatio","title":"eyeDistanceToImageShorterSideRatio","navigatorTitle":[{"text":"eyeDistanceToImageShorterSideRatio","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeDistanceToImageShorterSideRatio"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/eyeDistanceToImageShorterSideRatio"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects"]]},"abstract":[{"type":"text","text":"Eye distance ratio to image shorter side."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"eyeDistanceToImageShorterSideRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/faceaspects\/eyedistancetoimageshortersideratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceaspects\/eyedistancetoimageshortersideratio"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.11.0"}],"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"kind":"symbol","title":"FaceAspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","url":"\/documentation\/dotfacecore\/faceaspects","type":"topic","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects/eyeDistanceToImageShorterSideRatio":{"url":"\/documentation\/dotfacecore\/faceaspects\/eyedistancetoimageshortersideratio","type":"topic","title":"eyeDistanceToImageShorterSideRatio","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/eyeDistanceToImageShorterSideRatio","navigatorTitle":[{"text":"eyeDistanceToImageShorterSideRatio","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeDistanceToImageShorterSideRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"text":"Eye distance ratio to image shorter side.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"eyeDistanceToImageShorterSideRatio"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"eyeDistanceToImageShorterSideRatio","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"eyeDistanceToImageShorterSideRatio","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTFFaceAspects","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace"},{"value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1eyeDistanceToImageShorterSideRatio\/title","value":"eyeDistanceToImageShorterSideRatio","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1eyeDistanceToImageShorterSideRatio\/fragments","value":[{"text":"eyeDistanceToImageShorterSideRatio","kind":"identifier"}]}]}]}