{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/init(eyeDistanceToImageShorterSideRatio:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"init(eyeDistanceToImageShorterSideRatio:)","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects(im)initWithEyeDistanceToImageShorterSideRatio:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"eyeDistanceToImageShorterSideRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithEyeDistanceToImageShorterSideRatio:"}],"roleHeading":"Initializer"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"eyeDistanceToImageShorterSideRatio","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceaspects\/init(eyedistancetoimageshortersideratio:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceaspects\/init(eyedistancetoimageshortersideratio:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"type":"topic","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"role":"symbol","title":"FaceAspects","url":"\/documentation\/dotfacecore\/faceaspects","abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects/init(eyeDistanceToImageShorterSideRatio:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithEyeDistanceToImageShorterSideRatio:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects\/init(eyeDistanceToImageShorterSideRatio:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"eyeDistanceToImageShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(eyeDistanceToImageShorterSideRatio:)","url":"\/documentation\/dotfacecore\/faceaspects\/init(eyedistancetoimageshortersideratio:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithEyeDistanceToImageShorterSideRatio:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEyeDistanceToImageShorterSideRatio:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithEyeDistanceToImageShorterSideRatio:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"eyeDistanceToImageShorterSideRatio"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects"},{"value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"op":"replace","value":"initWithEyeDistanceToImageShorterSideRatio:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1init(eyeDistanceToImageShorterSideRatio:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects~1init(eyeDistanceToImageShorterSideRatio:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithEyeDistanceToImageShorterSideRatio:","kind":"identifier"}]}]}]}