{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillTransition(_:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewWillTransition"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"magnifEyeLivenessViewControllerViewWillTransition:","kind":"identifier"}],"platforms":[{"message":"Use MultiRangeLivenessViewController instead.","deprecated":true,"beta":false,"unavailable":false}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"method","title":"magnifEyeLivenessViewControllerViewWillTransition(_:)","externalID":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessViewControllerViewWillTransition:","roleHeading":"Instance Method","role":"symbol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(magnifEyeLivenessViewControllerViewWillTransition:) "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController"},{"text":")","kind":"text"}]}]}],"sections":[],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilltransition(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilltransition(_:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate":{"deprecated":true,"title":"MagnifEyeLivenessViewControllerDelegate","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"title":"MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"type":"topic","role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewWillTransition(_:)":{"kind":"symbol","deprecated":true,"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillTransition(_:)","title":"magnifEyeLivenessViewControllerViewWillTransition(_:)","role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilltransition(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"magnifEyeLivenessViewControllerViewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"magnifEyeLivenessViewControllerViewWillTransition:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"deprecated":true,"unavailable":false}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"magnifEyeLivenessViewControllerViewWillTransition:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewWillTransition:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewWillTransition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/deprecationSummary","value":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFMagnifEyeLivenessViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/navigatorTitle"},{"op":"replace","value":"DOTFMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillTransition(_:)\/title","value":"magnifEyeLivenessViewControllerViewWillTransition:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillTransition(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewWillTransition:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}