{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/debugInfo","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"debugInfo","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","kind":"typeIdentifier","text":"DebugInfo"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/debuginfo"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:6DotNfc0B20TravelDocumentReaderC5ErrorC9debugInfoAA05DebugH0Cvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","text":"DebugInfo","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","title":"debugInfo","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"deprecated":false,"name":"iOS","introducedAt":"13.0","unavailable":false}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error"]]},"references":{"doc://DotNfc/documentation/DotNfc/DebugInfo":{"type":"topic","navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugInfo"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","title":"DebugInfo","url":"\/documentation\/dotnfc\/debuginfo","abstract":[]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error/debugInfo":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/debugInfo","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/debuginfo","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"debugInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","text":"DebugInfo","kind":"typeIdentifier"}],"title":"debugInfo"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error","title":"NfcTravelDocumentReader.Error","kind":"symbol","abstract":[{"text":"If reading fails due to any other reason.","type":"text"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","value":"DOTNDebugInfo"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNDebugInfo"}]},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}