{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"confidence"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)DOTDetectionPosition","kind":"typeIdentifier","text":"DOTDetectionPosition"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"position"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceAspects:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","kind":"typeIdentifier","text":"DOTFFaceAspects"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceAspects"},{"kind":"text","text":" "},{"text":"faceQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceQuality"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passiveLivenessFaceAttribute:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"text":"passiveLivenessFaceAttribute","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fullFrontalBgrRawImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTBgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"fullFrontalBgrRawImage"},{"kind":"text","text":" "},{"text":"template:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","text":"DOTFTemplate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"template_","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:"}],"externalID":"c:@M@DotFaceCore@objc(cs)Face(im)initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","role":"symbol","navigatorTitle":[{"text":"initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/face\/initwithconfidence:position:faceaspects:facequality:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","title":"FaceQuality","kind":"symbol","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facequality","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"role":"symbol","kind":"symbol","title":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","fragments":[{"kind":"identifier","text":"Face"}],"type":"topic","url":"\/documentation\/dotfacecore\/face","abstract":[{"type":"text","text":"Detected face in the image."}]},"doc://DotFaceCore/documentation/DotFaceCore/Face/initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:":{"url":"\/documentation\/dotfacecore\/face\/initwithconfidence:position:faceaspects:facequality:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","fragments":[{"kind":"text","text":"- "},{"text":"initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:"}],"title":"initWithConfidence:position:faceAspects:faceQuality:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"navigatorTitle":[{"kind":"identifier","text":"Template"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Template","kind":"identifier"}],"title":"Template","abstract":[{"text":"Face template.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/template","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceaspects","role":"symbol","abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"title":"FaceAspects"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","title":"FaceAttribute","role":"symbol","type":"topic","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceattribute"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.6.0"}],"url":"\/documentation\/dotfacecore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"role":"symbol","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","type":"topic","url":"\/documentation\/dotfacecore\/bgrrawimage","kind":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title","value":"DOTFTemplate","op":"replace"},{"op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments"},{"value":"DOTFFaceAspects","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","op":"replace","value":"DOTFFaceAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"op":"replace","value":"DOTBgrRawImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments"}]}]}