{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/localization\/uselocalizationdictionary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/localization\/uselocalizationdictionary"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/useLocalizationDictionary"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"]]},"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Type Property","externalID":"c:@M@DotNfc@objc(cs)DOTNLocalization(cpy)useLocalizationDictionary","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"useLocalizationDictionary","navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}]},"abstract":[{"type":"text","text":"If you set this to "},{"type":"codeVoice","code":"true"},{"text":", ","type":"text"},{"type":"codeVoice","code":"localizationDictionary"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/Localization/useLocalizationDictionary":{"title":"useLocalizationDictionary","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/useLocalizationDictionary","url":"\/documentation\/dotnfc\/localization\/uselocalizationdictionary","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"If you set this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizationDictionary"},{"type":"text","text":" will be used to localize strings. Default value is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Localization":{"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization","title":"Localization","role":"symbol","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"url":"\/documentation\/dotnfc\/localization","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"useLocalizationDictionary","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"useLocalizationDictionary"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1useLocalizationDictionary\/title","value":"useLocalizationDictionary","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1useLocalizationDictionary\/fragments","value":[{"kind":"identifier","text":"useLocalizationDictionary"}],"op":"replace"},{"value":"DOTNLocalization","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/title","op":"replace"},{"value":[{"text":"DOTNLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNLocalization"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/navigatorTitle","op":"replace"}]}]}