{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/LogLevel-swift.enum","preciseIdentifier":"s:6DotNfc6LoggerC8LogLevelO","text":"LogLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/logger\/loglevel-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/logger\/loglevel-swift.type.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/logLevel-swift.type.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"role":"symbol","title":"logLevel","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"s:6DotNfc6LoggerC8LogLevelO"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DotNfcLogger(cpy)logLevel","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotNfcLoggerLogLevel":{"role":"symbol","title":"DotNfcLoggerLogLevel","fragments":[{"kind":"identifier","text":"DotNfcLoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLoggerLogLevel","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotnfcloggerloglevel"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger/LogLevel-swift.enum":{"role":"symbol","title":"Logger.LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/LogLevel-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/dotnfc\/logger\/loglevel-swift.enum"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger/logLevel-swift.type.property":{"role":"symbol","title":"logLevel","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"s:6DotNfc6LoggerC8LogLevelO"}],"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/logLevel-swift.type.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"url":"\/documentation\/dotnfc\/logger\/loglevel-swift.type.property"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger":{"role":"symbol","title":"Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"url":"\/documentation\/dotnfc\/logger"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"DotNfc provides a component for NFC reading which is easy to integrate into an iOS application. Supported documents are those which implement Machine Readable Travel Document (MRTD) standards as specified by International Civil Aviation Organization (ICAO)."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"logLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"logLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLoggerLogLevel","preciseIdentifier":"c:@M@DotNfc@E@DotNfcLoggerLogLevel","text":"DotNfcLoggerLogLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1logLevel-swift.type.property\/title","value":"logLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1logLevel-swift.type.property\/fragments","value":[{"kind":"identifier","text":"logLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger\/title","value":"DotNfcLogger"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger\/fragments","value":[{"kind":"identifier","text":"DotNfcLogger"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}