{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","kind":"relationships"}],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"DotDocumentLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"role":"symbol","symbolKind":"class","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","roleHeading":"Class"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotDocumentLibraryConfigurationModules) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode"],"generated":true,"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration"]]},"sections":[],"references":{"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","title":"barcode","abstract":[]},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration":{"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration","abstract":[{"type":"text","text":"Document library configuration."}],"title":"DotDocumentLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Document library module configuration."}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","title":"init(barcode:)","role":"symbol"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/title"},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/fragments"},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/navigatorTitle"}]}]}