{"topicSections":[{"generated":true,"anchor":"Operators","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/!=(_:_:)"],"title":"Operators"}],"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"DotFaceCore"}],"title":"Equatable Implementations","role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/Equatable-Implementations"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotpalmmoduleid\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmModuleId/!=(_:_:)":{"type":"topic","abstract":[],"title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/!=(_:_:)","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotpalmmoduleid\/!=(_:_:)"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmModuleId":{"abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotpalmmoduleid","title":"DotPalmModuleId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}