{"metadata":{"roleHeading":"Instance Method","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"DotFaceCore"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"role":"symbol","title":"hash(into:)"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotpalmmoduleid\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/hash(into:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/RawRepresentable-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotPalmModuleId/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/RawRepresentable-Implementations","url":"\/documentation\/dotfacecore\/dotpalmmoduleid\/rawrepresentable-implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmModuleId/hash(into:)":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"url":"\/documentation\/dotfacecore\/dotpalmmoduleid\/hash(into:)","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/hash(into:)","kind":"symbol","title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmModuleId":{"url":"\/documentation\/dotfacecore\/dotpalmmoduleid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId","type":"topic","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"title":"DotPalmModuleId"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}