{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId"]]},"metadata":{"symbolKind":"init","title":"init(rawValue:)","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"s:7DotCore0A12PalmModuleIdO8rawValueACSgSi_tcfc"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotpalmmoduleid\/init(rawvalue:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotPalmModuleId/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId\/init(rawValue:)","url":"\/documentation\/dotfacecore\/dotpalmmoduleid\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmModuleId":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"type":"topic","role":"symbol","title":"DotPalmModuleId","kind":"symbol","url":"\/documentation\/dotfacecore\/dotpalmmoduleid","abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmModuleId","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/title","op":"replace","value":"DotPalmModuleId"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmModuleId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}