{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/tiltangles\/pitch"]},{"paths":["\/documentation\/dotfacelite\/tiltangles\/pitch"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/pitch"},"abstract":[{"type":"text","text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(py)pitch","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pitch"}],"roleHeading":"Instance Property","title":"pitch"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"url":"\/documentation\/dotfacelite\/tiltangles","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","kind":"symbol","title":"TiltAngles","abstract":[{"text":"Tilt angles.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TiltAngles"}],"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}]},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","type":"link","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles/pitch":{"kind":"symbol","title":"pitch","navigatorTitle":[{"text":"pitch","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/pitch","url":"\/documentation\/dotfacelite\/tiltangles\/pitch","abstract":[{"type":"text","text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees."}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pitch","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"pitch"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1pitch\/title","value":"pitch","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1pitch\/fragments","value":[{"kind":"identifier","text":"pitch"}]}]}]}