{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@CM@DotDocument@objc(cs)DOTPointDouble(im)mirrored","title":"mirrored()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/pointdouble\/mirrored()"]},{"paths":["\/documentation\/dotdocument\/pointdouble\/mirrored()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/mirrored()"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"text":"() -> ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"}]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/mirrored()":{"abstract":[],"type":"topic","title":"mirrored()","url":"\/documentation\/dotdocument\/pointdouble\/mirrored()","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/mirrored()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble":{"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"type":"topic","title":"PointDouble","url":"\/documentation\/dotdocument\/pointdouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.3.0"}],"title":"DotDocument","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mirrored","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","text":"DOTPointDouble"},{"text":" *) ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1mirrored()\/title","value":"mirrored","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1mirrored()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}