{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/Equatable-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/!=(_:_:)"]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/!=(_:_:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCore@E@DotFaceModuleId","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"DotNfc"}],"symbolKind":"op","roleHeading":"Operator"},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/!=(_:_:)":{"url":"\/documentation\/dotnfc\/dotfacemoduleid\/!=(_:_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/!=(_:_:)","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"title":"DotFaceModuleId","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotfacemoduleid","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}]},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/Equatable-Implementations":{"url":"\/documentation\/dotnfc\/dotfacemoduleid\/equatable-implementations","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","kind":"article","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle","value":[{"text":"DotFaceModuleId","kind":"identifier"}]}]}]}