{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/backgroundUniformity","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/backgrounduniformity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/backgrounduniformity"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"DotFaceModuleId.backgroundUniformity","role":"symbol","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdBackgroundUniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"modules":[{"name":"DotNfc"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"title":"DotFaceModuleId","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"url":"\/documentation\/dotnfc\/dotfacemoduleid","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/backgroundUniformity":{"url":"\/documentation\/dotnfc\/dotfacemoduleid\/backgrounduniformity","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/backgroundUniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"type":"topic","title":"DotFaceModuleId.backgroundUniformity","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceModuleIdBackgroundUniformity","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title","op":"replace","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle"},{"value":"DotFaceModuleIdBackgroundUniformity","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1backgroundUniformity\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1backgroundUniformity\/fragments"}]}]}