{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/detectionbalanced"]},{"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/detectionbalanced"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionBalanced","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"detectionBalanced","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"sections":[],"metadata":{"title":"DotFaceModuleId.detectionBalanced","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionBalanced"}],"externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdDetectionBalanced","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"symbolKind":"case"},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/detectionBalanced":{"title":"DotFaceModuleId.detectionBalanced","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detectionBalanced","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotfacemoduleid\/detectionbalanced","type":"topic","navigatorTitle":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionBalanced"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotfacemoduleid","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"title":"DotFaceModuleId","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","title":"DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 9.4.1"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFaceModuleIdDetectionBalanced","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFaceModuleIdDetectionBalanced","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1detectionBalanced\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1detectionBalanced\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}]},{"value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}