{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/eyeGazeLiveness"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/eyegazeliveness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/eyegazeliveness"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdEyeGazeLiveness","modules":[{"name":"DotNfc"}],"title":"DotFaceModuleId.eyeGazeLiveness"},"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"title":"DotFaceModuleId","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"url":"\/documentation\/dotnfc\/dotfacemoduleid"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/eyeGazeLiveness":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}],"title":"DotFaceModuleId.eyeGazeLiveness","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"eyeGazeLiveness","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/eyeGazeLiveness","url":"\/documentation\/dotnfc\/dotfacemoduleid\/eyegazeliveness"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFaceModuleIdEyeGazeLiveness","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle","op":"replace"},{"value":"DotFaceModuleIdEyeGazeLiveness","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1eyeGazeLiveness\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1eyeGazeLiveness\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}