{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/RawRepresentable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/rawrepresentable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"sections":[],"kind":"article","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/hashValue"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/hash(into:)"],"title":"Instance Methods","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"role":"symbol","title":"DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/dotfacemoduleid"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/hash(into:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/hash(into:)","type":"topic","title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"url":"\/documentation\/dotnfc\/dotfacemoduleid\/hash(into:)","abstract":[],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/hashValue":{"type":"topic","title":"hashValue","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"url":"\/documentation\/dotnfc\/dotfacemoduleid\/hashvalue","abstract":[],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle"}]}]}