{"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/verification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/verification"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotNfc"}],"title":"DotFaceModuleId.verification","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdVerification","role":"symbol","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}],"symbolKind":"case","navigatorTitle":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/verification","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"type":"topic","url":"\/documentation\/dotnfc\/dotfacemoduleid","title":"DotFaceModuleId","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}]},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/verification":{"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/dotfacemoduleid\/verification","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}],"title":"DotFaceModuleId.verification","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/verification","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceModuleIdVerification","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title","value":"DotFaceModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1verification\/title","value":"DotFaceModuleIdVerification","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1verification\/fragments","value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}