{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary\/deinitialize()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibrary\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibrary\/deinitialize()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary"]]},"metadata":{"required":true,"title":"deinitialize()","externalID":"c:@M@DotFaceCore@objc(pl)DotLibrary(im)deinitializeAndReturnError:","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary":{"url":"\/documentation\/dotfacecore\/dotlibrary","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary/deinitialize()":{"type":"topic","title":"deinitialize()","required":true,"kind":"symbol","url":"\/documentation\/dotfacecore\/dotlibrary\/deinitialize()","role":"symbol","abstract":[],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary\/deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deinitializeAndReturnError:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary~1deinitialize()\/title","op":"replace","value":"deinitializeAndReturnError:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary~1deinitialize()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}