{"metadata":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"required":true,"symbolKind":"property","title":"id","externalID":"c:@M@DotFaceCore@objc(pl)DotLibrary(py)id","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotLibraryId","preciseIdentifier":"c:@M@DotFaceCore@E@DotLibraryId"}],"role":"symbol","modules":[{"name":"DotFaceCore"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibrary\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibrary\/id"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary\/id","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId","preciseIdentifier":"c:@M@DotFaceCore@E@DotLibraryId","text":"DotLibraryId"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary":{"url":"\/documentation\/dotfacecore\/dotlibrary","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibraryId":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId","title":"DotLibraryId","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotfacecore\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary/id":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary\/id","required":true,"type":"topic","title":"id","abstract":[],"url":"\/documentation\/dotfacecore\/dotlibrary\/id","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotLibraryId","preciseIdentifier":"c:@M@DotFaceCore@E@DotLibraryId"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"id","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"id"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotFaceCore@E@DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace"},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId\/fragments","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary~1id\/title","value":"id"},{"op":"replace","value":[{"kind":"identifier","text":"id"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary~1id\/fragments"}]}]}