{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/initialize(license:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibrary\/initialize(license:)"]},{"paths":["\/documentation\/dotfacecore\/dotlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"initialize(license:)","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(pl)DotLibrary(im)initializeWithLicense:error:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier","text":"DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"symbolKind":"method","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"required":true},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotlibrary","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary","abstract":[],"title":"DotLibrary"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary/initialize(license:)":{"title":"initialize(license:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier","text":"DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/initialize(license:)","required":true,"url":"\/documentation\/dotfacecore\/dotlibrary\/initialize(license:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initializeWithLicense:error:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeWithLicense:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<DotSdkLicenseProxyProtocol>","preciseIdentifier":"c:Qo@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"license"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace"},{"value":"initializeWithLicense:error:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1initialize(license:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1initialize(license:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}]}]}]}