{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/palm"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotlibraryid\/palm"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/palm"]}],"metadata":{"title":"DotLibraryId.palm","roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdPalm","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"]]},"abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/palm":{"url":"\/documentation\/dotfacecore\/dotlibraryid\/palm","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/palm","title":"DotLibraryId.palm","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palm"}],"role":"symbol","abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.0"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotlibraryid","kind":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdPalm"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"DotLibraryIdPalm","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1palm\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1palm\/fragments","value":[{"text":"DotLibraryIdPalm","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}