{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"facing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","text":"CameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewScaleType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType"},{"kind":"text","text":" = .fit, "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false, ","kind":"text"},{"text":"isPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = true)","kind":"text"}]}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"facing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"text":"previewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(im)initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","navigatorTitle":[{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"type":"topic","title":"CameraPreviewScaleType","kind":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/cameraconfiguration","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","kind":"symbol","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"title":"CameraConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"facing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","kind":"symbol","navigatorTitle":[{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}],"abstract":[],"title":"init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"kind":"symbol","type":"topic","title":"CameraFacing","url":"\/documentation\/dotfacelite\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","role":"symbol","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"facing"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"previewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isPreviewVisible"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/navigatorTitle"},{"op":"replace","value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/fragments"},{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}