{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"calculatePixelCount"}],"roleHeading":"Instance Method","role":"symbol","title":"calculatePixelCount()","symbolKind":"method","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)calculatePixelCount"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"]]},"abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/imagesize\/calculatepixelcount()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagesize\/calculatepixelcount()"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculatePixelCount()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageSize/calculatePixelCount()":{"navigatorTitle":[{"kind":"identifier","text":"calculatePixelCount"}],"type":"topic","url":"\/documentation\/dotdocument\/imagesize\/calculatepixelcount()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"calculatePixelCount","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[{"text":"Calculate the number of pixels of the image.","type":"text"}],"title":"calculatePixelCount()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/calculatePixelCount()"},"doc://DotDocument/documentation/DotDocument/ImageSize":{"abstract":[{"type":"text","text":"Image size in pixels."}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotdocument\/imagesize","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","role":"symbol","type":"topic","kind":"symbol","title":"ImageSize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"calculatePixelCount","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"calculatePixelCount"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"calculatePixelCount","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1calculatePixelCount()\/fragments","value":[{"kind":"text","text":"- "},{"text":"calculatePixelCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"}]}]}