{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/isEqual(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"externalID":"c:@M@DotCore@objc(cs)DOTCorners(im)isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"symbolKind":"method","title":"isEqual(_:)"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/corners\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/corners\/isequal(_:)"]}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Corners":{"url":"\/documentation\/dotpalmcore\/corners","title":"Corners","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Corners"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/isEqual(_:)":{"url":"\/documentation\/dotpalmcore\/corners\/isequal(_:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/isEqual(_:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"isEqual:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTCorners","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}