{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"The result of the document detection. Might be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" only if "},{"type":"codeVoice","code":"DocumentAutoCaptureViewController\/requestCapture()"},{"type":"text","text":" was used to get the result."}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/document","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"},{"kind":"text","text":"?"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"text":"Document","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"?","kind":"text"}],"title":"document","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult(py)document","navigatorTitle":[{"text":"document","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/document"]},{"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/document"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureresult","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","title":"DocumentAutoCaptureResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdetector","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentDetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"title":"DocumentDetector.Document","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Document"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","role":"symbol","kind":"symbol","abstract":[{"text":"Result of the document detection process.","type":"text"}],"fragments":[{"text":"DOTDDocumentDetectorDocument","kind":"identifier"}],"type":"topic","title":"DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/document":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"document"}],"abstract":[{"type":"text","text":"The result of the document detection. Might be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" only if "},{"code":"DocumentAutoCaptureViewController\/requestCapture()","type":"codeVoice"},{"type":"text","text":" was used to get the result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/document","role":"symbol","kind":"symbol","title":"document","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector"},{"text":".","kind":"text"},{"text":"Document","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureresult\/document"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"document"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"document","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","text":"DOTDDocumentDetectorDocument","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"document","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","op":"replace","value":"DOTDDocumentAutoCaptureResult"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1document\/title","value":"document","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1document\/fragments","op":"replace","value":[{"text":"document","kind":"identifier"}]}]}]}