{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd2"}],"externalID":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType@DOTTravelDocumentTypeTd2","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"td2"}],"symbolKind":"case","role":"symbol","title":"TravelDocumentType.td2","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"td2","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/traveldocumenttype\/td2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocumenttype\/td2"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td2"},"sections":[],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentType"}],"kind":"symbol","title":"TravelDocumentType","type":"topic","abstract":[{"text":"Travel document type according to ICAO Doc 9303 specification.","type":"text"}],"url":"\/documentation\/dotnfc\/traveldocumenttype","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/td2":{"navigatorTitle":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"td2","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttype\/td2","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td2","kind":"symbol","title":"TravelDocumentType.td2"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.7.1"}],"title":"DotNfc","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTTravelDocumentTypeTd2"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd2"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTTravelDocumentType","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/fragments","op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]},{"op":"replace","value":"DOTTravelDocumentTypeTd2","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td2\/title"},{"op":"replace","value":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td2\/fragments"}]}]}