{"variants":[{"paths":["\/documentation\/dotnfc\/traveldocumenttype\/td3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocumenttype\/td3"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}],"role":"symbol","title":"TravelDocumentType.td3","externalID":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType@DOTTravelDocumentTypeTd3","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"td3"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Case"},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td3","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td3","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentType":{"url":"\/documentation\/dotnfc\/traveldocumenttype","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentType"}],"title":"TravelDocumentType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/td3":{"navigatorTitle":[{"text":"DOTTravelDocumentTypeTd3","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td3","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttype\/td3","title":"TravelDocumentType.td3","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td3","kind":"identifier"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTTravelDocumentTypeTd3","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTTravelDocumentTypeTd3","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTTravelDocumentType","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/navigatorTitle","op":"replace"},{"value":"DOTTravelDocumentTypeTd3","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td3\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td3\/fragments","op":"replace"}]}]}