{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as a "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"object."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(ciImage:ciContext:)"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImageFactory"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"ciImage"},{"content":[{"type":"paragraph","inlineContent":[{"text":"CIContext.","type":"text"}]}],"name":"ciContext"}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" instance."}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotfacecore\/bgrrawimagefactory\/create(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/bgrrawimagefactory\/create(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImageFactory(cm)createWithCiImage:ciContext:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"title":"create(ciImage:ciContext:)","role":"symbol"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImageFactory/create(ciImage:ciContext:)":{"abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(ciImage:ciContext:)","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/bgrrawimagefactory\/create(ciimage:cicontext:)","title":"create(ciImage:ciContext:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/bgrrawimage","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImageFactory":{"title":"BgrRawImageFactory","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImageFactory","url":"\/documentation\/dotfacecore\/bgrrawimagefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"code":"BgrRawImage","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"DOTBgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage"},{"kind":"text","text":" *) "},{"text":"createWithCiImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":" *) ","kind":"text"},{"text":"ciImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ciContext:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":" *) ","kind":"text"},{"text":"ciContext","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments"},{"value":"DOTBgrRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"value":"DOTBgrRawImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImageFactory\/title"},{"op":"replace","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImageFactory\/fragments"}]}]}