{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"text":"?)","kind":"text"}],"externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:fingers:","title":"init(document:face:faceLite:nfc:palm:fingers:)"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration":{"title":"DotFingersLibraryConfiguration","role":"symbol","abstract":[{"text":"Fingers library configuration.","type":"text"}],"navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","kind":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","type":"topic","abstract":[{"text":"Palm library configuration.","type":"text"}],"title":"DotPalmLibraryConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries":{"title":"Libraries","kind":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","url":"\/documentation\/dotpalmcore\/libraries","type":"topic","abstract":[{"text":"Container for library configurations.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration","type":"topic","abstract":[{"type":"text","text":"Face library configuration."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLiteLibraryConfiguration":{"title":"DotFaceLiteLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLiteLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotfacelitelibraryconfiguration","type":"topic","abstract":[{"type":"text","text":"Face Lite library configuration."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/Libraries/init(document:face:faceLite:nfc:palm:fingers:)":{"title":"init(document:face:faceLite:nfc:palm:fingers:)","kind":"symbol","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)","url":"\/documentation\/dotpalmcore\/libraries\/init(document:face:facelite:nfc:palm:fingers:)","type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration","type":"topic","abstract":[{"text":"Document library configuration.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotNfcLibraryConfiguration":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"NFC library configuration."}],"navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotnfclibraryconfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"title":"DotNfcLibraryConfiguration"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocument:face:faceLite:nfc:palm:fingers:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceLite:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLiteLibraryConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceLite"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nfc"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palm"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","kind":"typeIdentifier","text":"DotFingersLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fingers"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/title","value":"Libraries","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/navigatorTitle","value":[{"text":"Libraries","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLiteLibraryConfiguration\/title","value":"DotFaceLiteLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLiteLibraryConfiguration\/fragments","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLiteLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/title","value":"initWithDocument:face:faceLite:nfc:palm:fingers:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}