{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","roleHeading":"Operator","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"!=(_:_:)","role":"symbol"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/!=(_:_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmmoduleid\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/Equatable-Implementations"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/Equatable-Implementations":{"type":"topic","kind":"article","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/equatable-implementations","abstract":[],"role":"collectionGroup"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"kind":"symbol","title":"DotPalmModuleId","type":"topic","url":"\/documentation\/dotdocument\/dotpalmmoduleid","role":"symbol","abstract":[{"code":"DotPalm","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/!=(_:_:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotdocument\/dotpalmmoduleid\/!=(_:_:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/!=(_:_:)","title":"!=(_:_:)","abstract":[]}},"variantOverrides":[{"patch":[{"value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/title","op":"replace"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/fragments","op":"replace"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}