{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"modules":[{"name":"DotDocument"}],"role":"symbol","title":"DotPalmModuleId.detection","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@DotCore@E@DotPalmModuleId@DotPalmModuleIdDetection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotpalmmoduleid\/detection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotpalmmoduleid\/detection"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/detection","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/detection":{"url":"\/documentation\/dotdocument\/dotpalmmoduleid\/detection","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/detection","title":"DotPalmModuleId.detection"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId":{"title":"DotPalmModuleId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module identifier.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"url":"\/documentation\/dotdocument\/dotpalmmoduleid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotPalmModuleIdDetection","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotPalmModuleIdDetection","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId~1detection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId~1detection\/fragments"},{"op":"replace","value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/title"},{"op":"replace","value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/fragments"},{"op":"replace","value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/navigatorTitle"}]}]}