{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/RawRepresentable-Implementations"]]},"metadata":{"modules":[{"name":"DotDocument","relatedModules":["Swift"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","title":"hashValue","roleHeading":"Instance Property","symbolKind":"property","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"role":"symbol","extendedModule":"Swift"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/hashValue","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmmoduleid\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/hashValue":{"title":"hashValue","kind":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotdocument\/dotpalmmoduleid\/hashvalue","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/hashValue","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/RawRepresentable-Implementations","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId":{"url":"\/documentation\/dotdocument\/dotpalmmoduleid","kind":"symbol","role":"symbol","title":"DotPalmModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","type":"topic","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/navigatorTitle","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}]}]}