{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/hash(into:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotpalmmoduleid\/hash(into:)"]}],"metadata":{"title":"hash(into:)","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","extendedModule":"Swift","roleHeading":"Instance Method","symbolKind":"method","modules":[{"relatedModules":["Swift"],"name":"DotDocument"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/RawRepresentable-Implementations"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotPalmModuleId":{"role":"symbol","title":"DotPalmModuleId","type":"topic","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotpalmmoduleid","abstract":[{"code":"DotPalm","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/hash(into:)":{"title":"hash(into:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/hash(into:)","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/hash(into:)","type":"topic","abstract":[],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/RawRepresentable-Implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/navigatorTitle","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}]}]}