{"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/!=(_:_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervalfloat\/error\/!=(_:_:)"]}],"sections":[],"metadata":{"extendedModule":"Swift","title":"!=(_:_:)","symbolKind":"op","roleHeading":"Operator","modules":[{"relatedModules":["Swift"],"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/Equatable-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/Equatable-Implementations","abstract":[],"url":"\/documentation\/dotnfc\/intervalfloat\/error\/equatable-implementations","role":"collectionGroup","type":"topic","title":"Equatable Implementations"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","url":"\/documentation\/dotnfc\/intervalfloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalFloat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error":{"abstract":[],"title":"IntervalFloat.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/intervalfloat\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/!=(_:_:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/!=(_:_:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat\/error\/!=(_:_:)","title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}