{"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/errorDescription","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/failureReason","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/helpAnchor","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/recoverySuggestion"]}],"metadata":{"modules":[{"name":"DotNfc"}],"role":"collectionGroup","title":"LocalizedError Implementations","roleHeading":"API Collection"},"kind":"article","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/LocalizedError-Implementations"},"variants":[{"paths":["\/documentation\/dotnfc\/intervalfloat\/error\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/helpAnchor":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"helpAnchor","url":"\/documentation\/dotnfc\/intervalfloat\/error\/helpanchor","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/helpAnchor"},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","url":"\/documentation\/dotnfc\/intervalfloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalFloat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/recoverySuggestion":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/recoverySuggestion","url":"\/documentation\/dotnfc\/intervalfloat\/error\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","title":"recoverySuggestion","type":"topic","abstract":[],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/failureReason":{"type":"topic","title":"failureReason","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/intervalfloat\/error\/failurereason","kind":"symbol","role":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error":{"abstract":[],"title":"IntervalFloat.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/intervalfloat\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/errorDescription":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"errorDescription","url":"\/documentation\/dotnfc\/intervalfloat\/error\/errordescription","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/errorDescription"}},"variantOverrides":[{"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}