{"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointerPacked","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BgraRawImage"],["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BgraRawImage"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/bgrarawimage\/bytespointerpacked"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimage\/bytespointerpacked"]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointerPacked"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bytesPointerPacked"}],"symbolKind":"property","title":"bytesPointerPacked","roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DOTBgraRawImage(py)bytesPointerPacked","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointerPacked","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":">","kind":"text"}],"modules":[{"name":"DotPalmCore"}]},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BgraRawImage":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"title":"BgraRawImage","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BgraRawImage"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BgraRawImage/bytesPointerPacked":{"role":"symbol","navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}],"abstract":[],"title":"bytesPointerPacked","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage\/bytespointerpacked","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointerPacked"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt32","preciseIdentifier":"s:s6UInt32V"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointerPacked"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmDetector":{"kind":"symbol","title":"PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmDetector","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bytesPointerPacked","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"bytesPointerPacked","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"uint32_t","preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bytesPointerPacked","kind":"identifier"}]}]}},{"op":"replace","value":"DOTBgraRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BgraRawImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BgraRawImage~1bytesPointerPacked\/title","value":"bytesPointerPacked","op":"replace"},{"value":[{"text":"bytesPointerPacked","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BgraRawImage~1bytesPointerPacked\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}