{"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"title":"dependencyIdentifiers","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSizeTooLargeValidator(py)dependencyIdentifiers","symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/dependencyIdentifiers"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/dependencyIdentifiers":{"title":"dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/dependencyidentifiers","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/dependencyIdentifiers"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"title":"SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"abstract":[{"type":"text","text":"Validate whether the size of the detected fingers is too large."}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"dependencyIdentifiers","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1dependencyIdentifiers\/title"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1dependencyIdentifiers\/fragments"},{"value":"DOTFGSizeTooLargeValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle"}]}]}