{"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","symbolKind":"class","title":"PalmAutoCaptureQualityAttributeThresholds.Builder","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"role":"symbol"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/init()"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/brightnessInterval(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/build()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/minConfidence(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/minSharpness(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/minTemplateExtractionQuality(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)"],"generated":true,"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"title":"PalmAutoCaptureQualityAttributeThresholds","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/build()":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/build()","title":"build()","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/build()","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"build","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds","text":"PalmAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"}],"abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/minConfidence(_:)":{"title":"minConfidence(_:)","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/minconfidence(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/minConfidence(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"title":"PalmAutoCaptureQualityAttributeThresholds.Builder","kind":"symbol","navigatorTitle":[{"text":"Builder","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/minTemplateExtractionQuality(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minTemplateExtractionQuality"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/minTemplateExtractionQuality(_:)","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/mintemplateextractionquality(_:)","title":"minTemplateExtractionQuality(_:)","kind":"symbol","type":"topic","role":"symbol"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/minSharpness(_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/minSharpness(_:)","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/minsharpness(_:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSharpness"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"title":"minSharpness(_:)","kind":"symbol"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/init()":{"title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/init()","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/init()","role":"symbol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/sizeInterval(_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/sizeinterval(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"text":"(","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"abstract":[],"role":"symbol","title":"sizeInterval(_:)","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder/brightnessInterval(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessInterval"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder\/brightnessinterval(_:)","kind":"symbol","type":"topic","title":"brightnessInterval(_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder\/brightnessInterval(_:)","role":"symbol","abstract":[]},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","value":"DOTPPalmAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholds"}]}]}]}