{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceNotDetectedValidator(cpy)defaultMinConfidenceThreshold","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"modules":[{"name":"DotFaceLite"}],"title":"defaultMinConfidenceThreshold","role":"symbol","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/defaultMinConfidenceThreshold"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Default threshold value."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/defaultminconfidencethreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/defaultminconfidencethreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/defaultMinConfidenceThreshold":{"role":"symbol","title":"defaultMinConfidenceThreshold","kind":"symbol","abstract":[{"type":"text","text":"Default threshold value."}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/defaultMinConfidenceThreshold","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/defaultminconfidencethreshold","navigatorTitle":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceNotDetectedValidator"}],"title":"FaceNotDetectedValidator","abstract":[{"type":"text","text":"Validates confidence of the detected face."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"defaultMinConfidenceThreshold","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinConfidenceThreshold"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"defaultMinConfidenceThreshold","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1defaultMinConfidenceThreshold\/title"},{"op":"replace","value":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1defaultMinConfidenceThreshold\/fragments"},{"op":"replace","value":"DOTFLFaceNotDetectedValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title"},{"op":"replace","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/navigatorTitle"},{"op":"replace","value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}