{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator"]]},"sections":[],"metadata":{"symbolKind":"property","title":"dependencyIdentifiers","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceNotDetectedValidator(py)dependencyIdentifiers","modules":[{"name":"DotFaceLite"}]},"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/dependencyidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/dependencyidentifiers"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/dependencyIdentifiers":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"title":"dependencyIdentifiers","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/dependencyidentifiers","type":"topic","kind":"symbol","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/dependencyIdentifiers","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.12.0"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"abstract":[{"type":"text","text":"Validates confidence of the detected face."}],"kind":"symbol","navigatorTitle":[{"text":"FaceNotDetectedValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceNotDetectedValidator"}],"type":"topic","title":"FaceNotDetectedValidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","role":"symbol","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"dependencyIdentifiers","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"value":"DOTFLFaceNotDetectedValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}]}]}]}