{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceNotDetectedValidator(py)minConfidenceThreshold","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","title":"minConfidenceThreshold","navigatorTitle":[{"text":"minConfidenceThreshold","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/minconfidencethreshold"]},{"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/minconfidencethreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Current minimal accepted confidence."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/minConfidenceThreshold"},"sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceNotDetectedValidator":{"navigatorTitle":[{"text":"FaceNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","abstract":[{"text":"Validates confidence of the detected face.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceNotDetectedValidator","kind":"identifier"}],"kind":"symbol","title":"FaceNotDetectedValidator","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceNotDetectedValidator/minConfidenceThreshold":{"abstract":[{"type":"text","text":"Current minimal accepted confidence."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/minConfidenceThreshold","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/minconfidencethreshold","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minConfidenceThreshold"}],"title":"minConfidenceThreshold","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.4.1"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"kind":"symbol","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"minConfidenceThreshold","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minConfidenceThreshold"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"minConfidenceThreshold","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title","op":"replace","value":"DOTFLFaceNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}]},{"value":"minConfidenceThreshold","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1minConfidenceThreshold\/title"},{"value":[{"text":"minConfidenceThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1minConfidenceThreshold\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"}]}]}