{"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"text","text":".standard"},{"type":"text","text":" preset."}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":" * "},{"kind":"identifier","text":"qualityAttributeThresholds"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"qualityAttributeThresholds","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"qualityAttributeThresholds"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureConfiguration(py)qualityAttributeThresholds","roleHeading":"Instance Property","title":"qualityAttributeThresholds"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration\/qualityattributethresholds"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration\/qualityAttributeThresholds"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","title":"DOTFLBaseFaceAutoCaptureConfiguration","url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"fragments":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureConfiguration"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds":{"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","kind":"symbol","title":"FaceAutoCaptureQualityAttributeThresholds","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 9.2.3"}],"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration/qualityAttributeThresholds":{"fragments":[{"text":"qualityAttributeThresholds","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration\/qualityAttributeThresholds","url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration\/qualityattributethresholds","title":"qualityAttributeThresholds","abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"text","text":".standard"},{"type":"text","text":" preset."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFLFaceAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}