{"metadata":{"externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO39invalidCandidateSelectionDurationMillisyA2EmF","symbolKind":"case","roleHeading":"Case","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCandidateSelectionDurationMillis"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/invalidCandidateSelectionDurationMillis":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCandidateSelectionDurationMillis"}],"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration","title":"AutoCaptureConfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error","title":"AutoCaptureConfiguration.Error","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}