{"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error\/composeWithInternalError()"],"title":"Instance Methods"}],"metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","roleHeading":"API Collection","title":"DotSdkError Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error\/DotSdkError-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervalfloat\/error\/dotsdkerror-implementations"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/IntervalFloat/Error":{"abstract":[],"title":"IntervalFloat.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/intervalfloat\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/IntervalFloat/Error/composeWithInternalError()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotdocument\/intervalfloat\/error\/composewithinternalerror()","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error\/composeWithInternalError()","abstract":[],"type":"topic","kind":"symbol","title":"composeWithInternalError()"},"doc://DotDocument/documentation/DotDocument/IntervalFloat":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotdocument\/intervalfloat","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","kind":"symbol","title":"IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/title","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}