{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLiteLibraryConfiguration\/init","interfaceLanguage":"occ"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"init","externalID":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacelitelibraryconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLiteLibraryConfiguration"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLiteLibraryConfiguration":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLiteLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFaceLiteLibraryConfiguration","abstract":[{"text":"Face Lite library configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacelitelibraryconfiguration"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLiteLibraryConfiguration/init":{"url":"\/documentation\/dotfingerscore\/dotfacelitelibraryconfiguration\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLiteLibraryConfiguration\/init","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceLiteLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLiteLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLiteLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLiteLibraryConfiguration\/navigatorTitle"}]}]}