{"abstract":[{"type":"text","text":"JPEG2000 compressed image format"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg2000","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg2000"}],"roleHeading":"Case","title":"ImageFormat.jpeg2000","symbolKind":"case","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg2000"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg2000"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imageformat\/jpeg2000"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/imageformat\/jpeg2000"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat":{"title":"ImageFormat","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotfacecore\/imageformat","abstract":[{"type":"text","text":"Supported image formats."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/jpeg2000":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpeg2000"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg2000","url":"\/documentation\/dotfacecore\/imageformat\/jpeg2000","abstract":[{"type":"text","text":"JPEG2000 compressed image format"}],"role":"symbol","title":"ImageFormat.jpeg2000","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTImageFormatJpeg2000","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFormat","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/title"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/fragments"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/navigatorTitle"},{"value":"DOTImageFormatJpeg2000","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg2000\/title"},{"value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg2000\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}