{"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/id"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"]]},"abstract":[{"type":"text","text":"The library identifier."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibraryId","text":"DotLibraryId","preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/id","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","navigatorTitle":[{"text":"id","kind":"identifier"}],"title":"id","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DotFaceLiteLibrary(py)id"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotFaceLiteLibrary/id":{"url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/id","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}],"title":"id","abstract":[{"type":"text","text":"The library identifier."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/id","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotLibraryId":{"role":"symbol","title":"DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibraryId","url":"\/documentation\/dotfacelite\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.4.1"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotFaceLiteLibrary":{"abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotFaceLite","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLiteLibrary"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceLiteLibrary","kind":"identifier"}],"title":"DotFaceLiteLibrary","url":"\/documentation\/dotfacelite\/dotfacelitelibrary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibraryId","text":"DotLibraryId","preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1id\/title","value":"id","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibraryId\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title","value":"DotFaceLiteLibrary","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments","value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}]}]}]}