{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/init()"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}]}]}],"metadata":{"roleHeading":"Initializer","externalID":"c:@M@DotFaceLite@objc(cs)DotFaceLiteLibrary(im)init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"init","title":"init()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/init()"]},{"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary/init()":{"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/init()","title":"init()","role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/init()"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfacelitelibrary","title":"DotFaceLiteLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotFaceLite","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceLiteLibrary","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 8.15.0","type":"text"}],"type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"init","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1init()\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"value":"DotFaceLiteLibrary","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title","op":"replace"},{"op":"replace","value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments"}]}]}