{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"abstract":[{"text":"The result returned from the processing of one image during the palm auto capture process.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureControllerProcessingResult) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/detection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/phase","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/result"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC","modules":[{"name":"DotPalmCore"}],"title":"PalmAutoCaptureController.ProcessingResult","navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult/detection":{"abstract":[{"type":"text","text":"The result of processing image during the palm auto capture process."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/detection","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/detection","title":"detection","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult/result":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/result","kind":"symbol","title":"result","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/result","abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"type":"topic"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"title":"PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult/phase":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/phase","kind":"symbol","abstract":[{"type":"text","text":"Current phase of the palm auto capture process."}],"type":"topic","role":"symbol","title":"phase","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/phase","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase"}]},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult/init(detection:result:phase:)":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/init(detection:result:phase:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","title":"init(detection:result:phase:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"text":"?, ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase"},{"text":")","kind":"text"}]},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"title":"PalmAutoCaptureController.ProcessingResult","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","type":"topic","abstract":[{"type":"text","text":"The result returned from the processing of one image during the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult","navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}]},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}