{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/imagesize\/shorterside"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/imagesize\/shorterside"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/shorterSide"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"externalID":"c:@CM@DotCore@objc(cs)DOTImageSize(py)shorterSide","extendedModule":"DotCore","navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"symbolKind":"property","title":"shorterSide"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/shorterSide":{"abstract":[],"kind":"symbol","title":"shorterSide","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/shorterSide","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfacecore\/imagesize\/shorterside","navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"title":"ImageSize","kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotfacecore\/imagesize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shorterSide"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"shorterSide"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1shorterSide\/title","value":"shorterSide"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1shorterSide\/fragments","value":[{"kind":"identifier","text":"shorterSide"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}]}]}]}