{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"]]},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minConfidence","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Minimal valid confidence of the detected document.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Value 0.0 represents low confidence."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high confidence."}],"metadata":{"symbolKind":"property","title":"minConfidence","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC13minConfidence0A4Core13WrappedDoubleCSgvp","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/minconfidence"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"title":"WrappedDouble","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotdocument\/wrappeddouble"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/minConfidence":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"kind":"text","text":": "},{"text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"minConfidence","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minConfidence","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/minconfidence","type":"topic","abstract":[{"type":"text","text":"Minimal valid confidence of the detected document."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low confidence."},{"text":" ","type":"text"},{"type":"text","text":"Vaue 1.0 represents high confidence."}],"role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"QualityAttributeThresholds"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"title":"DocumentAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"title":"DocumentAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTWrappedDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace"}]}]}