{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/!=(_:_:)"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/Equatable-Implementations"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/!=(_:_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"extendedModule":"Swift","title":"!=(_:_:)","symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotDocumentCommons@E@DOTTravelDocumentType","roleHeading":"Operator","modules":[{"relatedModules":["Swift"],"name":"DotDocument"}],"role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument/TravelDocumentType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/dotdocument\/traveldocumenttype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/Equatable-Implementations","kind":"article"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"type":"topic","title":"MrzReader"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}],"title":"TravelDocumentType","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttype","type":"topic","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/!=(_:_:)":{"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/!=(_:_:)","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/dotdocument\/traveldocumenttype\/!=(_:_:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"value":"DOTTravelDocumentType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]}]}]}