{"kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/common"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration"]]},"metadata":{"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessConfiguration(py)common","navigatorTitle":[{"kind":"identifier","text":"common"}],"symbolKind":"property","title":"common","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"common"}],"modules":[{"name":"DotFaceCore"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/common"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","text":"DOTCommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" * ","kind":"text"},{"text":"common","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration":{"url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration","abstract":[{"text":"Configuration options for the UI Smile Liveness component.","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"DOTFSmileLivenessConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration","type":"topic","kind":"symbol","title":"DOTFSmileLivenessConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"kind":"symbol","type":"topic","title":"CommonConfiguration","url":"\/documentation\/dotfacecore\/commonconfiguration","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration/common":{"kind":"symbol","title":"common","url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/common","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"fragments":[{"text":"common","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/common","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle"}]}]}