{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotlibraryid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotlibraryid"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH","doc:\/\/com.innovatrics.dot.document\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"title":"DotLibraryId","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DotDocument@E@DotLibraryId","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/document","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/face","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/faceLite","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/nfc"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId":{"role":"symbol","title":"DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotdocument\/dotlibraryid"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotdocument\/dotlibraryid\/equatable-implementations"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/nfc":{"role":"symbol","title":"DotLibraryId.nfc","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc"}],"abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"type":"text","text":" identifier."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/nfc","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdNfc"}],"url":"\/documentation\/dotdocument\/dotlibraryid\/nfc"},"doc://com.innovatrics.dot.document/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.document\/SY"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotdocument\/dotlibraryid\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotlibraryid\/init(rawvalue:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/document":{"role":"symbol","title":"DotLibraryId.document","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"type":"text","text":" identifier."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/document","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"url":"\/documentation\/dotdocument\/dotlibraryid\/document"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotlibraryid\/description"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/face":{"role":"symbol","title":"DotLibraryId.face","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"}],"abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" identifier."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/face","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFace"}],"url":"\/documentation\/dotdocument\/dotlibraryid\/face"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId/faceLite":{"role":"symbol","title":"DotLibraryId.faceLite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"}],"abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"type":"text","text":" identifier."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/faceLite","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"url":"\/documentation\/dotdocument\/dotlibraryid\/facelite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/document","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/face","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/faceLite","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId\/nfc"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1nfc\/title","value":"DotLibraryIdNfc"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1nfc\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdNfc"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1document\/title","value":"DotLibraryIdDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1document\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1face\/title","value":"DotLibraryIdFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1face\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1faceLite\/title","value":"DotLibraryIdFaceLite"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId~1faceLite\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}