{"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"FaceAutoCapturePreview","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:11DotFaceCore0B18AutoCaptureUiStateC4IdleC7previewAE0aB7Commons0bdE7PreviewC_tcfc","modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"init(preview:)","symbolKind":"init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate\/idle\/init(preview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle\/init(preview:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","kind":"typeIdentifier","text":"FaceAutoCapturePreview"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturepreview","title":"FaceAutoCapturePreview","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}],"abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Idle/init(preview:)":{"title":"init(preview:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle\/init(preview:)","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/idle\/init(preview:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"FaceAutoCapturePreview","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"title":"FaceAutoCaptureUiState","navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Idle":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Idle","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/idle","abstract":[{"text":"Idle state.","type":"text"}],"role":"symbol","type":"topic","title":"FaceAutoCaptureUiState.Idle","navigatorTitle":[{"text":"Idle","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFaceAutoCapturePreview","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace"},{"value":"DOTFFaceAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]}]}]}