{"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration(im)init","symbolKind":"method","roleHeading":"Instance Method","title":"init","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfaceeyegazelivenessmoduleconfiguration\/init"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceEyeGazeLivenessModuleConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfaceeyegazelivenessmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration","title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceEyeGazeLivenessModuleConfiguration/init":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfaceeyegazelivenessmoduleconfiguration\/init"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}