{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"defaultThreshold","roleHeading":"Type Property","externalID":"c:@M@DotDocument@objc(cs)DOTDSharpnessTooLowValidator(cpy)defaultThreshold","modules":[{"name":"DotDocument"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"symbolKind":"property","role":"symbol"},"abstract":[{"text":"Default threshold is 0.65.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/defaultThreshold"},"references":{"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/defaultThreshold":{"navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"abstract":[{"text":"Default threshold is 0.65.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/defaultThreshold","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/defaultthreshold","kind":"symbol","title":"defaultThreshold","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"abstract":[{"text":"Validate minimum sharpness of the detected document.","type":"text"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","role":"symbol","title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"defaultThreshold","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultThreshold","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"}]}],"kind":"declarations"}},{"value":"defaultThreshold","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1defaultThreshold\/title","op":"replace"},{"op":"replace","value":[{"text":"defaultThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1defaultThreshold\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"value":"DOTDSharpnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments"}]}]}