{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyeinnercorner"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyeinnercorner"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"FaceFeature.leftEyeInnerCorner","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeInnerCorner"}],"navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyeInnerCorner","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureLeftEyeInnerCorner"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/leftEyeInnerCorner"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftEyeInnerCorner","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature/leftEyeInnerCorner":{"title":"FaceFeature.leftEyeInnerCorner","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"leftEyeInnerCorner"}],"url":"\/documentation\/dotfacecore\/facefeature\/lefteyeinnercorner","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyeInnerCorner","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/leftEyeInnerCorner","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.9.0","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"abstract":[{"type":"text","text":"Available face features."}],"title":"FaceFeature","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeature"}],"navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"role":"symbol","url":"\/documentation\/dotfacecore\/facefeature"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceFeatureLeftEyeInnerCorner"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFFaceFeatureLeftEyeInnerCorner","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyeInnerCorner"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1leftEyeInnerCorner\/title","value":"DOTFFaceFeatureLeftEyeInnerCorner","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyeInnerCorner"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1leftEyeInnerCorner\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title","op":"replace","value":"DOTFFaceFeature"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}