{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpplaceholdervisible"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPlaceholderVisible"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"DOTPPlaceholder","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholder"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Visible placeholder.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder"],"title":"Inherits From","type":"inheritsFrom"}],"sections":[],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholderVisible","symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"DOTPPlaceholderVisible","kind":"identifier"}],"title":"DOTPPlaceholderVisible","modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","fragments":[{"text":"DOTPPlaceholderVisible","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible"},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/type"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/initWithType:","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/isEqual:"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible":{"url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible","fragments":[{"text":"DOTPPlaceholderVisible","kind":"identifier"}],"title":"DOTPPlaceholderVisible","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Visible placeholder."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible/initWithType:":{"navigatorTitle":[{"kind":"identifier","text":"initWithType:"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible\/initwithtype:","title":"initWithType:","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/initWithType:"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible/description":{"title":"description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/description","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"description"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible\/description"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible/hash":{"title":"hash","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/hash","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"hash"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible\/hash"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"url":"\/documentation\/dotpalmcore\/placeholder","role":"symbol","title":"Placeholder","type":"topic","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible/type":{"title":"type","url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible\/type","type":"topic","abstract":[{"text":"Placeholder type. Default is ","type":"text"},{"text":".left","type":"text"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/type","role":"symbol","fragments":[{"text":"type","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible/isEqual:":{"title":"isEqual:","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/isEqual:","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible\/isequal:"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTPPlaceholder","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title"},{"op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments"},{"op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}