{"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/dorsal","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/palmar"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/description"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPHandOrientation) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandOrientation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"enum","externalID":"c:@M@DotPalmCore@E@DOTPHandOrientation","roleHeading":"Enumeration","title":"HandOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HandOrientation"}],"navigatorTitle":[{"text":"HandOrientation","kind":"identifier"}]},"abstract":[{"type":"text","text":"Represents the orientation of a hand when detecting palm."}],"variants":[{"paths":["\/documentation\/dotpalmcore\/handorientation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/handorientation"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/RawRepresentable-Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/handorientation\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/Equatable-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/Equatable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/dotpalmcore\/handorientation\/equatable-implementations","title":"Equatable Implementations","type":"topic","kind":"article"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"kind":"symbol","navigatorTitle":[{"text":"HandOrientation","kind":"identifier"}],"type":"topic","role":"symbol","title":"HandOrientation","url":"\/documentation\/dotpalmcore\/handorientation","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","abstract":[{"text":"Represents the orientation of a hand when detecting palm.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandOrientation","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/description":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","title":"description","url":"\/documentation\/dotpalmcore\/handorientation\/description","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/description"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/init(rawValue:)":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/handorientation\/init(rawvalue:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/init(rawValue:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/palmar":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/palmar","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palmar","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/handorientation\/palmar","navigatorTitle":[{"text":"DOTPHandOrientationPalmar","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Palmar orientation."}],"title":"HandOrientation.palmar","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/dorsal":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dorsal"}],"url":"\/documentation\/dotpalmcore\/handorientation\/dorsal","title":"HandOrientation.dorsal","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/dorsal","abstract":[{"type":"text","text":"Dorsal orientation."}],"navigatorTitle":[{"kind":"identifier","text":"DOTPHandOrientationDorsal"}]},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SY"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"DOTPHandOrientation","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPHandOrientation"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPHandOrientation","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/dorsal","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/palmar"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPHandOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title","value":"DOTPHandOrientation","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPHandOrientation"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPHandOrientation"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/navigatorTitle","op":"replace"},{"value":"DOTPHandOrientationPalmar","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1palmar\/title","op":"replace"},{"value":[{"text":"DOTPHandOrientationPalmar","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1palmar\/fragments","op":"replace"},{"value":"DOTPHandOrientationDorsal","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1dorsal\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPHandOrientationDorsal"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation~1dorsal\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}