{"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/init(value:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/value"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}],"abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTWrappedFloat) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat","symbolKind":"class","title":"WrappedFloat","navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/wrappedfloat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/wrappedfloat"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat/init(value:)":{"url":"\/documentation\/dotpalmcore\/wrappedfloat\/init(value:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}],"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/init(value:)","kind":"symbol","title":"init(value:)","role":"symbol"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat/description":{"url":"\/documentation\/dotpalmcore\/wrappedfloat\/description","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/description","kind":"symbol","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat":{"role":"symbol","navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"kind":"symbol","title":"WrappedFloat","url":"\/documentation\/dotpalmcore\/wrappedfloat","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat/hash":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/hash","url":"\/documentation\/dotpalmcore\/wrappedfloat\/hash","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat/value":{"url":"\/documentation\/dotpalmcore\/wrappedfloat\/value","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/value","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"title":"value","navigatorTitle":[{"text":"value","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat/isEqual(_:)":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEqual(_:)","type":"topic","url":"\/documentation\/dotpalmcore\/wrappedfloat\/isequal(_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/isEqual(_:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/value"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/init(value:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTWrappedFloat","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1init(value:)\/title","value":"initWithValue:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1init(value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/navigatorTitle","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}