{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/autocaptureconfiguration\/error"]}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO","role":"symbol","title":"AutoCaptureConfiguration.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"modules":[{"name":"DotFingersCore"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration"]]},"kind":"symbol","sections":[],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/invalidMinValidSamplesInRowToStartCandidateSelection"],"title":"Enumeration Cases"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/errorMessage","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/internalError"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/Error-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/LocalizedError-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError","doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/s5ErrorP","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/s8SendableP","doc:\/\/DotFingersCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"platforms":["iOS"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"AutoCaptureConfiguration.Error","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/DotSdkError-Implementations":{"kind":"article","title":"DotSdkError Implementations","url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/dotsdkerror-implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/internalError":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/internalerror","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}],"title":"internalError","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/internalError"},"doc://DotFingersCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/DotFingersCore\/s8SendableP"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/invalidCandidateSelectionDurationMillis":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCandidateSelectionDurationMillis"}],"title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/Error-Implementations":{"title":"Error Implementations","kind":"article","url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/error-implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/Error-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/invalidMinValidSamplesInRowToStartCandidateSelection":{"kind":"symbol","title":"AutoCaptureConfiguration.Error.invalidMinValidSamplesInRowToStartCandidateSelection","url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/invalidminvalidsamplesinrowtostartcandidateselection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidMinValidSamplesInRowToStartCandidateSelection"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/invalidMinValidSamplesInRowToStartCandidateSelection"},"doc://DotFingersCore/s5ErrorP":{"identifier":"doc:\/\/DotFingersCore\/s5ErrorP","type":"unresolvable","title":"Swift.Error"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/DotFingersCore\/s16SendableMetatypeP","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/Equatable-Implementations":{"kind":"article","title":"Equatable Implementations","url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/equatable-implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/Equatable-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/LocalizedError-Implementations":{"abstract":[],"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/localizederror-implementations","role":"collectionGroup","title":"LocalizedError Implementations","type":"topic","kind":"article","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/LocalizedError-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/errorMessage":{"abstract":[],"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/errormessage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"errorMessage","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/errorMessage"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkError":{"kind":"symbol","title":"DotSdkError","url":"\/documentation\/dotfingerscore\/dotsdkerror","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError"},"doc://DotFingersCore/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","identifier":"doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/navigatorTitle"}]}]}