{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/passiveLiveness","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"}]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"case","title":"DotFaceModuleCategory.passiveLiveness","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"}],"navigatorTitle":[{"text":"DotFaceModuleCategoryPassiveLiveness","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DotFaceModuleCategory@DotFaceModuleCategoryPassiveLiveness","role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Case"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/passiveliveness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/passiveliveness"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/passiveLiveness":{"title":"DotFaceModuleCategory.passiveLiveness","url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/passiveliveness","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/passiveLiveness","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryPassiveLiveness"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.17.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodulecategory","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" module category."}],"title":"DotFaceModuleCategory","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceModuleCategoryPassiveLiveness"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleCategoryPassiveLiveness","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotFaceModuleCategoryPassiveLiveness"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1passiveLiveness\/title","value":"DotFaceModuleCategoryPassiveLiveness"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1passiveLiveness\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleCategoryPassiveLiveness"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","value":"DotFaceModuleCategory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","value":[{"text":"DotFaceModuleCategory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleCategory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}