{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModuleId","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"],"generated":true,"title":"DotFace modularization"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"externalID":"c:@M@DotFaceCore@E@DotFaceModuleId","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModuleId","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"DotFaceModuleId"},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"]}],"abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionFast","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/verification"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/description"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid"]}],"references":{"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/eyeGazeLiveness":{"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/eyegazeliveness","title":"DotFaceModuleId.eyeGazeLiveness","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/eyeGazeLiveness","navigatorTitle":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLiveness"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/detectionBalanced":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/detectionbalanced","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionBalanced","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"title":"DotFaceModuleId.detectionBalanced","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionBalanced"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/detectionFast":{"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/detectionfast","title":"DotFaceModuleId.detectionFast","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionFast","navigatorTitle":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detectionFast","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/Equatable-Implementations":{"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/equatable-implementations","title":"Equatable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/Equatable-Implementations","type":"topic","role":"collectionGroup"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/expressionNeutral":{"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/expressionneutral","title":"DotFaceModuleId.expressionNeutral","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/expressionNeutral","navigatorTitle":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expressionNeutral"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/verification":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/verification","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verification"}],"role":"symbol","type":"topic","title":"DotFaceModuleId.verification","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/verification","navigatorTitle":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/RawRepresentable-Implementations":{"kind":"article","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/backgroundUniformity":{"title":"DotFaceModuleId.backgroundUniformity","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/backgrounduniformity","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/backgroundUniformity","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/init(rawValue:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/init(rawValue:)","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/description":{"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/description","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/description","role":"symbol","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}],"title":"DotFaceModule","url":"\/documentation\/dotfacecore\/dotfacemodule","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModule"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotfacecore\/dotfacemoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"title":"DotFaceModuleId"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/passiveLiveness":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/passiveLiveness","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/passiveliveness","title":"DotFaceModuleId.passiveLiveness","abstract":[],"navigatorTitle":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemodulecategory","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModuleCategory","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" module category."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","title":"DotFaceModuleCategory","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotFaceModuleId","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionFast","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/verification"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"],"title":"DotFace modularization","generated":true}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"DotFaceModuleIdEyeGazeLiveness","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1eyeGazeLiveness\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1eyeGazeLiveness\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}]},{"op":"replace","value":"DotFaceModuleIdDetectionBalanced","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1detectionBalanced\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1detectionBalanced\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1detectionFast\/title","value":"DotFaceModuleIdDetectionFast"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1detectionFast\/fragments","value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1expressionNeutral\/title","value":"DotFaceModuleIdExpressionNeutral","op":"replace"},{"op":"replace","value":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1expressionNeutral\/fragments"},{"op":"replace","value":"DotFaceModuleIdVerification","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1verification\/title"},{"value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1verification\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1backgroundUniformity\/title","op":"replace","value":"DotFaceModuleIdBackgroundUniformity"},{"value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1backgroundUniformity\/fragments","op":"replace"},{"value":"DotFaceModule","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId","op":"replace"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1passiveLiveness\/title","value":"DotFaceModuleIdPassiveLiveness"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1passiveLiveness\/fragments","value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}]},{"op":"replace","value":"DotFaceModuleCategory","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","op":"replace","value":[{"text":"DotFaceModuleCategory","kind":"identifier"}]}]}]}