{"sections":[],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"text":"() -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(im)mirrored","extendedModule":"DotCore","title":"mirrored()","role":"symbol","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/corners\/mirrored()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/corners\/mirrored()"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/mirrored()"},"references":{"doc://DotNfc/documentation/DotNfc/Corners/mirrored()":{"url":"\/documentation\/dotnfc\/corners\/mirrored()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"abstract":[],"title":"mirrored()","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/mirrored()","kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Corners":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","title":"Corners","role":"symbol","url":"\/documentation\/dotnfc\/corners"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mirrored","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","text":"DOTCorners"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1mirrored()\/title","value":"mirrored"},{"value":[{"kind":"text","text":"- "},{"text":"mirrored","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1mirrored()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]}]}]}