{"abstract":[{"type":"text","text":"Head pose evaluation result"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/headPose","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"headPose","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"headPose","kind":"identifier"},{"kind":"text","text":": "},{"text":"HeadPose","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose"}],"title":"headPose","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality(py)headPose","modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headPose","kind":"identifier"},{"kind":"text","text":": "},{"text":"HeadPose","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facequality\/headpose"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facequality\/headpose"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"title":"FaceQuality","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/headPose":{"type":"topic","role":"symbol","title":"headPose","url":"\/documentation\/dotfacecore\/facequality\/headpose","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headPose","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose","text":"HeadPose"}],"abstract":[{"type":"text","text":"Head pose evaluation result"}],"navigatorTitle":[{"text":"headPose","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/headPose"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","role":"symbol","title":"HeadPose","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}],"abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"url":"\/documentation\/dotfacecore\/headpose","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"headPose","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"headPose","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFHeadPose","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"headPose"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1headPose\/title","value":"headPose"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1headPose\/fragments","op":"replace","value":[{"text":"headPose","kind":"identifier"}]},{"op":"replace","value":"DOTFHeadPose","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}