{"abstract":[{"type":"text","text":"Face image quality evaluation result."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/imageQuality"},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"imageQuality"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality(py)imageQuality","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","text":"FaceImageQuality","kind":"typeIdentifier"}],"title":"imageQuality"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceImageQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facequality\/imagequality"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facequality\/imagequality"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.6.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/imageQuality":{"navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Face image quality evaluation result."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/imageQuality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","text":"FaceImageQuality"}],"url":"\/documentation\/dotfacecore\/facequality\/imagequality","title":"imageQuality","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"title":"FaceQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"type":"topic","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"url":"\/documentation\/dotfacecore\/facequality","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceImageQuality","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceimagequality","title":"FaceImageQuality","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"imageQuality","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"imageQuality"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTFFaceImageQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"imageQuality"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"imageQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1imageQuality\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1imageQuality\/fragments","value":[{"kind":"identifier","text":"imageQuality"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"op":"replace","value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments"},{"value":"DOTFFaceImageQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}]}]}]}