{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wearables"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","text":"Wearables","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/wearables","interfaceLanguage":"swift"},"metadata":{"title":"wearables","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","navigatorTitle":[{"text":"wearables","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality(py)wearables","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"wearables","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables","text":"Wearables"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/facequality\/wearables"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facequality\/wearables"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Wearables evaluation result."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"title":"FaceQuality","kind":"symbol","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"url":"\/documentation\/dotfacecore\/facequality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"title":"Wearables","url":"\/documentation\/dotfacecore\/wearables","type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.2"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/wearables":{"navigatorTitle":[{"text":"wearables","kind":"identifier"}],"abstract":[{"text":"Wearables evaluation result.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/wearables","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"wearables","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Wearables","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables"}],"title":"wearables","type":"topic","url":"\/documentation\/dotfacecore\/facequality\/wearables","kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"wearables","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"wearables","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","text":"DOTFWearables","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"wearables","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFFaceQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","value":"DOTFWearables","op":"replace"},{"value":[{"text":"DOTFWearables","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1wearables\/title","value":"wearables","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1wearables\/fragments","value":[{"text":"wearables","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}