{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"DotPalmCore"}],"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detection14transformationAeA0ac15DetectionModuleE0C_AA0ac14TransformationjE0CSgtcfc","title":"init(detection:transformation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class":{"role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersLibraryConfiguration.Modules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersTransformationModuleConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersDetectionModuleConfiguration":{"role":"symbol","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","role":"symbol","abstract":[],"title":"init(detection:transformation:)","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFingersTransformationModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}