{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","interfaceLanguage":"swift"},"metadata":{"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC14transformationAA0ac20TransformationModuleE0CSgvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","title":"transformation","role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersTransformationModuleConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"title":"transformation","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class":{"role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersLibraryConfiguration.Modules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"}]}]}