{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/description","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/placeholder\/visible\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"symbolKind":"property","externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC11descriptionSSvp","title":"description"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible":{"navigatorTitle":[{"kind":"identifier","text":"Visible"}],"url":"\/documentation\/dotfacecore\/placeholder\/visible","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible","abstract":[{"type":"text","text":"Visible placeholder."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"title":"Placeholder.Visible","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/description","title":"description","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/placeholder\/visible\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotfacecore\/placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"title":"Placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title","value":"DOTPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholder"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle","value":[{"text":"DOTPlaceholder","kind":"identifier"}],"op":"replace"}]}]}