{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult\/content"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult(py)content","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"modules":[{"name":"DotFaceLite"}],"title":"content"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureresult\/content"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureresult\/content"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Binary content for server-side evaluation."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","url":"\/documentation\/dotfacelite\/faceautocaptureresult","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"kind":"symbol","type":"topic","title":"FaceAutoCaptureResult","navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureResult","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.6.0"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult/content":{"navigatorTitle":[{"text":"content","kind":"identifier"}],"title":"content","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult\/content","role":"symbol","abstract":[{"type":"text","text":"Binary content for server-side evaluation."}],"url":"\/documentation\/dotfacelite\/faceautocaptureresult\/content","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"content"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"content"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"content"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","value":"DOTFLFaceAutoCaptureResult"},{"value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments"},{"value":"DOTFLFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"op":"replace","value":"content","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult~1content\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult~1content\/fragments","value":[{"text":"content","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]}]}]}