{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/imageQuality","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","text":"PalmImageQuality"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"imageQuality","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality(py)imageQuality","roleHeading":"Instance Property","navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","text":"PalmImageQuality"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/palmquality\/imagequality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmquality\/imagequality"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"]]},"abstract":[{"text":"Image quality.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmQuality","kind":"identifier"}],"navigatorTitle":[{"text":"PalmQuality","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Palm quality.","type":"text"}],"title":"PalmQuality","url":"\/documentation\/dotpalmcore\/palmquality","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/imageQuality":{"navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/imageQuality","url":"\/documentation\/dotpalmcore\/palmquality\/imagequality","title":"imageQuality","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmImageQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Image quality."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmImageQuality"}],"title":"PalmImageQuality","abstract":[{"text":"Palm image quality.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","navigatorTitle":[{"kind":"identifier","text":"PalmImageQuality"}],"url":"\/documentation\/dotpalmcore\/palmimagequality","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"imageQuality"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"imageQuality"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPPalmImageQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","op":"replace","value":"DOTPPalmQuality"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments","op":"replace","value":[{"text":"DOTPPalmQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1imageQuality\/title","op":"replace","value":"imageQuality"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1imageQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"imageQuality"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/title","op":"replace","value":"DOTPPalmImageQuality"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmImageQuality"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmImageQuality","kind":"identifier"}]}]}]}