{"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/init(x:y:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt"]]},"metadata":{"symbolKind":"init","externalID":"c:@M@DotCore@objc(cs)DOTPointInt(im)initWithX:y:","navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(x:y:)","modules":[{"name":"DotPalmCore"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/pointint\/init(x:y:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/pointint\/init(x:y:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/init(x:y:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithX:y:","kind":"identifier"}],"title":"init(x:y:)","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/init(x:y:)","kind":"symbol","url":"\/documentation\/dotpalmcore\/pointint\/init(x:y:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt":{"url":"\/documentation\/dotpalmcore\/pointint","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"title":"PointInt","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithX:y:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithX:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"x"},{"text":" ","kind":"text"},{"text":"y:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"y","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"initWithX:y:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1init(x:y:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1init(x:y:)\/fragments"},{"op":"replace","value":"DOTPointInt","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/title"},{"op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/fragments"},{"op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/navigatorTitle"}]}]}