{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The 3 bytes of color image pixel:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0th byte: BB - blue"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"1st byte: GG - green"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2nd byte: RR - red"}]}]}]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgr","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"case","role":"symbol","title":"ImageFormat.rawBgr","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgr","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}]},"abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/imageformat\/rawbgr"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imageformat\/rawbgr"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","abstract":[{"text":"Supported image formats.","type":"text"}],"url":"\/documentation\/dotpalmcore\/imageformat","role":"symbol","type":"topic","kind":"symbol","title":"ImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ImageFormat","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/rawBgr":{"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgr","url":"\/documentation\/dotpalmcore\/imageformat\/rawbgr","title":"ImageFormat.rawBgr","type":"topic","abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rawBgr","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DOTImageFormatRawBgr","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","value":"DOTImageFormat"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments"},{"op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle"},{"op":"replace","value":"DOTImageFormatRawBgr","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgr\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgr\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"op":"replace"}]}]}