{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Error\/localizedDescription"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/error\/error-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Error\/Error-Implementations"},"sections":[],"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"Error Implementations","modules":[{"name":"DotFaceLite"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacelite\/facedetector"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Error":{"type":"topic","url":"\/documentation\/dotfacelite\/facedetector\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Error","abstract":[],"kind":"symbol","title":"FaceDetector.Error"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Error/localizedDescription":{"type":"topic","url":"\/documentation\/dotfacelite\/facedetector\/error\/localizeddescription","abstract":[],"kind":"symbol","role":"symbol","title":"localizedDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Error\/localizedDescription"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"op":"replace","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}