{"metadata":{"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","symbolKind":"property","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","title":"detection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/detection"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection"},"references":{"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Fingers library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/detection","kind":"symbol","title":"detection"},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"title":"DotFingersDetectionModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration":{"abstract":[{"type":"text","text":"Fingers library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","role":"symbol","title":"DotFingersLibraryConfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotFingersDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}