{"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"metadata":{"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detection14transformationAeA0ac15DetectionModuleE0C_AA0ac14TransformationjE0CSgtcfc","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?)","kind":"text"}],"symbolKind":"init","title":"init(detection:transformation:)","modules":[{"name":"DotNfc"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)","role":"symbol","abstract":[],"title":"init(detection:transformation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transformation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Fingers library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"title":"DotFingersDetectionModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration":{"abstract":[{"type":"text","text":"Fingers library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","role":"symbol","title":"DotFingersLibraryConfiguration","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","type":"topic","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","url":"\/documentation\/dotnfc\/dotfingerstransformationmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFingersDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFingersTransformationModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}