{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"transformation","externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC14transformationAA0ac20TransformationModuleE0CSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","type":"topic","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersTransformationModuleConfiguration","url":"\/documentation\/dotnfc\/dotfingerstransformationmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","kind":"symbol","title":"transformation"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Fingers library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration":{"abstract":[{"type":"text","text":"Fingers library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","role":"symbol","title":"DotFingersLibraryConfiguration","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersTransformationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/title"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/fragments"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersTransformationModuleConfiguration\/navigatorTitle"},{"value":"DotFingersLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/title"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/fragments"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/navigatorTitle"}]}]}