{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"aspects"}],"title":"aspects","fragments":[{"text":"aspects","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)Face(py)aspects"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/aspects"},"abstract":[{"type":"text","text":"Face aspects."}],"variants":[{"paths":["\/documentation\/dotfacecore\/face\/aspects"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","text":"DOTFFaceAspects"},{"kind":"text","text":" * "},{"kind":"identifier","text":"aspects"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Face":{"title":"Face","url":"\/documentation\/dotfacecore\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","fragments":[{"text":"Face","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/Face/aspects":{"url":"\/documentation\/dotfacecore\/face\/aspects","abstract":[{"text":"Face aspects.","type":"text"}],"title":"aspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/aspects","type":"topic","fragments":[{"text":"aspects","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"kind":"symbol","url":"\/documentation\/dotfacecore\/faceaspects","role":"symbol","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"title":"FaceAspects"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceAspects","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace"},{"value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","op":"replace"},{"value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}