{"variants":[{"paths":["\/documentation\/dotfacecore\/face\/initwithconfidence:position:faceaspects:facequality:facekeypoints:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)DOTDetectionPosition","text":"DOTDetectionPosition","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"position"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAspects:"},{"text":"(","kind":"text"},{"text":"DOTFFaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceAspects"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceQuality:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","kind":"typeIdentifier","text":"DOTFFaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceQuality"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceKeypoints:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","text":"DOTFFaceKeypoints","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"faceKeypoints","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"passiveLivenessFaceAttribute:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","text":"DOTFFaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"text":"passiveLivenessFaceAttribute","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullFrontalBgrRawImage:"},{"kind":"text","text":"("},{"text":"DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fullFrontalBgrRawImage"},{"kind":"text","text":" "},{"text":"template:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFTemplate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"kind":"text","text":" *) "},{"text":"template_","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)Face(im)initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","role":"symbol","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:"}],"title":"initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Template":{"title":"Template","url":"\/documentation\/dotfacecore\/template","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Template","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","role":"symbol","abstract":[{"type":"text","text":"Face template."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceKeypoints"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","type":"topic","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"title":"FaceKeypoints","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoints"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"title":"FaceQuality","kind":"symbol","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"url":"\/documentation\/dotfacecore\/facequality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/Face/initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:":{"title":"initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","kind":"symbol","url":"\/documentation\/dotfacecore\/face\/initwithconfidence:position:faceaspects:facequality:facekeypoints:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"kind":"symbol","type":"topic","title":"BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/bgrrawimage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceaspects","title":"FaceAspects","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"title":"FaceAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/faceattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.2"}]},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"kind":"symbol","type":"topic","title":"Face","abstract":[{"type":"text","text":"Detected face in the image."}],"url":"\/documentation\/dotfacecore\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","fragments":[{"text":"Face","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title","op":"replace","value":"DOTFTemplate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","value":"DOTFFaceKeypoints","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"value":"DOTFFaceQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"text":"DOTFFaceQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}