{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/face\/initwithconfidence:position:aspects:quality:keypoints:passiveliveness:fullfrontalimage:template:"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"position:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTDetectionPosition","preciseIdentifier":"c:objc(cs)DOTDetectionPosition","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"aspects:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceAspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aspects","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quality:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"DOTFFaceQuality","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"quality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"keypoints:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"DOTFFaceKeypoints","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"keypoints","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"passiveLiveness:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"passiveLiveness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fullFrontalImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fullFrontalImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"template:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"DOTFTemplate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"template_","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)Face(im)initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:","navigatorTitle":[{"text":"initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:","kind":"identifier"}],"role":"symbol","title":"initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"title":"FaceAspects","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceaspects","kind":"symbol","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"title":"FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"role":"symbol","url":"\/documentation\/dotfacecore\/faceattribute","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"type":"topic","title":"FaceKeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","kind":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"type":"topic","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"title":"FaceQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","url":"\/documentation\/dotfacecore\/face","kind":"symbol","fragments":[{"kind":"identifier","text":"Face"}],"title":"Face","abstract":[{"type":"text","text":"Detected face in the image."}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"role":"symbol","abstract":[{"text":"Face template.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"kind":"symbol","title":"Template","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","url":"\/documentation\/dotfacecore\/template","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Template"}]},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfacecore\/image","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"kind":"symbol","type":"topic","title":"Image"},"doc://DotFaceCore/documentation/DotFaceCore/Face/initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:","url":"\/documentation\/dotfacecore\/face\/initwithconfidence:position:aspects:quality:keypoints:passiveliveness:fullfrontalimage:template:","title":"initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidence:position:aspects:quality:keypoints:passiveLiveness:fullFrontalImage:template:"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceAspects","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/navigatorTitle"},{"value":"DOTFFaceAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle"},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceKeypoints"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle"},{"value":"DOTFFaceQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle"},{"value":"DOTFTemplate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title"},{"value":[{"kind":"identifier","text":"DOTFTemplate"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments"},{"value":[{"text":"DOTFTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}