{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/left"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/rectangledouble\/left"]},{"paths":["\/documentation\/dotpalmcore\/rectangledouble\/left"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"Left edge."}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","title":"left","navigatorTitle":[{"text":"left","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)left"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/left":{"role":"symbol","title":"left","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/left","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"left"}],"url":"\/documentation\/dotpalmcore\/rectangledouble\/left","abstract":[{"text":"Left edge.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"left"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmDetector","kind":"identifier"}],"title":"PalmDetector","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.6.1"}],"title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"left","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"left"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"left","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1left\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1left\/fragments","value":[{"text":"left","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace"}]}]}