{"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/errorDescription"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/composeWithInternalError()"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/intervalfloat\/error\/dotsdkerror-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error"]]},"kind":"article","metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"DotSdkError Implementations"},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/errorDescription":{"title":"errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/errordescription","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/errorDescription"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error":{"role":"symbol","title":"IntervalFloat.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/composeWithInternalError()":{"role":"symbol","title":"composeWithInternalError()","url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/composewithinternalerror()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/composeWithInternalError()","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat":{"role":"symbol","title":"IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotfingerscore\/intervalfloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/description":{"role":"symbol","title":"description","abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/description","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/title","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}]}]}