{"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error"]]},"sections":[],"topicSections":[{"generated":true,"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/!=(_:_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/intervalfloat\/error\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat":{"role":"symbol","title":"IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotfingerscore\/intervalfloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error":{"role":"symbol","title":"IntervalFloat.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/!=(_:_:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}