{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/intervalfloat\/error\/recoverysuggestion"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","role":"symbol","title":"recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFingersCore","relatedModules":["Foundation"]}],"extendedModule":"Foundation","platforms":[{"unavailable":false,"introducedAt":"8.0","name":"iOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"8.0","name":"iPadOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"8.0","name":"Mac Catalyst","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"10.10","name":"macOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"9.0","name":"tvOS","deprecated":false,"beta":false},{"unavailable":false,"introducedAt":"2.0","name":"watchOS","deprecated":false,"beta":false}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/recoverySuggestion"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat":{"role":"symbol","title":"IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotfingerscore\/intervalfloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error":{"role":"symbol","title":"IntervalFloat.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/intervalfloat\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalFloat/Error/recoverySuggestion":{"url":"\/documentation\/dotfingerscore\/intervalfloat\/error\/recoverysuggestion","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"title":"recoverySuggestion","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalFloat\/Error\/recoverySuggestion"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalFloat","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/fragments","op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalFloat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}]}]}