{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/points","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"]]},"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/points"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/points"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"points","kind":"identifier"}],"extendedModule":"DotCore","role":"symbol","title":"points","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(py)points","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"points"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"kind":"text","text":"]"}],"symbolKind":"property","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}]},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble/points":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/points","navigatorTitle":[{"text":"points","kind":"identifier"}],"type":"topic","role":"symbol","title":"points","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":"]","kind":"text"}],"url":"\/documentation\/dotdocument\/rectangledouble\/points"},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"type":"topic","title":"RectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","url":"\/documentation\/dotdocument\/rectangledouble","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/PointDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"symbol","title":"PointDouble","type":"topic","url":"\/documentation\/dotdocument\/pointdouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"points","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"points"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<DOTPointDouble *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"points","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"points","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1points\/title"},{"value":[{"kind":"identifier","text":"points"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1points\/fragments"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle"},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}