{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory"]]},"metadata":{"title":"createBgraRawImage(ciImage:ciContext:)","role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithCiImage:ciContext:","symbolKind":"method","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}]}],"name":"ciImage"},{"content":[{"inlineContent":[{"type":"text","text":"CIContext."}],"type":"paragraph"}],"name":"ciContext"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" instance."}]}]}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","url":"\/documentation\/dotpalmcore\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"title":"createBgraRawImage(ciImage:ciContext:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory":{"kind":"symbol","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory","title":"ImageFactory","url":"\/documentation\/dotpalmcore\/imagefactory"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"title":"Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBgraRawImageWithCiImage:ciContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"ciContext:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}]}],"name":"ciImage"},{"content":[{"inlineContent":[{"type":"text","text":"CIContext."}],"type":"paragraph"}],"name":"ciContext"}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title","value":"createBgraRawImageWithCiImage:ciContext:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"}]}]}