{"variants":[{"paths":["\/documentation\/dotfacecore\/faceimage\/facesizeratiointerval"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceimage\/facesizeratiointerval"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"faceSizeRatioInterval","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage(py)faceSizeRatioInterval","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"faceSizeRatioInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"}],"navigatorTitle":[{"text":"faceSizeRatioInterval","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/faceSizeRatioInterval","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Face size ratio interval used for face detection."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","text":"IntervalDouble"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImage/faceSizeRatioInterval":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"}],"abstract":[{"text":"Face size ratio interval used for face detection.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/faceSizeRatioInterval","navigatorTitle":[{"kind":"identifier","text":"faceSizeRatioInterval"}],"kind":"symbol","type":"topic","title":"faceSizeRatioInterval","url":"\/documentation\/dotfacecore\/faceimage\/facesizeratiointerval","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"title":"FaceImage","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImage"}],"navigatorTitle":[{"kind":"identifier","text":"FaceImage"}],"abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceimage","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol","type":"topic","title":"IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"faceSizeRatioInterval","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"faceSizeRatioInterval"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"DOTIntervalDouble"},{"kind":"text","text":" * "},{"text":"faceSizeRatioInterval","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1faceSizeRatioInterval\/title","value":"faceSizeRatioInterval","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1faceSizeRatioInterval\/fragments","value":[{"kind":"identifier","text":"faceSizeRatioInterval"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title","value":"DOTFFaceImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImage"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/navigatorTitle"},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}