{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/description","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(py)description","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/intervalfloat\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/intervalfloat\/description"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/description","title":"description","url":"\/documentation\/dotfacecore\/intervalfloat\/description","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.6.0"}],"url":"\/documentation\/dotfacecore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat":{"url":"\/documentation\/dotfacecore\/intervalfloat","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"title":"IntervalFloat","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"}],"platforms":["iOS"]}]}},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1description\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTIntervalFloat","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}