{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/fast\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"role":"symbol","externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC4FastCAEycfc","symbolKind":"init","modules":[{"name":"DotPalmCore"}],"title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Fast\/init()"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Fast"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration/Fast/init()":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/fast\/init()","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Fast\/init()","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration/Fast":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/fast","abstract":[{"type":"text","text":"Face detection fast module."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Fast","title":"DotFaceDetectionModuleConfiguration.Fast","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fast"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Fast"}]}},"variantOverrides":[{"patch":[{"value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}