{"seeAlsoSections":[{"title":"Non-UI components","generated":true,"anchor":"Non-UI-components","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPPalmDetector) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This component requires the "},{"type":"codeVoice","code":"DotPalmDetection"},{"type":"text","text":" module to be active."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmdetector"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"},"sections":[],"metadata":{"navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"title":"PalmDetector","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","topicSections":[{"title":"Palm detection input","anchor":"Palm-detection-input","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"]},{"title":"Palm detection output","anchor":"Palm-detection-output","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/init()"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/detect(bgraRawImage:limit:)"]},{"title":"Enumerations","generated":true,"anchor":"Enumerations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"url":"\/documentation\/dotpalmcore\/bgrarawimage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"type":"topic","title":"PalmAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/init()":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/init()","title":"init()","role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/init()","abstract":[{"text":"Create the palm detector.","type":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of image parameters analysis."}],"title":"ImageParameters","url":"\/documentation\/dotpalmcore\/imageparameters"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/detect(bgraRawImage:limit:)":{"abstract":[{"type":"text","text":"Detect palms in an image."}],"title":"detect(bgraRawImage:limit:)","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/detect(bgraRawImage:limit:)","url":"\/documentation\/dotpalmcore\/palmdetector\/detect(bgrarawimage:limit:)","kind":"symbol","navigatorTitle":[{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"title":"PalmDetector.Palm","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","abstract":[{"type":"text","text":"Result of the palm detection process."}],"navigatorTitle":[{"text":"Palm","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotpalmcore\/rectangledouble","type":"topic","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"kind":"symbol","title":"PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Error":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/error","title":"PalmDetector.Error","abstract":[],"role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","kind":"symbol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTPPalmDetector"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmDetector","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"],"anchor":"Palm-detection-input","title":"Palm detection input"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"],"anchor":"Palm-detection-output","title":"Palm detection output"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/detect(bgraRawImage:limit:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/init()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Non-UI components","anchor":"Non-UI-components","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmDetector"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/navigatorTitle"},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1init()\/fragments"},{"value":"DOTPImageParameters","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title"},{"value":[{"text":"DOTPImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments"},{"value":[{"kind":"identifier","text":"DOTPImageParameters"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/navigatorTitle"},{"value":"detectWithBgraRawImage:limit:error:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1detect(bgraRawImage:limit:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1detect(bgraRawImage:limit:)\/fragments"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle"},{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}