{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:validators:detectionArea:)","interfaceLanguage":"swift"},"metadata":{"externalID":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC6common04autoD010validators13detectionAreaAE0A4Core06CommonF0C_0aD00cdF0CSayAA0bcD24FrameParametersValidator_pGAJ15RectangleDoubleCSgtKcfc","symbolKind":"init","role":"symbol","title":"init(common:autoCapture:validators:detectionArea:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureFrameParametersValidator","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Initializer"},"abstract":[{"type":"text","text":"Create document auto capture controller configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration"},{"text":" = .init(), ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration"},{"text":" = try! .init(\n                minValidSamplesInRowToStartCandidateSelection: Defaults.minValidSamplesInRowToStartCandidateSelection,\n                candidateSelectionDurationMillis: Defaults.candidateSelectionDurationMillis\n            ), ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureFrameParametersValidator","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator"},{"text":"], ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},{"text":"? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/init(common:autocapture:validators:detectionarea:)"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/init(common:autoCapture:validators:detectionArea:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:validators:detectionArea:)","kind":"symbol","title":"init(common:autoCapture:validators:detectionArea:)","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/init(common:autocapture:validators:detectionarea:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureFrameParametersValidator","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Create document auto capture controller configuration.","type":"text"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","role":"symbol","title":"DocumentAutoCaptureController.Configuration"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/autocaptureconfiguration","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","title":"AutoCaptureConfiguration","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"abstract":[{"type":"text","text":"Common configuration for all components."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","role":"symbol","title":"CommonConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/commonconfiguration"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"type":"topic","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator","kind":"symbol","title":"DocumentAutoCaptureFrameParametersValidator","url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParametersValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParametersValidator"}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"type":"topic","title":"RectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","url":"\/documentation\/dotdocument\/rectangledouble","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle"},{"value":"DOTDDocumentAutoCaptureFrameParametersValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParametersValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/navigatorTitle"},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","op":"replace"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle"}]}]}