{"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/libraries\/init(document:face:facelite:nfc:palm:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/libraries\/init(document:face:facelite:nfc:palm:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:","title":"init(document:face:faceLite:nfc:palm:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/init(document:face:faceLite:nfc:palm:)"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","abstract":[{"text":"Palm library configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"kind":"symbol","title":"DotFaceLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration":{"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Document library configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","title":"DotDocumentLibraryConfiguration","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceLiteLibraryConfiguration":{"role":"symbol","navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacelitelibraryconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLiteLibraryConfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face Lite library configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"title":"DotFaceLiteLibraryConfiguration"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/Libraries/init(document:face:faceLite:nfc:palm:)":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/libraries\/init(document:face:facelite:nfc:palm:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/init(document:face:faceLite:nfc:palm:)","title":"init(document:face:faceLite:nfc:palm:)"},"doc://DotDocument/documentation/DotDocument/DotNfcLibraryConfiguration":{"type":"topic","url":"\/documentation\/dotdocument\/dotnfclibraryconfiguration","abstract":[{"type":"text","text":"NFC library configuration."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","role":"symbol","title":"DotNfcLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Libraries":{"url":"\/documentation\/dotdocument\/libraries","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"role":"symbol","title":"Libraries","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocument:face:faceLite:nfc:palm:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocument:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"kind":"identifier","text":"face:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"face"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLiteLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLite"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nfc"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palm"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLiteLibraryConfiguration\/title","value":"DotFaceLiteLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLiteLibraryConfiguration\/fragments","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLiteLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1init(document:face:faceLite:nfc:palm:)\/title","value":"initWithDocument:face:faceLite:nfc:palm:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1init(document:face:faceLite:nfc:palm:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle","value":[{"text":"Libraries","kind":"identifier"}]}]}]}