{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/libraries\/nfc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/libraries\/nfc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/nfc"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"nfc","kind":"identifier"}],"role":"symbol","title":"nfc","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)Libraries(py)nfc"},"abstract":[{"text":"NFC library configuration.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotNfcLibraryConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"title":"DotNfcLibraryConfiguration","url":"\/documentation\/dotdocument\/dotnfclibraryconfiguration","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"NFC library configuration.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Libraries":{"url":"\/documentation\/dotdocument\/libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"role":"symbol","title":"Libraries"},"doc://DotDocument/documentation/DotDocument/Libraries/nfc":{"url":"\/documentation\/dotdocument\/libraries\/nfc","abstract":[{"text":"NFC library configuration.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/nfc","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"?"}],"title":"nfc","navigatorTitle":[{"kind":"identifier","text":"nfc"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"nfc","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"nfc","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":" * ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotNfcLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotNfcLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle"},{"op":"replace","value":"nfc","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1nfc\/title"},{"op":"replace","value":[{"text":"nfc","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1nfc\/fragments"}]}]}