{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel"]]},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"metadata":{"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup","modules":[{"name":"DotFaceLite"}]},"kind":"article","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/loggerloglevel\/equatable-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/!=(_:_:)":{"kind":"symbol","url":"\/documentation\/dotfacelite\/loggerloglevel\/!=(_:_:)","type":"topic","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/!=(_:_:)","role":"symbol","title":"!=(_:_:)"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel":{"kind":"symbol","title":"LoggerLogLevel","role":"symbol","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","url":"\/documentation\/dotfacelite\/loggerloglevel","abstract":[{"text":"Available log levels.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}