{"kind":"symbol","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"ImageParameters"},{"type":"text","text":" with normalized values in range [0, 1.0]."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"sharpness","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"hotspotsScore","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters"]]},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sharpness"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightness"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"hotspotsScore"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDImageParameters(im)initWithSharpness:brightness:hotspotsScore:","title":"init(sharpness:brightness:hotspotsScore:)","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"initWithSharpness:brightness:hotspotsScore:","kind":"identifier"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageparameters\/init(sharpness:brightness:hotspotsscore:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageparameters\/init(sharpness:brightness:hotspotsscore:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters\/init(sharpness:brightness:hotspotsScore:)"},"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParameters":{"kind":"symbol","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"role":"symbol","title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageparameters","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParameters/init(sharpness:brightness:hotspotsScore:)":{"url":"\/documentation\/dotdocument\/imageparameters\/init(sharpness:brightness:hotspotsscore:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSharpness:brightness:hotspotsScore:"}],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"hotspotsScore","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(sharpness:brightness:hotspotsScore:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters\/init(sharpness:brightness:hotspotsScore:)","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"ImageParameters"},{"text":" with normalized values in range [0, 1.0].","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","role":"collection","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithSharpness:brightness:hotspotsScore:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSharpness:brightness:hotspotsScore:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithSharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"sharpness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"brightness:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"brightness","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hotspotsScore:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"hotspotsScore","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"value":[{"text":"DOTDImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters~1init(sharpness:brightness:hotspotsScore:)\/title","value":"initWithSharpness:brightness:hotspotsScore:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters~1init(sharpness:brightness:hotspotsScore:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSharpness:brightness:hotspotsScore:","kind":"identifier"}]}]}]}