{"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDMrzReaderResult) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Result","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"MRZ reading result.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader\/result"]}],"metadata":{"symbolKind":"class","role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Class","externalID":"s:11DotDocument9MrzReaderC6ResultC","navigatorTitle":[{"kind":"identifier","text":"Result"}],"title":"MrzReader.Result","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Result","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/init(rawLines:travelDocumentType:machineReadableZone:error:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/error","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/machineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/rawLines","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/travelDocumentType"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader/Result/rawLines":{"url":"\/documentation\/dotdocument\/mrzreader\/result\/rawlines","abstract":[{"text":"Lines of text recognized by OCR of the document.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/rawLines","title":"rawLines","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}]},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/travelDocumentType":{"url":"\/documentation\/dotdocument\/mrzreader\/result\/traveldocumenttype","abstract":[{"type":"text","text":"Resolved travel document type."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/travelDocumentType","title":"travelDocumentType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":"?"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/init(rawLines:travelDocumentType:machineReadableZone:error:)":{"url":"\/documentation\/dotdocument\/mrzreader\/result\/init(rawlines:traveldocumenttype:machinereadablezone:error:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/init(rawLines:travelDocumentType:machineReadableZone:error:)","title":"init(rawLines:travelDocumentType:machineReadableZone:error:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawLines"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReadingError","preciseIdentifier":"s:11DotDocument9MrzReaderC12ReadingErrorC"},{"kind":"text","text":"?)"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/error":{"url":"\/documentation\/dotdocument\/mrzreader\/result\/error","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument9MrzReaderC12ReadingErrorC","text":"ReadingError"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/error","abstract":[{"text":"Error thrown during MRZ reading.","type":"text"}],"title":"error","type":"topic","role":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/description":{"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/dotdocument\/mrzreader\/result\/description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/description","kind":"symbol","title":"description"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result":{"navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/mrzreader\/result","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result","abstract":[{"text":"MRZ reading result.","type":"text"}],"title":"MrzReader.Result","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/machineReadableZone":{"role":"symbol","abstract":[{"text":"Parsed MRZ.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/mrzreader\/result\/machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/machineReadableZone","kind":"symbol","title":"machineReadableZone"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle"}]}]}