{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder"]]},"metadata":{"title":"minConfidence(_:)","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC13minConfidenceyAiA13WrappedDoubleCSgKF","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"minConfidence","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/minConfidence(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"minConfidence","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"minConfidence"},{"kind":"text","text":": "},{"text":"WrappedDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/minconfidence(_:)"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder":{"title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds.Builder","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Builder","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Builder"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureViewController.Configuration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/WrappedDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedDouble"}],"abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedDouble","type":"topic","url":"\/documentation\/dotdocument\/wrappeddouble","title":"WrappedDouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","type":"topic","title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder/minConfidence(_:)":{"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/minconfidence(_:)","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/minConfidence(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"kind":"text","text":"("},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"kind":"symbol","title":"minConfidence(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1WrappedDouble\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","op":"replace"}]}]}