{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses\/arePreconditionsMet"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFGlasses(py)arePreconditionsMet","title":"arePreconditionsMet","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"arePreconditionsMet","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"]]},"abstract":[{"type":"text","text":"This is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/glasses\/arepreconditionsmet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/glasses\/arepreconditionsmet"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"arePreconditionsMet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"text":"In case this flag is set to ","type":"text"},{"code":"false","type":"codeVoice"},{"text":", the resulting score is not reliable.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses/arePreconditionsMet":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"arePreconditionsMet","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/glasses\/arepreconditionsmet","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses\/arePreconditionsMet","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"This is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"title":"arePreconditionsMet","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"abstract":[{"type":"text","text":"Face attribute for the glasses."}],"title":"Glasses","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Glasses","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/glasses","navigatorTitle":[{"text":"Glasses","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"arePreconditionsMet","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"arePreconditionsMet"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"arePreconditionsMet"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses~1arePreconditionsMet\/title","value":"arePreconditionsMet","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses~1arePreconditionsMet\/fragments","value":[{"text":"arePreconditionsMet","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/navigatorTitle","value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace"}]}]}