{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTPSizeTooSmallValidator) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator"]},{"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooSmallValidator","symbolKind":"class","title":"SizeTooSmallValidator","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/validate(palmAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold"]}],"abstract":[{"text":"Validate whether the size of the detected palm is too small.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/dependencyIdentifiers":{"kind":"symbol","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","role":"symbol","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/dependencyidentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}]},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/identifier":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/identifier","kind":"symbol","type":"topic","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/identifier","title":"identifier"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator":{"url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator","title":"PalmAutoCaptureDetectionValidator","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetectionValidator"}],"abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","navigatorTitle":[{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"type":"topic","title":"SizeTooSmallValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/defaultMinEdgeLengthToImageShorterSideRatioThreshold":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"}],"abstract":[{"text":"Default threshold.","type":"text"}],"title":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"abstract":[{"text":"Validate minimum brightness of the detected palm.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"type":"topic","title":"BrightnessTooLowValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/validate(palmAutoCaptureFrameParameters:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/validate(palmAutoCaptureFrameParameters:)","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/validate(palmautocaptureframeparameters:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"abstract":[{"text":"Validate size of the detected palm.","type":"text"}],"title":"validate(palmAutoCaptureFrameParameters:)"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/init(minEdgeLengthToImageShorterSideRatioThreshold:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"title":"init(minEdgeLengthToImageShorterSideRatioThreshold:)"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/init()":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[{"type":"text","text":"Initialize with default threshold."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","title":"init()","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/init()"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","title":"SizeTooLargeValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"role":"symbol","type":"topic","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"abstract":[{"text":"Validate if the detected palm is within the bounds of the image.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmOutOfBoundsValidator"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"type":"topic","title":"PalmOutOfBoundsValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"type":"topic","title":"PalmNotDetectedValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/minEdgeLengthToImageShorterSideRatioThreshold":{"title":"minEdgeLengthToImageShorterSideRatioThreshold","abstract":[{"text":"Current minimal edge length to image shorter side ratio threshold.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold","navigatorTitle":[{"kind":"identifier","text":"minEdgeLengthToImageShorterSideRatioThreshold"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"type":"topic","abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"title":"BrightnessTooHighValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPSizeTooSmallValidator","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/validate(palmAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold"],"title":"Type Properties"}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator"],"type":"conformsTo","title":"Conforms To"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"generated":true}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPSizeTooSmallValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1dependencyIdentifiers\/title"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1dependencyIdentifiers\/fragments"},{"value":"identifier","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1identifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1identifier\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/title","value":"DOTPPalmAutoCaptureDetectionValidator"},{"value":[{"text":"DOTPPalmAutoCaptureDetectionValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","value":"DOTPSizeTooSmallValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/title","op":"replace","value":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/fragments","value":[{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"op":"replace"},{"value":"DOTPBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1validate(palmAutoCaptureFrameParameters:)\/title","value":"validateWithPalmAutoCaptureFrameParameters:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/title","value":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","value":"DOTPSizeTooLargeValidator"},{"value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"},{"value":"DOTPPalmOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title"},{"op":"replace","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments"},{"op":"replace","value":"DOTPPalmNotDetectedValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title"},{"op":"replace","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/title","value":"minEdgeLengthToImageShorterSideRatioThreshold"},{"value":[{"kind":"identifier","text":"minEdgeLengthToImageShorterSideRatioThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","op":"replace","value":"DOTPSharpnessTooLowValidator"},{"value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title","value":"DOTPBrightnessTooHighValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments","op":"replace","value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}]}]}]}