{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotpalmdetectionmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration(im)init","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotfingerscore\/dotpalmdetectionmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration","title":"DotPalmDetectionModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Palm detection module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmDetectionModuleConfiguration/init":{"type":"topic","url":"\/documentation\/dotfingerscore\/dotpalmdetectionmoduleconfiguration\/init","abstract":[],"title":"init","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmDetectionModuleConfiguration\/init","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotPalmDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/title"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}