{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder\/minmouthstatusscore(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minMouthStatusScore","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"minMouthStatusScore","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/minMouthStatusScore(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder"]]},"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"title":"minMouthStatusScore(_:)","externalID":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC19minMouthStatusScoreyAE0aC013WrappedDoubleCSgKF","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minMouthStatusScore","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","url":"\/documentation\/dotfacecore\/wrappeddouble","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Builder":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder","navigatorTitle":[{"text":"Builder","kind":"identifier"}],"type":"topic","role":"symbol","title":"FaceAutoCaptureQualityAttributeThresholds.Builder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Builder/minMouthStatusScore(_:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/minMouthStatusScore(_:)","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder\/minmouthstatusscore(_:)","title":"minMouthStatusScore(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minMouthStatusScore","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","title":"FaceAutoCaptureQualityAttributeThresholds","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTFFaceAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}