{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"title":"init","symbolKind":"method","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"abstract":[{"text":"Face passive liveness module.","type":"text"}],"title":"DotFacePassiveLivenessModuleConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration"},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration/init":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration\/init","url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration\/init","abstract":[],"type":"topic","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}