{"sections":[],"seeAlsoSections":[{"title":"MRZ reading output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate"],"generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTMrzStringPosition) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzstringposition"]},{"paths":["\/documentation\/dotdocument\/mrzstringposition"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/endIndex","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/lineIndex","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/startIndex"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/isEqual(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"},"abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","title":"MrzStringPosition","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzStringPosition","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo"}],"references":{"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"title":"Td1MachineReadableZone","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td1MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"kind":"symbol"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"title":"Td3MachineReadableZone","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"url":"\/documentation\/dotdocument\/machinereadablezone","kind":"symbol","title":"MachineReadableZone","role":"symbol","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/isEqual(_:)","url":"\/documentation\/dotdocument\/mrzstringposition\/isequal(_:)"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"navigatorTitle":[{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"title":"MrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElementWithCheckDigit"}]},"doc://DotDocument/documentation/DotDocument/MrzElement":{"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","url":"\/documentation\/dotdocument\/mrzelement","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/description":{"type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/description","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","title":"description"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/lineIndex":{"type":"topic","abstract":[{"type":"text","text":"An index of the line in MRZ."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/lineIndex","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition\/lineindex","navigatorTitle":[{"kind":"identifier","text":"lineIndex"}],"role":"symbol","title":"lineIndex"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","kind":"symbol","title":"MrzDateElementWithCheckDigit","role":"symbol","abstract":[{"type":"text","text":"A "},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"kind":"symbol","title":"MrzNameElement","url":"\/documentation\/dotdocument\/mrznameelement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}]},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/endIndex":{"type":"topic","abstract":[{"text":"An index of the last character in the MRZ line.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"endIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/endIndex","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition\/endindex","navigatorTitle":[{"kind":"identifier","text":"endIndex"}],"role":"symbol","title":"endIndex"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"url":"\/documentation\/dotdocument\/mrzstringposition","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"title":"MrzStringPosition","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}]},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"title":"Td2MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone","role":"symbol","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"url":"\/documentation\/dotdocument\/mrzdate","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"title":"MrzDate","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}]},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/init(lineIndex:startIndex:endIndex:)":{"type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"lineIndex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"text":"startIndex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"endIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition\/init(lineindex:startindex:endindex:)","navigatorTitle":[{"kind":"identifier","text":"initWithLineIndex:startIndex:endIndex:"}],"role":"symbol","title":"init(lineIndex:startIndex:endIndex:)"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/hash":{"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/hash","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","title":"hash"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/startIndex":{"type":"topic","abstract":[{"text":"An index of the first character in the MRZ line.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"startIndex","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/startIndex","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition\/startindex","navigatorTitle":[{"kind":"identifier","text":"startIndex"}],"role":"symbol","title":"startIndex"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTMrzStringPosition","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/endIndex","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/lineIndex","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/startIndex"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"MRZ reading output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTMrzStringPosition","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone"},{"value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTMachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","value":"DOTMrzElement","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1description\/fragments","op":"replace"},{"value":"lineIndex","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1lineIndex\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1lineIndex\/fragments","op":"replace","value":[{"kind":"identifier","text":"lineIndex"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments"},{"value":"DOTMrzNameElement","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","op":"replace"},{"value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1endIndex\/title","value":"endIndex"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1endIndex\/fragments","op":"replace","value":[{"text":"endIndex","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition","op":"replace"},{"op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","value":"DOTMrzDate"},{"value":[{"kind":"identifier","text":"DOTMrzDate"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1init(lineIndex:startIndex:endIndex:)\/title","value":"initWithLineIndex:startIndex:endIndex:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1init(lineIndex:startIndex:endIndex:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLineIndex:startIndex:endIndex:"}],"op":"replace"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1hash\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1hash\/fragments"},{"value":"startIndex","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1startIndex\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1startIndex\/fragments","op":"replace","value":[{"kind":"identifier","text":"startIndex"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}