{"seeAlsoSections":[{"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init(threshold:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/threshold"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/defaultThreshold"]}],"variants":[{"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","title":"Conforms To"}],"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDSharpnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDSharpnessTooLowValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"inlineContent":[{"text":"To use this validator also following validators must be applied: ","type":"text"},{"code":"DocumentOutOfBoundsValidator","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}],"abstract":[{"text":"Validate minimum sharpness of the detected document.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable"},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","kind":"symbol","title":"DocumentOutOfBoundsValidator"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","role":"symbol","title":"MrzNotValidValidator","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNotValidValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/defaultThreshold":{"navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"abstract":[{"text":"Default threshold is 0.65.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/defaultThreshold","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/defaultthreshold","kind":"symbol","title":"defaultThreshold","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"abstract":[{"text":"Validate minimum sharpness of the detected document.","type":"text"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","role":"symbol","title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init()","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/init()","kind":"symbol","title":"init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"abstract":[{"text":"Use this protocol to create document validators.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","role":"symbol","title":"DocumentAutoCaptureDetectionValidator","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","title":"DocumentDoesNotFitPlaceholderValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}],"abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/threshold":{"navigatorTitle":[{"kind":"identifier","text":"threshold"}],"abstract":[{"type":"text","text":"Current minimal accepted sharpness."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/threshold","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/threshold","kind":"symbol","title":"threshold","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/dependencyIdentifiers":{"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/dependencyIdentifiers","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/dependencyidentifiers","kind":"symbol","title":"dependencyIdentifiers","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","title":"BrightnessTooHighValidator","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","title":"HotspotsScoreTooHighValidator","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","navigatorTitle":[{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","role":"symbol","title":"DocumentNotDetectedValidator","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"abstract":[{"type":"text","text":"Validate size of the detected document."}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","role":"symbol","title":"SizeTooSmallValidator","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/identifier":{"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/identifier","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/identifier","kind":"symbol","title":"identifier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"abstract":[{"text":"Validate minimum brightness of the detected document.","type":"text"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","role":"symbol","title":"BrightnessTooLowValidator","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/validate(documentAutoCaptureFrameParameters:)":{"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"abstract":[{"text":"Validate sharpness of the detected document.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/validate(documentautocaptureframeparameters:)","kind":"symbol","title":"validate(documentAutoCaptureFrameParameters:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/init(threshold:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init(threshold:)","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/init(threshold:)","kind":"symbol","title":"init(threshold:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"threshold"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTDSharpnessTooLowValidator"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/threshold"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init(threshold:)","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/defaultThreshold"],"title":"Type Properties"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"type":"conformsTo","title":"Conforms To"}]},{"value":[{"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTDSharpnessTooLowValidator"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","value":"DOTDDocumentOutOfBoundsValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTDMrzNotValidValidator"},{"value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace"},{"value":"defaultThreshold","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1defaultThreshold\/title"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1defaultThreshold\/fragments"},{"value":"DOTDSharpnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","op":"replace","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","op":"replace"},{"value":"DOTDDocumentDoesNotFitPlaceholderValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}]},{"value":"threshold","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1threshold\/title","op":"replace"},{"op":"replace","value":[{"text":"threshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1threshold\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1dependencyIdentifiers\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"replace","value":"DOTDBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title"},{"value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator"},{"op":"replace","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDDocumentNotDetectedValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","op":"replace","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}]},{"value":"DOTDSizeTooSmallValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"value":"DOTDBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBrightnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","op":"replace"},{"value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1init(threshold:)\/title","value":"initWithThreshold:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1init(threshold:)\/fragments","op":"replace"}]}]}