{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/nfc"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/libraries\/nfc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/libraries\/nfc"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"nfc","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)Libraries(py)nfc","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"nfc","kind":"identifier"}]},"abstract":[{"text":"NFC library configuration.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/Libraries/nfc":{"abstract":[{"text":"NFC library configuration.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"nfc","kind":"identifier"}],"role":"symbol","title":"nfc","url":"\/documentation\/dotpalmcore\/libraries\/nfc","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/nfc","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","kind":"symbol","type":"topic","title":"Libraries","url":"\/documentation\/dotpalmcore\/libraries","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"abstract":[{"type":"text","text":"Container for library configurations."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotNfcLibraryConfiguration":{"title":"DotNfcLibraryConfiguration","role":"symbol","url":"\/documentation\/dotpalmcore\/dotnfclibraryconfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","abstract":[{"type":"text","text":"NFC library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibraryConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"nfc","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nfc"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"nfc","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1nfc\/title"},{"op":"replace","value":[{"text":"nfc","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1nfc\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}