{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","kind":"typeIdentifier","text":"FaceQuality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","text":"FaceQuality","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer","externalID":"s:11DotFaceLite0B8DetectorC0B0C10confidence8position7qualityAESd_0aB7Commons17DetectionPositionCAA0B7QualityCtcfc","symbolKind":"init","role":"symbol","title":"init(confidence:position:quality:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/face\/init(confidence:position:quality:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/init(confidence:position:quality:)","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/init(confidence:position:quality:)":{"abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/init(confidence:position:quality:)","type":"topic","title":"init(confidence:position:quality:)","url":"\/documentation\/dotfacelite\/facedetector\/face\/init(confidence:position:quality:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","text":"FaceQuality"},{"kind":"text","text":")"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacelite\/facedetector","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"abstract":[{"type":"text","text":"Detected face."}],"url":"\/documentation\/dotfacelite\/facedetector\/face","title":"FaceDetector.Face","role":"symbol","navigatorTitle":[{"text":"Face","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","role":"symbol","abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"url":"\/documentation\/dotfacelite\/detectionposition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","title":"DetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"type":"topic","title":"FaceQuality","abstract":[{"text":"Face quality.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","url":"\/documentation\/dotfacelite\/facequality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/title","value":"DOTDetectionPosition","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","value":[{"text":"DOTDetectionPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title","value":"DOTFLFaceQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceQuality"}],"op":"replace"}]}]}