{"metadata":{"roleHeading":"Protocol","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"title":"DocumentAutoCaptureViewControllerDelegate","symbolKind":"protocol","externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate"},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:finished:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:uiStateUpdated:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillTransition(_:)"]}],"sections":[],"abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDDocumentAutoCaptureViewControllerDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate"},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerNoCameraPermission(_:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"title":"documentAutoCaptureViewControllerNoCameraPermission(_:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollernocamerapermission(_:)","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerNoCameraPermission(_:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewWillTransition(_:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"title":"documentAutoCaptureViewControllerViewWillTransition(_:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewwilltransition(_:)","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillTransition(_:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewDidLoad(_:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidLoad:","kind":"identifier"}],"title":"documentAutoCaptureViewControllerViewDidLoad(_:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidload(_:)","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLoad(_:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"title":"DocumentAutoCaptureViewControllerDelegate","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewDidLayoutSubviews(_:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidLayoutSubviews","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"title":"documentAutoCaptureViewControllerViewDidLayoutSubviews(_:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidlayoutsubviews(_:)","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLayoutSubviews(_:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewController(_:finished:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewController:finished:","kind":"identifier"}],"title":"documentAutoCaptureViewController(_:finished:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:finished:)","required":true,"abstract":[{"type":"text","text":"Tells the delegate that the document auto capture has finished with a result. This callback is called after the component has stopped."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:finished:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewDidDisappear(_:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"title":"documentAutoCaptureViewControllerViewDidDisappear(_:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdiddisappear(_:)","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidDisappear(_:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewDidAppear(_:)":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewdidappear(_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidAppear(_:)","kind":"symbol","title":"documentAutoCaptureViewControllerViewDidAppear(_:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewWillAppear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureViewControllerViewWillAppear:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewwillappear(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseDocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillAppear(_:)","abstract":[],"title":"documentAutoCaptureViewControllerViewWillAppear(_:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewController(_:uiStateUpdated:)":{"role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the UI state was updated."}],"navigatorTitle":[{"text":"documentAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiState","text":"DocumentAutoCaptureUiState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontroller(_:uistateupdated:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:uiStateUpdated:)","kind":"symbol","title":"documentAutoCaptureViewController(_:uiStateUpdated:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate/documentAutoCaptureViewControllerViewWillDisappear(_:)":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"documentAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate\/documentautocaptureviewcontrollerviewwilldisappear(_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillDisappear(_:)","kind":"symbol","title":"documentAutoCaptureViewControllerViewWillDisappear(_:)"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDDocumentAutoCaptureViewControllerDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:finished:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewController(_:uiStateUpdated:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate\/documentAutoCaptureViewControllerViewWillTransition(_:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"documentAutoCaptureViewControllerNoCameraPermission:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerNoCameraPermission(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerNoCameraPermission(_:)\/fragments"},{"value":"documentAutoCaptureViewControllerViewWillTransition:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillTransition(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillTransition(_:)\/fragments"},{"value":"documentAutoCaptureViewControllerViewDidLoad:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidLoad(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureViewControllerViewDidLoad:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidLoad(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title","value":"DOTDDocumentAutoCaptureViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/title","value":"documentAutoCaptureViewControllerViewDidLayoutSubviews:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"documentAutoCaptureViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"documentAutoCaptureViewController:finished:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:finished:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureViewController:finished:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidDisappear(_:)\/title","value":"documentAutoCaptureViewControllerViewDidDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidDisappear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidAppear(_:)\/title","value":"documentAutoCaptureViewControllerViewDidAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillAppear(_:)\/title","value":"documentAutoCaptureViewControllerViewWillAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:uiStateUpdated:)\/title","value":"documentAutoCaptureViewController:uiStateUpdated:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewController(_:uiStateUpdated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillDisappear(_:)\/title","value":"documentAutoCaptureViewControllerViewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate~1documentAutoCaptureViewControllerViewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}],"op":"replace"}]}]}