{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/description"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/pointint\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/pointint\/description"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTPointInt(py)description","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"description","kind":"identifier"}],"symbolKind":"property","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/PointInt":{"type":"topic","role":"symbol","title":"PointInt","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotfacecore\/pointint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/description":{"abstract":[],"type":"topic","kind":"symbol","title":"description","url":"\/documentation\/dotfacecore\/pointint\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPointInt","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/title"},{"op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/fragments"},{"op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1description\/fragments"}]}]}