{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/detectionposition\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/detectionposition\/rebased(parentrectangle:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"rebased(parentRectangle:)","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"externalID":"c:@CM@DotFingersCore@objc(cs)DOTFGDetectionPosition(im)rebasedWithParentRectangle:","symbolKind":"method","modules":[{"name":"DotFingersCore"}],"extendedModule":"DotFingersCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition"}],"roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition","kind":"typeIdentifier","text":"DetectionPosition","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/rebased(parentRectangle:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/rebased(parentRectangle:)":{"title":"rebased(parentRectangle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/detectionposition\/rebased(parentrectangle:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/rebased(parentRectangle:)"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"rebasedWithParentRectangle:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition","kind":"typeIdentifier","text":"DOTFGDetectionPosition"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rebasedWithParentRectangle:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentRectangle"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFGDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle"},{"value":"rebasedWithParentRectangle:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1rebased(parentRectangle:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1rebased(parentRectangle:)\/fragments"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}