{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"sections":[],"kind":"symbol","metadata":{"title":"dependencyIdentifiers","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLDevicePitchTooHighValidator(py)dependencyIdentifiers","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/dependencyidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/dependencyidentifiers"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DevicePitchTooHighValidator":{"type":"topic","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator","abstract":[{"type":"text","text":"Validate maximum pitch angle of the device."}],"navigatorTitle":[{"text":"DevicePitchTooHighValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevicePitchTooHighValidator","kind":"identifier"}],"kind":"symbol","title":"DevicePitchTooHighValidator","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DevicePitchTooHighValidator/dependencyIdentifiers":{"kind":"symbol","title":"dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/dependencyidentifiers","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"dependencyIdentifiers","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/title","value":"DOTFLDevicePitchTooHighValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/fragments","value":[{"text":"DOTFLDevicePitchTooHighValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLDevicePitchTooHighValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1dependencyIdentifiers\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}