{"metadata":{"role":"symbol","extendedModule":"DotCore","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"roleHeading":"Type Method","externalID":"c:@CM@DotCore@objc(cs)DOTPointInt(cm)fromCgPoint:","modules":[{"relatedModules":["DotCore"],"name":"DotFaceLite"}],"title":"from(cgPoint:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt","text":"PointInt"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/from(cgPoint:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/pointint\/from(cgpoint:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/pointint\/from(cgpoint:)"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/PointInt/from(cgPoint:)":{"role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/from(cgPoint:)","url":"\/documentation\/dotfacelite\/pointint\/from(cgpoint:)","kind":"symbol","type":"topic","title":"from(cgPoint:)"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt":{"navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt","type":"topic","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"kind":"symbol","title":"PointInt","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/pointint"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"fromCgPoint:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt","kind":"typeIdentifier","text":"DOTPointInt"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromCgPoint:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgPoint"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1from(cgPoint:)\/title","op":"replace","value":"fromCgPoint:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1from(cgPoint:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/title","op":"replace","value":"DOTPointInt"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}]}]}]}