{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/hash","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner(py)hash","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","title":"hash"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/hash":{"type":"topic","navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/hash","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/hash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"kind":"symbol","role":"symbol","title":"hash"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","title":"WrappedEyeGazeLivenessCorner","type":"topic","role":"symbol","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"EyeGazeLivenessCorner"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"hash"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1hash\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFWrappedEyeGazeLivenessCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace"}]}]}