{"abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"code":".front","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/cameraFacing"},"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"cameraFacing","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC12cameraFacingAA06CameraJ0Ovp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","title":"FaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","type":"topic","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","type":"topic","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/cameraFacing":{"title":"cameraFacing","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/camerafacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/cameraFacing","abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"type":"text","text":"."}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.3.0"}],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"type":"topic","kind":"symbol","title":"CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"url":"\/documentation\/dotfacecore\/camerafacing","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}