{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","kind":"typeIdentifier","text":"Placeholder"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/placeholder"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/placeholder","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC11placeholder0aB7Commons11PlaceholderCvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Placeholder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"title":"placeholder"},"sections":[],"abstract":[{"type":"text","text":"Specify the placeholder. Default is "},{"type":"codeVoice","code":".Visible"},{"type":"text","text":"."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Face Auto Capture component."}],"title":"FaceAutoCaptureViewController.Configuration"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/placeholder":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","kind":"typeIdentifier","text":"Placeholder"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/placeholder","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/placeholder","title":"placeholder","abstract":[{"text":"Specify the placeholder. Default is ","type":"text"},{"code":".Visible","type":"codeVoice"},{"text":".","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"abstract":[{"text":"Placeholder.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotfacecore\/placeholder","title":"Placeholder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title","op":"replace","value":"DOTPlaceholder"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle","op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]}]}]}