{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/query"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC5queryAA0B14DetectionQueryCvp","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"query"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"}],"title":"query"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","text":"FaceDetectionQuery"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/query"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"abstract":[{"type":"text","text":"Query for additional evaluation of face auto capture result."}],"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"title":"FaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"title":"DotFaceCore","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/query":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"query","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier"}],"role":"symbol","title":"query","type":"topic","abstract":[{"type":"text","text":"Query for additional evaluation of face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/query","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/query"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"kind":"symbol","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"type":"topic","title":"FaceDetectionQuery","navigatorTitle":[{"kind":"identifier","text":"FaceDetectionQuery"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"op":"replace"}]}]}