{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)initializeWithConfiguration:error:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotFingersCore"}],"title":"initialize(configuration:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:7DotCore0A3SdkC13ConfigurationC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration","text":"Configuration","preciseIdentifier":"s:7DotCore0A3SdkC13ConfigurationC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}]}],"name":"configuration"}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method should be called on the background thread."}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Throws an error if ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" fails to decode provided license or if any library fails to initialize.","type":"text"}]}],"style":"note","type":"aside","name":"Throws"}]}],"abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" with configuration.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/initialize(configuration:)"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotsdk\/initialize(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotsdk\/initialize(configuration:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/configuration","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration","title":"DotSdk.Configuration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkConfiguration":{"fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotsdkconfiguration","abstract":[{"text":"The ","type":"text"},{"text":"DotSdk","type":"text"},{"text":" configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration","title":"DotSdkConfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotfingerscore\/dotsdk","abstract":[{"text":"Class responsible for the initialization of IDV libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFingers"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","title":"DotSdk","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/initialize(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:7DotCore0A3SdkC13ConfigurationC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/initialize(configuration:)","abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" with configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/initialize(configuration:)","title":"initialize(configuration:)","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initializeWithConfiguration:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeWithConfiguration:error:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"initializeWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotSdkConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotSdk","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/title","op":"replace"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/fragments","op":"replace"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/navigatorTitle","op":"replace"},{"value":"initializeWithConfiguration:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1initialize(configuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1initialize(configuration:)\/fragments","op":"replace"}]}]}