{"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/!=(_:_:)"],"generated":true}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingertype\/equatable-implementations"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","title":"FingerType","role":"symbol","abstract":[{"text":"Type of detected finger.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/!=(_:_:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","title":"!=(_:_:)","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/fingertype\/!=(_:_:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect fingers in an image.","type":"text"}],"title":"FingerDetector","type":"topic","url":"\/documentation\/dotfingerscore\/fingerdetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerDetector"}],"navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","value":[{"text":"DOTFGFingerType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","value":[{"text":"DOTFGFingerType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","value":"DOTFGFingerDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]}]}]}