{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/little","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingertype\/little"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingertype\/little"]}],"abstract":[{"text":"Little finger.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@E@DOTFGFingerType@DOTFGFingerTypeLittle","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"little"}],"title":"FingerType.little","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"DOTFGFingerTypeLittle","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","title":"FingerType","role":"symbol","abstract":[{"text":"Type of detected finger.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/little":{"url":"\/documentation\/dotfingerscore\/fingertype\/little","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"}],"title":"FingerType.little","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/little","role":"symbol","abstract":[{"text":"Little finger.","type":"text"}],"navigatorTitle":[{"text":"DOTFGFingerTypeLittle","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFGFingerTypeLittle","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerTypeLittle"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTFGFingerTypeLittle"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerType"}]},{"op":"replace","value":[{"text":"DOTFGFingerType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle"},{"op":"replace","value":"DOTFGFingerTypeLittle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1little\/title"},{"op":"replace","value":[{"text":"DOTFGFingerTypeLittle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1little\/fragments"}]}]}