{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","text":"DOTFLFaceAutoCaptureDetection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"DOTFLFaceAutoCaptureResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"result"},{"kind":"text","text":" "},{"kind":"identifier","text":"events:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSet<DOTFLFaceAutoCaptureControllerWrappedEvent *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"events"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/initwithdetection:result:events:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/initWithDetection:result:events:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:result:events:"}],"title":"initWithDetection:result:events:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerProcessingResult(im)initWithDetection:result:events:","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:events:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureResult":{"role":"symbol","title":"FaceAutoCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"url":"\/documentation\/dotfacelite\/faceautocaptureresult"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"role":"symbol","title":"FaceAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of the image processing during the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult/initWithDetection:result:events:":{"role":"symbol","title":"initWithDetection:result:events:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:result:events:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/initWithDetection:result:events:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:events:"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/initwithdetection:result:events:"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult":{"role":"symbol","title":"DOTFLFaceAutoCaptureControllerProcessingResult","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerProcessingResult"}],"abstract":[{"type":"text","text":"The result returned from the processing of one image during the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 5.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","value":"DOTFLFaceAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}