{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Fingers-swift.class","preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC0B0C","text":"Fingers","kind":"typeIdentifier"}]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Minimal valid sharpness of the detected fingers.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents blurry fingers.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Value 1.0 represents sharp fingers."}],"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC0B0C","text":"Fingers"}],"title":"fingers","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds(py)fingers","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"fingers","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/fingers-swift.property","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/fingers-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/fingers-swift.property"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureQualityAttributeThresholdsFingers":{"fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholdsFingers"}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturequalityattributethresholdsfingers","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureQualityAttributeThresholdsFingers","title":"DOTFGFingersAutoCaptureQualityAttributeThresholdsFingers","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Fingers-swift.class":{"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/fingers-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fingers"}],"title":"FingersAutoCaptureQualityAttributeThresholds.Fingers","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Fingers-swift.class","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Fingers"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","title":"FingersAutoCaptureQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the fingers auto capture result.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/fingers-swift.property":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/fingers-swift.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Fingers","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC0B0C"}],"kind":"symbol","role":"symbol","title":"fingers","abstract":[{"text":"Minimal valid sharpness of the detected fingers.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Value 0.0 represents blurry fingers."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents sharp fingers."}],"navigatorTitle":[{"text":"fingers","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/fingers-swift.property"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"fingers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fingers","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholdsFingers","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureQualityAttributeThresholdsFingers","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholdsFingers"},{"text":" * ","kind":"text"},{"text":"fingers","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title","value":"DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1fingers-swift.property\/title","value":"fingers"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1fingers-swift.property\/fragments","value":[{"text":"fingers","kind":"identifier"}]}]}]}