{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTImageSize) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"languages":["swift"]}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/init(width:height:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/cgSize","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/height","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/longerSide","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/shorterSide","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/width"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculatePixelCount()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/isEqual(_:)"]},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/from(cgSize:)"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","externalID":"c:@M@DotCore@objc(cs)DOTImageSize","roleHeading":"Class","symbolKind":"class","role":"symbol","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/imagesize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imagesize"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"references":{"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/from(cgSize:)":{"navigatorTitle":[{"text":"fromCgSize:","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/from(cgSize:)","title":"from(cgSize:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/imagesize\/from(cgsize:)"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/init(width:height:)":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/init(width:height:)","url":"\/documentation\/dotpalmcore\/imagesize\/init(width:height:)","navigatorTitle":[{"kind":"identifier","text":"initWithWidth:height:"}],"type":"topic","title":"init(width:height:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/description":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"title":"description","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/description","kind":"symbol","url":"\/documentation\/dotpalmcore\/imagesize\/description"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/hash":{"role":"symbol","abstract":[],"title":"hash","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/imagesize\/hash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/hash"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/isEqual(_:)","type":"topic","url":"\/documentation\/dotpalmcore\/imagesize\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/calculatePixelCount()":{"navigatorTitle":[{"kind":"identifier","text":"calculatePixelCount"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculatePixelCount()","title":"calculatePixelCount()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"url":"\/documentation\/dotpalmcore\/imagesize\/calculatepixelcount()"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/calculateWidthToHeightRatio()":{"url":"\/documentation\/dotpalmcore\/imagesize\/calculatewidthtoheightratio()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"type":"topic","title":"calculateWidthToHeightRatio()","kind":"symbol","abstract":[{"type":"text","text":"Calculate width to height ratio."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculateWidthToHeightRatio()","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/shorterSide":{"url":"\/documentation\/dotpalmcore\/imagesize\/shorterside","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shorterSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"kind":"symbol","type":"topic","title":"shorterSide","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/shorterSide","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/height":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imagesize\/height","title":"height","kind":"symbol","abstract":[{"type":"text","text":"Image height in pixels."}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/height"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"abstract":[{"type":"text","text":"Image size in pixels."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","title":"ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imagesize"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/width":{"abstract":[{"text":"Image width in pixels.","type":"text"}],"url":"\/documentation\/dotpalmcore\/imagesize\/width","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"width","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/width","role":"symbol","navigatorTitle":[{"text":"width","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/cgSize":{"url":"\/documentation\/dotpalmcore\/imagesize\/cgsize","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cgSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"cgSize"}],"type":"topic","title":"cgSize","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/cgSize","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/longerSide":{"url":"\/documentation\/dotpalmcore\/imagesize\/longerside","type":"topic","kind":"symbol","title":"longerSide","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"longerSide","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","navigatorTitle":[{"text":"longerSide","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/longerSide","abstract":[]},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTImageSize"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/cgSize","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/height","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/longerSide","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/shorterSide","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/width"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculatePixelCount()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/init(width:height:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/from(cgSize:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImageSize","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"fromCgSize:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1from(cgSize:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1from(cgSize:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromCgSize:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1init(width:height:)\/title","op":"replace","value":"initWithWidth:height:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidth:height:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1init(width:height:)\/fragments","op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1description\/fragments"},{"value":"hash","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1hash\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1calculatePixelCount()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"}],"op":"replace"},{"value":"calculateWidthToHeightRatio","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1calculateWidthToHeightRatio()\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1calculateWidthToHeightRatio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateWidthToHeightRatio"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1shorterSide\/title","op":"replace","value":"shorterSide"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1shorterSide\/fragments","op":"replace","value":[{"kind":"identifier","text":"shorterSide"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1height\/title","value":"height","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1height\/fragments","value":[{"text":"height","kind":"identifier"}]},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1width\/title","value":"width"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1width\/fragments","value":[{"text":"width","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"cgSize","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1cgSize\/title"},{"value":[{"text":"cgSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1cgSize\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1longerSide\/title","value":"longerSide","op":"replace"},{"value":[{"kind":"identifier","text":"longerSide"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1longerSide\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}