{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/loggerloglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/loggerloglevel"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Available log levels."}],"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggerLogLevel"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel","role":"symbol","title":"LoggerLogLevel","symbolKind":"enum","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/debug","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/error","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/info","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/none","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/warning"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTLoggerLogLevel) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggerLogLevel","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/description":{"url":"\/documentation\/dotpalmcore\/loggerloglevel\/description","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/description","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/init(rawValue:)":{"type":"topic","url":"\/documentation\/dotpalmcore\/loggerloglevel\/init(rawvalue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SY","title":"Swift.RawRepresentable"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/debug":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/debug","type":"topic","url":"\/documentation\/dotpalmcore\/loggerloglevel\/debug","navigatorTitle":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"title":"LoggerLogLevel.debug","abstract":[{"type":"text","text":"Logs events suitable for debugging purposes."}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/loggerloglevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","title":"LoggerLogLevel","abstract":[{"type":"text","text":"Available log levels."}]},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/warning":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/warning","title":"LoggerLogLevel.warning","url":"\/documentation\/dotpalmcore\/loggerloglevel\/warning","type":"topic","navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/Equatable-Implementations":{"abstract":[],"type":"topic","kind":"article","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/dotpalmcore\/loggerloglevel\/equatable-implementations","role":"collectionGroup"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/none":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/none","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"Disables logging."}],"url":"\/documentation\/dotpalmcore\/loggerloglevel\/none","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"title":"LoggerLogLevel.none","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/error":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/loggerloglevel\/error","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"type":"topic","title":"LoggerLogLevel.error","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/error","abstract":[{"type":"text","text":"Logs failed operations and other errors."}]},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/info":{"type":"topic","abstract":[{"type":"text","text":"Logs informative events."}],"title":"LoggerLogLevel.info","role":"symbol","url":"\/documentation\/dotpalmcore\/loggerloglevel\/info","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"info","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/info","navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/RawRepresentable-Implementations":{"url":"\/documentation\/dotpalmcore\/loggerloglevel\/rawrepresentable-implementations","type":"topic","kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/RawRepresentable-Implementations","abstract":[]},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTLoggerLogLevel"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/debug","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/error","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/info","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/none","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/warning"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTLoggerLogLevel","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1debug\/title","value":"DOTLoggerLogLevelDebug"},{"op":"replace","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1debug\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1warning\/title","op":"replace","value":"DOTLoggerLogLevelWarning"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1warning\/fragments","value":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1none\/title","value":"DOTLoggerLogLevelNone","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1none\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1error\/title","value":"DOTLoggerLogLevelError","op":"replace"},{"value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1error\/fragments"},{"op":"replace","value":"DOTLoggerLogLevelInfo","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1info\/title"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1info\/fragments"}]}]}