{"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"variants":[{"paths":["\/documentation\/dotpalmcore\/rectangledouble"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/rectangledouble"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/init(left:top:right:bottom:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/bottom","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/cgRect","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/height","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/points","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/right","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/top","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/width","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/widthToHeightRatio"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/fullRectangle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/zeroRectangle"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/from(cgRect:)"]}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"title":"Palm detection output","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTRectangleDouble) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"]]},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble","modules":[{"name":"DotPalmCore"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/isEqual(_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/isEqual(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"isEqual(_:)","role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble\/isequal(_:)","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/fullRectangle":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/fullRectangle","title":"fullRectangle","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/rectangledouble\/fullrectangle","navigatorTitle":[{"text":"fullRectangle","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fullRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/init(left:top:right:bottom:)":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/init(left:top:right:bottom:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"left"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"top","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"right"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"bottom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"title":"init(left:top:right:bottom:)","type":"topic","url":"\/documentation\/dotpalmcore\/rectangledouble\/init(left:top:right:bottom:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/width":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/width","kind":"symbol","title":"width","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"width","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/rectangledouble\/width","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/rebased(parentRectangle:)":{"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"title":"rebased(parentRectangle:)","url":"\/documentation\/dotpalmcore\/rectangledouble\/rebased(parentrectangle:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/rebased(parentRectangle:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"text":"parentRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}]},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/bottom":{"kind":"symbol","navigatorTitle":[{"text":"bottom","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/rectangledouble\/bottom","abstract":[{"type":"text","text":"Bottom edge."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottom"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/bottom","title":"bottom"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/hash":{"kind":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/rectangledouble\/hash","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/hash","title":"hash"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/from(cgRect:)":{"url":"\/documentation\/dotpalmcore\/rectangledouble\/from(cgrect:)","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/from(cgRect:)","type":"topic","title":"from(cgRect:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"text":"cgRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/description":{"role":"symbol","title":"description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/description","abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"kind":"symbol","abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"url":"\/documentation\/dotpalmcore\/imageparameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"role":"symbol","type":"topic","title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm","kind":"symbol","abstract":[{"type":"text","text":"Result of the palm detection process."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Palm"}],"navigatorTitle":[{"kind":"identifier","text":"Palm"}],"title":"PalmDetector.Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/mirrored()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/mirrored()","abstract":[],"type":"topic","title":"mirrored()","kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble\/mirrored()","navigatorTitle":[{"kind":"identifier","text":"mirrored"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/top":{"url":"\/documentation\/dotpalmcore\/rectangledouble\/top","kind":"symbol","type":"topic","title":"top","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","navigatorTitle":[{"text":"top","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/top","abstract":[{"type":"text","text":"Top edge."}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/right":{"role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble\/right","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"right","kind":"symbol","navigatorTitle":[{"text":"right","kind":"identifier"}],"abstract":[{"text":"Right edge.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/right","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/zeroRectangle":{"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/zeroRectangle","navigatorTitle":[{"kind":"identifier","text":"zeroRectangle"}],"url":"\/documentation\/dotpalmcore\/rectangledouble\/zerorectangle","kind":"symbol","title":"zeroRectangle","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zeroRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}]},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","title":"RectangleDouble","role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/widthToHeightRatio":{"title":"widthToHeightRatio","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"widthToHeightRatio","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/widthToHeightRatio","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"widthToHeightRatio","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"url":"\/documentation\/dotpalmcore\/rectangledouble\/widthtoheightratio"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/left":{"abstract":[{"type":"text","text":"Left edge."}],"navigatorTitle":[{"text":"left","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/left","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble\/left","title":"left"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/height":{"url":"\/documentation\/dotpalmcore\/rectangledouble\/height","navigatorTitle":[{"kind":"identifier","text":"height"}],"title":"height","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/height","type":"topic"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/points":{"title":"points","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/points","abstract":[],"url":"\/documentation\/dotpalmcore\/rectangledouble\/points","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"points"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"text":"]","kind":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/cgRect":{"title":"cgRect","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/cgRect","url":"\/documentation\/dotpalmcore\/rectangledouble\/cgrect","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTRectangleDouble","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/bottom","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/cgRect","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/height","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/points","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/right","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/top","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/width","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/widthToHeightRatio"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/init(left:top:right:bottom:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/fullRectangle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/zeroRectangle"],"title":"Type Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/from(cgRect:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Palm detection output","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters"]}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTRectangleDouble"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1isEqual(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1fullRectangle\/title","value":"fullRectangle"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1fullRectangle\/fragments","op":"replace","value":[{"kind":"identifier","text":"fullRectangle"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"},{"op":"replace","value":"initWithLeft:top:right:bottom:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1init(left:top:right:bottom:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1init(left:top:right:bottom:)\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1width\/title","value":"width","op":"replace"},{"value":[{"text":"width","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1width\/fragments"},{"value":"rebasedWithParentRectangle:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1rebased(parentRectangle:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1rebased(parentRectangle:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1bottom\/title","value":"bottom"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1bottom\/fragments","value":[{"kind":"identifier","text":"bottom"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1hash\/title","op":"replace","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1from(cgRect:)\/title","op":"replace","value":"fromCgRect:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1from(cgRect:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromCgRect:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1description\/title","op":"replace","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1description\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","op":"replace","value":"DOTPImageParameters"},{"value":[{"text":"DOTPImageParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments","op":"replace"},{"value":"mirrored","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1mirrored()\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1mirrored()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1top\/title","value":"top"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1top\/fragments","value":[{"kind":"identifier","text":"top"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1right\/title","value":"right","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"right"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1right\/fragments"},{"value":"zeroRectangle","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1zeroRectangle\/title","op":"replace"},{"value":[{"text":"zeroRectangle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1zeroRectangle\/fragments","op":"replace"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments"},{"value":"widthToHeightRatio","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1widthToHeightRatio\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1widthToHeightRatio\/fragments","value":[{"text":"widthToHeightRatio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1left\/title","value":"left"},{"value":[{"text":"left","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1left\/fragments"},{"value":"height","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1height\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1height\/fragments","value":[{"kind":"identifier","text":"height"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1points\/title","value":"points"},{"value":[{"kind":"identifier","text":"points"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1points\/fragments"},{"op":"replace","value":"cgRect","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1cgRect\/title"},{"op":"replace","value":[{"kind":"identifier","text":"cgRect"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1cgRect\/fragments"}]}]}