{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"Default is:","type":"text"}],"type":"paragraph"},{"syntax":null,"code":[".init(cameraFacing: .front)"],"type":"codeListing"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/camera"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/camera"},"metadata":{"role":"symbol","title":"camera","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC6camera0aF006CameraI0Cvp","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"BaseFaceAutoCaptureViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"title":"BaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing face images with customizable UI."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","title":"CameraConfiguration","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"url":"\/documentation\/dotfacelite\/cameraconfiguration","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/camera":{"type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"title":"camera","role":"symbol","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/camera","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/camera","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFLBaseFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title"},{"value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle"}]}]}