{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","text":"CaptureMode","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"externalID":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC11captureMode0aF00fK0Ovp","roleHeading":"Instance Property","title":"captureMode","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode"},"abstract":[{"type":"text","text":"Capture mode. Default value is "},{"code":".autoCapture","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/capturemode"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/captureMode":{"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/capturemode","abstract":[{"type":"text","text":"Capture mode. Default value is "},{"code":".autoCapture","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier"}],"kind":"symbol","title":"captureMode","role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}],"title":"CaptureMode","type":"topic","url":"\/documentation\/dotfacelite\/capturemode","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"BaseFaceAutoCaptureViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing face images with customizable UI.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"title":"BaseFaceAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title","op":"replace","value":"DOTCaptureMode"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFLBaseFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}]},{"value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}