{"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection"],"anchor":"Type-Properties","title":"Type Properties","generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"struct","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"externalID":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV","title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","modules":[{"name":"DotFaceLite"}],"roleHeading":"Structure","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Defaults"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/Defaults/captureMode":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"abstract":[],"title":"captureMode","type":"topic","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults\/capturemode","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"BaseFaceAutoCaptureViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/Defaults/candidateSelectionDurationMillis":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"title":"candidateSelectionDurationMillis","type":"topic","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults\/candidateselectiondurationmillis","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/Defaults/minValidSamplesInRowToStartCandidateSelection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"title":"minValidSamplesInRowToStartCandidateSelection","type":"topic","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults\/minvalidsamplesinrowtostartcandidateselection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing face images with customizable UI.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"title":"BaseFaceAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/Defaults":{"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","type":"topic","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFLBaseFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}