{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraPreviewScaleType","text":"CameraPreviewScaleType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessconfiguration\/defaults\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration\/Defaults\/cameraPreviewScaleType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraPreviewScaleType"}],"title":"cameraPreviewScaleType","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore26SmileLivenessConfigurationC8DefaultsV22cameraPreviewScaleTypeAA06CameraijK0OvpZ","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration\/Defaults"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessViewController":{"role":"symbol","title":"SmileLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessConfiguration":{"role":"symbol","title":"SmileLivenessConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the smile liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessConfiguration"}],"url":"\/documentation\/dotfacecore\/smilelivenessconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessConfiguration/Defaults/cameraPreviewScaleType":{"role":"symbol","title":"cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraPreviewScaleType"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration\/Defaults\/cameraPreviewScaleType","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessconfiguration\/defaults\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessConfiguration/Defaults":{"role":"symbol","title":"SmileLivenessConfiguration.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacecore\/smilelivenessconfiguration\/defaults"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTFCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTFCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessConfiguration\/title","value":"DOTFSmileLivenessConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}