{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/qualityattributethresholds"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC26qualityAttributeThresholdsAA0bef7QualitykL0Cvp","title":"qualityAttributeThresholds","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"codeVoice","code":".standard"},{"type":"text","text":" preset."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds","text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"role":"symbol","title":"qualityAttributeThresholds","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/qualityattributethresholds","abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"code":".standard","type":"codeVoice"},{"type":"text","text":" preset."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","title":"BaseFingersAutoCaptureViewController.Configuration","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFGBaseFingersAutoCaptureViewController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}