{"variants":[{"paths":["\/documentation\/dotfacecore\/facedetector\/face\/confidence"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/confidence","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confidence","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"abstract":[{"type":"text","text":"Confidence of the detection in interval "},{"type":"codeVoice","code":"[0.0, 1.0]"},{"type":"text","text":", where "},{"type":"codeVoice","code":"0.0"},{"text":" stands for min confidence and ","type":"text"},{"code":"1.0","type":"codeVoice"},{"text":" stands for max confidence.","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confidence","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceCore0B8DetectorC0B0C10confidenceSdvp","title":"confidence","symbolKind":"property","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/confidence":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confidence","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotfacecore\/facedetector\/face\/confidence","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/confidence","abstract":[{"type":"text","text":"Confidence of the detection in interval "},{"type":"codeVoice","code":"[0.0, 1.0]"},{"type":"text","text":", where "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":" stands for min confidence and "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":" stands for max confidence."}],"title":"confidence","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","kind":"symbol","role":"symbol","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"navigatorTitle":[{"text":"Face","kind":"identifier"}],"title":"FaceDetector.Face","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","abstract":[{"text":"Detected face in the image.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}