{"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/right"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/right"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"right","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)right","navigatorTitle":[{"kind":"identifier","text":"right"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Right edge."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/right","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/RectangleDouble/right":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","url":"\/documentation\/dotdocument\/rectangledouble\/right","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/right","title":"right","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"right"}],"abstract":[{"type":"text","text":"Right edge."}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"kind":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"type":"topic","title":"RectangleDouble","url":"\/documentation\/dotdocument\/rectangledouble","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"right","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"right","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"right","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1right\/title"},{"op":"replace","value":[{"kind":"identifier","text":"right"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1right\/fragments"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}