{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"title":"from(cgRect:)","extendedModule":"DotCore","role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(cm)fromCgRect:","roleHeading":"Type Method","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","kind":"typeIdentifier","text":"RectangleInt"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/from(cgRect:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/rectangleint\/from(cgrect:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/rectangleint\/from(cgrect:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/RectangleInt/from(cgRect:)":{"navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"abstract":[],"title":"from(cgRect:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/from(cgRect:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt"}],"kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint\/from(cgrect:)"},"doc://DotDocument/documentation/DotDocument/RectangleInt":{"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"kind":"symbol","url":"\/documentation\/dotdocument\/rectangleint","navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"type":"topic","role":"symbol","title":"RectangleInt","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"fromCgRect:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTRectangleInt","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt"},{"text":" *) ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"cgRect","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1from(cgRect:)\/title","value":"fromCgRect:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1from(cgRect:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/title","value":"DOTRectangleInt"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/fragments","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleInt"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}