{"metadata":{"symbolKind":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLDevicePitchTooHighValidator(im)init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initialize with default angle in degrees."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/init()"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DevicePitchTooHighValidator":{"role":"symbol","navigatorTitle":[{"text":"DevicePitchTooHighValidator","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","abstract":[{"text":"Validate maximum pitch angle of the device.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevicePitchTooHighValidator","kind":"identifier"}],"title":"DevicePitchTooHighValidator"},"doc://DotFaceLite/documentation/DotFaceLite/DevicePitchTooHighValidator/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init()","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/init()","role":"symbol","type":"topic","abstract":[{"text":"Initialize with default angle in degrees.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/title","value":"DOTFLDevicePitchTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLDevicePitchTooHighValidator"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}