{"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isVideoCaptureEnabled","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Use this flag to enable\/disable video capture."},{"type":"text","text":" "},{"type":"text","text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session."},{"type":"text","text":" "},{"type":"text","text":"The captured video is included exclusively in the binary content of the result. Default is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration"]]},"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isVideoCaptureEnabled","title":"isVideoCaptureEnabled","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/isvideocaptureenabled"]},{"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/isvideocaptureenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/isVideoCaptureEnabled":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isVideoCaptureEnabled","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isVideoCaptureEnabled"}],"url":"\/documentation\/dotpalmcore\/cameraconfiguration\/isvideocaptureenabled","role":"symbol","abstract":[{"type":"text","text":"Use this flag to enable\/disable video capture."},{"type":"text","text":" "},{"type":"text","text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session."},{"type":"text","text":" "},{"type":"text","text":"The captured video is included exclusively in the binary content of the result. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"title":"isVideoCaptureEnabled"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration":{"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"title":"CameraConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"url":"\/documentation\/dotpalmcore\/cameraconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isVideoCaptureEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"isVideoCaptureEnabled"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isVideoCaptureEnabled","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isVideoCaptureEnabled\/title"},{"value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isVideoCaptureEnabled\/fragments"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/fragments"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}