{"sections":[],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult\/detection","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult\/detection"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC9detectionAA0bdE9DetectionCvp","title":"detection","symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult/detection":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier","text":"FaceAutoCaptureDetection"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult\/detection","type":"topic","title":"detection","role":"symbol","abstract":[{"text":"The result of processing video frame during the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult\/detection"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetection","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"title":"FaceAutoCaptureDetection","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","title":"FaceAutoCaptureController.ProcessingResult","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult","abstract":[{"text":"The result returned from the processing of one image during the face auto capture process.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessingResult"}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]}]}]}