{"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessResult(py)bgraRawImage","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"bgraRawImage"}],"title":"bgraRawImage","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bgraRawImage","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/bgraRawImage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Captured face image."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessresult\/bgrarawimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessresult\/bgrarawimage"]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","title":"MagnifEyeLivenessViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","abstract":[{"text":"version: 8.3.1","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"title":"MagnifEyeLivenessResult","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessResult"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessresult","kind":"symbol","abstract":[{"type":"text","text":"The final result of the MagnifEye liveness process."}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","kind":"symbol","title":"BgraRawImage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","url":"\/documentation\/dotfacelite\/bgrarawimage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessResult/bgraRawImage":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"}],"title":"bgraRawImage","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/bgraRawImage","navigatorTitle":[{"kind":"identifier","text":"bgraRawImage"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessresult\/bgrarawimage","kind":"symbol","abstract":[{"type":"text","text":"Captured face image."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bgraRawImage"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"bgraRawImage"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bgraRawImage"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/title","value":"DOTFLMagnifEyeLivenessResult","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessResult","kind":"identifier"}]},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"value":"bgraRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1bgraRawImage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1bgraRawImage\/fragments","value":[{"kind":"identifier","text":"bgraRawImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}