{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"recoverySuggestion","modules":[{"name":"DotFingersCore","relatedModules":["Foundation"]}],"externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:14DotFingersCore30FingerToFingerprintTransformerC5ErrorO","roleHeading":"Instance Property","platforms":[{"unavailable":false,"beta":false,"deprecated":false,"name":"iOS","introducedAt":"8.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS","introducedAt":"8.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"8.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"macOS","introducedAt":"10.10"},{"unavailable":false,"beta":false,"deprecated":false,"name":"tvOS","introducedAt":"9.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"watchOS","introducedAt":"2.0"}],"role":"symbol","extendedModule":"Foundation"},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/recoverySuggestion","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/recoverysuggestion"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error/recoverySuggestion":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"recoverySuggestion","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/recoverySuggestion","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"kind":"symbol","role":"symbol","title":"FingerToFingerprintTransformer","abstract":[{"text":"Stateless class which transforms detected finger images into fingerprint images.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error","title":"FingerToFingerprintTransformer.Error","role":"symbol","abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingerToFingerprintTransformer","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/title","op":"replace"},{"value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/navigatorTitle","op":"replace"}]}]}