{"abstract":[{"type":"text","text":"Right edge."}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/right","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/rectangleint\/right"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/rectangleint\/right"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt(py)right","navigatorTitle":[{"kind":"identifier","text":"right"}],"modules":[{"name":"DotFaceCore"}],"title":"right","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"symbolKind":"property"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt":{"url":"\/documentation\/dotfacecore\/rectangleint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}],"kind":"symbol","title":"RectangleInt"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/right":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/right","title":"right","url":"\/documentation\/dotfacecore\/rectangleint\/right","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"right"}],"abstract":[{"type":"text","text":"Right edge."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"right","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"right"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/fragments"},{"op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/navigatorTitle"},{"op":"replace","value":"right","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1right\/title"},{"op":"replace","value":[{"text":"right","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1right\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}