{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:"},"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:iscamerapreviewvisible:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDQualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","text":"DOTDQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validationMode:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","text":"DOTDValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"validationMode"},{"text":" ","kind":"text"},{"text":"mrzValidation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","text":"DOTDMrzValidation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"mrzValidation"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","kind":"typeIdentifier","text":"DOTDPlaceholderType"},{"kind":"text","text":") "},{"text":"placeholderType","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCameraPreviewVisible:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"]]},"metadata":{"symbolKind":"method","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:"}],"navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:","kind":"identifier"}],"title":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:","roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"kind":"symbol","sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DOTDQualityAttributeThresholds":{"title":"DOTDQualityAttributeThresholds","fragments":[{"kind":"identifier","text":"DOTDQualityAttributeThresholds"}],"url":"\/documentation\/dotdocument\/dotdqualityattributethresholds","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration":{"fragments":[{"text":"DOTDDocumentAutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration","title":"DOTDDocumentAutoCaptureConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","kind":"symbol","abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MrzValidation","kind":"identifier"}],"navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzvalidation","title":"MrzValidation","type":"topic"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","title":"CameraPreviewScaleType"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","abstract":[],"title":"ValidationMode","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/validationmode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","kind":"symbol","url":"\/documentation\/dotdocument\/placeholdertype","type":"topic","abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"title":"PlaceholderType"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:iscamerapreviewvisible:","title":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:","kind":"symbol","abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","title":"CameraFacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotdocument\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTDValidationMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}]},{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments"}]}]}