{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"]]},"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAttributeThresholds:"},{"kind":"text","text":"("},{"text":"DOTDQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDQualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","text":"DOTDValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validationMode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"mrzValidation:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"DOTDMrzValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"mrzValidation"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","text":"DOTCameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":" "},{"text":"placeholderType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTDPlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"placeholderType"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:"},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","symbolKind":"method","title":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","roleHeading":"Instance Method"},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration","url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration","title":"DOTDDocumentAutoCaptureConfiguration","role":"symbol","kind":"symbol","fragments":[{"text":"DOTDDocumentAutoCaptureConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholdertype","abstract":[{"text":"Represents the type of placeholder used in document auto-capture UI.","type":"text"}],"type":"topic","title":"PlaceholderType","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","type":"topic","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:","role":"symbol","kind":"symbol","title":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:"}]},"doc://DotDocument/documentation/DotDocument/DOTDQualityAttributeThresholds":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","fragments":[{"text":"DOTDQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdqualityattributethresholds","type":"topic","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"kind":"symbol","title":"DOTDQualityAttributeThresholds","role":"symbol"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/validationmode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationMode"}],"title":"ValidationMode","navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","type":"topic","url":"\/documentation\/dotdocument\/camerafacing","title":"CameraFacing","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype","title":"CameraPreviewScaleType","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"url":"\/documentation\/dotdocument\/mrzvalidation","role":"symbol","kind":"symbol","title":"MrzValidation","abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"op":"replace","value":[{"text":"DOTDValidationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments"},{"value":"DOTDMrzValidation","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"op":"replace"}]}]}