{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/placeholder"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDPlaceholder","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","text":"DOTDPlaceholder"},{"kind":"text","text":" * "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"placeholder","kind":"identifier"}],"role":"symbol","fragments":[{"text":"placeholder","kind":"identifier"}],"title":"placeholder","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration(py)placeholder"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/placeholder","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Specify the placeholder. Default is "},{"type":"text","text":".Visible"},{"type":"text","text":"."}],"references":{"doc://DotDocument/documentation/DotDocument/Placeholder":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotdocument\/placeholder","type":"topic","abstract":[{"type":"text","text":"Placeholder."}],"title":"Placeholder","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration/placeholder":{"role":"symbol","fragments":[{"text":"placeholder","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/placeholder","title":"placeholder","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/placeholder","abstract":[{"type":"text","text":"Specify the placeholder. Default is "},{"type":"text","text":".Visible"},{"type":"text","text":"."}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration":{"kind":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureConfiguration"}],"title":"DOTDDocumentAutoCaptureConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the UI Document Auto Capture component."}],"type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title","value":"DOTDPlaceholder","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholder"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDPlaceholder"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}