{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)description"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/description"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/description"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/description":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/description","title":"description"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration":{"type":"topic","kind":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","title":"CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/cameraconfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1description\/fragments"},{"op":"replace","value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}