{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"facing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","kind":"typeIdentifier","text":"CameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewScaleType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType"},{"kind":"text","text":" = .fit, "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"isPreviewVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = true)"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:"}],"title":"init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","role":"symbol","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(im)initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"facing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isPreviewVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"symbolKind":"init","modules":[{"name":"DotPalmCore"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration":{"type":"topic","kind":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","title":"CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/cameraconfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/camerafacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","role":"symbol","title":"CameraPreviewScaleType","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)","title":"init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","navigatorTitle":[{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"facing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraFacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"facing"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"previewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isPreviewVisible"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/title"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/navigatorTitle"},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/navigatorTitle"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/navigatorTitle"},{"value":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}