{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","text":"ImageSize"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/bgrarawimage\/init(bytespointer:size:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/bgrarawimage\/init(bytespointer:size:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/init(bytesPointer:size:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgraRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"title":"init(bytesPointer:size:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTBgraRawImage(im)initWithBytesPointer:size:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"],["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"],["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"role":"symbol","title":"BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotdocument\/bgrarawimage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage/init(bytesPointer:size:)":{"role":"symbol","title":"init(bytesPointer:size:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgraRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage\/init(bytesPointer:size:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"url":"\/documentation\/dotdocument\/bgrarawimage\/init(bytespointer:size:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageSize":{"role":"symbol","title":"ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotdocument\/imagesize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBytesPointer:size:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBytesPointer:size:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBytesPointer:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"uint8_t","preciseIdentifier":"c:@T@uint8_t"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bytesPointer"},{"kind":"text","text":" "},{"kind":"identifier","text":"size:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","text":"DOTImageSize"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage~1init(bytesPointer:size:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBytesPointer:size:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}