{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"]]},"abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"role":"symbol","title":"DotLibraryId.faceLite","roleHeading":"Case","modules":[{"name":"DotNfc"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFaceLite"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/faceLite"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotlibraryid\/facelite"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotlibraryid\/facelite"]}],"references":{"doc://DotNfc/documentation/DotNfc/DotLibraryId/faceLite":{"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/faceLite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"}],"kind":"symbol","abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"text":" identifier.","type":"text"}],"url":"\/documentation\/dotnfc\/dotlibraryid\/facelite","role":"symbol","type":"topic","title":"DotLibraryId.faceLite"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"kind":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotlibraryid","title":"DotLibraryId","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotLibraryIdFaceLite","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1faceLite\/title","value":"DotLibraryIdFaceLite","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1faceLite\/fragments","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/navigatorTitle","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"}]}]}