{"metadata":{"roleHeading":"Initializer","externalID":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles(im)initWithPitch:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"title":"init(pitch:)","role":"symbol","symbolKind":"init","modules":[{"name":"DotFaceLite"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles\/init(pitch:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/tiltangles\/init(pitch:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/tiltangles\/init(pitch:)"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/TiltAngles/init(pitch:)":{"url":"\/documentation\/dotfacelite\/tiltangles\/init(pitch:)","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles\/init(pitch:)","title":"init(pitch:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPitch:"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","kind":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"type":"link"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/TiltAngles":{"url":"\/documentation\/dotfacelite\/tiltangles","role":"symbol","title":"TiltAngles","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Tilt angles."},{"text":" ","type":"text"},{"text":"Also see ","type":"text"},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"text":".","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPitch:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPitch:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"pitch"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"initWithPitch:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles~1init(pitch:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles~1init(pitch:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPitch:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/title","op":"replace","value":"DOTTiltAngles"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTiltAngles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}