{"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiStateRunning(py)detection","symbolKind":"property","fragments":[{"kind":"identifier","text":"detection"}],"title":"detection","navigatorTitle":[{"text":"detection","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","text":"DOTFFaceAutoCaptureDetection"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detection"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/detection","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/detection":{"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/detection","type":"topic","abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/detection","kind":"symbol","title":"detection","fragments":[{"kind":"identifier","text":"detection"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning":{"type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning","kind":"symbol","title":"DOTFFaceAutoCaptureUiStateRunning","fragments":[{"text":"DOTFFaceAutoCaptureUiStateRunning","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"abstract":[{"text":"The result of processing video frame during the face auto capture process.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"kind":"symbol","role":"symbol","title":"FaceAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"url":"\/documentation\/dotfacecore\/faceautocapturedetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}