{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/deviceTiltAngles"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TiltAngles","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles"},{"kind":"text","text":"?"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles","kind":"identifier"},{"kind":"text","text":": "},{"text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters(py)deviceTiltAngles","navigatorTitle":[{"kind":"identifier","text":"deviceTiltAngles"}],"roleHeading":"Instance Property","symbolKind":"property","title":"deviceTiltAngles"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/devicetiltangles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/devicetiltangles"]}],"sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/deviceTiltAngles":{"url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/devicetiltangles","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles","kind":"typeIdentifier","text":"TiltAngles"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/deviceTiltAngles","kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"deviceTiltAngles","kind":"identifier"}],"title":"deviceTiltAngles"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/TiltAngles":{"url":"\/documentation\/dotfacelite\/tiltangles","title":"TiltAngles","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"type":"topic","abstract":[{"type":"text","text":"Tilt angles."},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}]},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"title":"FaceAutoCaptureFrameParameters","navigatorTitle":[{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected face."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"deviceTiltAngles"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"deviceTiltAngles"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTTiltAngles","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles"},{"text":" * ","kind":"text"},{"text":"deviceTiltAngles","kind":"identifier"}]}]}},{"op":"replace","value":"deviceTiltAngles","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1deviceTiltAngles\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1deviceTiltAngles\/fragments","value":[{"kind":"identifier","text":"deviceTiltAngles"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/title","value":"DOTTiltAngles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","op":"replace","value":"DOTFLFaceAutoCaptureFrameParameters"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments"},{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}