{"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC","role":"symbol","roleHeading":"Class","modules":[{"name":"DotFaceLite"}],"symbolKind":"class","title":"MultiRangeLivenessViewController.Configuration","extendedModule":"DotFaceLite","navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController"]]},"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults"],"anchor":"Structures","title":"Structures","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/init(common:camera:challengeSequence:isDetectionLayerVisible:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/camera","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/challengeSequence","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/common","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/isDetectionLayerVisible"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLMultiRangeLivenessConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class"},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/challengeSequence":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"challengeSequence"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC","text":"Wrapped"},{"kind":"text","text":"]"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/challengeSequence","title":"challengeSequence","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/challengesequence","kind":"symbol","abstract":[{"type":"text","text":"List of Multi-Range challenge items. This list represents a liveness challenge and should be obtained from the DIS (Digital Identity Service). The minimum number of items is 4."}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","title":"MultiRangeLivenessViewController.Configuration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/Defaults":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults","abstract":[],"title":"MultiRangeLivenessViewController.Configuration.Defaults"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/isDetectionLayerVisible":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"isDetectionLayerVisible","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/isDetectionLayerVisible","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/isdetectionlayervisible","abstract":[{"type":"text","text":"Use this flag to show or hide detection circle during the Multi-Range Liveness process. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"kind":"symbol"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"role":"symbol","title":"MultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/init(common:camera:challengeSequence:isDetectionLayerVisible:)":{"type":"topic","abstract":[{"type":"text","text":"Create the Multi-Range Liveness configuration."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/init(common:camera:challengesequence:isdetectionlayervisible:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/init(common:camera:challengeSequence:isDetectionLayerVisible:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":", ","kind":"text"},{"text":"challengeSequence","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","text":"MultiRangeLivenessChallengeItem"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:14DotFaceCommons31MultiRangeLivenessChallengeItemO7WrappedC"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol","title":"init(common:camera:challengeSequence:isDetectionLayerVisible:)"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/common":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"role":"symbol","title":"common","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/common","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/common","abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"type":"codeVoice","code":".init()"},{"type":"text","text":"."}],"kind":"symbol"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/description":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/description","kind":"symbol","type":"topic","role":"symbol","title":"description","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/camera":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"}],"role":"symbol","title":"camera","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/camera","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/camera","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"kind":"symbol"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}