{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","text":"BaseFingersAutoCaptureViewController"},{"kind":"text","text":"."},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholder","text":"Placeholder"},{"kind":"text","text":" = .Visible())"}]}]}],"abstract":[{"type":"text","text":"Create the fingers auto capture configuration."}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Placeholder","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholder"},{"kind":"text","text":")"}],"externalID":"s:14DotFingersCore0B25AutoCaptureViewControllerC13ConfigurationC04baseH023isDetectionLayerVisible11placeholderAeA04BasebdefG0CADC_SbAA11PlaceholderCtcfc","symbolKind":"init","modules":[{"name":"DotFingersCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","title":"BaseFingersAutoCaptureViewController.Configuration","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Configuration-swift.class/init(baseConfiguration:isDetectionLayerVisible:placeholder:)":{"role":"symbol","title":"init(baseConfiguration:isDetectionLayerVisible:placeholder:)","type":"topic","abstract":[{"text":"Create the fingers auto capture configuration.","type":"text"}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placeholder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholder","text":"Placeholder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class\/init(baseconfiguration:isdetectionlayervisible:placeholder:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class\/init(baseConfiguration:isDetectionLayerVisible:placeholder:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","type":"topic","title":"FingersAutoCaptureViewController","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI Fingers Auto Capture component."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureViewController"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"role":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"abstract":[{"type":"text","text":"Placeholder."}],"url":"\/documentation\/dotfingerscore\/placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","title":"FingersAutoCaptureViewController.Configuration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Fingers Auto Capture component."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingersAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/navigatorTitle"},{"value":"DOTFGPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle"},{"value":"DOTFGBaseFingersAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle"}]}]}