{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble"}]}],"kind":"declarations"}],"metadata":{"title":"faceSizeRatioInterval","roleHeading":"Instance Property","role":"symbol","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC21faceSizeRatioIntervalAA0L6DoubleCvp","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"sections":[],"abstract":[{"text":"Interval used for calculating minimal and maximal face size in image in range [0.0, 1.0]. Default is ","type":"text"},{"code":"[0.1, 0.3]","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/faceSizeRatioInterval","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/facesizeratiointerval"]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/faceSizeRatioInterval":{"title":"faceSizeRatioInterval","role":"symbol","abstract":[{"text":"Interval used for calculating minimal and maximal face size in image in range [0.0, 1.0]. Default is ","type":"text"},{"type":"codeVoice","code":"[0.1, 0.3]"},{"text":".","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceSizeRatioInterval","kind":"identifier"},{"kind":"text","text":": "},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/facesizeratiointerval","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/faceSizeRatioInterval","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"title":"FaceAutoCaptureViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"FaceAutoCaptureViewController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments"}]}]}