{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"lines"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td2"},{"kind":"text","text":": "},{"text":"Td2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"init","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone(im)initWithLines:td2:","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td2"},{"kind":"text","text":": "},{"text":"Td2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"init(lines:td2:)","navigatorTitle":[{"text":"initWithLines:td2:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td2:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/init(lines:td2:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/init(lines:td2:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","url":"\/documentation\/dotnfc\/td2machinereadablezone","title":"Td2MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/init(lines:td2:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td2:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/machinereadablezone\/init(lines:td2:)","kind":"symbol","type":"topic","title":"init(lines:td2:)","role":"symbol","navigatorTitle":[{"text":"initWithLines:td2:","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone":{"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","title":"MachineReadableZone"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithLines:td2:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLines:td2:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithLines:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"lines"},{"kind":"text","text":" "},{"text":"td2:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","text":"DOTTd2MachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"},{"text":" *) ","kind":"text"},{"text":"td2","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone","op":"replace"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td2:)\/title","value":"initWithLines:td2:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td2:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLines:td2:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}