{"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"init","title":"init(format:bytes:size:)","externalID":"s:7DotCore5ImageC6format5bytes4sizeAcA0C6FormatO_10Foundation4DataVAA0C4SizeCtcfc","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/image\/init(format:bytes:size:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/init(format:bytes:size:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","url":"\/documentation\/dotfacelite\/imagesize","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize"},"doc://DotFaceLite/documentation/DotFaceLite/Image/init(format:bytes:size:)":{"url":"\/documentation\/dotfacelite\/image\/init(format:bytes:size:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/init(format:bytes:size:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"},{"text":", ","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","title":"init(format:bytes:size:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"role":"symbol","title":"Image","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat","abstract":[{"text":"Supported image formats.","type":"text"}],"url":"\/documentation\/dotfacelite\/imageformat","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","role":"symbol","type":"topic","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"url":"\/documentation\/dotfacelite\/facedetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","kind":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle"},{"value":"DOTImageFormat","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle"},{"value":"DOTFLFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}