{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/configuration","interfaceLanguage":"swift"},"abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"type":"text","text":" configuration."}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"property","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DotPalmLibrary(py)configuration","title":"configuration","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"configuration","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/configuration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/configuration"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary/configuration":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration"}],"title":"configuration","url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/configuration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/configuration","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"type":"text","text":" configuration."}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"type":"topic","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","abstract":[{"text":"Configuration of the ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library. This class specifies how the "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library will be initialized."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.13.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","type":"topic","url":"\/documentation\/dotpalmcore\/dotpalmlibrary","navigatorTitle":[{"text":"DotPalmLibrary","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library initialization."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmLibrary"}],"kind":"symbol","title":"DotPalmLibrary"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"configuration"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"configuration","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":" * "},{"text":"configuration","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"configuration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1configuration\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1configuration\/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"value":"DotPalmLibrary","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments","value":[{"kind":"identifier","text":"DotPalmLibrary"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}