{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/init(configuration:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/init(configuration:)"]},{"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/init(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary"]]},"metadata":{"symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration"},{"text":")","kind":"text"}],"title":"init(configuration:)","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DotPalmLibrary(im)initWithConfiguration:","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" configuration.","type":"text"}]}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Init "},{"type":"codeVoice","code":"DotPalmLibrary"},{"type":"text","text":"."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary/init(configuration:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Init "},{"type":"codeVoice","code":"DotPalmLibrary"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/init(configuration:)","url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/init(configuration:)","title":"init(configuration:)","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary":{"url":"\/documentation\/dotpalmcore\/dotpalmlibrary","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","role":"symbol","navigatorTitle":[{"text":"DotPalmLibrary","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmLibrary"}],"title":"DotPalmLibrary","type":"topic","abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library initialization."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"type":"topic","title":"DotPalmLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library. This class specifies how the "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library will be initialized."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithConfiguration:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","value":"initWithConfiguration:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1init(configuration:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1init(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/title","op":"replace","value":"DotPalmLibrary"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibrary"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}