{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample\/initWithImage:timestampMillis:depthImage:cameraCalibrationData:"},"metadata":{"navigatorTitle":[{"text":"initWithImage:timestampMillis:depthImage:cameraCalibrationData:","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerPhotoSample(im)initWithImage:timestampMillis:depthImage:cameraCalibrationData:","symbolKind":"method","roleHeading":"Instance Method","title":"initWithImage:timestampMillis:depthImage:cameraCalibrationData:","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:timestampMillis:depthImage:cameraCalibrationData:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timestampMillis:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"timestampMillis","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"depthImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":" *) ","kind":"text"},{"text":"depthImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraCalibrationData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVCameraCalibrationData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCameraCalibrationData"},{"text":" *) ","kind":"text"},{"text":"cameraCalibrationData","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerphotosample\/initwithimage:timestampmillis:depthimage:cameracalibrationdata:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerPhotoSample":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample","fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureControllerPhotoSample"}],"kind":"symbol","role":"symbol","title":"DOTFGFingersAutoCaptureControllerPhotoSample","abstract":[{"text":"The photo-capture sample, supplied in response to a ","type":"text"},{"text":".captureDepth","type":"text"},{"text":" event during the fingers auto capture process.","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerphotosample"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerPhotoSample/initWithImage:timestampMillis:depthImage:cameraCalibrationData:":{"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerphotosample\/initwithimage:timestampmillis:depthimage:cameracalibrationdata:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:timestampMillis:depthImage:cameraCalibrationData:","kind":"identifier"}],"title":"initWithImage:timestampMillis:depthImage:cameraCalibrationData:","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample\/initWithImage:timestampMillis:depthImage:cameraCalibrationData:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithImage:timestampMillis:depthImage:cameraCalibrationData:","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTImage","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","op":"replace","value":[{"text":"DOTImage","kind":"identifier"}]}]}]}