{"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/!=(_:_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/Equatable-Implementations"]]},"sections":[],"metadata":{"modules":[{"name":"DotNfc","relatedModules":["Swift"]}],"title":"!=(_:_:)","symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotNfc@E@DOTNAccessControlProtocol","extendedModule":"Swift","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Operator"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/accesscontrolprotocol\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/!=(_:_:)":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/!=(_:_:)","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/!=(_:_:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/Equatable-Implementations","kind":"article","type":"topic","title":"Equatable Implementations","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/equatable-implementations"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/accesscontrolprotocol","title":"AccessControlProtocol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","abstract":[{"text":"Access Control protocol.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTNAccessControlProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}