{"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/qualityattributethresholds"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Customize thresholds for the quality attributes of the capture result. Default is ","type":"text"},{"code":".passiveLiveness","type":"codeVoice"},{"text":" preset.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration"]]},"metadata":{"externalID":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC26qualityAttributeThresholdsAA0bef7QualitykL0Cvp","title":"qualityAttributeThresholds","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","type":"topic","title":"BaseFaceAutoCaptureViewController","role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing high quality face images with customizable UI.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","type":"topic","title":"qualityAttributeThresholds","role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/qualityattributethresholds","abstract":[{"text":"Customize thresholds for the quality attributes of the capture result. Default is ","type":"text"},{"code":".passiveLiveness","type":"codeVoice"},{"text":" preset.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","type":"topic","title":"BaseFaceAutoCaptureViewController.Configuration","role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","type":"topic","title":"FaceAutoCaptureQualityAttributeThresholds","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFBaseFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTFFaceAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}