{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/palmQuality","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"palmQuality","kind":"identifier"},{"kind":"text","text":": "},{"text":"PalmQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality"}],"role":"symbol","externalID":"s:11DotPalmCore0B8DetectorC0B0C11palmQualityAA0bF0Cvp","symbolKind":"property","modules":[{"name":"DotPalmCore"}],"title":"palmQuality"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/palmquality"]}],"abstract":[{"text":"Palm quality.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmQuality"},{"kind":"text","text":": "},{"text":"PalmQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"}],"languages":["swift"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/palmQuality":{"abstract":[{"text":"Palm quality.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/palmQuality","type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/palmquality","kind":"symbol","title":"palmQuality","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"palmQuality","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","kind":"typeIdentifier","text":"PalmQuality"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"title":"PalmDetector.Palm","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","abstract":[{"type":"text","text":"Result of the palm detection process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Palm","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Palm"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","kind":"symbol","title":"PalmDetector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmDetector"}],"navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.14.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmQuality","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}],"type":"topic","abstract":[{"type":"text","text":"Palm quality."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmquality","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","title":"PalmQuality"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace"},{"value":"DOTPPalmQuality","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmQuality"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}