{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","text":"PalmImageQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateExtractionQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithImageQuality:templateExtractionQuality:","kind":"identifier"}],"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}],"title":"init(imageQuality:templateExtractionQuality:)","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality(im)initWithImageQuality:templateExtractionQuality:"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/init(imageQuality:templateExtractionQuality:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmImageQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality"},{"text":", ","kind":"text"},{"text":"templateExtractionQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmquality\/init(imagequality:templateextractionquality:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmquality\/init(imagequality:templateextractionquality:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmQuality"}],"abstract":[{"text":"Palm quality.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmquality","navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}],"title":"PalmQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/init(imageQuality:templateExtractionQuality:)":{"url":"\/documentation\/dotpalmcore\/palmquality\/init(imagequality:templateextractionquality:)","title":"init(imageQuality:templateExtractionQuality:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","text":"PalmImageQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateExtractionQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithImageQuality:templateExtractionQuality:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/init(imageQuality:templateExtractionQuality:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","title":"PalmImageQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmImageQuality","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmimagequality","abstract":[{"type":"text","text":"Palm image quality."}],"role":"symbol","navigatorTitle":[{"text":"PalmImageQuality","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithImageQuality:templateExtractionQuality:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageQuality:templateExtractionQuality:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","text":"DOTPPalmImageQuality","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageQuality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"templateExtractionQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"templateExtractionQuality"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","op":"replace","value":"DOTPPalmQuality"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments","op":"replace","value":[{"text":"DOTPPalmQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1init(imageQuality:templateExtractionQuality:)\/title","op":"replace","value":"initWithImageQuality:templateExtractionQuality:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1init(imageQuality:templateExtractionQuality:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageQuality:templateExtractionQuality:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/title","value":"DOTPPalmImageQuality"},{"value":[{"text":"DOTPPalmImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/fragments"},{"value":[{"text":"DOTPPalmImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}