{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)"]}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooSmallValidator(im)initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","title":"init(minEdgeLengthToImageShorterSideRatioThreshold:)","navigatorTitle":[{"text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)"},"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"title":"SizeTooSmallValidator","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/init(minEdgeLengthToImageShorterSideRatioThreshold:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(minEdgeLengthToImageShorterSideRatioThreshold:)","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","op":"replace","value":"DOTPSizeTooSmallValidator"},{"value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"value":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/fragments","op":"replace"}]}]}