{"abstract":[{"type":"text","text":"Builder for "},{"type":"codeVoice","code":"PalmAutoCaptureQualityAttributeThresholds"},{"type":"text","text":" recommended for standard use cases, for example matching."}],"metadata":{"externalID":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7PresetsC8standardAC7BuilderCvpZ","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds"},{"text":".","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"title":"standard","symbolKind":"property","role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Type Property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","text":"PalmAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","text":"Builder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minConfidence"},{"text":" value is 0.8.","type":"text"}]},{"type":"paragraph","inlineContent":[{"code":"sizeInterval","type":"codeVoice"},{"type":"text","text":" value is [0.4, 0.48]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minTemplateExtractionQuality"},{"text":" value is 0.7.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minSharpness"},{"text":" value is 0.07.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"brightnessInterval"},{"type":"text","text":" value is [0.25, 0.9]."}]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Presets\/standard","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Presets"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/presets\/standard"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Presets/standard":{"title":"standard","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds"},{"text":".","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"abstract":[{"text":"Builder for ","type":"text"},{"code":"PalmAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":" recommended for standard use cases, for example matching.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/presets\/standard","type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Presets\/standard"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"title":"PalmAutoCaptureQualityAttributeThresholds","type":"topic","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"title":"PalmAutoCaptureQualityAttributeThresholds.Builder","kind":"symbol","navigatorTitle":[{"text":"Builder","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Presets":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/presets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presets"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Presets","title":"PalmAutoCaptureQualityAttributeThresholds.Presets","abstract":[{"text":"Presets for the quality attributes thresholds of the palm auto capture result.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Presets"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","value":"DOTPPalmAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholds"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}