{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/rectangledouble\/init(left:top:right:bottom:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/rectangledouble\/init(left:top:right:bottom:)"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/init(left:top:right:bottom:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"left","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"right","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"left","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"right","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(im)initWithLeft:top:right:bottom:","navigatorTitle":[{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"modules":[{"name":"DotFaceLite"}],"title":"init(left:top:right:bottom:)"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"title":"FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector","type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.7.1"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotfacelite\/rectangledouble","type":"topic","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble/init(left:top:right:bottom:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"left"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"right","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/init(left:top:right:bottom:)","kind":"symbol","type":"topic","title":"init(left:top:right:bottom:)","url":"\/documentation\/dotfacelite\/rectangledouble\/init(left:top:right:bottom:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithLeft:top:right:bottom:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithLeft:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"left","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"top:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"top","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"right:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"text":"right","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bottom:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"bottom","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1init(left:top:right:bottom:)\/title","value":"initWithLeft:top:right:bottom:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1init(left:top:right:bottom:)\/fragments","op":"replace"}]}]}