{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/height","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/height"]},{"paths":["\/documentation\/dotnfc\/rectangledouble\/height"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","title":"height","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(py)height","navigatorTitle":[{"kind":"identifier","text":"height"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","url":"\/documentation\/dotnfc\/rectangledouble","role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/height":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"height"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/height","url":"\/documentation\/dotnfc\/rectangledouble\/height","type":"topic","title":"height","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"height"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"height"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1height\/title","value":"height","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1height\/fragments","value":[{"kind":"identifier","text":"height"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}