{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":" = Defaults.faceSizeRatioInterval, "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","text":"CameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureconfiguration\/init(sessiontoken:facesizeratiointerval:istorchenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facesimplecaptureconfiguration\/init(sessiontoken:facesizeratiointerval:istorchenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureConfiguration\/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the face simple capture configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType"},{"kind":"text","text":")"}],"title":"init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureConfiguration(im)initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"role":"symbol","title":"IntervalDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfacecore\/intervaldouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureConfiguration/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)":{"role":"symbol","title":"init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the face simple capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureConfiguration\/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureconfiguration\/init(sessiontoken:facesizeratiointerval:istorchenabled:camerafacing:camerapreviewscaletype:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"role":"symbol","title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacecore\/camerafacing"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureConfiguration":{"role":"symbol","title":"FaceSimpleCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureConfiguration"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","text":"DOTIntervalDouble"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","text":"DOTCameraFacing"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureConfiguration~1init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)\/title","value":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureConfiguration~1init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureConfiguration\/title","value":"DOTFFaceSimpleCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}