{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class\/instructionBackgroundColor","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.class\/instructionbackgroundcolor"]}],"abstract":[{"type":"text","text":"Instruction background color."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}],"symbolKind":"property","externalID":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC5StyleC26instructionBackgroundColorSo7UIColorCvp","role":"symbol","title":"instructionBackgroundColor","modules":[{"name":"DotFaceCore"}],"platforms":[{"message":"Use MultiRangeLivenessViewController instead.","beta":false,"unavailable":false,"deprecated":true}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Style-swift.class":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class","kind":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"deprecated":true,"title":"MagnifEyeLivenessViewController.Style","abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.class","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"title":"MagnifEyeLivenessViewController","abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Style-swift.class/instructionBackgroundColor":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class\/instructionBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Instruction background color."}],"kind":"symbol","deprecated":true,"role":"symbol","title":"instructionBackgroundColor","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.class\/instructionbackgroundcolor"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle"}]}]}