{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderCandidateSelectionColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.class\/placeholdercandidateselectioncolor"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class\/placeholderCandidateSelectionColor","interfaceLanguage":"swift"},"metadata":{"platforms":[{"unavailable":false,"beta":false,"message":"Use MultiRangeLivenessViewController instead.","deprecated":true}],"role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC5StyleC34placeholderCandidateSelectionColorSo7UIColorCvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderCandidateSelectionColor","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"title":"placeholderCandidateSelectionColor"},"sections":[],"abstract":[{"type":"text","text":"Placeholder color during candidate selection phase."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Style-swift.class/placeholderCandidateSelectionColor":{"kind":"symbol","deprecated":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderCandidateSelectionColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.class\/placeholdercandidateselectioncolor","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class\/placeholderCandidateSelectionColor","type":"topic","abstract":[{"text":"Placeholder color during candidate selection phase.","type":"text"}],"title":"placeholderCandidateSelectionColor"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"deprecated":true,"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","title":"MagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Style-swift.class":{"type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"title":"MagnifEyeLivenessViewController.Style","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Style-swift.class","kind":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/style-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}