{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderConfiguration","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration","text":"NfcTravelDocumentReaderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderProtocol","text":"NfcTravelDocumentReaderProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderfactory\/create(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderfactory\/create(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderFactory\/create(configuration:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create and configure "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:"}],"role":"symbol","title":"create(configuration:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderConfiguration","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderProtocol","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderProtocol"}],"symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)NfcTravelDocumentReaderFactory(im)createWithConfiguration:","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderFactory"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol":{"role":"symbol","title":"NfcTravelDocumentReaderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderConfiguration":{"role":"symbol","title":"NfcTravelDocumentReaderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderConfiguration"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderconfiguration"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderFactory/create(configuration:)":{"role":"symbol","title":"create(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderConfiguration","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderProtocol","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderProtocol"}],"abstract":[{"type":"text","text":"Create and configure "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderFactory\/create(configuration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderfactory\/create(configuration:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderFactory":{"role":"symbol","title":"NfcTravelDocumentReaderFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderFactory"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderFactory"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderfactory"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createWithConfiguration:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id<DOTNNfcTravelDocumentReaderProtocol>","preciseIdentifier":"c:Qo@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderProtocol"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderConfiguration","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration","text":"DOTNNfcTravelDocumentReaderConfiguration"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/title","value":"DOTNNfcTravelDocumentReaderProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderConfiguration\/title","value":"DOTNNfcTravelDocumentReaderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderFactory~1create(configuration:)\/title","value":"createWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderFactory~1create(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createWithConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderFactory\/title","value":"NfcTravelDocumentReaderFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderFactory\/fragments","value":[{"kind":"identifier","text":"NfcTravelDocumentReaderFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}