{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/description"],"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervaldouble\/error\/customstringconvertible-implementations"]}],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","title":"CustomStringConvertible Implementations","role":"collectionGroup"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.17.1"}]},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"IntervalDouble.Error","url":"\/documentation\/dotnfc\/intervaldouble\/error","abstract":[],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/description","url":"\/documentation\/dotnfc\/intervaldouble\/error\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/IntervalDouble":{"title":"IntervalDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","url":"\/documentation\/dotnfc\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}]}]}