{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.helpAnchor","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/intervaldouble\/error\/helpanchor"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false},{"name":"iPadOS","introducedAt":"8.0","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"8.0","beta":false,"name":"Mac Catalyst","deprecated":false,"unavailable":false},{"name":"macOS","introducedAt":"10.10","deprecated":false,"beta":false,"unavailable":false},{"introducedAt":"9.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"2.0","beta":false,"name":"watchOS","deprecated":false,"unavailable":false}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"extendedModule":"Foundation","title":"helpAnchor","modules":[{"name":"DotNfc","relatedModules":["Foundation"]}],"externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/helpAnchor","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"IntervalDouble.Error","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/intervaldouble\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error"},"doc://DotNfc/documentation/DotNfc/IntervalDouble":{"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/intervaldouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble"},"doc://DotNfc/documentation/DotNfc/IntervalDouble/Error/helpAnchor":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","title":"helpAnchor","url":"\/documentation\/dotnfc\/intervaldouble\/error\/helpanchor","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/Error\/helpAnchor"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/title","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/fragments","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}