{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer\/analyze(bgraRawImage:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Analyze an image and return ","type":"text"},{"code":"ImageParameters","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"analyze","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","text":"ImageParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Image to analyze."}]}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Image parameters which contain: "},{"code":"sharpness","type":"codeVoice"},{"type":"text","text":", "},{"code":"brightness","type":"codeVoice"},{"type":"text","text":", "},{"code":"hotspotsScore","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Throws an error if ","type":"text"},{"code":"ImageParametersAnalyzer","type":"codeVoice"},{"text":" fails to analyze the image.","type":"text"}]}],"name":"Throws"}],"kind":"content"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"analyzeWithBgraRawImage:error:","kind":"identifier"}],"title":"analyze(bgraRawImage:)","externalID":"c:@M@DotDocument@objc(cs)DOTDImageParametersAnalyzer(im)analyzeWithBgraRawImage:error:","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"analyze","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageparametersanalyzer\/analyze(bgrarawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageparametersanalyzer\/analyze(bgrarawimage:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"type":"topic","title":"BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","kind":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}]},"doc://DotDocument/documentation/DotDocument/ImageParametersAnalyzer/analyze(bgraRawImage:)":{"title":"analyze(bgraRawImage:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"analyze","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"}],"navigatorTitle":[{"kind":"identifier","text":"analyzeWithBgraRawImage:error:"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer\/analyze(bgraRawImage:)","type":"topic","url":"\/documentation\/dotdocument\/imageparametersanalyzer\/analyze(bgrarawimage:)","abstract":[{"text":"Analyze an image and return ","type":"text"},{"code":"ImageParameters","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotDocument","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/ImageParameters":{"title":"ImageParameters","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageparameters","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageParametersAnalyzer":{"type":"topic","abstract":[{"text":"Stateless class which can analyze image parameters.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageParametersAnalyzer"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParametersAnalyzer"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","url":"\/documentation\/dotdocument\/imageparametersanalyzer","title":"ImageParametersAnalyzer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"analyzeWithBgraRawImage:error:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"analyzeWithBgraRawImage:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"DOTDImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters"},{"kind":"text","text":" *) "},{"text":"analyzeWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"bgraRawImage","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer~1analyze(bgraRawImage:)\/title","value":"analyzeWithBgraRawImage:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer~1analyze(bgraRawImage:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"analyzeWithBgraRawImage:error:"}]},{"op":"replace","value":"DOTDImageParameters","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments","value":[{"text":"DOTDImageParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/title","value":"DOTDImageParametersAnalyzer","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/fragments","value":[{"kind":"identifier","text":"DOTDImageParametersAnalyzer"}],"op":"replace"}]}]}