{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/bgrarawimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/bgrarawimage"]}],"abstract":[{"text":"Detection image.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/bgraRawImage"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection(py)bgraRawImage","symbolKind":"property","navigatorTitle":[{"text":"bgraRawImage","kind":"identifier"}],"title":"bgraRawImage","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bgraRawImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"title":"DocumentAutoCaptureDetection","role":"symbol","abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"url":"\/documentation\/dotdocument\/documentautocapturedetection","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection/bgraRawImage":{"abstract":[{"type":"text","text":"Detection image."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"bgraRawImage","kind":"identifier"}],"type":"topic","title":"bgraRawImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/bgraRawImage","url":"\/documentation\/dotdocument\/documentautocapturedetection\/bgrarawimage"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"type":"topic","title":"DocumentAutoCaptureController","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotdocument\/bgrarawimage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"bgraRawImage"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"bgraRawImage","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":" * "},{"text":"bgraRawImage","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1bgraRawImage\/title","value":"bgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1bgraRawImage\/fragments","value":[{"kind":"identifier","text":"bgraRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]}]}]}