{"sections":[],"abstract":[{"type":"text","text":"JPEG compressed image format"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"roleHeading":"Case","title":"ImageFormat.jpeg","symbolKind":"case","role":"symbol","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/imageformat\/jpeg"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/imageformat\/jpeg"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/jpeg":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"title":"ImageFormat.jpeg","url":"\/documentation\/dotfacecore\/imageformat\/jpeg","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg","type":"topic","abstract":[{"type":"text","text":"JPEG compressed image format"}],"kind":"symbol","navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat":{"kind":"symbol","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/imageformat","role":"symbol","abstract":[{"type":"text","text":"Supported image formats."}],"title":"ImageFormat","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTImageFormatJpeg","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFormatJpeg","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg\/title"},{"value":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg\/fragments"},{"value":"DOTImageFormat","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/title"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/fragments"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}