{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Case","title":"ImageFormat.rawBgr","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}],"role":"symbol","navigatorTitle":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgr"},"variants":[{"paths":["\/documentation\/dotfacecore\/imageformat\/rawbgr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/imageformat\/rawbgr"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgr","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The 3 bytes of color image pixel:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0th byte: BB - blue"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"1st byte: GG - green","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2nd byte: RR - red"}]}]}],"type":"unorderedList"}],"kind":"content"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/rawBgr":{"title":"ImageFormat.rawBgr","url":"\/documentation\/dotfacecore\/imageformat\/rawbgr","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgr","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgr","role":"symbol","navigatorTitle":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}],"abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat","url":"\/documentation\/dotfacecore\/imageformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTImageFormatRawBgr","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTImageFormatRawBgr","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgr\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgr\/fragments","op":"replace"},{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}]}]}]}