{"abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDDocumentAutoCapturePreview) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/cameraImage","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/detectionArea","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/placeholder"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturepreview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturepreview"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"roleHeading":"Class","title":"DocumentAutoCapturePreview","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","symbolKind":"class","navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"role":"symbol"},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships"}],"sections":[],"references":{"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/hash":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hash","url":"\/documentation\/dotdocument\/documentautocapturepreview\/hash","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/cameraImage":{"navigatorTitle":[{"text":"cameraImage","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/cameraImage","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"title":"cameraImage","url":"\/documentation\/dotdocument\/documentautocapturepreview\/cameraimage","type":"topic","abstract":[{"type":"text","text":"A rectangular region defined relative to the container where the camera image is displayed in the container."}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/placeholder":{"navigatorTitle":[{"text":"placeholder","kind":"identifier"}],"title":"placeholder","url":"\/documentation\/dotdocument\/documentautocapturepreview\/placeholder","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/placeholder","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A rectangular region defined relative to the container that represents the placeholder position."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/init(cameraImage:detectionArea:placeholder:)":{"navigatorTitle":[{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}],"title":"init(cameraImage:detectionArea:placeholder:)","url":"\/documentation\/dotdocument\/documentautocapturepreview\/init(cameraimage:detectionarea:placeholder:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":")","kind":"text"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"type":"topic","title":"DocumentAutoCapturePreview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","url":"\/documentation\/dotdocument\/documentautocapturepreview","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/detectionArea":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionArea","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"A rectangular region defined relative to the container that defines the portion of the camera image used for detection."}],"navigatorTitle":[{"text":"detectionArea","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/detectionArea","url":"\/documentation\/dotdocument\/documentautocapturepreview\/detectionarea","kind":"symbol","role":"symbol","title":"detectionArea","type":"topic"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturepreview\/isequal(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/isEqual(_:)","type":"topic","kind":"symbol","title":"isEqual(_:)"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTDDocumentAutoCapturePreview","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/cameraImage","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/detectionArea","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/placeholder"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/isEqual(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1hash\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1cameraImage\/title","op":"replace","value":"cameraImage"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1cameraImage\/fragments","op":"replace","value":[{"text":"cameraImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1placeholder\/title","op":"replace","value":"placeholder"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1placeholder\/fragments","op":"replace","value":[{"kind":"identifier","text":"placeholder"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/title","op":"replace","value":"initWithCameraImage:detectionArea:placeholder:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholder:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title","op":"replace","value":"DOTDDocumentAutoCapturePreview"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1detectionArea\/title","op":"replace","value":"detectionArea"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1detectionArea\/fragments","op":"replace","value":[{"kind":"identifier","text":"detectionArea"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}