{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"title":"FaceAutoCaptureDetection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/init(image:face:deviceTiltAngles:validatorIdentifiers:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/deviceTiltAngles","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/validatorIdentifiers"],"anchor":"Instance-Properties","generated":true}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"anchor":"Face-auto-capture-result","title":"Face auto capture result"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceAutoCaptureDetection) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturedetection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocapturedetection"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/validatorIdentifiers":{"kind":"symbol","abstract":[{"type":"text","text":"Validator identifiers for which the validation has failed."}],"navigatorTitle":[{"kind":"identifier","text":"validatorIdentifiers"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/validatorIdentifiers","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"title":"validatorIdentifiers","url":"\/documentation\/dotfacecore\/faceautocapturedetection\/validatoridentifiers"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/description":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","url":"\/documentation\/dotfacecore\/faceautocapturedetection\/description"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","title":"FaceAutoCaptureResult","url":"\/documentation\/dotfacecore\/faceautocaptureresult","kind":"symbol","role":"symbol","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"type":"topic"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/init(image:face:deviceTiltAngles:validatorIdentifiers:)":{"kind":"symbol","navigatorTitle":[{"text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}],"title":"init(image:face:deviceTiltAngles:validatorIdentifiers:)","abstract":[],"type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturedetection\/init(image:face:devicetiltangles:validatoridentifiers:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/init(image:face:deviceTiltAngles:validatorIdentifiers:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"text":".","kind":"text"},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/face":{"kind":"symbol","abstract":[{"type":"text","text":"Detected face."}],"navigatorTitle":[{"kind":"identifier","text":"face"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/face","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"kind":"text","text":"?"}],"title":"face","url":"\/documentation\/dotfacecore\/faceautocapturedetection\/face"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"type":"topic","title":"FaceAutoCaptureDetection","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturedetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","title":"DetectionPosition","url":"\/documentation\/dotfacecore\/detectionposition","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The position of the detected face in the image."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/deviceTiltAngles":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/deviceTiltAngles","url":"\/documentation\/dotfacecore\/faceautocapturedetection\/devicetiltangles","navigatorTitle":[{"kind":"identifier","text":"deviceTiltAngles"}],"title":"deviceTiltAngles","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"TiltAngles"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Tilt angles of the device."}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/image":{"kind":"symbol","abstract":[{"type":"text","text":"Detection image."}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/image","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"title":"image","url":"\/documentation\/dotfacecore\/faceautocapturedetection\/image"},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTFFaceAutoCaptureDetection","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/deviceTiltAngles","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/validatorIdentifiers"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/init(image:face:deviceTiltAngles:validatorIdentifiers:)"],"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Face auto capture result","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"anchor":"Face-auto-capture-result"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"validatorIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1validatorIdentifiers\/title"},{"value":[{"kind":"identifier","text":"validatorIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1validatorIdentifiers\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1description\/fragments"},{"value":"DOTFFaceAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/navigatorTitle"},{"value":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1init(image:face:deviceTiltAngles:validatorIdentifiers:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1init(image:face:deviceTiltAngles:validatorIdentifiers:)\/fragments"},{"value":"face","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1face\/title"},{"value":[{"kind":"identifier","text":"face"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1face\/fragments"},{"value":"DOTFFaceAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle"},{"value":"DOTDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments"},{"value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/navigatorTitle"},{"value":"deviceTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1deviceTiltAngles\/title"},{"value":[{"kind":"identifier","text":"deviceTiltAngles"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1deviceTiltAngles\/fragments"},{"value":"image","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1image\/title"},{"value":[{"kind":"identifier","text":"image"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1image\/fragments"}]}]}