{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expressionNeutral"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundUniformity"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"eyeGazeLiveness"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"passiveLiveness"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","text":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceVerificationModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"verification"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(im)initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}],"roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:":{"type":"topic","title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:","kind":"symbol","navigatorTitle":[{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceExpressionNeutralModuleConfiguration":{"type":"topic","title":"DotFaceExpressionNeutralModuleConfiguration","abstract":[{"type":"text","text":"Face expression neutral module."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfaceexpressionneutralmoduleconfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceBackgroundUniformityModuleConfiguration":{"type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","abstract":[{"type":"text","text":"Face background uniformity module."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotpalmcore\/dotfacebackgrounduniformitymoduleconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceVerificationModuleConfiguration":{"abstract":[{"type":"text","text":"Face verification module."}],"kind":"symbol","title":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceVerificationModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotfaceverificationmoduleconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceEyeGazeLivenessModuleConfiguration":{"type":"topic","title":"DotFaceEyeGazeLivenessModuleConfiguration","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceEyeGazeLivenessModuleConfiguration","url":"\/documentation\/dotpalmcore\/dotfaceeyegazelivenessmoduleconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFacePassiveLivenessModuleConfiguration":{"type":"topic","title":"DotFacePassiveLivenessModuleConfiguration","abstract":[{"type":"text","text":"Face passive liveness module."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacepassivelivenessmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration":{"type":"topic","title":"DotFaceDetectionModuleConfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"type":"topic","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules","abstract":[{"text":"Face library module configuration.","type":"text"}],"title":"DotFaceLibraryConfigurationModules","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","url":"\/documentation\/dotpalmcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/title","value":"DotFaceExpressionNeutralModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/title","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceVerificationModuleConfiguration\/title","value":"DotFaceVerificationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceVerificationModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}]}]}