{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/dateofexpiry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/dateofexpiry"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfExpiry","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)dateOfExpiry","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"title":"dateOfExpiry"},"references":{"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"title":"MrzDateElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"url":"\/documentation\/dotnfc\/td1machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"type":"topic","title":"Td1MachineReadableZone"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/dateOfExpiry":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfExpiry","navigatorTitle":[{"text":"dateOfExpiry","kind":"identifier"}],"abstract":[],"title":"dateOfExpiry","url":"\/documentation\/dotnfc\/td1machinereadablezone\/dateofexpiry","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"dateOfExpiry","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"dateOfExpiry"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dateOfExpiry"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","value":"dateOfExpiry","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfExpiry\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfExpiry\/fragments","op":"replace","value":[{"text":"dateOfExpiry","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}