{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone\/isEqual(_:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"isEqual(_:)","externalID":"c:@M@DotNfc@objc(cs)DOTTd2MachineReadableZone(im)isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotNfc"}],"symbolKind":"method","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/isequal(_:)"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.5.0","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td2MachineReadableZone/isEqual(_:)":{"title":"isEqual(_:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/td2machinereadablezone\/isequal(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone~1isEqual(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}