{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenVerificationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","externalID":"s:7DotCore0A3SdkC5ErrorO42transactionCountingTokenVerificationFailedyAEsAD_p_tcAEmF","symbolKind":"case","modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Case"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenVerificationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error":{"abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error","url":"\/documentation\/dotfacecore\/dotsdk\/error","title":"DotSdk.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/transactionCountingTokenVerificationFailed(internalError:)":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","role":"symbol","abstract":[],"title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenVerificationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments"},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}