{"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"symbolKind":"class","role":"symbol","title":"TiltAngles","externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTTiltAngles) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/tiltangles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/tiltangles"]}],"abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"text":"Also see ","type":"text"},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"text":".","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/init(pitch:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/pitch"]}],"references":{"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"title":"Sensor Coordinate System","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","title":"TiltAngles","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/tiltangles","abstract":[{"type":"text","text":"Tilt angles."},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true,"type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles/pitch":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/pitch","url":"\/documentation\/dotfacelite\/tiltangles\/pitch","role":"symbol","title":"pitch","abstract":[{"type":"text","text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"pitch","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles/description":{"url":"\/documentation\/dotfacelite\/tiltangles\/description","abstract":[],"title":"description","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles/init(pitch:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/init(pitch:)","url":"\/documentation\/dotfacelite\/tiltangles\/init(pitch:)","role":"symbol","title":"init(pitch:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"pitch"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTTiltAngles","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTTiltAngles"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/pitch"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles\/init(pitch:)"]}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTTiltAngles","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title","value":"DOTTiltAngles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"value":"pitch","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1pitch\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1pitch\/fragments","value":[{"text":"pitch","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1description\/title","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1description\/fragments"},{"op":"replace","value":"initWithPitch:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1init(pitch:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles~1init(pitch:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithPitch:"}]}]}]}