{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk"]]},"metadata":{"title":"getLibrary(libraryId:)","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite0A3SdkC10getLibrary9libraryIdAA0aF0_pSgAA0afH0O_tF","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId"},{"kind":"text","text":") -> "},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DotLibrary"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/getLibrary(libraryId:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotsdk\/getlibrary(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibraryId"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DotLibrary","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk":{"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk","url":"\/documentation\/dotfacelite\/dotsdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotLibraryId":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibraryId","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"title":"DotLibraryId","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotlibraryid","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotLibrary":{"role":"symbol","kind":"symbol","type":"topic","title":"DotLibrary","abstract":[],"url":"\/documentation\/dotfacelite\/dotlibrary","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibrary"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/getLibrary(libraryId:)":{"kind":"symbol","title":"getLibrary(libraryId:)","url":"\/documentation\/dotfacelite\/dotsdk\/getlibrary(libraryid:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId"},{"kind":"text","text":") -> "},{"text":"DotLibrary","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DotLibrary","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/getLibrary(libraryId:)","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"text":"version: 8.5.0","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibraryId\/title","value":"DotLibraryId"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibraryId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary\/title","value":"DotLibrary"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary\/fragments","op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}]}]}]}