{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/shared"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","text":"DotSdk","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/shared"]},{"paths":["\/documentation\/dotfacelite\/dotsdk\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"DotSdk","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceLite"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"shared","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotSdk(cpy)shared"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Shared singleton instance."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/shared":{"abstract":[{"type":"text","text":"Shared singleton instance."}],"title":"shared","type":"topic","role":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotsdk\/shared","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"text":"DotSdk","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdk","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"shared","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"},{"text":" * ","kind":"text"},{"text":"shared","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"replace","value":"DotSdk","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"}]}]}