{"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"title":"deinitialize()","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)deinitializeAndReturnError:","role":"symbol","symbolKind":"method"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Deinitialize "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotsdk\/deinitialize()"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/deinitialize()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method should be called on the background thread."}]}],"kind":"content"}],"references":{"doc://DotNfc/documentation/DotNfc/DotSdk/deinitialize()":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/deinitialize()","role":"symbol","url":"\/documentation\/dotnfc\/dotsdk\/deinitialize()","title":"deinitialize()","abstract":[{"text":"Deinitialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}]},"doc://DotNfc/documentation/DotNfc/DotSdk":{"title":"DotSdk","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotnfc\/dotsdk","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.10.0"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"deinitializeAndReturnError:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk~1deinitialize()\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DotSdk","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}