{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/hash","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)hash","title":"hash","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/hash":{"url":"\/documentation\/dotpalmcore\/cameraconfiguration\/hash","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/hash","type":"topic","title":"hash","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"url":"\/documentation\/dotpalmcore\/cameraconfiguration","title":"CameraConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","title":"DotPalmCore","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.2.2"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hash"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}