{"kind":"symbol","abstract":[{"type":"text","text":"Use this flag to show\/hide camera preview. Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isPreviewVisible"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/ispreviewvisible"]},{"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/ispreviewvisible"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration"]]},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isPreviewVisible","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isPreviewVisible","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"isPreviewVisible","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"title":"CameraConfiguration","url":"\/documentation\/dotpalmcore\/cameraconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/isPreviewVisible":{"title":"isPreviewVisible","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPreviewVisible"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/ispreviewvisible","kind":"symbol","abstract":[{"text":"Use this flag to show\/hide camera preview. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isPreviewVisible","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isPreviewVisible","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"isPreviewVisible","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/navigatorTitle"},{"value":"isPreviewVisible","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isPreviewVisible\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isPreviewVisible\/fragments","value":[{"text":"isPreviewVisible","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}