{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/hash"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/detectionposition\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/detectionposition\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"hash","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition(py)hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/hash":{"url":"\/documentation\/dotdocument\/detectionposition\/hash","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/hash","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","type":"topic","title":"hash"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"role":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"symbol","abstract":[{"type":"text","text":"Position of the document card in the image."}],"title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"url":"\/documentation\/dotdocument\/documentdetector","kind":"symbol","title":"DocumentDetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"hash","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1hash\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1hash\/fragments"},{"op":"replace","value":"DOTDDetectionPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title"},{"op":"replace","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments"},{"op":"replace","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle"},{"op":"replace","value":"DOTDDocumentDetector","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}