{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/detectionposition\/init(topleft:topright:bottomright:bottomleft:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/detectionposition\/init(topleft:topright:bottomright:bottomleft:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"topLeft","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomRight","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomLeft"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topLeft"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"role":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","roleHeading":"Initializer","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition(im)initWithTopLeft:topRight:bottomRight:bottomLeft:","symbolKind":"init"},"references":{"doc://DotDocument/documentation/DotDocument/PointDouble":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","title":"PointDouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotdocument\/pointdouble","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","type":"topic","abstract":[{"text":"Position of the document card in the image.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","title":"DetectionPosition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}]},"doc://DotDocument/documentation/DotDocument/DetectionPosition/init(topLeft:topRight:bottomRight:bottomLeft:)":{"kind":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"url":"\/documentation\/dotdocument\/detectionposition\/init(topleft:topright:bottomright:bottomleft:)","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"topLeft"},{"kind":"text","text":": "},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topRight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRight"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"title":"DocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDetector"}],"type":"topic","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"url":"\/documentation\/dotdocument\/documentdetector"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithTopLeft:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"kind":"text","text":" *) "},{"text":"topLeft","kind":"internalParam"},{"kind":"text","text":" "},{"text":"topRight:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topRight"},{"kind":"text","text":" "},{"text":"bottomRight:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":" *) ","kind":"text"},{"text":"bottomRight","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":" *) "},{"text":"bottomLeft","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTDDetectionPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}