{"abstract":[{"type":"text","text":"Top left corner point."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/detectionposition\/topleft"]},{"paths":["\/documentation\/dotdocument\/detectionposition\/topleft"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"topLeft"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition(py)topLeft","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"title":"topLeft","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topLeft","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotdocument\/pointdouble","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","title":"PointDouble","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"url":"\/documentation\/dotdocument\/documentdetector","kind":"symbol","title":"DocumentDetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}]},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"role":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"symbol","abstract":[{"type":"text","text":"Position of the document card in the image."}],"title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/topLeft":{"navigatorTitle":[{"text":"topLeft","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Top left corner point."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topLeft","title":"topLeft","url":"\/documentation\/dotdocument\/detectionposition\/topleft"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"topLeft","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"topLeft"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":" * ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle"},{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle"},{"value":"DOTDDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title"},{"value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments"},{"value":[{"text":"DOTDDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle"},{"value":"topLeft","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1topLeft\/title"},{"value":[{"kind":"identifier","text":"topLeft"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1topLeft\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}