{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/detectionposition\/topright"]},{"paths":["\/documentation\/dotdocument\/detectionposition\/topright"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble"}],"role":"symbol","navigatorTitle":[{"text":"topRight","kind":"identifier"}],"title":"topRight","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentDetectionPosition(py)topRight","symbolKind":"property","roleHeading":"Instance Property"},"abstract":[{"text":"Top right corner point.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/topRight","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/pointdouble","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DetectionPosition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"title":"DetectionPosition","abstract":[{"type":"text","text":"Position of the document card in the image."}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DetectionPosition/topRight":{"role":"symbol","abstract":[{"type":"text","text":"Top right corner point."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"topRight","kind":"identifier"}],"title":"topRight","kind":"symbol","url":"\/documentation\/dotdocument\/detectionposition\/topright","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/topRight"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"topRight","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"topRight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTPointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"},{"text":" * ","kind":"text"},{"text":"topRight","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace"},{"value":"DOTDocumentDetectionPosition","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition\/fragments","value":[{"text":"DOTDocumentDetectionPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition~1topRight\/title","op":"replace","value":"topRight"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition~1topRight\/fragments","value":[{"text":"topRight","kind":"identifier"}]}]}]}