{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries\/face","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?"}],"modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"face"}],"roleHeading":"Instance Property","title":"face","role":"symbol","externalID":"c:@M@DotCore@objc(cs)Libraries(py)face"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/libraries\/face"]},{"paths":["\/documentation\/dotfacelite\/libraries\/face"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"title":"DotFaceLibraryConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/Libraries/face":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"face","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries\/face","abstract":[{"type":"text","text":"Face library configuration."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/libraries\/face","title":"face"},"doc://DotFaceLite/documentation/DotFaceLite/Libraries":{"title":"Libraries","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"abstract":[{"type":"text","text":"Container for library configurations."}],"role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/libraries"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","title":"DotFaceLite"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"face","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"face","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"face","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/navigatorTitle"},{"value":"face","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries~1face\/title"},{"value":[{"kind":"identifier","text":"face"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries~1face\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/title","value":"Libraries","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/navigatorTitle","value":[{"text":"Libraries","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}