{"variants":[{"paths":["\/documentation\/dotfacelite\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries"]]},"metadata":{"symbolKind":"init","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:fingers:","role":"symbol","title":"init(document:face:faceLite:nfc:palm:fingers:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Libraries":{"type":"topic","url":"\/documentation\/dotfacelite\/libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries","title":"Libraries","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"title":"DotFaceLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibraryConfiguration":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfacelitelibraryconfiguration","navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"title":"DotFaceLiteLibraryConfiguration","abstract":[{"type":"text","text":"Face Lite library configuration."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"type":"topic","title":"DotFingersLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"title":"DotDocumentLibraryConfiguration","abstract":[{"text":"Document library configuration.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotNfcLibraryConfiguration":{"type":"topic","abstract":[{"type":"text","text":"NFC library configuration."}],"url":"\/documentation\/dotfacelite\/dotnfclibraryconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotNfcLibraryConfiguration","title":"DotNfcLibraryConfiguration","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration":{"type":"topic","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","title":"DotPalmLibraryConfiguration","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Libraries/init(document:face:faceLite:nfc:palm:fingers:)":{"type":"topic","url":"\/documentation\/dotfacelite\/libraries\/init(document:face:facelite:nfc:palm:fingers:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)","title":"init(document:face:faceLite:nfc:palm:fingers:)","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithDocument:face:faceLite:nfc:palm:fingers:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceLite:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"faceLite","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"nfc:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"nfc","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"palm:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"palm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fingers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"fingers","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/title","value":"Libraries","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/fragments","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/navigatorTitle","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibraryConfiguration\/title","value":"DotFaceLiteLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibraryConfiguration\/fragments","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotNfcLibraryConfiguration\/fragments","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/title","value":"initWithDocument:face:faceLite:nfc:palm:fingers:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}