{"variants":[{"paths":["\/documentation\/dotfacecore\/intervaldouble\/error\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO","symbolKind":"property","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"extendedModule":"DotCore","title":"errorDescription","role":"symbol","roleHeading":"Instance Property"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"DotSdkError.errorDescription"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble\/Error\/errorDescription","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble\/Error"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble/Error/errorDescription":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble\/Error\/errorDescription","title":"errorDescription","url":"\/documentation\/dotfacecore\/intervaldouble\/error\/errordescription","abstract":[],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble/Error":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/intervaldouble\/error","title":"IntervalDouble.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble\/Error","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"kind":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfacecore\/intervaldouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"title":"IntervalDouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle"}]}]}