{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/hash"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"hash","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration(py)hash"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration for face library components.","type":"text"}],"url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","title":"FaceLibraryComponentConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/hash":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/hash","abstract":[],"kind":"symbol","type":"topic","title":"hash"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hash"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]}]}]}