{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/init(facesizeratiointerval:query:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/init(facesizeratiointerval:query:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration(im)initWithFaceSizeRatioInterval:query:error:","roleHeading":"Initializer","title":"init(faceSizeRatioInterval:query:)","navigatorTitle":[{"kind":"identifier","text":"initWithFaceSizeRatioInterval:query:error:"}],"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/init(faceSizeRatioInterval:query:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"type":"topic","title":"FaceLibraryComponentConfiguration","abstract":[{"type":"text","text":"Configuration for face library components."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/init(faceSizeRatioInterval:query:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/init(faceSizeRatioInterval:query:)","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/init(facesizeratiointerval:query:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"init(faceSizeRatioInterval:query:)","navigatorTitle":[{"kind":"identifier","text":"initWithFaceSizeRatioInterval:query:error:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","url":"\/documentation\/dotfacecore\/facedetectionquery","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic","title":"FaceDetectionQuery","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFaceSizeRatioInterval:query:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFaceSizeRatioInterval:query:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFaceSizeRatioInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"DOTIntervalDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"query:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1init(faceSizeRatioInterval:query:)\/title","value":"initWithFaceSizeRatioInterval:query:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1init(faceSizeRatioInterval:query:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFaceSizeRatioInterval:query:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/navigatorTitle","value":[{"kind":"identifier","text":"FaceDetectionQuery"}]}]}]}