{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFQualityAttributeId","text":"QualityAttributeId"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange","text":"ValueRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"strictRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange","text":"ValueRange"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/qualityattribute\/init(id:targetrange:strictrange:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/qualityattribute\/init(id:targetrange:strictrange:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/init(id:targetRange:strictRange:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFQualityAttributeId"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"strictRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(id:targetRange:strictRange:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttribute(im)initWithId:targetRange:strictRange:error:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithId:targetRange:strictRange:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId":{"role":"symbol","title":"QualityAttributeId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattributeid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute":{"role":"symbol","title":"QualityAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}],"url":"\/documentation\/dotfacecore\/qualityattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ValueRange":{"role":"symbol","title":"ValueRange","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValueRange"}],"abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" range, compatible with Objective-C."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValueRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValueRange"}],"url":"\/documentation\/dotfacecore\/valuerange"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/init(id:targetRange:strictRange:)":{"role":"symbol","title":"init(id:targetRange:strictRange:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFQualityAttributeId"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"strictRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/init(id:targetRange:strictRange:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithId:targetRange:strictRange:error:"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/init(id:targetrange:strictrange:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithId:targetRange:strictRange:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:targetRange:strictRange:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithId:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFQualityAttributeId","text":"DOTFQualityAttributeId"},{"kind":"text","text":")"},{"kind":"internalParam","text":"id"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetRange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange","text":"DOTFValueRange"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"targetRange"},{"kind":"text","text":" "},{"kind":"identifier","text":"strictRange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange","text":"DOTFValueRange"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"strictRange"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/title","value":"DOTFQualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/fragments","value":[{"kind":"identifier","text":"DOTFQualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/title","value":"DOTFQualityAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFQualityAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ValueRange\/title","value":"DOTFValueRange"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ValueRange\/fragments","value":[{"kind":"identifier","text":"DOTFValueRange"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1init(id:targetRange:strictRange:)\/title","value":"initWithId:targetRange:strictRange:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1init(id:targetRange:strictRange:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:targetRange:strictRange:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}