{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Detection information. If the process has just started and no camera image has been processed yet, this will be "},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/detection"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/running\/detection"]}],"metadata":{"externalID":"s:11DotDocument0B18AutoCaptureUiStateC7RunningC9detectionAA0bcD9DetectionCSgvp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection"},{"kind":"text","text":"?"}],"role":"symbol","roleHeading":"Instance Property","title":"detection","symbolKind":"property","modules":[{"name":"DotDocument"}]},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"abstract":[{"text":"Running state.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","title":"DocumentAutoCaptureUiState.Running","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running","navigatorTitle":[{"text":"Running","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureuistate","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureUiState"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"title":"DocumentAutoCaptureUiState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureUiState"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","role":"symbol","type":"topic","title":"DocumentAutoCaptureDetection","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturedetection"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/detection":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","kind":"typeIdentifier","text":"DocumentAutoCaptureDetection"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Detection information. If the process has just started and no camera image has been processed yet, this will be "},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/detection","title":"detection","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/detection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title","value":"DOTDDocumentAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"op":"replace"}]}]}