{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/preview"},"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview"}],"role":"symbol","roleHeading":"Instance Property","title":"preview","externalID":"s:11DotDocument0B18AutoCaptureUiStateC7RunningC7previewAA0bcD7PreviewCvp"},"abstract":[{"text":"Preview information.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/running\/preview"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","kind":"symbol","role":"symbol","title":"DocumentAutoCaptureUiState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureUiState"}],"abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureUiState"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","kind":"symbol","role":"symbol","title":"DocumentAutoCaptureUiState.Running","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"abstract":[{"text":"Running state.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Running"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"title":"DocumentAutoCapturePreview","url":"\/documentation\/dotdocument\/documentautocapturepreview"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/preview":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/preview","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/preview","kind":"symbol","role":"symbol","title":"preview","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DocumentAutoCapturePreview"}],"abstract":[{"text":"Preview information.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title","op":"replace","value":"DOTDDocumentAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title","op":"replace","value":"DOTDDocumentAutoCapturePreview"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}