{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"kind":"text","text":" "},{"text":"faceSizeRatioInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier","text":"DOTIntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"text":" ","kind":"text"},{"text":"query:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"text":" *) ","kind":"text"},{"text":"query","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessConfiguration(im)initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","roleHeading":"Instance Method"},"abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration":{"role":"symbol","url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"title":"DOTFMagnifEyeLivenessConfiguration","kind":"symbol","fragments":[{"text":"DOTFMagnifEyeLivenessConfiguration","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"role":"symbol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"title":"FaceDetectionQuery","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","url":"\/documentation\/dotfacecore\/facedetectionquery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"type":"topic","title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:","navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.3.1"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacecore\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"title":"CameraFacing","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace"},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments"}]}]}