{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"]},{"paths":["\/documentation\/dotfacecore\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DotLibrary","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}]}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"], "},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"title":"init(licenseBytes:libraries:transactionCountingToken:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkConfiguration":{"role":"symbol","title":"DotSdkConfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration","type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"url":"\/documentation\/dotfacecore\/dotsdkconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary":{"role":"symbol","abstract":[],"title":"DotLibrary","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotlibrary","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkConfiguration/init(licenseBytes:libraries:transactionCountingToken:)":{"role":"symbol","title":"init(licenseBytes:libraries:transactionCountingToken:)","url":"\/documentation\/dotfacecore\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLicenseBytes:libraries:transactionCountingToken:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries:"},{"text":"(","kind":"text"},{"text":"NSArray<id<DotLibrary>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"libraries","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transactionCountingToken:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"transactionCountingToken","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DotSdkConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/title","op":"replace","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/fragments"},{"value":"initWithLicenseBytes:libraries:transactionCountingToken:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/fragments"}]}]}