{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"kind":"article","topicSections":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/hashValue"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/hash(into:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode"]]},"metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","title":"RawRepresentable Implementations","roleHeading":"API Collection"},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/validationmode\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/ValidationMode/hash(into:)":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/hash(into:)","title":"hash(into:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/dotdocument\/validationmode\/hash(into:)"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/ValidationMode/hashValue":{"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"role":"symbol","url":"\/documentation\/dotdocument\/validationmode\/hashvalue","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/hashValue","type":"topic","title":"hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","abstract":[]},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}],"title":"ValidationMode","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationMode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","url":"\/documentation\/dotdocument\/validationmode"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","op":"replace","value":"DOTDValidationMode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","op":"replace","value":[{"text":"DOTDValidationMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/navigatorTitle","op":"replace","value":[{"text":"DOTDValidationMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}