{"metadata":{"modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@DotDocument@E@DOTDValidationMode@DOTDValidationModeStandard","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}],"title":"ValidationMode.standard","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DOTDValidationModeStandard"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/standard","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Document must be clearly visible and sharp enough."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/validationmode\/standard"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/validationmode\/standard"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","title":"DotDocument","kind":"symbol","abstract":[{"text":"version: 8.14.1","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"url":"\/documentation\/dotdocument\/validationmode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationMode"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"ValidationMode","navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ValidationMode/standard":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}],"abstract":[{"text":"Document must be clearly visible and sharp enough.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode\/standard","url":"\/documentation\/dotdocument\/validationmode\/standard","type":"topic","role":"symbol","title":"ValidationMode.standard","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTDValidationModeStandard"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTDValidationModeStandard"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTDValidationModeStandard","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTDValidationModeStandard"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"text":"DOTDValidationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode~1standard\/title","value":"DOTDValidationModeStandard"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode~1standard\/fragments","value":[{"text":"DOTDValidationModeStandard","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}