{"metadata":{"title":"nationality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"navigatorTitle":[{"text":"nationality","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)nationality","modules":[{"name":"DotDocument"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/nationality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/nationality"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/nationality","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"title":"Td3MachineReadableZone","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","url":"\/documentation\/dotdocument\/mrzelement","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/nationality":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/nationality","kind":"symbol","title":"nationality","role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/nationality","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"nationality","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"nationality"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"nationality"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},{"text":" * ","kind":"text"},{"text":"nationality","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]},{"value":"DOTMrzElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","value":"nationality","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1nationality\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1nationality\/fragments","value":[{"kind":"identifier","text":"nationality"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}