{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.property"]}],"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"title":"modules","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration(py)modules","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","text":"Modules"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","text":"Modules"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/modules-swift.property"},"kind":"symbol","abstract":[{"type":"text","text":"Module configuration."}],"references":{"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/modules-swift.property":{"type":"topic","navigatorTitle":[{"text":"modules","kind":"identifier"}],"title":"modules","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/modules-swift.property","kind":"symbol","abstract":[{"type":"text","text":"Module configuration."}],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.property","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fingers library module configuration."}],"title":"DotFingersLibraryConfiguration.Modules"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfigurationModules":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules","fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fingers library module configuration."}],"title":"DotFingersLibraryConfigurationModules"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"title":"DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"modules","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"modules"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules","text":"DotFingersLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"modules","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration~1modules-swift.property\/title"},{"op":"replace","value":[{"kind":"identifier","text":"modules"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration~1modules-swift.property\/fragments"},{"op":"replace","value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/navigatorTitle"}]}]}