{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentModuleId","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId","preciseIdentifier":"c:@M@DotCore@E@DotDocumentModuleId"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentmodule\/moduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotdocumentmodule\/moduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"required":true,"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(pl)DotDocumentModule(py)moduleId","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotDocumentModuleId","text":"DotDocumentModuleId"}],"title":"moduleId","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule\/moduleId","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId":{"abstract":[{"code":"DotDocument","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentmoduleid","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"kind":"symbol","title":"DotDocumentModuleId","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId"},"doc://DotDocument/documentation/DotDocument/DotDocumentModule":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModule"}],"url":"\/documentation\/dotdocument\/dotdocumentmodule","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModule"}],"title":"DotDocumentModule","kind":"symbol","abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module."}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentModule/moduleId":{"abstract":[],"required":true,"type":"topic","navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"url":"\/documentation\/dotdocument\/dotdocumentmodule\/moduleid","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotDocumentModuleId","text":"DotDocumentModuleId"}],"title":"moduleId","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModule\/moduleId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"moduleId"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"moduleId"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotDocumentModuleId","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId","preciseIdentifier":"c:@M@DotCore@E@DotDocumentModuleId"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/title","value":"DotDocumentModuleId"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/fragments"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/navigatorTitle"},{"value":"DotDocumentModule","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule\/title"},{"value":[{"text":"DotDocumentModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule\/fragments"},{"value":[{"text":"DotDocumentModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule\/navigatorTitle"},{"value":"moduleId","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule~1moduleId\/title"},{"value":[{"text":"moduleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModule~1moduleId\/fragments"}]}]}