{"variants":[{"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class\/detection"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"DotDocument"}],"title":"detection","externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fingers library module configuration."}],"title":"DotFingersLibraryConfiguration.Modules"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"type":"topic","title":"detection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class\/detection","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"title":"DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFingersDetectionModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotdocument\/dotfingersdetectionmoduleconfiguration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/title","op":"replace","value":"DotFingersLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/title","op":"replace","value":"DotFingersDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]}]}]}