{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","interfaceLanguage":"swift"},"metadata":{"title":"init(detection:transformation:)","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?)"}],"symbolKind":"init","role":"symbol","externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detection14transformationAeA0ac15DetectionModuleE0C_AA0ac14TransformationjE0CSgtcfc"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"text":"DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"title":"init(detection:transformation:)","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?)"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"title":"DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fingers library module configuration."}],"title":"DotFingersLibraryConfiguration.Modules"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","type":"topic","navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFingersDetectionModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotdocument\/dotfingersdetectionmoduleconfiguration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}