{"variants":[{"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC14transformationAA0ac20TransformationModuleE0CSgvp","title":"transformation","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fingers library module configuration."}],"title":"DotFingersLibraryConfiguration.Modules"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"title":"DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"title":"transformation","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation"},"doc://DotDocument/documentation/DotDocument/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","type":"topic","navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFingersTransformationModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}