{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dotFaceLibrary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary","text":"DotFaceLibrary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary","text":"DotFaceLibrary"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/Result","preciseIdentifier":"s:11DotFaceCore0aB7LibraryC6ResultC","text":"Result"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibrarydelegate\/dotfacelibraryinitializationfinished(_:result:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacelibrarydelegate\/dotfacelibraryinitializationfinished(_:result:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryInitializationFinished(_:result:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework initialization has finished with "},{"type":"codeVoice","code":"result"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}],"role":"symbol","title":"dotFaceLibraryInitializationFinished(_:result:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB7LibraryC6ResultC"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceLibraryDelegate(im)dotFaceLibraryInitializationFinished:result:","required":true,"modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryDelegate/dotFaceLibraryInitializationFinished(_:result:)":{"navigatorTitle":[{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}],"role":"symbol","title":"dotFaceLibraryInitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB7LibraryC6ResultC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework initialization has finished with "},{"type":"codeVoice","code":"result"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryInitializationFinished(_:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrarydelegate\/dotfacelibraryinitializationfinished(_:result:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary":{"role":"symbol","title":"DotFaceLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryDelegate":{"role":"symbol","title":"DotFaceLibraryDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle initialization and deinitialization events of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"url":"\/documentation\/dotfacecore\/dotfacelibrarydelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/Result":{"role":"symbol","title":"DotFaceLibrary.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the initialization and deinitialization of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/result"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryResult":{"role":"symbol","title":"DotFaceLibraryResult","fragments":[{"kind":"identifier","text":"DotFaceLibraryResult"}],"abstract":[{"type":"text","text":"Result of the initialization and deinitialization of the "},{"type":"text","text":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryResult","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibraryresult"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dotFaceLibraryInitializationFinished:result:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary","text":"DotFaceLibrary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dotFaceLibrary"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryResult","text":"DotFaceLibraryResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate~1dotFaceLibraryInitializationFinished(_:result:)\/title","value":"dotFaceLibraryInitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate~1dotFaceLibraryInitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","value":[{"kind":"identifier","text":"DotFaceLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate\/title","value":"DotFaceLibraryDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}