{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/pointdouble\/from(cgpoint:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/pointdouble\/from(cgpoint:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"PointDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble\/from(cgPoint:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@CM@DotCore@objc(cs)DOTPointDouble(cm)fromCgPoint:","roleHeading":"Type Method","role":"symbol","modules":[{"relatedModules":["DotCore"],"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"title":"from(cgPoint:)","extendedModule":"DotCore","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"symbolKind":"method"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble/from(cgPoint:)":{"url":"\/documentation\/dotfacecore\/pointdouble\/from(cgpoint:)","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"title":"from(cgPoint:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble\/from(cgPoint:)","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble":{"url":"\/documentation\/dotfacecore\/pointdouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"title":"PointDouble","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","type":"topic","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"fromCgPoint:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cgPoint","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"fromCgPoint:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble~1from(cgPoint:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble~1from(cgPoint:)\/fragments","op":"replace"},{"value":"DOTPointDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/navigatorTitle","op":"replace"}]}]}