{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confidenceLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = DocumentNotDetectedValidator.defaultConfidenceThreshold, "},{"kind":"externalParam","text":"sizeSmallThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = SizeSmallValidator.defaultShortestEdgeToImageSideRatioThreshold, "},{"kind":"externalParam","text":"sharpnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = SharpnessLowValidator.defaultThreshold, "},{"kind":"externalParam","text":"brightnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = BrightnessLowValidator.defaultThreshold, "},{"kind":"externalParam","text":"brightnessHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = BrightnessHighValidator.defaultThreshold, "},{"kind":"externalParam","text":"hotspotsScoreHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = HotspotsScoreHighValidator.defaultThreshold, "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTValidationMode","text":"ValidationMode"},{"kind":"text","text":" = Defaults.validationMode, "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isMrzReadingEnabled, "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraFacing","text":"CameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"kind":"externalParam","text":"cameraPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreset","text":"CameraPreset"},{"kind":"text","text":" = Defaults.cameraPreset) "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(confidencelowthreshold:sizesmallthreshold:sharpnesslowthreshold:brightnesslowthreshold:brightnesshighthreshold:hotspotsscorehighthreshold:validationmode:ismrzreadingenabled:isdetectionlayervisible:camerafacing:camerapreviewscaletype:ca-o11l"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(confidencelowthreshold:sizesmallthreshold:sharpnesslowthreshold:brightnesslowthreshold:brightnesshighthreshold:hotspotsscorehighthreshold:validationmode:ismrzreadingenabled:isdetectionlayervisible:camerafacing:camerapreviewscaletype:ca-o11l"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"}],"role":"symbol","title":"init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confidenceLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeSmallThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sharpnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightnessHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hotspotsScoreHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreset","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreset"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureConfiguration(im)initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:","modules":[{"name":"DotDocument"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This constructor will be removed. Use another one using QualityAttributeThresholds parameter."}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)":{"deprecated":true,"role":"symbol","title":"init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confidenceLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeSmallThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sharpnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightnessHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hotspotsScoreHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreset","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreset"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(confidencelowthreshold:sizesmallthreshold:sharpnesslowthreshold:brightnesslowthreshold:brightnesshighthreshold:hotspotsscorehighthreshold:validationmode:ismrzreadingenabled:isdetectionlayervisible:camerafacing:camerapreviewscaletype:ca-o11l"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode":{"role":"symbol","title":"ValidationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"url":"\/documentation\/dotdocument\/validationmode"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraFacing":{"role":"symbol","title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotdocument\/camerafacing"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset":{"role":"symbol","title":"CameraPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreset"}],"abstract":[{"type":"text","text":"Camera preset and video frame resolution."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreset"}],"url":"\/documentation\/dotdocument\/camerapreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfidenceLowThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"confidenceLowThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeSmallThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"sizeSmallThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpnessLowThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"sharpnessLowThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessLowThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"brightnessLowThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessHighThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"brightnessHighThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"hotspotsScoreHighThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"hotspotsScoreHighThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTValidationMode","text":"DOTValidationMode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"validationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMrzReadingEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraFacing","text":"DOTDCameraFacing"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreviewScaleType","text":"DOTDCameraPreviewScaleType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreset:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreset","text":"DOTDCameraPreset"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraPreset"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)\/title","value":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title","value":"DOTDCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTValidationMode"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTValidationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTDCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTDCameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/title","value":"DOTDCameraPreset"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}