{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLMultiRangeLivenessViewController) ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"inlineContent":[{"type":"text","text":"A visual component for capturing images suitable for Multi-Range Liveness evaluation."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Style-swift.class"]},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/init(configuration:style:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/configuration-swift.property","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/delegate","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/style-swift.property"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/start()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/stop()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidLoad()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillTransition(to:with:)"]},{"generated":true,"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Error"]}],"metadata":{"title":"MultiRangeLivenessViewController","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","role":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"class"},"seeAlsoSections":[{"generated":true,"title":"UI components","anchor":"UI-components","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)UIViewController"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSCoding","doc:\/\/DotFaceLite\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFaceLite\/objc(pl)UIAppearanceContainer","doc:\/\/DotFaceLite\/objc(pl)UIContentContainer","doc:\/\/DotFaceLite\/objc(pl)UIFocusEnvironment","doc:\/\/DotFaceLite\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFaceLite\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFaceLite\/objc(pl)UIStateRestoring","doc:\/\/DotFaceLite\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFaceLite\/objc(pl)UITraitEnvironment","doc:\/\/DotFaceLite\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","title":"MultiRangeLivenessViewController","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/viewDidAppear(_:)":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidAppear(_:)","abstract":[],"title":"viewDidAppear(_:)","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/viewdidappear(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/viewDidLayoutSubviews()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/viewdidlayoutsubviews()","abstract":[],"role":"symbol","title":"viewDidLayoutSubviews()","type":"topic","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidLayoutSubviews()"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/start()":{"title":"start()","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/start()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/start()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"start","kind":"identifier"}],"abstract":[{"text":"Start the Multi-Range Liveness process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/stop()":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/stop()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Stop the Multi-Range Liveness process.","type":"text"}],"title":"stop()"},"doc://DotFaceLite/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIFocusEnvironment"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/delegate":{"role":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/delegate","title":"delegate","abstract":[{"text":"Set this delegate to handle the Multi-Range Liveness events.","type":"text"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLMultiRangeLivenessViewControllerDelegate","text":"MultiRangeLivenessViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/delegate"},"doc://DotFaceLite/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://DotFaceLite/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIUserActivityRestoring"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/viewDidLoad()":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"title":"viewDidLoad()","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/viewdidload()","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://DotFaceLite/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://DotFaceLite/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIAppearanceContainer"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/style-swift.property":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"style"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/style-swift.property","title":"style","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/style-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC5StyleC"}],"abstract":[{"text":"Current style.","type":"text"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/init(configuration:style:)":{"title":"init(configuration:style:)","abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"MultiRangeLivenessViewController"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/init(configuration:style:)","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/init(configuration:style:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC5StyleC"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://DotFaceLite/objc(cs)UIViewController":{"title":"UIViewController","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)UIViewController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"kind":"symbol","type":"topic","title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"deprecated":true,"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","kind":"symbol","title":"MagnifEyeLivenessViewController"},"doc://DotFaceLite/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/viewWillAppear(_:)":{"role":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/viewwillappear(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillAppear(_:)","type":"topic","title":"viewWillAppear(_:)"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/viewWillTransition(to:with:)":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillTransition(to:with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"abstract":[],"title":"viewWillTransition(to:with:)","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/viewwilltransition(to:with:)","type":"topic"},"doc://DotFaceLite/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/5UIKit23UITraitChangeObservableP"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/configuration-swift.property":{"title":"configuration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/configuration-swift.property","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"abstract":[{"text":"Current configuration.","type":"text"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.property","kind":"symbol"},"doc://DotFaceLite/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Error":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Error","title":"MultiRangeLivenessViewController.Error","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","role":"symbol","kind":"symbol","title":"MultiRangeLivenessViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class"},"doc://DotFaceLite/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Style-swift.class":{"type":"topic","navigatorTitle":[{"text":"Style","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Customization options for the Multi-Range Liveness user interface."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Style-swift.class","role":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/style-swift.class","title":"MultiRangeLivenessViewController.Style"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/viewDidDisappear(_:)":{"type":"topic","abstract":[],"kind":"symbol","title":"viewDidDisappear(_:)","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/viewdiddisappear(_:)"},"doc://DotFaceLite/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/viewWillDisappear(_:)":{"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillDisappear(_:)","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/viewwilldisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"viewWillDisappear(_:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTFLMultiRangeLivenessViewController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/configuration-swift.property","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/delegate","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/style-swift.property"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/init(configuration:style:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/start()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/stop()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewDidLoad()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/viewWillTransition(to:with:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)UIViewController"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"UI-components","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"],"title":"UI components"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidLayoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1start()\/title","value":"start","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1start()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1stop()\/title","value":"stop","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1stop()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1delegate\/title","value":"delegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1delegate\/fragments","value":[{"kind":"identifier","text":"delegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1style-swift.property\/title","value":"style","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1style-swift.property\/fragments","value":[{"kind":"identifier","text":"style"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1init(configuration:style:)\/title","value":"initWithConfiguration:style:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewWillTransition(to:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1configuration-swift.property\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1viewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"}]}]}