{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillAppear(_:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead."}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewwillappear(_:)"]},{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewwillappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceSimpleCaptureViewControllerViewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"FaceSimpleCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"title":"faceSimpleCaptureViewControllerViewWillAppear(_:)","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear:"}],"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","text":"FaceSimpleCaptureViewController"},{"text":")","kind":"text"}],"platforms":[],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate(im)faceSimpleCaptureViewControllerViewWillAppear:","symbolKind":"method"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewWillAppear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear:"}],"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewwillappear(_:)","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear"},{"kind":"text","text":"("},{"text":"FaceSimpleCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"text":")","kind":"text"}],"role":"symbol","title":"faceSimpleCaptureViewControllerViewWillAppear(_:)","deprecated":true,"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.7.0"}],"title":"DotFaceCore","role":"collection","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"abstract":[{"text":"Implement this delegate to handle the face simple capture events.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","title":"FaceSimpleCaptureViewControllerDelegate","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing face images."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"role":"symbol","deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","title":"FaceSimpleCaptureViewController","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","type":"topic","navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceSimpleCaptureViewControllerViewWillAppear:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"faceSimpleCaptureViewControllerViewWillAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceSimpleCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"faceSimpleCaptureViewControllerViewWillAppear:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillAppear(_:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillAppear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear:"}]},{"value":"DOTFFaceSimpleCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewControllerDelegate"}]},{"value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}