{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nfcKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","text":"NfcKey"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"nfcKey","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NFC key created from the document number, date of expiry and date of birth."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can handle success or failure of NFC reading by implementing the delegate methods."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/read(nfckey:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/read(nfcKey:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Read passport using NFC key."}],"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","title":"read(nfcKey:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nfcKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcKey","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"s:6DotNfc0B28TravelDocumentReaderProtocolPAAE4read6nfcKeyyAA0bI0C_tF","extendedModule":"DotNfc","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol/read(nfcKey:)":{"role":"symbol","title":"read(nfcKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nfcKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcKey","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Read passport using NFC key."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/read(nfcKey:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/read(nfckey:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey":{"role":"symbol","title":"NfcKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"abstract":[{"type":"text","text":"NFC key created from document number, date of expiry and date of birth."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"url":"\/documentation\/dotnfc\/nfckey"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol":{"role":"symbol","title":"NfcTravelDocumentReaderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"kind":"identifier","text":"DOTNNfcKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/title","value":"DOTNNfcTravelDocumentReaderProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}