{"abstract":[{"type":"text","text":"Score of the face feature."}],"metadata":{"title":"score","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceFeaturePoint(py)score","navigatorTitle":[{"kind":"identifier","text":"score"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeaturepoint\/score"]},{"paths":["\/documentation\/dotfacecore\/facefeaturepoint\/score"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/score"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint/score":{"url":"\/documentation\/dotfacecore\/facefeaturepoint\/score","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/score","navigatorTitle":[{"kind":"identifier","text":"score"}],"role":"symbol","type":"topic","abstract":[{"text":"Score of the face feature.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"title":"score"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint","url":"\/documentation\/dotfacecore\/facefeaturepoint","kind":"symbol","navigatorTitle":[{"text":"FaceFeaturePoint","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeaturePoint","kind":"identifier"}],"abstract":[{"type":"text","text":"Face feature point contains face feature, point and score."}],"role":"symbol","title":"FaceFeaturePoint"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"score","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"score"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","value":"score","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1score\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1score\/fragments","value":[{"text":"score","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint\/title","value":"DOTFFaceFeaturePoint"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeaturePoint"}]}]}]}