{"abstract":[{"type":"text","text":"Specify polling option. Default is "},{"type":"codeVoice","code":"standard"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/pollingOption-swift.property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pollingOption","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum","text":"PollingOption","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC13PollingOptionO"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.property"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class"]]},"metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"DotNfc"}],"title":"pollingOption","roleHeading":"Instance Property","externalID":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC13pollingOptionAE07PollingH0Ovp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pollingOption","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PollingOption","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC13PollingOptionO"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"title":"NfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum":{"title":"NfcTravelDocumentReader.Configuration.PollingOption","role":"symbol","navigatorTitle":[{"text":"PollingOption","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum","type":"topic","abstract":[{"text":"Polling option specifies which travel documents can be detected.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PollingOption","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/pollingOption-swift.property":{"type":"topic","abstract":[{"text":"Specify polling option. Default is ","type":"text"},{"code":"standard","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/pollingOption-swift.property","role":"symbol","title":"pollingOption","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pollingOption"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC13PollingOptionO","text":"PollingOption"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"NfcTravelDocumentReader.Configuration","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for ","type":"text"},{"code":"NfcTravelDocumentReader","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}