{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/localizedDescription","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/Error-Implementations"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Error.localizedDescription","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"platforms":[{"introducedAt":"8.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","introducedAt":"10.10","unavailable":false,"beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"9.0","deprecated":false},{"introducedAt":"2.0","unavailable":false,"beta":false,"name":"watchOS","deprecated":false}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"extendedModule":"Swift","role":"symbol","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:6DotNfc24CardAccessNumberPasswordC5ErrorO","modules":[{"name":"DotNfc","relatedModules":["Swift"]}],"title":"localizedDescription","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"kind":"symbol","title":"NfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/localizedDescription":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/localizeddescription","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/localizedDescription","title":"localizedDescription"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/Error-Implementations":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/error-implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/Error-Implementations","title":"Error Implementations"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CardAccessNumberPassword","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","type":"topic","kind":"symbol","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"title":"CardAccessNumberPassword","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CardAccessNumberPassword"}]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","type":"topic","kind":"symbol","abstract":[],"title":"CardAccessNumberPassword.Error","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}