{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/position","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"externalID":"s:11DotFaceLite0B8DetectorC0B0C8position0aB7Commons17DetectionPositionCvp","role":"symbol","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","title":"position","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","kind":"typeIdentifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Position of the detected face in the image.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/facedetector\/face\/position"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"text":"version: 8.12.1","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"url":"\/documentation\/dotfacelite\/facedetector","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"title":"FaceDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/position":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"position"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/position","url":"\/documentation\/dotfacelite\/facedetector\/face\/position","role":"symbol","title":"position","abstract":[{"text":"Position of the detected face in the image.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"abstract":[{"text":"Detected face.","type":"text"}],"navigatorTitle":[{"text":"Face","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector\/face","kind":"symbol","title":"FaceDetector.Face"},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"role":"symbol","title":"DetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","type":"topic","url":"\/documentation\/dotfacelite\/detectionposition"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFLFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"value":[{"text":"DOTDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","op":"replace"}]}]}