{"sections":[],"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration(im)init","title":"init","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacepassivelivenessmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFacePassiveLivenessModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotfacepassivelivenessmoduleconfiguration","abstract":[{"type":"text","text":"Face passive liveness module."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration","kind":"symbol","title":"DotFacePassiveLivenessModuleConfiguration","role":"symbol","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFacePassiveLivenessModuleConfiguration/init":{"abstract":[],"title":"init","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotpalmcore\/dotfacepassivelivenessmoduleconfiguration\/init","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration\/init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]}]}]}