{"metadata":{"navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isNfcEnabled","symbolKind":"property","required":true,"roleHeading":"Instance Property","title":"isNfcEnabled","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isnfcenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isnfcenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isNfcEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isnfcenabled","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","required":true,"title":"isNfcEnabled","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isNfcEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/navigatorTitle","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title","op":"replace","value":"isNfcEnabled"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}