{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Request capture of the next detection.","type":"text"}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController(im)requestCaptureWithIsFacePresenceRequired:","role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceLite"}],"title":"requestCapture(isFacePresenceRequired:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"("},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"title":"requestCapture(isFacePresenceRequired:)","kind":"symbol","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"type":"text","text":"version: 8.2.0"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","type":"topic","abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"requestCaptureWithIsFacePresenceRequired:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isFacePresenceRequired","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","value":"requestCaptureWithIsFacePresenceRequired:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"op":"replace"},{"value":"DOTFLFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"}]}]}