{"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"bottomRight","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"bottomRight"}],"title":"bottomRight","modules":[{"name":"DotDocument"}],"symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition(py)bottomRight"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/bottomRight"},"abstract":[{"type":"text","text":"Bottom right corner point."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdbarcodedetectionposition\/bottomright"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/PointDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","url":"\/documentation\/dotdocument\/pointdouble","title":"PointDouble"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition/bottomRight":{"kind":"symbol","abstract":[{"type":"text","text":"Bottom right corner point."}],"fragments":[{"kind":"identifier","text":"bottomRight"}],"title":"bottomRight","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition\/bottomright","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/bottomRight","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","title":"DOTDBarcodeDetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","fragments":[{"text":"DOTDBarcodeDetectionPosition","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}