{"metadata":{"title":"bottomLeft","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition(py)bottomLeft","symbolKind":"property","fragments":[{"text":"bottomLeft","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Bottom left corner point."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"DOTPointDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/bottomLeft","interfaceLanguage":"occ"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdbarcodedetectionposition\/bottomleft"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"]]},"references":{"doc://DotDocument/documentation/DotDocument/PointDouble":{"kind":"symbol","title":"PointDouble","url":"\/documentation\/dotdocument\/pointdouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition/bottomLeft":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Bottom left corner point."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/bottomLeft","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition\/bottomleft","type":"topic","fragments":[{"kind":"identifier","text":"bottomLeft"}],"title":"bottomLeft"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"title":"DOTDBarcodeDetectionPosition","type":"topic","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","role":"symbol","fragments":[{"text":"DOTDBarcodeDetectionPosition","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"}},"variantOverrides":[{"patch":[{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}