{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopLeft:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topLeft"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"topRight"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bottomRight"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bottomLeft"},{"kind":"text","text":";"}]}]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition(im)initWithTopLeft:topRight:bottomRight:bottomLeft:","navigatorTitle":[{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"symbolKind":"method","role":"symbol","modules":[{"name":"DotDocument"}],"title":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotdbarcodedetectionposition\/initwithtopleft:topright:bottomright:bottomleft:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/initWithTopLeft:topRight:bottomRight:bottomLeft:"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/PointDouble":{"kind":"symbol","title":"PointDouble","url":"\/documentation\/dotdocument\/pointdouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition/initWithTopLeft:topRight:bottomRight:bottomLeft:":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/initWithTopLeft:topRight:bottomRight:bottomLeft:","title":"initWithTopLeft:topRight:bottomRight:bottomLeft:","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition\/initwithtopleft:topright:bottomright:bottomleft:","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"title":"DOTDBarcodeDetectionPosition","type":"topic","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","role":"symbol","fragments":[{"text":"DOTDBarcodeDetectionPosition","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Position of the barcode in the image."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}