{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","kind":"typeIdentifier","text":"DOTDBarcodeDetectionPosition"},{"kind":"text","text":" *) "},{"text":"rebasedWithParentRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"parentRectangle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition(im)rebasedWithParentRectangle:","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"title":"rebasedWithParentRectangle:","fragments":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/dotdbarcodedetectionposition\/rebasedwithparentrectangle:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/rebasedWithParentRectangle:","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"type":"topic","title":"RectangleDouble","kind":"symbol","url":"\/documentation\/dotdocument\/rectangledouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"title":"DOTDBarcodeDetectionPosition","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","fragments":[{"text":"DOTDBarcodeDetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","abstract":[{"text":"Position of the barcode in the image.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition/rebasedWithParentRectangle:":{"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/rebasedWithParentRectangle:","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition\/rebasedwithparentrectangle:","title":"rebasedWithParentRectangle:","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle"}]}]}