{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/wrappeddouble\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/wrappeddouble\/hash"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble\/hash","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hash","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble(py)hash","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/WrappedDouble/hash":{"abstract":[],"url":"\/documentation\/dotnfc\/wrappeddouble\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble\/hash","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/WrappedDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/wrappeddouble","title":"WrappedDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble","type":"topic","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.10.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","type":"topic","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"hash","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble~1hash\/title","op":"replace","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","value":"DOTWrappedDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble\/title"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble\/fragments","op":"replace"}]}]}