{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/init(image:faceSizeRatioInterval:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"symbol","navigatorTitle":[{"text":"initWithImage:faceSizeRatioInterval:error:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage(im)initWithImage:faceSizeRatioInterval:error:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(image:faceSizeRatioInterval:)","symbolKind":"init"},"abstract":[{"text":"Create face image from raw image and face size interval.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"Raw image. Image must be in ","type":"text"},{"type":"codeVoice","code":".rawBgr"},{"text":" format.","type":"text"}]}]},{"name":"faceSizeRatioInterval","content":[{"inlineContent":[{"type":"text","text":"Face size interval as a ratio to shorter image side. This defines the size of searched face in the image."},{"type":"text","text":" "},{"type":"text","text":"Valid values are in interval [0.0, 1.0]. "},{"type":"codeVoice","code":"faceSizeRatioInterval.min"},{"type":"text","text":" must be greater than or equal to minimal valid face size,"},{"type":"text","text":" "},{"type":"text","text":"which depends on the active detection module."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"style":"note","content":[{"inlineContent":[{"text":"Throws an error if ","type":"text"},{"code":"faceSizeRatioInterval","type":"codeVoice"},{"text":" is not valid.","type":"text"}],"type":"paragraph"}],"name":"Throws","type":"aside"}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceimage\/init(image:facesizeratiointerval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceimage\/init(image:facesizeratiointerval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Image":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image"}],"abstract":[],"title":"Image","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/image"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"url":"\/documentation\/dotfacecore\/facedetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","type":"topic","title":"FaceDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage/init(image:faceSizeRatioInterval:)":{"title":"init(image:faceSizeRatioInterval:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Create face image from raw image and face size interval."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/init(image:faceSizeRatioInterval:)","url":"\/documentation\/dotfacecore\/faceimage\/init(image:facesizeratiointerval:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:faceSizeRatioInterval:error:"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol","type":"topic","title":"IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImage"}],"url":"\/documentation\/dotfacecore\/faceimage","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"title":"FaceImage","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithImage:faceSizeRatioInterval:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:faceSizeRatioInterval:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceSizeRatioInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"DOTIntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"Raw image. Image must be in ","type":"text"},{"code":".rawBgr","type":"codeVoice"},{"text":" format.","type":"text"}]}]},{"name":"faceSizeRatioInterval","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Face size interval as a ratio to shorter image side. This defines the size of searched face in the image."},{"type":"text","text":" "},{"type":"text","text":"Valid values are in interval [0.0, 1.0]. "},{"type":"codeVoice","code":"faceSizeRatioInterval.min"},{"type":"text","text":" must be greater than or equal to minimal valid face size,"},{"type":"text","text":" "},{"type":"text","text":"which depends on the active detection module."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" for this parameter."}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","op":"replace"},{"value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace"},{"value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","op":"replace"},{"value":"initWithImage:faceSizeRatioInterval:error:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1init(image:faceSizeRatioInterval:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:faceSizeRatioInterval:error:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1init(image:faceSizeRatioInterval:)\/fragments","op":"replace"},{"value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle","op":"replace"},{"value":"DOTFFaceImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title","op":"replace"},{"value":[{"text":"DOTFFaceImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments","op":"replace"},{"value":[{"text":"DOTFFaceImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/navigatorTitle","op":"replace"}]}]}