{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/corner","interfaceLanguage":"swift"},"metadata":{"title":"corner","externalID":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner(py)corner","role":"symbol","navigatorTitle":[{"text":"corner","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"corner","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner","text":"EyeGazeLivenessCorner"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"corner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner","text":"EyeGazeLivenessCorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/corner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/corner"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"abstract":[{"type":"text","text":"Objective-C wrapper of "},{"code":"EyeGazeLivenessCorner","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","title":"WrappedEyeGazeLivenessCorner","navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedEyeGazeLivenessCorner"}]},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/corner":{"type":"topic","title":"corner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/corner","role":"symbol","navigatorTitle":[{"text":"corner","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/corner","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"corner","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner","text":"EyeGazeLivenessCorner","kind":"typeIdentifier"}],"kind":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","abstract":[{"text":"Eye gaze liveness corner.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"navigatorTitle":[{"text":"EyeGazeLivenessCorner","kind":"identifier"}],"title":"EyeGazeLivenessCorner","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"corner","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"corner","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner","text":"DOTFEyeGazeLivenessCorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner"},{"text":" ","kind":"text"},{"text":"corner","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title","value":"DOTFWrappedEyeGazeLivenessCorner"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1corner\/title","op":"replace","value":"corner"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1corner\/fragments","value":[{"kind":"identifier","text":"corner"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title","value":"DOTFEyeGazeLivenessCorner","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCorner"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments"}]}]}