{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/init(corner:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/init(corner:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/init(corner:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner(im)initWithCorner:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"corner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner","text":"EyeGazeLivenessCorner"},{"kind":"text","text":")"}],"roleHeading":"Initializer","title":"init(corner:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCorner:"}],"modules":[{"name":"DotFaceCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"corner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EyeGazeLivenessCorner","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/init(corner:)":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/init(corner:)","kind":"symbol","role":"symbol","title":"init(corner:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithCorner:"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/init(corner:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"corner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner"},{"kind":"text","text":")"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"title":"WrappedEyeGazeLivenessCorner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"EyeGazeLivenessCorner"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner":{"abstract":[{"type":"text","text":"Eye gaze liveness corner."}],"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","kind":"symbol","type":"topic","title":"EyeGazeLivenessCorner"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithCorner:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCorner:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCorner:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","text":"DOTFEyeGazeLivenessCorner"},{"kind":"text","text":") "},{"kind":"internalParam","text":"corner"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithCorner:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1init(corner:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCorner:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1init(corner:)\/fragments"},{"value":"DOTFWrappedEyeGazeLivenessCorner","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title"},{"value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments"},{"value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/navigatorTitle"},{"value":"DOTFEyeGazeLivenessCorner","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title"},{"value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments"},{"value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/navigatorTitle"}]}]}