{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"symbolKind":"method","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner(im)isEqual:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Method","title":"isEqual(_:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/isEqual(_:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.3.0"}],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"title":"isEqual(_:)","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/isequal(_:)","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","kind":"symbol","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"EyeGazeLivenessCorner"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"title":"WrappedEyeGazeLivenessCorner","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"isEqual:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"value":"DOTFWrappedEyeGazeLivenessCorner","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}],"op":"replace"}]}]}