{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","text":"PointDouble"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition"]]},"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble"},{"text":"]","kind":"text"}],"title":"points","symbolKind":"property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"points","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@CM@DotDocument@objc(cs)DOTDocumentDetectionPosition(py)points"},"variants":[{"paths":["\/documentation\/dotdocument\/detectionposition\/points"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/detectionposition\/points"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/points"},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble":{"title":"PointDouble","url":"\/documentation\/dotdocument\/pointdouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DetectionPosition":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"text":"Position of the document card in the image.","type":"text"}],"title":"DetectionPosition","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DetectionPosition/points":{"url":"\/documentation\/dotdocument\/detectionposition\/points","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"points","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DetectionPosition\/points","kind":"symbol","title":"points"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"points"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"points","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<DOTPointDouble *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"points"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDocumentDetectionPosition","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDocumentDetectionPosition"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition~1points\/title","value":"points"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DetectionPosition~1points\/fragments","op":"replace","value":[{"kind":"identifier","text":"points"}]}]}]}