{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" = .init(), ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"text":" = try! .init(\n                minValidSamplesInRowToStartCandidateSelection: Defaults.minValidSamplesInRowToStartCandidateSelection,\n                candidateSelectionDurationMillis: Defaults.candidateSelectionDurationMillis\n            ), ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"FingersAutoCaptureFrameParametersValidator","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator"},{"text":"], ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"text":" = .Presets.standard.build(), ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":"? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Create fingers auto capture controller configuration."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/init(common:autocapture:validators:qualityattributethresholds:detectionarea:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class"]]},"kind":"symbol","metadata":{"roleHeading":"Initializer","title":"init(common:autoCapture:validators:qualityAttributeThresholds:detectionArea:)","symbolKind":"init","externalID":"s:14DotFingersCore0B21AutoCaptureControllerC13ConfigurationC6common04autoE010validators26qualityAttributeThresholds13detectionAreaAE0aC006CommonG0C_0aE00deG0CSayAA0bdE24FrameParametersValidator_pGAA0bde7QualitylM0CAK15RectangleDoubleCSgtKcfc","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"text":", ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"FingersAutoCaptureFrameParametersValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator"},{"text":"], ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:validators:qualityAttributeThresholds:detectionArea:)"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class":{"type":"topic","kind":"symbol","title":"FingersAutoCaptureController.Configuration","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration of the fingers auto capture non-UI component."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"role":"symbol","title":"FingersAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureController"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"title":"FingersAutoCaptureFrameParametersValidator","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator","kind":"symbol","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class/init(common:autoCapture:validators:qualityAttributeThresholds:detectionArea:)":{"title":"init(common:autoCapture:validators:qualityAttributeThresholds:detectionArea:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validators"},{"text":": [","kind":"text"},{"text":"FingersAutoCaptureFrameParametersValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator"},{"text":"], ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Create fingers auto capture controller configuration."}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/init(common:autocapture:validators:qualityattributethresholds:detectionarea:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:validators:qualityAttributeThresholds:detectionArea:)"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/CommonConfiguration":{"kind":"symbol","title":"CommonConfiguration","url":"\/documentation\/dotfingerscore\/commonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Common configuration for all components."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CommonConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle"},{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/navigatorTitle"},{"op":"replace","value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CommonConfiguration\/navigatorTitle"}]}]}