{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/four"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/four"]}],"sections":[],"metadata":{"title":"MultiRangeLivenessChallengeItem.four","externalID":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem@DOTMultiRangeLivenessChallengeItemFour","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemFour","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"four","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"four"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/four"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem":{"role":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem","abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"title":"MultiRangeLivenessChallengeItem","type":"topic","navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/four":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"four"}],"url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/four","title":"MultiRangeLivenessChallengeItem.four","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/four","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemFour"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTMultiRangeLivenessChallengeItemFour","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItemFour","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DOTMultiRangeLivenessChallengeItemFour","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/navigatorTitle","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1four\/title","value":"DOTMultiRangeLivenessChallengeItemFour","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1four\/fragments","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemFour"}],"op":"replace"}]}]}