{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/one"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem"]]},"metadata":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"one","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem@DOTMultiRangeLivenessChallengeItemOne","navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}],"symbolKind":"case","title":"MultiRangeLivenessChallengeItem.one"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/one"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/one"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"one"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem":{"abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"title":"MultiRangeLivenessChallengeItem","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/one":{"abstract":[],"navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}],"title":"MultiRangeLivenessChallengeItem.one","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/one","type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/one","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"one","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTMultiRangeLivenessChallengeItemOne"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemOne"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/navigatorTitle","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1one\/title","value":"DOTMultiRangeLivenessChallengeItemOne"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1one\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}]}]}]}