{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"three","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/three"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/three"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/three","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem@DOTMultiRangeLivenessChallengeItemThree","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"three"}],"roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"title":"MultiRangeLivenessChallengeItem.three"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem":{"type":"topic","abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"title":"MultiRangeLivenessChallengeItem","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/three":{"type":"topic","abstract":[],"title":"MultiRangeLivenessChallengeItem.three","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"three","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/three","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemThree"}],"role":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/three"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItemThree"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItem"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/fragments","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/navigatorTitle","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1three\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItemThree"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1three\/fragments","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}]}]}]}