{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/loggerloglevel\/debug"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/loggerloglevel\/debug"]}],"abstract":[{"text":"Logs events suitable for debugging purposes.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"LoggerLogLevel.debug","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelDebug","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/debug","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/debug":{"title":"LoggerLogLevel.debug","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/loggerloglevel\/debug","abstract":[{"text":"Logs events suitable for debugging purposes.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/debug"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","title":"DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","url":"\/documentation\/dotnfc\/loggerloglevel","abstract":[{"type":"text","text":"Available log levels."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","role":"symbol","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTLoggerLogLevelDebug","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"op":"replace","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1debug\/title","value":"DOTLoggerLogLevelDebug","op":"replace"},{"value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1debug\/fragments"},{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}