{"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/!=(_:_:)"],"generated":true,"anchor":"Operators"}],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/loggerloglevel\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.17.1"}]},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"url":"\/documentation\/dotnfc\/loggerloglevel","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","type":"topic","title":"LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"abstract":[{"text":"Available log levels.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/!=(_:_:)":{"title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/dotnfc\/loggerloglevel\/!=(_:_:)","abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/!=(_:_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"}]}]}