{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelInfo","title":"LoggerLogLevel.info","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}]},"abstract":[{"type":"text","text":"Logs informative events."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/loggerloglevel\/info"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/loggerloglevel\/info"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/info","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/info":{"abstract":[{"text":"Logs informative events.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/info","role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"url":"\/documentation\/dotnfc\/loggerloglevel\/info","title":"LoggerLogLevel.info","type":"topic"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"abstract":[{"text":"Available log levels.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"kind":"symbol","title":"LoggerLogLevel","url":"\/documentation\/dotnfc\/loggerloglevel","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTLoggerLogLevelInfo","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1info\/title","value":"DOTLoggerLogLevelInfo","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1info\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace"}]}]}