{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/none"},"sections":[],"metadata":{"title":"LoggerLogLevel.none","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelNone","modules":[{"name":"DotNfc"}],"role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"abstract":[{"type":"text","text":"Disables logging."}],"variants":[{"paths":["\/documentation\/dotnfc\/loggerloglevel\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/loggerloglevel\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"title":"LoggerLogLevel","url":"\/documentation\/dotnfc\/loggerloglevel","type":"topic","abstract":[{"text":"Available log levels.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/none":{"title":"LoggerLogLevel.none","kind":"symbol","url":"\/documentation\/dotnfc\/loggerloglevel\/none","abstract":[{"type":"text","text":"Disables logging."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/none","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTLoggerLogLevelNone","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTLoggerLogLevel","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle"},{"value":"DOTLoggerLogLevelNone","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1none\/title"},{"value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1none\/fragments"}]}]}