{"metadata":{"title":"RawRepresentable Implementations","modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/hashValue"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/hash(into:)"],"anchor":"Instance-Methods"}],"kind":"article","variants":[{"paths":["\/documentation\/dotnfc\/loggerloglevel\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/hash(into:)":{"abstract":[],"title":"hash(into:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/hash(into:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotnfc\/loggerloglevel\/hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/hashValue":{"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"abstract":[],"role":"symbol","type":"topic","title":"hashValue","url":"\/documentation\/dotnfc\/loggerloglevel\/hashvalue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/hashValue","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"abstract":[{"text":"Available log levels.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"kind":"symbol","title":"LoggerLogLevel","url":"\/documentation\/dotnfc\/loggerloglevel","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title","op":"replace"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","op":"replace"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}