{"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmNotDetectedValidator(im)validateWithPalmAutoCaptureFrameParameters:","symbolKind":"method","title":"validate(palmAutoCaptureFrameParameters:)","navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}],"name":"palmAutoCaptureFrameParameters"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" to indicate there was no suitable palm detected in the image."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/validate(palmautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/validate(palmautocaptureframeparameters:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/validate(palmAutoCaptureFrameParameters:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Validate confidence of the detected palm.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/validate(palmAutoCaptureFrameParameters:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/validate(palmautocaptureframeparameters:)","navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"title":"validate(palmAutoCaptureFrameParameters:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/validate(palmAutoCaptureFrameParameters:)","abstract":[{"text":"Validate confidence of the detected palm.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","abstract":[{"text":"Information from the detection process about the detected palm.","type":"text"}],"title":"PalmAutoCaptureFrameParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmNotDetectedValidator"}],"title":"PalmNotDetectedValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","type":"topic","abstract":[{"text":"Validates confidence of the detected palm.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"DOTPPalmAutoCaptureFrameParameters","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters"},{"text":" *) ","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"palmAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"text":"Frame parameters to validate.","type":"text"}]}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" to indicate there was no suitable palm detected in the image.","type":"text"}]}],"kind":"content"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1validate(palmAutoCaptureFrameParameters:)\/title","op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title","op":"replace","value":"DOTPPalmAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","op":"replace","value":"DOTPPalmNotDetectedValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments","op":"replace","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}]}]}]}