{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomRight","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","title":"bottomRight","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"role":"symbol","roleHeading":"Instance Property","externalID":"s:11DotDocument7BarcodeC17DetectionPositionC11bottomRight0A4Core11PointDoubleCvp"},"variants":[{"paths":["\/documentation\/dotdocument\/barcode\/detectionposition\/bottomright"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"text":"Bottom right corner point.","type":"text"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotdocument\/pointdouble"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","abstract":[{"text":"Position of the barcode in the image.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"Barcode.DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcode\/detectionposition"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/bottomRight":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/bottomright","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/bottomRight","title":"bottomRight","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"abstract":[{"type":"text","text":"Bottom right corner point."}],"role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Barcode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","abstract":[{"text":"Result of barcode detection process.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"Barcode","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Barcode","kind":"identifier"}],"navigatorTitle":[{"text":"Barcode","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcode"}},"variantOverrides":[{"patch":[{"value":"DOTPointDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","op":"replace"},{"value":"DOTDBarcode","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBarcode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDBarcode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}