{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdDetection","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"symbolKind":"case","title":"DotFingersModuleId.detection","role":"symbol","modules":[{"name":"DotNfc"}]},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotfingersmoduleid\/detection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfingersmoduleid\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/detection","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFingersModuleId":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfingersmoduleid","role":"symbol","abstract":[{"code":"DotFingers","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"title":"DotFingersModuleId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersModuleId"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/detection":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"detection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/detection","url":"\/documentation\/dotnfc\/dotfingersmoduleid\/detection","abstract":[],"title":"DotFingersModuleId.detection","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFingersModuleIdDetection","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFingersModuleId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/title"},{"value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/fragments"},{"value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/navigatorTitle"},{"value":"DotFingersModuleIdDetection","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1detection\/title"},{"value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1detection\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}