{"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"anchor":"Operators","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/!=(_:_:)"],"title":"Operators"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/Equatable-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"DotNfc"}],"title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"]]},"kind":"article","sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotfingersmoduleid\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFingersModuleId":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfingersmoduleid","role":"symbol","abstract":[{"code":"DotFingers","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"title":"DotFingersModuleId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersModuleId"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/!=(_:_:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/dotfingersmoduleid\/!=(_:_:)","abstract":[],"kind":"symbol","title":"!=(_:_:)"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/title","value":"DotFingersModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}