{"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotfingersmoduleid\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/hash(into:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"]]},"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotCore@E@DotFingersModuleId","extendedModule":"Swift","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"symbolKind":"method","title":"hash(into:)","modules":[{"name":"DotNfc","relatedModules":["Swift"]}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/hash(into:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"abstract":[],"url":"\/documentation\/dotnfc\/dotfingersmoduleid\/hash(into:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/hash(into:)","title":"hash(into:)","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfingersmoduleid","role":"symbol","abstract":[{"code":"DotFingers","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"title":"DotFingersModuleId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersModuleId"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/navigatorTitle","op":"replace"}]}]}