{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"]]},"sections":[],"metadata":{"externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdTransformation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"title":"DotFingersModuleId.transformation","symbolKind":"case","roleHeading":"Case","modules":[{"name":"DotNfc"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/dotfingersmoduleid\/transformation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfingersmoduleid\/transformation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/transformation","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/transformation":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transformation"}],"navigatorTitle":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/transformation","url":"\/documentation\/dotnfc\/dotfingersmoduleid\/transformation","abstract":[],"title":"DotFingersModuleId.transformation","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfingersmoduleid","role":"symbol","abstract":[{"code":"DotFingers","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"title":"DotFingersModuleId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersModuleId"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DotFingersModuleIdTransformation","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1transformation\/title","value":"DotFingersModuleIdTransformation","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1transformation\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/title","value":"DotFingersModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace"}]}]}