{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit"]]},"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit(py)hash","title":"hash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/hash"]},{"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/hash","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"title":"MrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","role":"symbol","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"type":"topic","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzcheckdigit","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}]},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/hash":{"kind":"symbol","role":"symbol","abstract":[],"title":"hash","url":"\/documentation\/dotdocument\/mrzcheckdigit\/hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title","op":"replace","value":"DOTMrzCheckDigit"},{"op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1hash\/title","value":"hash"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1hash\/fragments"}]}]}