{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBarcode:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(im)initWithBarcode:","symbolKind":"method","modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Instance Method","title":"initWithBarcode:","navigatorTitle":[{"text":"initWithBarcode:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithBarcode:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules\/initWithBarcode:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfigurationModules/initWithBarcode:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcode:"}],"kind":"symbol","type":"topic","title":"initWithBarcode:","role":"symbol","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:","navigatorTitle":[{"kind":"identifier","text":"initWithBarcode:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules\/initWithBarcode:","abstract":[]},"doc://DotNfc/documentation/DotNfc/DotDocumentBarcodeModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"kind":"symbol","type":"topic","title":"DotDocumentBarcodeModuleConfiguration","role":"symbol","url":"\/documentation\/dotnfc\/dotdocumentbarcodemoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}]},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"kind":"symbol","type":"topic","title":"DotDocumentLibraryConfigurationModules","role":"symbol","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfigurationmodules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfigurationModules","abstract":[{"type":"text","text":"Document library module configuration."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}