{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Validate maximum pitch angle of the device."}],"metadata":{"modules":[{"name":"DotFaceLite"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"DevicePitchTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevicePitchTooHighValidator"}],"navigatorTitle":[{"kind":"identifier","text":"DevicePitchTooHighValidator"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLDevicePitchTooHighValidator"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init(maxAngleThreshold:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/identifier","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/maxAngleThreshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/defaultAngleThreshold"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFLDevicePitchTooHighValidator) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevicePitchTooHighValidator"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.3.2"}],"title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/dependencyIdentifiers":{"url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/dependencyidentifiers","title":"dependencyIdentifiers","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/dependencyIdentifiers","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/init(maxAngleThreshold:)":{"url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/init(maxanglethreshold:)","title":"init(maxAngleThreshold:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init(maxAngleThreshold:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"maxAngleThreshold"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMaxAngleThreshold:error:"}],"abstract":[{"text":"Initialize with custom angle in degrees.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","title":"FaceAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/init()":{"url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/init()","title":"init()","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init()","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"text":"Initialize with default angle in degrees.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/identifier":{"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"title":"identifier","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/identifier","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/identifier","role":"symbol"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/defaultAngleThreshold":{"url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/defaultanglethreshold","title":"defaultAngleThreshold","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/defaultAngleThreshold","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultAngleThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"defaultAngleThreshold","kind":"identifier"}],"abstract":[{"text":"Default pitch angle in degrees.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator":{"title":"DevicePitchTooHighValidator","abstract":[{"type":"text","text":"Validate maximum pitch angle of the device."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DevicePitchTooHighValidator"}],"navigatorTitle":[{"text":"DevicePitchTooHighValidator","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/validate(faceAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/validate(faceautocaptureframeparameters:)","title":"validate(faceAutoCaptureFrameParameters:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/validate(faceAutoCaptureFrameParameters:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}],"abstract":[{"text":"Validate pitch angle of the device.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DevicePitchTooHighValidator/maxAngleThreshold":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/maxAngleThreshold","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/maxanglethreshold","title":"maxAngleThreshold","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxAngleThreshold"}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxAngleThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"text":"Current max pitch angle in degrees.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTFLDevicePitchTooHighValidator"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFLDevicePitchTooHighValidator"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFLDevicePitchTooHighValidator","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/identifier","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/maxAngleThreshold"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/init(maxAngleThreshold:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/validate(faceAutoCaptureFrameParameters:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/defaultAngleThreshold"],"title":"Type Properties"}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator"],"title":"Conforms To","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFLDevicePitchTooHighValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1dependencyIdentifiers\/fragments"},{"value":"initWithMaxAngleThreshold:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1init(maxAngleThreshold:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1init(maxAngleThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithMaxAngleThreshold:error:","kind":"identifier"}],"op":"replace"},{"value":"DOTFLFaceAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1init()\/title","value":"init"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1identifier\/title","value":"identifier"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1identifier\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1defaultAngleThreshold\/title","op":"replace","value":"defaultAngleThreshold"},{"value":[{"kind":"identifier","text":"defaultAngleThreshold"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1defaultAngleThreshold\/fragments"},{"op":"replace","value":"DOTFLDevicePitchTooHighValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/fragments","op":"replace","value":[{"text":"DOTFLDevicePitchTooHighValidator","kind":"identifier"}]},{"value":"validateWithFaceAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1validate(faceAutoCaptureFrameParameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1maxAngleThreshold\/title","value":"maxAngleThreshold"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1maxAngleThreshold\/fragments","op":"replace","value":[{"text":"maxAngleThreshold","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}