{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper\/init(travelDocumentType:)"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","text":"TravelDocumentType","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttypewrapper\/init(traveldocumenttype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/traveldocumenttypewrapper\/init(traveldocumenttype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"init","role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper(im)initWithTravelDocumentType:","navigatorTitle":[{"text":"initWithTravelDocumentType:","kind":"identifier"}],"title":"init(travelDocumentType:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"},{"text":")","kind":"text"}]},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"title":"TravelDocumentTypeWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper/init(travelDocumentType:)":{"navigatorTitle":[{"text":"initWithTravelDocumentType:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper\/init(traveldocumenttype:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper\/init(travelDocumentType:)","abstract":[],"title":"init(travelDocumentType:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"title":"TravelDocumentType","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithTravelDocumentType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTravelDocumentType:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithTravelDocumentType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","text":"DOTTravelDocumentType","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"travelDocumentType","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTTravelDocumentTypeWrapper"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/navigatorTitle","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper~1init(travelDocumentType:)\/title","value":"initWithTravelDocumentType:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper~1init(travelDocumentType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTravelDocumentType:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","value":"DOTTravelDocumentType"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/navigatorTitle","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]}]}]}