{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/init(detectionAreaImageSize:palm:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/init(detectionareaimagesize:palm:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/init(detectionareaimagesize:palm:)"]}],"kind":"symbol","metadata":{"symbolKind":"init","title":"init(detectionAreaImageSize:palm:)","roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters(im)initWithDetectionAreaImageSize:palm:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionAreaImageSize:palm:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"detectionAreaImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"palm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PalmDetector","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"?)","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"detectionAreaImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","text":"PalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"},{"text":"?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"title":"PalmAutoCaptureController","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"title":"PalmDetector.Palm","abstract":[{"type":"text","text":"Result of the palm detection process."}],"navigatorTitle":[{"text":"Palm","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"title":"ImageSize","type":"topic","url":"\/documentation\/dotpalmcore\/imagesize","role":"symbol","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/init(detectionAreaImageSize:palm:)":{"title":"init(detectionAreaImageSize:palm:)","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/init(detectionareaimagesize:palm:)","role":"symbol","navigatorTitle":[{"text":"initWithDetectionAreaImageSize:palm:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"detectionAreaImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"palm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PalmDetector","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"text":".","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/init(detectionAreaImageSize:palm:)"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","role":"symbol","fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"title":"DOTPPalmDetectorPalm","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected palm."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","title":"PalmAutoCaptureFrameParameters"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmDetector"}],"title":"PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithDetectionAreaImageSize:palm:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDetectionAreaImageSize:palm:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetectionAreaImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"DOTImageSize","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},{"text":" *) ","kind":"text"},{"text":"detectionAreaImageSize","kind":"internalParam"},{"kind":"text","text":" "},{"text":"palm:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","text":"DOTPPalmDetectorPalm","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"palm"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace"},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1init(detectionAreaImageSize:palm:)\/title","value":"initWithDetectionAreaImageSize:palm:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDetectionAreaImageSize:palm:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1init(detectionAreaImageSize:palm:)\/fragments","op":"replace"},{"value":"DOTPPalmAutoCaptureFrameParameters","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace","value":"DOTPPalmDetector"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}