{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate","text":"NfcTravelDocumentReaderDelegate"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/setdelegate(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/setDelegate(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set delegate, "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":" will hold weak reference to it."}],"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","title":"setDelegate(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderDelegate","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"s:6DotNfc0B28TravelDocumentReaderProtocolPAAE11setDelegateyyAA0bcdeH0_pSgF","extendedModule":"DotNfc","platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate":{"role":"symbol","title":"NfcTravelDocumentReaderDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the NFC reading events."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol/setDelegate(_:)":{"role":"symbol","title":"setDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderDelegate","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set delegate, "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":" will hold weak reference to it."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/setDelegate(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/setdelegate(_:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.5.3"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol":{"role":"symbol","title":"NfcTravelDocumentReaderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/title","value":"DOTNNfcTravelDocumentReaderDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/title","value":"DOTNNfcTravelDocumentReaderProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}