{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" instance."}]}]},{"kind":"parameters","parameters":[{"name":"bgrRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/ciimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/ciimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgrRawImage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}],"title":"create(bgrRawImage:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTCIImageFactory(cm)createWithBgrRawImage:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory/create(bgrRawImage:)":{"role":"symbol","title":"create(bgrRawImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory\/create(bgrRawImage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"url":"\/documentation\/dotdocument\/ciimagefactory\/create(bgrrawimage:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.5.3"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory":{"role":"symbol","title":"CIImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotdocument\/ciimagefactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage":{"role":"symbol","title":"BgrRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"url":"\/documentation\/dotdocument\/bgrrawimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithBgrRawImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithBgrRawImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","text":"DOTBgrRawImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bgrRawImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory~1create(bgrRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}