{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfaceliteenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfaceliteenabled"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"isFaceLiteEnabled","navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceLiteEnabled","symbolKind":"property","required":true,"modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"title":"isFaceLiteEnabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfaceliteenabled","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"isFaceLiteEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/fragments"},{"op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/navigatorTitle"},{"op":"replace","value":"isFaceLiteEnabled","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title"},{"op":"replace","value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments"}]}]}