{"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isPalmEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isPalmEnabled","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isPalmEnabled","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPalmEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/ispalmenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/ispalmenabled"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isPalmEnabled":{"title":"isPalmEnabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPalmEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"isPalmEnabled","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/ispalmenabled","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isPalmEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"isPalmEnabled"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isPalmEnabled","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isPalmEnabled","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isPalmEnabled"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/fragments"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/navigatorTitle"}]}]}