{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/licensebytes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/licensebytes"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"licenseBytes","navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)licenseBytes","symbolKind":"property","required":true,"modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/licenseBytes","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/licenseBytes":{"title":"licenseBytes","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/licensebytes","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/licenseBytes"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"licenseBytes","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"licenseBytes"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"licenseBytes"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"licenseBytes","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/title"},{"value":[{"kind":"identifier","text":"licenseBytes"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/fragments"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/title"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/fragments"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}