{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"image"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"image","navigatorTitle":[{"text":"image","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerSample(py)image","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"identifier","text":"image"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Sample image."}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample\/image"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerSample/image":{"title":"image","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample\/image","kind":"symbol","abstract":[{"type":"text","text":"Sample image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample\/image","fragments":[{"text":"image","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerSample":{"title":"DOTPPalmAutoCaptureControllerSample","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample","kind":"symbol","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample","fragments":[{"text":"DOTPPalmAutoCaptureControllerSample","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"navigatorTitle":[{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","title":"Image","url":"\/documentation\/dotpalmcore\/image","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}