{"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:timestampMillis:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"initWithImage:timestampMillis:","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerSample(im)initWithImage:timestampMillis:","navigatorTitle":[{"text":"initWithImage:timestampMillis:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample\/initWithImage:timestampMillis:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample\/initwithimage:timestampmillis:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"timestampMillis:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"timestampMillis"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/Image":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotpalmcore\/image","title":"Image","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerSample":{"title":"DOTPPalmAutoCaptureControllerSample","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample","kind":"symbol","fragments":[{"text":"DOTPPalmAutoCaptureControllerSample","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerSample/initWithImage:timestampMillis:":{"title":"initWithImage:timestampMillis:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:timestampMillis:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample\/initwithimage:timestampmillis:","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample\/initWithImage:timestampMillis:","kind":"symbol","navigatorTitle":[{"text":"initWithImage:timestampMillis:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"}]}]}