{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPlaceholderPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"rect","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"]}],"metadata":{"role":"symbol","title":"createPlaceholderPath(rect:cornerRadius:)","navigatorTitle":[{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Type Method","externalID":"c:@M@DotFaceLite@objc(cs)DOTBezierPathFactory(cm)createPlaceholderPathWithRect:cornerRadius:","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPlaceholderPath","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BezierPathFactory":{"abstract":[],"title":"BezierPathFactory","kind":"symbol","type":"topic","navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bezierpathfactory","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BezierPathFactory","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"abstract":[],"title":"createPlaceholderPath(rect:cornerRadius:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"url":"\/documentation\/dotfacelite\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createPlaceholderPath"},{"text":"(","kind":"text"},{"text":"rect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"createPlaceholderPathWithRect:cornerRadius:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"},{"kind":"text","text":" *) "},{"text":"createPlaceholderPathWithRect:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cornerRadius:"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"DOTBezierPathFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory\/fragments","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"createPlaceholderPathWithRect:cornerRadius:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"op":"replace"}]}]}