{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/name"},"metadata":{"title":"name","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)name","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzNameElement","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/name"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/name"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","type":"topic","title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"title":"Td3MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/name":{"title":"name","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"name","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"}],"navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone\/name","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/name","abstract":[],"kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"url":"\/documentation\/dotdocument\/mrznameelement","title":"MrzNameElement","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"name","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"name"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTMrzNameElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"name","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/navigatorTitle"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1name\/title"},{"value":[{"text":"name","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1name\/fragments"},{"op":"replace","value":"DOTMrzNameElement","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title"},{"op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments"},{"op":"replace","value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}