{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule\/moduleId"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmModuleId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmmodule\/moduleid"]},{"paths":["\/documentation\/dotpalmcore\/dotpalmmodule\/moduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"moduleId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId","text":"DotPalmModuleId"}],"required":true,"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(pl)DotPalmModule(py)moduleId","role":"symbol","title":"moduleId","navigatorTitle":[{"kind":"identifier","text":"moduleId"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModule/moduleId":{"url":"\/documentation\/dotpalmcore\/dotpalmmodule\/moduleid","required":true,"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId","text":"DotPalmModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule\/moduleId","title":"moduleId","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId":{"url":"\/documentation\/dotpalmcore\/dotpalmmoduleid","role":"symbol","abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module identifier.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","title":"DotPalmModuleId","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModule":{"url":"\/documentation\/dotpalmcore\/dotpalmmodule","role":"symbol","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModule","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmModule","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","title":"DotPalmModule","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"moduleId"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"moduleId","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotPalmModuleId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule~1moduleId\/title","op":"replace","value":"moduleId"},{"value":[{"kind":"identifier","text":"moduleId"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule~1moduleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/title","value":"DotPalmModule"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmModule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}