{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewController(_:processed:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontroller(_:processed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontroller(_:processed:)"]}],"sections":[],"metadata":{"roleHeading":"Instance Method","title":"multiRangeLivenessViewController(_:processed:)","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"kind":"text","text":")"}],"symbolKind":"method","required":true,"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessLiteViewController:processed:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewController:processed:"}]},"abstract":[{"text":"Tells the delegate that the new detection was processed.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(multiRangeLivenessLiteViewController:processed:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"kind":"text","text":" "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","title":"FaceAutoCaptureDetection"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate","navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate","kind":"symbol","title":"MultiRangeLivenessViewControllerDelegate","role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"abstract":[{"text":"UI component for capturing images suitable for Multi-Range Liveness evaluation.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","type":"topic","role":"symbol","title":"MultiRangeLivenessViewController","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","kind":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewController(_:processed:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewController(_:processed:)","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontroller(_:processed:)","navigatorTitle":[{"text":"multiRangeLivenessLiteViewController:processed:","kind":"identifier"}],"required":true,"title":"multiRangeLivenessViewController(_:processed:)","abstract":[{"text":"Tells the delegate that the new detection was processed.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":", ","kind":"text"},{"text":"processed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"text":")","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"multiRangeLivenessLiteViewController:processed:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessLiteViewController:processed:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"multiRangeLivenessLiteViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLMultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"processed:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLFaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","op":"replace","value":"DOTFLFaceAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewController(_:processed:)\/title","op":"replace","value":"multiRangeLivenessLiteViewController:processed:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewController(_:processed:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessLiteViewController:processed:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}