{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}],"title":"multiRangeLivenessViewControllerViewWillTransition(_:)","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewWillTransition:"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"multiRangeLivenessViewControllerViewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessLiteViewControllerViewWillTransition:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilltransition(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilltransition(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(multiRangeLivenessLiteViewControllerViewWillTransition:) "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillTransition(_:)"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"title":"MultiRangeLivenessViewController","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for Multi-Range Liveness evaluation."}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewWillTransition(_:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerViewWillTransition:","kind":"identifier"}],"role":"symbol","abstract":[],"title":"multiRangeLivenessViewControllerViewWillTransition(_:)","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilltransition(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillTransition(_:)"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate":{"navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"title":"MultiRangeLivenessViewControllerDelegate","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"multiRangeLivenessLiteViewControllerViewWillTransition:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewWillTransition:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"multiRangeLivenessLiteViewControllerViewWillTransition:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"DOTFLMultiRangeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController"},{"op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillTransition(_:)\/title","value":"multiRangeLivenessLiteViewControllerViewWillTransition:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"multiRangeLivenessLiteViewControllerViewWillTransition:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillTransition(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/title","value":"DOTFLMultiRangeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/fragments","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]}]}]}