{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilldisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilldisappear(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"multiRangeLivenessViewControllerViewWillDisappear(_:)","role":"symbol","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessLiteViewControllerViewWillDisappear:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewWillDisappear:"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(multiRangeLivenessLiteViewControllerViewWillDisappear:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"kind":"text","text":")"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillDisappear(_:)","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate":{"abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate","title":"MultiRangeLivenessViewControllerDelegate","type":"topic","role":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewWillDisappear(_:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilldisappear(_:)","title":"multiRangeLivenessViewControllerViewWillDisappear(_:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewWillDisappear:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillDisappear(_:)"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","title":"MultiRangeLivenessViewController","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewWillDisappear:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","text":"DOTFLMultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillDisappear(_:)\/title","value":"multiRangeLivenessLiteViewControllerViewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"multiRangeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}]}]}]}