{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"symbolKind":"property","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit(py)hash"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/hash","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/hash"]},{"paths":["\/documentation\/dotnfc\/mrzcheckdigit\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/hash":{"title":"hash","url":"\/documentation\/dotnfc\/mrzcheckdigit\/hash","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/hash","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzCheckDigit","kind":"identifier"}],"kind":"symbol","title":"MrzCheckDigit","url":"\/documentation\/dotnfc\/mrzcheckdigit","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"hash"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1hash\/title","value":"hash"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","op":"replace","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]}]}]}