{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules\/initwithdetection:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:"}],"roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(im)initWithDetection:","title":"initWithDetection:"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules"]]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules\/initWithDetection:"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfigurationModules":{"title":"DotPalmLibraryConfigurationModules","role":"symbol","abstract":[{"text":"Palm library module configuration.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules","fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmDetectionModuleConfiguration":{"title":"DotPalmDetectionModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Palm detection module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotpalmdetectionmoduleconfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfigurationModules/initWithDetection:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:"}],"title":"initWithDetection:","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules\/initwithdetection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules\/initWithDetection:"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/title","op":"replace","value":"DotPalmDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}