{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/description"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.description"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","extendedModule":"DotCore","externalID":"s:7DotCore0A8SdkErrorPAAE11descriptionSSvp::SYNTHESIZED::s:11DotFaceCore32MultiRangeLivenessViewControllerC5ErrorO","roleHeading":"Instance Property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/description"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error":{"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"MultiRangeLivenessViewController.Error","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"MultiRangeLivenessViewController","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Error/description":{"abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"description","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/error\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Error\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFMultiRangeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle","op":"replace"}]}]}