{"metadata":{"navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdDocument","symbolKind":"case","roleHeading":"Case","title":"DotLibraryId.document","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"document"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"document","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"type":"text","text":" identifier."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/document","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotlibraryid\/document"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotlibraryid\/document"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId":{"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotfingerscore\/dotlibraryid","type":"topic","title":"DotLibraryId","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/document":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotlibraryid\/document","abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"text":" identifier.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/document","title":"DotLibraryId.document","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotLibraryIdDocument","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/navigatorTitle"},{"op":"replace","value":"DotLibraryIdDocument","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1document\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1document\/fragments"}]}]}