{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/faceLite"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"faceLite","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"DotLibraryId.faceLite","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFaceLite","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"roleHeading":"Case","symbolKind":"case"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotlibraryid\/facelite"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotlibraryid\/facelite"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId":{"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotfingerscore\/dotlibraryid","type":"topic","title":"DotLibraryId","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/faceLite":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/faceLite","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceLite"}],"kind":"symbol","role":"symbol","title":"DotLibraryId.faceLite","abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotlibraryid\/facelite"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotLibraryIdFaceLite","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}]}]}},{"value":"DotLibraryId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1faceLite\/title","value":"DotLibraryIdFaceLite"},{"value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1faceLite\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}