{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"BgraRawImage"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"cgImage"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" instance."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory\/create(cgImage:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrarawimagefactory\/create(cgimage:)"]},{"paths":["\/documentation\/dotdocument\/bgrarawimagefactory\/create(cgimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithCgImage:","roleHeading":"Type Method","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"symbolKind":"method","title":"create(cgImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}]},"references":{"doc://DotDocument/documentation/DotDocument/BgraRawImageFactory":{"title":"BgraRawImageFactory","type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimagefactory","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}]},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.7.1","type":"text"}],"type":"topic","role":"collection"},"doc://DotDocument/documentation/DotDocument/BgraRawImageFactory/create(cgImage:)":{"url":"\/documentation\/dotdocument\/bgrarawimagefactory\/create(cgimage:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"text":" as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"}],"type":"topic","title":"create(cgImage:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory\/create(cgImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}]},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"title":"BgraRawImage","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","role":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"createWithCgImage:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCgImage:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"DOTBgraRawImage"},{"kind":"text","text":" *) "},{"text":"createWithCgImage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CGImage","preciseIdentifier":"c:@S@CGImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cgImage"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"value":"createWithCgImage:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory~1create(cgImage:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory~1create(cgImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments"}]}]}