{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult\/init(detection:result:phase:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier","text":"FaceAutoCaptureDetection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","kind":"typeIdentifier","text":"FaceAutoCaptureResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Phase","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC5PhaseO","kind":"typeIdentifier","text":"Phase"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult"]]},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult"},{"text":"?, ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Phase","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC5PhaseO"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"init","role":"symbol","externalID":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC9detection6result5phaseAeA0bdE9DetectionC_AA0bdeH0CSgAC5PhaseOtcfc","title":"init(detection:result:phase:)","roleHeading":"Initializer"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","url":"\/documentation\/dotfacelite\/faceautocaptureresult","type":"topic","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"title":"FaceAutoCaptureResult"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult":{"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"title":"FaceAutoCaptureController.ProcessingResult","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","abstract":[{"text":"The result returned from the processing of one image during the face auto capture process.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult/init(detection:result:phase:)":{"title":"init(detection:result:phase:)","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult\/init(detection:result:phase:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult"},{"text":"?, ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Phase","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC5PhaseO"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)","kind":"symbol","role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Phase":{"title":"FaceAutoCaptureController.Phase","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Phase","abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/phase","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Phase","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Phase","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 8.17.1","type":"text"}],"title":"DotFaceLite","role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","type":"topic","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"title":"FaceAutoCaptureDetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFLFaceAutoCaptureResult","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle"},{"op":"replace","value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"DOTFLFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle"}]}]}