{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/init(image:timestampMillis:depthImage:cameraCalibrationData:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/cameraCalibrationData","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/depthImage","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/timestampMillis"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"s:14DotFingersCore0B21AutoCaptureControllerC11PhotoSampleC","title":"FingersAutoCaptureController.PhotoSample","navigatorTitle":[{"text":"PhotoSample","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"],"title":"Fingers auto capture process","anchor":"Fingers-auto-capture-process","generated":true}],"abstract":[{"text":"The photo-capture sample, supplied in response to a ","type":"text"},{"code":".captureDepth","type":"codeVoice"},{"text":" event during the fingers auto capture process.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingersAutoCaptureControllerPhotoSample) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample/cameraCalibrationData":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/cameraCalibrationData","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraCalibrationData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCameraCalibrationData","preciseIdentifier":"c:objc(cs)AVCameraCalibrationData","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","title":"cameraCalibrationData","abstract":[{"text":"Camera calibration data captured alongside the photo.","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample\/cameracalibrationdata"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample/depthImage":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/depthImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"depthImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","title":"depthImage","abstract":[{"text":"Depth image captured alongside the photo.","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample\/depthimage"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","title":"FingersAutoCaptureController.ProcessingResult","role":"symbol","abstract":[{"text":"The result returned from the processing of one image during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample/init(image:timestampMillis:depthImage:cameraCalibrationData:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/init(image:timestampMillis:depthImage:cameraCalibrationData:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"depthImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cameraCalibrationData","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AVCameraCalibrationData","preciseIdentifier":"c:objc(cs)AVCameraCalibrationData","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(image:timestampMillis:depthImage:cameraCalibrationData:)","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample\/init(image:timestampmillis:depthimage:cameracalibrationdata:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"navigatorTitle":[{"kind":"identifier","text":"PhotoSample"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"code":".captureDepth","type":"codeVoice"},{"text":" event during the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","title":"FingersAutoCaptureController.PhotoSample","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","title":"FingersAutoCaptureResult","role":"symbol","abstract":[{"text":"The final result of the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Sample":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"navigatorTitle":[{"text":"Sample","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","title":"FingersAutoCaptureController.Sample","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected fingers."}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","role":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCapturePhase"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCapturePhase"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"type":"text","text":"Phase of the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","title":"FingersAutoCapturePhase","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample/timestampMillis":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/timestampMillis","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"timestampMillis","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"timestampMillis","abstract":[{"text":"Sample timestamp.","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample\/timestampmillis"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample/image":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample\/image","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"image","abstract":[{"text":"Sample image.","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample\/image"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DetectionPosition","abstract":[{"text":"Position of the finger in the image.","type":"text"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/detectionposition"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureEvent":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureevent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureEvent"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent","title":"FingersAutoCaptureEvent","role":"symbol","abstract":[{"text":"An event emitted during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureEvent"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureResult","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureDetection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCapturePhase","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle"},{"op":"replace","value":"DOTFGDetectionPosition","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureEvent","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureEvent"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureEvent"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}