{"metadata":{"navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureController(im)processWithSample:error:","symbolKind":"method","roleHeading":"Instance Method","title":"process(sample:)","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Sample","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC6SampleC"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC16ProcessingResultC"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","text":"Sample","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC6SampleC"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Input sample. Terminates if ","type":"text"},{"type":"codeVoice","code":"sample.image"},{"text":" property is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"type":"paragraph"}],"name":"sample"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The result of processing of the input sample.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"style":"note","name":"Throws","content":[{"inlineContent":[{"type":"text","text":"Throws an error if you call this method after the fingers auto capture process has finished."}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"Process an input sample and update the state."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/process(sample:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/process(sample:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/process(sample:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerProcessingResult":{"fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureControllerProcessingResult"}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerprocessingresult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult","title":"DOTFGFingersAutoCaptureControllerProcessingResult","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerSample":{"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollersample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the fingers auto capture process.","type":"text"}],"title":"DOTFGFingersAutoCaptureControllerSample","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerSample","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureControllerSample"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Sample":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"navigatorTitle":[{"text":"Sample","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","title":"FingersAutoCaptureController.Sample","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","title":"FingersAutoCaptureController.ProcessingResult","role":"symbol","abstract":[{"text":"The result returned from the processing of one image during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/process(sample:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC6SampleC","text":"Sample"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC16ProcessingResultC"}],"navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/process(sample:)","abstract":[{"type":"text","text":"Process an input sample and update the state."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/process(sample:)","title":"process(sample:)","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"processWithSample:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"processWithSample:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerProcessingResult","text":"DOTFGFingersAutoCaptureControllerProcessingResult"},{"text":" *) ","kind":"text"},{"text":"processWithSample:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerSample","text":"DOTFGFingersAutoCaptureControllerSample","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerSample"},{"text":" *) ","kind":"text"},{"text":"sample","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input sample. Terminates if "},{"type":"codeVoice","code":"sample.image"},{"type":"text","text":" property is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}]}],"name":"sample"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}],"name":"error"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of processing of the input sample."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","op":"replace","value":"DOTFGFingersAutoCaptureController"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1process(sample:)\/title","op":"replace","value":"processWithSample:error:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1process(sample:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithSample:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}