{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel"]]},"abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"languages":["swift"]}]}],"metadata":{"title":"LoggerLogLevel.error","modules":[{"name":"DotFaceCore"}],"symbolKind":"case","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelError","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/loggerloglevel\/error"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/loggerloglevel\/error"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/error","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel","abstract":[{"text":"Available log levels.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"url":"\/documentation\/dotfacecore\/loggerloglevel","kind":"symbol","title":"LoggerLogLevel"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/error":{"title":"LoggerLogLevel.error","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"url":"\/documentation\/dotfacecore\/loggerloglevel\/error","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/error","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTLoggerLogLevelError","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/navigatorTitle","op":"replace"},{"value":"DOTLoggerLogLevelError","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1error\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1error\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}