{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/istorchenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/istorchenabled"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/isTorchEnabled"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Use this flag to turn the torch on\/off during the capture process.","type":"text"},{"text":" ","type":"text"},{"text":"Torch will be turned on only if ","type":"text"},{"code":"facing","type":"codeVoice"},{"text":" property is set to ","type":"text"},{"code":".back","type":"codeVoice"},{"text":". Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"isTorchEnabled","kind":"identifier"}],"roleHeading":"Instance Property","title":"isTorchEnabled","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isTorchEnabled","symbolKind":"property"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/cameraconfiguration","kind":"symbol","title":"CameraConfiguration"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration/isTorchEnabled":{"type":"topic","title":"isTorchEnabled","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"text":"Use this flag to turn the torch on\/off during the capture process.","type":"text"},{"text":" ","type":"text"},{"text":"Torch will be turned on only if ","type":"text"},{"code":"facing","type":"codeVoice"},{"text":" property is set to ","type":"text"},{"code":".back","type":"codeVoice"},{"text":". Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotdocument\/cameraconfiguration\/istorchenabled","navigatorTitle":[{"text":"isTorchEnabled","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/isTorchEnabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"isTorchEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"isTorchEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1isTorchEnabled\/title","value":"isTorchEnabled","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1isTorchEnabled\/fragments","value":[{"text":"isTorchEnabled","kind":"identifier"}],"op":"replace"}]}]}