{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/description"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","externalID":"s:7DotCore0A12PalmModuleIdO11descriptionSSvp","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/dotpalmmoduleid\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/description","abstract":[],"type":"topic","title":"description","role":"symbol","url":"\/documentation\/dotnfc\/dotpalmmoduleid\/description","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"role":"symbol","abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotnfc\/dotpalmmoduleid","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"title":"DotPalmModuleId"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/title","op":"replace"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/fragments","op":"replace"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/navigatorTitle","op":"replace"}]}]}