{"abstract":[{"text":"Overall sharpness of the document in range [0, 1.0]. Where 0 means low sharpness and 1.0 means high sharpness.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters"]]},"metadata":{"role":"symbol","symbolKind":"property","title":"sharpness","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpness"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDImageParameters(py)sharpness","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"sharpness"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageparameters\/sharpness"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageparameters\/sharpness"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/sharpness"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sharpness","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}]}],"references":{"doc://DotDocument/documentation/DotDocument/ImageParameters":{"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/imageparameters","title":"ImageParameters","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"abstract":[{"type":"text","text":"Result of image parameters analysis."}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.16.0"}],"type":"topic","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/ImageParameters/sharpness":{"navigatorTitle":[{"kind":"identifier","text":"sharpness"}],"role":"symbol","url":"\/documentation\/dotdocument\/imageparameters\/sharpness","title":"sharpness","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/sharpness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpness"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Overall sharpness of the document in range [0, 1.0]. Where 0 means low sharpness and 1.0 means high sharpness."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sharpness","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"sharpness"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpness"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"value":[{"kind":"identifier","text":"DOTDImageParameters"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments","op":"replace"},{"op":"replace","value":"sharpness","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1sharpness\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1sharpness\/fragments","value":[{"text":"sharpness","kind":"identifier"}]}]}]}