{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Logger"}],"title":"Logger","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPLogger","modules":[{"name":"DotPalmCore"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization"],"title":"Global components"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/logLevel"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/debug(_:file:function:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/error(_:file:function:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/info(_:file:function:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/warning(_:file:function:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTPLogger) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/logger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/logger"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/Logger":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"title":"Logger","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger","kind":"symbol","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/logger"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"text":"version: 8.6.1","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Logger/info(_:file:function:)":{"role":"symbol","navigatorTitle":[{"text":"info:file:function:","kind":"identifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/info(_:file:function:)","title":"info(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"info","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"function"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/logger\/info(_:file:function:)"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library initialization."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotPalmLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibrary","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary","title":"DotPalmLibrary","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Logger/error(_:file:function:)":{"navigatorTitle":[{"text":"error:file:function:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/error(_:file:function:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"kind":"symbol","title":"error(_:file:function:)","url":"\/documentation\/dotpalmcore\/logger\/error(_:file:function:)"},"doc://DotPalmCore/documentation/DotPalmCore/Logger/logLevel":{"abstract":[{"text":"Log level currently in use. Default value is ","type":"text"},{"code":".none","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/logger\/loglevel","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/logLevel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"LoggerLogLevel","kind":"typeIdentifier"}],"role":"symbol","title":"logLevel"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/Logger/debug(_:file:function:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/debug(_:file:function:)","url":"\/documentation\/dotpalmcore\/logger\/debug(_:file:function:)","navigatorTitle":[{"kind":"identifier","text":"debug:file:function:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"debug(_:file:function:)","role":"symbol","kind":"symbol"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/Logger/warning(_:file:function:)":{"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/warning(_:file:function:)","url":"\/documentation\/dotpalmcore\/logger\/warning(_:file:function:)","title":"warning(_:file:function:)","abstract":[],"navigatorTitle":[{"text":"warning:file:function:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Localization":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"title":"Localization","type":"topic","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization","kind":"symbol","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/localization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTPLogger","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"DOTPLogger","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"DOTPLogger","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/logLevel"]},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/debug(_:file:function:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/error(_:file:function:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/info(_:file:function:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/warning(_:file:function:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":[{"title":"Global components","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization"],"generated":true}],"op":"replace"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPLogger"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/title","value":"DOTPLogger"},{"value":[{"text":"DOTPLogger","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/fragments"},{"value":"info:file:function:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1info(_:file:function:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1info(_:file:function:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"info:file:function:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/title","value":"DotPalmLibrary"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments","value":[{"text":"DotPalmLibrary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1error(_:file:function:)\/title","value":"error:file:function:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"error:file:function:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1error(_:file:function:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1logLevel\/title","value":"logLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1logLevel\/fragments","value":[{"text":"logLevel","kind":"identifier"}]},{"value":"debug:file:function:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1debug(_:file:function:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"debug:file:function:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1debug(_:file:function:)\/fragments"},{"value":"warning:file:function:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1warning(_:file:function:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1warning(_:file:function:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"warning:file:function:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/title","op":"replace","value":"DOTPLocalization"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/fragments","value":[{"text":"DOTPLocalization","kind":"identifier"}],"op":"replace"}]}]}