{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error\/localizedDescription","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Error.localizedDescription","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/error\/localizeddescription"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"title":"localizedDescription","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:7DotCore0A3SdkC5ErrorO","symbolKind":"property","roleHeading":"Instance Property","extendedModule":"Swift","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":[{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"iOS","unavailable":false},{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"8.0","name":"Mac Catalyst","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"10.10","name":"macOS","unavailable":false},{"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"9.0","deprecated":false},{"beta":false,"unavailable":false,"name":"watchOS","introducedAt":"2.0","deprecated":false}],"modules":[{"name":"DotFaceLite","relatedModules":["Swift"]}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Error/localizedDescription":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error\/localizedDescription","abstract":[],"kind":"symbol","title":"localizedDescription","type":"topic","url":"\/documentation\/dotfacelite\/dotsdk\/error\/localizeddescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Error":{"abstract":[],"title":"DotSdk.Error","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotsdk\/error"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","title":"DotSdk","type":"topic","url":"\/documentation\/dotfacelite\/dotsdk","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"}]}]}