{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/configuration-swift.property","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"configuration","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController(py)configuration"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Current configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"title":"FaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","abstract":[{"text":"Configuration options for the UI Face Auto Capture component.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration":{"fragments":[{"text":"DOTFLFaceAutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","title":"DOTFLFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the UI Face Auto Capture component."}],"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/configuration-swift.property":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"kind":"symbol","title":"configuration","type":"topic","abstract":[{"type":"text","text":"Current configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/configuration-swift.property","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"configuration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFLFaceAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1configuration-swift.property\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1configuration-swift.property\/fragments","value":[{"text":"configuration","kind":"identifier"}]}]}]}