{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration"]]},"variants":[{"paths":["\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"role":"symbol","title":"init","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration(im)init","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"DotNfc"}]},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/DotFaceExpressionNeutralModuleConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration","title":"DotFaceExpressionNeutralModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face expression neutral module."}],"url":"\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceExpressionNeutralModuleConfiguration/init":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration\/init","title":"init","role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration\/init","type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceExpressionNeutralModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]}]}]}