{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/cameraPreviewScaleType","interfaceLanguage":"swift"},"metadata":{"title":"cameraPreviewScaleType","externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC22cameraPreviewScaleTypeAA06CamerajkL0Ovp","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Specify camera preview scale type. Default is "},{"code":".fit","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","text":"CameraPreviewScaleType"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/cameraPreviewScaleType":{"title":"cameraPreviewScaleType","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/cameraPreviewScaleType","role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/camerapreviewscaletype","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"}],"abstract":[{"text":"Specify camera preview scale type. Default is ","type":"text"},{"code":".fit","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.3.2"}],"title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraPreviewScaleType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"type":"topic","title":"CameraPreviewScaleType","url":"\/documentation\/dotfacelite\/camerapreviewscaletype","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType"}},"variantOverrides":[{"patch":[{"value":"DOTFLFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}