{"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"DotNfc"}],"title":"LocalizedError Implementations"},"variants":[{"paths":["\/documentation\/dotnfc\/nfckey\/error\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/failureReason","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/helpAnchor","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/recoverySuggestion"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/LocalizedError-Implementations","interfaceLanguage":"swift"},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey":{"navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","abstract":[{"type":"text","text":"NFC key created from document number, date of expiry and date of birth."}],"url":"\/documentation\/dotnfc\/nfckey","title":"NfcKey","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcKey","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error/helpAnchor":{"title":"helpAnchor","url":"\/documentation\/dotnfc\/nfckey\/error\/helpanchor","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/helpAnchor","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error/recoverySuggestion":{"title":"recoverySuggestion","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error\/recoverysuggestion","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/recoverySuggestion","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error":{"title":"NfcKey.Error","url":"\/documentation\/dotnfc\/nfckey\/error","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error/failureReason":{"title":"failureReason","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error\/failurereason","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/failureReason","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNNfcKey","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}]}]}