{"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:","kind":"identifier"}],"title":"init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)","platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"nameOfHolder"},{"text":": ","kind":"text"},{"text":"NameOfHolder","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"otherNames","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"personalNumber"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fullDateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"placeOfBirth"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"text":"address","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"telephone"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"profession"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"personalSummary"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"otherValidTravelDocumentNumbers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"text":"custodyInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(im)initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:","modules":[{"name":"DotNfc"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"nameOfHolder"},{"text":": ","kind":"text"},{"text":"NameOfHolder","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"otherNames"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"text":"personalNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fullDateOfBirth"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"placeOfBirth","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"address"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"text":"telephone","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"profession","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"personalSummary","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"otherValidTravelDocumentNumbers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"custodyInformation"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/init(nameofholder:othernames:personalnumber:fulldateofbirth:placeofbirth:address:telephone:profession:title:personalsummary:othervalidtraveldocumentnumbers:custodyinformation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/init(nameofholder:othernames:personalnumber:fulldateofbirth:placeofbirth:address:telephone:profession:title:personalsummary:othervalidtraveldocumentnumbers:custodyinformation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"title":"AdditionalPersonalDetails","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalPersonalDetails"}]},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)":{"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/init(nameofholder:othernames:personalnumber:fulldateofbirth:placeofbirth:address:telephone:profession:title:personalsummary:othervalidtraveldocumentnumbers:custodyinformation:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)","title":"init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"nameOfHolder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder","text":"NameOfHolder"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"otherNames"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"personalNumber"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fullDateOfBirth"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"placeOfBirth"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"text":"address","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"text":"telephone","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"profession"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"personalSummary","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"otherValidTravelDocumentNumbers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"text":"custodyInformation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","role":"symbol","type":"topic","kind":"symbol","title":"TravelDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NameOfHolder":{"url":"\/documentation\/dotnfc\/nameofholder","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NameOfHolder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NameOfHolder"}],"abstract":[{"type":"text","text":"Name of travel document holder."}],"title":"NameOfHolder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithNameOfHolder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTNNameOfHolder","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder"},{"kind":"text","text":" *) "},{"text":"nameOfHolder","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"otherNames:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"otherNames"},{"text":" ","kind":"text"},{"kind":"identifier","text":"personalNumber:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"personalNumber","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullDateOfBirth:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fullDateOfBirth"},{"text":" ","kind":"text"},{"text":"placeOfBirth:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeOfBirth","kind":"internalParam"},{"kind":"text","text":" "},{"text":"address:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"address"},{"text":" ","kind":"text"},{"kind":"identifier","text":"telephone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"telephone"},{"text":" ","kind":"text"},{"kind":"identifier","text":"profession:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"profession"},{"kind":"text","text":" "},{"kind":"identifier","text":"title:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"title"},{"text":" ","kind":"text"},{"text":"personalSummary:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"personalSummary","kind":"internalParam"},{"kind":"text","text":" "},{"text":"otherValidTravelDocumentNumbers:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"otherValidTravelDocumentNumbers"},{"text":" ","kind":"text"},{"text":"custodyInformation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"custodyInformation"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"DOTNAdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","op":"replace","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}]},{"value":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:","kind":"identifier"}]},{"value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","value":"DOTNNameOfHolder","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/title"},{"value":[{"kind":"identifier","text":"DOTNNameOfHolder"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/fragments"}]}]}