{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"nameOfHolder","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NameOfHolder","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/nameOfHolder"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/nameofholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/nameofholder"]}],"metadata":{"modules":[{"name":"DotNfc"}],"title":"nameOfHolder","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nameOfHolder"},{"kind":"text","text":": "},{"text":"NameOfHolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)nameOfHolder","platforms":[{"unavailable":false,"introducedAt":"13.0","beta":false,"deprecated":false,"name":"iOS"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nameOfHolder"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"abstract":[{"type":"text","text":"Full name of document holder."}],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","role":"symbol","type":"topic","kind":"symbol","title":"TravelDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"title":"AdditionalPersonalDetails","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalPersonalDetails"}]},"doc://DotNfc/documentation/DotNfc/NameOfHolder":{"url":"\/documentation\/dotnfc\/nameofholder","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NameOfHolder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NameOfHolder"}],"abstract":[{"type":"text","text":"Name of travel document holder."}],"title":"NameOfHolder"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/nameOfHolder":{"abstract":[{"type":"text","text":"Full name of document holder."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/nameOfHolder","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"nameOfHolder","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder","text":"NameOfHolder"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nameOfHolder"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/nameofholder","title":"nameOfHolder"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"nameOfHolder"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"nameOfHolder","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","text":"DOTNNameOfHolder","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder"},{"kind":"text","text":" * "},{"text":"nameOfHolder","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","op":"replace","value":"DOTNAdditionalPersonalDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}]},{"value":"DOTNNameOfHolder","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/fragments","value":[{"kind":"identifier","text":"DOTNNameOfHolder"}]},{"value":"nameOfHolder","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1nameOfHolder\/title"},{"op":"replace","value":[{"text":"nameOfHolder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1nameOfHolder\/fragments"}]}]}