{"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"threshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooLowValidator(im)initWithThreshold:error:","title":"init(threshold:)","symbolKind":"init","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"role":"symbol","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"threshold"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init(threshold:)"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.4.1","type":"text"}],"url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"role":"symbol","title":"FaceAutoCaptureController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooLowValidator":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","abstract":[{"text":"Validate minimum brightness of the detected face.","type":"text"}],"role":"symbol","title":"BrightnessTooLowValidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooLowValidator/init(threshold:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"threshold"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"kind":"symbol","title":"init(threshold:)","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init(threshold:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init(threshold:)","navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithThreshold:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithThreshold:error:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"threshold","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init(threshold:)\/title","value":"initWithThreshold:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init(threshold:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}