{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)Libraries","navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"title":"Libraries","modules":[{"name":"DotDocument"}],"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"symbolKind":"class"},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/libraries"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/libraries"]}],"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/init(document:face:faceLite:nfc:palm:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/document","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/face","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/faceLite","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/nfc","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/palm"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"languages":["swift"]}]}],"abstract":[{"text":"Container for library configurations.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries"},"references":{"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","url":"\/documentation\/dotdocument\/libraries","role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"title":"Libraries","type":"topic","abstract":[{"type":"text","text":"Container for library configurations."}]},"doc://DotDocument/documentation/DotDocument/Libraries/face":{"abstract":[{"text":"Face library configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/face","title":"face","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/libraries\/face","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"face","kind":"identifier"}]},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/Libraries/faceLite":{"title":"faceLite","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Face Lite library configuration."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/faceLite","navigatorTitle":[{"text":"faceLite","kind":"identifier"}],"url":"\/documentation\/dotdocument\/libraries\/facelite"},"doc://DotDocument/documentation/DotDocument/Libraries/init(document:face:faceLite:nfc:palm:)":{"role":"symbol","url":"\/documentation\/dotdocument\/libraries\/init(document:face:facelite:nfc:palm:)","navigatorTitle":[{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/init(document:face:faceLite:nfc:palm:)","type":"topic","abstract":[],"title":"init(document:face:faceLite:nfc:palm:)"},"doc://DotDocument/documentation/DotDocument/Libraries/nfc":{"url":"\/documentation\/dotdocument\/libraries\/nfc","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/nfc","role":"symbol","navigatorTitle":[{"text":"nfc","kind":"identifier"}],"abstract":[{"text":"NFC library configuration.","type":"text"}],"type":"topic","title":"nfc"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/Libraries/document":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/document","type":"topic","navigatorTitle":[{"text":"document","kind":"identifier"}],"title":"document","abstract":[{"text":"Document library configuration.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/libraries\/document"},"doc://DotDocument/documentation/DotDocument/Libraries/palm":{"url":"\/documentation\/dotdocument\/libraries\/palm","type":"topic","navigatorTitle":[{"text":"palm","kind":"identifier"}],"title":"palm","kind":"symbol","abstract":[{"text":"Palm library configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/palm","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"Libraries"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/document","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/face","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/faceLite","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/nfc","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/palm"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/init(document:face:faceLite:nfc:palm:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title","op":"replace","value":"Libraries"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"Libraries"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1face\/title","op":"replace","value":"face"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1face\/fragments","op":"replace","value":[{"kind":"identifier","text":"face"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1faceLite\/title","op":"replace","value":"faceLite"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1faceLite\/fragments","op":"replace","value":[{"text":"faceLite","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1init(document:face:faceLite:nfc:palm:)\/title","op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1init(document:face:faceLite:nfc:palm:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1nfc\/title","op":"replace","value":"nfc"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1nfc\/fragments","op":"replace","value":[{"kind":"identifier","text":"nfc"}]},{"value":"document","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1document\/title"},{"value":[{"text":"document","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1document\/fragments"},{"value":"palm","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1palm\/title"},{"value":[{"kind":"identifier","text":"palm"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1palm\/fragments"}]}]}