{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/init(faceImage:)"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/faceImage","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/hash"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/isEqual(_:)"],"title":"Instance Methods"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"title":"Structured content","generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTNEncodedIdentificationFeaturesFace) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"variants":[{"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/encodedidentificationfeaturesface"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"metadata":{"symbolKind":"class","platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"13.0"}],"title":"EncodedIdentificationFeaturesFace","externalID":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/isEqual(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/isEqual(_:)","abstract":[],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/isequal(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","title":"isEqual(_:)"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/faceImage":{"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/faceimage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/faceImage","title":"faceImage","abstract":[{"type":"text","text":"Face image of document holder."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceImage"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceImage"},{"kind":"text","text":": "},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"kind":"text","text":"?"}]},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/description":{"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/description","title":"description","abstract":[],"type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"title":"AdditionalPersonalDetails"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails","type":"topic","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalDetails"}],"kind":"symbol","title":"OptionalDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/init(faceImage:)":{"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/init(faceimage:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/init(faceImage:)","title":"init(faceImage:)","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFaceImage:"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"text":"?)","kind":"text"}]},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MachineReadableZoneInformation","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","url":"\/documentation\/dotnfc\/machinereadablezoneinformation","title":"MachineReadableZoneInformation"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"type":"topic","kind":"symbol","abstract":[{"text":"Contents of DG2 - Face image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"title":"EncodedIdentificationFeaturesFace"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"type":"topic","abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","title":"DisplayedSignatureOrUsualMark"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace/hash":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[],"title":"hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface\/hash"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"title":"AdditionalDocumentDetails","url":"\/documentation\/dotnfc\/additionaldocumentdetails","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdditionalDocumentDetails"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"kind":"symbol","type":"topic","title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTNEncodedIdentificationFeaturesFace","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/faceImage","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/hash"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/init(faceImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace\/isEqual(_:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Structured content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"]}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1faceImage\/title","value":"faceImage"},{"value":[{"kind":"identifier","text":"faceImage"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1faceImage\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"value":"DOTNAdditionalPersonalDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNOptionalDetails"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1init(faceImage:)\/title","value":"initWithFaceImage:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFaceImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1init(faceImage:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","op":"replace","value":"DOTNMachineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTNEncodedIdentificationFeaturesFace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","op":"replace","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","op":"replace","value":"DOTNAdditionalDocumentDetails"},{"op":"replace","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}