{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat"},"metadata":{"externalID":"c:@M@DotNfc@E@DOTNImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"ImageFormat","role":"symbol","platforms":[{"name":"iOS","beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Supported image formats.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg2000"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/description"]},{"generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"]}],"variants":[{"paths":["\/documentation\/dotnfc\/imageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imageformat"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNImageFormat) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://DotNfc/SY":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY","title":"Swift.RawRepresentable"},"doc://DotNfc/documentation/DotNfc/ImageFormat/jpeg":{"navigatorTitle":[{"text":"DOTNImageFormatJpeg","kind":"identifier"}],"title":"ImageFormat.jpeg","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"JPEG"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg","url":"\/documentation\/dotnfc\/imageformat\/jpeg","role":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageFormat/jpeg2000":{"url":"\/documentation\/dotnfc\/imageformat\/jpeg2000","type":"topic","role":"symbol","abstract":[{"type":"text","text":"JPEG2000"}],"title":"ImageFormat.jpeg2000","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg2000"}],"navigatorTitle":[{"text":"DOTNImageFormatJpeg2000","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg2000"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/ImageFormat/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotnfc\/imageformat\/init(rawvalue:)","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/ImageFormat/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/description","kind":"symbol","title":"description","url":"\/documentation\/dotnfc\/imageformat\/description","role":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"type":"text","text":"Supported image formats."}],"kind":"symbol","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"title":"ImageFormat","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","role":"symbol","url":"\/documentation\/dotnfc\/imageformat"},"doc://DotNfc/documentation/DotNfc/ImageFormat/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/dotnfc\/imageformat\/rawrepresentable-implementations","type":"topic","abstract":[],"kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/RawRepresentable-Implementations"},"doc://DotNfc/documentation/DotNfc/ImageFormat/Equatable-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","url":"\/documentation\/dotnfc\/imageformat\/equatable-implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"DOTNImageFormat","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTNImageFormat","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNImageFormat"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg2000"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNImageFormat","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg\/title","value":"DOTNImageFormatJpeg"},{"value":[{"text":"DOTNImageFormatJpeg","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg2000\/title","op":"replace","value":"DOTNImageFormatJpeg2000"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg2000\/fragments","value":[{"kind":"identifier","text":"DOTNImageFormatJpeg2000"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","value":"DOTNImageFormat","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","value":[{"kind":"identifier","text":"DOTNImageFormat"}],"op":"replace"}]}]}