{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword\/description"],"title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword"]}],"abstract":[{"text":"Password for accessing the chip.","type":"text"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"DotNfc"}],"title":"TravelDocumentReaderPassword","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","symbolKind":"protocol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNTravelDocumentReaderPassword) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPassword","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"text":"Overview","anchor":"overview","type":"heading"},{"inlineContent":[{"type":"text","text":"There are two types of passwords:"},{"text":" ","type":"text"},{"isActive":true,"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","type":"reference"},{"text":" - password from Machine Readable Zone.","type":"text"},{"type":"text","text":" "},{"type":"reference","isActive":true,"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"},{"type":"text","text":" - Card Access Number."}],"type":"paragraph"}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/traveldocumentreaderpassword"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocumentreaderpassword"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"abstract":[{"text":"Password for accessing the chip.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"type":"topic","title":"TravelDocumentReaderPassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","role":"symbol","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","type":"topic","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"kind":"symbol","title":"MachineReadableZonePassword","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZonePassword"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword\/description","role":"symbol","kind":"symbol","abstract":[],"required":true,"type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocumentreaderpassword\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"description"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"role":"symbol","kind":"symbol","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CardAccessNumberPassword"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword","title":"CardAccessNumberPassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CardAccessNumberPassword","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"DOTNTravelDocumentReaderPassword","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}]},{"value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword\/description"],"title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"DOTNTravelDocumentReaderPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments","value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace","value":"DOTNMachineReadableZonePassword"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments"},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword~1description\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","op":"replace","value":"DOTNCardAccessNumberPassword"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","op":"replace"}]}]}