{"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/detection"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running"]]},"abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection","text":"PalmAutoCaptureDetection","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"text":"?","kind":"text"}],"title":"detection","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC7RunningC9detectionAA0bdE9DetectionCSgvp"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/detection"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running","title":"PalmAutoCaptureUiState.Running","abstract":[{"type":"text","text":"Running state."}],"navigatorTitle":[{"kind":"identifier","text":"Running"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running/detection":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/detection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureDetection","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/detection","abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","title":"detection","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"navigatorTitle":[{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","title":"PalmAutoCaptureUiState","role":"symbol","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"title":"PalmAutoCaptureDetection","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTPPalmAutoCaptureUiState","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle"},{"op":"replace","value":"DOTPPalmAutoCaptureDetection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle"}]}]}