{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview","text":"PalmAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview"},{"text":", ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","text":"PalmAutoCapturePhase","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC","text":"Wrapped","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped"},{"text":"?, ","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection","text":"PalmAutoCaptureDetection","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","text":"PalmAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/init(preview:phase:detection:result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC7RunningC7preview5phase9detection6resultAeA0bdE7PreviewC_AA0bdE5PhaseO7WrappedCSgAA0bdE9DetectionCSgAA0bdE6ResultCSgtcfc","title":"init(preview:phase:detection:result:)","modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCapturePreview","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"},{"kind":"text","text":", "},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","text":"PalmAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC","text":"Wrapped"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureDetection","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureResult","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","symbolKind":"init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running"]]},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"title":"PalmAutoCaptureResult","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"title":"PalmAutoCaptureUiState","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","type":"topic","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running/init(preview:phase:detection:result:)":{"title":"init(preview:phase:detection:result:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCapturePreview","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"},{"kind":"text","text":", "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCapturePhase","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureDetection","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureResult","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/init(preview:phase:detection:result:)","type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturepreview","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCapturePreview","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"type":"topic","title":"PalmAutoCapturePreview"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"navigatorTitle":[{"text":"Running","kind":"identifier"}],"title":"PalmAutoCaptureUiState.Running","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running","abstract":[{"text":"Running state.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"title":"PalmAutoCapturePhase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Phase of the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturephase","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"title":"PalmAutoCaptureDetection","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","url":"\/documentation\/dotpalmcore\/palmautocapturedetection","type":"topic","abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped":{"title":"PalmAutoCapturePhase.Wrapped","kind":"symbol","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title","op":"replace","value":"DOTPPalmAutoCaptureResult"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","op":"replace","value":"DOTPPalmAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title","op":"replace","value":"DOTPPalmAutoCapturePreview"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","op":"replace","value":"DOTPPalmAutoCapturePhase"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCapturePhase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title","op":"replace","value":"DOTPPalmAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}