{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","text":"PalmAutoCapturePhase","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC","text":"Wrapped","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/phase"]}],"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"phase","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCapturePhase","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase"},{"kind":"text","text":"."},{"text":"Wrapped","preciseIdentifier":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC7RunningC5phaseAA0bdE5PhaseO7WrappedCSgvp"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/phase"},"abstract":[{"text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"navigatorTitle":[{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","title":"PalmAutoCaptureUiState","role":"symbol","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturephase","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","role":"symbol","abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"title":"PalmAutoCapturePhase"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"role":"symbol","title":"PalmAutoCapturePhase.Wrapped","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running/phase":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/phase","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/phase","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC"},{"text":"?","kind":"text"}],"abstract":[{"text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"type":"codeVoice","code":"null"},{"text":".","type":"text"}],"role":"symbol","title":"phase","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running","title":"PalmAutoCaptureUiState.Running","abstract":[{"type":"text","text":"Running state."}],"navigatorTitle":[{"kind":"identifier","text":"Running"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","op":"replace","value":"DOTPPalmAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","op":"replace","value":"DOTPPalmAutoCapturePhase"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]}]}]}