{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/preview"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC7RunningC7previewAA0bdE7PreviewCvp","modules":[{"name":"DotPalmCore"}],"role":"symbol","title":"preview","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview","text":"PalmAutoCapturePreview","kind":"typeIdentifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/preview"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running"]]},"abstract":[{"text":"Preview information.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running/preview":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/preview","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"}],"title":"preview","abstract":[{"text":"Preview information.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/preview","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"url":"\/documentation\/dotpalmcore\/palmautocapturepreview","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","title":"PalmAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCapturePreview","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running":{"role":"symbol","title":"PalmAutoCaptureUiState.Running","navigatorTitle":[{"text":"Running","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Running state.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","title":"PalmAutoCaptureUiState","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTPPalmAutoCapturePreview","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title"},{"value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments"},{"value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle"},{"value":"DOTPPalmAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle"}]}]}