{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/maxMaskPresenceScore:error:"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"maxMaskPresenceScore:error:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maxMaskPresenceScore:error:"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","symbolKind":"method","title":"maxMaskPresenceScore:error:","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder(im)maxMaskPresenceScore:error:"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"maxMaskPresenceScore:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","text":"DOTWrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":" *) ","kind":"text"},{"text":"maxMaskPresenceScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/maxmaskpresencescore:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","url":"\/documentation\/dotfacecore\/wrappeddouble","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder/maxMaskPresenceScore:error:":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/maxMaskPresenceScore:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maxMaskPresenceScore:error:"}],"title":"maxMaskPresenceScore:error:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxMaskPresenceScore:error:"}],"abstract":[],"url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/maxmaskpresencescore:error:","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","type":"topic","abstract":[],"kind":"symbol","role":"symbol","title":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","fragments":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle"}]}]}