{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"custodyInformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"abstract":[{"type":"text","text":"Custody information."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/custodyInformation"},"metadata":{"title":"custodyInformation","role":"symbol","roleHeading":"Instance Property","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"13.0"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)custodyInformation","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"custodyInformation"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"custodyInformation","kind":"identifier"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/custodyinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/custodyinformation"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"type":"topic","title":"TravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","title":"AdditionalPersonalDetails","url":"\/documentation\/dotnfc\/additionalpersonaldetails","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/custodyInformation":{"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/custodyinformation","title":"custodyInformation","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/custodyInformation","type":"topic","kind":"symbol","abstract":[{"text":"Custody information.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"custodyInformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"custodyInformation"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"custodyInformation"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"custodyInformation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"custodyInformation","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTNAdditionalPersonalDetails","op":"replace"},{"value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1custodyInformation\/title","value":"custodyInformation","op":"replace"},{"value":[{"text":"custodyInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1custodyInformation\/fragments"}]}]}