{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Other valid travel document numbers.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"otherValidTravelDocumentNumbers","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)otherValidTravelDocumentNumbers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherValidTravelDocumentNumbers","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"modules":[{"name":"DotNfc"}],"role":"symbol","title":"otherValidTravelDocumentNumbers","roleHeading":"Instance Property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/othervalidtraveldocumentnumbers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/othervalidtraveldocumentnumbers"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherValidTravelDocumentNumbers","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherValidTravelDocumentNumbers","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/otherValidTravelDocumentNumbers":{"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"otherValidTravelDocumentNumbers","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"otherValidTravelDocumentNumbers"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherValidTravelDocumentNumbers","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/othervalidtraveldocumentnumbers","abstract":[{"type":"text","text":"Other valid travel document numbers."}],"title":"otherValidTravelDocumentNumbers","role":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails","role":"symbol","abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"title":"AdditionalPersonalDetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalPersonalDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"otherValidTravelDocumentNumbers","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"otherValidTravelDocumentNumbers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"otherValidTravelDocumentNumbers"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"otherValidTravelDocumentNumbers","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherValidTravelDocumentNumbers\/title"},{"value":[{"text":"otherValidTravelDocumentNumbers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherValidTravelDocumentNumbers\/fragments"},{"value":"DOTNAdditionalPersonalDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments"},{"value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}