{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nfcTravelDocumentReader"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"nfcTravelDocumentReader","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"text":", ","kind":"text"},{"text":"failed","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","kind":"typeIdentifier","text":"NfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},{"kind":"text","text":"."},{"preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC5ErrorC","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"Tells the delegate that NFC reading has failed with an error.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:failed:)"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate(im)nfcTravelDocumentReader:failed:","symbolKind":"method","modules":[{"name":"DotNfc"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfcTravelDocumentReader"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","text":"NfcTravelDocumentReader","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"failed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC5ErrorC","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"role":"symbol","navigatorTitle":[{"text":"nfcTravelDocumentReader:failed:","kind":"identifier"}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false,"name":"iOS"}],"title":"nfcTravelDocumentReader(_:failed:)","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:failed:)"]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:failed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"kind":"symbol","title":"NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate/nfcTravelDocumentReader(_:failed:)":{"kind":"symbol","title":"nfcTravelDocumentReader(_:failed:)","navigatorTitle":[{"kind":"identifier","text":"nfcTravelDocumentReader:failed:"}],"type":"topic","required":true,"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:failed:)","abstract":[{"text":"Tells the delegate that NFC reading has failed with an error.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:failed:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nfcTravelDocumentReader"},{"text":"(","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"kind":"text","text":", "},{"text":"failed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC5ErrorC","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"type":"topic","kind":"symbol","title":"NfcTravelDocumentReader.Error","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}]},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderError":{"url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreadererror","abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderError","title":"DOTNNfcTravelDocumentReaderError","fragments":[{"text":"DOTNNfcTravelDocumentReaderError","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate":{"kind":"symbol","title":"NfcTravelDocumentReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the NFC reading events."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"nfcTravelDocumentReader:failed:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"nfcTravelDocumentReader:failed:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"nfcTravelDocumentReader:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTNNfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},{"text":" *) ","kind":"text"},{"text":"nfcTravelDocumentReader","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderError","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderError","text":"DOTNNfcTravelDocumentReaderError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"op":"replace","value":"nfcTravelDocumentReader:failed:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:failed:)\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:failed:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"nfcTravelDocumentReader:failed:","kind":"identifier"}]},{"value":"DOTNNfcTravelDocumentReaderDelegate","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/fragments","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReaderDelegate","kind":"identifier"}]}]}]}