{"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that NFC reading has been canceled by the system dialog cancel button on click event."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReaderCanceled(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"nfcTravelDocumentReader"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","text":"NfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate"]]},"metadata":{"role":"symbol","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate(im)nfcTravelDocumentReaderCanceled:","navigatorTitle":[{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled:"}],"roleHeading":"Instance Method","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"nfcTravelDocumentReaderCanceled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","text":"NfcTravelDocumentReader"},{"text":")","kind":"text"}],"title":"nfcTravelDocumentReaderCanceled(_:)","platforms":[{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0","name":"iOS"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreadercanceled(_:)"]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreadercanceled(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate","title":"NfcTravelDocumentReaderDelegate","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the NFC reading events."}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate/nfcTravelDocumentReaderCanceled(_:)":{"navigatorTitle":[{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled:"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreadercanceled(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"text":")","kind":"text"}],"role":"symbol","required":true,"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReaderCanceled(_:)","kind":"symbol","title":"nfcTravelDocumentReaderCanceled(_:)","abstract":[{"type":"text","text":"Tells the delegate that NFC reading has been canceled by the system dialog cancel button on click event."}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"type":"topic","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"nfcTravelDocumentReaderCanceled:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"nfcTravelDocumentReaderCanceled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTNNfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},{"text":" *) ","kind":"text"},{"text":"nfcTravelDocumentReader","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/title","value":"DOTNNfcTravelDocumentReaderDelegate"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReaderDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/fragments"},{"value":"nfcTravelDocumentReaderCanceled:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReaderCanceled(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReaderCanceled(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}