{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","interfaceLanguage":"swift"},"metadata":{"title":"eyeGazeLiveness","role":"symbol","symbolKind":"property","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC15eyeGazeLivenessAA0ac3Eyehi6ModuleE0CSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceEyeGazeLivenessModuleConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceEyeGazeLivenessModuleConfiguration","type":"topic","title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotfaceeyegazelivenessmoduleconfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class":{"title":"DotFaceLibraryConfiguration.Modules","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration":{"abstract":[{"type":"text","text":"Face library configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","type":"topic","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class/eyeGazeLiveness":{"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness","abstract":[],"type":"topic","kind":"symbol","title":"eyeGazeLiveness","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}]}]}