{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthleftcorner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthleftcorner"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"sections":[],"metadata":{"title":"FaceFeature.mouthLeftCorner","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureMouthLeftCorner","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthLeftCorner","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthLeftCorner"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouthLeftCorner","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLeftCorner","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthLeftCorner":{"title":"FaceFeature.mouthLeftCorner","role":"symbol","url":"\/documentation\/dotfacecore\/facefeature\/mouthleftcorner","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthLeftCorner","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLeftCorner","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthLeftCorner"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"url":"\/documentation\/dotfacecore\/facefeature","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","role":"symbol","type":"topic","title":"FaceFeature","abstract":[{"text":"Available face features.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.3.1"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFFaceFeatureMouthLeftCorner","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureMouthLeftCorner"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureMouthLeftCorner","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLeftCorner\/title","value":"DOTFFaceFeatureMouthLeftCorner"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLeftCorner\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureMouthLeftCorner"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","op":"replace","value":"DOTFFaceFeature"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}