{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowOuterEdge"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/righteyebrowouteredge"]},{"paths":["\/documentation\/dotfacecore\/facefeature\/righteyebrowouteredge"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"DOTFFaceFeatureRightEyebrowOuterEdge","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureRightEyebrowOuterEdge","title":"FaceFeature.rightEyebrowOuterEdge","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightEyebrowOuterEdge"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightEyebrowOuterEdge"}]}]}],"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyebrowOuterEdge":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowOuterEdge","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rightEyebrowOuterEdge","kind":"identifier"}],"kind":"symbol","title":"FaceFeature.rightEyebrowOuterEdge","role":"symbol","navigatorTitle":[{"text":"DOTFFaceFeatureRightEyebrowOuterEdge","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfacecore\/facefeature\/righteyebrowouteredge"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.3.1"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"navigatorTitle":[{"kind":"identifier","text":"FaceFeature"}],"url":"\/documentation\/dotfacecore\/facefeature","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","role":"symbol","type":"topic","title":"FaceFeature","abstract":[{"text":"Available face features.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFFaceFeatureRightEyebrowOuterEdge","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyebrowOuterEdge"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureRightEyebrowOuterEdge","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DOTFFaceFeatureRightEyebrowOuterEdge","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowOuterEdge\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowOuterEdge\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyebrowOuterEdge"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}