{"sections":[],"abstract":[{"type":"text","text":"If you set this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizationDictionary"},{"type":"text","text":" will be used to localize strings. Default value is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/localization\/uselocalizationdictionary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/localization\/uselocalizationdictionary"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/useLocalizationDictionary","interfaceLanguage":"swift"},"metadata":{"title":"useLocalizationDictionary","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLLocalization(cpy)useLocalizationDictionary","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}]},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/Localization/useLocalizationDictionary":{"kind":"symbol","url":"\/documentation\/dotfacelite\/localization\/uselocalizationdictionary","title":"useLocalizationDictionary","abstract":[{"text":"If you set this to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", ","type":"text"},{"type":"codeVoice","code":"localizationDictionary"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/useLocalizationDictionary"},"doc://DotFaceLite/documentation/DotFaceLite/Localization":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization","title":"Localization","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfacelite\/localization","kind":"symbol","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"useLocalizationDictionary","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"useLocalizationDictionary"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"useLocalizationDictionary","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1useLocalizationDictionary\/title"},{"op":"replace","value":[{"text":"useLocalizationDictionary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1useLocalizationDictionary\/fragments"},{"op":"replace","value":"DOTFLLocalization","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/title"},{"op":"replace","value":[{"text":"DOTFLLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLLocalization"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}