{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","text":"ImageSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/imagesize\/from(cgsize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/imagesize\/from(cgsize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/from(cgSize:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize"}],"title":"from(cgSize:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@DotNfc@objc(cs)DOTImageSize(cm)fromCgSize:","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"fromCgSize:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.4.2"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/from(cgSize:)":{"role":"symbol","title":"from(cgSize:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/from(cgSize:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromCgSize:"}],"url":"\/documentation\/dotnfc\/imagesize\/from(cgsize:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize":{"role":"symbol","title":"ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotnfc\/imagesize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"fromCgSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgSize:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","text":"DOTImageSize"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromCgSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cgSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1from(cgSize:)\/title","value":"fromCgSize:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1from(cgSize:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}