{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transformation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"transformation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:"},"metadata":{"title":"initWithDetection:transformation:","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:transformation:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:transformation:"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(im)initWithDetection:transformation:"},"references":{"doc://DotDocument/documentation/DotDocument/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","type":"topic","navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfigurationModules":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules","fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fingers library module configuration."}],"title":"DotFingersLibraryConfigurationModules"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfigurationModules/initWithDetection:transformation:":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:transformation:"}],"title":"initWithDetection:transformation:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:transformation:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersDetectionModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotdocument\/dotfingersdetectionmoduleconfiguration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/title","op":"replace","value":"DotFingersTransformationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/title","op":"replace","value":"DotFingersDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]}]}]}