{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules\/transformation"},"metadata":{"title":"transformation","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"transformation","kind":"identifier"}],"fragments":[{"text":"transformation","kind":"identifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)transformation"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"transformation"},{"kind":"text","text":";"}]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules\/transformation"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfigurationModules":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules","fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Fingers library module configuration."}],"title":"DotFingersLibraryConfigurationModules"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfigurationModules/transformation":{"type":"topic","title":"transformation","fragments":[{"kind":"identifier","text":"transformation"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules\/transformation","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules\/transformation","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","type":"topic","navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}