{"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/hash","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile(py)hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"roleHeading":"Instance Property","symbolKind":"property","title":"hash","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/ldsmasterfile\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/ldsmasterfile\/hash"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile"]]},"references":{"doc://DotNfc/documentation/DotNfc/LdsMasterFile/hash":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/hash","type":"topic","title":"hash","url":"\/documentation\/dotnfc\/ldsmasterfile\/hash","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","title":"LdsMasterFile","abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/ldsmasterfile","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LdsMasterFile"}],"navigatorTitle":[{"kind":"identifier","text":"LdsMasterFile"}],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","value":"DOTNLdsMasterFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLdsMasterFile"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments"},{"op":"replace","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/navigatorTitle"},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle"}]}]}