{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"extendedModule":"Swift","title":"hash(into:)","modules":[{"relatedModules":["Swift"],"name":"DotNfc"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]}},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotpalmmoduleid\/hash(into:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/hash(into:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/DotPalmModuleId":{"url":"\/documentation\/dotnfc\/dotpalmmoduleid","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotPalmModuleId","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId","title":"DotPalmModuleId","type":"topic","role":"symbol","abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module identifier.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/hash(into:)":{"url":"\/documentation\/dotnfc\/dotpalmmoduleid\/hash(into:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/hash(into:)","title":"hash(into:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]}},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"DotPalmModuleId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/title"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/fragments"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}