{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"sections":[],"metadata":{"roleHeading":"Initializer","externalID":"s:7DotCore0A12PalmModuleIdO8rawValueACSgSi_tcfc","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"init"},"variants":[{"paths":["\/documentation\/dotnfc\/dotpalmmoduleid\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/init(rawValue:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/DotPalmModuleId":{"type":"topic","abstract":[{"code":"DotPalm","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"title":"DotPalmModuleId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId","kind":"symbol","url":"\/documentation\/dotnfc\/dotpalmmoduleid"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/dotnfc\/dotpalmmoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/init(rawValue:)","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"patch":[{"value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/fragments","op":"replace"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}