{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/hashValue"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/hash(into:)"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotpalmmoduleid\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/hashValue":{"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"type":"topic","title":"hashValue","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotpalmmoduleid\/hashvalue","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/hashValue"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId","type":"topic","title":"DotPalmModuleId","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"url":"\/documentation\/dotnfc\/dotpalmmoduleid"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/hash(into:)":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/hash(into:)","abstract":[],"title":"hash(into:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"url":"\/documentation\/dotnfc\/dotpalmmoduleid\/hash(into:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/title","value":"DotPalmModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/navigatorTitle","value":[{"text":"DotPalmModuleId","kind":"identifier"}],"op":"replace"}]}]}