{"abstract":[{"text":"Image data.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/image\/bytes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/image\/bytes"]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"13.0"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNImage(py)bytes","role":"symbol","title":"bytes","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/bytes"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Image"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/Image":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","url":"\/documentation\/dotnfc\/image","kind":"symbol","navigatorTitle":[{"text":"Image","kind":"identifier"}],"title":"Image","abstract":[{"type":"text","text":"Raw image data representation."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Image/bytes":{"type":"topic","url":"\/documentation\/dotnfc\/image\/bytes","abstract":[{"text":"Image data.","type":"text"}],"title":"bytes","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/bytes","navigatorTitle":[{"kind":"identifier","text":"bytes"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"bytes","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bytes"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bytes"}]}],"kind":"declarations"},"op":"replace"},{"value":"DOTNImage","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTNImage"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1bytes\/title","op":"replace","value":"bytes"},{"value":[{"kind":"identifier","text":"bytes"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1bytes\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}