{"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/description","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/image\/description"]},{"paths":["\/documentation\/dotnfc\/image\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"description","roleHeading":"Instance Property","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNImage(py)description","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"13.0","deprecated":false}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Image"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/Image/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/description","role":"symbol","title":"description","kind":"symbol","url":"\/documentation\/dotnfc\/image\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc/Image":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotnfc\/image","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","title":"Image","abstract":[{"type":"text","text":"Raw image data representation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","op":"replace","value":"DOTNImage"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","value":[{"kind":"identifier","text":"DOTNImage"}],"op":"replace"}]}]}