{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/format"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/image\/format"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/image\/format"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","kind":"typeIdentifier","text":"ImageFormat","preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Image format."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Image"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","role":"symbol","platforms":[{"name":"iOS","introducedAt":"13.0","unavailable":false,"deprecated":false,"beta":false}],"title":"format","navigatorTitle":[{"text":"format","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNImage(py)format","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"text":"ImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat"}]},"references":{"doc://DotNfc/documentation/DotNfc/Image/format":{"abstract":[{"type":"text","text":"Image format."}],"type":"topic","navigatorTitle":[{"text":"format","kind":"identifier"}],"title":"format","url":"\/documentation\/dotnfc\/image\/format","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/format","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"format"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat","text":"ImageFormat","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/Image":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"kind":"symbol","abstract":[{"text":"Raw image data representation.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","title":"Image","url":"\/documentation\/dotnfc\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.15.1"}],"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","role":"collection"},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"url":"\/documentation\/dotnfc\/imageformat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","title":"ImageFormat","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"format","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"format","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTNImageFormat","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1format\/title","op":"replace","value":"format"},{"value":[{"text":"format","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1format\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","value":"DOTNImage","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNImage"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","value":"DOTNImageFormat"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","value":[{"text":"DOTNImageFormat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}