{"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"initWithBytes:format:size:","kind":"identifier"}],"symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytes"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(bytes:format:size:)","platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"13.0"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNImage(im)initWithBytes:format:size:","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytes"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat","kind":"typeIdentifier","text":"ImageFormat","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageFormat"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/image\/init(bytes:format:size:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/image\/init(bytes:format:size:)"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Image"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Image\/init(bytes:format:size:)","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Image/init(bytes:format:size:)":{"url":"\/documentation\/dotnfc\/image\/init(bytes:format:size:)","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Image\/init(bytes:format:size:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageFormat","preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"title":"init(bytes:format:size:)","role":"symbol","navigatorTitle":[{"text":"initWithBytes:format:size:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/imagesize","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"role":"symbol","title":"ImageSize"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Image":{"title":"Image","type":"topic","abstract":[{"type":"text","text":"Raw image data representation."}],"url":"\/documentation\/dotnfc\/image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Image","kind":"symbol","navigatorTitle":[{"text":"Image","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageFormat":{"url":"\/documentation\/dotnfc\/imageformat","type":"topic","title":"ImageFormat","abstract":[{"text":"Supported image formats.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageFormat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithBytes:format:size:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBytes:format:size:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"bytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"format:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageFormat","kind":"typeIdentifier","text":"DOTNImageFormat","preciseIdentifier":"c:@M@DotNfc@E@DOTNImageFormat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"format"},{"text":" ","kind":"text"},{"text":"size:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"DOTImageSize","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize"},{"text":" *) ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Image~1init(bytes:format:size:)\/title","value":"initWithBytes:format:size:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBytes:format:size:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Image~1init(bytes:format:size:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Image\/title","op":"replace","value":"DOTNImage"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Image\/fragments","value":[{"kind":"identifier","text":"DOTNImage"}],"op":"replace"},{"value":"DOTNImageFormat","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageFormat\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageFormat\/fragments","value":[{"kind":"identifier","text":"DOTNImageFormat"}],"op":"replace"}]}]}