{"metadata":{"roleHeading":"Class","title":"AuthenticationStatus","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"iOS"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationStatus","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}]},"abstract":[{"type":"text","text":"Authentication status of data and chip."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/init(data:chip:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/chip","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/data","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/hash"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/isEqual(_:)"],"title":"Instance Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTNAuthenticationStatus) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationStatus","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/authenticationstatus"]},{"paths":["\/documentation\/dotnfc\/authenticationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"],"title":"NFC protocols"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","type":"conformsTo"}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.9.0"}],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"title":"isEqual(_:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/isEqual(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","url":"\/documentation\/dotnfc\/authenticationstatus\/isequal(_:)"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"abstract":[{"text":"Authentication status of the data and protocol used for that purpose.","type":"text"}],"title":"DataAuthenticationStatus","url":"\/documentation\/dotnfc\/dataauthenticationstatus","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"title":"ChipAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"kind":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus","navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/authenticationstatus\/hash","title":"hash","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/hash","abstract":[],"kind":"symbol","type":"topic"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum","title":"ChipAuthenticationStatus.AuthenticationProtocol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"navigatorTitle":[{"text":"AuthenticationProtocol","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/authenticationstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationStatus"}],"navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","title":"AuthenticationStatus","role":"symbol"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"role":"symbol","abstract":[{"type":"text","text":"Access Control protocol."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","url":"\/documentation\/dotnfc\/accesscontrolprotocol","title":"AccessControlProtocol"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/init(data:chip:)":{"title":"init(data:chip:)","type":"topic","url":"\/documentation\/dotnfc\/authenticationstatus\/init(data:chip:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","text":"DataAuthenticationStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"chip"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","text":"ChipAuthenticationStatus","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/init(data:chip:)","navigatorTitle":[{"kind":"identifier","text":"initWithData:chip:"}]},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/chip":{"abstract":[{"type":"text","text":"Chip authentication status (using either PACE - Chip Authentication Mapping, Chip Authentication or Active Authentication protocol)."}],"title":"chip","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chip"},{"text":": ","kind":"text"},{"text":"ChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/authenticationstatus\/chip","navigatorTitle":[{"text":"chip","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/chip"},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/data":{"kind":"symbol","title":"data","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"data"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/data","type":"topic","abstract":[{"text":"Data authentication status (using Passing Authentication protocol).","type":"text"}],"url":"\/documentation\/dotnfc\/authenticationstatus\/data"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/description":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/authenticationstatus\/description","kind":"symbol","type":"topic","title":"description"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTNAuthenticationStatus","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/chip","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/data","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/hash"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/init(data:chip:)","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"],"title":"NFC protocols"}]},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTNAuthenticationStatus"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1isEqual(_:)\/title","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"value":"DOTNDataAuthenticationStatus","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title"},{"value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments"},{"value":"DOTNChipAuthenticationStatus","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title"},{"value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title","value":"DOTNAuthenticationStatus"},{"op":"replace","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","op":"replace","value":"DOTNAccessControlProtocol"},{"value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1init(data:chip:)\/title","value":"initWithData:chip:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1init(data:chip:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:chip:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1chip\/title","value":"chip"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1chip\/fragments","op":"replace","value":[{"kind":"identifier","text":"chip"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1data\/title","op":"replace","value":"data"},{"value":[{"kind":"identifier","text":"data"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1data\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1description\/title","value":"description","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1description\/fragments"}]}]}