{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class"]]},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","externalID":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC5ErrorO","title":"FaceAutoCaptureController.Configuration.Error","modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/invalidValidators(internalError:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/errorMessage","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/internalError"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/CustomStringConvertible-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/DotSdkError-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/Error-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/LocalizedError-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkError","doc:\/\/DotFaceLite\/10Foundation14LocalizedErrorP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/s5ErrorP","doc:\/\/DotFaceLite\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error/internalError":{"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error\/internalerror","abstract":[],"title":"internalError","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/internalError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","role":"symbol","kind":"symbol","title":"FaceAutoCaptureController.Configuration","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class"},"doc://DotFaceLite/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/10Foundation14LocalizedErrorP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error/LocalizedError-Implementations":{"title":"LocalizedError Implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/LocalizedError-Implementations","abstract":[],"kind":"article","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error\/localizederror-implementations","role":"collectionGroup","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","type":"topic","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController"},"doc://DotFaceLite/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/DotFaceLite\/s8SendableP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkError":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotSdkError"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotsdkerror","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkError"}],"role":"symbol","title":"DotSdkError","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkError"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 9.1.1","type":"text"}],"title":"DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/CustomStringConvertible-Implementations","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error\/customstringconvertible-implementations","kind":"article","type":"topic","title":"CustomStringConvertible Implementations","abstract":[],"role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error/Error-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"title":"Error Implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/Error-Implementations","kind":"article","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error\/error-implementations"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error/errorMessage":{"type":"topic","title":"errorMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error\/errormessage","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/errorMessage"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error/invalidValidators(internalError:)":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error\/invalidvalidators(internalerror:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidValidators"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/invalidValidators(internalError:)","abstract":[],"title":"FaceAutoCaptureController.Configuration.Error.invalidValidators(internalError:)","type":"topic","role":"symbol"},"doc://DotFaceLite/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/DotFaceLite\/s5ErrorP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error/DotSdkError-Implementations":{"role":"collectionGroup","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error\/dotsdkerror-implementations","type":"topic","title":"DotSdkError Implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error\/DotSdkError-Implementations","abstract":[],"kind":"article"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"FaceAutoCaptureController.Configuration.Error"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}