{"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceLite"}],"title":"init(type:)","role":"symbol","symbolKind":"init","roleHeading":"Initializer","externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC4typeAeA0D4TypeO_tcfc"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/init(type:)"},"variants":[{"paths":["\/documentation\/dotfacelite\/placeholder\/visible\/init(type:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType"},{"text":" = .circle)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/placeholder","title":"Placeholder","role":"symbol","abstract":[{"text":"Placeholder.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible","type":"topic","url":"\/documentation\/dotfacelite\/placeholder\/visible","navigatorTitle":[{"text":"Visible","kind":"identifier"}],"title":"Placeholder.Visible","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"abstract":[{"text":"Visible placeholder.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","abstract":[{"type":"text","text":"Type of placeholder."}],"title":"PlaceholderType","kind":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/placeholdertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible/init(type:)":{"title":"init(type:)","url":"\/documentation\/dotfacelite\/placeholder\/visible\/init(type:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/init(type:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title","op":"replace","value":"DOTPlaceholder"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle","op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/title","op":"replace","value":"DOTPlaceholderType"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/fragments","op":"replace","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/navigatorTitle","op":"replace","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}