{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"},"sections":[],"abstract":[{"text":"Default threshold.","type":"text"}],"metadata":{"symbolKind":"property","modules":[{"name":"DotPalmCore"}],"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmOutOfBoundsValidator(cpy)defaultMinCornerDistanceToImageShorterSideRatioThreshold","navigatorTitle":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"roleHeading":"Type Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold"]},{"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"type":"topic","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","title":"PalmOutOfBoundsValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","abstract":[{"type":"text","text":"version: 8.14.0"}],"kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/defaultMinCornerDistanceToImageShorterSideRatioThreshold":{"role":"symbol","type":"topic","abstract":[{"text":"Default threshold.","type":"text"}],"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","value":"DOTPPalmOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}]},{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"},{"value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/title","op":"replace"},{"value":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/fragments"}]}]}