{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/validate(palmAutoCaptureFrameParameters:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Frame parameters to validate.","type":"text"}]}],"name":"palmAutoCaptureFrameParameters"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" for out of bounds palm.","type":"text"}]}],"kind":"content"}],"metadata":{"symbolKind":"method","title":"validate(palmAutoCaptureFrameParameters:)","modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmOutOfBoundsValidator(im)validateWithPalmAutoCaptureFrameParameters:"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/validate(palmautocaptureframeparameters:)"]},{"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/validate(palmautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","type":"topic","role":"symbol","title":"PalmAutoCaptureFrameParameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"kind":"symbol","abstract":[{"type":"text","text":"Information from the detection process about the detected palm."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","title":"PalmOutOfBoundsValidator","role":"symbol","abstract":[{"text":"Validate if the detected palm is within the bounds of the image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/validate(palmAutoCaptureFrameParameters:)":{"abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/validate(palmAutoCaptureFrameParameters:)","navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/validate(palmautocaptureframeparameters:)","title":"validate(palmAutoCaptureFrameParameters:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"validateWithPalmAutoCaptureFrameParameters:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","text":"DOTPPalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Frame parameters to validate.","type":"text"}],"type":"paragraph"}],"name":"palmAutoCaptureFrameParameters"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" for out of bounds palm.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title","value":"DOTPPalmAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","value":"DOTPPalmOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/navigatorTitle","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1validate(palmAutoCaptureFrameParameters:)\/title","value":"validateWithPalmAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]}]}]}