{"variants":[{"paths":["\/documentation\/dotnfc\/dotnfclibrary\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary\/id"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/id"},"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DotNfcLibrary(py)id","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"}],"platforms":[{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"iOS","unavailable":false}],"modules":[{"name":"DotNfc"}],"role":"symbol","title":"id","navigatorTitle":[{"text":"id","kind":"identifier"}]},"abstract":[{"text":"The library identifier.","type":"text"}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","title":"DotLibraryId","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","url":"\/documentation\/dotnfc\/dotlibraryid"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary":{"role":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary","navigatorTitle":[{"kind":"identifier","text":"DotNfcLibrary"}],"title":"DotNfcLibrary","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotNfcLibrary"}],"kind":"symbol","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":" library initialization.","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/id":{"abstract":[{"text":"The library identifier.","type":"text"}],"url":"\/documentation\/dotnfc\/dotnfclibrary\/id","title":"id","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/id"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"id"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/title","value":"DotNfcLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotNfcLibrary"}]},{"value":"id","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1id\/title","op":"replace"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1id\/fragments","op":"replace"}]}]}