{"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC12cameraFacing0A6Camera0kJ0Ovp","modules":[{"name":"DotFaceCore"}],"platforms":[],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"role":"symbol","symbolKind":"property","title":"cameraFacing"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/cameraFacing","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}],"type":"paragraph"}],"abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"type":"codeVoice","code":".front"},{"text":".","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class/cameraFacing":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}],"role":"symbol","deprecated":true,"abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/cameraFacing","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/camerafacing","title":"cameraFacing","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"type":"topic","title":"CameraFacing","url":"\/documentation\/dotfacecore\/camerafacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}],"role":"symbol","type":"topic","deprecated":true,"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","title":"FaceSimpleCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"title":"FaceSimpleCaptureViewController","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","role":"symbol","deprecated":true,"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController","op":"replace"},{"value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}