{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/faceSizeRatioInterval","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/facesizeratiointerval"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceSizeRatioInterval","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"}],"roleHeading":"Instance Property","title":"faceSizeRatioInterval","modules":[{"name":"DotFaceCore"}],"platforms":[],"externalID":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC21faceSizeRatioInterval0aC00L6DoubleCvp","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval"},{"text":": ","kind":"text"},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble"}],"languages":["swift"]}]}],"abstract":[{"text":"Interval used for calculating minimal and maximal face size in image in range [0.0, 1.0]. Default is ","type":"text"},{"type":"codeVoice","code":"[0.1, 0.3]"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"url":"\/documentation\/dotfacecore\/intervaldouble","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","kind":"symbol","title":"IntervalDouble"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"title":"FaceSimpleCaptureViewController","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","role":"symbol","deprecated":true,"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class/faceSizeRatioInterval":{"deprecated":true,"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"faceSizeRatioInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Interval used for calculating minimal and maximal face size in image in range [0.0, 1.0]. Default is "},{"type":"codeVoice","code":"[0.1, 0.3]"},{"text":".","type":"text"}],"type":"topic","title":"faceSizeRatioInterval","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/facesizeratiointerval","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/faceSizeRatioInterval"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}],"role":"symbol","type":"topic","deprecated":true,"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","title":"FaceSimpleCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]}]}]}