{"metadata":{"externalID":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC5queryAA0B14DetectionQueryCvp","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"query","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","text":"FaceDetectionQuery"}],"title":"query","platforms":[],"symbolKind":"property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"query","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/query"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/query","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Query for additional evaluation of face simple capture result."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead."}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.10.0","type":"text"}],"url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class":{"abstract":[{"text":"Configuration options for the face simple capture process.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"deprecated":true,"title":"FaceSimpleCaptureViewController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class/query":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/query","kind":"symbol","abstract":[{"type":"text","text":"Query for additional evaluation of face simple capture result."}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"query","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"}],"title":"query","deprecated":true,"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/query"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"title":"FaceSimpleCaptureViewController","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"title":"FaceDetectionQuery","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"url":"\/documentation\/dotfacecore\/facedetectionquery","navigatorTitle":[{"kind":"identifier","text":"FaceDetectionQuery"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetectionQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"op":"replace"}]}]}