{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingerstransformationmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersTransformationModuleConfiguration":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerstransformationmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"title":"DotFingersTransformationModuleConfiguration","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersTransformationModuleConfiguration/init":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerstransformationmoduleconfiguration\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","abstract":[],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/title","op":"replace","value":"DotFingersTransformationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}