{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingerBundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundle","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"}]}],"kind":"declarations"},{"parameters":[{"name":"fingerBundle","content":[{"inlineContent":[{"type":"text","text":"Bundle of the finger image with detection data. Terminates if the image is not in "},{"code":".rawBgra","type":"codeVoice"},{"type":"text","text":" format."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The resulting fingerprint image.","type":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"This method should be called on the background thread."}],"type":"paragraph"},{"type":"aside","style":"note","name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"FingerToFingerprintTransformer"},{"type":"text","text":" fails to execute the transformation."}]}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundle:)"]}],"metadata":{"title":"transform(fingerBundle:)","roleHeading":"Instance Method","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerToFingerprintTransformer(im)transformWithFingerBundle:error:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingerBundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundle","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"transformWithFingerBundle:error:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Transform a single finger image into a fingerprint image."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundle:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/transform(fingerBundle:)":{"type":"topic","title":"transform(fingerBundle:)","navigatorTitle":[{"text":"transformWithFingerBundle:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundle:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingerBundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundle:)","abstract":[{"text":"Transform a single finger image into a fingerprint image.","type":"text"}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle":{"role":"symbol","title":"FingerBundle","navigatorTitle":[{"text":"FingerBundle","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerbundle","abstract":[{"type":"text","text":"Bundle of a finger image with detection data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerBundle"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfingerscore\/image","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","title":"FingerToFingerprintTransformer","navigatorTitle":[{"text":"FingerToFingerprintTransformer","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerToFingerprintTransformer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which transforms detected finger images into fingerprint images.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"transformWithFingerBundle:error:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformWithFingerBundle:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"typeIdentifier","text":"DOTImage"},{"kind":"text","text":" *) "},{"text":"transformWithFingerBundle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","text":"DOTFGFingerBundle"},{"kind":"text","text":" *) "},{"text":"fingerBundle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"fingerBundle","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bundle of the finger image with detection data. Terminates if the image is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}]}]},{"content":[{"inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"}},{"value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The resulting fingerprint image."},{"type":"text","text":" On failure, this method returns "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundle:)\/title","op":"replace","value":"transformWithFingerBundle:error:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformWithFingerBundle:error:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundle:)\/fragments","op":"replace"},{"value":"DOTFGFingerBundle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTFGFingerBundle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerBundle"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/title","value":"DOTFGFingerToFingerprintTransformer"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/fragments","value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/navigatorTitle","value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}