{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureController(py)configuration","roleHeading":"Instance Property","title":"configuration","modules":[{"name":"DotPalmCore"}]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"abstract":[{"type":"text","text":"Current configuration."}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/configuration-swift.property","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","title":"PalmAutoCaptureController.Configuration","type":"topic","abstract":[{"type":"text","text":"Configuration of the palm auto capture non-UI component."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration":{"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration","role":"symbol","title":"DOTPPalmAutoCaptureControllerConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration","kind":"symbol","abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureControllerConfiguration"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/configuration-swift.property":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.property","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Current configuration."}],"title":"configuration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/configuration-swift.property"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"configuration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"configuration","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration","text":"DOTPPalmAutoCaptureControllerConfiguration","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1configuration-swift.property\/title","op":"replace","value":"configuration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1configuration-swift.property\/fragments","op":"replace","value":[{"text":"configuration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]}]}]}