{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/!=(_:_:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/Equatable-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"extendedModule":"Swift","title":"!=(_:_:)","symbolKind":"op","roleHeading":"Operator","role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCore@E@DotFaceModuleId","modules":[{"relatedModules":["Swift"],"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/!=(_:_:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"title":"DotFaceModuleId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","url":"\/documentation\/dotfacecore\/dotfacemoduleid","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/!=(_:_:)":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/Equatable-Implementations":{"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/equatable-implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/Equatable-Implementations","title":"Equatable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}