{"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","title":"maxAngleThreshold","navigatorTitle":[{"kind":"identifier","text":"maxAngleThreshold"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLDevicePitchTooHighValidator(py)maxAngleThreshold","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"maxAngleThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/maxanglethreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/maxanglethreshold"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/maxAngleThreshold","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"maxAngleThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator"]]},"abstract":[{"type":"text","text":"Current max pitch angle in degrees."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.6.0"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DevicePitchTooHighValidator":{"abstract":[{"text":"Validate maximum pitch angle of the device.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator","title":"DevicePitchTooHighValidator","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DevicePitchTooHighValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DevicePitchTooHighValidator","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DevicePitchTooHighValidator/maxAngleThreshold":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DevicePitchTooHighValidator\/maxAngleThreshold","url":"\/documentation\/dotfacelite\/devicepitchtoohighvalidator\/maxanglethreshold","title":"maxAngleThreshold","navigatorTitle":[{"text":"maxAngleThreshold","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxAngleThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Current max pitch angle in degrees."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"maxAngleThreshold"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"maxAngleThreshold","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxAngleThreshold"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/title","value":"DOTFLDevicePitchTooHighValidator"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLDevicePitchTooHighValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1maxAngleThreshold\/title","op":"replace","value":"maxAngleThreshold"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DevicePitchTooHighValidator~1maxAngleThreshold\/fragments","op":"replace","value":[{"text":"maxAngleThreshold","kind":"identifier"}]}]}]}