{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/init(image:palm:content:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureresult\/init(image:palm:content:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureresult\/init(image:palm:content:)"]}],"metadata":{"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","text":"PalmDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(image:palm:content:)","navigatorTitle":[{"text":"initWithImage:palm:content:","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult(im)initWithImage:palm:content:","modules":[{"name":"DotPalmCore"}],"roleHeading":"Initializer"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"title":"PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI Palm Auto Capture component."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","title":"PalmAutoCaptureViewController","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"title":"PalmDetector.Palm","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Result of the palm detection process."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"title":"DOTPPalmDetectorPalm","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"abstract":[{"text":"Result of the palm detection process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"title":"PalmAutoCaptureResult","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureresult","type":"topic","abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","title":"Image","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotpalmcore\/image"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"title":"PalmDetector","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult/init(image:palm:content:)":{"type":"topic","navigatorTitle":[{"text":"initWithImage:palm:content:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","text":"PalmDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(image:palm:content:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/init(image:palm:content:)","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureresult\/init(image:palm:content:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImage:palm:content:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:palm:content:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm","text":"DOTPPalmDetectorPalm","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"},{"text":" *) ","kind":"text"},{"text":"palm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"DOTPPalmAutoCaptureResult","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title"},{"value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"},{"value":"initWithImage:palm:content:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1init(image:palm:content:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:palm:content:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1init(image:palm:content:)\/fragments"}]}]}