{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/palm","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureresult\/palm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureresult\/palm"]}],"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","title":"palm","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult(py)palm","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","text":"PalmDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"kind":"text","text":"?"}],"symbolKind":"property","modules":[{"name":"DotPalmCore"}],"role":"symbol","navigatorTitle":[{"text":"palm","kind":"identifier"}]},"abstract":[{"text":"The result of the palm detection. Might be ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" only if ","type":"text"},{"isActive":true,"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/requestCapture()","type":"reference"},{"text":" was used to get the result.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"kind":"text","text":": "},{"text":"PalmDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"},{"text":"?","kind":"text"}]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol","title":"PalmAutoCaptureController","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult/palm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/palm","url":"\/documentation\/dotpalmcore\/palmautocaptureresult\/palm","kind":"symbol","title":"palm","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","text":"PalmDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Palm","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The result of the palm detection. Might be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" only if "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/requestCapture()","isActive":true,"type":"reference"},{"type":"text","text":" was used to get the result."}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"palm"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"title":"DOTPPalmDetectorPalm","fragments":[{"kind":"identifier","text":"DOTPPalmDetectorPalm"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"role":"symbol","title":"PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"abstract":[{"text":"Result of the palm detection process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Palm"}],"role":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"title":"PalmDetector.Palm","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/requestCapture()":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/requestCapture()","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/requestcapture()","kind":"symbol","title":"requestCapture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Request capture of the next detection.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"requestCapture","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"title":"PalmAutoCaptureResult","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","kind":"symbol","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"title":"PalmDetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"palm","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"palm"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm","text":"DOTPPalmDetectorPalm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"palm","kind":"identifier"}]}]}},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1palm\/title","value":"palm","op":"replace"},{"value":[{"text":"palm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1palm\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1requestCapture()\/title","op":"replace","value":"requestCapture"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1requestCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestCapture"}],"op":"replace"},{"value":"DOTPPalmAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"}]}]}