{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/minEdgeDistanceToImageShorterSideRatioThreshold"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/minedgedistancetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/minedgedistancetoimageshortersideratiothreshold"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Current margin to image side ratio threshold."}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"minEdgeDistanceToImageShorterSideRatioThreshold","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceOutOfBoundsValidator(py)minEdgeDistanceToImageShorterSideRatioThreshold","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","title":"FaceOutOfBoundsValidator","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","type":"topic","abstract":[{"type":"text","text":"Validate if the detected face is within the specified bounds."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/minEdgeDistanceToImageShorterSideRatioThreshold":{"role":"symbol","type":"topic","title":"minEdgeDistanceToImageShorterSideRatioThreshold","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/minedgedistancetoimageshortersideratiothreshold","kind":"symbol","abstract":[{"type":"text","text":"Current margin to image side ratio threshold."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/minEdgeDistanceToImageShorterSideRatioThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEdgeDistanceToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"minEdgeDistanceToImageShorterSideRatioThreshold","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minEdgeDistanceToImageShorterSideRatioThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"minEdgeDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","value":"DOTFLFaceOutOfBoundsValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}]},{"value":"minEdgeDistanceToImageShorterSideRatioThreshold","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1minEdgeDistanceToImageShorterSideRatioThreshold\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1minEdgeDistanceToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"minEdgeDistanceToImageShorterSideRatioThreshold"}]}]}]}