{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/inRange","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/tooHigh","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/tooLow"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFValueRangeStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}],"title":"ValueRange.Status","roleHeading":"Enumeration","symbolKind":"enum","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"s:11DotFaceCore10ValueRangeC6StatusO","navigatorTitle":[{"text":"Status","kind":"identifier"}]},"abstract":[{"text":"Status of a value with respect to a range.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/valuerange\/status"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/Equatable-Implementations":{"abstract":[],"kind":"article","type":"topic","title":"Equatable Implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/Equatable-Implementations","url":"\/documentation\/dotfacecore\/valuerange\/status\/equatable-implementations","role":"collectionGroup"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/tooLow":{"title":"ValueRange.Status.tooLow","role":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/status\/toolow","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/tooLow","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tooLow","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/tooHigh":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tooHigh","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/valuerange\/status\/toohigh","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/tooHigh","abstract":[],"role":"symbol","title":"ValueRange.Status.tooHigh","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status":{"title":"ValueRange.Status","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/status","abstract":[{"type":"text","text":"Status of a value with respect to a range."}],"role":"symbol","navigatorTitle":[{"text":"Status","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"title":"ValueRange","abstract":[{"text":"Representation of ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" range, compatible with Objective-C.","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/valuerange","navigatorTitle":[{"text":"ValueRange","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValueRange","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/RawRepresentable-Implementations","url":"\/documentation\/dotfacecore\/valuerange\/status\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/valuerange\/status\/init(rawvalue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","role":"symbol"},"doc://DotFaceCore/SY":{"identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/inRange":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/inRange","url":"\/documentation\/dotfacecore\/valuerange\/status\/inrange","kind":"symbol","abstract":[],"title":"ValueRange.Status.inRange","role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"inRange","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"DOTFValueRange","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title","op":"replace"},{"value":[{"text":"DOTFValueRange","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments","op":"replace"},{"value":[{"text":"DOTFValueRange","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}