{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:transformation:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(im)initWithDetection:transformation:","title":"initWithDetection:transformation:","navigatorTitle":[{"text":"initWithDetection:transformation:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfigurationModules"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation:"},{"text":"(","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"transformation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfigurationmodules","abstract":[{"type":"text","text":"Fingers library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfigurationModules","title":"DotFingersLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersTransformationModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfingerstransformationmoduleconfiguration","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersTransformationModuleConfiguration","title":"DotFingersTransformationModuleConfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfigurationModules/initWithDetection:transformation:":{"url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:transformation:"}],"title":"initWithDetection:transformation:","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDetection:transformation:"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration","title":"DotFingersDetectionModuleConfiguration","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration"},{"op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}