{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfacepassivelivenessmoduleconfiguration\/init"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration(im)init","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFacePassiveLivenessModuleConfiguration":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFacePassiveLivenessModuleConfiguration","abstract":[{"text":"Face passive liveness module.","type":"text"}],"navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacepassivelivenessmoduleconfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFacePassiveLivenessModuleConfiguration/init":{"url":"\/documentation\/dotfingerscore\/dotfacepassivelivenessmoduleconfiguration\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration\/init","title":"init","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/title","op":"replace","value":"DotFacePassiveLivenessModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]}]}]}