{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DetectedFace"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureresult\/detectedface"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facesimplecaptureresult\/detectedface"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureResult\/detectedFace","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detected face."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"}],"title":"detectedFace","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureResult(py)detectedFace","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"detectedFace"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureResult"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureResult/detectedFace":{"role":"symbol","title":"detectedFace","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"}],"abstract":[{"type":"text","text":"Detected face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureResult\/detectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectedFace"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureresult\/detectedface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.5.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureResult":{"role":"symbol","title":"FaceSimpleCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the face simple capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureResult"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureresult"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectedFace":{"role":"symbol","title":"DetectedFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectedFace"}],"abstract":[{"type":"text","text":"Result of face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectedFace"}],"url":"\/documentation\/dotfacecore\/detectedface"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"detectedFace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectedFace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DOTFDetectedFace"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectedFace"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureResult~1detectedFace\/title","value":"detectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureResult~1detectedFace\/fragments","value":[{"kind":"identifier","text":"detectedFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/title","value":"DOTFFaceSimpleCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/title","value":"DOTFDetectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/fragments","value":[{"kind":"identifier","text":"DOTFDetectedFace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}