{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration"]]},"abstract":[{"text":"Module configuration.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/modules-swift.property"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration(py)modules","modules":[{"name":"DotPalmCore"}],"role":"symbol","title":"modules","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"modules","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class":{"role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersLibraryConfiguration.Modules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfigurationModules":{"kind":"symbol","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules","role":"symbol","title":"DotFingersLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/modules-swift.property":{"kind":"symbol","abstract":[{"text":"Module configuration.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.property","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/modules-swift.property","role":"symbol","title":"modules","navigatorTitle":[{"text":"modules","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"modules","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"modules","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules","text":"DotFingersLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration~1modules-swift.property\/title","op":"replace","value":"modules"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration~1modules-swift.property\/fragments","op":"replace","value":[{"text":"modules","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}