{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotFingersLibraryConfigurationModules) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)"],"anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","title":"DotFingersLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"title":"transformation","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","role":"symbol","abstract":[],"title":"init(detection:transformation:)","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?)","kind":"text"}]},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"title":"detection","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class\/detection","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfiguration/Modules-swift.class":{"role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfiguration\/modules-swift.class","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersLibraryConfiguration.Modules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfiguration\/Modules-swift.class","type":"topic"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration","op":"replace"},{"op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]}]}]}