{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/init()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"metadata":{"title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"init","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerCountTooLowValidator(im)init","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"roleHeading":"Initializer","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/init()","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator/init()":{"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/init()","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/init()"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"role":"symbol","title":"FingerCountTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"FingerCountTooLowValidator"}],"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerCountTooLowValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"init","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1init()\/fragments"},{"value":"DOTFGFingerCountTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}