{"abstract":[{"text":"Current minimal accepted count of detected fingers.","type":"text"}],"metadata":{"title":"minFingerCountThreshold","navigatorTitle":[{"kind":"identifier","text":"minFingerCountThreshold"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerCountTooLowValidator(py)minFingerCountThreshold","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFingerCountThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minFingerCountThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/minfingercountthreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/minfingercountthreshold"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/minFingerCountThreshold"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator/minFingerCountThreshold":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/minFingerCountThreshold","type":"topic","title":"minFingerCountThreshold","url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/minfingercountthreshold","abstract":[{"type":"text","text":"Current minimal accepted count of detected fingers."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFingerCountThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"minFingerCountThreshold"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"role":"symbol","title":"FingerCountTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"FingerCountTooLowValidator"}],"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerCountTooLowValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minFingerCountThreshold","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"minFingerCountThreshold"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFingerCountThreshold"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"minFingerCountThreshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1minFingerCountThreshold\/title"},{"op":"replace","value":[{"text":"minFingerCountThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1minFingerCountThreshold\/fragments"},{"op":"replace","value":"DOTFGFingerCountTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments"},{"value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle"}]}]}