{"abstract":[{"text":"Validate count of detected fingers.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"title":"validate(fingersAutoCaptureFrameParameters:)","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerCountTooLowValidator(im)validateWithFingersAutoCaptureFrameParameters:","symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingersAutoCaptureFrameParameters","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"fingersAutoCaptureFrameParameters","content":[{"inlineContent":[{"type":"text","text":"Frame parameters to validate."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" when the count of detected fingers is below the threshold.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/validate(fingersautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/validate(fingersautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/validate(fingersAutoCaptureFrameParameters:)"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator/validate(fingersAutoCaptureFrameParameters:)":{"abstract":[{"text":"Validate count of detected fingers.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator\/validate(fingersautocaptureframeparameters:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","kind":"typeIdentifier","text":"FingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"title":"validate(fingersAutoCaptureFrameParameters:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator\/validate(fingersAutoCaptureFrameParameters:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"role":"symbol","title":"FingerCountTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"FingerCountTooLowValidator"}],"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerCountTooLowValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"title":"FingersAutoCaptureFrameParameters","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information from the detection process about the detected fingers.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"validateWithFingersAutoCaptureFrameParameters:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","kind":"typeIdentifier","text":"DOTFGFingersAutoCaptureFrameParameters","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}],"name":"fingersAutoCaptureFrameParameters"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" when the count of detected fingers is below the threshold."}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"validateWithFingersAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1validate(fingersAutoCaptureFrameParameters:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments"},{"value":"DOTFGFingerCountTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle"},{"value":"DOTFGFingersAutoCaptureFrameParameters","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}