{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/isequal(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/isEqual(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"isEqual(_:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"s:11DotFaceCore0B18AutoCaptureUiStateC7RunningC7isEqualySbypSgF"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running":{"title":"FaceAutoCaptureUiState.Running","navigatorTitle":[{"kind":"identifier","text":"Running"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"abstract":[{"type":"text","text":"Running state."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"kind":"symbol","title":"FaceAutoCaptureUiState","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running/isEqual(_:)":{"title":"isEqual(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/isEqual(_:)","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/isequal(_:)","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title","value":"DOTFFaceAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]}]}]}