{"abstract":[{"type":"text","text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be "},{"type":"codeVoice","code":"null"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/phase"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC","text":"Wrapped"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceCore0B18AutoCaptureUiStateC7RunningC5phase0aB7Commons0bdE5PhaseO7WrappedCSgvp","title":"phase","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/phase"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate","title":"FaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running":{"abstract":[{"type":"text","text":"Running state."}],"navigatorTitle":[{"kind":"identifier","text":"Running"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running","title":"FaceAutoCaptureUiState.Running","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","title":"FaceAutoCapturePhase","url":"\/documentation\/dotfacecore\/faceautocapturephase","abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running/phase":{"abstract":[{"type":"text","text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be "},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/phase","title":"phase","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/phase","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/Wrapped":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturephase\/wrapped","title":"FaceAutoCapturePhase.Wrapped","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title","value":"DOTFFaceAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/title","value":"DOTFaceAutoCapturePhase","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}