{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult","text":"FaceAutoCaptureResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult"},{"kind":"text","text":"?"}],"externalID":"s:11DotFaceCore0B18AutoCaptureUiStateC7RunningC6resultAA0bdE6ResultCSgvp","title":"result","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/result","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running"]]},"abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"codeVoice","code":"null"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/result"]}],"kind":"symbol","sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","type":"topic","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCaptureUiState","url":"\/documentation\/dotfacecore\/faceautocaptureuistate","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"title":"FaceAutoCaptureResult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocaptureresult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running":{"title":"FaceAutoCaptureUiState.Running","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running","kind":"symbol","abstract":[{"text":"Running state.","type":"text"}],"navigatorTitle":[{"text":"Running","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running/result":{"type":"topic","title":"result","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/result","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/result","abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title","value":"DOTFFaceAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title","value":"DOTFFaceAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}]}]}]}