{"metadata":{"navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}],"title":"MultiRangeLivenessChallengeItem.one","role":"symbol","symbolKind":"case","roleHeading":"Case","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"one"}],"externalID":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem@DOTMultiRangeLivenessChallengeItemOne"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"one"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/one"]},{"paths":["\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/one"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/one","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/one":{"kind":"symbol","type":"topic","title":"MultiRangeLivenessChallengeItem.one","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"one","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/one","role":"symbol","navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/one"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem":{"navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"title":"MultiRangeLivenessChallengeItem","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTMultiRangeLivenessChallengeItemOne"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemOne"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1one\/title","value":"DOTMultiRangeLivenessChallengeItemOne"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1one\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItemOne","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/fragments","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]}]}]}