{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/three"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/three"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/three"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"three"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Case","role":"symbol","navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}],"title":"MultiRangeLivenessChallengeItem.three","symbolKind":"case","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem@DOTMultiRangeLivenessChallengeItemThree","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"three","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/three":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/three","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/three","role":"symbol","type":"topic","navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}],"title":"MultiRangeLivenessChallengeItem.three","abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"three","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"title":"MultiRangeLivenessChallengeItem","kind":"symbol","role":"symbol","abstract":[{"text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DOTMultiRangeLivenessChallengeItemThree","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"DOTMultiRangeLivenessChallengeItemThree","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1three\/title"},{"value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemThree"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1three\/fragments","op":"replace"},{"value":"DOTMultiRangeLivenessChallengeItem","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/title","op":"replace"},{"value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}