{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"expressionNeutral","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/expressionneutral"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral","interfaceLanguage":"swift"},"metadata":{"title":"expressionNeutral","roleHeading":"Instance Property","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC17expressionNeutralAA0ac10Expressionh6ModuleE0CSgvp","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?"}],"symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"abstract":[{"type":"text","text":"Face library configuration."}],"role":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class/expressionNeutral":{"title":"expressionNeutral","abstract":[],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"},{"text":": ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class\/expressionneutral"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","kind":"symbol","type":"topic","title":"DotFaceLibraryConfiguration.Modules"},"doc://DotDocument/documentation/DotDocument/DotFaceExpressionNeutralModuleConfiguration":{"abstract":[{"type":"text","text":"Face expression neutral module."}],"url":"\/documentation\/dotdocument\/dotfaceexpressionneutralmoduleconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceExpressionNeutralModuleConfiguration","kind":"symbol","type":"topic","title":"DotFaceExpressionNeutralModuleConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/title","op":"replace","value":"DotFaceExpressionNeutralModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]}]}]}