{"abstract":[{"type":"text","text":"Contains parsed MRZ of one specific travel document type."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/machineReadableZone","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/machinereadablezone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/machinereadablezone"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"machineReadableZone"}],"role":"symbol","title":"machineReadableZone","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"machineReadableZone"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZone"}],"modules":[{"name":"DotNfc"}],"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation(py)machineReadableZone"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.3.1","type":"text"}],"url":"\/documentation\/dotnfc","type":"topic","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","role":"symbol","abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MachineReadableZoneInformation","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezoneinformation","title":"MachineReadableZoneInformation","navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Result of NFC reading."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"title":"MachineReadableZone","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation/machineReadableZone":{"url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/machinereadablezone","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/machineReadableZone","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZone"}],"abstract":[{"text":"Contains parsed MRZ of one specific travel document type.","type":"text"}],"title":"machineReadableZone","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"machineReadableZone"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"machineReadableZone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"machineReadableZone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMachineReadableZone","text":"DOTMachineReadableZone"},{"text":" * ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"}]}],"kind":"declarations"}},{"value":"DOTNMachineReadableZoneInformation","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title"},{"op":"replace","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments"},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/title","value":"DOTMachineReadableZone"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/fragments"},{"value":"machineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1machineReadableZone\/title","op":"replace"},{"value":[{"text":"machineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1machineReadableZone\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}