{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration"]]},"abstract":[{"type":"text","text":"Libraries configuration."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Libraries","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration\/libraries","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"libraries","symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries","kind":"typeIdentifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"externalID":"s:7DotCore0A3SdkC13ConfigurationC9librariesAA9LibrariesCvp"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/configuration\/libraries"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"title":"DotSdk","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","type":"topic","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotsdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Configuration":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotsdk\/configuration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"DotSdk.Configuration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Configuration/libraries":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","text":"Libraries"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration\/libraries","title":"libraries","abstract":[{"type":"text","text":"Libraries configuration."}],"url":"\/documentation\/dotfacelite\/dotsdk\/configuration\/libraries"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Libraries":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries","role":"symbol","abstract":[{"type":"text","text":"Container for library configurations."}],"title":"Libraries","kind":"symbol","url":"\/documentation\/dotfacelite\/libraries"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title","op":"replace","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/navigatorTitle","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/title","op":"replace","value":"Libraries"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/fragments","op":"replace","value":[{"kind":"identifier","text":"Libraries"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/navigatorTitle","op":"replace","value":[{"text":"Libraries","kind":"identifier"}]}]}]}