{"abstract":[{"text":"Current maximal accepted size.","type":"text"}],"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooLargeValidator(py)maxDetectionSizeToImageShorterSideRatioThreshold","navigatorTitle":[{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"modules":[{"name":"DotFaceLite"}],"title":"maxDetectionSizeToImageShorterSideRatioThreshold","roleHeading":"Instance Property"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","title":"SizeTooLargeValidator","abstract":[{"type":"text","text":"Validate size of the detected face."}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/maxDetectionSizeToImageShorterSideRatioThreshold":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold","title":"maxDetectionSizeToImageShorterSideRatioThreshold","abstract":[{"text":"Current maximal accepted size.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","value":"DOTFLSizeTooLargeValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/title","value":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}