{"sections":[],"metadata":{"externalID":"s:7DotCore0A9LibraryIdO11descriptionSSvp","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","symbolKind":"property","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"variants":[{"paths":["\/documentation\/dotnfc\/dotlibraryid\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/description"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/description":{"title":"description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/dotnfc\/dotlibraryid\/description","role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/description"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","title":"DotLibraryId","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DotLibraryId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","op":"replace"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}