{"metadata":{"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFace","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFace"}],"symbolKind":"case","title":"DotLibraryId.face","roleHeading":"Case","modules":[{"name":"DotNfc"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" identifier."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotlibraryid\/face"]},{"paths":["\/documentation\/dotnfc\/dotlibraryid\/face"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/face"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","title":"DotLibraryId","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/face":{"navigatorTitle":[{"text":"DotLibraryIdFace","kind":"identifier"}],"title":"DotLibraryId.face","abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" identifier."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid\/face","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/face","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotLibraryIdFace","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdFace","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotLibraryIdFace"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/navigatorTitle","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1face\/title","value":"DotLibraryIdFace","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1face\/fragments","value":[{"text":"DotLibraryIdFace","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}