{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary"},{"text":"], ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil)","kind":"text"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)"},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"transactionCountingToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"symbolKind":"init","title":"init(licenseBytes:libraries:transactionCountingToken:)","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"]}],"references":{"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkConfiguration","kind":"identifier"}],"title":"DotSdkConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","role":"symbol","url":"\/documentation\/dotdocument\/dotsdkconfiguration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/init(licenseBytes:libraries:transactionCountingToken:)":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)","abstract":[],"title":"init(licenseBytes:libraries:transactionCountingToken:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"], ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"type":"topic","url":"\/documentation\/dotdocument\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"},"doc://DotDocument/documentation/DotDocument/DotLibrary":{"url":"\/documentation\/dotdocument\/dotlibrary","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary","role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","title":"DotDocument","kind":"symbol","abstract":[{"text":"version: 8.15.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithLicenseBytes:libraries:transactionCountingToken:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithLicenseBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"licenseBytes"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries:"},{"text":"(","kind":"text"},{"text":"NSArray<id<DotLibrary>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"libraries"},{"kind":"text","text":" "},{"text":"transactionCountingToken:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"transactionCountingToken"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/title","value":"DotSdkConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/fragments","value":[{"text":"DotSdkConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/title","value":"initWithLicenseBytes:libraries:transactionCountingToken:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/fragments"}]}]}