{"variants":[{"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"libraries","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"libraries","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(py)libraries"},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/libraries","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","text":"DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"List of "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" libraries to use."}],"references":{"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/libraries":{"title":"libraries","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"kind":"text","text":"]"}],"url":"\/documentation\/dotdocument\/dotsdkconfiguration\/libraries","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/libraries","abstract":[{"type":"text","text":"List of "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" libraries to use."}],"navigatorTitle":[{"kind":"identifier","text":"libraries"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotsdkconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","title":"DotSdkConfiguration","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotLibrary":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","abstract":[],"role":"symbol","title":"DotLibrary","url":"\/documentation\/dotdocument\/dotlibrary","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibrary"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"libraries","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"libraries"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<DotLibrary>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"libraries","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1libraries\/title","op":"replace"},{"value":[{"text":"libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1libraries\/fragments","op":"replace"},{"value":"DotSdkConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotSdkConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/navigatorTitle","op":"replace"},{"value":"DotLibrary","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/navigatorTitle","op":"replace"}]}]}