{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DotSdkLicenseProxy(py)isFaceLiteEnabled","symbolKind":"property","title":"isFaceLiteEnabled","role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceliteenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceliteenabled"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceLiteEnabled","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"DotSdkLicenseProxyProtocol.isFaceLiteEnabled"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFaceLiteEnabled":{"abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceliteenabled","kind":"symbol","title":"isFaceLiteEnabled","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceLiteEnabled","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"version: 8.3.0","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy":{"navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy","title":"DotSdkLicenseProxy","abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxy","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"isFaceLiteEnabled","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"isFaceLiteEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title"},{"value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}