{"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isFaceMatchingEnabled","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfacematchingenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfacematchingenabled"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceMatchingEnabled"},"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DotSdkLicenseProxy(py)isFaceMatchingEnabled","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","title":"isFaceMatchingEnabled","navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFaceMatchingEnabled":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceMatchingEnabled","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfacematchingenabled","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"title":"isFaceMatchingEnabled","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy":{"title":"DotSdkLicenseProxy","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"isFaceMatchingEnabled","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isFaceMatchingEnabled"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"isFaceMatchingEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/fragments","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/fragments"}]}]}