{"variants":[{"paths":["\/documentation\/dotdocument\/mrzstringposition\/startindex"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzstringposition\/startindex"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/startIndex"},"abstract":[{"type":"text","text":"An index of the first character in the MRZ line."}],"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition(py)startIndex","modules":[{"name":"DotDocument"}],"title":"startIndex","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"startIndex","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"startIndex"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","title":"MrzStringPosition","url":"\/documentation\/dotdocument\/mrzstringposition","kind":"symbol","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition/startIndex":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"startIndex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","kind":"symbol","title":"startIndex","url":"\/documentation\/dotdocument\/mrzstringposition\/startindex","navigatorTitle":[{"kind":"identifier","text":"startIndex"}],"abstract":[{"type":"text","text":"An index of the first character in the MRZ line."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition\/startIndex"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"startIndex","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"startIndex","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"startIndex","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition","op":"replace"},{"value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments","op":"replace"},{"op":"replace","value":"startIndex","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1startIndex\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition~1startIndex\/fragments","op":"replace","value":[{"kind":"identifier","text":"startIndex"}]}]}]}