{"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"DotSdkError Implementations"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error"]]},"sections":[],"kind":"article","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/errorDescription"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/composeWithInternalError()"],"title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/intervaldouble\/error\/dotsdkerror-implementations"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error":{"abstract":[],"url":"\/documentation\/dotfingerscore\/intervaldouble\/error","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"IntervalDouble.Error","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error/composeWithInternalError()":{"url":"\/documentation\/dotfingerscore\/intervaldouble\/error\/composewithinternalerror()","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"composeWithInternalError()","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/composeWithInternalError()"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error/errorDescription":{"url":"\/documentation\/dotfingerscore\/intervaldouble\/error\/errordescription","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"errorDescription","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/errorDescription"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfingerscore\/intervaldouble","kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error/description":{"url":"\/documentation\/dotfingerscore\/intervaldouble\/error\/description","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/description"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}