{"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error"]]},"sections":[],"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/!=(_:_:)"],"title":"Operators","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/intervaldouble\/error\/equatable-implementations"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error/!=(_:_:)":{"title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/intervaldouble\/error\/!=(_:_:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/!=(_:_:)"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error":{"abstract":[],"url":"\/documentation\/dotfingerscore\/intervaldouble\/error","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"IntervalDouble.Error","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfingerscore\/intervaldouble","kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}]}]}