{"seeAlsoSections":[{"title":"Style and configuration","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureStyle"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"title":"DocumentAutoCaptureConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureConfiguration","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}]},"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class"]},{"title":"Structures","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Defaults"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/brightnessHighThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/brightnessLowThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraFacing","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraPreset","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraPreviewScaleType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/confidenceLowThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/confidenceThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/hotspotsScoreHighThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/isDetectionLayerVisible","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/isMrzReadingEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/qualityAttributeThresholds-swift.property","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/sharpnessLowThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/sizeSmallThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/validationMode"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Error"]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDocumentAutoCaptureConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureStyle":{"role":"symbol","title":"DocumentAutoCaptureStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureStyle"}],"abstract":[{"type":"text","text":"Customization options for the document auto capture user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureStyle"}],"url":"\/documentation\/dotdocument\/documentautocapturestyle"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:)":{"role":"symbol","title":"init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreviewScaleType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(qualityattributethresholds:validationmode:ismrzreadingenabled:isdetectionlayervisible:camerafacing:camerapreviewscaletype:)"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/sizeSmallThreshold":{"deprecated":true,"role":"symbol","title":"sizeSmallThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeSmallThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Minimal accepted size ratio between the shortest edge of the detected document and the image side, in range [0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/sizeSmallThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sizeSmallThreshold"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/sizesmallthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/confidenceThreshold":{"deprecated":true,"role":"symbol","title":"confidenceThreshold","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Document detection confidence threshold in range [0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/confidenceThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confidenceThreshold"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/confidencethreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/cameraPreset":{"deprecated":true,"role":"symbol","title":"cameraPreset","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreset","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreset"}],"abstract":[{"type":"text","text":"Specify camera preset. Default is "},{"type":"codeVoice","code":".fullHD"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraPreset"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/camerapreset"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/Error":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/error"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/confidenceLowThreshold":{"deprecated":true,"role":"symbol","title":"confidenceLowThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Minimal accepted document detection confidence threshold in range [0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/confidenceLowThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confidenceLowThreshold"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/confidencelowthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/brightnessHighThreshold":{"deprecated":true,"role":"symbol","title":"brightnessHighThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Maximal accepted brightness threshold in range [0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/brightnessHighThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"brightnessHighThreshold"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/brightnesshighthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/validationMode":{"role":"symbol","title":"validationMode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTValidationMode"}],"abstract":[{"type":"text","text":"Specify validation mode."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/validationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validationMode"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/validationmode"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/qualityAttributeThresholds-swift.property":{"role":"symbol","title":"qualityAttributeThresholds","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC"}],"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/qualityAttributeThresholds-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityAttributeThresholds"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.property"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/isMrzReadingEnabled":{"role":"symbol","title":"isMrzReadingEnabled","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this flag to enable MRZ reading during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/isMrzReadingEnabled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isMrzReadingEnabled"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/ismrzreadingenabled"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/isDetectionLayerVisible":{"role":"symbol","title":"isDetectionLayerVisible","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this flag to show or hide detection rectangle during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/isDetectionLayerVisible","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDetectionLayerVisible"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/isdetectionlayervisible"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/cameraFacing":{"role":"symbol","title":"cameraFacing","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraFacing"}],"abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".back"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraFacing"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/camerafacing"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Create the document auto capture configuration with default values."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/init()"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/cameraPreviewScaleType":{"role":"symbol","title":"cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Specify camera preview scale type. Default is "},{"type":"codeVoice","code":".fit"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cameraPreviewScaleType"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/camerapreviewscaletype"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/Defaults":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/defaults"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/hotspotsScoreHighThreshold":{"deprecated":true,"role":"symbol","title":"hotspotsScoreHighThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hotspotsScoreHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Maximal accepted hotspots score threshold in range [0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/hotspotsScoreHighThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hotspotsScoreHighThreshold"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/hotspotsscorehighthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/sharpnessLowThreshold":{"deprecated":true,"role":"symbol","title":"sharpnessLowThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Minimal accepted sharpness threshold in range [0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/sharpnessLowThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharpnessLowThreshold"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/sharpnesslowthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)":{"deprecated":true,"role":"symbol","title":"init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confidenceLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeSmallThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sharpnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightnessHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"hotspotsScoreHighThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreset"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreset","preciseIdentifier":"c:@M@DotDocument@E@DOTDCameraPreset"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(confidencelowthreshold:sizesmallthreshold:sharpnesslowthreshold:brightnesslowthreshold:brightnesshighthreshold:hotspotsscorehighthreshold:validationmode:ismrzreadingenabled:isdetectionlayervisible:camerafacing:camerapreviewscaletype:ca-o11l"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/brightnessLowThreshold":{"deprecated":true,"role":"symbol","title":"brightnessLowThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessLowThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Minimal accepted brightness threshold in range [0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/brightnessLowThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"brightnessLowThreshold"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/brightnesslowthreshold"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/brightnessHighThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/brightnessLowThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraFacing","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraPreset","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/cameraPreviewScaleType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/confidenceLowThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/confidenceThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/hotspotsScoreHighThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/isDetectionLayerVisible","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/isMrzReadingEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/qualityAttributeThresholds-swift.property","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/sharpnessLowThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/sizeSmallThreshold","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/validationMode"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Style and configuration","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureStyle"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDocumentAutoCaptureConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureStyle\/title","value":"DOTDocumentAutoCaptureStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureStyle\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:)\/title","value":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1sizeSmallThreshold\/title","value":"sizeSmallThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1sizeSmallThreshold\/fragments","value":[{"kind":"identifier","text":"sizeSmallThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1confidenceThreshold\/title","value":"confidenceThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1confidenceThreshold\/fragments","value":[{"kind":"identifier","text":"confidenceThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1cameraPreset\/title","value":"cameraPreset"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1cameraPreset\/fragments","value":[{"kind":"identifier","text":"cameraPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1confidenceLowThreshold\/title","value":"confidenceLowThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1confidenceLowThreshold\/fragments","value":[{"kind":"identifier","text":"confidenceLowThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1brightnessHighThreshold\/title","value":"brightnessHighThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1brightnessHighThreshold\/fragments","value":[{"kind":"identifier","text":"brightnessHighThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1validationMode\/title","value":"validationMode"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1validationMode\/fragments","value":[{"kind":"identifier","text":"validationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1qualityAttributeThresholds-swift.property\/title","value":"qualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1qualityAttributeThresholds-swift.property\/fragments","value":[{"kind":"identifier","text":"qualityAttributeThresholds"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1isMrzReadingEnabled\/title","value":"isMrzReadingEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1isMrzReadingEnabled\/fragments","value":[{"kind":"identifier","text":"isMrzReadingEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1isDetectionLayerVisible\/title","value":"isDetectionLayerVisible"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1isDetectionLayerVisible\/fragments","value":[{"kind":"identifier","text":"isDetectionLayerVisible"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1cameraFacing\/title","value":"cameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1cameraFacing\/fragments","value":[{"kind":"identifier","text":"cameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1cameraPreviewScaleType\/title","value":"cameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1cameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"cameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1hotspotsScoreHighThreshold\/title","value":"hotspotsScoreHighThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1hotspotsScoreHighThreshold\/fragments","value":[{"kind":"identifier","text":"hotspotsScoreHighThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1sharpnessLowThreshold\/title","value":"sharpnessLowThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1sharpnessLowThreshold\/fragments","value":[{"kind":"identifier","text":"sharpnessLowThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)\/title","value":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(confidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfidenceLowThreshold:sizeSmallThreshold:sharpnessLowThreshold:brightnessLowThreshold:brightnessHighThreshold:hotspotsScoreHighThreshold:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:cameraFacing:cameraPreviewScaleType:cameraPreset:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1brightnessLowThreshold\/title","value":"brightnessLowThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1brightnessLowThreshold\/fragments","value":[{"kind":"identifier","text":"brightnessLowThreshold"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}