{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/rebased(parentRectangle:)"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"role":"symbol","title":"rebased(parentRectangle:)","roleHeading":"Instance Method","extendedModule":"DotCore","modules":[{"name":"DotPalmCore","relatedModules":["DotCore"]}],"externalID":"c:@CM@DotCore@objc(cs)DOTCorners(im)rebasedWithParentRectangle:","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/corners\/rebased(parentrectangle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/corners\/rebased(parentrectangle:)"]}],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/Corners":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"kind":"symbol","title":"Corners","type":"topic","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","kind":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"role":"symbol","type":"topic","title":"RectangleDouble"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/rebased(parentRectangle:)":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/rebased(parentRectangle:)","title":"rebased(parentRectangle:)","kind":"symbol","url":"\/documentation\/dotpalmcore\/corners\/rebased(parentrectangle:)","role":"symbol","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rebasedWithParentRectangle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTCorners","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"},{"text":" *) ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"text":"parentRectangle","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}]},{"value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/navigatorTitle","op":"replace"},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","op":"replace"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","op":"replace"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle","op":"replace"},{"value":"rebasedWithParentRectangle:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1rebased(parentRectangle:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1rebased(parentRectangle:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}