{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)Face(py)passiveLiveness","navigatorTitle":[{"kind":"identifier","text":"passiveLiveness"}],"title":"passiveLiveness","fragments":[{"kind":"identifier","text":"passiveLiveness"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/passiveLiveness","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Passive liveness. This is evaluated only if it is specified in "},{"type":"text","text":"FaceDetectionQuery"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","text":"DOTFFaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":" * "},{"kind":"identifier","text":"passiveLiveness"},{"kind":"text","text":";"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/face\/passiveliveness"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute","role":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"title":"FaceAttribute","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"url":"\/documentation\/dotfacecore\/face","kind":"symbol","type":"topic","fragments":[{"text":"Face","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","role":"symbol","title":"Face","abstract":[{"type":"text","text":"Detected face in the image."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Face/passiveLiveness":{"abstract":[{"type":"text","text":"Passive liveness. This is evaluated only if it is specified in "},{"type":"text","text":"FaceDetectionQuery"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/dotfacecore\/face\/passiveliveness","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/passiveLiveness","fragments":[{"text":"passiveLiveness","kind":"identifier"}],"role":"symbol","title":"passiveLiveness"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","op":"replace","value":"DOTFFaceAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}