{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Face quality attributes. Only attributes specified in ","type":"text"},{"text":"FaceDetectionQuery","type":"text"},{"text":" are evaluated.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFFaceQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"},{"text":" * ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/quality","interfaceLanguage":"occ"},"metadata":{"title":"quality","role":"symbol","fragments":[{"text":"quality","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","navigatorTitle":[{"text":"quality","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)Face(py)quality"},"variants":[{"paths":["\/documentation\/dotfacecore\/face\/quality"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","title":"FaceQuality","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"url":"\/documentation\/dotfacecore\/face","kind":"symbol","type":"topic","fragments":[{"text":"Face","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","role":"symbol","title":"Face","abstract":[{"type":"text","text":"Detected face in the image."}]},"doc://DotFaceCore/documentation/DotFaceCore/Face/quality":{"abstract":[{"text":"Face quality attributes. Only attributes specified in ","type":"text"},{"text":"FaceDetectionQuery","type":"text"},{"text":" are evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/face\/quality","type":"topic","role":"symbol","fragments":[{"text":"quality","kind":"identifier"}],"kind":"symbol","title":"quality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/quality"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"text":"DOTFFaceQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}