{"metadata":{"navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(im)initWithMin:max:error:","modules":[{"name":"DotPalmCore"}],"symbolKind":"init","title":"init(min:max:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/intervalfloat\/init(min:max:)"]},{"paths":["\/documentation\/dotpalmcore\/intervalfloat\/init(min:max:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/init(min:max:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"max","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/init(min:max:)":{"url":"\/documentation\/dotpalmcore\/intervalfloat\/init(min:max:)","navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:error:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/init(min:max:)","type":"topic","title":"init(min:max:)","kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat":{"title":"IntervalFloat","url":"\/documentation\/dotpalmcore\/intervalfloat","role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMin:max:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMin:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"min"},{"kind":"text","text":" "},{"kind":"identifier","text":"max:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"max"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat~1init(min:max:)\/title","value":"initWithMin:max:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat~1init(min:max:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/title","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}