{"metadata":{"title":"max","symbolKind":"property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(py)max","navigatorTitle":[{"text":"max","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/intervalfloat\/max"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/intervalfloat\/max"]}],"abstract":[{"type":"text","text":"Maximal interval value."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/max"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat":{"title":"IntervalFloat","url":"\/documentation\/dotpalmcore\/intervalfloat","role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/max":{"title":"max","url":"\/documentation\/dotpalmcore\/intervalfloat\/max","role":"symbol","abstract":[{"text":"Maximal interval value.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/max","navigatorTitle":[{"kind":"identifier","text":"max"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"max"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"max"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat~1max\/title","op":"replace","value":"max"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat~1max\/fragments","op":"replace","value":[{"kind":"identifier","text":"max"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}