{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/sizeInterval(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/sizeinterval(_:)"]}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sizeInterval","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"title":"sizeInterval(_:)","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC12sizeIntervalyAI0aC00N6DoubleCSgKF","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeInterval"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"sizeInterval","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder/sizeInterval(_:)":{"title":"sizeInterval(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/sizeInterval(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/sizeinterval(_:)","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"title":"PalmAutoCaptureViewController.Configuration","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder":{"navigatorTitle":[{"kind":"identifier","text":"Builder"}],"title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds.Builder","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Builder"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"title":"PalmAutoCaptureViewController","kind":"symbol","abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.7.0","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","title":"IntervalDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotpalmcore\/intervaldouble","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds","type":"topic","abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments"}]}]}