{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator"]]},"abstract":[{"text":"Validate presence of barcode on the detected document.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}],"name":"documentAutoCaptureFrameParameters"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" for missing barcode."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcodenotpresentvalidator\/validate(documentautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/barcodenotpresentvalidator\/validate(documentautocaptureframeparameters:)"]}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeNotPresentValidator(im)validateWithDocumentAutoCaptureFrameParameters:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"validate(documentAutoCaptureFrameParameters:)","roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)"},"references":{"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator/validate(documentAutoCaptureFrameParameters:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)","abstract":[{"text":"Validate presence of barcode on the detected document.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/barcodenotpresentvalidator\/validate(documentautocaptureframeparameters:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"type":"topic","title":"validate(documentAutoCaptureFrameParameters:)"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BarcodeNotPresentValidator"}],"url":"\/documentation\/dotdocument\/barcodenotpresentvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeNotPresentValidator"}],"title":"BarcodeNotPresentValidator","kind":"symbol","abstract":[{"type":"text","text":"Validate if barcode is present."}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"symbol","title":"DocumentAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"},{"kind":"text","text":"("},{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":";"}]}]}},{"value":{"parameters":[{"content":[{"inlineContent":[{"text":"Frame parameters to validate.","type":"text"}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" for missing barcode.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/title","value":"DOTDBarcodeNotPresentValidator"},{"value":[{"kind":"identifier","text":"DOTDBarcodeNotPresentValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/fragments","op":"replace"},{"value":[{"text":"DOTDBarcodeNotPresentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}]}]}]}