{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Hidden placeholder."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPlaceholderHidden) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hidden"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Class","modules":[{"name":"DotFaceCore"}],"title":"Placeholder.Hidden","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hidden"}],"role":"symbol","externalID":"s:14DotFaceCommons11PlaceholderC6HiddenC","symbolKind":"class","navigatorTitle":[{"text":"Hidden","kind":"identifier"}]},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/hash"],"generated":true},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/placeholder\/hidden"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Hidden/hash":{"type":"topic","abstract":[],"title":"hash","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/hash","url":"\/documentation\/dotfacecore\/placeholder\/hidden\/hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Hidden/description":{"title":"description","abstract":[],"url":"\/documentation\/dotfacecore\/placeholder\/hidden\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/description","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"title":"Placeholder","url":"\/documentation\/dotfacecore\/placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Hidden":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden","url":"\/documentation\/dotfacecore\/placeholder\/hidden","abstract":[{"text":"Hidden placeholder.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Hidden"}],"role":"symbol","title":"Placeholder.Hidden","navigatorTitle":[{"kind":"identifier","text":"Hidden"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Hidden/isEqual(_:)":{"title":"isEqual(_:)","abstract":[],"url":"\/documentation\/dotfacecore\/placeholder\/hidden\/isequal(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden\/isEqual(_:)","kind":"symbol","type":"topic"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTPlaceholder","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace"}]}]}