{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","title":"compositeCheckDigit","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)compositeCheckDigit"},"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/compositecheckdigit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/compositecheckdigit"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/compositeCheckDigit","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"references":{"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/compositeCheckDigit":{"title":"compositeCheckDigit","role":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone\/compositecheckdigit","navigatorTitle":[{"kind":"identifier","text":"compositeCheckDigit"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"compositeCheckDigit","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/compositeCheckDigit","kind":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone","title":"Td2MachineReadableZone","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}]},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"type":"topic","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"title":"MrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.7.1"}],"title":"DotNfc","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"compositeCheckDigit","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"compositeCheckDigit","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"DOTMrzCheckDigit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"compositeCheckDigit"}]}]}},{"op":"replace","value":"compositeCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1compositeCheckDigit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"compositeCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1compositeCheckDigit\/fragments"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","op":"replace"},{"op":"replace","value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]}]}]}