{"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfBirth"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"dateOfBirth","symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)dateOfBirth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateOfBirth","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","title":"MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/dateOfBirth":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone\/dateofbirth","role":"symbol","abstract":[],"title":"dateOfBirth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfBirth"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dateOfBirth","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dateOfBirth","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit"},{"text":" * ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"DOTMrzDateElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/navigatorTitle","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfBirth\/title","value":"dateOfBirth"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfBirth\/fragments","value":[{"text":"dateOfBirth","kind":"identifier"}]},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}