{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfExpiry","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"}]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/dateofexpiry"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/dateofexpiry"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"dateOfExpiry","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)dateOfExpiry","title":"dateOfExpiry","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/dateOfExpiry":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/dateOfExpiry","url":"\/documentation\/dotnfc\/td2machinereadablezone\/dateofexpiry","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfExpiry"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"}],"navigatorTitle":[{"text":"dateOfExpiry","kind":"identifier"}],"type":"topic","abstract":[],"title":"dateOfExpiry","kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"kind":"symbol","role":"symbol","title":"Td2MachineReadableZone","url":"\/documentation\/dotnfc\/td2machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"text":" with parsed ","type":"text"},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"title":"MrzDateElementWithCheckDigit","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dateOfExpiry","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"dateOfExpiry"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"DOTMrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"dateOfExpiry","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfExpiry\/title","value":"dateOfExpiry","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1dateOfExpiry\/fragments","op":"replace","value":[{"kind":"identifier","text":"dateOfExpiry"}]},{"op":"replace","value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","op":"replace"}]}]}