{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)"]},{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"documentCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentNumber"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"optionalData","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"optionalData","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":"?, ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(im)initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"url":"\/documentation\/dotnfc\/mrzcheckdigit","role":"symbol","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"kind":"symbol","title":"MrzCheckDigit","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}],"abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.15.0"}],"url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)":{"role":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentCode"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","kind":"typeIdentifier","text":"MrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionalData"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"compositeCheckDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier","text":"MrzCheckDigit"},{"text":")","kind":"text"}],"title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}],"abstract":[]},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"type":"topic","kind":"symbol","role":"symbol","title":"MrzElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzElement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","url":"\/documentation\/dotnfc\/mrzelement","type":"topic","title":"MrzElement","role":"symbol","kind":"symbol","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"url":"\/documentation\/dotnfc\/td2machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"Td2MachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Td2MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"title":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit"},"doc://DotNfc/documentation/DotNfc/MrzNameElement":{"navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrznameelement","abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"MrzNameElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzNameElement","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithDocumentCode:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","text":"DOTMrzElement"},{"text":" *) ","kind":"text"},{"text":"documentCode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"},{"kind":"text","text":" *) "},{"text":"issuingStateOrOrganization","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"name:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"DOTMrzNameElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"kind":"text","text":" "},{"text":"documentNumber:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentNumber"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"DOTMrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nationality"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfBirth:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"text":"dateOfBirth","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","text":"DOTMrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":" *) ","kind":"text"},{"text":"sex","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dateOfExpiry:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":" *) "},{"text":"dateOfExpiry","kind":"internalParam"},{"kind":"text","text":" "},{"text":"optionalData:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"optionalData","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compositeCheckDigit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"DOTMrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"compositeCheckDigit"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"DOTMrzCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}]},{"value":"DOTMrzElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"op":"replace","value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"value":"DOTMrzDateElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/title","value":"DOTMrzNameElement","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"op":"replace"}]}]}