{"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/issuingstateororganization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/issuingstateororganization"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"title":"issuingStateOrOrganization","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTTd2MachineReadableZone(py)issuingStateOrOrganization","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","text":"MrzElement"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone\/issuingStateOrOrganization","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td2MachineReadableZone":{"navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone","kind":"symbol","title":"Td2MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td2MachineReadableZone/issuingStateOrOrganization":{"url":"\/documentation\/dotnfc\/td2machinereadablezone\/issuingstateororganization","kind":"symbol","navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td2MachineReadableZone\/issuingStateOrOrganization","title":"issuingStateOrOrganization","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"issuingStateOrOrganization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"}],"role":"symbol","type":"topic","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"kind":"symbol","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/mrzelement","type":"topic","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"issuingStateOrOrganization"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"DOTMrzElement"},{"text":" * ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTTd2MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments"},{"value":"issuingStateOrOrganization","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone~1issuingStateOrOrganization\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td2MachineReadableZone~1issuingStateOrOrganization\/fragments","value":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"op":"replace"},{"value":"DOTMrzElement","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}