{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/sex"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/sex"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/sex"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"sex"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)sex","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"role":"symbol","title":"sex"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/sex":{"title":"sex","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/sex","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/td2machinereadablezone\/sex","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sex"}]},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"kind":"symbol","title":"Td2MachineReadableZone","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"type":"topic","url":"\/documentation\/dotnfc\/td2machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"title":"MrzElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","url":"\/documentation\/dotnfc\/mrzelement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sex","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"sex","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"DOTMrzElement","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"sex","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1sex\/title","op":"replace"},{"value":[{"kind":"identifier","text":"sex"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1sex\/fragments","op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","op":"replace"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/navigatorTitle","op":"replace"},{"value":"DOTMrzElement","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","op":"replace"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzElement"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}