{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"extendedModule":"Swift","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"roleHeading":"Instance Property","modules":[{"relatedModules":["Swift"],"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","title":"localizedDescription","platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"iPadOS","deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"macOS","deprecated":false,"introducedAt":"10.10"},{"unavailable":false,"beta":false,"name":"tvOS","deprecated":false,"introducedAt":"9.0"},{"unavailable":false,"beta":false,"name":"watchOS","deprecated":false,"introducedAt":"2.0"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error\/Error-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"Error.localizedDescription","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/intervalfloat\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error\/localizedDescription"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/Error/Error-Implementations":{"title":"Error Implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error\/Error-Implementations","type":"topic","kind":"article","role":"collectionGroup","url":"\/documentation\/dotfacecore\/intervalfloat\/error\/error-implementations","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/Error":{"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/intervalfloat\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"IntervalFloat.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/Error/localizedDescription":{"title":"localizedDescription","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error\/localizedDescription","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/intervalfloat\/error\/localizeddescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat":{"url":"\/documentation\/dotfacecore\/intervalfloat","type":"topic","kind":"symbol","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"title":"IntervalFloat","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","role":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTIntervalFloat","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}