{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:finished:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontroller(_:finished:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontroller(_:finished:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate(im)fingersAutoCaptureViewController:finished:","role":"symbol","title":"fingersAutoCaptureViewController(_:finished:)","navigatorTitle":[{"text":"fingersAutoCaptureViewController:finished:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fingersAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","text":"FingersAutoCaptureResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"Tells the delegate that the fingers auto capture component has finished with a result. This callback is called after the component has stopped."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingersAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureResult","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"role":"symbol","title":"FingersAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the fingers auto capture process."}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewController(_:finished:)":{"type":"topic","kind":"symbol","title":"fingersAutoCaptureViewController(_:finished:)","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontroller(_:finished:)","abstract":[{"text":"Tells the delegate that the fingers auto capture component has finished with a result. This callback is called after the component has stopped.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingersAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","text":"FingersAutoCaptureResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"fingersAutoCaptureViewController:finished:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:finished:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate":{"role":"symbol","title":"FingersAutoCaptureViewControllerDelegate","navigatorTitle":[{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the fingers auto capture events."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"fingersAutoCaptureViewController:finished:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fingersAutoCaptureViewController:finished:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"fingersAutoCaptureViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGBaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"finished:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingersAutoCaptureResult","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title","value":"DOTFGBaseFingersAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title","value":"DOTFGFingersAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewController(_:finished:)\/title","value":"fingersAutoCaptureViewController:finished:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewController(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fingersAutoCaptureViewController:finished:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/title","value":"DOTFGFingersAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewControllerDelegate"}]}]}]}