{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},{"text":")","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"fingersAutoCaptureViewControllerViewWillDisappear(_:)","externalID":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate(im)fingersAutoCaptureViewControllerViewWillDisappear:","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewWillDisappear:"}],"symbolKind":"method","modules":[{"name":"DotFingersCore"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillDisappear(_:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewWillDisappear(_:)":{"kind":"symbol","title":"fingersAutoCaptureViewControllerViewWillDisappear(_:)","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewwilldisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewWillDisappear:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillDisappear(_:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate":{"role":"symbol","title":"FingersAutoCaptureViewControllerDelegate","navigatorTitle":[{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the fingers auto capture events."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"fingersAutoCaptureViewControllerViewWillDisappear:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"fingersAutoCaptureViewControllerViewWillDisappear:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillDisappear(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillDisappear(_:)\/fragments","op":"replace"},{"value":"DOTFGFingersAutoCaptureViewControllerDelegate","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/navigatorTitle","op":"replace"},{"value":"DOTFGBaseFingersAutoCaptureViewController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}