{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollernocamerapermission(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollernocamerapermission(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"metadata":{"title":"fingersAutoCaptureViewControllerNoCameraPermission(_:)","navigatorTitle":[{"text":"fingersAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate(im)fingersAutoCaptureViewControllerNoCameraPermission:","symbolKind":"method","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerNoCameraPermission(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate":{"role":"symbol","title":"FingersAutoCaptureViewControllerDelegate","navigatorTitle":[{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the fingers auto capture events."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerNoCameraPermission(_:)":{"role":"symbol","title":"fingersAutoCaptureViewControllerNoCameraPermission(_:)","navigatorTitle":[{"text":"fingersAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollernocamerapermission(_:)","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerNoCameraPermission(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fingersAutoCaptureViewControllerNoCameraPermission:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","kind":"typeIdentifier","text":"DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFGBaseFingersAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle"},{"value":"DOTFGFingersAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewControllerDelegate"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/navigatorTitle"},{"op":"replace","value":"fingersAutoCaptureViewControllerNoCameraPermission:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerNoCameraPermission(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerNoCameraPermission(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}