{"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessViewControllerViewDidLayoutSubviews:","platforms":[],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews:"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","role":"symbol"},"kind":"symbol","deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidlayoutsubviews(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidlayoutsubviews(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(magnifEyeLivenessViewControllerViewDidLayoutSubviews:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"typeIdentifier","text":"MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"title":"MagnifEyeLivenessViewController","deprecated":true,"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)":{"deprecated":true,"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidlayoutsubviews(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","title":"magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","abstract":[],"navigatorTitle":[{"text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate":{"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate","kind":"symbol","type":"topic","abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"deprecated":true,"title":"MagnifEyeLivenessViewControllerDelegate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"magnifEyeLivenessViewControllerViewDidLayoutSubviews:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFMagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)\/title","value":"magnifEyeLivenessViewControllerViewDidLayoutSubviews:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFMagnifEyeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}