{"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/detection"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/description"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotpalmmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotpalmmoduleid"]}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"c:@M@DotCore@E@DotPalmModuleId","title":"DotPalmModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotNfc\/SY"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/RawRepresentable-Implementations","url":"\/documentation\/dotnfc\/dotpalmmoduleid\/rawrepresentable-implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId":{"kind":"symbol","role":"symbol","title":"DotPalmModuleId","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId","type":"topic","abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotnfc\/dotpalmmoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}]},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/detection":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/detection","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"url":"\/documentation\/dotnfc\/dotpalmmoduleid\/detection","kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"DotPalmModuleId.detection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}]},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/init(rawValue:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/dotpalmmoduleid\/init(rawvalue:)","role":"symbol","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/description":{"kind":"symbol","role":"symbol","title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/description","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/dotpalmmoduleid\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotNfc/documentation/DotNfc/DotPalmModuleId/Equatable-Implementations":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/Equatable-Implementations","url":"\/documentation\/dotnfc\/dotpalmmoduleid\/equatable-implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmModuleId\/detection"],"anchor":"Enumeration-Cases","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/title","op":"replace","value":"DotPalmModuleId"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId~1detection\/title","value":"DotPalmModuleIdDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmModuleId~1detection\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}]}]}]}