{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit(im)initWithValue:positions:checkDigit:date:","roleHeading":"Initializer","symbolKind":"init","role":"symbol","title":"init(value:positions:checkDigit:date:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"positions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MrzStringPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"checkDigit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"date","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzDate","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:checkDigit:date:"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"positions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"kind":"text","text":"], "},{"text":"checkDigit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":", "},{"text":"date","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","text":"MrzDate","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"title":"MrzStringPosition","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.7.1","type":"text"}],"type":"topic","role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzdate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDate","kind":"identifier"}],"title":"MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}],"title":"MrzDateElementWithCheckDigit","kind":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit/init(value:positions:checkDigit:date:)":{"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)","title":"init(value:positions:checkDigit:date:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"positions"},{"text":": [","kind":"text"},{"text":"MrzStringPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition"},{"text":"], ","kind":"text"},{"text":"checkDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"date"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","kind":"typeIdentifier","text":"MrzDate"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:checkDigit:date:"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"title":"MrzCheckDigit","type":"topic","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithValue:positions:checkDigit:date:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:positions:checkDigit:date:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithValue:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"positions:"},{"text":"(","kind":"text"},{"text":"NSArray<DOTMrzStringPosition *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"positions","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"checkDigit:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","text":"DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"checkDigit","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"date:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","text":"DOTMrzDate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"date"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition","op":"replace"},{"op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","op":"replace","value":"DOTMrzDate"},{"value":[{"text":"DOTMrzDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/title","op":"replace","value":"initWithValue:positions:checkDigit:date:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:positions:checkDigit:date:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"op":"replace"}]}]}