{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"metadata":{"roleHeading":"Initializer","symbolKind":"init","title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentNumber"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfBirth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"optionalData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":"?, ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"},{"text":")","kind":"text"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(im)initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentCode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"documentNumber","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"typeIdentifier","text":"MrzElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"optionalData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?, ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"type":"topic","title":"MrzReader"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"type":"topic","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"title":"MrzNameElement","url":"\/documentation\/dotdocument\/mrznameelement","abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"type":"topic","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}],"title":"MrzDateElementWithCheckDigit","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"type":"topic","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","url":"\/documentation\/dotdocument\/mrzelement","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"title":"Td2MachineReadableZone","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","kind":"symbol","url":"\/documentation\/dotdocument\/td2machinereadablezone"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","kind":"symbol","abstract":[{"text":"A ","type":"text"},{"code":"MrzElement","type":"codeVoice"},{"text":" with check digit and checksum validitity information.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","title":"MrzElementWithCheckDigit","type":"topic"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","role":"symbol","url":"\/documentation\/dotdocument\/td2machinereadablezone\/init(documentcode:issuingstateororganization:name:documentnumber:nationality:dateofbirth:sex:dateofexpiry:optionaldata:compositecheckdigit:)","kind":"symbol","title":"init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)","abstract":[],"navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentCode"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"kind":"text","text":", "},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"optionalData","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"title":"MrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDocumentCode:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"DOTMrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentCode"},{"kind":"text","text":" "},{"text":"issuingStateOrOrganization:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},{"text":" *) ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"name:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"DOTMrzNameElement","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"text":"documentNumber:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"documentNumber"},{"kind":"text","text":" "},{"text":"nationality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nationality"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"DOTMrzDateElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"text":"dateOfBirth","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sex:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"sex","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dateOfExpiry:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dateOfExpiry"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optionalData:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"DOTMrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"optionalData"},{"kind":"text","text":" "},{"text":"compositeCheckDigit:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":" *) "},{"text":"compositeCheckDigit","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"value":"DOTMrzNameElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}]},{"value":"DOTMrzDateElementWithCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"value":"DOTMrzElement","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"op":"replace","value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"op":"replace","value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:documentNumber:nationality:dateOfBirth:sex:dateOfExpiry:optionalData:compositeCheckDigit:)\/fragments"},{"value":"DOTMrzCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}