{"metadata":{"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:result:phase:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithDetection:result:phase:","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerProcessingResult(im)initWithDetection:result:phase:","title":"initWithDetection:result:phase:","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","kind":"typeIdentifier","text":"DOTFLFaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"text":"DOTFLFaceAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"phase:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFaceAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase"},{"text":") ","kind":"text"},{"text":"phase","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/initWithDetection:result:phase:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/initwithdetection:result:phase:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturephase","title":"FaceAutoCapturePhase","abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePhase"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePhase"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult/initWithDetection:result:phase:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:result:phase:"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/initwithdetection:result:phase:","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/initWithDetection:result:phase:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:phase:"}],"title":"initWithDetection:result:phase:","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult":{"kind":"symbol","type":"topic","title":"DOTFLFaceAutoCaptureControllerProcessingResult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the face auto capture process."}],"fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerProcessingResult"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"role":"symbol","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureresult","title":"FaceAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection","title":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","role":"symbol","type":"topic","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFaceAutoCapturePhase","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/title","op":"replace"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/fragments","op":"replace"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/navigatorTitle","op":"replace"},{"value":"DOTFLFaceAutoCaptureResult","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle","op":"replace"},{"value":"DOTFLFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","op":"replace"}]}]}