{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview(im)initWithCameraImage:detectionArea:placeholder:","navigatorTitle":[{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init","modules":[{"name":"DotFaceCore"}],"title":"init(cameraImage:detectionArea:placeholder:)","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cameraImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturepreview\/init(cameraimage:detectionarea:placeholder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocapturepreview\/init(cameraimage:detectionarea:placeholder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview":{"title":"FaceAutoCapturePreview","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturepreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview/init(cameraImage:detectionArea:placeholder:)":{"type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholder:"}],"url":"\/documentation\/dotfacecore\/faceautocapturepreview\/init(cameraimage:detectionarea:placeholder:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":")"}],"title":"init(cameraImage:detectionArea:placeholder:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"title":"RectangleDouble","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","url":"\/documentation\/dotfacecore\/rectangledouble","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithCameraImage:detectionArea:placeholder:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea:"},{"kind":"text","text":"("},{"text":"DOTRectangleDouble","preciseIdentifier":"c:objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectionArea","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTRectangleDouble","preciseIdentifier":"c:objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholder","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/title","op":"replace","value":"DOTFaceAutoCapturePreview"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/navigatorTitle","op":"replace","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/title","op":"replace","value":"initWithCameraImage:detectionArea:placeholder:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/navigatorTitle","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}