{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturepreview\/placeholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturepreview\/placeholder"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview\/placeholder","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"title":"placeholder","externalID":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview(py)placeholder"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview"]]},"sections":[],"abstract":[{"type":"text","text":"A rectangular region defined relative to the container that represents the placeholder position."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview/placeholder":{"title":"placeholder","type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturepreview\/placeholder","role":"symbol","kind":"symbol","abstract":[{"text":"A rectangular region defined relative to the container that represents the placeholder position.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview\/placeholder","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"placeholder"}]},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"title":"RectangleDouble","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","url":"\/documentation\/dotfacecore\/rectangledouble","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview":{"title":"FaceAutoCapturePreview","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturepreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"placeholder","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"placeholder"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:objc(cs)DOTRectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"placeholder","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview~1placeholder\/title"},{"op":"replace","value":[{"text":"placeholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview~1placeholder\/fragments"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/navigatorTitle"},{"op":"replace","value":"DOTFaceAutoCapturePreview","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/title"},{"op":"replace","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/navigatorTitle"}]}]}