{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/placeholder\/visible\/init(type:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"init(type:)","externalID":"s:14DotFingersCore11PlaceholderC7VisibleC4typeAeA0D4TypeO_tcfc","symbolKind":"init","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGPlaceholderType","text":"PlaceholderType"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PlaceholderType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGPlaceholderType"},{"text":" = .left)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible\/init(type:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Visible/init(type:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible\/init(type:)","type":"topic","title":"init(type:)","url":"\/documentation\/dotfingerscore\/placeholder\/visible\/init(type:)","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGPlaceholderType","kind":"typeIdentifier","text":"PlaceholderType"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"role":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"abstract":[{"type":"text","text":"Placeholder."}],"url":"\/documentation\/dotfingerscore\/placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType":{"type":"topic","kind":"symbol","title":"PlaceholderType","url":"\/documentation\/dotfingerscore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Visible":{"url":"\/documentation\/dotfingerscore\/placeholder\/visible","abstract":[{"type":"text","text":"Visible placeholder."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Visible"}],"navigatorTitle":[{"text":"Visible","kind":"identifier"}],"title":"Placeholder.Visible","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title","value":"DOTFGPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTFGPlaceholder"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGPlaceholder"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/title","value":"DOTFGPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}]}]}]}