{"metadata":{"required":true,"symbolKind":"property","modules":[{"name":"DotNfc"}],"role":"symbol","title":"isFaceLiteEnabled","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceLiteEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceliteenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceliteenabled"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"type":"topic","title":"DotSdkLicenseProxyProtocol","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceliteenabled","role":"symbol","required":true,"title":"isFaceLiteEnabled","navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isFaceLiteEnabled","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/navigatorTitle","op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title","op":"replace","value":"isFaceLiteEnabled"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments","op":"replace","value":[{"text":"isFaceLiteEnabled","kind":"identifier"}]}]}]}