{"metadata":{"title":"isNfcEnabled","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isNfcEnabled","required":true,"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isnfcenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isnfcenabled"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isNfcEnabled"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isNfcEnabled":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"type":"topic","abstract":[],"required":true,"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isNfcEnabled","title":"isNfcEnabled","url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isnfcenabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isNfcEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title","value":"isNfcEnabled"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]}]}]}