{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled"]},{"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol"]]},"metadata":{"required":true,"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isRealTimeTransactionReportingEnabled","navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","externalID":"c:@M@DotNfc@objc(pl)DotSdkLicenseProxyProtocol(py)isRealTimeTransactionReportingEnabled"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"role":"symbol","required":true,"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"title":"isRealTimeTransactionReportingEnabled"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.3.0","type":"text"}],"role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"isRealTimeTransactionReportingEnabled","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title","value":"isRealTimeTransactionReportingEnabled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}]},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace"}]}]}