{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcodevalidation\/description"]}],"metadata":{"role":"symbol","externalID":"s:11DotDocument17BarcodeValidationO11descriptionSSvp","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"description","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/description","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"references":{"doc://DotDocument/documentation/DotDocument/BarcodeValidation/description":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/description","url":"\/documentation\/dotdocument\/barcodevalidation\/description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"description","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","type":"topic","title":"BarcodeValidation","abstract":[{"text":"Mode of barcode validation.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BarcodeValidation"}],"role":"symbol","url":"\/documentation\/dotdocument\/barcodevalidation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTDBarcodeValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title"},{"op":"replace","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments"},{"op":"replace","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle"}]}]}