{"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requirePresenceAndValidity","kind":"identifier"}],"title":"BarcodeValidation.requirePresenceAndValidity","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTDBarcodeValidationRequirePresenceAndValidity"}],"externalID":"c:@M@DotDocument@E@DOTDBarcodeValidation@DOTDBarcodeValidationRequirePresenceAndValidity"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/requirePresenceAndValidity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A barcode must be present and valid."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requirePresenceAndValidity","kind":"identifier"}],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"inlineContent":[{"text":"If you want to use this option, you will need the ","type":"text"},{"code":"DotDocumentBarcode","type":"codeVoice"},{"text":" module to be active.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcodevalidation\/requirepresenceandvalidity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/barcodevalidation\/requirepresenceandvalidity"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/BarcodeValidation/requirePresenceAndValidity":{"type":"topic","url":"\/documentation\/dotdocument\/barcodevalidation\/requirepresenceandvalidity","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/requirePresenceAndValidity","abstract":[{"type":"text","text":"A barcode must be present and valid."}],"role":"symbol","title":"BarcodeValidation.requirePresenceAndValidity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requirePresenceAndValidity"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDBarcodeValidationRequirePresenceAndValidity"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"type":"topic","url":"\/documentation\/dotdocument\/barcodevalidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","abstract":[{"type":"text","text":"Mode of barcode validation."}],"role":"symbol","title":"BarcodeValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTDBarcodeValidationRequirePresenceAndValidity","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTDBarcodeValidationRequirePresenceAndValidity","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTDBarcodeValidationRequirePresenceAndValidity","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1requirePresenceAndValidity\/title","value":"DOTDBarcodeValidationRequirePresenceAndValidity","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation~1requirePresenceAndValidity\/fragments","value":[{"text":"DOTDBarcodeValidationRequirePresenceAndValidity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","value":"DOTDBarcodeValidation","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"op":"replace"}]}]}