{"variants":[{"paths":["\/documentation\/dotnfc\/bgrarawimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/bgrarawimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithBgrRawImage:","title":"create(bgrRawImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":") -> "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"modules":[{"name":"DotNfc"}],"symbolKind":"method"},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(bgrRawImage:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"kind":"text","text":") -> "},{"text":"BgraRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"bgrRawImage"}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/BgrRawImage":{"title":"BgrRawImage","url":"\/documentation\/dotnfc\/bgrrawimage","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}]},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory/create(bgrRawImage:)":{"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"role":"symbol","type":"topic","title":"create(bgrRawImage:)","url":"\/documentation\/dotnfc\/bgrarawimagefactory\/create(bgrrawimage:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(bgrRawImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}]},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"kind":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"type":"topic","title":"BgraRawImage","role":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","url":"\/documentation\/dotnfc\/bgrarawimage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory":{"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrarawimagefactory","abstract":[{"type":"text","text":"Create "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory","title":"BgraRawImageFactory","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"createWithBgrRawImage:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"},{"kind":"text","text":"("},{"text":"DOTBgrRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgrRawImage"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/title","op":"replace","value":"DOTBgrRawImage"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(bgrRawImage:)\/fragments"},{"op":"replace","value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace"},{"value":"DOTBgraRawImageFactory","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/fragments"}]}]}