{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"ImageFactory","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Class"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"anchor":"Converting-images","generated":true,"title":"Converting images"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/imagefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imagefactory"]}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"title":"CIImageFactory","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotpalmcore\/ciimagefactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory":{"title":"ImageFactory","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"url":"\/documentation\/dotpalmcore\/imagefactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/image","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","title":"Image"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory/createBgrRawImage(ciImage:ciContext:)":{"url":"\/documentation\/dotpalmcore\/imagefactory\/createbgrrawimage(ciimage:cicontext:)","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","kind":"symbol","title":"createBgrRawImage(ciImage:ciContext:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"role":"symbol","navigatorTitle":[{"text":"createBgrRawImageWithCiImage:ciContext:","kind":"identifier"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory/createBgrRawImage(cgImage:)":{"title":"createBgrRawImage(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgrRawImage(cgImage:)","url":"\/documentation\/dotpalmcore\/imagefactory\/createbgrrawimage(cgimage:)"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory":{"url":"\/documentation\/dotpalmcore\/cgimagefactory","title":"CGImageFactory","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory/createBgraRawImage(cgImage:)":{"url":"\/documentation\/dotpalmcore\/imagefactory\/createbgrarawimage(cgimage:)","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(cgImage:)","kind":"symbol","title":"createBgraRawImage(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}]},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"title":"createBgraRawImage(ciImage:ciContext:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory/createBgraRawImage(bgrRawImage:)":{"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgr"},{"text":" format as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}],"url":"\/documentation\/dotpalmcore\/imagefactory\/createbgrarawimage(bgrrawimage:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","title":"createBgraRawImage(bgrRawImage:)"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"Converting-images","generated":true,"title":"Converting images","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFactory"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/title","value":"createBgrRawImageWithCiImage:ciContext:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCiImage:ciContext:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgrRawImage(cgImage:)\/title","value":"createBgrRawImageWithCgImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(cgImage:)\/title","value":"createBgraRawImageWithCgImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title","value":"createBgraRawImageWithCiImage:ciContext:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title","value":"createBgraRawImageWithBgrRawImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}