{"kind":"symbol","metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Protocol","title":"PalmAutoCaptureViewControllerDelegate","role":"symbol","externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}]},"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:finished:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:uiStateUpdated:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillTransition(_:)"],"generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"abstract":[{"type":"text","text":"Implement this delegate to handle the palm auto capture events."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureViewControllerDelegate) "},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureViewControllerDelegate","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewWillDisappear(_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillDisappear(_:)","title":"palmAutoCaptureViewControllerViewWillDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"palmAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilldisappear(_:)","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerNoCameraPermission(_:)":{"title":"palmAutoCaptureViewControllerNoCameraPermission(_:)","kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollernocamerapermission(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerNoCameraPermission(_:)","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerNoCameraPermission:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewDidLayoutSubviews(_:)":{"abstract":[],"title":"palmAutoCaptureViewControllerViewDidLayoutSubviews(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palmAutoCaptureViewControllerViewDidLayoutSubviews","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"palmAutoCaptureViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLayoutSubviews(_:)","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdidlayoutsubviews(_:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewController(_:uiStateUpdated:)":{"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palmAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiState"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"palmAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontroller(_:uistateupdated:)","title":"palmAutoCaptureViewController(_:uiStateUpdated:)","type":"topic","abstract":[{"type":"text","text":"Tells the delegate that the UI state was updated."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:uiStateUpdated:)"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate","title":"PalmAutoCaptureViewControllerDelegate","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the palm auto capture events."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewDidLoad(_:)":{"title":"palmAutoCaptureViewControllerViewDidLoad(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdidload(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLoad(_:)","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewDidDisappear(_:)":{"title":"palmAutoCaptureViewControllerViewDidDisappear(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdiddisappear(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidDisappear:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewWillAppear(_:)":{"title":"palmAutoCaptureViewControllerViewWillAppear(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwillappear(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillAppear:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillAppear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewWillTransition(_:)":{"title":"palmAutoCaptureViewControllerViewWillTransition(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewwilltransition(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillTransition(_:)","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillTransition:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillTransition"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewControllerViewDidAppear(_:)":{"title":"palmAutoCaptureViewControllerViewDidAppear(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontrollerviewdidappear(_:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidAppear:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidAppear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","kind":"typeIdentifier","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewController(_:finished:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:finished:)","title":"palmAutoCaptureViewController(_:finished:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palmAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"palmAutoCaptureViewController:finished:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontroller(_:finished:)","required":true,"abstract":[{"text":"Tells the delegate that the palm auto capture component has finished with a result.. This callback is called after the component has stopped.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"DOTPPalmAutoCaptureViewControllerDelegate","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:finished:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:uiStateUpdated:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewControllerViewWillTransition(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillDisappear(_:)\/title","value":"palmAutoCaptureViewControllerViewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillDisappear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerNoCameraPermission(_:)\/title","value":"palmAutoCaptureViewControllerNoCameraPermission:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerNoCameraPermission(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerNoCameraPermission:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/title","value":"palmAutoCaptureViewControllerViewDidLayoutSubviews:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLayoutSubviews:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewController(_:uiStateUpdated:)\/title","value":"palmAutoCaptureViewController:uiStateUpdated:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewController(_:uiStateUpdated:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewController:uiStateUpdated:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/title","value":"DOTPPalmAutoCaptureViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidLoad(_:)\/title","value":"palmAutoCaptureViewControllerViewDidLoad:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidLoad:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidDisappear(_:)\/title","value":"palmAutoCaptureViewControllerViewDidDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidDisappear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillAppear(_:)\/title","value":"palmAutoCaptureViewControllerViewWillAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillAppear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillTransition(_:)\/title","value":"palmAutoCaptureViewControllerViewWillTransition:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewWillTransition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewWillTransition:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidAppear(_:)\/title","value":"palmAutoCaptureViewControllerViewDidAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewControllerViewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewControllerViewDidAppear:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewController(_:finished:)\/title","value":"palmAutoCaptureViewController:finished:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewController(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewController:finished:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}