{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble"]]},"sections":[],"metadata":{"title":"description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"description","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble(py)description","modules":[{"name":"DotFaceLite"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/description"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/intervaldouble\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/intervaldouble\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble\/description","kind":"symbol","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/intervaldouble\/description"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble":{"title":"IntervalDouble","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble","role":"symbol","url":"\/documentation\/dotfacelite\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble~1description\/fragments","op":"replace"},{"value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/title","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/fragments","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/navigatorTitle","op":"replace"}]}]}