{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"primaryElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"MrzElement"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"secondaryElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"MrzElement"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrznameelement\/init(primaryelement:secondaryelement:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrznameelement\/init(primaryelement:secondaryelement:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement\/init(primaryElement:secondaryElement:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"primaryElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"secondaryElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":"?)"}],"title":"init(primaryElement:secondaryElement:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNameElement(im)initWithPrimaryElement:secondaryElement:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPrimaryElement:secondaryElement:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 6.5.2"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNameElement/init(primaryElement:secondaryElement:)":{"role":"symbol","title":"init(primaryElement:secondaryElement:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"primaryElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"secondaryElement"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement\/init(primaryElement:secondaryElement:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPrimaryElement:secondaryElement:"}],"url":"\/documentation\/dotdocument\/mrznameelement\/init(primaryelement:secondaryelement:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"role":"symbol","title":"MrzElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNameElement":{"role":"symbol","title":"MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone name element with primary and secondary elements."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"url":"\/documentation\/dotdocument\/mrznameelement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPrimaryElement:secondaryElement:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPrimaryElement:secondaryElement:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPrimaryElement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"primaryElement"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryElement:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"secondaryElement"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement~1init(primaryElement:secondaryElement:)\/title","value":"initWithPrimaryElement:secondaryElement:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement~1init(primaryElement:secondaryElement:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPrimaryElement:secondaryElement:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title","value":"DOTDMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTDMrzElement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTDMrzNameElement"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNameElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}