{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery","text":"FaceImageQualityQuery","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"headPose","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","text":"HeadPoseQuery","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"wearables","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"WearablesQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery","text":"ExpressionQuery"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:headPose:wearables:expression:"}],"symbolKind":"init","roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery(im)initWithImageQuality:headPose:wearables:expression:","title":"init(imageQuality:headPose:wearables:expression:)","modules":[{"name":"DotFaceCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery\/init(imageQuality:headPose:wearables:expression:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceImageQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"},{"kind":"text","text":" = FaceImageQualityQuery(), "},{"text":"headPose","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HeadPoseQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","kind":"typeIdentifier"},{"kind":"text","text":" = HeadPoseQuery(), "},{"text":"wearables","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery","kind":"typeIdentifier","text":"WearablesQuery"},{"kind":"text","text":" = WearablesQuery(), "},{"kind":"externalParam","text":"expression"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","text":"ExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery","kind":"typeIdentifier"},{"kind":"text","text":" = ExpressionQuery())"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facequalityquery\/init(imagequality:headpose:wearables:expression:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facequalityquery\/init(imagequality:headpose:wearables:expression:)"]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","role":"symbol","title":"ExpressionQuery","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}],"navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/expressionquery","abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"title":"FaceQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"role":"symbol","url":"\/documentation\/dotfacecore\/facequalityquery","kind":"symbol","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"title":"HeadPoseQuery","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseQuery"}],"abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","kind":"symbol","url":"\/documentation\/dotfacecore\/headposequery","role":"symbol","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"title":"FaceImageQualityQuery","type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImageQualityQuery"}],"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}]},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"title":"WearablesQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WearablesQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/wearablesquery","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery/init(imageQuality:headPose:wearables:expression:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceImageQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"headPose","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","text":"HeadPoseQuery"},{"text":", ","kind":"text"},{"text":"wearables","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery","text":"WearablesQuery"},{"text":", ","kind":"text"},{"text":"expression","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery","text":"ExpressionQuery","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery\/init(imagequality:headpose:wearables:expression:)","kind":"symbol","abstract":[],"title":"init(imageQuality:headPose:wearables:expression:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:headPose:wearables:expression:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery\/init(imageQuality:headPose:wearables:expression:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithImageQuality:headPose:wearables:expression:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageQuality:headPose:wearables:expression:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithImageQuality:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","text":"DOTFFaceImageQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageQuality"},{"kind":"text","text":" "},{"text":"headPose:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","kind":"typeIdentifier","text":"DOTFHeadPoseQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"headPose"},{"kind":"text","text":" "},{"kind":"identifier","text":"wearables:"},{"text":"(","kind":"text"},{"text":"DOTFWearablesQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"wearables"},{"text":" ","kind":"text"},{"text":"expression:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"expression"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery"},{"value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments"},{"value":"DOTFHeadPoseQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}]},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments"},{"value":"DOTFWearablesQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery~1init(imageQuality:headPose:wearables:expression:)\/title","value":"initWithImageQuality:headPose:wearables:expression:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery~1init(imageQuality:headPose:wearables:expression:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImageQuality:headPose:wearables:expression:"}]}]}]}