{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)"]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"init","roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotNfc"}],"title":"init(detection:)","externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAeA0ac15DetectionModuleE0C_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","abstract":[],"title":"init(detection:)"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration":{"kind":"symbol","title":"DotPalmLibraryConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"type":"topic","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration"},"doc://DotNfc/documentation/DotNfc/DotPalmDetectionModuleConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration","title":"DotPalmDetectionModuleConfiguration","url":"\/documentation\/dotnfc\/dotpalmdetectionmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Palm detection module configuration.","type":"text"}],"navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class","abstract":[{"text":"Palm library module configuration.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"title":"DotPalmLibraryConfiguration.Modules","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/modules-swift.class","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}