{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"modules","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotPalmModule","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotPalmModule"},{"text":"]","kind":"text"}]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"modules","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotPalmModule","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotPalmModule"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration(py)modules","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","title":"modules"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/modules"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration"]]},"abstract":[{"type":"text","text":"List of modules to load during initialization."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModule":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModule"}],"navigatorTitle":[{"text":"DotPalmModule","kind":"identifier"}],"title":"DotPalmModule","url":"\/documentation\/dotpalmcore\/dotpalmmodule","abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module."}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library. This class specifies how the "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library will be initialized."}],"role":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/modules":{"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/modules","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"modules","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DotPalmModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotPalmModule"},{"kind":"text","text":"]"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"modules"}],"abstract":[{"type":"text","text":"List of modules to load during initialization."}],"title":"modules"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"modules","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"modules","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<DotPalmModule>>"},{"kind":"text","text":" * "},{"text":"modules","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DotPalmModule","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/fragments","op":"replace","value":[{"text":"DotPalmModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1modules\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1modules\/fragments","value":[{"kind":"identifier","text":"modules"}]}]}]}