{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/pointdouble\/x"]},{"paths":["\/documentation\/dotpalmcore\/pointdouble\/x"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/x","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble"]]},"sections":[],"abstract":[{"text":"X coordinate.","type":"text"}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(py)x","roleHeading":"Instance Property","title":"x","symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"x","kind":"identifier"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"url":"\/documentation\/dotpalmcore\/pointdouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","title":"PointDouble","role":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/x":{"navigatorTitle":[{"text":"x","kind":"identifier"}],"title":"x","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/x","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"X coordinate."}],"url":"\/documentation\/dotpalmcore\/pointdouble\/x"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 8.14.1"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"x"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"x"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1x\/title","op":"replace","value":"x"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1x\/fragments","op":"replace","value":[{"kind":"identifier","text":"x"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}