{"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfingersmoduleid\/equatable-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId"]]},"topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/!=(_:_:)"],"title":"Operators","generated":true}],"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"DotFingersCore"}],"role":"collectionGroup"},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/!=(_:_:)":{"title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/!=(_:_:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/!=(_:_:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId":{"kind":"symbol","title":"DotFingersModuleId","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/fragments","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}]}]}]}