{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/issuingstateororganization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/issuingstateororganization"]}],"metadata":{"title":"issuingStateOrOrganization","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)issuingStateOrOrganization","navigatorTitle":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"symbolKind":"property","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"issuingStateOrOrganization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"MrzElement","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/issuingStateOrOrganization","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone"]]},"references":{"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone/issuingStateOrOrganization":{"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone\/issuingstateororganization","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/issuingStateOrOrganization","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"}],"title":"issuingStateOrOrganization","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"title":"Td1MachineReadableZone","type":"topic","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","role":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td1MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"title":"MrzReader"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"title":"MrzElement","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"symbol","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"issuingStateOrOrganization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"issuingStateOrOrganization","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"issuingStateOrOrganization"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1issuingStateOrOrganization\/title","value":"issuingStateOrOrganization"},{"value":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1issuingStateOrOrganization\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments"},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace"}]}]}