{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.helpAnchor"},{"type":"text","text":"."}],"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"DotDocument","relatedModules":["Foundation"]}],"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:11DotDocument22ImagePerspectiveWarperC5ErrorO","extendedModule":"Foundation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","platforms":[{"beta":false,"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"8.0"},{"beta":false,"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"8.0"},{"beta":false,"name":"Mac Catalyst","unavailable":false,"deprecated":false,"introducedAt":"8.0"},{"beta":false,"name":"macOS","unavailable":false,"deprecated":false,"introducedAt":"10.10"},{"beta":false,"name":"tvOS","unavailable":false,"deprecated":false,"introducedAt":"9.0"},{"beta":false,"name":"watchOS","unavailable":false,"deprecated":false,"introducedAt":"2.0"}],"title":"helpAnchor"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/error\/helpanchor"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/helpAnchor"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"abstract":[{"text":"Stateless class which can warp the image perspective and create new image as a result.","type":"text"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper","role":"symbol","navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","kind":"symbol","type":"topic","title":"ImagePerspectiveWarper"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error/helpAnchor":{"abstract":[],"url":"\/documentation\/dotdocument\/imageperspectivewarper\/error\/helpanchor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/helpAnchor","kind":"symbol","type":"topic","title":"helpAnchor"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error":{"abstract":[],"url":"\/documentation\/dotdocument\/imageperspectivewarper\/error","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error","kind":"symbol","type":"topic","title":"ImagePerspectiveWarper.Error"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","op":"replace","value":"DOTDImagePerspectiveWarper"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","op":"replace","value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/navigatorTitle","op":"replace","value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}