{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/backgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Background color of top level view."}],"metadata":{"title":"backgroundColor","externalID":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC15backgroundColorSo7UIColorCvp","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/backgroundColor","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class":{"abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class","type":"topic","navigatorTitle":[{"text":"Style","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class","title":"SmileLivenessViewController.Style","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"type":"topic","kind":"symbol","abstract":[{"text":"UI Smile Liveness component.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","title":"SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class/backgroundColor":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class\/backgroundColor","abstract":[{"text":"Background color of top level view.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class\/backgroundcolor","title":"backgroundColor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFSmileLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle","op":"replace"}]}]}