{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator\/init()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator\/init()"]}],"kind":"symbol","abstract":[{"type":"text","text":"Initialize with default threshold."}],"metadata":{"title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooLowValidator(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"references":{"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator/init()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator\/init()","role":"symbol","title":"init()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Initialize with default threshold."}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/init()"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"title":"BrightnessTooLowValidator","type":"topic","abstract":[{"text":"Validate minimum brightness of the detected document.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.14.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","value":"DOTDBrightnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooLowValidator"}]}]}]}