{"metadata":{"navigatorTitle":[{"text":"moduleId","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(pl)DotFingersModule(py)moduleId","symbolKind":"property","required":true,"roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"title":"moduleId","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersModuleId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotFingersModuleId"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId","text":"DotFingersModuleId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotFingersModuleId"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule\/moduleId","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/dotfingersmodule\/moduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotfingersmodule\/moduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModule":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModule"}],"kind":"symbol","role":"symbol","title":"DotFingersModule","abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module."}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModule"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmodule"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFingersModuleId","abstract":[{"type":"codeVoice","code":"DotFingers"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModule/moduleId":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule\/moduleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersModuleId","preciseIdentifier":"c:@M@DotCore@E@DotFingersModuleId"}],"kind":"symbol","role":"symbol","title":"moduleId","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"required":true,"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmodule\/moduleid"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"moduleId"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"moduleId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId","preciseIdentifier":"c:@M@DotCore@E@DotFingersModuleId","text":"DotFingersModuleId"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule\/title","value":"DotFingersModule"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule\/fragments","value":[{"text":"DotFingersModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule\/navigatorTitle","value":[{"text":"DotFingersModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/fragments","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule~1moduleId\/title","value":"moduleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule~1moduleId\/fragments","value":[{"text":"moduleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}