{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDDetectionPosition) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}]}]}],"sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Document-detection-output","title":"Document detection output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"variants":[{"paths":["\/documentation\/dotdocument\/detectionposition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/detectionposition"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Position of the document card in the image."}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/bottomLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/bottomRight","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/points","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topRight"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/isEqual(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/mirrored()","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/rebased(parentRectangle:)"]},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/from(rectangle:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"]]},"metadata":{"title":"DetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","roleHeading":"Class","symbolKind":"class","role":"symbol","modules":[{"name":"DotDocument"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DetectionPosition/description":{"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/description","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/detectionposition\/description","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/init(topLeft:topRight:bottomRight:bottomLeft:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition\/init(topleft:topright:bottomright:bottomleft:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":")"}]},"doc://DotDocument/documentation/DotDocument/DetectionPosition/isEqual(_:)":{"title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/isEqual(_:)","url":"\/documentation\/dotdocument\/detectionposition\/isequal(_:)"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"text":"Position of the document card in the image.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","type":"topic","title":"DetectionPosition","url":"\/documentation\/dotdocument\/detectionposition","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/hash":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/detectionposition\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"hash","abstract":[]},"doc://DotDocument/documentation/DotDocument/DetectionPosition/bottomLeft":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"abstract":[{"type":"text","text":"Bottom left corner point."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/bottomLeft","url":"\/documentation\/dotdocument\/detectionposition\/bottomleft","role":"symbol","title":"bottomLeft","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/topRight":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"topRight","kind":"identifier"}],"abstract":[{"type":"text","text":"Top right corner point."}],"url":"\/documentation\/dotdocument\/detectionposition\/topright","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topRight","title":"topRight","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/mirrored()":{"url":"\/documentation\/dotdocument\/detectionposition\/mirrored()","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"title":"mirrored()","type":"topic"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/rebased(parentRectangle:)":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/rebased(parentRectangle:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"title":"rebased(parentRectangle:)","abstract":[],"url":"\/documentation\/dotdocument\/detectionposition\/rebased(parentrectangle:)"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/points":{"navigatorTitle":[{"kind":"identifier","text":"points"}],"abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":"]"}],"url":"\/documentation\/dotdocument\/detectionposition\/points","title":"points","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/points","kind":"symbol"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/bottomRight":{"url":"\/documentation\/dotdocument\/detectionposition\/bottomright","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/bottomRight","abstract":[{"text":"Bottom right corner point.","type":"text"}],"type":"topic","title":"bottomRight","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","title":"DocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"title":"DocumentDetector.Document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"url":"\/documentation\/dotdocument\/documentdetector\/document","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Document"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","type":"topic"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/topLeft":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"topLeft","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topLeft","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"title":"topLeft","type":"topic","url":"\/documentation\/dotdocument\/detectionposition\/topleft","abstract":[{"type":"text","text":"Top left corner point."}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/from(rectangle:)":{"title":"from(rectangle:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"fromRectangle:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/detectionposition\/from(rectangle:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/from(rectangle:)"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTDDetectionPosition"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/bottomLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/bottomRight","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/points","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topLeft","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/topRight"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/isEqual(_:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/mirrored()","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/rebased(parentRectangle:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/from(rectangle:)"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDDetectionPosition","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","op":"replace","value":"DOTDDetectionPosition"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1bottomLeft\/title","op":"replace","value":"bottomLeft"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1bottomLeft\/fragments","op":"replace","value":[{"text":"bottomLeft","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1topRight\/title","op":"replace","value":"topRight"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1topRight\/fragments","op":"replace","value":[{"kind":"identifier","text":"topRight"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1mirrored()\/title","op":"replace","value":"mirrored"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1mirrored()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1rebased(parentRectangle:)\/title","op":"replace","value":"rebasedWithParentRectangle:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1rebased(parentRectangle:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1points\/title","op":"replace","value":"points"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1points\/fragments","op":"replace","value":[{"text":"points","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1bottomRight\/title","op":"replace","value":"bottomRight"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1bottomRight\/fragments","op":"replace","value":[{"text":"bottomRight","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1topLeft\/title","op":"replace","value":"topLeft"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1topLeft\/fragments","op":"replace","value":[{"kind":"identifier","text":"topLeft"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1from(rectangle:)\/title","op":"replace","value":"fromRectangle:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1from(rectangle:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"}]}]}]}