{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotDocumentLibraryConfigurationModules) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class"]}],"abstract":[{"type":"text","text":"Document library module configuration."}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"title":"DotDocumentLibraryConfiguration.Modules","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"Modules","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode"],"generated":true}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration","abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","title":"DotDocumentLibraryConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","title":"barcode","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","title":"init(barcode:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}]}]}