{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/initwithdetectionposition:confidence:quality:handposition:handorientation:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","kind":"identifier"}],"title":"initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm(im)initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","symbolKind":"method","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/initWithDetectionPosition:confidence:quality:handPosition:handOrientation:"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithDetectionPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPDetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"},{"text":" *) ","kind":"text"},{"text":"detectionPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confidence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"quality:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"DOTPPalmQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"},{"text":" *) ","kind":"text"},{"text":"quality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"handPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPHandPosition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition"},{"text":") ","kind":"text"},{"text":"handPosition","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"handOrientation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPHandOrientation","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation"},{"text":") ","kind":"text"},{"text":"handOrientation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm/initWithDetectionPosition:confidence:quality:handPosition:handOrientation:":{"type":"topic","title":"initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/initwithdetectionposition:confidence:quality:handposition:handorientation:","kind":"symbol","navigatorTitle":[{"text":"initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/initWithDetectionPosition:confidence:quality:handPosition:handOrientation:","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandPosition","kind":"identifier"}],"role":"symbol","title":"HandPosition","url":"\/documentation\/dotpalmcore\/handposition","type":"topic","navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","abstract":[{"text":"Represents the position of a hand when detecting palm.","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"title":"DOTPPalmDetectorPalm","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"abstract":[{"text":"Result of the palm detection process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}],"url":"\/documentation\/dotpalmcore\/palmquality","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmQuality"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","title":"PalmQuality","abstract":[{"type":"text","text":"Palm quality."}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","title":"DetectionPosition","role":"symbol","abstract":[{"type":"text","text":"Position of the palm in the image."}],"url":"\/documentation\/dotpalmcore\/detectionposition","kind":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"url":"\/documentation\/dotpalmcore\/handorientation","title":"HandOrientation","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandOrientation","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"HandOrientation","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","abstract":[{"type":"text","text":"Represents the orientation of a hand when detecting palm."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title","op":"replace","value":"DOTPHandPosition"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments","op":"replace","value":[{"text":"DOTPHandPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPHandPosition"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","op":"replace","value":"DOTPPalmQuality"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments","op":"replace","value":[{"text":"DOTPPalmQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","op":"replace","value":"DOTPDetectionPosition"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title","op":"replace","value":"DOTPHandOrientation"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments","op":"replace","value":[{"text":"DOTPHandOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/navigatorTitle","op":"replace","value":[{"text":"DOTPHandOrientation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}