{"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"palmQuality","kind":"identifier"}],"navigatorTitle":[{"text":"palmQuality","kind":"identifier"}],"title":"palmQuality","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm(py)palmQuality"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/palmquality"]}],"abstract":[{"type":"text","text":"Palm quality."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"DOTPPalmQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"},{"text":" * ","kind":"text"},{"text":"palmQuality","kind":"identifier"},{"text":";","kind":"text"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/palmQuality"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","role":"symbol","abstract":[{"type":"text","text":"Result of the palm detection process."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","title":"DOTPPalmDetectorPalm","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm/palmQuality":{"abstract":[{"type":"text","text":"Palm quality."}],"fragments":[{"text":"palmQuality","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"palmQuality","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/palmquality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/palmQuality"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"role":"symbol","title":"PalmQuality","abstract":[{"text":"Palm quality.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmQuality","kind":"identifier"}],"navigatorTitle":[{"text":"PalmQuality","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmquality","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","value":"DOTPPalmQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments","value":[{"text":"DOTPPalmQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]}]}]}