{"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/quality","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/quality"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"]]},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"quality"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm(py)quality","modules":[{"name":"DotPalmCore"}],"symbolKind":"property","title":"quality","roleHeading":"Instance Property","fragments":[{"text":"quality","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTPPalmQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality"},{"kind":"text","text":" * "},{"kind":"identifier","text":"quality"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"abstract":[{"text":"Palm quality attributes.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm/quality":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/quality","kind":"symbol","fragments":[{"kind":"identifier","text":"quality"}],"abstract":[{"type":"text","text":"Palm quality attributes."}],"title":"quality","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/quality","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"url":"\/documentation\/dotpalmcore\/palmquality","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","title":"PalmQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmQuality"}],"navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}],"role":"symbol","abstract":[{"text":"Palm quality.","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","kind":"symbol","fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of the palm detection process."}],"title":"DOTPPalmDetectorPalm","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","value":"DOTPPalmQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]}]}]}