{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/dependencyIdentifiers"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator"]]},"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/dependencyidentifiers"]}],"sections":[],"metadata":{"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","title":"dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceOutOfBoundsValidator(py)dependencyIdentifiers","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"symbolKind":"property","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceOutOfBoundsValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","title":"FaceOutOfBoundsValidator","abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/dependencyIdentifiers":{"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/dependencyidentifiers","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","title":"FaceAutoCaptureController","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"dependencyIdentifiers","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"dependencyIdentifiers","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTFLFaceOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}]},{"value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1dependencyIdentifiers\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]}]}]}