{"sections":[],"metadata":{"navigatorTitle":[{"text":"bundleId","kind":"identifier"}],"roleHeading":"Instance Property","title":"bundleId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotSdk(py)bundleId"},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/bundleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotsdk\/bundleid"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Application Bundle ID."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/bundleId","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DotSdk":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","url":"\/documentation\/dotdocument\/dotsdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":"."}],"title":"DotSdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotSdk/bundleId":{"url":"\/documentation\/dotdocument\/dotsdk\/bundleid","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bundleId"}],"abstract":[{"type":"text","text":"Application Bundle ID."}],"title":"bundleId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/bundleId"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bundleId","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"bundleId"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"bundleId","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","value":"DotSdk"},{"op":"replace","value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1bundleId\/title","op":"replace","value":"bundleId"},{"op":"replace","value":[{"text":"bundleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1bundleId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}