{"abstract":[{"type":"text","text":"Deinitialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdk\/deinitialize()"]},{"paths":["\/documentation\/dotdocument\/dotsdk\/deinitialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method should be called on the background thread."}],"type":"paragraph"},{"name":"Throws","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" fails to deinitialize."}]}],"style":"note"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)deinitializeAndReturnError:","title":"deinitialize()","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/deinitialize()","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DotSdk/deinitialize()":{"type":"topic","url":"\/documentation\/dotdocument\/dotsdk\/deinitialize()","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"title":"deinitialize()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/deinitialize()","abstract":[{"type":"text","text":"Deinitialize "},{"type":"codeVoice","code":"DotSdk"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}]},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotDocument","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotSdk":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","url":"\/documentation\/dotdocument\/dotsdk","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"title":"DotSdk","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"deinitializeAndReturnError:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1deinitialize()\/title","value":"deinitializeAndReturnError:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}