{"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadSystemConstants","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/initializationFailed(internalError:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/licenseDataNotSet","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenIsNil","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/errorMessage","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/internalError"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/DotSdkError-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/Error-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"sections":[],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkError","doc:\/\/DotDocument\/10Foundation14LocalizedErrorP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/s5ErrorP","doc:\/\/DotDocument\/s8SendableP","doc:\/\/DotDocument\/s16SendableMetatypeP"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"enum","role":"symbol","title":"DotSdk.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"externalID":"s:7DotCore0A3SdkC5ErrorO","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"roleHeading":"Enumeration"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error"},"references":{"doc://DotDocument/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/DotDocument\/s5ErrorP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/LocalizedError-Implementations":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/localizederror-implementations","title":"LocalizedError Implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/LocalizedError-Implementations"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error","title":"DotSdk.Error","role":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/DotSdkError-Implementations":{"title":"DotSdkError Implementations","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/DotSdkError-Implementations","kind":"article","url":"\/documentation\/dotdocument\/dotsdk\/error\/dotsdkerror-implementations","role":"collectionGroup","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotSdkError":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkError"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkError","title":"DotSdkError","role":"symbol","url":"\/documentation\/dotdocument\/dotsdkerror","navigatorTitle":[{"kind":"identifier","text":"DotSdkError"}]},"doc://DotDocument/documentation/DotDocument/DotSdk":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","title":"DotSdk","role":"symbol","url":"\/documentation\/dotdocument\/dotsdk","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/DotDocument\/s16SendableMetatypeP","type":"unresolvable"},"doc://DotDocument/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","identifier":"doc:\/\/DotDocument\/10Foundation14LocalizedErrorP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/failedToLoadSystemConstants":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/failedtoloadsystemconstants","title":"DotSdk.Error.failedToLoadSystemConstants","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadSystemConstants"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/transactionCountingTokenIsNil":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/transactioncountingtokenisnil","title":"DotSdk.Error.transactionCountingTokenIsNil","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenIsNil"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenIsNil"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/errorMessage":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/errorMessage","url":"\/documentation\/dotdocument\/dotsdk\/error\/errormessage","title":"errorMessage","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/Error-Implementations":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/error-implementations","title":"Error Implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/Error-Implementations"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/initializationFailed(internalError:)":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/initializationfailed(internalerror:)","title":"DotSdk.Error.initializationFailed(internalError:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"initializationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/initializationFailed(internalError:)"},"doc://DotDocument/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/DotDocument\/s8SendableP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/internalError":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/internalerror","title":"internalError","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/internalError"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/transactionCountingTokenVerificationFailed(internalError:)":{"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)","kind":"symbol","title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenVerificationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/licenseDataNotSet":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/licensedatanotset","title":"DotSdk.Error.licenseDataNotSet","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseDataNotSet"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/licenseDataNotSet"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error/failedToLoadLibrary(libraryId:)":{"url":"\/documentation\/dotdocument\/dotsdk\/error\/failedtoloadlibrary(libraryid:)","title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadLibrary"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","op":"replace","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]}]}]}