{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdk\/getLibrary(libraryId:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdk"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"text":"DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"s:11DotDocument0A3SdkC10getLibrary9libraryIdAA0aE0_pSgAA0aeG0O_tF","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLibrary"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(pl)DotLibrary","text":"DotLibrary"},{"kind":"text","text":"?"}],"symbolKind":"method","modules":[{"name":"DotDocument"}],"title":"getLibrary(libraryId:)"},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/getlibrary(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibrary":{"type":"topic","abstract":[],"title":"DotLibrary","kind":"symbol","url":"\/documentation\/dotdocument\/dotlibrary","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdk/getLibrary(libraryId:)":{"type":"topic","role":"symbol","title":"getLibrary(libraryId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DotLibrary","preciseIdentifier":"c:@M@DotDocument@objc(pl)DotLibrary"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdk\/getLibrary(libraryId:)","url":"\/documentation\/dotdocument\/dotsdk\/getlibrary(libraryid:)","abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdk":{"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotsdk","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdk","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId":{"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"title":"DotLibraryId"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/title","op":"replace","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"value":"DotLibraryId","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}