{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Shared singleton instance."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdk\/shared"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdk\/shared"]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotSdk(cpy)shared","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"shared","kind":"identifier"}],"title":"shared","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotSdk","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"}],"role":"symbol","roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/shared"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","text":"DotSdk","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk"}]}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotSdk/shared":{"abstract":[{"text":"Shared singleton instance.","type":"text"}],"url":"\/documentation\/dotdocument\/dotsdk\/shared","navigatorTitle":[{"text":"shared","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/shared","title":"shared"},"doc://DotDocument/documentation/DotDocument/DotSdk":{"title":"DotSdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotsdk","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"shared","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"shared"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","text":"DotSdk","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"},{"text":" * ","kind":"text"},{"text":"shared","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1shared\/title","value":"shared"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk~1shared\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}