{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"cgImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" instance."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"variants":[{"paths":["\/documentation\/dotdocument\/imagefactory\/createbgrrawimage(cgimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/imagefactory\/createbgrrawimage(cgimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(cgImage:)"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory"]]},"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Type Method","title":"createBgrRawImage(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgrRawImageWithCgImage:"},"references":{"doc://DotDocument/documentation/DotDocument/Image":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotdocument\/image","abstract":[],"title":"Image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/ImageFactory":{"navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","kind":"symbol","title":"ImageFactory","url":"\/documentation\/dotdocument\/imagefactory","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}]},"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgrRawImage(cgImage:)":{"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"url":"\/documentation\/dotdocument\/imagefactory\/createbgrrawimage(cgimage:)","type":"topic","navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgrRawImage(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"role":"symbol","title":"createBgrRawImage(cgImage:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createBgrRawImageWithCgImage:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"cgImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}]}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" instance.","type":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgrRawImage(cgImage:)\/title","value":"createBgrRawImageWithCgImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}