{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Parsed MRZ of TD3."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td3"},{"text":": ","kind":"text"},{"text":"Td3MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone"]]},"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td3"},{"text":": ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone"},{"text":"?","kind":"text"}],"title":"td3","externalID":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone(py)td3","navigatorTitle":[{"kind":"identifier","text":"td3"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/machinereadablezone\/td3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/machinereadablezone\/td3"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/td3","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","title":"Td3MachineReadableZone","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"kind":"symbol","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","type":"topic","url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone/td3":{"kind":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone\/td3","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/td3","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"td3"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"td3","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"abstract":[{"text":"Parsed MRZ of TD3.","type":"text"}],"title":"td3"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"url":"\/documentation\/dotdocument\/machinereadablezone","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","title":"MachineReadableZone","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"td3","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"td3","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"DOTTd3MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"td3","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"value":"td3","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1td3\/title","op":"replace"},{"value":[{"text":"td3","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1td3\/fragments","op":"replace"},{"op":"replace","value":"DOTMachineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]}]}]}