{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFBaseFaceAutoCaptureConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","extendedModule":"DotFaceCore","title":"BaseFaceAutoCaptureViewController.Configuration"},"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"anchor":"Structures","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults"],"generated":true,"title":"Structures"},{"anchor":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/autoCapture","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/camera","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/common","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/faceLibraryComponent","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds"],"generated":true,"title":"Instance Properties"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"]]},"references":{"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/autoCapture":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/autoCapture","title":"autoCapture","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/autocapture"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/common":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/common","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/common","type":"topic","title":"common","abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"code":".init()","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/captureMode":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","text":"CaptureMode"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/capturemode","type":"topic","title":"captureMode","kind":"symbol","abstract":[{"text":"Capture mode. Default value is ","type":"text"},{"code":".autoCapture","type":"codeVoice"},{"text":".","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","type":"topic","title":"BaseFaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"kind":"symbol"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/camera":{"title":"camera","role":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/camera","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/camera"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","type":"topic","title":"BaseFaceAutoCaptureViewController.Configuration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/faceLibraryComponent":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/faceLibraryComponent","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","text":"FaceLibraryComponentConfiguration"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/facelibrarycomponent","type":"topic","title":"faceLibraryComponent","kind":"symbol","abstract":[{"text":"Configuration for face library components.","type":"text"}]},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:facelibrarycomponent:qualityattributethresholds:capturemode:)","type":"topic","title":"init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)","abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/init()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"text":"Create the face auto capture configuration with default values.","type":"text"}],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/init()","role":"symbol","title":"init()","kind":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults","type":"topic","title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/description","type":"topic","title":"description","kind":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","title":"qualityAttributeThresholds","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"qualityAttributeThresholds","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"codeVoice","code":".passiveLiveness"},{"type":"text","text":" preset."}],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/qualityattributethresholds"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","value":"DOTFBaseFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}