{"metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController(im)requestCaptureWithIsFacePresenceRequired:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"requestCapture(isFacePresenceRequired:)","symbolKind":"method","navigatorTitle":[{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false)","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"If true, the result will be captured only if a face is detected with defined quality attributes."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the result will be captured regardless of the face presence. Default is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"isFacePresenceRequired"}]}],"abstract":[{"text":"Request capture of the next detection.","type":"text"}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","title":"requestCapture(isFacePresenceRequired:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isFacePresenceRequired"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Request capture of the next detection."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","type":"topic","title":"BaseFaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"requestCaptureWithIsFacePresenceRequired:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isFacePresenceRequired","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"isFacePresenceRequired","content":[{"inlineContent":[{"type":"text","text":"If true, the result will be captured only if a face is detected with defined quality attributes."},{"type":"text","text":" "},{"type":"text","text":"Otherwise, the result will be captured regardless of the face presence. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"requestCaptureWithIsFacePresenceRequired:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments"},{"op":"replace","value":"DOTFBaseFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle"}]}]}