{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/facedetector\/face\/quality"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/quality","interfaceLanguage":"swift"},"abstract":[{"text":"Face quality attributes. Only attributes specified in ","type":"text"},{"type":"codeVoice","code":"FaceDetectionQuery"},{"text":" are evaluated.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","text":"FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceCore0B8DetectorC0B0C7qualityAA0B7QualityCvp","title":"quality"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"type":"topic","url":"\/documentation\/dotfacecore\/facedetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","title":"FaceDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"kind":"symbol","url":"\/documentation\/dotfacecore\/facequality","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"title":"FaceQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"url":"\/documentation\/dotfacecore\/facedetector\/face","type":"topic","abstract":[{"type":"text","text":"Detected face in the image."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","kind":"symbol","title":"FaceDetector.Face","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"navigatorTitle":[{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/quality":{"type":"topic","abstract":[{"type":"text","text":"Face quality attributes. Only attributes specified in "},{"type":"codeVoice","code":"FaceDetectionQuery"},{"type":"text","text":" are evaluated."}],"title":"quality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/quality","url":"\/documentation\/dotfacecore\/facedetector\/face\/quality","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","kind":"typeIdentifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","op":"replace"},{"value":"DOTFFaceQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}