{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/sex"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","roleHeading":"Instance Property","title":"sex","navigatorTitle":[{"text":"sex","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTTd1MachineReadableZone(py)sex","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"sex","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/sex"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/sex"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/sex":{"kind":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone\/sex","title":"sex","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/sex","navigatorTitle":[{"text":"sex","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzreader","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone":{"url":"\/documentation\/dotdocument\/td1machinereadablezone","kind":"symbol","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","type":"topic","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td1MachineReadableZone"}],"title":"Td1MachineReadableZone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"type":"topic","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzelement","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"sex","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sex"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"text":" * ","kind":"text"},{"text":"sex","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1sex\/title","op":"replace","value":"sex"},{"op":"replace","value":[{"kind":"identifier","text":"sex"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1sex\/fragments"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]}]}]}