{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult\/init(bgrRawImage:face:content:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"},{"kind":"text","text":", "},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult"]]},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBgrRawImage:face:content:"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}],"title":"init(bgrRawImage:face:content:)","modules":[{"name":"DotFaceCore"}],"symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessResult(im)initWithBgrRawImage:face:content:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessresult\/init(bgrrawimage:face:content:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessresult\/init(bgrrawimage:face:content:)"]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","kind":"symbol","title":"Face","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/face","abstract":[{"type":"text","text":"Detected face in the image."}],"fragments":[{"kind":"identifier","text":"Face"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessResult":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult","role":"symbol","navigatorTitle":[{"text":"MultiRangeLivenessResult","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessResult","kind":"identifier"}],"title":"MultiRangeLivenessResult","abstract":[{"type":"text","text":"The final result of the Multi-Range Liveness process."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessresult","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"url":"\/documentation\/dotfacecore\/facedetector\/face","role":"symbol","navigatorTitle":[{"text":"Face","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"abstract":[{"type":"text","text":"Detected face in the image."}],"title":"FaceDetector.Face","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessResult/init(bgrRawImage:face:content:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult\/init(bgrRawImage:face:content:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBgrRawImage:face:content:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":", "},{"text":"face","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":")","kind":"text"}],"title":"init(bgrRawImage:face:content:)","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessresult\/init(bgrrawimage:face:content:)","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"url":"\/documentation\/dotfacecore\/bgrrawimage","role":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"title":"BgrRawImage","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithBgrRawImage:face:content:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBgrRawImage:face:content:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBgrRawImage:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","text":"DOTBgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"bgrRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","text":"Face","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"face"},{"kind":"text","text":" "},{"kind":"identifier","text":"content:"},{"kind":"text","text":"("},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"content"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"op":"replace"},{"value":"DOTFMultiRangeLivenessResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessResult"}],"op":"replace"},{"value":"initWithBgrRawImage:face:content:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult~1init(bgrRawImage:face:content:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult~1init(bgrRawImage:face:content:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBgrRawImage:face:content:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","op":"replace","value":"DOTBgrRawImage"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}