{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/initialize(license:)"},"variants":[{"paths":["\/documentation\/dotnfc\/dotlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotlibrary\/initialize(license:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotNfc@objc(pl)DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","modules":[{"name":"DotNfc"}],"required":true,"roleHeading":"Instance Method","externalID":"c:@M@DotNfc@objc(pl)DotLibrary(im)initializeWithLicense:error:","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"title":"initialize(license:)","symbolKind":"method"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotlibrary","kind":"symbol","title":"DotLibrary","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary/initialize(license:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/initialize(license:)","url":"\/documentation\/dotnfc\/dotlibrary\/initialize(license:)","role":"symbol","required":true,"abstract":[],"type":"topic","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"kind":"symbol","title":"initialize(license:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.1.0"}],"type":"topic","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","role":"collection","title":"DotNfc"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initializeWithLicense:error:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initializeWithLicense:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@DotNfc@objc(pl)DotSdkLicenseProxyProtocol","text":"id<DotSdkLicenseProxyProtocol>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"license"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments"},{"op":"replace","value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1initialize(license:)\/title","op":"replace","value":"initializeWithLicense:error:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1initialize(license:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}