{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/verifyIsActive()"},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"method","role":"symbol","title":"verifyIsActive()","required":true,"navigatorTitle":[{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotNfc@objc(pl)DotLibrary(im)verifyIsActiveAndReturnError:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verifyIsActive","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotlibrary\/verifyisactive()"]},{"paths":["\/documentation\/dotnfc\/dotlibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyIsActive"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary/verifyIsActive()":{"role":"symbol","title":"verifyIsActive()","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/verifyIsActive()","url":"\/documentation\/dotnfc\/dotlibrary\/verifyisactive()","required":true,"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"verifyIsActive","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary":{"url":"\/documentation\/dotnfc\/dotlibrary","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"verifyIsActiveAndReturnError:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"verifyIsActiveAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1verifyIsActive()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1verifyIsActive()\/fragments"},{"op":"replace","value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/title"},{"op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}