{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/min","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble(py)min","navigatorTitle":[{"text":"min","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"min","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"symbolKind":"property","role":"symbol","title":"min","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}]},"sections":[],"abstract":[{"text":"Minimal interval value.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervaldouble\/min"]},{"paths":["\/documentation\/dotdocument\/intervaldouble\/min"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"min"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.14.1"}],"url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/intervaldouble","type":"topic","title":"IntervalDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/min":{"kind":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/min","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/min","abstract":[{"text":"Minimal interval value.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"min"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","title":"min","type":"topic","navigatorTitle":[{"kind":"identifier","text":"min"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"min","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"min"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"min","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1min\/title","op":"replace","value":"min"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1min\/fragments","value":[{"kind":"identifier","text":"min"}]}]}]}