{"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererror\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/Error-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/localizedDescription"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"DotNfc"}],"role":"collectionGroup","title":"Error Implementations"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError/localizedDescription":{"role":"symbol","title":"localizedDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/localizedDescription","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror\/localizeddescription"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError":{"role":"symbol","title":"NfcTravelDocumentReaderError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderError"}],"abstract":[{"type":"text","text":"NFC reading error."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderError"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError\/title","value":"DOTNNfcTravelDocumentReaderError"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}