{"variants":[{"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/dotsdkerror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/DotSdkError-Implementations"},"kind":"article","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error"]]},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/errorDescription"],"generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/composeWithInternalError()"],"generated":true,"title":"Instance Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"collectionGroup","title":"DotSdkError Implementations","roleHeading":"API Collection","modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error/errorDescription":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/errorDescription","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/errordescription","abstract":[],"kind":"symbol","type":"topic","title":"errorDescription","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error","abstract":[],"title":"FaceLibraryComponentConfiguration.Error","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","abstract":[{"text":"Configuration for face library components.","type":"text"}],"title":"FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/description","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/description","abstract":[],"kind":"symbol","type":"topic","title":"description","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error/composeWithInternalError()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/composeWithInternalError()","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/composewithinternalerror()","abstract":[],"kind":"symbol","type":"topic","title":"composeWithInternalError()","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}