{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration"]]},"abstract":[{"text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation. Default is ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/commonconfiguration\/sessiontoken"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/commonconfiguration\/sessiontoken"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration\/sessionToken","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration(py)sessionToken","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sessionToken"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"sessionToken","symbolKind":"property","modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","url":"\/documentation\/dotfacecore\/commonconfiguration","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration/sessionToken":{"abstract":[{"type":"text","text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation. Default is "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration\/sessionToken","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/commonconfiguration\/sessiontoken","type":"topic","role":"symbol","navigatorTitle":[{"text":"sessionToken","kind":"identifier"}],"title":"sessionToken","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"sessionToken","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sessionToken"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sessionToken"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration~1sessionToken\/title","value":"sessionToken","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration~1sessionToken\/fragments","value":[{"kind":"identifier","text":"sessionToken"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}