{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/minconfidence:error:"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"minConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTWrappedDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":" *) ","kind":"text"},{"text":"minConfidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","title":"minConfidence:error:","fragments":[{"text":"- ","kind":"text"},{"text":"minConfidence:error:","kind":"identifier"}],"navigatorTitle":[{"text":"minConfidence:error:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder(im)minConfidence:error:","symbolKind":"method"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder/minConfidence:error:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"minConfidence:error:","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/minconfidence:error:","navigatorTitle":[{"text":"minConfidence:error:","kind":"identifier"}],"title":"minConfidence:error:","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder":{"url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder","type":"topic","title":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","role":"symbol","kind":"symbol","fragments":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble":{"url":"\/documentation\/dotpalmcore\/wrappeddouble","title":"WrappedDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","kind":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/fragments"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/navigatorTitle"}]}]}