{"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(magnifEyeLivenessViewControllerViewDidDisappear:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidDisappear(_:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidDisappear:"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","platforms":[],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"magnifEyeLivenessViewControllerViewDidDisappear(_:)","externalID":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessViewControllerViewDidDisappear:"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"title":"MagnifEyeLivenessViewController","deprecated":true,"type":"topic","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate":{"type":"topic","title":"MagnifEyeLivenessViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate","abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate","deprecated":true},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidDisappear(_:)":{"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdiddisappear(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidDisappear:"}],"title":"magnifEyeLivenessViewControllerViewDidDisappear(_:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"deprecated":true,"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"magnifEyeLivenessViewControllerViewDidDisappear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidDisappear:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","text":"DOTFMagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFMagnifEyeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidDisappear(_:)\/title","value":"magnifEyeLivenessViewControllerViewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewDidDisappear:","kind":"identifier"}]}]}]}