{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DotDocumentLibraryConfigurationModules) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/modules-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","role":"symbol","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"title":"DotDocumentLibraryConfiguration.Modules"},"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"],"title":"Initializers"},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode"]}],"abstract":[{"type":"text","text":"Document library module configuration."}],"references":{"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration","title":"DotDocumentLibraryConfiguration","type":"topic","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?)","kind":"text"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","title":"init(barcode:)","type":"topic"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library module configuration."}],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","type":"topic","navigatorTitle":[{"text":"Modules","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?","kind":"text"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","title":"barcode","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/title","op":"replace","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace"}]}]}