{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/!=(_:_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/placeholdertype\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"metadata":{"modules":[{"relatedModules":["Swift"],"name":"DotFingersCore"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotFingersCore@E@DOTFGPlaceholderType","extendedModule":"Swift","symbolKind":"op","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"!=(_:_:)","role":"symbol","roleHeading":"Operator"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfingerscore\/placeholdertype\/!=(_:_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotfingerscore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType","title":"PlaceholderType","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTFGPlaceholderType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}