{"metadata":{"modules":[{"name":"DotFingersCore"}],"title":"Equatable Implementations","roleHeading":"API Collection","role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/!=(_:_:)"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/Equatable-Implementations"},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/placeholdertype\/equatable-implementations"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotfingerscore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType","title":"PlaceholderType","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfingerscore\/placeholdertype\/!=(_:_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/title","value":"DOTFGPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}]}]}]}