{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/right","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/placeholdertype\/right"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/placeholdertype\/right"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Right hand fingers placeholder."}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@E@DOTFGPlaceholderType@DOTFGPlaceholderTypeRight","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"title":"PlaceholderType.right","role":"symbol","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DOTFGPlaceholderTypeRight"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/right":{"url":"\/documentation\/dotfingerscore\/placeholdertype\/right","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/right","title":"PlaceholderType.right","role":"symbol","abstract":[{"type":"text","text":"Right hand fingers placeholder."}],"navigatorTitle":[{"text":"DOTFGPlaceholderTypeRight","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotfingerscore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType","title":"PlaceholderType","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFGPlaceholderTypeRight","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTFGPlaceholderTypeRight","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTFGPlaceholderTypeRight","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFGPlaceholderTypeRight","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType~1right\/title"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholderTypeRight"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType~1right\/fragments"},{"value":"DOTFGPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/title"},{"value":[{"text":"DOTFGPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/navigatorTitle"}]}]}