{"metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:6DotNfc24CardAccessNumberPasswordC5ErrorO","title":"composeWithInternalError()","extendedModule":"DotCore","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"composeWithInternalError"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.composeWithInternalError()","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/composeWithInternalError()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/DotSdkError-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"composeWithInternalError"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/composewithinternalerror()"]}],"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/DotSdkError-Implementations":{"kind":"article","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/dotsdkerror-implementations","title":"DotSdkError Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/DotSdkError-Implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic","title":"CardAccessNumberPassword.Error"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","role":"symbol","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CardAccessNumberPassword"}],"title":"CardAccessNumberPassword","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/composeWithInternalError()":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/composeWithInternalError()","role":"symbol","type":"topic","kind":"symbol","title":"composeWithInternalError()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"composeWithInternalError"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/composewithinternalerror()"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol","title":"NfcTravelDocumentReader","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}