{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator"]]},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooHighValidator(im)init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","role":"symbol","symbolKind":"init","modules":[{"name":"DotDocument"}]},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/init()":{"abstract":[{"type":"text","text":"Initialize with default threshold."}],"title":"init()","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/init()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init()"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"role":"symbol","type":"topic","title":"BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","kind":"symbol","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","value":"DOTDBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}]}]}]}