{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/description","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration"]]},"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)description","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","title":"description"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/description"]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/description"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1description\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}