{"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator\/validate(faceautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator\/validate(faceautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"faceAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"text":"Current frame parameters.","type":"text"}]}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" for the failed validation and ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" for the successful validation.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Validate current frame parameters.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotFaceLite"}],"title":"validate(faceAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true,"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureFrameParametersValidator(im)validateWithFaceAutoCaptureFrameParameters:","navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator\/validate(faceAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"abstract":[{"text":"Information from the detection process about the detected face.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"title":"FaceAutoCaptureFrameParameters","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParametersValidator/validate(faceAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator\/validate(faceautocaptureframeparameters:)","abstract":[{"type":"text","text":"Validate current frame parameters."}],"type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator\/validate(faceAutoCaptureFrameParameters:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}],"title":"validate(faceAutoCaptureFrameParameters:)"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParametersValidator":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParametersValidator"}],"title":"FaceAutoCaptureFrameParametersValidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator","url":"\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParametersValidator"}],"abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"validateWithFaceAutoCaptureFrameParameters:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLFaceAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"faceAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current frame parameters."}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" for the failed validation and ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" for the successful validation.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"DOTFLFaceAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/navigatorTitle","op":"replace"},{"value":"validateWithFaceAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator~1validate(faceAutoCaptureFrameParameters:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments","op":"replace"},{"value":"DOTFLFaceAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}