{"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLicenseBytes:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"licenseBytes"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","text":"Libraries","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"libraries"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingToken:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"transactionCountingToken"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkConfiguration":{"title":"DotSdkConfiguration","fragments":[{"text":"DotSdkConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"text","text":"DotSdk"},{"type":"text","text":" configuration."}],"url":"\/documentation\/dotfingerscore\/dotsdkconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkConfiguration/initWithLicenseBytes:libraries:transactionCountingToken:":{"url":"\/documentation\/dotfingerscore\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:"},"doc://DotFingersCore/documentation/DotFingersCore/Libraries":{"url":"\/documentation\/dotfingerscore\/libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"title":"Libraries","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"}},"variantOverrides":[{"patch":[{"value":"Libraries","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/fragments","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/navigatorTitle","value":[{"text":"Libraries","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}