{"metadata":{"role":"symbol","title":"result","symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult"},{"text":"?","kind":"text"}],"externalID":"s:11DotDocument0B18AutoCaptureUiStateC7RunningC6resultAA0bcD6ResultCSgvp","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/result"},"kind":"symbol","abstract":[{"text":"Result. If the process has not finished, this will be ","type":"text"},{"type":"codeVoice","code":"null"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/running\/result"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"kind":"symbol","type":"topic","title":"DocumentAutoCaptureUiState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureuistate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Running"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","title":"DocumentAutoCaptureUiState.Running","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running","role":"symbol","abstract":[{"type":"text","text":"Running state."}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/result":{"abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"codeVoice","code":"null"},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/result","title":"result","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/result","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","url":"\/documentation\/dotdocument\/documentautocaptureresult","role":"symbol","title":"DocumentAutoCaptureResult","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTDDocumentAutoCaptureUiState","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle","op":"replace"},{"value":"DOTDDocumentAutoCaptureResult","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}