{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules"]]},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:transformation:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithDetection:transformation:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithDetection:transformation:","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(im)initWithDetection:transformation:","modules":[{"name":"DotFaceLite"}],"symbolKind":"method","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"text":"transformation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"transformation"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:"},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersTransformationModuleConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"title":"DotFingersTransformationModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"url":"\/documentation\/dotfacelite\/dotfingerstransformationmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfigurationModules/initWithDetection:transformation:":{"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:","fragments":[{"kind":"text","text":"- "},{"text":"initWithDetection:transformation:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDetection:transformation:"}],"title":"initWithDetection:transformation:","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","abstract":[],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersDetectionModuleConfiguration":{"url":"\/documentation\/dotfacelite\/dotfingersdetectionmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFingersDetectionModuleConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersDetectionModuleConfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfigurationModules":{"title":"DotFingersLibraryConfigurationModules","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfigurationmodules","role":"symbol","fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules","abstract":[{"type":"text","text":"Fingers library module configuration."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersTransformationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/title"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/fragments"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersDetectionModuleConfiguration\/title","op":"replace","value":"DotFingersDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersDetectionModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]}]}]}