{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules\/transformation","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"transformation","role":"symbol","symbolKind":"property","fragments":[{"text":"transformation","kind":"identifier"}],"navigatorTitle":[{"text":"transformation","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)transformation"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfigurationmodules\/transformation"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfigurationModules":{"title":"DotFingersLibraryConfigurationModules","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfigurationmodules","role":"symbol","fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules","abstract":[{"type":"text","text":"Fingers library module configuration."}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfigurationModules/transformation":{"fragments":[{"kind":"identifier","text":"transformation"}],"kind":"symbol","title":"transformation","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfigurationModules\/transformation","abstract":[],"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfigurationmodules\/transformation","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersTransformationModuleConfiguration":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"title":"DotFingersTransformationModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"url":"\/documentation\/dotfacelite\/dotfingerstransformationmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]}]}]}