{"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":" = 0.06) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(im)initWithModules:faceDetectionConfidenceThreshold:error:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"title":"init(modules:faceDetectionConfidenceThreshold:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"type":"topic","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"role":"symbol","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"title":"DotFaceLibraryConfigurationModules","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","type":"topic","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","abstract":[{"type":"text","text":"Face library module configuration."}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"kind":"symbol","type":"topic","title":"init(modules:faceDetectionConfidenceThreshold:)","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class":{"type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"role":"symbol","kind":"symbol","title":"DotFaceLibraryConfiguration.Modules","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithModules:faceDetectionConfidenceThreshold:error:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithModules:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","text":"DotFaceLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modules"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectionConfidenceThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"kind":"internalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithModules:faceDetectionConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments"}]}]}