{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"]]},"sections":[],"abstract":[{"text":"Top left corner point.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/detectionposition\/topleft"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/detectionposition\/topleft"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topLeft","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topLeft"},{"text":": ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"topLeft","kind":"identifier"}],"title":"topLeft","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition(py)topLeft"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","title":"PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"role":"symbol","type":"topic","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/topLeft":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topLeft","abstract":[{"type":"text","text":"Top left corner point."}],"kind":"symbol","navigatorTitle":[{"text":"topLeft","kind":"identifier"}],"title":"topLeft","url":"\/documentation\/dotpalmcore\/detectionposition\/topleft","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/detectionposition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","title":"DetectionPosition","type":"topic","abstract":[{"type":"text","text":"Position of the palm in the image."}]},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","role":"symbol","title":"PointDouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"url":"\/documentation\/dotpalmcore\/pointdouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"topLeft"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"topLeft","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"topLeft","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPPalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1topLeft\/title","value":"topLeft","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1topLeft\/fragments","value":[{"text":"topLeft","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","value":"DOTPDetectionPosition"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}