{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/validators","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validators","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator","text":"FaceAutoCaptureDetectionValidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class"]]},"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"validators","kind":"identifier"},{"text":": [","kind":"text"},{"text":"FaceAutoCaptureDetectionValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator"},{"text":"]","kind":"text"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC10validatorsSayAA0bdE18DetectionValidator_pGvp","title":"validators","role":"symbol"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/validators"]}],"abstract":[{"type":"text","text":"Array of validators which will be used to validate the face detection result."}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/validators":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validators","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator","text":"FaceAutoCaptureDetectionValidator","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/validators","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/validators","abstract":[{"type":"text","text":"Array of validators which will be used to validate the face detection result."}],"title":"validators","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","title":"FaceAutoCaptureController.Configuration","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","title":"FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"type":"text","text":"version: 8.2.0"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"title":"FaceAutoCaptureDetectionValidator","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","navigatorTitle":[{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Use this protocol to create face validators.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"value":"DOTFLFaceAutoCaptureDetectionValidator","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments","op":"replace"}]}]}