{"abstract":[{"text":"Process an input image or video frame and update the state.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","text":"BgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"ProcessingResult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Input image.","type":"text"}],"type":"paragraph"}],"name":"bgraRawImage"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image timestamp.","type":"text"}]}],"name":"timestampMillis"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The result of processing of the input image.","type":"text"}]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Throws","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error if you call this method after the face auto capture process has finished."}]}],"type":"aside","style":"note"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/process(bgrarawimage:timestampmillis:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/process(bgrarawimage:timestampmillis:)"]}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use process(sample:) instead."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(bgraRawImage:timestampMillis:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"platforms":[],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureController(im)processWithBgraRawImage:timestampMillis:error:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"processWithBgraRawImage:timestampMillis:error:"}],"title":"process(bgraRawImage:timestampMillis:)"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/process(bgraRawImage:timestampMillis:)":{"deprecated":true,"title":"process(bgraRawImage:timestampMillis:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(bgraRawImage:timestampMillis:)","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/process(bgrarawimage:timestampmillis:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult"}],"abstract":[{"type":"text","text":"Process an input image or video frame and update the state."}],"navigatorTitle":[{"text":"processWithBgraRawImage:timestampMillis:error:","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult":{"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerProcessingResult"}],"abstract":[{"type":"text","text":"The result returned from the processing of one image during the face auto capture process."}],"title":"DOTFLFaceAutoCaptureControllerProcessingResult","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"url":"\/documentation\/dotfacelite\/bgrarawimage","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","title":"BgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult":{"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"title":"FaceAutoCaptureController.ProcessingResult","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","abstract":[{"text":"The result returned from the processing of one image during the face auto capture process.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 8.17.1","type":"text"}],"title":"DotFaceLite","role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"processWithBgraRawImage:timestampMillis:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"processWithBgraRawImage:timestampMillis:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTFLFaceAutoCaptureControllerProcessingResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerProcessingResult","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult"},{"text":" *) ","kind":"text"},{"text":"processWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timestampMillis:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"timestampMillis","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image.","type":"text"}]}]},{"name":"timestampMillis","content":[{"type":"paragraph","inlineContent":[{"text":"Input image timestamp.","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The result of processing of the input image."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"processWithBgraRawImage:timestampMillis:error:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithBgraRawImage:timestampMillis:error:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/fragments"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/navigatorTitle"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"}]}]}