{"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"role":"symbol","title":"documentCode","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)documentCode"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/documentCode"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"documentCode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/documentcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/documentcode"]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.14.1"}],"url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone/documentCode":{"abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone\/documentcode","title":"documentCode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/documentCode","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzelement","title":"MrzElement","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"documentCode","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"documentCode","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentCode"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1documentCode\/title","value":"documentCode","op":"replace"},{"value":[{"kind":"identifier","text":"documentCode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1documentCode\/fragments","op":"replace"},{"op":"replace","value":"DOTMrzElement","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]}]}]}