{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfaceverificationmoduleprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfaceverificationmoduleprotocol"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleProtocol","interfaceLanguage":"swift"},"metadata":{"symbolKind":"protocol","modules":[{"name":"DotFaceCore"}],"title":"DotFaceVerificationModuleProtocol","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceVerificationModuleProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceVerificationModuleProtocol","kind":"identifier"}],"roleHeading":"Protocol"},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","text":"DotFaceModule","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceVerificationModuleProtocol":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleProtocol","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/dotfaceverificationmoduleprotocol","type":"topic","title":"DotFaceVerificationModuleProtocol","navigatorTitle":[{"text":"DotFaceVerificationModuleProtocol","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleProtocol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","url":"\/documentation\/dotfacecore\/dotfacemodule","type":"topic","title":"DotFaceModule","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModule"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModule"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"DotFaceVerificationModuleProtocol"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleProtocol"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleProtocol"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","text":"DotFaceModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"text":">","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleProtocol\/title","op":"replace","value":"DotFaceVerificationModuleProtocol"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleProtocol"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleProtocol\/navigatorTitle","op":"replace","value":[{"text":"DotFaceVerificationModuleProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","op":"replace","value":"DotFaceModule"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/navigatorTitle","op":"replace","value":[{"text":"DotFaceModule","kind":"identifier"}]}]}]}