{"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/init(corner:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/corner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/hash"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFWrappedEyeGazeLivenessCorner) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedEyeGazeLivenessCorner"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","title":"WrappedEyeGazeLivenessCorner","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"class","roleHeading":"Class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"code":"EyeGazeLivenessCorner","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/init(corner:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"corner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EyeGazeLivenessCorner","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCorner:"}],"title":"init(corner:)","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/init(corner:)","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/init(corner:)"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/hash":{"title":"hash","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/hash","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/hash","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/isEqual(_:)":{"type":"topic","abstract":[],"title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/isequal(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/isEqual(_:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","title":"WrappedEyeGazeLivenessCorner","type":"topic","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"EyeGazeLivenessCorner"},{"type":"text","text":"."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/corner":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/corner","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/corner","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"corner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner"}],"navigatorTitle":[{"kind":"identifier","text":"corner"}],"title":"corner","kind":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner/description":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/description","abstract":[],"title":"description","type":"topic","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFWrappedEyeGazeLivenessCorner"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/corner","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/hash"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/init(corner:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1init(corner:)\/title","op":"replace","value":"initWithCorner:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1init(corner:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCorner:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title","op":"replace","value":"DOTFWrappedEyeGazeLivenessCorner"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/navigatorTitle","op":"replace","value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1corner\/title","op":"replace","value":"corner"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1corner\/fragments","op":"replace","value":[{"text":"corner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}