{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/face","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturedetection\/face"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturedetection\/face"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Face detection result.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"face","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier","text":"FaceDetector"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"},{"text":"?","kind":"text"}],"title":"face","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection(py)face","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"face","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","text":"Face","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.7.1"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacelite\/faceautocapturedetection","title":"FaceAutoCaptureDetection","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"type":"topic","abstract":[{"type":"text","text":"The result of the image processing during the face auto capture process."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"title":"FaceAutoCaptureController","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"abstract":[{"type":"text","text":"Detected face."}],"url":"\/documentation\/dotfacelite\/facedetector\/face","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Face","kind":"identifier"}],"navigatorTitle":[{"text":"Face","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","role":"symbol","title":"FaceDetector.Face"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"url":"\/documentation\/dotfacelite\/dotflfacedetectorface","fragments":[{"text":"DOTFLFaceDetectorFace","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","title":"DOTFLFaceDetectorFace","abstract":[{"type":"text","text":"Detected face."}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"title":"FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector","type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection/face":{"navigatorTitle":[{"kind":"identifier","text":"face"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"face","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection\/face","type":"topic","role":"symbol","title":"face","abstract":[{"type":"text","text":"Face detection result."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/face","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","role":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","title":"MagnifEyeLivenessViewController"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"face","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"face"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace","text":"DOTFLFaceDetectorFace","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace"},{"text":" * ","kind":"text"},{"text":"face","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTFLFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"value":"face","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1face\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1face\/fragments","value":[{"text":"face","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}