{"metadata":{"role":"symbol","title":"configuration","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureController(py)configuration","symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Configuration","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/configuration-swift.property","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Current configuration."}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.property"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"role":"symbol","type":"topic","title":"FaceAutoCaptureController.Configuration","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/configuration-swift.property":{"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.property","title":"configuration","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/configuration-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"abstract":[{"text":"Current configuration.","type":"text"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerConfiguration":{"kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"title":"DOTFLFaceAutoCaptureControllerConfiguration","role":"symbol","fragments":[{"text":"DOTFLFaceAutoCaptureControllerConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"configuration"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFLFaceAutoCaptureControllerConfiguration","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration"},{"kind":"text","text":" * "},{"text":"configuration","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"op":"replace","value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1configuration-swift.property\/fragments"}]}]}