{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"metadata":{"externalID":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC","extendedModule":"DotFaceLite","symbolKind":"class","modules":[{"name":"DotFaceLite"}],"title":"FaceAutoCaptureController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"kind":"symbol","topicSections":[{"generated":true,"title":"Structures","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Defaults"],"anchor":"Structures"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:detectionArea:validators:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/autoCapture","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/common","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/detectionArea","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/validators"],"anchor":"Instance-Properties"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error"],"anchor":"Enumerations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLFaceAutoCaptureControllerConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/description","abstract":[],"title":"description","kind":"symbol","type":"topic","role":"symbol"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/detectionArea":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionArea","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/detectionarea","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/detectionArea","abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the face detection."}],"title":"detectionArea","kind":"symbol","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/common":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/common","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/common","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"codeVoice","code":".init()"},{"type":"text","text":"."}],"title":"common","kind":"symbol","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"title":"FaceAutoCaptureController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/validators":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/validators","abstract":[{"text":"Array of validators which will be used to validate the face detection result.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validators","kind":"identifier"},{"text":": [","kind":"text"},{"text":"FaceAutoCaptureFrameParametersValidator","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureFrameParametersValidator"},{"text":"]","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/validators","title":"validators","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/autoCapture":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/autoCapture","title":"autoCapture","role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/autocapture","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"}],"kind":"symbol","abstract":[{"text":"Configuration for auto capture components.","type":"text"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Defaults":{"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Defaults","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"type":"topic","title":"FaceAutoCaptureController.Configuration.Defaults"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/init(common:autoCapture:detectionArea:validators:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","text":"CommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier","text":"AutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureFrameParametersValidator","kind":"typeIdentifier","text":"FaceAutoCaptureFrameParametersValidator"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/init(common:autocapture:detectionarea:validators:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:detectionArea:validators:)","abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"title":"init(common:autoCapture:detectionArea:validators:)","kind":"symbol","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","title":"FaceAutoCaptureController.Configuration","abstract":[{"text":"Configuration of the face auto capture non-UI component.","type":"text"}]},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/Error":{"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"FaceAutoCaptureController.Configuration.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/Error","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/error","kind":"symbol"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]}]}]}