{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(sample:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"title":"process(sample:)","roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureController(im)processWithSample:error:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"process","kind":"identifier"},{"kind":"text","text":"("},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Sample","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC6SampleC","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC","kind":"typeIdentifier","text":"ProcessingResult"}]},"abstract":[{"type":"text","text":"Process an input sample and update the state."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"text":"sample","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC6SampleC","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample","text":"Sample"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"sample","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input sample."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of processing of the input sample."}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"content":[{"inlineContent":[{"text":"If you call this method after the face auto capture process has finished, it will throw an error.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note","name":"Throws"}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/process(sample:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/process(sample:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Sample":{"title":"FaceAutoCaptureController.Sample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Sample","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"text":"version: 8.12.1","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult","type":"topic","fragments":[{"text":"DOTFLFaceAutoCaptureControllerProcessingResult","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult","kind":"symbol","abstract":[{"type":"text","text":"The result returned from the processing of one image during the face auto capture process."}],"title":"DOTFLFaceAutoCaptureControllerProcessingResult","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/process(sample:)":{"abstract":[{"text":"Process an input sample and update the state.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(sample:)","navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"title":"process(sample:)","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/process(sample:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC6SampleC","text":"Sample","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample":{"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerSample"}],"abstract":[{"text":"The data sample captured at specific time which serves as an input for the face auto capture process.","type":"text"}],"title":"DOTFLFaceAutoCaptureControllerSample"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"title":"FaceAutoCaptureController","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ProcessingResult"}],"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult","kind":"symbol","abstract":[{"type":"text","text":"The result returned from the processing of one image during the face auto capture process."}],"title":"FaceAutoCaptureController.ProcessingResult","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"processWithSample:error:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"processWithSample:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult","text":"DOTFLFaceAutoCaptureControllerProcessingResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerProcessingResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"processWithSample:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerSample","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample","text":"DOTFLFaceAutoCaptureControllerSample"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sample"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"processWithSample:error:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(sample:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(sample:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"processWithSample:error:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace","value":"DOTFLFaceAutoCaptureController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace"}]}]}