{"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped\/init(phase:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped"]]},"metadata":{"title":"init(phase:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePhase","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC5phaseAeC_tcfc","role":"symbol","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped\/init(phase:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped":{"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped","title":"PalmAutoCapturePhase.Wrapped","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped/init(phase:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped\/init(phase:)","title":"init(phase:)","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped\/init(phase:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"text":"PalmAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCapturePhase"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","title":"PalmAutoCapturePhase","url":"\/documentation\/dotpalmcore\/palmautocapturephase","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","op":"replace","value":"DOTPPalmAutoCapturePhase"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}