{"metadata":{"navigatorTitle":[{"text":"expressionNeutral","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"title":"expressionNeutral","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)expressionNeutral","fragments":[{"text":"expressionNeutral","kind":"identifier"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/expressionNeutral"},"variants":[{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/expressionneutral"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expressionNeutral"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceExpressionNeutralModuleConfiguration":{"role":"symbol","type":"topic","title":"DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration","abstract":[{"type":"text","text":"Face expression neutral module."}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","abstract":[{"text":"Face library module configuration.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules/expressionNeutral":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/expressionneutral","role":"symbol","type":"topic","fragments":[{"text":"expressionNeutral","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/expressionNeutral","title":"expressionNeutral"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/title","op":"replace","value":"DotFaceExpressionNeutralModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]}]}]}