{"variants":[{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg4additionalidentificationfeatureirises"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg4additionalidentificationfeatureirises"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Raw data group DG4.","type":"text"}],"sections":[],"metadata":{"title":"dg4AdditionalIdentificationFeatureIrises","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"platforms":[{"deprecated":false,"introducedAt":"13.0","name":"iOS","beta":false,"unavailable":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dg4AdditionalIdentificationFeatureIrises"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg4AdditionalIdentificationFeatureIrises","symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg4AdditionalIdentificationFeatureIrises","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}]}]}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg4AdditionalIdentificationFeatureIrises":{"type":"topic","title":"dg4AdditionalIdentificationFeatureIrises","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg4additionalidentificationfeatureirises","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg4AdditionalIdentificationFeatureIrises","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dg4AdditionalIdentificationFeatureIrises"}],"abstract":[{"type":"text","text":"Raw data group DG4."}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"title":"Lds1eMrtdApplication","url":"\/documentation\/dotnfc\/lds1emrtdapplication","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"type":"topic","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Lds1eMrtdApplication"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","role":"symbol","title":"NfcTravelDocumentReader","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFile","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","role":"symbol","kind":"symbol","title":"Lds1ElementaryFile","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic","abstract":[{"text":"Result of NFC reading.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dg4AdditionalIdentificationFeatureIrises"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":" * "},{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg4AdditionalIdentificationFeatureIrises\/title","op":"replace","value":"dg4AdditionalIdentificationFeatureIrises"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg4AdditionalIdentificationFeatureIrises\/fragments","value":[{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","value":"DOTNLds1eMrtdApplication","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","op":"replace","value":"DOTNLds1ElementaryFile"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]}]}]}