{"metadata":{"title":"backgroundUniformity","navigatorTitle":[{"kind":"identifier","text":"backgroundUniformity"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)backgroundUniformity","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"identifier","text":"backgroundUniformity"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/backgroundUniformity"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"backgroundUniformity"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/backgrounduniformity"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules/backgroundUniformity":{"abstract":[],"role":"symbol","type":"topic","title":"backgroundUniformity","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/backgrounduniformity","fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/backgroundUniformity","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"title":"DotFaceLibraryConfigurationModules","abstract":[{"type":"text","text":"Face library module configuration."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}]},"doc://DotNfc/documentation/DotNfc/DotFaceBackgroundUniformityModuleConfiguration":{"abstract":[{"text":"Face background uniformity module.","type":"text"}],"role":"symbol","type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/title","op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}