{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"]]},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/detection"},"metadata":{"fragments":[{"kind":"identifier","text":"detection"}],"roleHeading":"Instance Property","title":"detection","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"detection"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)detection","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/detection"]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"title":"DotFaceLibraryConfigurationModules","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"abstract":[{"type":"text","text":"Face library module configuration."}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules/detection":{"role":"symbol","fragments":[{"text":"detection","kind":"identifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/detection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/detection","title":"detection"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","abstract":[{"text":"Face detection module configuration.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}]}]}