{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral:"},{"kind":"text","text":"("},{"text":"DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"expressionNeutral","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"backgroundUniformity:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"backgroundUniformity","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLiveness:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"eyeGazeLiveness"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"passiveLiveness"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"verification"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(im)initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotNfc"}],"title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}],"navigatorTitle":[{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"role":"symbol"},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceVerificationModuleConfiguration":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotfaceverificationmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"type":"topic","title":"DotFaceVerificationModuleConfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Face verification module.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceVerificationModuleConfiguration"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"role":"symbol","title":"DotFaceLibraryConfigurationModules","kind":"symbol","abstract":[{"text":"Face library module configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","type":"topic","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceEyeGazeLivenessModuleConfiguration":{"type":"topic","abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"title":"DotFaceEyeGazeLivenessModuleConfiguration"},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration":{"url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration","kind":"symbol","abstract":[{"text":"Face passive liveness module.","type":"text"}],"title":"DotFacePassiveLivenessModuleConfiguration","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:":{"url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","navigatorTitle":[{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceExpressionNeutralModuleConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Face expression neutral module."}],"title":"DotFaceExpressionNeutralModuleConfiguration","url":"\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceBackgroundUniformityModuleConfiguration":{"title":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration","role":"symbol","url":"\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration","abstract":[{"text":"Face background uniformity module.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration","abstract":[{"text":"Face detection module configuration.","type":"text"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","title":"DotFaceDetectionModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/title","op":"replace","value":"DotFaceVerificationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/title","op":"replace","value":"DotFacePassiveLivenessModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/title","op":"replace","value":"DotFaceExpressionNeutralModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"},{"value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"},{"value":"DotFaceDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/navigatorTitle"}]}]}