{"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"data"}],"title":"data","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.0","unavailable":false}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"data"},{"text":": ","kind":"text"},{"text":"DataAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","kind":"typeIdentifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus(py)data","modules":[{"name":"DotNfc"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/authenticationstatus\/data"]},{"paths":["\/documentation\/dotnfc\/authenticationstatus\/data"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Data authentication status (using Passing Authentication protocol).","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"data"},{"kind":"text","text":": "},{"text":"DataAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/data"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","kind":"symbol","abstract":[{"text":"Authentication status of the data and protocol used for that purpose.","type":"text"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataAuthenticationStatus"}],"type":"topic","title":"DataAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of data and chip."}],"role":"symbol","navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/authenticationstatus","title":"AuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationStatus"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/data":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"data","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","text":"DataAuthenticationStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/data","url":"\/documentation\/dotnfc\/authenticationstatus\/data","abstract":[{"text":"Data authentication status (using Passing Authentication protocol).","type":"text"}],"navigatorTitle":[{"text":"data","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"data","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"data","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"data","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","text":"DOTNDataAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus"},{"kind":"text","text":" * "},{"kind":"identifier","text":"data"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DOTNDataAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"op":"replace"},{"op":"replace","value":"DOTNAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title"},{"value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1data\/title","value":"data","op":"replace"},{"value":[{"text":"data","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1data\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}