{"abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds"},{"kind":"text","text":" *) "},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","kind":"typeIdentifier","text":"DOTCameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isCameraPreviewVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"isCameraPreviewVisible","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration"]]},"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:":{"type":"topic","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"title":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"url":"\/documentation\/dotpalmcore\/camerafacing","role":"symbol","title":"CameraFacing","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"type":"topic","title":"DOTPPalmAutoCaptureConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","role":"symbol","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration","kind":"symbol","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPQualityAttributeThresholds":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds","fragments":[{"text":"DOTPQualityAttributeThresholds","kind":"identifier"}],"title":"DOTPQualityAttributeThresholds","url":"\/documentation\/dotpalmcore\/dotpqualityattributethresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","title":"CameraPreviewScaleType","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","op":"replace"}]}]}