{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/facekeypoints\/nosebottom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/nosebottom"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseBottom","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"abstract":[{"type":"text","text":"Bottom nose."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseBottom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseBottom","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"noseBottom"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)noseBottom","title":"noseBottom"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"type":"topic","abstract":[{"text":"Face Keypoint","type":"text"}],"title":"FaceKeypoint","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","url":"\/documentation\/dotfacecore\/facekeypoint","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoint"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"url":"\/documentation\/dotfacecore\/facekeypoints","type":"topic","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","kind":"symbol","title":"FaceKeypoints","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoints"}],"navigatorTitle":[{"kind":"identifier","text":"FaceKeypoints"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/noseBottom":{"type":"topic","abstract":[{"text":"Bottom nose.","type":"text"}],"title":"noseBottom","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/noseBottom","url":"\/documentation\/dotfacecore\/facekeypoints\/nosebottom","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"noseBottom"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"noseBottom"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"noseBottom","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"noseBottom","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},{"kind":"text","text":" * "},{"kind":"identifier","text":"noseBottom"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFFaceKeypoint","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title"},{"value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments"},{"value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle"},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle"},{"value":"noseBottom","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseBottom\/title"},{"value":[{"text":"noseBottom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1noseBottom\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}