{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.backgroundColor, "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" = Defaults.instructionFont, "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.instructionTextColor, "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.instructionBackgroundColor, "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.placeholderColor, "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.detectionLayerColor, "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" = Defaults.overlayColor)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructionbackgroundcolor:placeholdercolor:detectionlayercolor:overlaycolor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructionbackgroundcolor:placeholdercolor:detectionlayercolor:overlaycolor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"title":"init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessStyle(im)initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 6.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessViewController":{"role":"symbol","title":"SmileLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)":{"role":"symbol","title":"init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructionbackgroundcolor:placeholdercolor:detectionlayercolor:overlaycolor:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle":{"role":"symbol","title":"SmileLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessStyle"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"backgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionFont:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionFont"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionTextColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"instructionBackgroundColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"placeholderColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionLayerColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"detectionLayerColor"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayColor:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"overlayColor"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)\/title","value":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle\/title","value":"DOTFSmileLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}