{"variants":[{"paths":["\/documentation\/dotfacelite\/cameraimagesource\/avcapturevideodataoutputsamplebufferdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/cameraimagesource\/avcapturevideodataoutputsamplebufferdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraImageSource\/AVCaptureVideoDataOutputSampleBufferDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraImageSource\/captureOutput(_:didOutput:from:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"DotFaceLite"}],"role":"collectionGroup","title":"AVCaptureVideoDataOutputSampleBufferDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraImageSource"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraImageSource/captureOutput(_:didOutput:from:)":{"role":"symbol","title":"captureOutput(_:didOutput:from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureOutput"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVCaptureOutput","preciseIdentifier":"c:objc(cs)AVCaptureOutput"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didOutput"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CMSampleBuffer","preciseIdentifier":"c:@T@CMSampleBufferRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureConnection","preciseIdentifier":"c:objc(cs)AVCaptureConnection"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraImageSource\/captureOutput(_:didOutput:from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}],"url":"\/documentation\/dotfacelite\/cameraimagesource\/captureoutput(_:didoutput:from:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 5.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraImageSource":{"role":"symbol","title":"CameraImageSource","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraImageSource"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraImageSource","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraImageSource"}],"url":"\/documentation\/dotfacelite\/cameraimagesource"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraImageSource\/captureOutput(_:didOutput:from:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraImageSource~1captureOutput(_:didOutput:from:)\/title","value":"captureOutput:didOutputSampleBuffer:fromConnection:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraImageSource~1captureOutput(_:didOutput:from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"captureOutput:didOutputSampleBuffer:fromConnection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraImageSource\/title","value":"CameraImageSource"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraImageSource\/fragments","value":[{"kind":"identifier","text":"CameraImageSource"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}