{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword\/description","interfaceLanguage":"swift"},"metadata":{"required":true,"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword(py)description","modules":[{"name":"DotNfc"}]},"variants":[{"paths":["\/documentation\/dotnfc\/traveldocumentreaderpassword\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocumentreaderpassword\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"type":"topic","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"kind":"symbol","title":"TravelDocumentReaderPassword","role":"symbol","abstract":[{"text":"Password for accessing the chip.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword/description":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"description","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword\/description","abstract":[],"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword\/description"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","value":"DOTNTravelDocumentReaderPassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPassword"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/navigatorTitle","value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"}]}]}