{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/result"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC7RunningC6resultAA0bdE6ResultCSgvp","modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureResult","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"result","symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"codeVoice","code":"null"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","text":"PalmAutoCaptureResult","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/result","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running","title":"PalmAutoCaptureUiState.Running","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"kind":"symbol","abstract":[{"type":"text","text":"Running state."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Running"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocaptureresult","role":"symbol","title":"PalmAutoCaptureResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running/result":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running\/result","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"result","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"text":"?","kind":"text"}],"title":"result","abstract":[{"text":"Result. If the process has not finished, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running\/result"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"type":"topic","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"title":"PalmAutoCaptureUiState","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title","value":"DOTPPalmAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","value":"DOTPPalmAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}]}]}]}