{"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DotDocumentLibraryConfigurationModules) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","title":"DotDocumentLibraryConfiguration.Modules"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Document library module configuration."}],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"references":{"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?)","kind":"text"}],"kind":"symbol","title":"init(barcode:)","abstract":[],"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","kind":"symbol","type":"topic","title":"barcode","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"abstract":[]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class":{"type":"topic","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class","abstract":[{"type":"text","text":"Document library module configuration."}],"kind":"symbol"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/title","op":"replace","value":"DotDocumentLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}]}]}