{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Face"}],"title":"FaceDetector.Face","role":"symbol","roleHeading":"Class","externalID":"s:11DotFaceLite0B8DetectorC0B0C","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"class"},"abstract":[{"text":"Detected face.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceDetectorFace) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Face","kind":"identifier"}]}]}],"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/face"]}],"kind":"symbol","seeAlsoSections":[{"title":"Face detection output","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageParameters","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/init(confidence:position:imageParameters:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/confidence","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/imageParameters","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/position"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"url":"\/documentation\/dotfacelite\/rectangledouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"url":"\/documentation\/dotfacelite\/facedetector","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/ImageParameters":{"type":"topic","abstract":[{"text":"Parameters of the image which was used for the face detection.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotfacelite\/imageparameters","title":"ImageParameters","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageParameters"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"navigatorTitle":[{"kind":"identifier","text":"Face"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","role":"symbol","url":"\/documentation\/dotfacelite\/facedetector\/face","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"abstract":[{"type":"text","text":"Detected face."}],"title":"FaceDetector.Face","type":"topic","kind":"symbol"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/confidence":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/confidence","abstract":[{"text":"Face detection confidence in range [0, 1.0]. Where 0 means low confidence and 1.0 means high confidence.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","title":"confidence","url":"\/documentation\/dotfacelite\/facedetector\/face\/confidence","kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/position":{"url":"\/documentation\/dotfacelite\/facedetector\/face\/position","type":"topic","kind":"symbol","role":"symbol","title":"position","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Position of the detected face in the image."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/position"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/description":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description","abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/facedetector\/face\/description","kind":"symbol","role":"symbol"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/imageParameters":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/imageParameters","abstract":[{"text":"Parameters of the face image.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters"},{"kind":"text","text":": "},{"text":"ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters"}],"role":"symbol","title":"imageParameters","url":"\/documentation\/dotfacelite\/facedetector\/face\/imageparameters","kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/init(confidence:position:imageParameters:)":{"abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/facedetector\/face\/init(confidence:position:imageparameters:)","title":"init(confidence:position:imageParameters:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/init(confidence:position:imageParameters:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confidence"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition"},{"text":", ","kind":"text"},{"text":"imageParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters","text":"ImageParameters"},{"text":")","kind":"text"}]},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments"},{"value":"DOTFLFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]},{"value":"DOTFLImageParameters","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageParameters\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageParameters\/fragments","value":[{"text":"DOTFLImageParameters","kind":"identifier"}],"op":"replace"}]}]}