{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum\/denied","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum\/denied"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum"]]},"abstract":[{"type":"text","text":"Data is proved not genuine."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"denied","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","title":"DataAuthenticationStatus.Status.denied","modules":[{"name":"DotNfc"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denied","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case","externalID":"s:6DotNfc24DataAuthenticationStatusC0E0O6deniedyA2EmF"},"references":{"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/Status-swift.enum/denied":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum\/denied","title":"DataAuthenticationStatus.Status.denied","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"denied","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum\/denied","abstract":[{"text":"Data is proved not genuine.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"abstract":[{"text":"Authentication status of the data and protocol used for that purpose.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataAuthenticationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus","type":"topic","title":"DataAuthenticationStatus","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/Status-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum","type":"topic","abstract":[{"type":"text","text":"Authentication status of the data."}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum","role":"symbol","navigatorTitle":[{"text":"Status","kind":"identifier"}],"kind":"symbol","title":"DataAuthenticationStatus.Status"}},"variantOverrides":[{"patch":[{"value":"DOTNDataAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}