{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum\/hash(into:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"metadata":{"extendedModule":"Swift","modules":[{"name":"DotNfc","relatedModules":["Swift"]}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::s:6DotNfc24DataAuthenticationStatusC0E0O","title":"hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/Status-swift.enum/hash(into:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum\/hash(into:)","abstract":[],"role":"symbol","title":"hash(into:)","type":"topic","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum\/hash(into:)"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/Status-swift.enum":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum","abstract":[{"text":"Authentication status of the data.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum","title":"DataAuthenticationStatus.Status","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Status"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus","abstract":[{"text":"Authentication status of the data and protocol used for that purpose.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","title":"DataAuthenticationStatus","type":"topic","navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTNDataAuthenticationStatus","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title"},{"value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments"},{"value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}