{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewWillDisappear"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"magnifEyeLivenessViewControllerViewWillDisappear(_:)","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessLiteViewControllerViewWillDisappear:","symbolKind":"method","required":true,"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewWillDisappear:"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(magnifEyeLivenessLiteViewControllerViewWillDisappear:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"magnifEyeLivenessViewControllerViewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillDisappear(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewWillDisappear(_:)":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillDisappear(_:)","type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilldisappear(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"magnifEyeLivenessViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"title":"magnifEyeLivenessViewControllerViewWillDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewWillDisappear:"}],"required":true,"abstract":[]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate":{"abstract":[{"type":"text","text":"Implement this delegate to handle the MagnifEye liveness events."}],"title":"MagnifEyeLivenessViewControllerDelegate","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"title":"MagnifEyeLivenessViewController","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"magnifEyeLivenessLiteViewControllerViewWillDisappear:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"magnifEyeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"magnifEyeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","kind":"typeIdentifier","text":"DOTFLMagnifEyeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"magnifEyeLivenessLiteViewControllerViewWillDisappear:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillDisappear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"magnifEyeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFLMagnifEyeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"op":"replace"}]}]}