{"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isLibraryActive(libraryId:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdk\/islibraryactive(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotsdk\/islibraryactive(libraryid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"title":"isLibraryActive(libraryId:)","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DotSdk(im)isLibraryActiveWithLibraryId:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isLibraryActive","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol"},"abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library is active."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLibraryActive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"libraryId"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"url":"\/documentation\/dotpalmcore\/dotlibraryid","title":"DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"kind":"symbol","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"title":"DotSdk","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdk","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/isLibraryActive(libraryId:)":{"url":"\/documentation\/dotpalmcore\/dotsdk\/islibraryactive(libraryid:)","title":"isLibraryActive(libraryId:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isLibraryActive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isLibraryActive(libraryId:)","abstract":[{"type":"text","text":"Check whether "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library is active."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isLibraryActiveWithLibraryId:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"},{"text":") ","kind":"text"},{"text":"libraryId","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1isLibraryActive(libraryId:)\/title","op":"replace","value":"isLibraryActiveWithLibraryId:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1isLibraryActive(libraryId:)\/fragments","op":"replace"}]}]}