{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"method","roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"}],"navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTCIImageFactory(cm)createWithBgrRawImage:","title":"create(bgrRawImage:)"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory"]]},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/ciimagefactory\/create(bgrrawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/ciimagefactory\/create(bgrrawimage:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory\/create(bgrRawImage:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage","text":"BgrRawImage"},{"text":") -> ","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgrRawImage","type":"codeVoice"},{"text":" object.","type":"text"}]}],"name":"bgrRawImage"}]},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/CIImageFactory":{"url":"\/documentation\/dotnfc\/ciimagefactory","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"title":"CIImageFactory"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/CIImageFactory/create(bgrRawImage:)":{"kind":"symbol","url":"\/documentation\/dotnfc\/ciimagefactory\/create(bgrrawimage:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"title":"create(bgrRawImage:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}],"navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory\/create(bgrRawImage:)","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage":{"title":"BgrRawImage","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrrawimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"createWithBgrRawImage:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createWithBgrRawImage:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTBgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage"},{"text":" *) ","kind":"text"},{"text":"bgrRawImage","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCIImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory\/title"},{"value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory~1create(bgrRawImage:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgrRawImage:","kind":"identifier"}]},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/title"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}