{"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:ciContext:","title":"create(bgraRawImage:ciContext:)","roleHeading":"Type Method","navigatorTitle":[{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"role":"symbol","modules":[{"name":"DotNfc"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/ciimagefactory\/create(bgrarawimage:cicontext:)"]},{"paths":["\/documentation\/dotnfc\/ciimagefactory\/create(bgrarawimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory\/create(bgraRawImage:ciContext:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgraRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"bgraRawImage"},{"name":"ciContext","content":[{"type":"paragraph","inlineContent":[{"text":"CIContext.","type":"text"}]}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CIImage"},{"text":" instance.","type":"text"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory"]]},"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/CIImageFactory/create(bgraRawImage:ciContext:)":{"url":"\/documentation\/dotnfc\/ciimagefactory\/create(bgrarawimage:cicontext:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory\/create(bgraRawImage:ciContext:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"title":"create(bgraRawImage:ciContext:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgraRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"title":"BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"role":"symbol","url":"\/documentation\/dotnfc\/bgrarawimage","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgraRawImage"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/CIImageFactory":{"url":"\/documentation\/dotnfc\/ciimagefactory","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CIImageFactory","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"title":"CIImageFactory"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createWithBgraRawImage:ciContext:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"createWithBgraRawImage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgraRawImage","text":"DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":" "},{"text":"ciContext:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ciContext"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"createWithBgraRawImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory~1create(bgraRawImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory~1create(bgraRawImage:ciContext:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"value":"DOTCIImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}