{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/IntervalDouble"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/validationdouble\/validate(value:interval:)"]},{"paths":["\/documentation\/dotpalmcore\/validationdouble\/validate(value:interval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationDouble\/validate(value:interval:)"},"metadata":{"title":"validate(value:interval:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"symbolKind":"method","externalID":"c:@M@DotPalmCore@objc(cs)DOTValidationDouble(cm)validateWithValue:interval:error:","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"roleHeading":"Type Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationDouble"]]},"kind":"symbol","references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ValidationDouble/validate(value:interval:)":{"type":"topic","title":"validate(value:interval:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationDouble\/validate(value:interval:)","navigatorTitle":[{"text":"validateWithValue:interval:error:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/validationdouble\/validate(value:interval:)","kind":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/IntervalDouble":{"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/intervaldouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","title":"IntervalDouble","role":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ValidationDouble":{"type":"topic","title":"ValidationDouble","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ValidationDouble","kind":"identifier"}],"abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationDouble","navigatorTitle":[{"text":"ValidationDouble","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/validationdouble","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"validateWithValue:interval:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithValue:"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"text":" ","kind":"text"},{"text":"interval:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTIntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/IntervalDouble"},{"kind":"text","text":" *) "},{"text":"interval","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationDouble~1validate(value:interval:)\/title","value":"validateWithValue:interval:error:","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationDouble~1validate(value:interval:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1IntervalDouble\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationDouble\/title","value":"DOTValidationDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationDouble\/fragments","value":[{"text":"DOTValidationDouble","kind":"identifier"}],"op":"replace"}]}]}