{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(im)initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","symbolKind":"init","roleHeading":"Initializer"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","role":"symbol","title":"AutoCaptureConfiguration","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)":{"role":"symbol","navigatorTitle":[{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minValidSamplesInRowToStartCandidateSelection"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)","abstract":[],"kind":"symbol","title":"init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithMinValidSamplesInRowToStartCandidateSelection:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/title","op":"replace","value":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:"}]}]}]}