{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble(py)description","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/description"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/intervaldouble\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/intervaldouble\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/description":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","title":"description","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/intervaldouble\/description"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfingerscore\/intervaldouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","title":"IntervalDouble","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble~1description\/fragments","op":"replace"},{"value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/fragments","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/navigatorTitle","op":"replace"}]}]}