{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/comHeaderAndDataGroupPresenceInformation"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/comheaderanddatagrouppresenceinformation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/comheaderanddatagrouppresenceinformation"]}],"metadata":{"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)comHeaderAndDataGroupPresenceInformation","navigatorTitle":[{"kind":"identifier","text":"comHeaderAndDataGroupPresenceInformation"}],"roleHeading":"Instance Property","title":"comHeaderAndDataGroupPresenceInformation","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"comHeaderAndDataGroupPresenceInformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"comHeaderAndDataGroupPresenceInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"Lds1ElementaryFile"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Raw data group COM."}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1eMrtdApplication"}],"abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"kind":"symbol","title":"Lds1eMrtdApplication"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","type":"topic","title":"TravelDocument"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","type":"topic","role":"collection"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFile"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile","kind":"symbol","role":"symbol","title":"Lds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/comHeaderAndDataGroupPresenceInformation":{"role":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/comheaderanddatagrouppresenceinformation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"comHeaderAndDataGroupPresenceInformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"}],"kind":"symbol","type":"topic","abstract":[{"text":"Raw data group COM.","type":"text"}],"navigatorTitle":[{"text":"comHeaderAndDataGroupPresenceInformation","kind":"identifier"}],"title":"comHeaderAndDataGroupPresenceInformation","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/comHeaderAndDataGroupPresenceInformation"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"comHeaderAndDataGroupPresenceInformation","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"comHeaderAndDataGroupPresenceInformation","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","text":"DOTNLds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":" * ","kind":"text"},{"text":"comHeaderAndDataGroupPresenceInformation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments"},{"value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/navigatorTitle"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle"},{"value":"DOTNLds1ElementaryFile","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"},{"value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle"},{"value":"comHeaderAndDataGroupPresenceInformation","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1comHeaderAndDataGroupPresenceInformation\/title"},{"value":[{"kind":"identifier","text":"comHeaderAndDataGroupPresenceInformation"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1comHeaderAndDataGroupPresenceInformation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}