{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners","text":"Corners"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/corners\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/corners\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/rebased(parentRectangle:)"},"metadata":{"extendedModule":"DotCore","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"title":"rebased(parentRectangle:)","role":"symbol","modules":[{"name":"DotFaceLite","relatedModules":["DotCore"]}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rebased","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier"}],"externalID":"c:@CM@DotCore@objc(cs)DOTCorners(im)rebasedWithParentRectangle:"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/Corners/rebased(parentRectangle:)":{"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/corners\/rebased(parentrectangle:)","title":"rebased(parentRectangle:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/rebased(parentRectangle:)"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"url":"\/documentation\/dotfacelite\/rectangledouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"},"doc://DotFaceLite/documentation/DotFaceLite/Corners":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"role":"symbol","title":"Corners","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotfacelite\/corners"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"rebasedWithParentRectangle:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTCorners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rebasedWithParentRectangle:"},{"text":"(","kind":"text"},{"text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"text":"parentRectangle","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1rebased(parentRectangle:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/title"},{"op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}