{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerstopped(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerstopped(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerStopped(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that the component has stopped."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceAutoCaptureViewController"},{"kind":"text","text":")"}],"title":"faceAutoCaptureViewControllerStopped(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFaceAutoCaptureViewControllerDelegate(im)faceAutoCaptureViewControllerStopped:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"role":"symbol","title":"FaceAutoCaptureViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"DotFaceCore is a part of DotFace framework group which provides components for the digital onboarding process using the latest Innovatrics IFace image processing library. It wraps the core functionality of IFace library to a higher-level module which is easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerStopped(_:)":{"role":"symbol","title":"faceAutoCaptureViewControllerStopped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceAutoCaptureViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the component has stopped."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerStopped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped:"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerstopped(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceAutoCaptureViewControllerStopped:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceAutoCaptureViewController","text":"DOTFaceAutoCaptureViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFaceAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerStopped(_:)\/title","value":"faceAutoCaptureViewControllerStopped:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerStopped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewControllerStopped:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}