{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"DotLibraryId.faceLite","symbolKind":"case","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFaceLite"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/faceLite","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/facelite"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/facelite"]}],"abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceLite"}]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotlibraryid","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/faceLite":{"kind":"symbol","navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/faceLite","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"title":"DotLibraryId.faceLite","abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"text":" identifier.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid\/facelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DotLibraryIdFaceLite"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"value":"DotLibraryIdFaceLite","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1faceLite\/title","op":"replace"},{"value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1faceLite\/fragments"}]}]}