{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/face"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/face"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/face"},"abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"metadata":{"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"}],"role":"symbol","title":"DotLibraryId.face","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFace","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFace"}],"roleHeading":"Case"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/face":{"type":"topic","abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotlibraryid\/face","title":"DotLibraryId.face","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/face","navigatorTitle":[{"text":"DotLibraryIdFace","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"kind":"symbol","title":"DotLibraryId","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","role":"symbol","url":"\/documentation\/dotpalmcore\/dotlibraryid","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DotLibraryIdFace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFace"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdFace","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotLibraryIdFace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1face\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1face\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFace"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}