{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFingers","title":"DotLibraryId.fingers","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"symbolKind":"case"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/fingers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/fingers"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/fingers","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/fingers":{"role":"symbol","abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid\/fingers","title":"DotLibraryId.fingers","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/fingers","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFingers"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"title":"DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"url":"\/documentation\/dotpalmcore\/dotlibraryid","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DotLibraryIdFingers"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFingers"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DotLibraryIdFingers","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"DotLibraryIdFingers","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1fingers\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFingers"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1fingers\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}