{"kind":"symbol","abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"codeVoice","code":".standard"},{"type":"text","text":" preset."}],"metadata":{"externalID":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC26qualityAttributeThresholdsAA0bef7QualitykL0Cvp","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"}],"title":"qualityAttributeThresholds","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/qualityattributethresholds"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing face images with customizable UI."}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"title":"BaseFaceAutoCaptureViewController"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/qualityattributethresholds","title":"qualityAttributeThresholds","abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"codeVoice","code":".standard"},{"type":"text","text":" preset."}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"title":"BaseFaceAutoCaptureViewController.Configuration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds":{"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","title":"FaceAutoCaptureQualityAttributeThresholds","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title","value":"DOTFLBaseFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFLFaceAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds"}]}]}]}