{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" = 0.06) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration"]]},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(modules:faceDetectionConfidenceThreshold:)","roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(im)initWithModules:faceDetectionConfidenceThreshold:error:","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"role":"symbol"},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration":{"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","abstract":[{"type":"text","text":"Face library configuration."}],"role":"symbol","kind":"symbol","title":"DotFaceLibraryConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","title":"init(modules:faceDetectionConfidenceThreshold:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class","abstract":[{"type":"text","text":"Face library module configuration."}],"role":"symbol","kind":"symbol","title":"DotFaceLibraryConfiguration.Modules"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","kind":"symbol","abstract":[{"text":"Face library module configuration.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithModules:faceDetectionConfidenceThreshold:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithModules:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFaceLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/title"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/navigatorTitle"},{"value":"initWithModules:faceDetectionConfidenceThreshold:error:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}