{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgrRawImage","type":"codeVoice"},{"text":" object.","type":"text"}]}],"name":"bgrRawImage"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" instance.","type":"text"}]}]}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/cgimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/cgimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithBgrRawImage:","modules":[{"name":"DotDocument"}],"roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"title":"create(bgrRawImage:)","symbolKind":"method"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory\/create(bgrRawImage:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/CGImageFactory":{"url":"\/documentation\/dotdocument\/cgimagefactory","title":"CGImageFactory","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGImageFactory"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/CGImageFactory/create(bgrRawImage:)":{"type":"topic","navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"url":"\/documentation\/dotdocument\/cgimagefactory\/create(bgrrawimage:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"text":") -> ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"}],"title":"create(bgrRawImage:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory\/create(bgrRawImage:)"},"doc://DotDocument/documentation/DotDocument/BgrRawImage":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"url":"\/documentation\/dotdocument\/bgrrawimage"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","title":"DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createWithBgrRawImage:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgrRawImage:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage","text":"CGImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","text":"DOTBgrRawImage"},{"kind":"text","text":" *) "},{"text":"bgrRawImage","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory~1create(bgrRawImage:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgrRawImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/fragments","op":"replace"}]}]}