{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraFacing"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","text":"CameraFacing"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"metadata":{"title":"cameraFacing","role":"symbol","roleHeading":"Type Property","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC8DefaultsV12cameraFacing0A6Camera0mL0OvpZ","symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"abstract":[{"type":"text","text":"UI component for capturing images suitable for Multi-Range Liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","type":"topic","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","role":"symbol","title":"MultiRangeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.16.0"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/Defaults/cameraFacing":{"type":"topic","abstract":[],"title":"cameraFacing","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults\/camerafacing","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraFacing","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"type":"topic","title":"MultiRangeLivenessViewController.Configuration","abstract":[{"text":"Configuration options for the Multi-Range Liveness process.","type":"text"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing","url":"\/documentation\/dotfacelite\/camerafacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/Defaults":{"type":"topic","title":"MultiRangeLivenessViewController.Configuration.Defaults","abstract":[],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}