{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules"]]},"metadata":{"fragments":[{"text":"passiveLiveness","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)passiveLiveness","title":"passiveLiveness","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"passiveLiveness"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/passiveLiveness"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/passiveliveness"]}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"kind":"symbol","title":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"abstract":[{"text":"Face passive liveness module.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules/passiveLiveness":{"fragments":[{"text":"passiveLiveness","kind":"identifier"}],"kind":"symbol","title":"passiveLiveness","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/passiveLiveness","abstract":[],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/passiveliveness","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"title":"DotFaceLibraryConfigurationModules","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},{"value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"}]}]}