{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]]},"metadata":{"roleHeading":"Type Method","modules":[{"name":"DotPalmCore"}],"symbolKind":"method","title":"create(bgraRawImage:ciContext:)","externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:ciContext:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"}]}],"kind":"declarations"},{"parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"CIContext."}],"type":"paragraph"}],"name":"ciContext"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrarawimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrarawimage:cicontext:)"]}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(bgraRawImage:ciContext:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"url":"\/documentation\/dotpalmcore\/bgrarawimage","title":"BgraRawImage"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory/create(bgraRawImage:ciContext:)":{"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"title":"create(bgraRawImage:ciContext:)","type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(bgraRawImage:ciContext:)","navigatorTitle":[{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrarawimage:cicontext:)"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"title":"CIImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CIImageFactory","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/ciimagefactory","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithBgraRawImage:ciContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":" *) "},{"text":"createWithBgraRawImage:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"ciContext:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"ciContext","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"value":"createWithBgraRawImage:ciContext:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(bgraRawImage:ciContext:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(bgraRawImage:ciContext:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}