{"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"stopAsyncOnStopped:","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(im)stopAsyncOnStopped:","role":"symbol","title":"stopAsync(onStopped:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAsync"},{"kind":"text","text":"("},{"text":"onStopped","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"kind":"symbol","abstract":[{"text":"Stop the document auto capture process asynchronously. The ","type":"text"},{"type":"codeVoice","code":"onStopped"},{"text":" callback is called after the process has stopped.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/stopAsync(onStopped:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onStopped"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/stopasync(onstopped:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/stopasync(onstopped:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","title":"DocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"text":"version: 8.13.0","type":"text"}],"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/stopAsync(onStopped:)":{"abstract":[{"text":"Stop the document auto capture process asynchronously. The ","type":"text"},{"type":"codeVoice","code":"onStopped"},{"text":" callback is called after the process has stopped.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/stopAsync(onStopped:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onStopped"},{"text":": () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/stopasync(onstopped:)","navigatorTitle":[{"kind":"identifier","text":"stopAsyncOnStopped:"}],"title":"stopAsync(onStopped:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"stopAsyncOnStopped:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopAsyncOnStopped:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"stopAsyncOnStopped:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFv()"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"onStopped"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1stopAsync(onStopped:)\/title","value":"stopAsyncOnStopped:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1stopAsync(onStopped:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stopAsyncOnStopped:"}],"op":"replace"}]}]}