{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/logger\/loglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/logger\/loglevel"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/logLevel"},"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"code":".none","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"LoggerLogLevel","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"kind":"text","text":": "},{"text":"LoggerLogLevel","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPLogger(cpy)logLevel","roleHeading":"Type Property","title":"logLevel","navigatorTitle":[{"kind":"identifier","text":"logLevel"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger"]]},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.1","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Logger":{"title":"Logger","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/logger","type":"topic","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger"},"doc://DotPalmCore/documentation/DotPalmCore/Logger/logLevel":{"url":"\/documentation\/dotpalmcore\/logger\/loglevel","title":"logLevel","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"code":".none","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/logLevel","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"text":": ","kind":"text"},{"text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}]},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"kind":"symbol","title":"LoggerLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","abstract":[{"type":"text","text":"Available log levels."}],"url":"\/documentation\/dotpalmcore\/loggerloglevel","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"logLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"logLevel","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DOTLoggerLogLevel","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/title","value":"DOTPLogger"},{"value":[{"kind":"identifier","text":"DOTPLogger"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1logLevel\/title","op":"replace","value":"logLevel"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1logLevel\/fragments","value":[{"text":"logLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}