{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/error\/failedtoloadsystemconstants"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"case","role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"s:7DotCore0A3SdkC5ErrorO27failedToLoadSystemConstantsyA2EmF","roleHeading":"Case","title":"DotSdk.Error.failedToLoadSystemConstants","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadSystemConstants","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotSdk/Error/failedToLoadSystemConstants":{"role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotsdk\/error\/failedtoloadsystemconstants","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error\/failedToLoadSystemConstants","kind":"symbol","title":"DotSdk.Error.failedToLoadSystemConstants"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotSdk":{"role":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotsdk","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","kind":"symbol","title":"DotSdk"},"doc://DotDocument/documentation/DotDocument/DotSdk/Error":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotsdk\/error","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Error","kind":"symbol","title":"DotSdk.Error"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotSdk","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title"},{"op":"replace","value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments"},{"op":"replace","value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle"}]}]}