{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bgrrawimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrrawimage"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"title":"BgrRawImage","roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DOTBgrRawImage","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"role":"symbol","modules":[{"name":"DotNfc"}],"symbolKind":"class"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/init(bytesPointer:size:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/size"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"kind":"relationships"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTBgrRawImage) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"sections":[],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage/size":{"type":"topic","title":"size","abstract":[{"text":"Image size.","type":"text"}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/size","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/bgrrawimage\/size","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage":{"role":"symbol","url":"\/documentation\/dotnfc\/bgrrawimage","type":"topic","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage","title":"BgrRawImage"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage/bytes":{"role":"symbol","url":"\/documentation\/dotnfc\/bgrrawimage\/bytes","type":"topic","navigatorTitle":[{"text":"bytes","kind":"identifier"}],"abstract":[{"text":"Raw image data.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytes","title":"bytes"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/@M@DotNfc@objc(pl)_RawImage":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/@M@DotNfc@objc(pl)_RawImage","title":"_RawImage","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/SH":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage/init(bytesPointer:size:)":{"role":"symbol","url":"\/documentation\/dotnfc\/bgrrawimage\/init(bytespointer:size:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"abstract":[{"text":"Do not use this, use ","type":"text"},{"type":"codeVoice","code":"BgrRawImageFactory"},{"text":" to create ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/init(bytesPointer:size:)","title":"init(bytesPointer:size:)"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage/bytesPointer":{"role":"symbol","url":"\/documentation\/dotnfc\/bgrrawimage\/bytespointer","type":"topic","navigatorTitle":[{"text":"bytesPointer","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bytesPointer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":">","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytesPointer","title":"bytesPointer"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTBgrRawImage"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/size"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage\/init(bytesPointer:size:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/@M@DotNfc@objc(pl)_RawImage"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBgrRawImage"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1size\/title","value":"size"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1size\/fragments","value":[{"kind":"identifier","text":"size"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1bytes\/title","value":"bytes"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1init(bytesPointer:size:)\/fragments","op":"replace"},{"value":"bytesPointer","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1bytesPointer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage~1bytesPointer\/fragments","value":[{"kind":"identifier","text":"bytesPointer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}