{"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNDataAuthenticationStatus) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DataAuthenticationStatus","kind":"identifier"}]}]}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/init(status:authenticationProtocol:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/authenticationProtocol-swift.property","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/status-swift.property"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"metadata":{"roleHeading":"Class","title":"DataAuthenticationStatus","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"platforms":[{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iOS"}],"symbolKind":"class","externalID":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"identifier"}],"role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"title":"Conforms To","kind":"relationships"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus","interfaceLanguage":"swift"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol"],"title":"NFC protocols"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AccessControlProtocol":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"Access Control protocol."}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"title":"AccessControlProtocol","type":"topic","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","type":"topic","kind":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol","navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/status-swift.property":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/status-swift.property","abstract":[{"type":"text","text":"Status of the authentication process."}],"navigatorTitle":[{"kind":"identifier","text":"status"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O","kind":"typeIdentifier","text":"Status"}],"role":"symbol","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.property","kind":"symbol","title":"status","type":"topic"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/description":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/description","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/description","kind":"symbol","title":"description","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AuthenticationStatus":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of data and chip."}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationStatus"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AuthenticationStatus","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/authenticationstatus","kind":"symbol","title":"AuthenticationStatus","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus","type":"topic","title":"ChipAuthenticationStatus","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"role":"symbol","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/isEqual(_:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/isEqual(_:)","title":"isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/isequal(_:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum","type":"topic","title":"DataAuthenticationStatus.AuthenticationProtocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol for authentication of the data."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/init(status:authenticationProtocol:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/init(status:authenticationProtocol:)","title":"init(status:authenticationProtocol:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithStatus:authenticationProtocol:","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O","kind":"typeIdentifier","text":"Status"},{"kind":"text","text":", "},{"kind":"externalParam","text":"authenticationProtocol"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO","kind":"typeIdentifier","text":"AuthenticationProtocol"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/init(status:authenticationprotocol:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"identifier"}],"abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus","role":"symbol","type":"topic","navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus","kind":"symbol","title":"DataAuthenticationStatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/hash":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/hash","title":"hash","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/Status-swift.enum":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum","abstract":[{"type":"text","text":"Authentication status of the data."}],"navigatorTitle":[{"kind":"identifier","text":"Status"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Status"}],"role":"symbol","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum","kind":"symbol","title":"DataAuthenticationStatus.Status"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DataAuthenticationStatus/authenticationProtocol-swift.property":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.property","title":"authenticationProtocol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/authenticationProtocol-swift.property","navigatorTitle":[{"text":"authenticationProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authenticationProtocol"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO","kind":"typeIdentifier","text":"AuthenticationProtocol"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Protocol used for that purpose."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[],"op":"replace","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTNDataAuthenticationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/authenticationProtocol-swift.property","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/status-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/init(status:authenticationProtocol:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DataAuthenticationStatus\/isEqual(_:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"NFC protocols","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol"]}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTNDataAuthenticationStatus","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/title","value":"DOTNAccessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}]},{"op":"replace","value":"status","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1status-swift.property\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1status-swift.property\/fragments","value":[{"kind":"identifier","text":"status"}],"op":"replace"},{"value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1description\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","value":"DOTNAuthenticationStatus","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AuthenticationStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1init(status:authenticationProtocol:)\/title","value":"initWithStatus:authenticationProtocol:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1init(status:authenticationProtocol:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:authenticationProtocol:"}],"op":"replace"},{"op":"replace","value":"DOTNDataAuthenticationStatus","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1hash\/title","value":"hash"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1authenticationProtocol-swift.property\/title","value":"authenticationProtocol","op":"replace"},{"op":"replace","value":[{"text":"authenticationProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DataAuthenticationStatus~1authenticationProtocol-swift.property\/fragments"}]}]}