{"abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"variants":[{"paths":["\/documentation\/dotnfc\/validationdouble"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/validationdouble"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"type":"conformsTo","title":"Conforms To"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTValidationDouble) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationDouble","kind":"identifier"}]}],"kind":"declarations"}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble\/validate(value:interval:)"]}],"metadata":{"roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DOTValidationDouble","navigatorTitle":[{"text":"ValidationDouble","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotNfc"}],"title":"ValidationDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationDouble","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.innovatrics.dot.nfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ValidationDouble/validate(value:interval:)":{"url":"\/documentation\/dotnfc\/validationdouble\/validate(value:interval:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble\/validate(value:interval:)","title":"validate(value:interval:)","navigatorTitle":[{"text":"validateWithValue:interval:error:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ValidationDouble":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble","kind":"symbol","type":"topic","title":"ValidationDouble","navigatorTitle":[{"text":"ValidationDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"url":"\/documentation\/dotnfc\/validationdouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ValidationDouble","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTValidationDouble","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DOTValidationDouble","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTValidationDouble","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationDouble\/validate(value:interval:)"],"title":"Type Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTValidationDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"validateWithValue:interval:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble~1validate(value:interval:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"validateWithValue:interval:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble~1validate(value:interval:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble\/title","value":"DOTValidationDouble","op":"replace"},{"value":[{"text":"DOTValidationDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationDouble\/fragments","op":"replace"}]}]}