{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/width"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt"]]},"variants":[{"paths":["\/documentation\/dotdocument\/rectangleint\/width"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangleint\/width"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}],"navigatorTitle":[{"text":"width","kind":"identifier"}],"extendedModule":"DotCore","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)width","title":"width","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument/RectangleInt":{"kind":"symbol","role":"symbol","title":"RectangleInt","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt","type":"topic","url":"\/documentation\/dotdocument\/rectangleint","navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/RectangleInt/width":{"url":"\/documentation\/dotdocument\/rectangleint\/width","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleInt\/width","kind":"symbol","role":"symbol","title":"width","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"width"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"width"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"width","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/title","value":"DOTRectangleInt"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/fragments","value":[{"text":"DOTRectangleInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1width\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleInt~1width\/fragments","value":[{"text":"width","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}