{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camera"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"kind":"symbol","metadata":{"platforms":[{"deprecated":true,"unavailable":false,"beta":false,"message":"Use MultiRangeLivenessViewController instead."}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier"}],"title":"camera","roleHeading":"Instance Property","externalID":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC13ConfigurationC6camera0A7Capture06CameraI0Cvp"},"sections":[],"deprecationSummary":[{"inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/camera","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Default is:"}]},{"type":"codeListing","code":[".init(cameraFacing: .front)"],"syntax":null}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"title":"MagnifEyeLivenessViewController","type":"topic","kind":"symbol","abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"url":"\/documentation\/dotfacecore\/cameraconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"title":"CameraConfiguration","type":"topic","kind":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class":{"deprecated":true,"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class","kind":"symbol","title":"MagnifEyeLivenessViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class/camera":{"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camera","type":"topic","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/camera","kind":"symbol","title":"camera","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"}],"deprecated":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace"},{"value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","op":"replace"}]}]}