{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/tiltangles"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/tiltangles"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTTiltAngles) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"role":"symbol","title":"TiltAngles","externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles","modules":[{"name":"DotFaceCore"}],"roleHeading":"Class"},"abstract":[{"text":"Tilt angles.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/init(pitch:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/pitch"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles/pitch":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"navigatorTitle":[{"text":"pitch","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/pitch","title":"pitch","url":"\/documentation\/dotfacecore\/tiltangles\/pitch","abstract":[{"text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees.","type":"text"}]},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles":{"url":"\/documentation\/dotfacecore\/tiltangles","role":"symbol","title":"TiltAngles","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"text":"Also see ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}]},"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles/description":{"url":"\/documentation\/dotfacecore\/tiltangles\/description","role":"symbol","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/description","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles/init(pitch:)":{"role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"pitch","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(pitch:)","navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/tiltangles\/init(pitch:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/init(pitch:)"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"type":"link","title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTTiltAngles"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTTiltAngles"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTiltAngles"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/pitch"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles\/init(pitch:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTTiltAngles","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"pitch","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1pitch\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1pitch\/fragments","value":[{"text":"pitch","kind":"identifier"}]},{"op":"replace","value":"DOTTiltAngles","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTiltAngles"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1description\/title","op":"replace","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1description\/fragments"},{"op":"replace","value":"initWithPitch:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1init(pitch:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPitch:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles~1init(pitch:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}