{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillTransition(to:with:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"metadata":{"navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","extendedModule":"DotFaceCore","externalID":"c:@CM@DotFaceCore@objc(cs)DOTFSmileLivenessViewController(im)viewWillTransitionToSize:withTransitionCoordinator:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"symbolKind":"method","title":"viewWillTransition(to:with:)","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"coordinator","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwilltransition(to:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwilltransition(to:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"abstract":[{"type":"text","text":"UI Smile Liveness component."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","kind":"symbol","title":"SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewWillTransition(to:with:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillTransition(to:with:)","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwilltransition(to:with:)","abstract":[],"navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"title":"viewWillTransition(to:with:)","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewWillTransitionToSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withTransitionCoordinator:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinator","text":"id<UIViewControllerTransitionCoordinator>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"coordinator","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFSmileLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title"},{"value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle"},{"op":"replace","value":"viewWillTransitionToSize:withTransitionCoordinator:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillTransition(to:with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillTransition(to:with:)\/fragments"}]}]}