{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/template"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"template","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore0B8DetectorC0B0C8templateAA8TemplateCSgvp","symbolKind":"property","title":"template","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Face template. It can be used for face matching. This is evaluated only if it is specified in "},{"type":"codeVoice","code":"FaceDetectionQuery"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"template","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/face\/template"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/template":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"template","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":"?","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face template. It can be used for face matching. This is evaluated only if it is specified in "},{"code":"FaceDetectionQuery","type":"codeVoice"},{"type":"text","text":"."}],"title":"template","url":"\/documentation\/dotfacecore\/facedetector\/face\/template","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/template"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Face"}],"title":"FaceDetector.Face","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","url":"\/documentation\/dotfacecore\/facedetector\/face","abstract":[{"type":"text","text":"Detected face in the image."}],"navigatorTitle":[{"kind":"identifier","text":"Face"}]},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Face template."}],"url":"\/documentation\/dotfacecore\/template","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Template","kind":"identifier"}],"type":"topic","title":"Template","navigatorTitle":[{"text":"Template","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title","value":"DOTFTemplate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments","value":[{"kind":"identifier","text":"DOTFTemplate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFTemplate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}