{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessControlProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AccessControlProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","kind":"typeIdentifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/accessControlProtocol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/accesscontrolprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/accesscontrolprotocol"]}],"metadata":{"platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false}],"navigatorTitle":[{"kind":"identifier","text":"accessControlProtocol"}],"title":"accessControlProtocol","externalID":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper(py)accessControlProtocol","symbolKind":"property","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper"]]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","kind":"symbol","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper","title":"AccessControlProtocolWrapper","role":"symbol","type":"topic","abstract":[{"text":"Access Control protocol wrapper.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocolWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocolWrapper"}]},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper/accessControlProtocol":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"accessControlProtocol"}],"kind":"symbol","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/accesscontrolprotocol","type":"topic","title":"accessControlProtocol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/accessControlProtocol"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"abstract":[{"text":"Access Control protocol.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"title":"AccessControlProtocol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"accessControlProtocol","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"accessControlProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","text":"DOTNAccessControlProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlProtocol"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/title","value":"DOTNAccessControlProtocolWrapper","op":"replace"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocolWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/fragments"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocolWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/navigatorTitle"},{"op":"replace","value":"accessControlProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1accessControlProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"accessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1accessControlProtocol\/fragments"},{"op":"replace","value":"DOTNAccessControlProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}