{"abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"BaseDocumentAutoCaptureViewController.Configuration","externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"extendedModule":"DotDocument","role":"symbol","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDBaseDocumentAutoCaptureConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"title":"Structures","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults"],"anchor":"Structures"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/autoCapture","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/barcodeValidation","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/camera","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/common","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/mrzValidation","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/validationMode"],"anchor":"Instance-Properties"}],"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/camera":{"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/camera","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/camera","title":"camera"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/common":{"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"code":".init()","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/common","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/common","title":"common"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/qualityattributethresholds","kind":"symbol","title":"qualityAttributeThresholds","abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"code":".standard","type":"codeVoice"},{"type":"text","text":" preset."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)":{"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:qualityattributethresholds:validationmode:mrzvalidation:barcodevalidation:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds","text":"DocumentAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mrzValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","text":"MrzValidation"},{"kind":"text","text":", "},{"kind":"externalParam","text":"barcodeValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation","text":"BarcodeValidation"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)","title":"init(common:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:)"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/init()":{"abstract":[{"text":"Create the document auto capture configuration with default values.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/init()","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/init()","title":"init()"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/autoCapture":{"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/autocapture","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/autoCapture","title":"autoCapture"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","title":"BaseDocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/barcodeValidation":{"abstract":[{"text":"Specify barcode validation. Default is ","type":"text"},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/barcodevalidation","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation","text":"BarcodeValidation"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/barcodeValidation","title":"barcodeValidation"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","type":"topic","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"BaseDocumentAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/validationMode":{"title":"validationMode","abstract":[{"text":"Specify validation mode. Default is ","type":"text"},{"code":".standard","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/validationMode","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/validationmode"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/description":{"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/description","kind":"symbol","abstract":[],"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/description","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/mrzValidation":{"abstract":[{"text":"Specify MRZ validation. Default is ","type":"text"},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/mrzvalidation","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","text":"MrzValidation"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/mrzValidation","title":"mrzValidation"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/Defaults":{"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults","title":"BaseDocumentAutoCaptureViewController.Configuration.Defaults"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDBaseDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}]}]}]}