{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@CM@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController(im)viewDidAppear:","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"extendedModule":"DotDocument","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"viewDidAppear(_:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidAppear(_:)"},"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"navigatorTitle":[{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","title":"BaseDocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/viewDidAppear(_:)":{"abstract":[],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/viewdidappear(_:)","role":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/viewDidAppear(_:)","kind":"symbol","type":"topic","title":"viewDidAppear(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewDidAppear:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidAppear:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDBaseDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle"},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidAppear(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1viewDidAppear(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}