{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handPosition"},{"text":": ","kind":"text"},{"text":"HandPosition","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Hand position, either left or right.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/handposition"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/handPosition","interfaceLanguage":"swift"},"metadata":{"externalID":"s:11DotPalmCore0B8DetectorC0B0C12handPositionAA04HandF0Ovp","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"handPosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","text":"HandPosition","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"handPosition","role":"symbol","modules":[{"name":"DotPalmCore"}],"symbolKind":"property"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"title":"PalmDetector","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","role":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","abstract":[{"type":"text","text":"version: 8.14.0"}],"kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/handPosition":{"role":"symbol","title":"handPosition","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","text":"HandPosition"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/handposition","abstract":[{"type":"text","text":"Hand position, either left or right."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/handPosition","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"url":"\/documentation\/dotpalmcore\/handposition","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","abstract":[{"text":"Represents the position of a hand when detecting palm.","type":"text"}],"navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"title":"HandPosition","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HandPosition","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"abstract":[{"text":"Result of the palm detection process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Palm"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","role":"symbol","type":"topic","title":"PalmDetector.Palm","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Palm"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"text":"DOTPPalmDetector","kind":"identifier"}]},{"op":"replace","value":"DOTPHandPosition","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title"},{"value":[{"text":"DOTPHandPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}