{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","text":"DetectionPosition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"PalmQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","text":"HandPosition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation","text":"HandOrientation","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality"},{"text":", ","kind":"text"},{"text":"handPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HandPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition"},{"text":", ","kind":"text"},{"text":"handOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HandOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation"},{"text":")","kind":"text"}],"title":"init(detectionPosition:confidence:quality:handPosition:handOrientation:)","symbolKind":"init","roleHeading":"Initializer","externalID":"s:11DotPalmCore0B8DetectorC0B0C17detectionPosition10confidence7quality04handF00I11OrientationAeA09DetectionF0C_SdAA0B7QualityCAA04HandF0OAA0mJ0Otcfc","modules":[{"name":"DotPalmCore"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/init(detectionposition:confidence:quality:handposition:handorientation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:quality:handPosition:handOrientation:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"abstract":[{"text":"Represents the position of a hand when detecting palm.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandPosition","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","title":"HandPosition","navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/handposition","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}],"url":"\/documentation\/dotpalmcore\/palmquality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","kind":"symbol","title":"PalmQuality","abstract":[{"text":"Palm quality.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmQuality"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"abstract":[{"text":"Position of the palm in the image.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","title":"DetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"url":"\/documentation\/dotpalmcore\/detectionposition","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"title":"PalmDetector.Palm","type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","kind":"symbol","abstract":[{"type":"text","text":"Result of the palm detection process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"title":"PalmDetector","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}]},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"url":"\/documentation\/dotpalmcore\/handorientation","type":"topic","abstract":[{"type":"text","text":"Represents the orientation of a hand when detecting palm."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HandOrientation"}],"navigatorTitle":[{"kind":"identifier","text":"HandOrientation"}],"title":"HandOrientation","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/init(detectionPosition:confidence:quality:handPosition:handOrientation:)":{"title":"init(detectionPosition:confidence:quality:handPosition:handOrientation:)","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:quality:handPosition:handOrientation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"PalmQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","text":"HandPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation","text":"HandOrientation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/init(detectionposition:confidence:quality:handposition:handorientation:)","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"DOTPHandPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title"},{"value":[{"kind":"identifier","text":"DOTPHandPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments"},{"value":[{"kind":"identifier","text":"DOTPHandPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/navigatorTitle"},{"value":"DOTPPalmQuality","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title"},{"value":[{"text":"DOTPPalmQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle"},{"value":"DOTPDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title"},{"value":[{"text":"DOTPDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments"},{"value":[{"text":"DOTPDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/navigatorTitle"},{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"},{"value":"DOTPHandOrientation","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title"},{"value":[{"text":"DOTPHandOrientation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments"},{"value":[{"kind":"identifier","text":"DOTPHandOrientation"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}