{"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/init(detectionposition:confidence:imageparameters:palmquality:handposition:handorientation:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"detectionPosition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","text":"DetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageParameters"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"palmQuality"},{"kind":"text","text":": "},{"text":"PalmQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","text":"HandPosition","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"handOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HandOrientation","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"detectionPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","text":"DetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageParameters"},{"kind":"text","text":": "},{"text":"ImageParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"palmQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"PalmQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"handPosition"},{"text":": ","kind":"text"},{"text":"HandPosition","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handOrientation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation","kind":"typeIdentifier","text":"HandOrientation"},{"text":")","kind":"text"}],"externalID":"s:11DotPalmCore0B8DetectorC0B0C17detectionPosition10confidence15imageParameters11palmQuality04handF00L11OrientationAeA09DetectionF0C_SdAA05ImageI0CAA0bK0CAA04HandF0OAA0pM0Otcfc","roleHeading":"Initializer","title":"init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Palm"}],"abstract":[{"type":"text","text":"Result of the palm detection process."}],"role":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","title":"PalmDetector.Palm","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","title":"PalmDetector","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/init(detectionposition:confidence:imageparameters:palmquality:handposition:handorientation:)","title":"init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageParameters"},{"text":": ","kind":"text"},{"text":"ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters"},{"text":", ","kind":"text"},{"text":"palmQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"PalmQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handPosition","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HandPosition","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handOrientation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation","text":"HandOrientation"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"role":"symbol","abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","title":"ImageParameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotpalmcore\/imageparameters","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","role":"symbol","abstract":[{"type":"text","text":"Palm quality."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmquality","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmQuality","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}],"kind":"symbol","title":"PalmQuality"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"HandPosition","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/handposition","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","title":"HandPosition","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Represents the position of a hand when detecting palm."}]},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","role":"symbol","abstract":[{"text":"Represents the orientation of a hand when detecting palm.","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/handorientation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HandOrientation"}],"navigatorTitle":[{"text":"HandOrientation","kind":"identifier"}],"kind":"symbol","title":"HandOrientation"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"url":"\/documentation\/dotpalmcore\/detectionposition","type":"topic","role":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"title":"DetectionPosition","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"Position of the palm in the image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","value":"DOTPImageParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments","value":[{"kind":"identifier","text":"DOTPImageParameters"}]},{"value":"DOTPPalmQuality","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmQuality"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments"},{"value":"DOTPHandPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments","value":[{"text":"DOTPHandPosition","kind":"identifier"}],"op":"replace"},{"value":"DOTPHandOrientation","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments","value":[{"kind":"identifier","text":"DOTPHandOrientation"}],"op":"replace"},{"value":"DOTPDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}