{"metadata":{"title":"init(detectionPosition:confidence:imageParameters:)","role":"symbol","symbolKind":"init","modules":[{"name":"DotPalmCore"}],"roleHeading":"Initializer","externalID":"s:11DotPalmCore0B8DetectorC0B0C17detectionPosition10confidence15imageParametersAeA09DetectionF0C_SdAA05ImageI0Ctcfc","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"detectionPosition"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"confidence"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"imageParameters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","text":"ImageParameters","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:imageParameters:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/init(detectionposition:confidence:imageparameters:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","kind":"typeIdentifier","text":"DetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","text":"ImageParameters"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 8.7.1"}],"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"kind":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmDetector"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"title":"PalmDetector","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"abstract":[{"type":"text","text":"Result of the palm detection process."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm","title":"PalmDetector.Palm","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/init(detectionPosition:confidence:imageParameters:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:imageParameters:)","abstract":[],"title":"init(detectionPosition:confidence:imageParameters:)","kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/init(detectionposition:confidence:imageparameters:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"},{"kind":"text","text":", "},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageParameters"},{"kind":"text","text":": "},{"text":"ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","url":"\/documentation\/dotpalmcore\/detectionposition","title":"DetectionPosition","abstract":[{"type":"text","text":"Position of the palm in the image."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imageparameters","title":"ImageParameters","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","value":"DOTPDetectionPosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","value":"DOTPImageParameters"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments","value":[{"text":"DOTPImageParameters","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}