{"metadata":{"symbolKind":"property","externalID":"s:11DotPalmCore0B8DetectorC0B0C7qualityAA0B7QualityCvp","role":"symbol","roleHeading":"Instance Property","title":"quality","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality"}],"modules":[{"name":"DotPalmCore"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/quality"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/quality","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"Palm quality attributes.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"navigatorTitle":[{"text":"Palm","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"title":"PalmDetector.Palm","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"title":"PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","role":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/quality":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/quality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/quality","type":"topic","role":"symbol","title":"quality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"PalmQuality","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Palm quality attributes.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"abstract":[{"type":"text","text":"Palm quality."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmQuality"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}],"role":"symbol","kind":"symbol","title":"PalmQuality","url":"\/documentation\/dotpalmcore\/palmquality","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"},{"value":"DOTPPalmQuality","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle"}]}]}