{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Instance Method","title":"init","externalID":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotnfclibraryconfiguration\/init"]}],"sections":[],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/DotNfcLibraryConfiguration/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration\/init","url":"\/documentation\/dotpalmcore\/dotnfclibraryconfiguration\/init","title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotNfcLibraryConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","title":"DotNfcLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotnfclibraryconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"abstract":[{"type":"text","text":"NFC library configuration."}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotNfcLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/title"},{"value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/fragments"},{"value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}