{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil)"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/commonconfiguration\/init(sessiontoken:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/commonconfiguration\/init(sessiontoken:)"]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration(im)initWithSessionToken:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"initWithSessionToken:","kind":"identifier"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"title":"init(sessionToken:)","role":"symbol","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration"]]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/init(sessionToken:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/CommonConfiguration/init(sessionToken:)":{"type":"topic","title":"init(sessionToken:)","abstract":[],"url":"\/documentation\/dotdocument\/commonconfiguration\/init(sessiontoken:)","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/init(sessionToken:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"url":"\/documentation\/dotdocument\/commonconfiguration","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","kind":"symbol","role":"symbol","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"abstract":[{"text":"Common configuration for all components.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithSessionToken:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithSessionToken:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1init(sessionToken:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1init(sessionToken:)\/fragments"},{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle"}]}]}