{"kind":"symbol","metadata":{"roleHeading":"Type Property","role":"symbol","modules":[{"name":"DotDocument"}],"title":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"}],"symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDSizeTooSmallValidator(cpy)defaultMinEdgeLengthToImageShorterSideRatioThreshold"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Default threshold is 0.43."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"]]},"variants":[{"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/defaultMinEdgeLengthToImageShorterSideRatioThreshold":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","title":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","navigatorTitle":[{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/defaultminedgelengthtoimageshortersideratiothreshold","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/defaultMinEdgeLengthToImageShorterSideRatioThreshold","abstract":[{"text":"Default threshold is 0.43.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","type":"topic","url":"\/documentation\/dotdocument\/sizetoosmallvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate size of the detected document."}],"kind":"symbol","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/title","op":"replace","value":"defaultMinEdgeLengthToImageShorterSideRatioThreshold"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1defaultMinEdgeLengthToImageShorterSideRatioThreshold\/fragments","op":"replace","value":[{"text":"defaultMinEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","op":"replace","value":"DOTDSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","op":"replace","value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}]}]}]}