{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat"]]},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"max","kind":"identifier"}],"title":"max","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(py)max"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/max","interfaceLanguage":"swift"},"abstract":[{"text":"Maximal interval value.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervalfloat\/max"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/intervalfloat\/max"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"max","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}]}]}],"references":{"doc://DotDocument/documentation/DotDocument/IntervalFloat":{"kind":"symbol","title":"IntervalFloat","url":"\/documentation\/dotdocument\/intervalfloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/IntervalFloat/max":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/max","role":"symbol","type":"topic","abstract":[{"text":"Maximal interval value.","type":"text"}],"url":"\/documentation\/dotdocument\/intervalfloat\/max","title":"max","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"max","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"max"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"max"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"max"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTIntervalFloat","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat~1max\/title","value":"max"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat~1max\/fragments","value":[{"text":"max","kind":"identifier"}]}]}]}