{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervaldouble\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/intervaldouble\/hash"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/hash"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble(py)hash","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Property","title":"hash"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble"]]},"references":{"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","url":"\/documentation\/dotdocument\/intervaldouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"type":"topic","kind":"symbol","role":"symbol","title":"IntervalDouble"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotdocument\/intervaldouble\/hash","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/hash","title":"hash","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"hash","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/navigatorTitle"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1hash\/fragments"}]}]}