{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"]]},"kind":"symbol","metadata":{"title":"DotFaceModuleCategory.expressionNeutral","role":"symbol","externalID":"c:@M@DotFaceCore@E@DotFaceModuleCategory@DotFaceModuleCategoryExpressionNeutral","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"expressionNeutral","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DotFaceModuleCategoryExpressionNeutral","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/expressionNeutral"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/expressionneutral"]},{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/expressionneutral"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/expressionNeutral":{"navigatorTitle":[{"text":"DotFaceModuleCategoryExpressionNeutral","kind":"identifier"}],"title":"DotFaceModuleCategory.expressionNeutral","url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/expressionneutral","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/expressionNeutral"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","url":"\/documentation\/dotfacecore\/dotfacemodulecategory","title":"DotFaceModuleCategory","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"}],"type":"topic","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" module category."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceModuleCategoryExpressionNeutral"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleCategoryExpressionNeutral","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotFaceModuleCategoryExpressionNeutral","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1expressionNeutral\/title","value":"DotFaceModuleCategoryExpressionNeutral","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceModuleCategoryExpressionNeutral"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1expressionNeutral\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","value":"DotFaceModuleCategory"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","value":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}