{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkError","doc:\/\/DotFaceCore\/10Foundation14LocalizedErrorP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/s5ErrorP","doc:\/\/DotFaceCore\/s8SendableP"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk"]]},"sections":[],"metadata":{"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"DotSdk.Error","role":"symbol","symbolKind":"enum","navigatorTitle":[{"text":"Error","kind":"identifier"}],"externalID":"s:7DotCore0A3SdkC5ErrorO"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/initializationFailed(internalError:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/licenseDataNotSet","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/transactionCountingTokenIsNil","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/errorMessage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/internalError"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/CustomStringConvertible-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/DotSdkError-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/Error-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/LocalizedError-Implementations"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/transactionCountingTokenVerificationFailed(internalError:)":{"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","url":"\/documentation\/dotfacecore\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)","title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenVerificationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/DotSdkError-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/DotSdkError-Implementations","title":"DotSdkError Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdk\/error\/dotsdkerror-implementations"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.17.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/internalError":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdk\/error\/internalerror","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/internalError","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"title":"internalError","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"url":"\/documentation\/dotfacecore\/dotsdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","role":"symbol","title":"DotSdk"},"doc://DotFaceCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/DotFaceCore\/s8SendableP"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error":{"title":"DotSdk.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotsdk\/error"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/Error-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/Error-Implementations","role":"collectionGroup","title":"Error Implementations","url":"\/documentation\/dotfacecore\/dotsdk\/error\/error-implementations","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/LocalizedError-Implementations":{"kind":"article","title":"LocalizedError Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/dotfacecore\/dotsdk\/error\/localizederror-implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/LocalizedError-Implementations","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/CustomStringConvertible-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdk\/error\/customstringconvertible-implementations","type":"topic","title":"CustomStringConvertible Implementations","kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/CustomStringConvertible-Implementations"},"doc://DotFaceCore/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/DotFaceCore\/s5ErrorP"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/errorMessage":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/errorMessage","title":"errorMessage","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotfacecore\/dotsdk\/error\/errormessage"},"doc://DotFaceCore/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","identifier":"doc:\/\/DotFaceCore\/10Foundation14LocalizedErrorP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/licenseDataNotSet":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseDataNotSet","kind":"identifier"}],"title":"DotSdk.Error.licenseDataNotSet","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdk\/error\/licensedatanotset","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/licenseDataNotSet"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/initializationFailed(internalError:)":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"DotSdk.Error.initializationFailed(internalError:)","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/initializationFailed(internalError:)","url":"\/documentation\/dotfacecore\/dotsdk\/error\/initializationfailed(internalerror:)","kind":"symbol","abstract":[],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkError":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkError","type":"topic","abstract":[],"navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"title":"DotSdkError","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotsdkerror"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/transactionCountingTokenIsNil":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenIsNil"}],"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdk\/error\/transactioncountingtokenisnil","type":"topic","title":"DotSdk.Error.transactionCountingTokenIsNil","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/transactionCountingTokenIsNil"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotSdk","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}