{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@DotFaceCommons@E@DOTPlaceholderType@DOTPlaceholderTypeCircle","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTPlaceholderTypeCircle"}],"roleHeading":"Case","role":"symbol","modules":[{"name":"DotFaceCore"}],"title":"PlaceholderType.circle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"circle"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/circle","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"circle","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/placeholdertype\/circle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/placeholdertype\/circle"]}],"abstract":[{"type":"text","text":"Circular placeholder."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType":{"kind":"symbol","title":"PlaceholderType","role":"symbol","url":"\/documentation\/dotfacecore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/circle":{"navigatorTitle":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}],"type":"topic","title":"PlaceholderType.circle","kind":"symbol","url":"\/documentation\/dotfacecore\/placeholdertype\/circle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"circle","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/circle","abstract":[{"type":"text","text":"Circular placeholder."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTPlaceholderTypeCircle","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTPlaceholderTypeCircle"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPlaceholderType","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPlaceholderType"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPlaceholderType"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/navigatorTitle","op":"replace"},{"value":"DOTPlaceholderTypeCircle","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType~1circle\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPlaceholderTypeCircle"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType~1circle\/fragments","op":"replace"}]}]}