{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults\/barcodeValidation"},"sections":[],"metadata":{"title":"barcodeValidation","symbolKind":"property","roleHeading":"Type Property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeValidation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BarcodeValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation"}],"modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV17barcodeValidationAA07BarcodeK0OvpZ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeValidation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BarcodeValidation","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults"]]},"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults\/barcodevalidation"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/Defaults":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"title":"BaseDocumentAutoCaptureViewController.Configuration.Defaults","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults","abstract":[],"navigatorTitle":[{"text":"Defaults","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/Defaults/barcodeValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults\/barcodeValidation","title":"barcodeValidation","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeValidation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation","text":"BarcodeValidation","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults\/barcodevalidation"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","title":"BarcodeValidation","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeValidation","kind":"identifier"}],"abstract":[{"text":"Mode of barcode validation.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"BarcodeValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcodevalidation"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"BaseDocumentAutoCaptureViewController.Configuration","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"title":"BaseDocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","abstract":[{"text":"UI component for capturing document images with customizable UI.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","value":"DOTDBarcodeValidation"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","value":"DOTDBaseDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}