{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class"],"anchor":"Classes","title":"Classes","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/init(modules:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/modules-swift.property"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"title":"DotFingersLibraryConfiguration"},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Fingers library configuration.","type":"text"}],"kind":"symbol","references":{"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration":{"title":"DotFingersLibraryConfiguration","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","abstract":[{"type":"text","text":"Fingers library configuration."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class":{"title":"DotFingersLibraryConfiguration.Modules","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class","abstract":[{"type":"text","text":"Fingers library module configuration."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/modules-swift.property":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/modules-swift.property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"title":"modules","type":"topic","abstract":[{"type":"text","text":"Module configuration."}],"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.property"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/init(modules:)":{"title":"init(modules:)","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/init(modules:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/init(modules:)","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}]},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFingersLibraryConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/modules-swift.property"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/init(modules:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/navigatorTitle"},{"value":"modules","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration~1modules-swift.property\/title"},{"value":[{"kind":"identifier","text":"modules"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration~1modules-swift.property\/fragments"},{"value":"initWithModules:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration~1init(modules:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration~1init(modules:)\/fragments"}]}]}