{"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessResult","roleHeading":"Class","symbolKind":"class","title":"MagnifEyeLivenessResult","role":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessResult","kind":"identifier"}]},"seeAlsoSections":[{"title":"MagnifEye liveness result","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition"],"anchor":"MagnifEye-liveness-result","generated":true}],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessresult"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"abstract":[{"type":"text","text":"The final result of the MagnifEye liveness process."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLMagnifEyeLivenessResult) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessResult"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/init(image:face:content:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/content","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/face","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/image"],"anchor":"Instance-Properties","generated":true}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessResult/init(image:face:content:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"title":"init(image:face:content:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithImage:face:content:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessresult\/init(image:face:content:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/init(image:face:content:)"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessResult":{"title":"MagnifEyeLivenessResult","url":"\/documentation\/dotfacelite\/magnifeyelivenessresult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"abstract":[{"text":"The final result of the MagnifEye liveness process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessResult","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition":{"title":"DetectionPosition","url":"\/documentation\/dotfacelite\/detectionposition","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"title":"FaceAutoCaptureDetection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessResult/description":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessresult\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","title":"description","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/description","abstract":[],"role":"symbol"},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessResult/face":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"}],"title":"face","role":"symbol","abstract":[{"text":"Face detection result.","type":"text"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessresult\/face","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/face","type":"topic","navigatorTitle":[{"kind":"identifier","text":"face"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessResult/content":{"title":"content","url":"\/documentation\/dotfacelite\/magnifeyelivenessresult\/content","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"abstract":[{"text":"Binary content for server-side evaluation.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/content","type":"topic","kind":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}]},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessResult/image":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"title":"image","role":"symbol","abstract":[{"type":"text","text":"Captured face image."}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessresult\/image","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/image","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFLMagnifEyeLivenessResult"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessResult","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessResult","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/content","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/face","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/image"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult\/init(image:face:content:)"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"anchor":"MagnifEye-liveness-result","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition"],"title":"MagnifEye liveness result","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFLMagnifEyeLivenessResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1init(image:face:content:)\/title","op":"replace","value":"initWithImage:face:content:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1init(image:face:content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:content:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/title","value":"DOTFLMagnifEyeLivenessResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1face\/title","value":"face"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1face\/fragments","op":"replace","value":[{"text":"face","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1content\/title","op":"replace","value":"content"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1content\/fragments","op":"replace","value":[{"text":"content","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1image\/title","op":"replace","value":"image"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult~1image\/fragments","op":"replace","value":[{"text":"image","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}