{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships","type":"conformsTo"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"title":"Face evaluation","generated":true}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"title":"ExpressionQuery","roleHeading":"Class","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ExpressionQuery","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init(eyes:evaluateMouth:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/evaluateMouth","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/eyes"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFExpressionQuery) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/expressionquery"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/expressionquery"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery/init()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init()","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"url":"\/documentation\/dotfacecore\/expressionquery\/init()","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"url":"\/documentation\/dotfacecore\/wearables","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","title":"Wearables","abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Wearables"}]},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"url":"\/documentation\/dotfacecore\/wearablesquery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","title":"WearablesQuery","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WearablesQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery/evaluateMouth":{"navigatorTitle":[{"kind":"identifier","text":"evaluateMouth"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Mouth evaluation flag.","type":"text"}],"title":"evaluateMouth","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/evaluateMouth","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"evaluateMouth","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfacecore\/expressionquery\/evaluatemouth"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"url":"\/documentation\/dotfacecore\/eyesexpression","kind":"symbol","type":"topic","navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","title":"EyesExpression","abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyesExpression","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"url":"\/documentation\/dotfacecore\/facequalityquery","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","title":"FaceQualityQuery","abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQualityQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"url":"\/documentation\/dotfacecore\/facequality","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","title":"FaceQuality","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceQuality","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyesExpressionQuery","kind":"identifier"}],"title":"EyesExpressionQuery","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","url":"\/documentation\/dotfacecore\/eyesexpressionquery","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery/init(eyes:evaluateMouth:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithEyes:evaluateMouth:"}],"kind":"symbol","role":"symbol","abstract":[],"title":"init(eyes:evaluateMouth:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init(eyes:evaluateMouth:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"eyes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery","text":"EyesExpressionQuery"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"evaluateMouth"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/expressionquery\/init(eyes:evaluatemouth:)"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"abstract":[{"text":"Face attribute for the glasses.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Glasses","kind":"identifier"}],"title":"Glasses","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","url":"\/documentation\/dotfacecore\/glasses","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"url":"\/documentation\/dotfacecore\/faceattribute","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","title":"FaceAttribute","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}]},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery/eyes":{"navigatorTitle":[{"text":"eyes","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Eyes expression query."}],"title":"eyes","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/eyes","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery","text":"EyesExpressionQuery"}],"url":"\/documentation\/dotfacecore\/expressionquery\/eyes"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}],"navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseAttribute"}],"kind":"symbol","title":"HeadPoseAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","role":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"url":"\/documentation\/dotfacecore\/headpose","kind":"symbol","type":"topic","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","title":"HeadPose","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}]},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/expression","abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Expression","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","navigatorTitle":[{"kind":"identifier","text":"Expression"}],"title":"Expression"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"url":"\/documentation\/dotfacecore\/faceimagequalityquery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","title":"FaceImageQualityQuery","abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}]},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"kind":"symbol","title":"FaceAspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","url":"\/documentation\/dotfacecore\/faceaspects","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"url":"\/documentation\/dotfacecore\/faceimagequality","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","title":"FaceImageQuality","abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}],"title":"ExpressionQuery","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","url":"\/documentation\/dotfacecore\/expressionquery","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"url":"\/documentation\/dotfacecore\/headposequery","kind":"symbol","type":"topic","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"title":"HeadPoseQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.0"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFExpressionQuery"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/evaluateMouth","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/eyes"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init(eyes:evaluateMouth:)"],"title":"Instance Methods"}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Face evaluation","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFExpressionQuery","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","value":"DOTFWearables"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","op":"replace","value":[{"text":"DOTFWearables","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery","op":"replace"},{"value":[{"text":"DOTFWearablesQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1evaluateMouth\/title","value":"evaluateMouth","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1evaluateMouth\/fragments","value":[{"text":"evaluateMouth","kind":"identifier"}]},{"value":"DOTFEyesExpression","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","value":[{"text":"DOTFEyesExpression","kind":"identifier"}]},{"value":"DOTFFaceQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"value":"DOTFFaceQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title"},{"value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace"},{"value":"DOTFEyesExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}]},{"value":"initWithEyes:evaluateMouth:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1init(eyes:evaluateMouth:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEyes:evaluateMouth:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1init(eyes:evaluateMouth:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1eyes\/title","value":"eyes","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1eyes\/fragments","value":[{"kind":"identifier","text":"eyes"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","value":"DOTFHeadPose"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPose"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"kind":"identifier","text":"DOTFExpression"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}]},{"value":"DOTFFaceAspects","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"op":"replace","value":"DOTFFaceImageQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","op":"replace","value":"DOTFExpressionQuery"},{"value":[{"text":"DOTFExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","value":"DOTFHeadPoseQuery"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"}]}]}