{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/eyeGazeLiveness","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}],"title":"DotFaceModuleId.eyeGazeLiveness","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}],"externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdEyeGazeLiveness","symbolKind":"case","role":"symbol"},"variants":[{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/eyegazeliveness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/eyegazeliveness"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/DotFaceModuleId":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleId"}],"title":"DotFaceModuleId","kind":"symbol","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfacemoduleid","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/eyeGazeLiveness":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/eyeGazeLiveness","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacemoduleid\/eyegazeliveness","type":"topic","abstract":[],"title":"DotFaceModuleId.eyeGazeLiveness"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceModuleIdEyeGazeLiveness","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/title","op":"replace","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/fragments","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/navigatorTitle","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1eyeGazeLiveness\/title","op":"replace","value":"DotFaceModuleIdEyeGazeLiveness"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1eyeGazeLiveness\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}