{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory\/create(bgraRawImage:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/ciimagefactory\/create(bgrarawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/ciimagefactory\/create(bgrarawimage:)"]}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" instance."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"title":"create(bgraRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"}],"roleHeading":"Type Method"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory":{"role":"symbol","url":"\/documentation\/dotfacecore\/ciimagefactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory","title":"CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory/create(bgraRawImage:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/ciimagefactory\/create(bgrarawimage:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}],"navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory\/create(bgraRawImage:)","title":"create(bgraRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","kind":"symbol","title":"BgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotfacecore\/bgrarawimage","type":"topic","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"createWithBgraRawImage:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgraRawImage"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/title","op":"replace","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory~1create(bgraRawImage:)\/title","value":"createWithBgraRawImage:"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory~1create(bgraRawImage:)\/fragments","op":"replace"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]}]}]}