{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFRandomEyeGazeLivenessCornersGenerator","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"class","title":"RandomEyeGazeLivenessCornersGenerator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RandomEyeGazeLivenessCornersGenerator","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"text":"RandomEyeGazeLivenessCornersGenerator","kind":"identifier"}]},"abstract":[{"type":"text","text":"Generates random corners for the eye gaze liveness process."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator\/generate(count:)"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFRandomEyeGazeLivenessCornersGenerator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RandomEyeGazeLivenessCornersGenerator","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator","doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFRandomEyeGazeLivenessCornersGenerator/init":{"role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFRandomEyeGazeLivenessCornersGenerator\/init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfrandomeyegazelivenesscornersgenerator\/init","kind":"symbol","title":"init"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCornersGenerator":{"role":"symbol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessCornersGenerator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator","abstract":[{"type":"text","text":"Generates corners for the eye gaze liveness process."}],"navigatorTitle":[{"text":"EyeGazeLivenessCornersGenerator","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator","kind":"symbol","title":"EyeGazeLivenessCornersGenerator"},"doc://DotFaceCore/documentation/DotFaceCore/RandomEyeGazeLivenessCornersGenerator":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RandomEyeGazeLivenessCornersGenerator"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator","abstract":[{"type":"text","text":"Generates random corners for the eye gaze liveness process."}],"navigatorTitle":[{"kind":"identifier","text":"RandomEyeGazeLivenessCornersGenerator"}],"url":"\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator","title":"RandomEyeGazeLivenessCornersGenerator","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/RandomEyeGazeLivenessCornersGenerator/generate(count:)":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator\/generate(count:)","abstract":[{"type":"text","text":"Generate random corners."}],"navigatorTitle":[{"text":"generateWithCount:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator\/generate(count:)","title":"generate(count:)","kind":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTFRandomEyeGazeLivenessCornersGenerator","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFRandomEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFRandomEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFRandomEyeGazeLivenessCornersGenerator\/init","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator\/generate(count:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator"],"title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFRandomEyeGazeLivenessCornersGenerator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFEyeGazeLivenessCornersGenerator","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/title"},{"value":[{"text":"DOTFEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/fragments"},{"value":[{"text":"DOTFEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/navigatorTitle"},{"value":"DOTFRandomEyeGazeLivenessCornersGenerator","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/title"},{"value":[{"kind":"identifier","text":"DOTFRandomEyeGazeLivenessCornersGenerator"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFRandomEyeGazeLivenessCornersGenerator"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator~1generate(count:)\/title","op":"replace","value":"generateWithCount:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator~1generate(count:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"generateWithCount:","kind":"identifier"}]}]}]}