{"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"class","title":"WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}]},"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":" value for Objective-C support.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/init(value:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/value"],"title":"Instance Properties","anchor":"Instance-Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/isEqual(_:)"],"title":"Instance Methods","generated":true}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/wrappedfloat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wrappedfloat"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTWrappedFloat) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat":{"type":"topic","url":"\/documentation\/dotfacecore\/wrappedfloat","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat","kind":"symbol","title":"WrappedFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat/hash":{"abstract":[],"type":"topic","url":"\/documentation\/dotfacecore\/wrappedfloat\/hash","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/hash","kind":"symbol","title":"hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat/isEqual(_:)":{"type":"topic","abstract":[],"title":"isEqual(_:)","kind":"symbol","url":"\/documentation\/dotfacecore\/wrappedfloat\/isequal(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat/init(value:)":{"title":"init(value:)","abstract":[],"url":"\/documentation\/dotfacecore\/wrappedfloat\/init(value:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/init(value:)","type":"topic","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat/description":{"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/description","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfacecore\/wrappedfloat\/description","title":"description","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat/value":{"navigatorTitle":[{"kind":"identifier","text":"value"}],"title":"value","url":"\/documentation\/dotfacecore\/wrappedfloat\/value","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/value","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}]},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTWrappedFloat","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/value"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/init(value:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/isEqual(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTWrappedFloat"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/title","value":"DOTWrappedFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1init(value:)\/title","value":"initWithValue:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1init(value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1value\/title","value":"value","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1value\/fragments","value":[{"kind":"identifier","text":"value"}],"op":"replace"}]}]}