{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/init(modulecategory:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/init(modulecategory:)"]}],"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"moduleCategory","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotFaceModuleCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithModuleCategory:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceModuleCategoryWrapper(im)initWithModuleCategory:","role":"symbol","symbolKind":"init","title":"init(moduleCategory:)","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/init(moduleCategory:)"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"moduleCategory","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotFaceModuleCategory","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategoryWrapper/init(moduleCategory:)":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/init(modulecategory:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"moduleCategory","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotFaceModuleCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"initWithModuleCategory:","kind":"identifier"}],"role":"symbol","type":"topic","title":"init(moduleCategory:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/init(moduleCategory:)","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"title":"DotFaceModuleCategory","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","url":"\/documentation\/dotfacecore\/dotfacemodulecategory","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" module category.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategoryWrapper":{"abstract":[{"type":"text","text":"Wrapped "},{"code":"DotFaceModuleCategory","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper","url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper","title":"DotFaceModuleCategoryWrapper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithModuleCategory:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithModuleCategory:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithModuleCategory:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"moduleCategory"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1init(moduleCategory:)\/title","value":"initWithModuleCategory:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1init(moduleCategory:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModuleCategory:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","value":"DotFaceModuleCategory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","value":[{"text":"DotFaceModuleCategory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/title","value":"DotFaceModuleCategoryWrapper","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/fragments"}]}]}