{"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"init","modules":[{"name":"DotFaceLite"}],"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detection14transformationAeA0ac15DetectionModuleE0C_AA0ac14TransformationjE0CSgtcfc","role":"symbol","title":"init(detection:transformation:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","abstract":[],"title":"init(detection:transformation:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Fingers library module configuration."}],"type":"topic","title":"DotFingersLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersDetectionModuleConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingersdetectionmoduleconfiguration","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersDetectionModuleConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"type":"topic","title":"DotFingersDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"type":"topic","title":"DotFingersLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersTransformationModuleConfiguration":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerstransformationmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"title":"DotFingersTransformationModuleConfiguration","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}