{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC14transformationAA0ac20TransformationModuleE0CSgvp","role":"symbol","title":"transformation","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Fingers library configuration."}],"type":"topic","title":"DotFingersLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersTransformationModuleConfiguration":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerstransformationmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersTransformationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"title":"DotFingersTransformationModuleConfiguration","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Fingers library module configuration."}],"type":"topic","title":"DotFingersLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"url":"\/documentation\/dotfacelite\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","abstract":[],"title":"transformation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"DotFingersLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/title"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/fragments"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersLibraryConfiguration\/navigatorTitle"},{"value":"DotFingersTransformationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/title"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/fragments"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersTransformationModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}