{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/common"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Common configuration for all UI components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/common","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","metadata":{"title":"common","symbolKind":"property","navigatorTitle":[{"text":"common","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"common","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessConfiguration(py)common"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","text":"DOTCommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" * ","kind":"text"},{"text":"common","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration":{"abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"title":"DOTFMagnifEyeLivenessConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration","type":"topic","url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration","fragments":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessConfiguration"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"title":"CommonConfiguration","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Common configuration for all components."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","url":"\/documentation\/dotfacecore\/commonconfiguration","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration/common":{"abstract":[{"text":"Common configuration for all UI components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"kind":"symbol","title":"common","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/common","fragments":[{"text":"common","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/common","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}