{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"DOTCommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration"},{"kind":"text","text":" *) "},{"text":"common","kind":"internalParam"},{"kind":"text","text":" "},{"text":"camera:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTCameraConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"camera"},{"text":" ","kind":"text"},{"text":"faceLibraryComponent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceLibraryComponentConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLibraryComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:isdetectionlayervisible:"]}],"kind":"symbol","abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessConfiguration(im)initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","title":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","interfaceLanguage":"occ"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"title":"CommonConfiguration","abstract":[{"type":"text","text":"Common configuration for all components."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/commonconfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","type":"topic","title":"FaceLibraryComponentConfiguration","abstract":[{"text":"Configuration for face library components.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration/initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"}],"type":"topic","role":"symbol","title":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","kind":"symbol","abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:isdetectionlayervisible:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:camera:faceLibraryComponent:isDetectionLayerVisible:"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration":{"fragments":[{"text":"DOTFMagnifEyeLivenessConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","title":"DOTFMagnifEyeLivenessConfiguration","kind":"symbol","abstract":[{"text":"Configuration options for the UI MagnifEye Liveness component.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"url":"\/documentation\/dotfacecore\/cameraconfiguration","role":"symbol","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"symbol","title":"CameraConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","op":"replace","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","op":"replace","value":"DOTFFaceLibraryComponentConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"}]}]}