{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"query:"},{"kind":"text","text":"("},{"text":"FaceDetectionQuery","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"text":" *) ","kind":"text"},{"text":"query","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"DOTCameraFacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessConfiguration(im)initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"url":"\/documentation\/dotfacecore\/intervaldouble","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"type":"topic","title":"IntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","role":"symbol","url":"\/documentation\/dotfacecore\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"title":"FaceDetectionQuery","kind":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","role":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:":{"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"title":"CameraPreviewScaleType","kind":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","role":"symbol","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration":{"abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"title":"DOTFMagnifEyeLivenessConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration","role":"symbol","url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration","fragments":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"value":"FaceDetectionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"}]}]}