{"abstract":[{"type":"text","text":"Date of expiry from Machine Readable Zone."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/dateofexpiry"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/dateofexpiry"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfExpiry","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword"]]},"metadata":{"modules":[{"name":"DotNfc"}],"title":"dateOfExpiry","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZonePassword(py)dateOfExpiry","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"roleHeading":"Instance Property"},"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/dateOfExpiry":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfExpiry","abstract":[{"type":"text","text":"Date of expiry from Machine Readable Zone."}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/dateofexpiry","title":"dateOfExpiry"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"kind":"symbol","title":"MachineReadableZonePassword","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"dateOfExpiry","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"dateOfExpiry","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"dateOfExpiry","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfExpiry\/title","value":"dateOfExpiry","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfExpiry\/fragments","value":[{"text":"dateOfExpiry","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","value":"DOTNMachineReadableZonePassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"op":"replace"}]}]}