{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDateOfBirth","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDateOfExpiry","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDocumentNumber(internalError:)"],"anchor":"Enumeration-Cases","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/errorMessage","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/internalError"],"anchor":"Instance-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/CustomStringConvertible-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/DotSdkError-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/Error-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/LocalizedError-Implementations"],"anchor":"Default-Implementations","generated":true}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"externalID":"s:6DotNfc27MachineReadableZonePasswordC5ErrorO","modules":[{"name":"DotNfc"}],"title":"MachineReadableZonePassword.Error","symbolKind":"enum","roleHeading":"Enumeration"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkError","doc:\/\/DotNfc\/10Foundation14LocalizedErrorP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/s5ErrorP","doc:\/\/DotNfc\/s8SendableP"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword"]]},"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/invalidDocumentNumber(internalError:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDocumentNumber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDocumentNumber(internalError:)","title":"MachineReadableZonePassword.Error.invalidDocumentNumber(internalError:)","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/invaliddocumentnumber(internalerror:)","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/internalError":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"type":"topic","title":"internalError","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/internalerror","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/internalError","abstract":[]},"doc://DotNfc/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/DotNfc\/s5ErrorP"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/DotSdkError-Implementations":{"title":"DotSdkError Implementations","kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/DotSdkError-Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/dotsdkerror-implementations"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/errorMessage":{"type":"topic","kind":"symbol","role":"symbol","title":"errorMessage","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/errorMessage","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/errormessage"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/invalidDateOfBirth":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDateOfBirth","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDateOfBirth","kind":"identifier"}],"type":"topic","title":"MachineReadableZonePassword.Error.invalidDateOfBirth","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/invaliddateofbirth","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"kind":"symbol","title":"MachineReadableZonePassword","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/CustomStringConvertible-Implementations":{"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/customstringconvertible-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/CustomStringConvertible-Implementations","kind":"article","title":"CustomStringConvertible Implementations","role":"collectionGroup","type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc/DotSdkError":{"kind":"symbol","title":"DotSdkError","navigatorTitle":[{"kind":"identifier","text":"DotSdkError"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkError","url":"\/documentation\/dotnfc\/dotsdkerror","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkError"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/invalidDateOfExpiry":{"title":"MachineReadableZonePassword.Error.invalidDateOfExpiry","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateOfExpiry"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/invaliddateofexpiry","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDateOfExpiry"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/DotNfc\/10Foundation14LocalizedErrorP"},"doc://DotNfc/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s8SendableP"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/Error-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/Error-Implementations","kind":"article","type":"topic","title":"Error Implementations","abstract":[],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/error-implementations"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"abstract":[],"title":"MachineReadableZonePassword.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/LocalizedError-Implementations":{"abstract":[],"kind":"article","title":"LocalizedError Implementations","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/localizederror-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/LocalizedError-Implementations","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace"},{"value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace"},{"value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","op":"replace"},{"value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","op":"replace"}]}]}