{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit\/isequal(_:)"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/isEqual(_:)"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit(im)isEqual:","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/isEqual(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"isEqual(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/isEqual(_:)","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/isequal(_:)","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"title":"MrzElementWithCheckDigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","kind":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","abstract":[{"type":"text","text":"A "},{"code":"MrzElement","type":"codeVoice"},{"text":" with check digit and checksum validitity information.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"isEqual:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1isEqual(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments"}]}]}