{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","symbolKind":"class","title":"CameraConfiguration"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCameraConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/facing","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isPreviewVisible","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isTorchEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isVideoCaptureEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/previewScaleType"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration"]}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/previewScaleType":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Preview scale type. Default is "},{"type":"codeVoice","code":".fit"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/previewscaletype","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/previewScaleType","title":"previewScaleType","navigatorTitle":[{"kind":"identifier","text":"previewScaleType"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol","title":"hash","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/hash","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"facing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"previewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isPreviewVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","title":"init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","navigatorTitle":[{"kind":"identifier","text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/isVideoCaptureEnabled":{"title":"isVideoCaptureEnabled","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/isvideocaptureenabled","role":"symbol","abstract":[{"text":"Use this flag to enable\/disable video capture.","type":"text"},{"text":" ","type":"text"},{"text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session.","type":"text"},{"text":" ","type":"text"},{"text":"The captured video is included exclusively in the binary content of the result. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isVideoCaptureEnabled","navigatorTitle":[{"kind":"identifier","text":"isVideoCaptureEnabled"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/isPreviewVisible":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","title":"isPreviewVisible","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/ispreviewvisible","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isPreviewVisible","navigatorTitle":[{"kind":"identifier","text":"isPreviewVisible"}],"kind":"symbol","abstract":[{"type":"text","text":"Use this flag to show\/hide camera preview. Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/isEqual(_:)":{"title":"isEqual(_:)","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/isequal(_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/facing":{"title":"facing","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/facing","role":"symbol","abstract":[{"type":"text","text":"Front or back camera facing."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/facing","navigatorTitle":[{"kind":"identifier","text":"facing"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"facing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"type":"topic","role":"symbol","title":"CameraConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","url":"\/documentation\/dotpalmcore\/cameraconfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}]},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/description","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/isTorchEnabled":{"title":"isTorchEnabled","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/istorchenabled","role":"symbol","abstract":[{"text":"Use this flag to turn the torch on\/off during the capture process.","type":"text"},{"text":" ","type":"text"},{"text":"Torch will be turned on only if ","type":"text"},{"code":"facing","type":"codeVoice"},{"text":" property is set to ","type":"text"},{"code":".back","type":"codeVoice"},{"text":". Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isTorchEnabled","navigatorTitle":[{"kind":"identifier","text":"isTorchEnabled"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTCameraConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/facing","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isPreviewVisible","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isTorchEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isVideoCaptureEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/previewScaleType"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/isEqual(_:)"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTCameraConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1previewScaleType\/title","value":"previewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1previewScaleType\/fragments","value":[{"kind":"identifier","text":"previewScaleType"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1hash\/title","op":"replace","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/title","value":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}]},{"value":"isVideoCaptureEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isVideoCaptureEnabled\/title","op":"replace"},{"value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isVideoCaptureEnabled\/fragments","op":"replace"},{"value":"isPreviewVisible","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isPreviewVisible\/title","op":"replace"},{"value":[{"text":"isPreviewVisible","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isPreviewVisible\/fragments","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isEqual(_:)\/fragments","op":"replace"},{"value":"facing","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1facing\/title","op":"replace"},{"value":[{"kind":"identifier","text":"facing"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1facing\/fragments","op":"replace"},{"value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1description\/fragments","op":"replace"},{"value":"isTorchEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isTorchEnabled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isTorchEnabled"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1isTorchEnabled\/fragments","op":"replace"}]}]}