{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"metadata":{"symbolKind":"class","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTPointInt","title":"PointInt","navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"roleHeading":"Class"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPointInt) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/init(x:y:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/cgPoint","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/x","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/y"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/from(cgPoint:)"],"generated":true,"anchor":"Type-Methods"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/pointint"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/pointint"]}],"kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PointInt/init(x:y:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/pointint\/init(x:y:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/init(x:y:)","title":"init(x:y:)","navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","title":"isEqual(_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/isEqual(_:)","url":"\/documentation\/dotpalmcore\/pointint\/isequal(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/from(cgPoint:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":") -> ","kind":"text"},{"text":"PointInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/pointint\/from(cgpoint:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/from(cgPoint:)","title":"from(cgPoint:)","navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/y":{"url":"\/documentation\/dotpalmcore\/pointint\/y","navigatorTitle":[{"kind":"identifier","text":"y"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/y","type":"topic","title":"y","kind":"symbol","abstract":[{"text":"Y coordinate.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/pointint\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/description","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/hash":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol","title":"hash","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/hash","url":"\/documentation\/dotpalmcore\/pointint\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/x":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol","title":"x","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/x","url":"\/documentation\/dotpalmcore\/pointint\/x","navigatorTitle":[{"kind":"identifier","text":"x"}],"kind":"symbol","abstract":[{"text":"X coordinate.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/cgPoint":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}],"type":"topic","role":"symbol","title":"cgPoint","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/cgPoint","url":"\/documentation\/dotpalmcore\/pointint\/cgpoint","navigatorTitle":[{"kind":"identifier","text":"cgPoint"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"type":"topic","role":"symbol","title":"PointInt","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt","url":"\/documentation\/dotpalmcore\/pointint","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTPointInt","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/cgPoint","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/x","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/y"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/init(x:y:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/isEqual(_:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/from(cgPoint:)"],"generated":true,"title":"Type Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPointInt","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithX:y:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1init(x:y:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithX:y:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1init(x:y:)\/fragments","op":"replace"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1isEqual(_:)\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1from(cgPoint:)\/title","value":"fromCgPoint:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1from(cgPoint:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1y\/title","value":"y","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1y\/fragments","value":[{"kind":"identifier","text":"y"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1description\/title","value":"description","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1description\/fragments"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1hash\/fragments","op":"replace"},{"op":"replace","value":"x","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1x\/title"},{"op":"replace","value":[{"kind":"identifier","text":"x"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1x\/fragments"},{"op":"replace","value":"cgPoint","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1cgPoint\/title"},{"op":"replace","value":[{"kind":"identifier","text":"cgPoint"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1cgPoint\/fragments"},{"op":"replace","value":"DOTPointInt","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/fragments"},{"value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/navigatorTitle","op":"replace"}]}]}