{"metadata":{"roleHeading":"Class","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt","title":"RectangleInt","navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"symbolKind":"class"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/rectangleint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/rectangleint"]}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTRectangleInt) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/init(left:top:right:bottom:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/bottom","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/cgRect","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/height","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/origin","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/right","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/top","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/width","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/widthToHeightRatio"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/from(cgRect:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/hash":{"title":"hash","url":"\/documentation\/dotpalmcore\/rectangleint\/hash","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/widthToHeightRatio":{"title":"widthToHeightRatio","url":"\/documentation\/dotpalmcore\/rectangleint\/widthtoheightratio","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/widthToHeightRatio","navigatorTitle":[{"kind":"identifier","text":"widthToHeightRatio"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/description":{"title":"description","url":"\/documentation\/dotpalmcore\/rectangleint\/description","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/origin":{"title":"origin","url":"\/documentation\/dotpalmcore\/rectangleint\/origin","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/origin","navigatorTitle":[{"kind":"identifier","text":"origin"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/from(cgRect:)":{"title":"from(cgRect:)","url":"\/documentation\/dotpalmcore\/rectangleint\/from(cgrect:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/from(cgRect:)","navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"RectangleInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/isEqual(_:)":{"title":"isEqual(_:)","url":"\/documentation\/dotpalmcore\/rectangleint\/isequal(_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/left":{"title":"left","url":"\/documentation\/dotpalmcore\/rectangleint\/left","role":"symbol","abstract":[{"text":"Left edge.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/left","navigatorTitle":[{"kind":"identifier","text":"left"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/init(left:top:right:bottom:)":{"title":"init(left:top:right:bottom:)","url":"\/documentation\/dotpalmcore\/rectangleint\/init(left:top:right:bottom:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/init(left:top:right:bottom:)","navigatorTitle":[{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/cgRect":{"title":"cgRect","url":"\/documentation\/dotpalmcore\/rectangleint\/cgrect","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/cgRect","navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/bottom":{"title":"bottom","url":"\/documentation\/dotpalmcore\/rectangleint\/bottom","role":"symbol","abstract":[{"text":"Bottom edge.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/bottom","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/right":{"title":"right","url":"\/documentation\/dotpalmcore\/rectangleint\/right","role":"symbol","abstract":[{"text":"Right edge.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/right","navigatorTitle":[{"kind":"identifier","text":"right"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/width":{"title":"width","url":"\/documentation\/dotpalmcore\/rectangleint\/width","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/width","navigatorTitle":[{"kind":"identifier","text":"width"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/top":{"title":"top","url":"\/documentation\/dotpalmcore\/rectangleint\/top","role":"symbol","abstract":[{"text":"Top edge.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/top","navigatorTitle":[{"kind":"identifier","text":"top"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt":{"title":"RectangleInt","url":"\/documentation\/dotpalmcore\/rectangleint","role":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleInt/height":{"title":"height","url":"\/documentation\/dotpalmcore\/rectangleint\/height","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/height","navigatorTitle":[{"kind":"identifier","text":"height"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTRectangleInt","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/bottom","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/cgRect","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/height","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/origin","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/right","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/top","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/width","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/widthToHeightRatio"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/init(left:top:right:bottom:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/isEqual(_:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleInt\/from(cgRect:)"],"anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTRectangleInt","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1hash\/fragments","op":"replace"},{"value":"widthToHeightRatio","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1widthToHeightRatio\/title","op":"replace"},{"value":[{"kind":"identifier","text":"widthToHeightRatio"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1widthToHeightRatio\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1description\/fragments","op":"replace"},{"value":"origin","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1origin\/title","op":"replace"},{"value":[{"kind":"identifier","text":"origin"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1origin\/fragments","op":"replace"},{"value":"fromCgRect:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1from(cgRect:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgRect:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1from(cgRect:)\/fragments","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1isEqual(_:)\/fragments","op":"replace"},{"value":"left","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1left\/title","op":"replace"},{"value":[{"kind":"identifier","text":"left"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1left\/fragments","op":"replace"},{"value":"initWithLeft:top:right:bottom:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1init(left:top:right:bottom:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1init(left:top:right:bottom:)\/fragments","op":"replace"},{"value":"cgRect","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1cgRect\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cgRect"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1cgRect\/fragments","op":"replace"},{"value":"bottom","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1bottom\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bottom"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1bottom\/fragments","op":"replace"},{"value":"right","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1right\/title","op":"replace"},{"value":[{"kind":"identifier","text":"right"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1right\/fragments","op":"replace"},{"value":"width","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1width\/title","op":"replace"},{"value":[{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1width\/fragments","op":"replace"},{"value":"top","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1top\/title","op":"replace"},{"value":[{"kind":"identifier","text":"top"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1top\/fragments","op":"replace"},{"value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt\/navigatorTitle","op":"replace"},{"value":"height","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1height\/title","op":"replace"},{"value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleInt~1height\/fragments","op":"replace"}]}]}