{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration(py)hash","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"roleHeading":"Instance Property","title":"hash"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/hash"},"variants":[{"paths":["\/documentation\/dotdocument\/commonconfiguration\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/commonconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"abstract":[{"type":"text","text":"Common configuration for all components."}],"role":"symbol","url":"\/documentation\/dotdocument\/commonconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","title":"CommonConfiguration"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration/hash":{"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/commonconfiguration\/hash","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration\/hash","title":"hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration~1hash\/fragments"}]}]}