{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"defaultThreshold","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDHotspotsScoreTooHighValidator(cpy)defaultThreshold","modules":[{"name":"DotDocument"}],"roleHeading":"Type Property","symbolKind":"property"},"abstract":[{"type":"text","text":"Default threshold is 0.008."}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/defaultThreshold","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator/defaultThreshold":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"text":"Default threshold is 0.008.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/defaultThreshold","title":"defaultThreshold","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/defaultthreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","title":"HotspotsScoreTooHighValidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.1.0"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultThreshold","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1defaultThreshold\/title","value":"defaultThreshold"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1defaultThreshold\/fragments","op":"replace"},{"value":"DOTDHotspotsScoreTooHighValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}]}]}]}