{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init(threshold:)"]},{"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init(threshold:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDHotspotsScoreTooHighValidator(im)initWithThreshold:error:","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"role":"symbol","title":"init(threshold:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator/init(threshold:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init(threshold:)","title":"init(threshold:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init(threshold:)","type":"topic","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"kind":"symbol","type":"topic","title":"HotspotsScoreTooHighValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"navigatorTitle":[{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithThreshold:error:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithThreshold:error:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"text":"threshold","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"initWithThreshold:error:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init(threshold:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithThreshold:error:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init(threshold:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator"},{"value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}