{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator"]]},"sections":[],"metadata":{"title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"init","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDHotspotsScoreTooHighValidator(im)init"},"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init()","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator\/init()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator\/init()","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"text":"Initialize with default threshold.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"type":"topic","abstract":[{"text":"Validate hotspots score of the detected document.","type":"text"}],"title":"HotspotsScoreTooHighValidator","url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"navigatorTitle":[{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]}]}]}