{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}],"title":"cameraFacing","roleHeading":"Instance Property","role":"symbol","externalID":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC13ConfigurationC12cameraFacingAA06CameraK0Ovp"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/cameraFacing"},"sections":[],"abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"code":".front","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camerafacing"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class":{"type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"MagnifEyeLivenessViewController.Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","title":"MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","title":"CameraFacing","url":"\/documentation\/dotfacecore\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class/cameraFacing":{"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/camerafacing","abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"code":".front","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/cameraFacing","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"}],"type":"topic","role":"symbol","title":"cameraFacing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}