{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetectionquery\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facedetectionquery\/description"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/description","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery(py)description","title":"description"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/description":{"url":"\/documentation\/dotfacecore\/facedetectionquery\/description","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/description","kind":"symbol","abstract":[],"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"title":"FaceDetectionQuery","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/navigatorTitle","value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace"}]}]}