{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/RawRepresentable-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/camerafacing\/rawrepresentable-implementations"]}],"sections":[],"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing"]]},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/hashValue"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/hash(into:)"],"generated":true}],"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"RawRepresentable Implementations"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"title":"CameraFacing","url":"\/documentation\/dotfacecore\/camerafacing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"kind":"symbol","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/hash(into:)":{"role":"symbol","abstract":[],"kind":"symbol","title":"hash(into:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/hash(into:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"url":"\/documentation\/dotfacecore\/camerafacing\/hash(into:)"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/hashValue":{"kind":"symbol","url":"\/documentation\/dotfacecore\/camerafacing\/hashvalue","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/hashValue","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"abstract":[],"role":"symbol","title":"hashValue"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title"},{"op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments"},{"op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/navigatorTitle"}]}]}