{"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTAutoCaptureConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error"],"title":"Enumerations","generated":true,"anchor":"Enumerations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"roleHeading":"Class","externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","title":"AutoCaptureConfiguration","role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/hash":{"abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/hash","title":"hash","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/hash","role":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/candidateSelectionDurationMillis":{"abstract":[{"text":"Duration of candidate selection phase in milliseconds. Value must be greater than or equal to ","type":"text"},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"candidateSelectionDurationMillis"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/candidateselectiondurationmillis","title":"candidateSelectionDurationMillis","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/description":{"type":"topic","abstract":[],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/description","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/description"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"title":"AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)":{"type":"topic","abstract":[],"title":"init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","kind":"symbol","navigatorTitle":[{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error","title":"AutoCaptureConfiguration.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/isEqual(_:)":{"type":"topic","abstract":[],"title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/isEqual(_:)","kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/isequal(_:)"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/minValidSamplesInRowToStartCandidateSelection":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection","title":"minValidSamplesInRowToStartCandidateSelection","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to "},{"code":"1","type":"codeVoice"},{"type":"text","text":"."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTAutoCaptureConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/title","value":"candidateSelectionDurationMillis","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/fragments","value":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}],"op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1description\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/title","value":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"value":"minValidSamplesInRowToStartCandidateSelection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/title","op":"replace"},{"value":[{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}