{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/init(bytesPointer:size:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytes","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytesPointer","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytesPointerPacked","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/size"]}],"metadata":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"DotFaceCore"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage","title":"BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTBgraRawImage) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/bgrarawimage"]},{"paths":["\/documentation\/dotfacecore\/bgrarawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage/init(bytesPointer:size:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgraRawImageFactory"},{"text":" to create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage\/init(bytespointer:size:)","kind":"symbol","title":"init(bytesPointer:size:)","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/init(bytesPointer:size:)"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage/bytesPointerPacked":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytesPointerPacked","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":">"}],"abstract":[],"navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage\/bytespointerpacked","kind":"symbol","title":"bytesPointerPacked","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytesPointerPacked"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage/bytes":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage\/bytes","kind":"symbol","title":"bytes","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytes"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage/bytesPointer":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bytesPointer","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"kind":"text","text":">"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage\/bytespointer","kind":"symbol","title":"bytesPointer","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytesPointer"},"doc://DotFaceCore/@M@DotCore@objc(pl)_RawImage":{"identifier":"doc:\/\/DotFaceCore\/@M@DotCore@objc(pl)_RawImage","title":"_RawImage","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage","kind":"symbol","title":"BgraRawImage","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage/size":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"size"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage\/size","kind":"symbol","title":"size","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/size"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTBgraRawImage","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytes","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytesPointer","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytesPointerPacked","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/size"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/init(bytesPointer:size:)"]}]},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/@M@DotCore@objc(pl)_RawImage"],"type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTBgraRawImage"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1init(bytesPointer:size:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBytesPointer:size:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytesPointerPacked\/title","op":"replace","value":"bytesPointerPacked"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytesPointerPacked\/fragments","value":[{"text":"bytesPointerPacked","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytes\/title","value":"bytes","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytesPointer\/title","op":"replace","value":"bytesPointer"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytesPointer\/fragments","value":[{"text":"bytesPointer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/fragments"},{"value":"size","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1size\/title"},{"value":[{"text":"size","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1size\/fragments","op":"replace"}]}]}