{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTBgrRawImageFactory) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"sections":[],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImageFactory","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"title":"BgrRawImageFactory","symbolKind":"class","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImageFactory"}]},"seeAlsoSections":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/bgrrawimagefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/bgrrawimagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(ciImage:ciContext:)"]}],"references":{"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory":{"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"url":"\/documentation\/dotfacecore\/cgimagefactory","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","title":"CGImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImageFactory/create(ciImage:ciContext:)":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/bgrrawimagefactory\/create(ciimage:cicontext:)","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"title":"create(ciImage:ciContext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" as a ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(ciImage:ciContext:)","kind":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory":{"type":"topic","url":"\/documentation\/dotfacecore\/ciimagefactory","title":"CIImageFactory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImageFactory":{"title":"BgrRawImageFactory","type":"topic","url":"\/documentation\/dotfacecore\/bgrrawimagefactory","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" from iOS native image types."}]},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/bgrrawimage","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","type":"topic","title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}]},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImageFactory/create(cgImage:)":{"title":"create(cgImage:)","type":"topic","url":"\/documentation\/dotfacecore\/bgrrawimagefactory\/create(cgimage:)","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(cgImage:)","kind":"symbol","role":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as a "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" object."}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTBgrRawImageFactory","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Converting images","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"],"generated":true}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTBgrRawImageFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"DOTCGImageFactory","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/fragments"},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/title","op":"replace","value":"DOTCIImageFactory"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory\/title","value":"DOTBgrRawImageFactory","op":"replace"},{"value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","op":"replace"},{"op":"replace","value":"createWithCgImage:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory~1create(cgImage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory~1create(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCgImage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}