{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"],["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"title":"Conforms To","kind":"relationships"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImageFactory","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CIImageFactory"],"title":"Converting images"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTBgrRawImage) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/init(bytesPointer:size:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/size"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/bgrrawimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/bgrrawimage"]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","modules":[{"name":"DotFaceCore"}]},"references":{"doc://com.innovatrics.dot.face.core/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/@M@DotFaceCore@objc(pl)_RawImage":{"title":"_RawImage","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/@M@DotFaceCore@objc(pl)_RawImage"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CGImageFactory":{"url":"\/documentation\/dotfacecore\/cgimagefactory","title":"CGImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGImageFactory"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CGImageFactory","abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImageFactory":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"type":"topic","title":"BgrRawImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" from iOS native image types."}],"url":"\/documentation\/dotfacecore\/bgrrawimagefactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImageFactory","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImageFactory"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/bgrrawimage","type":"topic","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage/bytes":{"url":"\/documentation\/dotfacecore\/bgrrawimage\/bytes","title":"bytes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/bytes","kind":"symbol","type":"topic","abstract":[{"text":"Raw image data.","type":"text"}]},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CIImageFactory":{"url":"\/documentation\/dotfacecore\/ciimagefactory","title":"CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CIImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CIImageFactory","kind":"symbol","type":"topic","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage/init(bytesPointer:size:)":{"url":"\/documentation\/dotfacecore\/bgrrawimage\/init(bytespointer:size:)","title":"init(bytesPointer:size:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTImageSize"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/init(bytesPointer:size:)","abstract":[{"type":"text","text":"Do not use this, use "},{"code":"BgrRawImageFactory","type":"codeVoice"},{"text":" to create ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage/size":{"url":"\/documentation\/dotfacecore\/bgrrawimage\/size","title":"size","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageSize","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"size"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/size","abstract":[{"type":"text","text":"Image size."}]},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector":{"title":"FaceDetector","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","type":"topic","role":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacecore\/facedetector"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage/bytesPointer":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/bytesPointer","title":"bytesPointer","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointer","kind":"identifier"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">"}],"url":"\/documentation\/dotfacecore\/bgrrawimage\/bytespointer","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"bytesPointer","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DOTBgrRawImage","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage\/init(bytesPointer:size:)"]}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/@M@DotFaceCore@objc(pl)_RawImage"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImageFactory","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CIImageFactory"],"title":"Converting images","generated":true}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBgrRawImage"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DOTCGImageFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CGImageFactory\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace"},{"value":"DOTBgrRawImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImageFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImageFactory\/fragments","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1bytes\/title","value":"bytes","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CIImageFactory\/fragments","op":"replace"},{"value":"initWithBytesPointer:size:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1init(bytesPointer:size:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1init(bytesPointer:size:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBytesPointer:size:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1size\/title","value":"size","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"size"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1size\/fragments"},{"value":"DOTFFaceDetector","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"value":"bytesPointer","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1bytesPointer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage~1bytesPointer\/fragments","value":[{"text":"bytesPointer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}