{"metadata":{"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCamera@E@DOTCameraFacing","roleHeading":"Enumeration","symbolKind":"enum","title":"CameraFacing"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/back","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/front"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/native"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCameraFacing) "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/camerafacing"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/camerafacing"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/SY":{"identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/front":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"front"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/front","navigatorTitle":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"title":"CameraFacing.front","abstract":[{"type":"text","text":"Front facing camera."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/camerafacing\/front"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/native":{"title":"native","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/native","type":"topic","url":"\/documentation\/dotfacecore\/camerafacing\/native","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","text":"AVCaptureDevice","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Position","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureDevicePosition"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/back":{"title":"CameraFacing.back","abstract":[{"text":"Back facing camera.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/back","type":"topic","navigatorTitle":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing\/back","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/dotfacecore\/camerafacing\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/RawRepresentable-Implementations"},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/init(rawValue:)","type":"topic","url":"\/documentation\/dotfacecore\/camerafacing\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing","kind":"symbol","url":"\/documentation\/dotfacecore\/camerafacing","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/Equatable-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/dotfacecore\/camerafacing\/equatable-implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/Equatable-Implementations","title":"Equatable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing/description":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/camerafacing\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/description","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraFacing"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/back","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing\/front"],"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCameraFacing"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"DOTCameraFacingFront","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing~1front\/title"},{"value":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing~1front\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing~1back\/title","value":"DOTCameraFacingBack","op":"replace"},{"value":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing~1back\/fragments"},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}