{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTCaptureMode) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"title":"CaptureMode","externalID":"c:@M@DotFaceCore@E@DOTCaptureMode","role":"symbol","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/autoCapture","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/waitForRequest"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/description"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH","doc:\/\/com.innovatrics.dot.face.core\/SY"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/capturemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/capturemode"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Capture mode.","type":"text"}],"references":{"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode/waitForRequest":{"url":"\/documentation\/dotfacecore\/capturemode\/waitforrequest","title":"CaptureMode.waitForRequest","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/waitForRequest","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"text":"Capture mode.","type":"text"}],"navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"type":"topic","title":"CaptureMode","url":"\/documentation\/dotfacecore\/capturemode","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode/autoCapture":{"abstract":[{"text":"Auto capture mode (automatic mode).","type":"text"}],"url":"\/documentation\/dotfacecore\/capturemode\/autocapture","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/autoCapture","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoCapture"}],"type":"topic","title":"CaptureMode.autoCapture"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/dotfacecore\/capturemode\/init(rawvalue:)","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://com.innovatrics.dot.face.core/SY":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode/RawRepresentable-Implementations":{"url":"\/documentation\/dotfacecore\/capturemode\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/RawRepresentable-Implementations","kind":"article"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode/Equatable-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/capturemode\/equatable-implementations","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/Equatable-Implementations","title":"Equatable Implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode/description":{"title":"description","url":"\/documentation\/dotfacecore\/capturemode\/description","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTCaptureMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/autoCapture","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode\/waitForRequest"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCaptureMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode~1waitForRequest\/title","value":"DOTCaptureModeWaitForRequest","op":"replace"},{"value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode~1waitForRequest\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode~1autoCapture\/title","value":"DOTCaptureModeAutoCapture","op":"replace"},{"op":"replace","value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode~1autoCapture\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}