{"sections":[],"metadata":{"roleHeading":"Class","title":"CGImageFactory","symbolKind":"class","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory"},"seeAlsoSections":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/cgimagefactory"]},{"paths":["\/documentation\/dotfacecore\/cgimagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCGImageFactory) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgrRawImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgraRawImage:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory/create(bgrRawImage:)":{"type":"topic","url":"\/documentation\/dotfacecore\/cgimagefactory\/create(bgrrawimage:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgrRawImage:)","navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"title":"create(bgrRawImage:)","kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}]},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImageFactory":{"type":"topic","url":"\/documentation\/dotfacecore\/bgrrawimagefactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"title":"BgrRawImageFactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}]},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"title":"BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","role":"symbol","url":"\/documentation\/dotfacecore\/bgrrawimage","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory/create(bgraRawImage:)":{"title":"create(bgraRawImage:)","kind":"symbol","url":"\/documentation\/dotfacecore\/cgimagefactory\/create(bgrarawimage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"}],"navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgraRawImage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}],"role":"symbol"},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory":{"title":"CGImageFactory","kind":"symbol","url":"\/documentation\/dotfacecore\/cgimagefactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory":{"abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacecore\/ciimagefactory","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory","title":"CIImageFactory","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTCGImageFactory","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgrRawImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(bgraRawImage:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"],"generated":true,"title":"Converting images"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTCGImageFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgrRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithBgrRawImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory\/title","value":"DOTBgrRawImageFactory","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImageFactory\/fragments"},{"op":"replace","value":"DOTBgrRawImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgraRawImage:)\/title","value":"createWithBgraRawImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:","kind":"identifier"}]},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/fragments","op":"replace","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]}]}]}