{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"seeAlsoSections":[{"title":"Face auto capture result","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureResult","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"],["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"],["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"],["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"kind":"symbol","abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDetectionPosition) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/detectionposition"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/detectionposition"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"DetectionPosition","modules":[{"name":"DotFaceCore"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTDetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/center","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/sizeToImageShorterSideRatio"],"title":"Instance Properties"}],"references":{"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"deprecated":true,"kind":"symbol","title":"FaceSimpleCaptureViewController","navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition/description":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"title":"description","type":"topic","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/detectionposition\/description","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition/center":{"role":"symbol","url":"\/documentation\/dotfacecore\/detectionposition\/center","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"center","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/center","abstract":[{"type":"text","text":"Center of the face in the image."}],"kind":"symbol","navigatorTitle":[{"text":"center","kind":"identifier"}],"title":"center"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureDetection":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCaptureDetection","url":"\/documentation\/dotfacecore\/faceautocapturedetection","type":"topic","abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition/sizeToImageShorterSideRatio":{"role":"symbol","url":"\/documentation\/dotfacecore\/detectionposition\/sizetoimageshortersideratio","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sizeToImageShorterSideRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/sizeToImageShorterSideRatio","abstract":[{"text":"Diameter of the face circle represented as a ratio to the image shorter side.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sizeToImageShorterSideRatio"}],"title":"sizeToImageShorterSideRatio"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition/init(center:sizeToImageShorterSideRatio:)":{"kind":"symbol","navigatorTitle":[{"text":"initWithCenter:sizeToImageShorterSideRatio:","kind":"identifier"}],"title":"init(center:sizeToImageShorterSideRatio:)","url":"\/documentation\/dotfacecore\/detectionposition\/init(center:sizetoimageshortersideratio:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"center","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizeToImageShorterSideRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)","type":"topic","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessViewController":{"kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileLivenessViewController"}],"abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","title":"SmileLivenessViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"kind":"symbol","role":"symbol","title":"MagnifEyeLivenessViewController","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}]},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","title":"DetectionPosition","url":"\/documentation\/dotfacecore\/detectionposition","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureResult":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"role":"symbol","title":"FaceAutoCaptureResult","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureresult"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTDetectionPosition","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/center","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/sizeToImageShorterSideRatio"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition\/init(center:sizeToImageShorterSideRatio:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Face auto capture result","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureResult","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDetectionPosition"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1description\/title","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1description\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1center\/title","value":"center"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1center\/fragments","value":[{"kind":"identifier","text":"center"}],"op":"replace"},{"value":"DOTFFaceAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}]},{"value":"DOTFFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"value":"sizeToImageShorterSideRatio","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1sizeToImageShorterSideRatio\/title"},{"value":[{"kind":"identifier","text":"sizeToImageShorterSideRatio"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1sizeToImageShorterSideRatio\/fragments"},{"op":"replace","value":"initWithCenter:sizeToImageShorterSideRatio:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1init(center:sizeToImageShorterSideRatio:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCenter:sizeToImageShorterSideRatio:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition~1init(center:sizeToImageShorterSideRatio:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title","value":"DOTFFaceAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}]}]}]}