{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"externalID":"c:@M@DotCore@E@DotDocumentModuleId","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"title":"DotDocumentModuleId","symbolKind":"enum","modules":[{"name":"DotFaceCore"}]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/barcode"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/init(rawValue:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId"},"abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId":{"abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"title":"DotDocumentModuleId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/init(rawValue:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/init(rawValue:)","abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/RawRepresentable-Implementations","abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/barcode":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/barcode","title":"DotDocumentModuleId.barcode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/barcode","abstract":[],"type":"topic"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/description":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/description","title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/description","abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentModuleId/Equatable-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/dotfacecore\/dotdocumentmoduleid\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/Equatable-Implementations","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotDocumentModuleId","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentModuleId\/barcode"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotDocumentModuleId","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId\/navigatorTitle"},{"op":"replace","value":"DotDocumentModuleIdBarcode","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId~1barcode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentModuleId~1barcode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}