{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibrarydelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacelibrarydelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Implement this delegate to handle initialization and deinitialization events of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"title":"DotFaceLibraryDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceLibraryDelegate","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryDeinitializationFinished(_:result:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryInitializationFinished(_:result:)"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary":{"role":"symbol","title":"DotFaceLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryDelegate":{"role":"symbol","title":"DotFaceLibraryDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle initialization and deinitialization events of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"url":"\/documentation\/dotfacecore\/dotfacelibrarydelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryDelegate/dotFaceLibraryInitializationFinished(_:result:)":{"navigatorTitle":[{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}],"role":"symbol","title":"dotFaceLibraryInitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB7LibraryC6ResultC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework initialization has finished with "},{"type":"codeVoice","code":"result"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryInitializationFinished(_:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrarydelegate\/dotfacelibraryinitializationfinished(_:result:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryDelegate/dotFaceLibraryDeinitializationFinished(_:result:)":{"navigatorTitle":[{"kind":"identifier","text":"dotFaceLibraryDeinitializationFinished:result:"}],"role":"symbol","title":"dotFaceLibraryDeinitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceLibraryDeinitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB7LibraryC6ResultC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework deinitialization has finished with "},{"type":"codeVoice","code":"result"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryDeinitializationFinished(_:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrarydelegate\/dotfacelibrarydeinitializationfinished(_:result:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceLibraryDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryDeinitializationFinished(_:result:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate\/dotFaceLibraryInitializationFinished(_:result:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","value":[{"kind":"identifier","text":"DotFaceLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate\/title","value":"DotFaceLibraryDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate~1dotFaceLibraryInitializationFinished(_:result:)\/title","value":"dotFaceLibraryInitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate~1dotFaceLibraryInitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceLibraryInitializationFinished:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate~1dotFaceLibraryDeinitializationFinished(_:result:)\/title","value":"dotFaceLibraryDeinitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate~1dotFaceLibraryDeinitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceLibraryDeinitializationFinished:result:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}