{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacedelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacedelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceDeinitializationFinished(_:result:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceInitializationFinished(_:result:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceDelegate"}],"role":"symbol","title":"DotFaceDelegate","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDelegate"}],"symbolKind":"protocol","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceDelegate","modules":[{"name":"DotFaceCore"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibraryDelegate instead."}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceDelegate/dotFaceInitializationFinished(_:result:)":{"navigatorTitle":[{"kind":"identifier","text":"dotFaceInitializationFinished:result:"}],"deprecated":true,"role":"symbol","title":"dotFaceInitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceInitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB0C6ResultC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceInitializationFinished(_:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/dotfacedelegate\/dotfaceinitializationfinished(_:result:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceDelegate":{"deprecated":true,"role":"symbol","title":"DotFaceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDelegate"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceDelegate"}],"url":"\/documentation\/dotfacecore\/dotfacedelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"DotFaceCore is a part of DotFace framework group which provides components for the digital onboarding process using the latest Innovatrics IFace image processing library. It wraps the core functionality of IFace library to a higher-level module which is easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceDelegate/dotFaceDeinitializationFinished(_:result:)":{"navigatorTitle":[{"kind":"identifier","text":"dotFaceDeinitializationFinished:result:"}],"deprecated":true,"role":"symbol","title":"dotFaceDeinitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceDeinitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB0C6ResultC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceDeinitializationFinished(_:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/dotfacedelegate\/dotfacedeinitializationfinished(_:result:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceDeinitializationFinished(_:result:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceInitializationFinished(_:result:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate~1dotFaceInitializationFinished(_:result:)\/title","value":"dotFaceInitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate~1dotFaceInitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceInitializationFinished:result:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate\/title","value":"DotFaceDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate\/fragments","value":[{"kind":"identifier","text":"DotFaceDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate~1dotFaceDeinitializationFinished(_:result:)\/title","value":"dotFaceDeinitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate~1dotFaceDeinitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceDeinitializationFinished:result:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}