{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceBackgroundUniformityModuleProtocol"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleProtocol","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Protocol","title":"DotFaceBackgroundUniformityModuleProtocol","symbolKind":"protocol","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceBackgroundUniformityModuleProtocol","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleProtocol"}],"role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/dotfacebackgrounduniformitymoduleprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacebackgrounduniformitymoduleprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","kind":"symbol","title":"DotFaceModule","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacemodule","navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceBackgroundUniformityModuleProtocol":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceBackgroundUniformityModuleProtocol","title":"DotFaceBackgroundUniformityModuleProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleProtocol"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacebackgrounduniformitymoduleprotocol","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceBackgroundUniformityModuleProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFaceBackgroundUniformityModuleProtocol","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotFaceBackgroundUniformityModuleProtocol","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleProtocol"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","kind":"typeIdentifier","text":"DotFaceModule"},{"kind":"text","text":">"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"text":"DotFaceModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleProtocol\/title","value":"DotFaceBackgroundUniformityModuleProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleProtocol\/fragments","value":[{"text":"DotFaceBackgroundUniformityModuleProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleProtocol\/navigatorTitle","value":[{"text":"DotFaceBackgroundUniformityModuleProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}