{"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DotFaceEyeGazeLivenessModuleProtocol","role":"symbol","roleHeading":"Protocol","title":"DotFaceEyeGazeLivenessModuleProtocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleProtocol","kind":"identifier"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleProtocol"},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"],"type":"inheritsFrom","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleprotocol"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","text":"DotFaceModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"type":"topic","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module.","type":"text"}],"kind":"symbol","title":"DotFaceModule","navigatorTitle":[{"kind":"identifier","text":"DotFaceModule"}],"url":"\/documentation\/dotfacecore\/dotfacemodule","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModule"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceEyeGazeLivenessModuleProtocol":{"title":"DotFaceEyeGazeLivenessModuleProtocol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleProtocol"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleProtocol"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleProtocol","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleprotocol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceEyeGazeLivenessModuleProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotFaceEyeGazeLivenessModuleProtocol","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"text":"DotFaceModule","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/navigatorTitle","value":[{"text":"DotFaceModule","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleProtocol\/title","value":"DotFaceEyeGazeLivenessModuleProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleProtocol\/fragments","value":[{"text":"DotFaceEyeGazeLivenessModuleProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleProtocol\/navigatorTitle","value":[{"text":"DotFaceEyeGazeLivenessModuleProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}