{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/s12CaseIterableP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/backgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/detection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/expressionNeutral","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/eyeGazeLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/passiveLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/verification"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/init(rawValue:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/description"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"DotFace modularization","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotFaceCore@E@DotFaceModuleCategory","modules":[{"name":"DotFaceCore"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"role":"symbol","title":"DotFaceModuleCategory","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModuleCategory","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" module category."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleCategory"}],"languages":["swift"]}]},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"Module category may contain multiple modules which provide similiar feature.","type":"text"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"title":"DotFaceModuleId","url":"\/documentation\/dotfacecore\/dotfacemoduleid"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/verification":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"verification","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/verification","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryVerification"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/verification","abstract":[],"title":"DotFaceModuleCategory.verification"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/description":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/description","abstract":[],"title":"description","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/equatable-implementations","type":"topic","kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/Equatable-Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/backgroundUniformity":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/backgrounduniformity","title":"DotFaceModuleCategory.backgroundUniformity","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundUniformity"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/backgroundUniformity","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleCategoryBackgroundUniformity","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","title":"DotFaceModule","url":"\/documentation\/dotfacecore\/dotfacemodule","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModule"}],"type":"topic","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"type":"topic","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" module category.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodulecategory","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"title":"DotFaceModuleCategory","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/eyeGazeLiveness":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/eyeGazeLiveness","navigatorTitle":[{"text":"DotFaceModuleCategoryEyeGazeLiveness","kind":"identifier"}],"title":"DotFaceModuleCategory.eyeGazeLiveness","url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/eyegazeliveness","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SY"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/RawRepresentable-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/RawRepresentable-Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s12CaseIterableP"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/init(rawValue:)":{"abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/init(rawvalue:)","type":"topic","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/expressionNeutral":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/expressionneutral","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expressionNeutral"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryExpressionNeutral"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/expressionNeutral","title":"DotFaceModuleCategory.expressionNeutral","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/detection":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/detection","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryDetection"}],"title":"DotFaceModuleCategory.detection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/detection","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/passiveLiveness":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/passiveliveness","title":"DotFaceModuleCategory.passiveLiveness","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/passiveLiveness","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleCategoryPassiveLiveness","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceModuleCategory"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/backgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/detection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/expressionNeutral","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/eyeGazeLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/passiveLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/verification"],"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId"],"title":"DotFace modularization"}],"op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1verification\/title","value":"DotFaceModuleCategoryVerification"},{"op":"replace","value":[{"text":"DotFaceModuleCategoryVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1verification\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1backgroundUniformity\/title","value":"DotFaceModuleCategoryBackgroundUniformity"},{"value":[{"kind":"identifier","text":"DotFaceModuleCategoryBackgroundUniformity"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1backgroundUniformity\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"text":"DotFaceModule","kind":"identifier"}]},{"value":"DotFaceModuleCategory","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleCategory"}]},{"op":"replace","value":"DotFaceModuleCategoryEyeGazeLiveness","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1eyeGazeLiveness\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1eyeGazeLiveness\/fragments","op":"replace","value":[{"text":"DotFaceModuleCategoryEyeGazeLiveness","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1expressionNeutral\/title","value":"DotFaceModuleCategoryExpressionNeutral","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1expressionNeutral\/fragments","value":[{"text":"DotFaceModuleCategoryExpressionNeutral","kind":"identifier"}]},{"value":"DotFaceModuleCategoryDetection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1detection\/title","op":"replace"},{"value":[{"text":"DotFaceModuleCategoryDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1detection\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1passiveLiveness\/title","value":"DotFaceModuleCategoryPassiveLiveness","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1passiveLiveness\/fragments","value":[{"text":"DotFaceModuleCategoryPassiveLiveness","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}