{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"roleHeading":"Class","title":"DotFaceLibraryConfiguration","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}]},"sections":[],"topicSections":[{"title":"Classes","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class"],"generated":true,"anchor":"Classes"},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/modules-swift.property"],"generated":true,"anchor":"Instance-Properties"}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","kind":"relationships"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Face library configuration.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/modules-swift.property":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"modules","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.property","title":"modules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/modules-swift.property","abstract":[{"text":"Module configuration.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","role":"symbol","kind":"symbol","title":"DotFaceLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","abstract":[{"type":"text","text":"Face library configuration."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Modules-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"type":"topic","role":"symbol","title":"DotFaceLibraryConfiguration.Modules","kind":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Modules-swift.class","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"title":"init(modules:faceDetectionConfidenceThreshold:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/init(modules:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"title":"init(modules:)","type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/init(modules:)"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/faceDetectionConfidenceThreshold":{"title":"faceDetectionConfidenceThreshold","kind":"symbol","type":"topic","abstract":[{"text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval ","type":"text"},{"code":"[0.0, 1.0]","type":"codeVoice"},{"text":". Default value is ","type":"text"},{"code":"0.06","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/modules-swift.property"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1modules-swift.property\/title","op":"replace","value":"modules"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1modules-swift.property\/fragments","op":"replace","value":[{"text":"modules","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"op":"replace","value":"initWithModules:faceDetectionConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments"},{"op":"replace","value":"initWithModules:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1init(modules:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1init(modules:)\/fragments"},{"op":"replace","value":"faceDetectionConfidenceThreshold","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/title"},{"op":"replace","value":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/fragments"}]}]}