{"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Fast"],"anchor":"Classes","title":"Classes","generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"kind":"symbol","metadata":{"title":"DotFaceDetectionModuleConfiguration","symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Balanced","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Fast"],"type":"inheritedBy","title":"Inherited By"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration"]}],"abstract":[{"text":"Face detection module configuration.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}]}],"references":{"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfigurationFast":{"abstract":[{"type":"text","text":"Face detection fast module."}],"title":"DotFaceDetectionModuleConfigurationFast","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationFast","type":"topic","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfigurationfast","fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationFast"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration/Fast":{"title":"DotFaceDetectionModuleConfiguration.Fast","navigatorTitle":[{"kind":"identifier","text":"Fast"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fast"}],"abstract":[{"type":"text","text":"Face detection fast module."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Fast","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration\/fast","kind":"symbol","role":"symbol"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration":{"abstract":[{"type":"text","text":"Face detection module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","type":"topic","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration/Balanced":{"title":"DotFaceDetectionModuleConfiguration.Balanced","abstract":[{"type":"text","text":"Face detection balanced module."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Balanced","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration\/balanced","navigatorTitle":[{"text":"Balanced","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfigurationBalanced":{"title":"DotFaceDetectionModuleConfigurationBalanced","kind":"symbol","abstract":[{"type":"text","text":"Face detection balanced module."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationBalanced","fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"}],"url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfigurationbalanced","type":"topic"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationBalanced","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationFast"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle"}]}]}