{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleProtocol"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","text":"DotFaceModule"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceexpressionneutralmoduleprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfaceexpressionneutralmoduleprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"DotFaceExpressionNeutralModuleProtocol","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleProtocol","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(pl)DotFaceExpressionNeutralModuleProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleProtocol","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleProtocol","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceExpressionNeutralModuleProtocol":{"navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleProtocol","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleProtocol","role":"symbol","title":"DotFaceExpressionNeutralModuleProtocol","url":"\/documentation\/dotfacecore\/dotfaceexpressionneutralmoduleprotocol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleProtocol","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodule","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"role":"symbol","title":"DotFaceModule","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceExpressionNeutralModuleProtocol","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleProtocol"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleProtocol"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleProtocol\/title","value":"DotFaceExpressionNeutralModuleProtocol","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleProtocol\/fragments","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleProtocol"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleProtocol"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","op":"replace","value":"DotFaceModule"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/navigatorTitle","op":"replace","value":[{"text":"DotFaceModule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}