{"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/detection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/transformation"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/init(rawValue:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/description"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"enum","externalID":"c:@M@DotCore@E@DotFingersModuleId","title":"DotFingersModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}]},"abstract":[{"code":"DotFingers","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfingersmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfingersmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/transformation":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/transformation","title":"DotFingersModuleId.transformation","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/transformation","abstract":[]},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/detection":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/detection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/detection","kind":"symbol","title":"DotFingersModuleId.detection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/init(rawValue:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/init(rawvalue:)","title":"init(rawValue:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/init(rawValue:)","abstract":[]},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/SY":{"identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/description":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/description","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/description","kind":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"url":"\/documentation\/dotfacecore\/dotfingersmoduleid","title":"DotFingersModuleId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId","abstract":[{"code":"DotFingers","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/RawRepresentable-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/Equatable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/equatable-implementations","title":"Equatable Implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/Equatable-Implementations","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersModuleId"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/detection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/transformation"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId~1transformation\/title","value":"DotFingersModuleIdTransformation"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId~1transformation\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId~1detection\/title","value":"DotFingersModuleIdDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId~1detection\/fragments","value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/fragments","value":[{"kind":"identifier","text":"DotFingersModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}