{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFFaceAutoCaptureUiStateIdle"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiState","kind":"typeIdentifier","text":"DOTFFaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle"},"abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/preview"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/initWithPreview:","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/isEqual:"],"title":"Instance Methods"}],"kind":"symbol","metadata":{"title":"DOTFFaceAutoCaptureUiStateIdle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiStateIdle"}],"roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiStateIdle","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiStateIdle"}],"symbolKind":"class"},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateIdle/description":{"title":"description","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/description","abstract":[],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle\/description","kind":"symbol","fragments":[{"text":"description","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateIdle/hash":{"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle\/hash","fragments":[{"text":"hash","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/hash","title":"hash","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateIdle/initWithPreview:":{"title":"initWithPreview:","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/initWithPreview:","abstract":[],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle\/initwithpreview:","kind":"symbol","navigatorTitle":[{"text":"initWithPreview:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateIdle/preview":{"title":"preview","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/preview","abstract":[{"type":"text","text":"Preview information."}],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle\/preview","kind":"symbol","fragments":[{"text":"preview","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateIdle/isEqual:":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle\/isEqual:","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle\/isequal:","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"title":"FaceAutoCaptureUiState","url":"\/documentation\/dotfacecore\/faceautocaptureuistate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateIdle":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateIdle","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistateidle","type":"topic","title":"DOTFFaceAutoCaptureUiStateIdle","abstract":[{"text":"Idle state.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This state is active either:"}],"fragments":[{"text":"DOTFFaceAutoCaptureUiStateIdle","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title","value":"DOTFFaceAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]}]}]}