{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"symbolKind":"class","title":"DotFingersDetectionModuleConfiguration","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},"abstract":[{"type":"text","text":"Fingers detection module configuration."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfingersdetectionmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfingersdetectionmoduleconfiguration"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersDetectionModuleConfiguration/init":{"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfingersdetectionmoduleconfiguration\/init","title":"init","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration\/init","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersDetectionModuleConfiguration":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration","kind":"symbol","title":"DotFingersDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotFingersDetectionModuleConfiguration","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"add","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration\/init"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}