{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"symbolKind":"class","role":"symbol","title":"DotFaceVerificationModuleConfiguration","externalID":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"modules":[{"name":"DotFaceCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Face verification module."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceVerificationModuleConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Face verification module."}],"url":"\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration","type":"topic","title":"DotFaceVerificationModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceVerificationModuleConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration\/init","url":"\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration\/init","abstract":[]},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFaceVerificationModuleConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration\/init"],"generated":true}],"op":"add","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceVerificationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle"}]}]}