{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibrary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibrary"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"role":"symbol","symbolKind":"protocol","title":"DotLibrary","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(pl)DotLibrary","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"roleHeading":"Protocol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"relationshipsSections":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary"],"type":"conformingTypes"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/id"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/deinitialize()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/initialize(license:)"],"title":"Instance Methods"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.8.0","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrary","kind":"symbol","title":"DotFaceLibrary","role":"symbol","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library initialization."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary":{"title":"DotLibrary","url":"\/documentation\/dotfacecore\/dotlibrary","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary/id":{"role":"symbol","title":"id","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/id","navigatorTitle":[{"text":"id","kind":"identifier"}],"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"}],"url":"\/documentation\/dotfacecore\/dotlibrary\/id"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary/deinitialize()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/deinitialize()","required":true,"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"role":"symbol","title":"deinitialize()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotfacecore\/dotlibrary\/deinitialize()","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary/initialize(license:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/initialize(license:)","required":true,"navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"role":"symbol","title":"initialize(license:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotfacecore\/dotlibrary\/initialize(license:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"DotLibrary","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace"},{"op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/id"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/deinitialize()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary\/initialize(license:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary"],"type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DotFaceLibrary","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/title","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1id\/title","value":"id"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1deinitialize()\/title","value":"deinitializeAndReturnError:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"value":"initializeWithLicense:error:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1initialize(license:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary~1initialize(license:)\/fragments"}]}]}