{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","externalID":"c:@M@DotCore@E@DotLibraryId","roleHeading":"Enumeration","modules":[{"name":"DotFaceCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"},"sections":[],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/document","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/faceLite","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/nfc","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/palm"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/description"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid"]}],"references":{"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotlibraryid","kind":"symbol","title":"DotLibraryId","role":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/description":{"abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/description","title":"description","url":"\/documentation\/dotfacecore\/dotlibraryid\/description","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/nfc":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/nfc","role":"symbol","url":"\/documentation\/dotfacecore\/dotlibraryid\/nfc","navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"kind":"symbol","title":"DotLibraryId.nfc","abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"text":" identifier.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/document":{"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"type":"text","text":" identifier."}],"type":"topic","title":"DotLibraryId.document","kind":"symbol","url":"\/documentation\/dotfacecore\/dotlibraryid\/document","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/document"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/RawRepresentable-Implementations":{"abstract":[],"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/dotfacecore\/dotlibraryid\/rawrepresentable-implementations"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/faceLite":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/faceLite","title":"DotLibraryId.faceLite","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"type":"text","text":" identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"url":"\/documentation\/dotfacecore\/dotlibraryid\/facelite"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/init(rawValue:)":{"title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/dotfacecore\/dotlibraryid\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/init(rawValue:)","abstract":[],"type":"topic"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/dotfacecore\/dotlibraryid\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/face":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"}],"kind":"symbol","type":"topic","role":"symbol","title":"DotLibraryId.face","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFace"}],"url":"\/documentation\/dotfacecore\/dotlibraryid\/face","abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" identifier."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/face"},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/palm":{"role":"symbol","navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotPalmLibrary"},{"type":"text","text":" identifier."}],"title":"DotLibraryId.palm","url":"\/documentation\/dotfacecore\/dotlibraryid\/palm","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/palm"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DotLibraryId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/document","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/faceLite","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/nfc","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/palm"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1nfc\/title","op":"replace","value":"DotLibraryIdNfc"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1nfc\/fragments","op":"replace","value":[{"text":"DotLibraryIdNfc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1document\/title","op":"replace","value":"DotLibraryIdDocument"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1document\/fragments","op":"replace","value":[{"text":"DotLibraryIdDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1faceLite\/title","op":"replace","value":"DotLibraryIdFaceLite"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1faceLite\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1face\/title","op":"replace","value":"DotLibraryIdFace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1face\/fragments","op":"replace","value":[{"text":"DotLibraryIdFace","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1palm\/title","op":"replace","value":"DotLibraryIdPalm"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1palm\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdPalm"}]}]}]}