{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdk"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdk"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"metadata":{"title":"DotSdk","roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DotSdk","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"symbolKind":"class","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/bundleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isInitialized","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/versionName"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/deinitialize()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/initialize(configuration:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isLibraryActive(libraryId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/shared"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error"],"title":"Enumerations"}],"references":{"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/bundleId":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bundleId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"bundleId","kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdk\/bundleid","type":"topic","abstract":[{"type":"text","text":"Application Bundle ID."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/bundleId","navigatorTitle":[{"text":"bundleId","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error":{"role":"symbol","title":"DotSdk.Error","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdk\/error"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/initialize(configuration:)":{"role":"symbol","title":"initialize(configuration:)","navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotsdk\/initialize(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/initialize(configuration:)"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotfacecore\/dotsdk","title":"DotSdk"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.11.0"}],"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/isLibraryActive(libraryId:)":{"abstract":[{"type":"text","text":"Check whether "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library is active."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isLibraryActive(libraryId:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isLibraryActive","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/dotfacecore\/dotsdk\/islibraryactive(libraryid:)","title":"isLibraryActive(libraryId:)"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/deinitialize()":{"kind":"symbol","type":"topic","role":"symbol","title":"deinitialize()","abstract":[{"type":"text","text":"Deinitialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"url":"\/documentation\/dotfacecore\/dotsdk\/deinitialize()"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/isInitialized":{"title":"isInitialized","abstract":[{"text":"Flag to determine if ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" is initialized.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isInitialized","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"isInitialized","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotsdk\/isinitialized","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/shared":{"url":"\/documentation\/dotfacecore\/dotsdk\/shared","abstract":[{"text":"Shared singleton instance.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"}],"kind":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/shared","title":"shared","type":"topic","role":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/versionName":{"url":"\/documentation\/dotfacecore\/dotsdk\/versionname","abstract":[{"type":"codeVoice","code":"DotSdk"},{"text":" version.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","navigatorTitle":[{"text":"versionName","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/versionName","title":"versionName","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DotSdk"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/bundleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isInitialized","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/versionName"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/deinitialize()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/initialize(configuration:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isLibraryActive(libraryId:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/shared"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1bundleId\/title","value":"bundleId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1bundleId\/fragments","value":[{"text":"bundleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1initialize(configuration:)\/title","op":"replace","value":"initializeWithConfiguration:error:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1initialize(configuration:)\/fragments","op":"replace"},{"value":"DotSdk","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1isLibraryActive(libraryId:)\/title","op":"replace","value":"isLibraryActiveWithLibraryId:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1isLibraryActive(libraryId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1deinitialize()\/title","value":"deinitializeAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1isInitialized\/title","op":"replace","value":"isInitialized"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1isInitialized\/fragments","op":"replace","value":[{"kind":"identifier","text":"isInitialized"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1shared\/title","op":"replace","value":"shared"},{"value":[{"text":"shared","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1shared\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1versionName\/title","op":"replace","value":"versionName"},{"value":[{"kind":"identifier","text":"versionName"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1versionName\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}