{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"roleHeading":"Protocol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"symbolKind":"protocol","title":"DotSdkLicenseProxyProtocol","modules":[{"name":"DotFaceCore"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/licenseBytes"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfacematchingenabled","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"required":true,"kind":"symbol","type":"topic","title":"isFaceMatchingEnabled","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","required":true,"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfaceliteenabled","title":"isFaceLiteEnabled"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isNfcEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNfcEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isNfcEnabled","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isnfcenabled","kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","type":"topic","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol","kind":"symbol","title":"DotSdkLicenseProxyProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/licenseBytes":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/licenseBytes","navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"required":true,"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/licensebytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"licenseBytes","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"title":"licenseBytes","abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isDocumentEnabled","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isdocumentenabled","kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isPalmEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPalmEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/ispalmenabled","type":"topic","kind":"symbol","title":"isPalmEnabled","required":true,"navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","role":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"type":"text","text":"version: 8.6.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isEvaluation":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isEvaluation","title":"isEvaluation","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isevaluation","required":true,"abstract":[],"role":"symbol","navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEvaluation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","role":"symbol","kind":"symbol","abstract":[],"type":"topic","required":true,"navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"title":"isRealTimeTransactionReportingEnabled"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","required":true,"title":"isFaceEyeGazeLivenessScoreEnabled","type":"topic","navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isFaceEnabled":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","navigatorTitle":[{"kind":"identifier","text":"isFaceEnabled"}],"required":true,"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfaceenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isFaceEnabled","abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isFacePassiveLivenessEnabled":{"kind":"symbol","type":"topic","title":"isFacePassiveLivenessEnabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isfacepassivelivenessenabled","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/licenseBytes"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title","op":"replace","value":"isFaceMatchingEnabled"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"op":"replace"},{"value":"isFaceLiteEnabled","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title","value":"isNfcEnabled","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}],"op":"replace"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/title","value":"licenseBytes","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"licenseBytes"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title","value":"isDocumentEnabled","op":"replace"},{"value":[{"kind":"identifier","text":"isDocumentEnabled"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/title","value":"isPalmEnabled"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/fragments","value":[{"text":"isPalmEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/title","op":"replace","value":"isEvaluation"},{"value":[{"text":"isEvaluation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title","value":"isRealTimeTransactionReportingEnabled"},{"value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments"},{"op":"replace","value":"isFaceEyeGazeLivenessScoreEnabled","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/title","op":"replace","value":"isFaceEnabled"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceEnabled"}]},{"op":"replace","value":"isFacePassiveLivenessEnabled","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/title"},{"value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}