{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomRight","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topRight"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/s12CaseIterableP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner","roleHeading":"Enumeration","navigatorTitle":[{"text":"EyeGazeLivenessCorner","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"EyeGazeLivenessCorner","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessCorner","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFEyeGazeLivenessCorner) "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessCorner","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner"},"abstract":[{"type":"text","text":"Eye gaze liveness corner."}],"references":{"doc://DotFaceCore/SY":{"identifier":"doc:\/\/DotFaceCore\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/bottomRight":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"}],"title":"EyeGazeLivenessCorner.bottomRight","role":"symbol","navigatorTitle":[{"text":"DOTFEyeGazeLivenessCornerBottomRight","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomright","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomRight"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/topLeft":{"title":"EyeGazeLivenessCorner.topLeft","kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/topleft","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerTopLeft"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topLeft","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/topRight":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"topRight","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerTopRight"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topRight","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/topright","abstract":[],"kind":"symbol","role":"symbol","title":"EyeGazeLivenessCorner.topRight"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.11.0"}],"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/init(rawvalue:)","abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/init(rawValue:)"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/description":{"kind":"symbol","abstract":[],"role":"symbol","title":"description","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","kind":"article","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/rawrepresentable-implementations","role":"collectionGroup","abstract":[]},"doc://DotFaceCore/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s12CaseIterableP"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/Equatable-Implementations":{"kind":"article","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/equatable-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/Equatable-Implementations","type":"topic","title":"Equatable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner/bottomLeft":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"bottomLeft","kind":"identifier"}],"title":"EyeGazeLivenessCorner.bottomLeft","role":"symbol","navigatorTitle":[{"text":"DOTFEyeGazeLivenessCornerBottomLeft","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/bottomleft","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomLeft"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCorner":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessCorner","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","role":"symbol","abstract":[{"text":"Eye gaze liveness corner.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCorner"}],"type":"topic","title":"EyeGazeLivenessCorner"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"DOTFEyeGazeLivenessCorner","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCorner"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/bottomRight","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topRight"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomRight\/title","op":"replace","value":"DOTFEyeGazeLivenessCornerBottomRight"},{"value":[{"text":"DOTFEyeGazeLivenessCornerBottomRight","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomRight\/fragments","op":"replace"},{"value":"DOTFEyeGazeLivenessCornerTopLeft","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topLeft\/title"},{"value":[{"text":"DOTFEyeGazeLivenessCornerTopLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topLeft\/fragments","op":"replace"},{"value":"DOTFEyeGazeLivenessCornerTopRight","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topRight\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topRight\/fragments","value":[{"text":"DOTFEyeGazeLivenessCornerTopRight","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFEyeGazeLivenessCornerBottomLeft","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomLeft\/title"},{"value":[{"text":"DOTFEyeGazeLivenessCornerBottomLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1bottomLeft\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title","value":"DOTFEyeGazeLivenessCorner"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCorner"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments"}]}]}