{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"metadata":{"title":"EyeGazeLivenessViewControllerDelegate","role":"symbol","externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"symbolKind":"protocol"},"abstract":[{"type":"text","text":"Implement this delegate to handle the eye gaze liveness events."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFEyeGazeLivenessViewControllerDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:finished:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:processed:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerAllCornersUsed(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerCriticalFacePresenceLost(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerNoCameraPermission(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidLoad(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillTransition(_:)"],"title":"Instance Methods"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerCriticalFacePresenceLost(_:)":{"title":"eyeGazeLivenessViewControllerCriticalFacePresenceLost(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerCriticalFacePresenceLost(_:)","abstract":[{"text":"Tells the delegate that the eye gaze liveness cannot continue because either the face is not detected anymore or the eyes are not visible clearly.","type":"text"},{"type":"text","text":" "},{"text":"This callback is called after the component has stopped.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLivenessViewControllerCriticalFacePresenceLost"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollercriticalfacepresencelost(_:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerCriticalFacePresenceLost:"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.3.0"}],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewWillDisappear(_:)":{"title":"eyeGazeLivenessViewControllerViewWillDisappear(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillDisappear(_:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewWillDisappear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewwilldisappear(_:)","navigatorTitle":[{"text":"eyeGazeLivenessViewControllerViewWillDisappear:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewController(_:finished:)":{"title":"eyeGazeLivenessViewController(_:finished:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:finished:)","abstract":[{"text":"Tells the delegate that the eye gaze liveness has finished with result. This callback is called after the component has stopped.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController"},{"kind":"text","text":", "},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EyeGazeLivenessResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:finished:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewController:finished:"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerNoCameraPermission(_:)":{"title":"eyeGazeLivenessViewControllerNoCameraPermission(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerNoCameraPermission(_:)","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLivenessViewControllerNoCameraPermission"},{"text":"(","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollernocamerapermission(_:)","navigatorTitle":[{"text":"eyeGazeLivenessViewControllerNoCameraPermission:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewDidLoad(_:)":{"title":"eyeGazeLivenessViewControllerViewDidLoad(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidLoad(_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewDidLoad","kind":"identifier"},{"kind":"text","text":"("},{"text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewdidload(_:)","navigatorTitle":[{"text":"eyeGazeLivenessViewControllerViewDidLoad:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","title":"EyeGazeLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","type":"topic","abstract":[{"text":"UI component for evaluating liveness by tracking eye gaze.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewController(_:processed:)":{"navigatorTitle":[{"text":"eyeGazeLivenessViewController:processed:","kind":"identifier"}],"role":"symbol","type":"topic","title":"eyeGazeLivenessViewController(_:processed:)","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:processed:)","kind":"symbol","required":true,"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:processed:)","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate","title":"EyeGazeLivenessViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","type":"topic","abstract":[{"text":"Implement this delegate to handle the eye gaze liveness events.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewDidDisappear(_:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewdiddisappear(_:)","title":"eyeGazeLivenessViewControllerViewDidDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewDidDisappear:"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidDisappear(_:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier","text":"EyeGazeLivenessViewController"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewDidLayoutSubviews(_:)":{"title":"eyeGazeLivenessViewControllerViewDidLayoutSubviews(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidLayoutSubviews(_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewdidlayoutsubviews(_:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewDidLayoutSubviews:"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerAllCornersUsed(_:)":{"title":"eyeGazeLivenessViewControllerAllCornersUsed(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerAllCornersUsed(_:)","abstract":[{"type":"text","text":"Tells the delegate that the eye gaze liveness cannot continue because all corners were used and not enough valid samples were captured."},{"text":" ","type":"text"},{"text":"This callback is called after the component has stopped.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewControllerAllCornersUsed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerallcornersused(_:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerAllCornersUsed:"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewWillTransition(_:)":{"abstract":[],"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewwilltransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewWillTransition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController"},{"kind":"text","text":")"}],"title":"eyeGazeLivenessViewControllerViewWillTransition(_:)","required":true,"role":"symbol","navigatorTitle":[{"text":"eyeGazeLivenessViewControllerViewWillTransition:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillTransition(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewWillAppear(_:)":{"title":"eyeGazeLivenessViewControllerViewWillAppear(_:)","required":true,"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillAppear(_:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewControllerViewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewwillappear(_:)","navigatorTitle":[{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewWillAppear:"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewDidAppear(_:)":{"navigatorTitle":[{"text":"eyeGazeLivenessViewControllerViewDidAppear:","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewDidAppear"},{"kind":"text","text":"("},{"text":"EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewdidappear(_:)","type":"topic","title":"eyeGazeLivenessViewControllerViewDidAppear(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"DOTFEyeGazeLivenessViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewControllerDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:finished:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:processed:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerAllCornersUsed(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerCriticalFacePresenceLost(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerNoCameraPermission(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidLoad(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewWillTransition(_:)"]}],"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFEyeGazeLivenessViewControllerDelegate"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"eyeGazeLivenessViewControllerCriticalFacePresenceLost:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerCriticalFacePresenceLost(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerCriticalFacePresenceLost:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerCriticalFacePresenceLost(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillDisappear(_:)\/title","value":"eyeGazeLivenessViewControllerViewWillDisappear:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"eyeGazeLivenessViewControllerViewWillDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillDisappear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:finished:)\/title","value":"eyeGazeLivenessViewController:finished:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"eyeGazeLivenessViewController:finished:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:finished:)\/fragments","op":"replace"},{"op":"replace","value":"eyeGazeLivenessViewControllerNoCameraPermission:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerNoCameraPermission(_:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerNoCameraPermission(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"eyeGazeLivenessViewControllerNoCameraPermission:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidLoad(_:)\/title","value":"eyeGazeLivenessViewControllerViewDidLoad:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidLoad(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewDidLoad:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","op":"replace","value":"DOTFEyeGazeLivenessViewController"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:processed:)\/title","op":"replace","value":"eyeGazeLivenessViewController:processed:"},{"value":[{"text":"- ","kind":"text"},{"text":"eyeGazeLivenessViewController:processed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:processed:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title","value":"DOTFEyeGazeLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFEyeGazeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidDisappear(_:)\/title","value":"eyeGazeLivenessViewControllerViewDidDisappear:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"eyeGazeLivenessViewControllerViewDidDisappear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidDisappear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidLayoutSubviews(_:)\/title","value":"eyeGazeLivenessViewControllerViewDidLayoutSubviews:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"eyeGazeLivenessViewControllerViewDidLayoutSubviews:","kind":"identifier"}]},{"op":"replace","value":"eyeGazeLivenessViewControllerAllCornersUsed:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerAllCornersUsed(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerAllCornersUsed:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerAllCornersUsed(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillTransition(_:)\/title","value":"eyeGazeLivenessViewControllerViewWillTransition:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillTransition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewWillTransition:"}]},{"value":"eyeGazeLivenessViewControllerViewWillAppear:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillAppear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"eyeGazeLivenessViewControllerViewWillAppear:","kind":"identifier"}]},{"value":"eyeGazeLivenessViewControllerViewDidAppear:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidAppear(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewDidAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidAppear(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}