{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The final result of the eye gaze liveness process.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFEyeGazeLivenessResult) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessResult","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult"]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessResult","kind":"identifier"}],"title":"EyeGazeLivenessResult","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult","navigatorTitle":[{"text":"EyeGazeLivenessResult","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class"},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/init(image:face:content:score:cornerImages:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/content","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/cornerImages","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/score"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/cornerImages":{"kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/cornerimages","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/cornerImages","type":"topic","deprecated":true,"title":"cornerImages","role":"symbol","navigatorTitle":[{"text":"cornerImages","kind":"identifier"}],"abstract":[{"text":"Array of images for each corner.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerImages","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"]","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/score":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/score","abstract":[{"text":"Returns the eye gaze liveness score from the interval [0, 1] if enabled by the license, null otherwise.","type":"text"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/score","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","title":"score","navigatorTitle":[{"text":"score","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/face":{"url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/face","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/face","role":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"}],"navigatorTitle":[{"kind":"identifier","text":"face"}],"title":"face","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult":{"abstract":[{"type":"text","text":"The final result of the eye gaze liveness process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult","url":"\/documentation\/dotfacecore\/eyegazelivenessresult","type":"topic","kind":"symbol","navigatorTitle":[{"text":"EyeGazeLivenessResult","kind":"identifier"}],"title":"EyeGazeLivenessResult","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/content":{"url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/content","navigatorTitle":[{"text":"content","kind":"identifier"}],"title":"content","type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Binary content for server-side evaluation."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/content"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/image":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"title":"image","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/image","abstract":[{"type":"text","text":"Face image."}],"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/image","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"image"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/init(image:face:content:score:cornerImages:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/init(image:face:content:score:cornerimages:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"score"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cornerImages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/init(image:face:content:score:cornerImages:)","navigatorTitle":[{"kind":"identifier","text":"initWithImage:face:content:score:cornerImages:"}],"abstract":[],"kind":"symbol","title":"init(image:face:content:score:cornerImages:)","type":"topic"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/description":{"kind":"symbol","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/description","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[]},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTFEyeGazeLivenessResult"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFEyeGazeLivenessResult","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/content","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/cornerImages","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/score"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/init(image:face:content:score:cornerImages:)"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1cornerImages\/title","op":"replace","value":"cornerImages"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1cornerImages\/fragments","op":"replace","value":[{"text":"cornerImages","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1score\/title","op":"replace","value":"score"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1score\/fragments","op":"replace","value":[{"text":"score","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1face\/title","op":"replace","value":"face"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1face\/fragments","op":"replace","value":[{"text":"face","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/title","op":"replace","value":"DOTFEyeGazeLivenessResult"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/fragments","op":"replace","value":[{"text":"DOTFEyeGazeLivenessResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1content\/title","op":"replace","value":"content"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1content\/fragments","op":"replace","value":[{"kind":"identifier","text":"content"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1image\/title","op":"replace","value":"image"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1image\/fragments","op":"replace","value":[{"kind":"identifier","text":"image"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1init(image:face:content:score:cornerImages:)\/title","op":"replace","value":"initWithImage:face:content:score:cornerImages:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1init(image:face:content:score:cornerImages:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:face:content:score:cornerImages:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}