{"seeAlsoSections":[{"title":"Face evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init(evaluateRightEye:evaluateLeftEye:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateLeftEye","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateRightEye"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFEyesExpressionQuery) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","roleHeading":"Class","title":"EyesExpressionQuery","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyesExpressionQuery","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery"},"abstract":[{"text":"Eyes expression query specifies which eye expression face attributes should be evaluated.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyesexpressionquery"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyesexpressionquery"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"navigatorTitle":[{"kind":"identifier","text":"HeadPoseQuery"}],"abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","role":"symbol","url":"\/documentation\/dotfacecore\/headposequery","type":"topic","title":"HeadPoseQuery","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery/evaluateLeftEye":{"type":"topic","title":"evaluateLeftEye","navigatorTitle":[{"kind":"identifier","text":"evaluateLeftEye"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Left eye evaluation flag."}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery\/evaluatelefteye","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateLeftEye","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateLeftEye"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"navigatorTitle":[{"kind":"identifier","text":"Expression"}],"abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Expression"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","role":"symbol","url":"\/documentation\/dotfacecore\/expression","type":"topic","title":"Expression","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"title":"HeadPose","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","kind":"symbol","abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPose"}],"url":"\/documentation\/dotfacecore\/headpose","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery/init(evaluateRightEye:evaluateLeftEye:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init(evaluateRightEye:evaluateLeftEye:)","kind":"symbol","title":"init(evaluateRightEye:evaluateLeftEye:)","url":"\/documentation\/dotfacecore\/eyesexpressionquery\/init(evaluaterighteye:evaluatelefteye:)","role":"symbol","navigatorTitle":[{"text":"initWithEvaluateRightEye:evaluateLeftEye:","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"evaluateRightEye"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"evaluateLeftEye","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"url":"\/documentation\/dotfacecore\/glasses","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Glasses","kind":"identifier"}],"title":"Glasses","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Glasses","kind":"identifier"}],"abstract":[{"text":"Face attribute for the glasses.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","type":"topic"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","role":"symbol","url":"\/documentation\/dotfacecore\/faceattribute","type":"topic","title":"FaceAttribute","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"title":"ExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","kind":"symbol","abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/expressionquery","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"role":"symbol","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceaspects","kind":"symbol","type":"topic","title":"FaceAspects","abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAspects","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.10.0","type":"text"}],"url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"title":"WearablesQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","kind":"symbol","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"url":"\/documentation\/dotfacecore\/wearablesquery","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WearablesQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"title":"FaceImageQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","kind":"symbol","abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImageQualityQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"title":"FaceQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","kind":"symbol","abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facequality","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HeadPoseAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","role":"symbol","url":"\/documentation\/dotfacecore\/headposeattribute","type":"topic","kind":"symbol","title":"HeadPoseAttribute"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery/init()":{"type":"topic","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/eyesexpressionquery\/init()","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQualityQuery"}],"url":"\/documentation\/dotfacecore\/facequalityquery","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","kind":"symbol","title":"FaceQualityQuery","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","role":"symbol","url":"\/documentation\/dotfacecore\/faceimagequality","type":"topic","title":"FaceImageQuality","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"title":"EyesExpression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","kind":"symbol","abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyesexpression","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpression"}]},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","role":"symbol","url":"\/documentation\/dotfacecore\/wearables","type":"topic","title":"Wearables","kind":"symbol"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery/evaluateRightEye":{"type":"topic","title":"evaluateRightEye","navigatorTitle":[{"text":"evaluateRightEye","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Right eye evaluation flag."}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery\/evaluaterighteye","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateRightEye","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateRightEye"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"title":"EyesExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","kind":"symbol","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpressionQuery","kind":"identifier"}]},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTFEyesExpressionQuery"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateLeftEye","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/evaluateRightEye"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery\/init(evaluateRightEye:evaluateLeftEye:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"op":"replace","value":[{"title":"Face evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTFEyesExpressionQuery","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace","value":"DOTFHeadPoseQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}]},{"value":"evaluateLeftEye","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateLeftEye\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateLeftEye\/fragments","value":[{"kind":"identifier","text":"evaluateLeftEye"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"text":"DOTFExpression","kind":"identifier"}]},{"value":"DOTFHeadPose","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"text":"DOTFHeadPose","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1init(evaluateRightEye:evaluateLeftEye:)\/title","value":"initWithEvaluateRightEye:evaluateLeftEye:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1init(evaluateRightEye:evaluateLeftEye:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithEvaluateRightEye:evaluateLeftEye:","kind":"identifier"}],"op":"replace"},{"value":"DOTFGlasses","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"kind":"identifier","text":"DOTFGlasses"}],"op":"replace"},{"value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects"},{"value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"value":"DOTFWearablesQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","op":"replace","value":"DOTFFaceQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1init()\/title","value":"init","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1init()\/fragments"},{"value":"DOTFFaceQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","op":"replace","value":"DOTFFaceImageQuality"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"},{"value":"DOTFEyesExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpression"}]},{"value":"DOTFWearables","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","value":[{"text":"DOTFWearables","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"evaluateRightEye","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateRightEye\/title"},{"value":[{"kind":"identifier","text":"evaluateRightEye"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery~1evaluateRightEye\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","value":"DOTFEyesExpressionQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}