{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFEyesExpression) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/init(rightEye:leftEye:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/leftEye","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/rightEye"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyesexpression"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyesexpression"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"title":"EyesExpression","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpression"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"title":"Face evaluation"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.15.0"}],"title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"kind":"symbol","title":"Expression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","url":"\/documentation\/dotfacecore\/expression","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Expression"}],"type":"topic","abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"navigatorTitle":[{"text":"Expression","kind":"identifier"}]},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression/rightEye":{"url":"\/documentation\/dotfacecore\/eyesexpression\/righteye","abstract":[{"text":"Right eye expression.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"rightEye"}],"type":"topic","title":"rightEye","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/rightEye","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEye"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","title":"FaceAttribute","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"url":"\/documentation\/dotfacecore\/wearables","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","title":"Wearables","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"navigatorTitle":[{"text":"Wearables","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"url":"\/documentation\/dotfacecore\/glasses","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","kind":"symbol","abstract":[{"type":"text","text":"Face attribute for the glasses."}],"title":"Glasses","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Glasses","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"kind":"symbol","title":"HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseAttribute"}],"type":"topic","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"kind":"symbol","title":"EyesExpressionQuery","url":"\/documentation\/dotfacecore\/eyesexpressionquery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpressionQuery"}],"type":"topic","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression/leftEye":{"abstract":[{"type":"text","text":"Left eye expression."}],"title":"leftEye","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEye"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier","text":"FaceAttribute"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"leftEye"}],"url":"\/documentation\/dotfacecore\/eyesexpression\/lefteye","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/leftEye"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"kind":"symbol","title":"FaceImageQualityQuery","url":"\/documentation\/dotfacecore\/faceimagequalityquery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImageQualityQuery","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"kind":"symbol","title":"HeadPose","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","url":"\/documentation\/dotfacecore\/headpose","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"navigatorTitle":[{"text":"HeadPose","kind":"identifier"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"kind":"symbol","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"title":"WearablesQuery","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WearablesQuery","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/wearablesquery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression/description":{"url":"\/documentation\/dotfacecore\/eyesexpression\/description","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression/init(rightEye:leftEye:)":{"type":"topic","role":"symbol","title":"init(rightEye:leftEye:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/init(rightEye:leftEye:)","url":"\/documentation\/dotfacecore\/eyesexpression\/init(righteye:lefteye:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rightEye"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"leftEye"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRightEye:leftEye:"}],"abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"kind":"symbol","title":"HeadPoseQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","url":"\/documentation\/dotfacecore\/headposequery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseQuery"}],"type":"topic","abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"kind":"symbol","title":"EyesExpression","url":"\/documentation\/dotfacecore\/eyesexpression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"kind":"symbol","title":"FaceQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","url":"\/documentation\/dotfacecore\/facequalityquery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQualityQuery"}],"type":"topic","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAspects"}],"navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceaspects","title":"FaceAspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","url":"\/documentation\/dotfacecore\/faceimagequality","abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceImageQuality","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"title":"FaceImageQuality","role":"symbol"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"kind":"symbol","title":"ExpressionQuery","url":"\/documentation\/dotfacecore\/expressionquery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressionQuery"}],"type":"topic","abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"kind":"symbol","title":"FaceQuality","type":"topic","url":"\/documentation\/dotfacecore\/facequality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","role":"symbol","abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFEyesExpression"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFEyesExpression"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpression"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/leftEye","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/rightEye"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression\/init(rightEye:leftEye:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"title":"Face evaluation"}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFEyesExpression"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"value":[{"text":"DOTFExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","op":"replace"},{"value":"rightEye","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1rightEye\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"rightEye"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1rightEye\/fragments"},{"value":"DOTFFaceAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace"},{"value":"DOTFWearables","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title"},{"op":"replace","value":[{"text":"DOTFWearables","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments"},{"value":"DOTFHeadPoseAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"op":"replace"},{"value":"DOTFEyesExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1leftEye\/title","value":"leftEye"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1leftEye\/fragments","value":[{"kind":"identifier","text":"leftEye"}],"op":"replace"},{"value":"DOTFFaceImageQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","value":"DOTFHeadPose"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","op":"replace","value":[{"text":"DOTFHeadPose","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1description\/title","value":"description","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":"initWithRightEye:leftEye:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1init(rightEye:leftEye:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression~1init(rightEye:leftEye:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithRightEye:leftEye:","kind":"identifier"}]},{"value":"DOTFHeadPoseQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","value":"DOTFEyesExpression"},{"value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments"},{"value":"DOTFFaceQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects","op":"replace"},{"op":"replace","value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","op":"replace","value":"DOTFFaceImageQuality"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace","value":[{"text":"DOTFFaceQuality","kind":"identifier"}]}]}]}