{"abstract":[{"type":"text","text":"Configuration for face library components."}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/init(faceSizeRatioInterval:query:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/faceSizeRatioInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/query"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/isEqual(_:)"]},{"anchor":"Enumerations","generated":true,"title":"Enumerations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFFaceLibraryComponentConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration"},"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"symbolKind":"class","title":"FaceLibraryComponentConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}]},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/hash":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/hash","abstract":[],"kind":"symbol","type":"topic","title":"hash"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/description":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/description","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/description","role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/query":{"type":"topic","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/query","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/query","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"query"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","text":"FaceDetectionQuery"}],"navigatorTitle":[{"kind":"identifier","text":"query"}],"abstract":[{"text":"Query for extra evaluations beyond basic face detection.","type":"text"}],"role":"symbol","kind":"symbol","title":"query"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration for face library components.","type":"text"}],"url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","title":"FaceLibraryComponentConfiguration"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/faceSizeRatioInterval":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/faceSizeRatioInterval","navigatorTitle":[{"kind":"identifier","text":"faceSizeRatioInterval"}],"title":"faceSizeRatioInterval","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Interval of the minimal and maximal face size in a image used for the face detection during the capture process. Values must be in range [0.0, 1.0]."}],"type":"topic","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/facesizeratiointerval"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/init(faceSizeRatioInterval:query:)":{"navigatorTitle":[{"text":"initWithFaceSizeRatioInterval:query:error:","kind":"identifier"}],"title":"init(faceSizeRatioInterval:query:)","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/init(faceSizeRatioInterval:query:)","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/init(facesizeratiointerval:query:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":", ","kind":"text"},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/isEqual(_:)":{"url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/isequal(_:)","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/isEqual(_:)","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error":{"role":"symbol","abstract":[],"title":"FaceLibraryComponentConfiguration.Error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error","type":"topic","navigatorTitle":[{"text":"Error","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceLibraryComponentConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/faceSizeRatioInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/query"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/init(faceSizeRatioInterval:query:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1query\/title","value":"query","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1query\/fragments","value":[{"kind":"identifier","text":"query"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1faceSizeRatioInterval\/title","value":"faceSizeRatioInterval","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1faceSizeRatioInterval\/fragments","value":[{"text":"faceSizeRatioInterval","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithFaceSizeRatioInterval:query:error:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1init(faceSizeRatioInterval:query:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFaceSizeRatioInterval:query:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1init(faceSizeRatioInterval:query:)\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration~1isEqual(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}