{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFaceSimpleCaptureViewControllerDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Implement this delegate to handle the face simple capture events."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"title":"FaceSimpleCaptureViewControllerDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@DotFaceCore@objc(pl)DOTFaceSimpleCaptureViewControllerDelegate","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewController(_:captured:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerNoCameraPermission(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerStopped(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLoad(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillTransition(_:)"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewDidDisappear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear:"}],"role":"symbol","title":"faceSimpleCaptureViewControllerViewDidDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidDisappear(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdiddisappear(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewWillDisappear(_:)":{"role":"symbol","title":"faceSimpleCaptureViewControllerViewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillDisappear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillDisappear:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewwilldisappear(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerStopped(_:)":{"role":"symbol","title":"faceSimpleCaptureViewControllerStopped(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerStopped"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the component has stopped."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerStopped(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerStopped:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerstopped(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewDidLayoutSubviews(_:)":{"role":"symbol","title":"faceSimpleCaptureViewControllerViewDidLayoutSubviews(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLayoutSubviews"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLayoutSubviews(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLayoutSubviews:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdidlayoutsubviews(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewController(_:captured:)":{"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewController:captured:"}],"role":"symbol","title":"faceSimpleCaptureViewController(_:captured:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captured"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTDetectedFace"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the face was captured."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewController(_:captured:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontroller(_:captured:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewDidLoad(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLoad:"}],"role":"symbol","title":"faceSimpleCaptureViewControllerViewDidLoad(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLoad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLoad(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdidload(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerNoCameraPermission(_:)":{"role":"symbol","title":"faceSimpleCaptureViewControllerNoCameraPermission(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerNoCameraPermission(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerNoCameraPermission:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollernocamerapermission(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewDidAppear(_:)":{"role":"symbol","title":"faceSimpleCaptureViewControllerViewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidAppear(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidAppear:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdidappear(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"role":"symbol","title":"FaceSimpleCaptureViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the face simple capture events."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewWillTransition(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillTransition:"}],"role":"symbol","title":"faceSimpleCaptureViewControllerViewWillTransition(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillTransition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillTransition(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewwilltransition(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewWillAppear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear:"}],"role":"symbol","title":"faceSimpleCaptureViewControllerViewWillAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillAppear(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewwillappear(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DOTFaceSimpleCaptureViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFaceSimpleCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceSimpleCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewController(_:captured:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerNoCameraPermission(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerStopped(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLoad(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillAppear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillDisappear(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewWillTransition(_:)"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFaceSimpleCaptureViewControllerDelegate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidDisappear(_:)\/title","value":"faceSimpleCaptureViewControllerViewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillDisappear(_:)\/title","value":"faceSimpleCaptureViewControllerViewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerStopped(_:)\/title","value":"faceSimpleCaptureViewControllerStopped:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerStopped(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerStopped:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidLayoutSubviews(_:)\/title","value":"faceSimpleCaptureViewControllerViewDidLayoutSubviews:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLayoutSubviews:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewController(_:captured:)\/title","value":"faceSimpleCaptureViewController:captured:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewController(_:captured:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewController:captured:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidLoad(_:)\/title","value":"faceSimpleCaptureViewControllerViewDidLoad:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLoad:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerNoCameraPermission(_:)\/title","value":"faceSimpleCaptureViewControllerNoCameraPermission:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerNoCameraPermission(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerNoCameraPermission:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidAppear(_:)\/title","value":"faceSimpleCaptureViewControllerViewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title","value":"DOTFaceSimpleCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFaceSimpleCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillTransition(_:)\/title","value":"faceSimpleCaptureViewControllerViewWillTransition:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillTransition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillTransition:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFaceSimpleCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillAppear(_:)\/title","value":"faceSimpleCaptureViewControllerViewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewWillAppear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}