{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper\/init(feature:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper\/description"]}],"abstract":[{"type":"text","text":"Face feature wrapper."}],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"FaceFeatureWrapper","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceFeatureWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeatureWrapper","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"FaceFeatureWrapper"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFFaceFeatureWrapper) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceFeatureWrapper"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/facefeaturewrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeaturewrapper"]}],"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeatureWrapper/init(feature:)":{"url":"\/documentation\/dotfacecore\/facefeaturewrapper\/init(feature:)","title":"init(feature:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"feature"},{"kind":"text","text":": "},{"text":"FaceFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper\/init(feature:)","navigatorTitle":[{"kind":"identifier","text":"initWithFeature:"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeatureWrapper/description":{"kind":"symbol","abstract":[{"type":"text","text":"Get face feature description."}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facefeaturewrapper\/description","title":"description","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeatureWrapper":{"kind":"symbol","abstract":[{"text":"Face feature wrapper.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FaceFeatureWrapper"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facefeaturewrapper","title":"FaceFeatureWrapper","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceFeatureWrapper","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTFFaceFeatureWrapper","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFFaceFeatureWrapper","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureWrapper"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper\/description"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeatureWrapper\/init(feature:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFFaceFeatureWrapper","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"initWithFeature:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeatureWrapper~1init(feature:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeatureWrapper~1init(feature:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFeature:","kind":"identifier"}]},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeatureWrapper~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeatureWrapper~1description\/fragments","op":"replace"},{"value":"DOTFFaceFeatureWrapper","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeatureWrapper\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeatureWrapper\/fragments","value":[{"text":"DOTFFaceFeatureWrapper","kind":"identifier"}]}]}]}