{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","interfaceLanguage":"swift"},"metadata":{"title":"FaceImageQualityQuery","role":"symbol","roleHeading":"Class","symbolKind":"class","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImageQualityQuery"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBackgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBrightness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateContrast","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateShadow","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateSharpness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateSpecularity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateUniqueIntensityLevels"],"title":"Instance Properties"}],"sections":[],"abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"title":"Face evaluation"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceImageQualityQuery) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimagequalityquery"]},{"paths":["\/documentation\/dotfacecore\/faceimagequalityquery"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateUniqueIntensityLevels":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateUniqueIntensityLevels","navigatorTitle":[{"text":"evaluateUniqueIntensityLevels","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"evaluateUniqueIntensityLevels","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"evaluateUniqueIntensityLevels","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateuniqueintensitylevels","abstract":[{"type":"text","text":"Unique intensity levels evaluation flag."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"url":"\/documentation\/dotfacecore\/faceattribute","title":"FaceAttribute","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAttribute","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"type":"topic","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"role":"symbol","title":"FaceAspects","url":"\/documentation\/dotfacecore\/faceaspects","abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}]},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/expression","abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Expression"}],"navigatorTitle":[{"text":"Expression","kind":"identifier"}],"title":"Expression"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"type":"topic","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"role":"symbol","title":"HeadPose","url":"\/documentation\/dotfacecore\/headpose","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","title":"FaceImageQualityQuery","abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"type":"topic","navigatorTitle":[{"text":"Glasses","kind":"identifier"}],"role":"symbol","title":"Glasses","url":"\/documentation\/dotfacecore\/glasses","abstract":[{"text":"Face attribute for the glasses.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"type":"topic","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"role":"symbol","title":"HeadPoseQuery","url":"\/documentation\/dotfacecore\/headposequery","abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"type":"topic","navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"role":"symbol","title":"EyesExpression","url":"\/documentation\/dotfacecore\/eyesexpression","abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpression"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateShadow":{"title":"evaluateShadow","kind":"symbol","abstract":[{"type":"text","text":"Shadow evaluation flag."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateShadow"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"evaluateShadow","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluateshadow","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateShadow"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)","title":"init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/init(evaluatesharpness:evaluatebrightness:evaluatecontrast:evaluateuniqueintensitylevels:evaluateshadow:evaluatespecularity:evaluatebackgrounduniformity:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"evaluateSharpness","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"evaluateBrightness","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateContrast"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateUniqueIntensityLevels"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateShadow"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"evaluateSpecularity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"evaluateBackgroundUniformity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQualityQuery"}],"kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"url":"\/documentation\/dotfacecore\/facequalityquery","title":"FaceQualityQuery","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateSharpness":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateSharpness"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"evaluateSharpness","abstract":[{"text":"Sharpness evaluation flag.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"evaluateSharpness"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateSharpness","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatesharpness","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateBackgroundUniformity":{"title":"evaluateBackgroundUniformity","role":"symbol","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebackgrounduniformity","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBackgroundUniformity","type":"topic","abstract":[{"text":"Background uniformity evaluation flag.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"evaluateBackgroundUniformity"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateBackgroundUniformity","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateSpecularity":{"navigatorTitle":[{"text":"evaluateSpecularity","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateSpecularity","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateSpecularity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatespecularity","role":"symbol","title":"evaluateSpecularity","abstract":[{"type":"text","text":"Specularity evaluation flag."}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/headposeattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","title":"HeadPoseAttribute","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/eyesexpressionquery","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpressionQuery"}],"navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}],"title":"EyesExpressionQuery"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/wearables","abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Wearables"}],"navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"title":"Wearables"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"type":"topic","navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}],"role":"symbol","title":"ExpressionQuery","url":"\/documentation\/dotfacecore\/expressionquery","abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateContrast":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateContrast","abstract":[{"text":"Contrast evaluation flag.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"evaluateContrast","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatecontrast","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"evaluateContrast","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"evaluateContrast"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateBrightness":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBrightness","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"evaluateBrightness"}],"type":"topic","abstract":[{"text":"Brightness evaluation flag.","type":"text"}],"kind":"symbol","title":"evaluateBrightness","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebrightness","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateBrightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","title":"FaceImageQuality","navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImageQuality","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceimagequality"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","title":"FaceQuality","abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/init()":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init()","title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/faceimagequalityquery\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"title":"WearablesQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WearablesQuery"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","url":"\/documentation\/dotfacecore\/wearablesquery"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceImageQualityQuery"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBackgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBrightness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateContrast","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateShadow","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateSharpness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateSpecularity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateUniqueIntensityLevels"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"title":"Face evaluation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFFaceImageQualityQuery"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"evaluateUniqueIntensityLevels","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateUniqueIntensityLevels\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateUniqueIntensityLevels\/fragments","value":[{"text":"evaluateUniqueIntensityLevels","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","op":"replace"},{"value":"DOTFExpression","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFExpression"}]},{"value":"DOTFHeadPose","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments"},{"value":"DOTFFaceImageQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFGlasses","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"kind":"identifier","text":"DOTFGlasses"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","value":"DOTFHeadPoseQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","value":"DOTFEyesExpression"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","value":[{"text":"DOTFEyesExpression","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateShadow\/title","value":"evaluateShadow","op":"replace"},{"value":[{"text":"evaluateShadow","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateShadow\/fragments"},{"op":"replace","value":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEvaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1init(evaluateSharpness:evaluateBrightness:evaluateContrast:evaluateUniqueIntensityLevels:evaluateShadow:evaluateSpecularity:evaluateBackgroundUniformity:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"value":"evaluateSharpness","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateSharpness\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateSharpness\/fragments","value":[{"text":"evaluateSharpness","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBackgroundUniformity\/title","op":"replace","value":"evaluateBackgroundUniformity"},{"op":"replace","value":[{"text":"evaluateBackgroundUniformity","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBackgroundUniformity\/fragments"},{"op":"replace","value":"evaluateSpecularity","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateSpecularity\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateSpecularity\/fragments","value":[{"text":"evaluateSpecularity","kind":"identifier"}]},{"value":"DOTFHeadPoseAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","value":"DOTFEyesExpressionQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"op":"replace"},{"value":"DOTFWearables","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments"},{"value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","op":"replace"},{"value":[{"text":"DOTFExpressionQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateContrast\/title","op":"replace","value":"evaluateContrast"},{"value":[{"text":"evaluateContrast","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateContrast\/fragments"},{"value":"evaluateBrightness","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBrightness\/title"},{"op":"replace","value":[{"text":"evaluateBrightness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBrightness\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","value":"DOTFFaceImageQuality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}],"op":"replace"},{"value":"DOTFFaceQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments"}]}]}