{"seeAlsoSections":[{"title":"Face simple capture result","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureDetection"}],"title":"FaceSimpleCaptureDetection","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureDetection","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureDetection"}]},"abstract":[{"type":"text","text":"The result of processing video frame during the face simple capture process."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/init(bgrRawImage:detectedFace:position:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/bgrRawImage","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/detectedFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/position"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecapturedetection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facesimplecapturedetection"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFFaceSimpleCaptureDetection) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureDetection"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition":{"role":"symbol","title":"DetectionPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"type":"text","text":"The position of the detected face in the image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"url":"\/documentation\/dotfacecore\/detectionposition"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureDetection/detectedFace":{"role":"symbol","title":"detectedFace","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Detected face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/detectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectedFace"}],"url":"\/documentation\/dotfacecore\/facesimplecapturedetection\/detectedface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureDetection":{"role":"symbol","title":"FaceSimpleCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the face simple capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureDetection"}],"url":"\/documentation\/dotfacecore\/facesimplecapturedetection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureDetection/position":{"role":"symbol","title":"position","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTDetectionPosition"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Position of the detected face in the detection image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/position","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"position"}],"url":"\/documentation\/dotfacecore\/facesimplecapturedetection\/position"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureDetection/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfacecore\/facesimplecapturedetection\/description"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureDetection/bgrRawImage":{"role":"symbol","title":"bgrRawImage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"}],"abstract":[{"type":"text","text":"Detection image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/bgrRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bgrRawImage"}],"url":"\/documentation\/dotfacecore\/facesimplecapturedetection\/bgrrawimage"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.0.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureResult":{"role":"symbol","title":"FaceSimpleCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the face simple capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureResult"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureresult"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureDetection/init(bgrRawImage:detectedFace:position:)":{"role":"symbol","title":"init(bgrRawImage:detectedFace:position:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTDetectionPosition"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/init(bgrRawImage:detectedFace:position:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBgrRawImage:detectedFace:position:"}],"url":"\/documentation\/dotfacecore\/facesimplecapturedetection\/init(bgrrawimage:detectedface:position:)"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceSimpleCaptureDetection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureDetection"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureDetection"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/bgrRawImage","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/detectedFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/position"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureDetection\/init(bgrRawImage:detectedFace:position:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Face simple capture result","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFFaceSimpleCaptureDetection"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1detectedFace\/title","value":"detectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1detectedFace\/fragments","value":[{"kind":"identifier","text":"detectedFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection\/title","value":"DOTFFaceSimpleCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1position\/title","value":"position"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1position\/fragments","value":[{"kind":"identifier","text":"position"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1bgrRawImage\/title","value":"bgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1bgrRawImage\/fragments","value":[{"kind":"identifier","text":"bgrRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/title","value":"DOTFFaceSimpleCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1init(bgrRawImage:detectedFace:position:)\/title","value":"initWithBgrRawImage:detectedFace:position:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureDetection~1init(bgrRawImage:detectedFace:position:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBgrRawImage:detectedFace:position:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}