{"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"seeAlsoSections":[{"title":"Face detection input","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFFaceImage) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImage","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"FaceImage","kind":"identifier"}],"symbolKind":"class","title":"FaceImage","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImage","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/faceimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimage"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Face image is used for face detection, matching and verification.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/init(bgrRawImage:faceSizeRatioInterval:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/bgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/faceSizeRatioInterval"],"title":"Instance Properties"}],"references":{"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage/faceSizeRatioInterval":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/faceSizeRatioInterval","url":"\/documentation\/dotfacecore\/faceimage\/facesizeratiointerval","type":"topic","abstract":[{"type":"text","text":"Face size ratio interval used for face detection."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"}],"title":"faceSizeRatioInterval","navigatorTitle":[{"kind":"identifier","text":"faceSizeRatioInterval"}]},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage/init(bgrRawImage:faceSizeRatioInterval:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBgrRawImage:faceSizeRatioInterval:error:"}],"title":"init(bgrRawImage:faceSizeRatioInterval:)","type":"topic","abstract":[{"type":"text","text":"Create face image from raw image and face size interval."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/init(bgrRawImage:faceSizeRatioInterval:)","role":"symbol","url":"\/documentation\/dotfacecore\/faceimage\/init(bgrrawimage:facesizeratiointerval:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgrRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","url":"\/documentation\/dotfacecore\/bgrrawimage","title":"BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","title":"FaceDetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"navigatorTitle":[{"text":"FaceImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"url":"\/documentation\/dotfacecore\/faceimage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImage"}],"title":"FaceImage","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage/bgrRawImage":{"abstract":[{"text":"Raw face image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bgrRawImage"}],"url":"\/documentation\/dotfacecore\/faceimage\/bgrrawimage","kind":"symbol","role":"symbol","type":"topic","title":"bgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/bgrRawImage","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bgrRawImage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}]},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceImage"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFFaceImage"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceImage","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/bgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/faceSizeRatioInterval"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/init(bgrRawImage:faceSizeRatioInterval:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"],"generated":true,"title":"Face detection input"}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFFaceImage"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1faceSizeRatioInterval\/title","value":"faceSizeRatioInterval"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1faceSizeRatioInterval\/fragments","value":[{"kind":"identifier","text":"faceSizeRatioInterval"}]},{"op":"replace","value":"initWithBgrRawImage:faceSizeRatioInterval:error:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1init(bgrRawImage:faceSizeRatioInterval:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1init(bgrRawImage:faceSizeRatioInterval:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBgrRawImage:faceSizeRatioInterval:error:","kind":"identifier"}]},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace"},{"value":"DOTFFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace"},{"op":"replace","value":"DOTFFaceImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1bgrRawImage\/title","value":"bgrRawImage"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1bgrRawImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"bgrRawImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}