{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureresult"]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureresult"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult","title":"FaceAutoCaptureResult"},"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/init(bgrRawImage:face:content:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/bgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/content","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/face"],"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceAutoCaptureResult) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"seeAlsoSections":[{"title":"Face auto capture result","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"generated":true}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturedetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureDetection","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult/face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/face","type":"topic","navigatorTitle":[{"text":"face","kind":"identifier"}],"abstract":[{"text":"Detected face in the image. Might be ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" only if ","type":"text"},{"type":"reference","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","isActive":true},{"type":"text","text":" was used to get the result."}],"role":"symbol","title":"face","url":"\/documentation\/dotfacecore\/faceautocaptureresult\/face","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"text":".","kind":"text"},{"text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.11.0"}],"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"abstract":[{"text":"Request capture of the next detection.","type":"text"}],"role":"symbol","title":"requestCapture(isFacePresenceRequired:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"url":"\/documentation\/dotfacecore\/faceautocaptureresult","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureResult","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"FaceAutoCaptureViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}]},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"url":"\/documentation\/dotfacecore\/detectionposition","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult/content":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/content","type":"topic","navigatorTitle":[{"text":"content","kind":"identifier"}],"abstract":[{"text":"Binary content for server-side evaluation.","type":"text"}],"role":"symbol","title":"content","url":"\/documentation\/dotfacecore\/faceautocaptureresult\/content","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/description","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"role":"symbol","title":"description","url":"\/documentation\/dotfacecore\/faceautocaptureresult\/description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult/bgrRawImage":{"abstract":[{"type":"text","text":"Face image."}],"url":"\/documentation\/dotfacecore\/faceautocaptureresult\/bgrrawimage","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bgrRawImage"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgrRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"type":"topic","title":"bgrRawImage","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/bgrRawImage"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult/init(bgrRawImage:face:content:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/init(bgrRawImage:face:content:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBgrRawImage:face:content:"}],"abstract":[],"role":"symbol","title":"init(bgrRawImage:face:content:)","url":"\/documentation\/dotfacecore\/faceautocaptureresult\/init(bgrrawimage:face:content:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":")","kind":"text"}]},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceAutoCaptureResult"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/bgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/content","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/face"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/init(bgrRawImage:face:content:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Face auto capture result","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"generated":true}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"value":"face","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1face\/title"},{"value":[{"text":"face","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1face\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","value":"requestCaptureWithIsFacePresenceRequired:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}]},{"value":"DOTFFaceAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFFaceAutoCaptureViewController"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"value":"DOTDetectionPosition","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1content\/title","value":"content","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1content\/fragments","value":[{"text":"content","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1description\/fragments","op":"replace"},{"value":"bgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1bgrRawImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1bgrRawImage\/fragments","value":[{"kind":"identifier","text":"bgrRawImage"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1init(bgrRawImage:face:content:)\/title","op":"replace","value":"initWithBgrRawImage:face:content:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBgrRawImage:face:content:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1init(bgrRawImage:face:content:)\/fragments","op":"replace"}]}]}