{"seeAlsoSections":[{"generated":true,"title":"Non-UI components","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","interfaceLanguage":"swift"},"metadata":{"title":"FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","modules":[{"name":"DotFaceCore"}],"roleHeading":"Class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceDetector) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/facedetector"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facedetector"]}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"],"title":"Face detection input"},{"title":"Face detection output","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/init()"],"title":"Initializers"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/detect(faceImage:query:limit:)"]},{"title":"Enumerations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error"]}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","kind":"symbol","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImage","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceimage","role":"symbol","title":"FaceImage","navigatorTitle":[{"kind":"identifier","text":"FaceImage"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Error":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facedetector\/error","abstract":[],"title":"FaceDetector.Error","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/detect(faceImage:query:limit:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/detect(faceImage:query:limit:)","abstract":[{"type":"text","text":"Detect faces in an image."}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"faceImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","text":"FaceImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"limit"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facedetector\/detect(faceimage:query:limit:)","role":"symbol","title":"detect(faceImage:query:limit:)","navigatorTitle":[{"text":"detectWithFaceImage:query:limit:error:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","kind":"symbol","abstract":[{"text":"Stateless class which can match templates.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateMatcher","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/templatematcher","role":"symbol","title":"TemplateMatcher","navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"url":"\/documentation\/dotfacecore\/facedetector","title":"FaceDetector","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}]},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/bgrrawimage","role":"symbol","title":"BgrRawImage","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceMatcher"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","role":"symbol","abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}],"title":"FaceMatcher","navigatorTitle":[{"text":"FaceMatcher","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facematcher"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/init()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/init()","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facedetector\/init()","role":"symbol","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","url":"\/documentation\/dotfacecore\/facedetector\/face","role":"symbol","type":"topic","abstract":[{"text":"Detected face in the image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Face","kind":"identifier"}],"title":"FaceDetector.Face","navigatorTitle":[{"kind":"identifier","text":"Face"}]},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceDetector"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"],"title":"Face detection input"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/detect(faceImage:query:limit:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/init()"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher"],"title":"Non-UI components","generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFFaceDetector"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DOTFFaceImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments","value":[{"text":"DOTFFaceImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector~1detect(faceImage:query:limit:)\/title","op":"replace","value":"detectWithFaceImage:query:limit:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithFaceImage:query:limit:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector~1detect(faceImage:query:limit:)\/fragments"},{"value":"DOTFTemplateMatcher","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace"},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","value":"DOTFFaceMatcher"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","value":[{"text":"DOTFFaceMatcher","kind":"identifier"}]},{"value":"init","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector~1init()\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector~1init()\/fragments"}]}]}