{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"},"abstract":[{"type":"text","text":"UI component for capturing face images."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"]}],"metadata":{"title":"FaceSimpleCaptureViewController","modules":[{"name":"DotFaceCore"}],"platforms":[],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"roleHeading":"Class"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceSimpleCaptureViewController) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"inlineContent":[{"text":"This component requires the ","type":"text"},{"type":"codeVoice","code":"DotFaceDetection*"},{"text":" module to be active.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSCoding","doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/s8SendableP","doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer","doc:\/\/DotFaceCore\/objc(pl)UIContentContainer","doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring","doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Style-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class"],"title":"Style and configuration"},{"title":"Delegate","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"title":"Face simple capture result"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/init(configuration:style:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/style-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/requestCapture()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillTransition(to:with:)"]}],"seeAlsoSections":[{"title":"UI components","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/init(configuration:style:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/init(configuration:style:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/init(configuration:style:)","deprecated":true,"title":"init(configuration:style:)","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC"},{"kind":"text","text":")"}],"abstract":[{"text":"Create new ","type":"text"},{"code":"FaceSimpleCaptureViewController","type":"codeVoice"},{"type":"text","text":"."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Style-swift.class":{"title":"FaceSimpleCaptureViewController.Style","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[{"type":"text","text":"Customization options for the face simple capture user interface."}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/style-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Style-swift.class","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"deprecated":true,"type":"topic"},"doc://DotFaceCore/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/style-swift.property":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/style-swift.property","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/style-swift.property","deprecated":true,"title":"style","navigatorTitle":[{"text":"style","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Current style."}]},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/viewDidDisappear(_:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidDisappear(_:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/viewdiddisappear(_:)","deprecated":true,"title":"viewDidDisappear(_:)","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[]},"doc://DotFaceCore/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"kind":"symbol","title":"EyeGazeLivenessViewController","type":"topic","abstract":[{"text":"UI component for evaluating liveness by tracking eye gaze.","type":"text"}],"navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"kind":"symbol","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","title":"FaceSimpleCaptureViewController","navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","type":"topic","kind":"symbol","title":"DetectionPosition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"url":"\/documentation\/dotfacecore\/detectionposition"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.2"}]},"doc://DotFaceCore/objc(pl)NSCoding":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","title":"MagnifEyeLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/objc(cs)UIViewController":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/viewWillDisappear(_:)":{"title":"viewWillDisappear(_:)","kind":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/viewwilldisappear(_:)","deprecated":true,"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillDisappear(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/delegate":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/delegate","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/delegate","deprecated":true,"title":"delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate","text":"FaceSimpleCaptureViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Set this delegate to handle the face simple capture events.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/requestCapture()":{"abstract":[{"type":"text","text":"Request face capture."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/requestCapture()","deprecated":true,"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"text":"()","kind":"text"}],"title":"requestCapture()","type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/requestcapture()","navigatorTitle":[{"text":"requestCapture","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"title":"SmileLivenessViewController","navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","type":"topic","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/viewDidLayoutSubviews()":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidLayoutSubviews()","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/viewdidlayoutsubviews()","deprecated":true,"title":"viewDidLayoutSubviews()","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/viewWillTransition(to:with:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillTransition(to:with:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/viewwilltransition(to:with:)","deprecated":true,"title":"viewWillTransition(to:with:)","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/start()":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/start()","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/start()","deprecated":true,"title":"start()","navigatorTitle":[{"text":"start","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"()","kind":"text"}],"abstract":[{"text":"Start the face simple capture process.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/stopAsync(onStopped:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/stopAsync(onStopped:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/stopasync(onstopped:)","deprecated":true,"title":"stopAsync(onStopped:)","navigatorTitle":[{"kind":"identifier","text":"stopAsyncOnStopped:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAsync","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"onStopped"},{"kind":"text","text":": () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Stop the face simple capture process asynchronously. The ","type":"text"},{"code":"onStopped","type":"codeVoice"},{"text":" callback is called after the process has stopped.","type":"text"}]},"doc://DotFaceCore/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://DotFaceCore/s8SendableP":{"identifier":"doc:\/\/DotFaceCore\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/viewDidLoad()":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidLoad()","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/viewdidload()","deprecated":true,"title":"viewDidLoad()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/configuration-swift.property":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/configuration-swift.property","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.property","deprecated":true,"title":"configuration","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Current configuration."}]},"doc://DotFaceCore/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://DotFaceCore/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"title":"FaceAutoCaptureViewController","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"deprecated":true,"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate","role":"symbol","kind":"symbol","abstract":[{"text":"Implement this delegate to handle the face simple capture events.","type":"text"}],"title":"FaceSimpleCaptureViewControllerDelegate","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"navigatorTitle":[{"text":"FaceSimpleCaptureViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}],"deprecated":true,"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class","title":"FaceSimpleCaptureViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://DotFaceCore/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureResult":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","url":"\/documentation\/dotfacecore\/facesimplecaptureresult","title":"FaceSimpleCaptureResult","navigatorTitle":[{"text":"FaceSimpleCaptureResult","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the face simple capture process."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/viewDidAppear(_:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidAppear(_:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/viewdidappear(_:)","deprecated":true,"title":"viewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[]},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment"},"doc://DotFaceCore/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/viewWillAppear(_:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillAppear(_:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/viewwillappear(_:)","deprecated":true,"title":"viewWillAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[]},"doc://DotFaceCore/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"DOTFFaceSimpleCaptureViewController","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"],"title":"Delegate"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"title":"Face simple capture result"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/style-swift.property"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/init(configuration:style:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/requestCapture()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"],"type":"inheritsFrom"}],"op":"replace"},{"op":"replace","value":[{"generated":true,"title":"UI components","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"]}],"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1init(configuration:style:)\/title","value":"initWithConfiguration:style:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1init(configuration:style:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:style:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1style-swift.property\/title","value":"style"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1style-swift.property\/fragments","value":[{"kind":"identifier","text":"style"}],"op":"replace"},{"value":"viewDidDisappear:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidDisappear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}]},{"value":"DOTFEyeGazeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}]},{"value":"DOTDetectionPosition","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"value":"viewWillDisappear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewWillDisappear(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewWillDisappear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}]},{"value":"delegate","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1delegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1delegate\/fragments","op":"replace"},{"value":"requestCapture","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1requestCapture()\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1requestCapture()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestCapture"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidLayoutSubviews()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},{"value":"viewWillTransitionToSize:withTransitionCoordinator:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewWillTransition(to:with:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewWillTransition(to:with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1start()\/title","value":"start"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1start()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}]},{"value":"stopAsyncOnStopped:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1stopAsync(onStopped:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1stopAsync(onStopped:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopAsyncOnStopped:","kind":"identifier"}]},{"op":"replace","value":"viewDidLoad","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidLoad()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidLoad()\/fragments","op":"replace"},{"value":"configuration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1configuration-swift.property\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1configuration-swift.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"configuration"}]},{"op":"replace","value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"value":"DOTFFaceSimpleCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/title","value":"DOTFFaceSimpleCaptureResult","op":"replace"},{"op":"replace","value":[{"text":"DOTFFaceSimpleCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1viewWillAppear(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}