{"abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createFullFrontalImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createTemplate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/evaluatePassiveLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/quality"]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"title":"FaceDetectionQuery","externalID":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"role":"symbol","symbolKind":"class"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"inlineContent":[{"text":"If an attribute in the query requires a module which is not activated, fatal error will occur during the processing of the query.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotfacecore\/facedetectionquery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facedetectionquery"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/createFullFrontalImage":{"title":"createFullFrontalImage","navigatorTitle":[{"text":"createFullFrontalImage","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createFullFrontalImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Create an ICAO full frontal image of the face."},{"text":" ","type":"text"},{"type":"text","text":"If boundaries of the normalized image leak outside of the original image, a white background is applied."},{"type":"text","text":" "},{"text":"Default value is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createFullFrontalImage","url":"\/documentation\/dotfacecore\/facedetectionquery\/createfullfrontalimage","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)":{"abstract":[],"navigatorTitle":[{"text":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}],"title":"init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","type":"topic","url":"\/documentation\/dotfacecore\/facedetectionquery\/init(quality:evaluatepassiveliveness:createfullfrontalimage:createtemplate:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceQualityQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery"},{"text":", ","kind":"text"},{"text":"evaluatePassiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"createFullFrontalImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"createTemplate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/quality":{"role":"symbol","abstract":[{"type":"text","text":"Face image quality query."}],"title":"quality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/facedetectionquery\/quality","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/quality","navigatorTitle":[{"text":"quality","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"role":"symbol","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"title":"FaceDetectionQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facedetectionquery","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/description":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/description","url":"\/documentation\/dotfacecore\/facedetectionquery\/description","title":"description"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/createTemplate":{"title":"createTemplate","navigatorTitle":[{"text":"createTemplate","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTemplate"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Create the face template which can be used for matching. This flag requires "},{"code":"DotFaceVerification","type":"codeVoice"},{"type":"text","text":" module. Default value is "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createTemplate","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery\/createtemplate","role":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/evaluatePassiveLiveness":{"abstract":[{"type":"text","text":"Passive liveness evaluation flag. This method requires "},{"type":"codeVoice","code":"DotFacePassiveLiveness"},{"text":" module. Default value is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"evaluatePassiveLiveness"}],"title":"evaluatePassiveLiveness","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/evaluatePassiveLiveness","type":"topic","url":"\/documentation\/dotfacecore\/facedetectionquery\/evaluatepassiveliveness","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluatePassiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"FaceDetectionQuery","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createFullFrontalImage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createTemplate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/evaluatePassiveLiveness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/quality"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetectionQuery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createFullFrontalImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1createFullFrontalImage\/title"},{"value":[{"text":"createFullFrontalImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1createFullFrontalImage\/fragments"},{"value":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)\/fragments"},{"value":"quality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1quality\/title"},{"value":[{"text":"quality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1quality\/fragments"},{"value":"FaceDetectionQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title"},{"value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"},{"value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1description\/fragments"},{"value":"createTemplate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1createTemplate\/title"},{"value":[{"text":"createTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1createTemplate\/fragments"},{"value":"evaluatePassiveLiveness","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1evaluatePassiveLiveness\/title"},{"value":[{"text":"evaluatePassiveLiveness","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1evaluatePassiveLiveness\/fragments"}]}]}