{"sections":[],"metadata":{"role":"symbol","roleHeading":"Class","title":"FaceQuality","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}],"symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/init(imageQuality:headPose:wearables:expression:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/headPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/imageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/wearables"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFFaceQuality) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceQuality","kind":"identifier"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"title":"Face evaluation","generated":true}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facequality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facequality"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/expression":{"url":"\/documentation\/dotfacecore\/facequality\/expression","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/expression","kind":"symbol","abstract":[{"type":"text","text":"Face expression evaluation result."}],"title":"expression","navigatorTitle":[{"text":"expression","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expression","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpression","text":"Expression"}],"role":"symbol"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQualityQuery"}],"role":"symbol","kind":"symbol","type":"topic","title":"FaceQualityQuery","navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/facequalityquery"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"navigatorTitle":[{"text":"Glasses","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Face attribute for the glasses.","type":"text"}],"title":"Glasses","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Glasses"}],"url":"\/documentation\/dotfacecore\/glasses","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"role":"symbol","kind":"symbol","type":"topic","title":"FaceImageQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAspects"}],"role":"symbol","kind":"symbol","type":"topic","title":"FaceAspects","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"url":"\/documentation\/dotfacecore\/faceaspects"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}],"role":"symbol","kind":"symbol","type":"topic","title":"EyesExpressionQuery","navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPose"}],"role":"symbol","kind":"symbol","type":"topic","title":"HeadPose","navigatorTitle":[{"kind":"identifier","text":"HeadPose"}],"abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"url":"\/documentation\/dotfacecore\/headpose"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/headPose":{"url":"\/documentation\/dotfacecore\/facequality\/headpose","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/headPose","kind":"symbol","abstract":[{"type":"text","text":"Head pose evaluation result"}],"title":"headPose","navigatorTitle":[{"text":"headPose","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headPose","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HeadPose","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"role":"symbol","kind":"symbol","type":"topic","title":"Wearables","navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"url":"\/documentation\/dotfacecore\/wearables"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyesExpression","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"EyesExpression","navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}],"abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"url":"\/documentation\/dotfacecore\/eyesexpression"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ExpressionQuery","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"ExpressionQuery","navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/expressionquery"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseQuery"}],"role":"symbol","kind":"symbol","type":"topic","title":"HeadPoseQuery","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/headposequery"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseAttribute"}],"role":"symbol","kind":"symbol","type":"topic","title":"HeadPoseAttribute","navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}],"abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"url":"\/documentation\/dotfacecore\/headposeattribute"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WearablesQuery"}],"role":"symbol","kind":"symbol","type":"topic","title":"WearablesQuery","navigatorTitle":[{"text":"WearablesQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/wearablesquery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/imageQuality":{"title":"imageQuality","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facequality\/imagequality","abstract":[{"text":"Face image quality evaluation result.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageQuality"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/imageQuality","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","kind":"typeIdentifier","text":"FaceImageQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/description":{"url":"\/documentation\/dotfacecore\/facequality\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/description","type":"topic","title":"description","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImageQuality"}],"role":"symbol","kind":"symbol","type":"topic","title":"FaceImageQuality","navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceimagequality"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"title":"FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceattribute","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"role":"symbol","kind":"symbol","type":"topic","title":"FaceQuality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"url":"\/documentation\/dotfacecore\/facequality"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Expression"}],"role":"symbol","kind":"symbol","type":"topic","title":"Expression","navigatorTitle":[{"kind":"identifier","text":"Expression"}],"abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"url":"\/documentation\/dotfacecore\/expression"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/wearables":{"url":"\/documentation\/dotfacecore\/facequality\/wearables","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/wearables","kind":"symbol","abstract":[{"type":"text","text":"Wearables evaluation result."}],"title":"wearables","navigatorTitle":[{"kind":"identifier","text":"wearables"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wearables","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables","text":"Wearables","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/init(imageQuality:headPose:wearables:expression:)":{"url":"\/documentation\/dotfacecore\/facequality\/init(imagequality:headpose:wearables:expression:)","title":"init(imageQuality:headPose:wearables:expression:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/init(imageQuality:headPose:wearables:expression:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","text":"FaceImageQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"headPose"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose","kind":"typeIdentifier","text":"HeadPose"},{"text":", ","kind":"text"},{"text":"wearables","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Wearables","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables"},{"text":", ","kind":"text"},{"text":"expression","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Expression","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpression","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithImageQuality:headPose:wearables:expression:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTFFaceQuality","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]},{"value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/headPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/imageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/wearables"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/init(imageQuality:headPose:wearables:expression:)"]}]},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Face evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFFaceQuality"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]}},{"value":"expression","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1expression\/title"},{"op":"replace","value":[{"kind":"identifier","text":"expression"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1expression\/fragments"},{"value":"DOTFFaceQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGlasses"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments"},{"value":"DOTFFaceImageQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","value":"DOTFEyesExpressionQuery"},{"value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","value":"DOTFHeadPose"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1headPose\/title","op":"replace","value":"headPose"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1headPose\/fragments","op":"replace","value":[{"text":"headPose","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","value":"DOTFWearables"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","op":"replace"},{"value":"DOTFEyesExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace"},{"value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments"},{"value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace","value":"DOTFHeadPoseQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"op":"replace"},{"value":"DOTFHeadPoseAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1imageQuality\/title","value":"imageQuality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1imageQuality\/fragments","op":"replace","value":[{"text":"imageQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1description\/title","value":"description","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1description\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","value":"DOTFFaceImageQuality","op":"replace"},{"value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"op":"replace","value":"DOTFFaceQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"value":[{"kind":"identifier","text":"DOTFExpression"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","op":"replace"},{"value":"wearables","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1wearables\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1wearables\/fragments","value":[{"text":"wearables","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1init(imageQuality:headPose:wearables:expression:)\/title","value":"initWithImageQuality:headPose:wearables:expression:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithImageQuality:headPose:wearables:expression:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1init(imageQuality:headPose:wearables:expression:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}