{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimagequality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimagequality"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"kind":"symbol","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"title":"Face evaluation"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQuality"}],"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","title":"FaceImageQuality"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/backgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/brightness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/contrast","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/shadow","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/sharpness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/specularity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/uniqueIntensityLevels"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFFaceImageQuality) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/uniqueIntensityLevels":{"role":"symbol","kind":"symbol","title":"uniqueIntensityLevels","type":"topic","abstract":[{"text":"Face image unique intensity levels.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/uniqueIntensityLevels","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uniqueIntensityLevels"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"uniqueIntensityLevels"}],"url":"\/documentation\/dotfacecore\/faceimagequality\/uniqueintensitylevels"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotfacecore\/faceimagequality\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/description","title":"description","type":"topic"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"kind":"symbol","abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/expressionquery","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ExpressionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}],"title":"ExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"kind":"symbol","abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"url":"\/documentation\/dotfacecore\/eyesexpression","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpression"}],"navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}],"title":"EyesExpression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"abstract":[{"text":"Eyes expression query specifies which eye expression face attributes should be evaluated.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/eyesexpressionquery","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyesExpressionQuery","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"title":"EyesExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)":{"title":"init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)","abstract":[],"url":"\/documentation\/dotfacecore\/faceimagequality\/init(sharpness:brightness:contrast:uniqueintensitylevels:shadow:specularity:backgrounduniformity:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"?, "},{"text":"contrast","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"uniqueIntensityLevels","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"shadow","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"specularity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)","navigatorTitle":[{"text":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"title":"Glasses","abstract":[{"type":"text","text":"Face attribute for the glasses."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","url":"\/documentation\/dotfacecore\/glasses","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Glasses","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Glasses","kind":"identifier"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"kind":"symbol","title":"FaceAspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","url":"\/documentation\/dotfacecore\/faceaspects","type":"topic","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"title":"HeadPoseQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseQuery"}],"url":"\/documentation\/dotfacecore\/headposequery","navigatorTitle":[{"kind":"identifier","text":"HeadPoseQuery"}],"role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/brightness":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"brightness","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotfacecore\/faceimagequality\/brightness","navigatorTitle":[{"text":"brightness","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Face image brightness.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/brightness","title":"brightness","type":"topic"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/specularity":{"kind":"symbol","url":"\/documentation\/dotfacecore\/faceimagequality\/specularity","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"specularity","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?","kind":"text"}],"abstract":[{"text":"Face image specularity.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/specularity","navigatorTitle":[{"kind":"identifier","text":"specularity"}],"role":"symbol","title":"specularity"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"kind":"symbol","abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"url":"\/documentation\/dotfacecore\/expression","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Expression","kind":"identifier"}],"navigatorTitle":[{"text":"Expression","kind":"identifier"}],"title":"Expression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/wearables","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"title":"Wearables","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/sharpness":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sharpness"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"sharpness","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/sharpness","url":"\/documentation\/dotfacecore\/faceimagequality\/sharpness","abstract":[{"text":"Face image sharpness.","type":"text"}],"kind":"symbol","role":"symbol","title":"sharpness"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"kind":"symbol","title":"FaceAttribute","type":"topic","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute","role":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"kind":"symbol","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"url":"\/documentation\/dotfacecore\/facequality","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"title":"FaceQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/backgroundUniformity":{"abstract":[{"text":"Face image background uniformity.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceimagequality\/backgrounduniformity","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/backgroundUniformity","kind":"symbol","role":"symbol","title":"backgroundUniformity","navigatorTitle":[{"kind":"identifier","text":"backgroundUniformity"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundUniformity"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/shadow":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadow"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotfacecore\/faceimagequality\/shadow","navigatorTitle":[{"kind":"identifier","text":"shadow"}],"kind":"symbol","abstract":[{"text":"Face image shadow.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/shadow","title":"shadow","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/wearablesquery","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WearablesQuery","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"title":"WearablesQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/contrast":{"url":"\/documentation\/dotfacecore\/faceimagequality\/contrast","title":"contrast","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contrast"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier","text":"FaceAttribute"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Face image contrast."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/contrast","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"contrast","kind":"identifier"}]},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"kind":"symbol","abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceimagequality","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQuality"}],"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"title":"FaceImageQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"kind":"symbol","abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/facequalityquery","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceQualityQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"title":"FaceQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.11.0"}],"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","title":"HeadPose","url":"\/documentation\/dotfacecore\/headpose","navigatorTitle":[{"kind":"identifier","text":"HeadPose"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImageQualityQuery"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"role":"symbol","type":"topic","kind":"symbol","title":"FaceImageQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","title":"HeadPoseAttribute","navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseAttribute"}],"kind":"symbol","abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTFFaceImageQuality","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}]},{"op":"replace","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/backgroundUniformity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/brightness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/contrast","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/shadow","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/sharpness","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/specularity","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/uniqueIntensityLevels"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true,"title":"Face evaluation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFFaceImageQuality"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1uniqueIntensityLevels\/title","value":"uniqueIntensityLevels"},{"value":[{"kind":"identifier","text":"uniqueIntensityLevels"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1uniqueIntensityLevels\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1description\/fragments","op":"replace"},{"value":"DOTFExpressionQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","value":"DOTFEyesExpression","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace","value":[{"text":"DOTFEyesExpression","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","value":"DOTFEyesExpressionQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)\/title","op":"replace","value":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","op":"replace","value":"DOTFGlasses"},{"value":[{"text":"DOTFGlasses","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace","value":"DOTFFaceAspects"},{"value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"},{"op":"replace","value":"DOTFHeadPoseQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1brightness\/title","value":"brightness"},{"value":[{"kind":"identifier","text":"brightness"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1brightness\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1specularity\/title","value":"specularity"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1specularity\/fragments","op":"replace","value":[{"text":"specularity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFExpression"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","op":"replace","value":"DOTFWearables"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","op":"replace","value":[{"text":"DOTFWearables","kind":"identifier"}]},{"op":"replace","value":"sharpness","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1sharpness\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1sharpness\/fragments","value":[{"kind":"identifier","text":"sharpness"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute","op":"replace"},{"op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace"},{"op":"replace","value":"backgroundUniformity","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1backgroundUniformity\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1backgroundUniformity\/fragments","op":"replace","value":[{"text":"backgroundUniformity","kind":"identifier"}]},{"value":"shadow","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1shadow\/title"},{"value":[{"kind":"identifier","text":"shadow"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1shadow\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"op":"replace"},{"value":"contrast","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1contrast\/title"},{"value":[{"kind":"identifier","text":"contrast"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1contrast\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","value":"DOTFFaceImageQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","op":"replace","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","value":"DOTFHeadPose","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"text":"DOTFHeadPose","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","op":"replace","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}]}]}]}