{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"seeAlsoSections":[{"title":"Detected face evaluation","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery"],"generated":true}],"variants":[{"paths":["\/documentation\/dotfacecore\/glasses"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/glasses"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"},"sections":[],"abstract":[{"type":"text","text":"Face attribute for the glasses."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/init(score:preconditionsMet:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/preconditionsMet","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/score"],"title":"Instance Properties"}],"metadata":{"title":"Glasses","roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}],"symbolKind":"class","role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"Glasses","kind":"identifier"}]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFGlasses) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Glasses"}]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses/score":{"title":"score","navigatorTitle":[{"text":"score","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/glasses\/score","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"score","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","abstract":[{"type":"text","text":"Face attribute score."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/score","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpression":{"title":"EyesExpression","navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}],"url":"\/documentation\/dotfacecore\/eyesexpression","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyesExpression","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","role":"symbol"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses/description":{"title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/glasses\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/description","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpressionQuery":{"url":"\/documentation\/dotfacecore\/eyesexpressionquery","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","role":"symbol","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}],"type":"topic","title":"EyesExpressionQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyesExpressionQuery","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery":{"navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/facequalityquery","role":"symbol","title":"FaceQualityQuery","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQualityQuery"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression":{"title":"Expression","navigatorTitle":[{"text":"Expression","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/expression","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Expression","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose":{"type":"topic","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headpose","kind":"symbol","title":"HeadPose","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadPose","kind":"identifier"}],"abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"title":"DotFaceCore","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAttribute":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}],"title":"FaceAttribute","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"type":"topic","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/faceattribute","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQuality":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImageQuality"}],"abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"title":"FaceImageQuality","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","url":"\/documentation\/dotfacecore\/faceimagequality","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute":{"title":"HeadPoseAttribute","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headposeattribute","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseAttribute"}],"kind":"symbol","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ExpressionQuery":{"url":"\/documentation\/dotfacecore\/expressionquery","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","role":"symbol","abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"type":"topic","title":"ExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ExpressionQuery","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses":{"title":"Glasses","navigatorTitle":[{"text":"Glasses","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/glasses","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Glasses","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Face attribute for the glasses."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Wearables":{"title":"Wearables","navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/wearables","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"kind":"symbol","abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses/init(score:preconditionsMet:)":{"title":"init(score:preconditionsMet:)","navigatorTitle":[{"text":"initWithScore:preconditionsMet:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/glasses\/init(score:preconditionsmet:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"score"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"preconditionsMet","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/init(score:preconditionsMet:)","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WearablesQuery":{"title":"WearablesQuery","navigatorTitle":[{"text":"WearablesQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/wearablesquery","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WearablesQuery","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQualityQuery":{"navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","role":"symbol","title":"FaceImageQualityQuery","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseQuery":{"title":"HeadPoseQuery","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headposequery","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseQuery","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","role":"symbol"},"doc://com.innovatrics.dot.face.core/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses/preconditionsMet":{"title":"preconditionsMet","navigatorTitle":[{"text":"preconditionsMet","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/glasses\/preconditionsmet","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preconditionsMet"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[{"text":"This is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/preconditionsMet","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAspects":{"title":"FaceAspects","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceaspects","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQuality":{"title":"FaceQuality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facequality","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","role":"symbol"},"doc://com.innovatrics.dot.face.core/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGlasses"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTFGlasses","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGlasses"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/preconditionsMet","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/score"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses\/init(score:preconditionsMet:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Detected face evaluation","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery"]}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFGlasses","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1score\/title","op":"replace","value":"score"},{"value":[{"kind":"identifier","text":"score"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1score\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace","value":"DOTFEyesExpression"},{"value":[{"kind":"identifier","text":"DOTFEyesExpression"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1description\/title","value":"description","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"value":"DOTFEyesExpressionQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"kind":"identifier","text":"DOTFExpression"}],"op":"replace"},{"value":"DOTFHeadPose","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFHeadPose"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace"},{"value":"DOTFFaceImageQuality","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute","op":"replace"},{"value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","op":"replace","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/title","value":"DOTFWearables","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/fragments","value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1init(score:preconditionsMet:)\/title","value":"initWithScore:preconditionsMet:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1init(score:preconditionsMet:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithScore:preconditionsMet:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]},{"value":"DOTFHeadPoseQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1preconditionsMet\/title","value":"preconditionsMet"},{"value":[{"text":"preconditionsMet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses~1preconditionsMet\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/fragments"}]}]}