{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFHeadPose) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/init(roll:yaw:pitch:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/pitch","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/roll","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/yaw"],"title":"Instance Properties"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/headpose"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headpose"]}],"seeAlsoSections":[{"title":"Detected face evaluation","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"]}],"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"title":"HeadPose","externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPose"}],"symbolKind":"class","roleHeading":"Class","role":"symbol"},"abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose/description":{"role":"symbol","url":"\/documentation\/dotfacecore\/headpose\/description","title":"description","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQualityQuery":{"url":"\/documentation\/dotfacecore\/faceimagequalityquery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"title":"FaceImageQualityQuery","abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseQuery":{"kind":"symbol","abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseQuery","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"title":"HeadPoseQuery","type":"topic","url":"\/documentation\/dotfacecore\/headposequery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose/pitch":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/pitch","url":"\/documentation\/dotfacecore\/headpose\/pitch","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"text":"HeadPoseAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Head pose pitch."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"pitch"}],"title":"pitch"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression":{"abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Expression","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Expression","kind":"identifier"}],"title":"Expression","type":"topic","url":"\/documentation\/dotfacecore\/expression","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WearablesQuery":{"kind":"symbol","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WearablesQuery","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"title":"WearablesQuery","type":"topic","url":"\/documentation\/dotfacecore\/wearablesquery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose/init(roll:yaw:pitch:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithRoll:yaw:pitch:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/init(roll:yaw:pitch:)","url":"\/documentation\/dotfacecore\/headpose\/init(roll:yaw:pitch:)","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"yaw"},{"kind":"text","text":": "},{"text":"HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"pitch"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(roll:yaw:pitch:)","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpressionQuery":{"kind":"symbol","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EyesExpressionQuery","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"title":"EyesExpressionQuery","type":"topic","url":"\/documentation\/dotfacecore\/eyesexpressionquery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery":{"abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"title":"FaceQualityQuery","type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose/roll":{"navigatorTitle":[{"kind":"identifier","text":"roll"}],"title":"roll","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/roll","type":"topic","url":"\/documentation\/dotfacecore\/headpose\/roll","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"roll"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Head pose roll.","type":"text"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.3.0"}],"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Wearables":{"kind":"symbol","abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Wearables","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"title":"Wearables","type":"topic","url":"\/documentation\/dotfacecore\/wearables","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose":{"navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","url":"\/documentation\/dotfacecore\/headpose","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPose"}],"title":"HeadPose","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute":{"abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}],"title":"HeadPoseAttribute","type":"topic","url":"\/documentation\/dotfacecore\/headposeattribute","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpression":{"kind":"symbol","abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"title":"EyesExpression","type":"topic","url":"\/documentation\/dotfacecore\/eyesexpression","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAttribute":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"url":"\/documentation\/dotfacecore\/faceattribute","type":"topic","role":"symbol","title":"FaceAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAttribute"}],"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses":{"type":"topic","title":"Glasses","navigatorTitle":[{"text":"Glasses","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Face attribute for the glasses."}],"url":"\/documentation\/dotfacecore\/glasses","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Glasses"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAspects":{"abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"title":"FaceAspects","type":"topic","url":"\/documentation\/dotfacecore\/faceaspects","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ExpressionQuery":{"abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExpressionQuery","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"title":"ExpressionQuery","type":"topic","url":"\/documentation\/dotfacecore\/expressionquery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQuality":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"url":"\/documentation\/dotfacecore\/faceimagequality","type":"topic","role":"symbol","title":"FaceImageQuality","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQuality":{"navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","kind":"symbol","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"title":"FaceQuality","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose/yaw":{"navigatorTitle":[{"text":"yaw","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/yaw","type":"topic","url":"\/documentation\/dotfacecore\/headpose\/yaw","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"yaw"},{"kind":"text","text":": "},{"text":"HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Head pose yaw."}],"title":"yaw"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFHeadPose","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"DOTFHeadPose","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFHeadPose"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/pitch","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/roll","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/yaw"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose\/init(roll:yaw:pitch:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"]}]},{"op":"replace","value":[{"generated":true,"title":"Detected face evaluation","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"]}],"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTFHeadPose","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/title","value":"DOTFHeadPoseQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1pitch\/title","value":"pitch"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1pitch\/fragments","value":[{"kind":"identifier","text":"pitch"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/title","op":"replace","value":"DOTFExpression"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"text":"DOTFExpression","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1init(roll:yaw:pitch:)\/title","value":"initWithRoll:yaw:pitch:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithRoll:yaw:pitch:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1init(roll:yaw:pitch:)\/fragments"},{"value":"DOTFEyesExpressionQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"value":"roll","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1roll\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1roll\/fragments","value":[{"kind":"identifier","text":"roll"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/title","value":"DOTFWearables"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFWearables"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/fragments"},{"value":"DOTFHeadPose","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"text":"DOTFHeadPose","kind":"identifier"}],"op":"replace"},{"value":"DOTFHeadPoseAttribute","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","op":"replace"},{"value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace","value":"DOTFEyesExpression"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace","value":[{"text":"DOTFEyesExpression","kind":"identifier"}]},{"value":"DOTFFaceAttribute","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace"},{"value":"DOTFFaceAspects","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace"},{"op":"replace","value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/title","op":"replace","value":"DOTFFaceImageQuality"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace","value":[{"text":"DOTFFaceQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1yaw\/title","value":"yaw"},{"op":"replace","value":[{"text":"yaw","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose~1yaw\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}