{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/init(angle:preconditionsMet:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/angle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/preconditionsMet"]}],"seeAlsoSections":[{"title":"Face evaluation","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","title":"HeadPoseAttribute","externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}]},"abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFHeadPoseAttribute) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/headposeattribute"]},{"paths":["\/documentation\/dotfacecore\/headposeattribute"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses":{"title":"Glasses","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Glasses"}],"navigatorTitle":[{"text":"Glasses","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Face attribute for the glasses."}],"url":"\/documentation\/dotfacecore\/glasses"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAttribute":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","title":"FaceAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceattribute","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}]},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery":{"title":"FaceQualityQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/facequalityquery"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpression":{"title":"EyesExpression","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}],"navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"url":"\/documentation\/dotfacecore\/eyesexpression"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute/angle":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"angle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"title":"angle","abstract":[{"type":"text","text":"Head pose attribute angle."}],"type":"topic","url":"\/documentation\/dotfacecore\/headposeattribute\/angle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"angle"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/angle","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute/description":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/description","url":"\/documentation\/dotfacecore\/headposeattribute\/description","role":"symbol","title":"description","abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute":{"title":"HeadPoseAttribute","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}],"url":"\/documentation\/dotfacecore\/headposeattribute"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute/init(angle:preconditionsMet:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/init(angle:preconditionsMet:)","title":"init(angle:preconditionsMet:)","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithAngle:preconditionsMet:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"angle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"preconditionsMet","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/headposeattribute\/init(angle:preconditionsmet:)","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQuality":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","title":"FaceQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facequality","abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ExpressionQuery":{"title":"ExpressionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExpressionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/expressionquery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQuality":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","title":"FaceImageQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagequality","abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Wearables":{"title":"Wearables","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"url":"\/documentation\/dotfacecore\/wearables"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WearablesQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","title":"WearablesQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WearablesQuery","kind":"identifier"}],"navigatorTitle":[{"text":"WearablesQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/wearablesquery","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression":{"title":"Expression","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Expression","kind":"identifier"}],"navigatorTitle":[{"text":"Expression","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"url":"\/documentation\/dotfacecore\/expression"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpressionQuery":{"title":"EyesExpressionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpressionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Eyes expression query specifies which eye expression face attributes should be evaluated.","type":"text"}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute/preconditionsMet":{"url":"\/documentation\/dotfacecore\/headposeattribute\/preconditionsmet","role":"symbol","title":"preconditionsMet","abstract":[{"type":"text","text":"This is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" when the preconditions for the evaluation of this head pose attribute were met. If the preconditions were not met, this is "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"preconditionsMet","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"preconditionsMet","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/preconditionsMet","type":"topic"},"doc://com.innovatrics.dot.face.core/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQualityQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","title":"FaceImageQualityQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery","abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}]},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","title":"HeadPose","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}],"navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/headpose","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAspects":{"title":"FaceAspects","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceaspects"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","title":"HeadPoseQuery","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadPoseQuery","kind":"identifier"}],"navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/headposequery","abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFHeadPoseAttribute"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/angle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/preconditionsMet"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/init(angle:preconditionsMet:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"],"title":"Face evaluation"}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFHeadPoseAttribute","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery"},{"value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace"},{"value":"DOTFEyesExpression","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/fragments","value":[{"text":"DOTFEyesExpression","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1angle\/title","op":"replace","value":"angle"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1angle\/fragments","value":[{"kind":"identifier","text":"angle"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1description\/title","value":"description","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1init(angle:preconditionsMet:)\/title","value":"initWithAngle:preconditionsMet:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAngle:preconditionsMet:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1init(angle:preconditionsMet:)\/fragments","op":"replace"},{"value":"DOTFFaceQuality","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/title"},{"value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/fragments"},{"value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"op":"replace","value":"DOTFFaceImageQuality","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","op":"replace"},{"value":"DOTFWearables","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/fragments","value":[{"text":"DOTFWearables","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/fragments","op":"replace","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"kind":"identifier","text":"DOTFExpression"}]},{"value":"DOTFEyesExpressionQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace"},{"value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","op":"replace"},{"op":"replace","value":"preconditionsMet","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1preconditionsMet\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1preconditionsMet\/fragments","value":[{"kind":"identifier","text":"preconditionsMet"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments"},{"value":"DOTFHeadPose","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"text":"DOTFHeadPose","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/fragments","value":[{"text":"DOTFFaceAspects","kind":"identifier"}]},{"value":"DOTFHeadPoseQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}