{"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init(evaluateRoll:evaluateYaw:evaluatePitch:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluatePitch","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateRoll","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateYaw"],"title":"Instance Properties","anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/headposequery"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/headposequery"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"title":"Face evaluation","anchor":"Face-evaluation"}],"abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseQuery"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"HeadPoseQuery"}],"title":"HeadPoseQuery","role":"symbol","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFHeadPoseQuery) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseQuery"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"title":"HeadPoseQuery","url":"\/documentation\/dotfacecore\/headposequery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HeadPoseQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","role":"symbol","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/evaluateYaw":{"url":"\/documentation\/dotfacecore\/headposequery\/evaluateyaw","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateYaw"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Yaw evaluation flag."}],"navigatorTitle":[{"kind":"identifier","text":"evaluateYaw"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateYaw","title":"evaluateYaw","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/evaluatePitch":{"url":"\/documentation\/dotfacecore\/headposequery\/evaluatepitch","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluatePitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Pitch evaluation flag."}],"navigatorTitle":[{"kind":"identifier","text":"evaluatePitch"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluatePitch","title":"evaluatePitch","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/evaluateRoll":{"url":"\/documentation\/dotfacecore\/headposequery\/evaluateroll","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"evaluateRoll","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Roll evaluation flag."}],"navigatorTitle":[{"kind":"identifier","text":"evaluateRoll"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateRoll","title":"evaluateRoll","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","url":"\/documentation\/dotfacecore\/eyesexpressionquery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"abstract":[{"text":"Eyes expression query specifies which eye expression face attributes should be evaluated.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}],"title":"EyesExpressionQuery"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/init()":{"url":"\/documentation\/dotfacecore\/headposequery\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init()","title":"init()","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/init(evaluateRoll:evaluateYaw:evaluatePitch:)":{"url":"\/documentation\/dotfacecore\/headposequery\/init(evaluateroll:evaluateyaw:evaluatepitch:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"evaluateRoll"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"evaluateYaw"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"evaluatePitch","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init(evaluateRoll:evaluateYaw:evaluatePitch:)","title":"init(evaluateRoll:evaluateYaw:evaluatePitch:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","url":"\/documentation\/dotfacecore\/faceimagequalityquery","navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"type":"topic","title":"FaceImageQualityQuery","abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"title":"Glasses","url":"\/documentation\/dotfacecore\/glasses","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"abstract":[{"type":"text","text":"Face attribute for the glasses."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"title":"FaceAspects","url":"\/documentation\/dotfacecore\/faceaspects","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"title":"HeadPose","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"url":"\/documentation\/dotfacecore\/headpose","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPose"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","url":"\/documentation\/dotfacecore\/faceimagequality","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"type":"topic","title":"FaceImageQuality","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImageQuality"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","url":"\/documentation\/dotfacecore\/eyesexpression","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}],"abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}],"title":"EyesExpression"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","url":"\/documentation\/dotfacecore\/wearablesquery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WearablesQuery"}],"title":"WearablesQuery"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"url":"\/documentation\/dotfacecore\/faceattribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","title":"FaceAttribute","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"title":"FaceQualityQuery","url":"\/documentation\/dotfacecore\/facequalityquery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","role":"symbol","navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"type":"topic","title":"HeadPoseAttribute","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"title":"Wearables","url":"\/documentation\/dotfacecore\/wearables","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"kind":"symbol","abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQuality"}],"title":"FaceQuality"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"url":"\/documentation\/dotfacecore\/expression","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Expression","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"navigatorTitle":[{"text":"Expression","kind":"identifier"}],"title":"Expression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"url":"\/documentation\/dotfacecore\/expressionquery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}],"kind":"symbol","type":"topic","abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","title":"ExpressionQuery","role":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFHeadPoseQuery"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluatePitch","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateRoll","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateYaw"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init(evaluateRoll:evaluateYaw:evaluatePitch:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"title":"Face evaluation","anchor":"Face-evaluation"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFHeadPoseQuery"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace","value":"DOTFHeadPoseQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}]},{"value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/navigatorTitle","op":"replace"},{"value":"evaluateYaw","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluateYaw\/title","op":"replace"},{"value":[{"kind":"identifier","text":"evaluateYaw"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluateYaw\/fragments","op":"replace"},{"value":"evaluatePitch","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluatePitch\/title","op":"replace"},{"value":[{"kind":"identifier","text":"evaluatePitch"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluatePitch\/fragments","op":"replace"},{"value":"evaluateRoll","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluateRoll\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluateRoll\/fragments","op":"replace","value":[{"kind":"identifier","text":"evaluateRoll"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace","value":"DOTFEyesExpressionQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init(evaluateRoll:evaluateYaw:evaluatePitch:)\/title","op":"replace","value":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init(evaluateRoll:evaluateYaw:evaluatePitch:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","op":"replace","value":"DOTFFaceImageQualityQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","op":"replace","value":"DOTFGlasses"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFGlasses"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFGlasses"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace","value":"DOTFFaceAspects"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAspects"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","op":"replace","value":"DOTFHeadPose"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","op":"replace","value":"DOTFFaceImageQuality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace","value":"DOTFEyesExpression"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpression"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpression"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","op":"replace","value":"DOTFWearablesQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","op":"replace","value":"DOTFFaceAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","op":"replace","value":"DOTFFaceQualityQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","op":"replace","value":"DOTFHeadPoseAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","op":"replace","value":"DOTFWearables"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFWearables"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFWearables"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","op":"replace","value":"DOTFFaceQuality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","op":"replace","value":"DOTFExpression"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFExpression"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFExpression"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","op":"replace","value":"DOTFExpressionQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}