{"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/init(format:bytes:size:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/bytes","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/format","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/size"],"title":"Instance Properties","anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTImage","symbolKind":"class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"modules":[{"name":"DotFaceCore"}],"title":"Image"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/dotfacecore\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"],"anchor":"Converting-images"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Image/description":{"abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/description","type":"topic","url":"\/documentation\/dotfacecore\/image\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","kind":"symbol","url":"\/documentation\/dotfacecore\/image","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","url":"\/documentation\/dotfacecore\/cgimagefactory","title":"CGImageFactory"},"doc://DotFaceCore/documentation/DotFaceCore/Image/init(format:bytes:size:)":{"title":"init(format:bytes:size:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat"},{"kind":"text","text":", "},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/init(format:bytes:size:)","kind":"symbol","url":"\/documentation\/dotfacecore\/image\/init(format:bytes:size:)","role":"symbol"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/Image/bytes":{"title":"bytes","abstract":[{"text":"Raw image data.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/bytes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"url":"\/documentation\/dotfacecore\/image\/bytes","navigatorTitle":[{"text":"bytes","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory":{"title":"CIImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/ciimagefactory","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/Image/size":{"title":"size","kind":"symbol","abstract":[{"type":"text","text":"Image size."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/size","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"url":"\/documentation\/dotfacecore\/image\/size","navigatorTitle":[{"kind":"identifier","text":"size"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory","url":"\/documentation\/dotfacecore\/imagefactory","title":"ImageFactory"},"doc://DotFaceCore/documentation/DotFaceCore/Image/format":{"title":"format","abstract":[{"text":"Format of the stored image","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/format","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/image\/format","navigatorTitle":[{"text":"format","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/bytes","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/format","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/size"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"],"anchor":"Converting-images","title":"Converting images","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1bytes\/title","value":"bytes"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1format\/title","value":"format"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image~1format\/fragments","value":[{"kind":"identifier","text":"format"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}