{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageSize) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"ImageSize","symbolKind":"class","role":"symbol","roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}]},"sections":[],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/init(width:height:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/cgSize","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/height","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/longerSide","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/shorterSide","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/width"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculatePixelCount()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/from(cgSize:)"]}],"abstract":[{"type":"text","text":"Image size in pixels."}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imagesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/imagesize"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/calculatePixelCount()":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculatePixelCount()","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"title":"calculatePixelCount()","url":"\/documentation\/dotfacecore\/imagesize\/calculatepixelcount()","role":"symbol","navigatorTitle":[{"text":"calculatePixelCount","kind":"identifier"}]},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/width":{"kind":"symbol","type":"topic","abstract":[{"text":"Image width in pixels.","type":"text"}],"url":"\/documentation\/dotfacecore\/imagesize\/width","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/width","navigatorTitle":[{"text":"width","kind":"identifier"}],"role":"symbol","title":"width"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/hash":{"title":"hash","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/hash","url":"\/documentation\/dotfacecore\/imagesize\/hash"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/description","type":"topic","url":"\/documentation\/dotfacecore\/imagesize\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/imagesize","abstract":[{"type":"text","text":"Image size in pixels."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"role":"symbol","title":"ImageSize"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/shorterSide":{"title":"shorterSide","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/shorterSide","url":"\/documentation\/dotfacecore\/imagesize\/shorterside"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/isEqual(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/imagesize\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/isEqual(_:)","title":"isEqual(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/init(width:height:)":{"title":"init(width:height:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"width","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithWidth:height:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/init(width:height:)","url":"\/documentation\/dotfacecore\/imagesize\/init(width:height:)"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/longerSide":{"title":"longerSide","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"longerSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"longerSide","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/longerSide","url":"\/documentation\/dotfacecore\/imagesize\/longerside"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/from(cgSize:)":{"title":"from(cgSize:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"navigatorTitle":[{"kind":"identifier","text":"fromCgSize:"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/from(cgSize:)","url":"\/documentation\/dotfacecore\/imagesize\/from(cgsize:)"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/height":{"title":"height","kind":"symbol","abstract":[{"type":"text","text":"Image height in pixels."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/height","url":"\/documentation\/dotfacecore\/imagesize\/height"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/calculateWidthToHeightRatio()":{"title":"calculateWidthToHeightRatio()","kind":"symbol","abstract":[{"type":"text","text":"Calculate width to height ratio."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculateWidthToHeightRatio()","url":"\/documentation\/dotfacecore\/imagesize\/calculatewidthtoheightratio()"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/cgSize":{"title":"cgSize","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"navigatorTitle":[{"kind":"identifier","text":"cgSize"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/cgSize","url":"\/documentation\/dotfacecore\/imagesize\/cgsize"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTImageSize","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/cgSize","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/height","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/longerSide","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/shorterSide","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/width"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculatePixelCount()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/init(width:height:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/from(cgSize:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTImageSize"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1calculatePixelCount()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"}]},{"op":"replace","value":"width","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1width\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1width\/fragments","value":[{"kind":"identifier","text":"width"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1hash\/title","value":"hash"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1hash\/fragments","op":"replace"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1description\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1shorterSide\/title","value":"shorterSide","op":"replace"},{"op":"replace","value":[{"text":"shorterSide","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1shorterSide\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1init(width:height:)\/title","value":"initWithWidth:height:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithWidth:height:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1init(width:height:)\/fragments"},{"value":"longerSide","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1longerSide\/title","op":"replace"},{"op":"replace","value":[{"text":"longerSide","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1longerSide\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1from(cgSize:)\/title","value":"fromCgSize:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1from(cgSize:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"fromCgSize:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1height\/title","value":"height","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1height\/fragments","value":[{"text":"height","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1calculateWidthToHeightRatio()\/title","op":"replace","value":"calculateWidthToHeightRatio"},{"value":[{"kind":"text","text":"- "},{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1calculateWidthToHeightRatio()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1cgSize\/title","value":"cgSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1cgSize\/fragments","value":[{"text":"cgSize","kind":"identifier"}]}]}]}