{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTIntervalDouble) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}]}]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/init(min:max:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/hash","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/max","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/min"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/isEqual(_:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/Error"],"title":"Enumerations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/intervaldouble"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/intervaldouble"]}],"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","symbolKind":"class","modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","title":"IntervalDouble","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}]},"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble/Error":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"abstract":[],"title":"IntervalDouble.Error","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/Error","url":"\/documentation\/dotfacecore\/intervaldouble\/error"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble/description":{"url":"\/documentation\/dotfacecore\/intervaldouble\/description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[],"title":"description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/description"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","title":"IntervalDouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble/min":{"kind":"symbol","url":"\/documentation\/dotfacecore\/intervaldouble\/min","navigatorTitle":[{"kind":"identifier","text":"min"}],"type":"topic","abstract":[{"text":"Minimal interval value.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/min","role":"symbol","title":"min","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"min","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/intervaldouble\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/hash"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/isEqual(_:)","kind":"symbol","url":"\/documentation\/dotfacecore\/intervaldouble\/isequal(_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble/init(min:max:)":{"abstract":[],"url":"\/documentation\/dotfacecore\/intervaldouble\/init(min:max:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/init(min:max:)","title":"init(min:max:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:error:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"text":"max","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble/max":{"url":"\/documentation\/dotfacecore\/intervaldouble\/max","role":"symbol","navigatorTitle":[{"text":"max","kind":"identifier"}],"abstract":[{"text":"Maximal interval value.","type":"text"}],"kind":"symbol","title":"max","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/max"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTIntervalDouble","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/hash","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/max","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/min"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/init(min:max:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble\/isEqual(_:)"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTIntervalDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1description\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1min\/title","value":"min","op":"replace"},{"value":[{"text":"min","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1min\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1hash\/title","value":"hash","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"value":"initWithMin:max:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1init(min:max:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:error:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1init(min:max:)\/fragments"},{"value":"max","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1max\/title"},{"value":[{"text":"max","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble~1max\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}