{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/init(document:face:faceLite:nfc:palm:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/document","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/faceLite","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/nfc","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/palm"],"generated":true,"anchor":"Instance-Properties"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"abstract":[{"text":"Container for library configurations.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"title":"Libraries","externalID":"c:@M@DotCore@objc(cs)Libraries","roleHeading":"Class","symbolKind":"class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/libraries"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/libraries"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"abstract":[{"type":"text","text":"Container for library configurations."}],"title":"Libraries","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/libraries","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries","kind":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/document":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"document"}],"kind":"symbol","role":"symbol","title":"document","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/document","abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotfacecore\/libraries\/document"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/nfc":{"navigatorTitle":[{"kind":"identifier","text":"nfc"}],"abstract":[{"type":"text","text":"NFC library configuration."}],"title":"nfc","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/nfc","url":"\/documentation\/dotfacecore\/libraries\/nfc","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/init(document:face:faceLite:nfc:palm:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}],"url":"\/documentation\/dotfacecore\/libraries\/init(document:face:facelite:nfc:palm:)","abstract":[],"type":"topic","title":"init(document:face:faceLite:nfc:palm:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/init(document:face:faceLite:nfc:palm:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/palm":{"type":"topic","url":"\/documentation\/dotfacecore\/libraries\/palm","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/palm","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"text":"?","kind":"text"}],"kind":"symbol","title":"palm","role":"symbol","navigatorTitle":[{"text":"palm","kind":"identifier"}],"abstract":[{"text":"Palm library configuration.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/face":{"url":"\/documentation\/dotfacecore\/libraries\/face","title":"face","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Face library configuration."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"face","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/face"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries/faceLite":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"faceLite","url":"\/documentation\/dotfacecore\/libraries\/facelite","role":"symbol","type":"topic","navigatorTitle":[{"text":"faceLite","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Face Lite library configuration."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/faceLite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"Libraries"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Libraries","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/document","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/faceLite","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/nfc","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/palm"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries\/init(document:face:faceLite:nfc:palm:)"],"anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/title","value":"Libraries"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/fragments","op":"replace"},{"value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/navigatorTitle","op":"replace"},{"value":"document","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1document\/title","op":"replace"},{"value":[{"kind":"identifier","text":"document"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1document\/fragments","op":"replace"},{"value":"nfc","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1nfc\/title","op":"replace"},{"value":[{"text":"nfc","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1nfc\/fragments","op":"replace"},{"value":"initWithDocument:face:faceLite:nfc:palm:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1init(document:face:faceLite:nfc:palm:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1init(document:face:faceLite:nfc:palm:)\/fragments","op":"replace"},{"value":"palm","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1palm\/title","op":"replace"},{"value":[{"text":"palm","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1palm\/fragments","op":"replace"},{"value":"face","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1face\/title","op":"replace"},{"value":[{"text":"face","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1face\/fragments","op":"replace"},{"value":"faceLite","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1faceLite\/title","op":"replace"},{"value":[{"kind":"identifier","text":"faceLite"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries~1faceLite\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}