{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFLocalization","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"Localization","roleHeading":"Class"},"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/bundle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/localizationDictionary","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/useLocalizationDictionary"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFLocalization) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization"},"seeAlsoSections":[{"generated":true,"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Logger"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/localization"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/localization"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"title":"Conforms To","type":"conformsTo"}],"references":{"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Localization/bundle":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundle"},{"kind":"text","text":": "},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bundle"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/bundle","title":"bundle","url":"\/documentation\/dotfacecore\/localization\/bundle","abstract":[{"text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically ","type":"text"},{"code":"Bundle.main","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Localization":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/localization","title":"Localization","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}]},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Localization/localizationDictionary":{"navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"kind":"symbol","abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizationDictionary"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/localizationDictionary","title":"localizationDictionary","url":"\/documentation\/dotfacecore\/localization\/localizationdictionary","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"}],"title":"DotFaceLibrary","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library initialization."}],"url":"\/documentation\/dotfacecore\/dotfacelibrary"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.2.0","type":"text"}],"role":"collection","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Logger":{"title":"Logger","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Logger","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/logger","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Localization/useLocalizationDictionary":{"url":"\/documentation\/dotfacecore\/localization\/uselocalizationdictionary","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/useLocalizationDictionary","type":"topic","navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","title":"useLocalizationDictionary","abstract":[{"type":"text","text":"If you set this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizationDictionary"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLocalization"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLocalization"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLocalization"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/bundle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/localizationDictionary","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization\/useLocalizationDictionary"],"title":"Type Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"value":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Logger"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFLocalization"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}]}},{"value":"bundle","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization~1bundle\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization~1bundle\/fragments","op":"replace","value":[{"text":"bundle","kind":"identifier"}]},{"value":"DOTFLocalization","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization\/title","op":"replace"},{"value":[{"text":"DOTFLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization~1localizationDictionary\/title","value":"localizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization~1localizationDictionary\/fragments","value":[{"kind":"identifier","text":"localizationDictionary"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/title","op":"replace","value":"DotFaceLibrary"},{"value":[{"text":"DotFaceLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Logger\/title","value":"DOTFLogger","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLogger"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Logger\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization~1useLocalizationDictionary\/title","value":"useLocalizationDictionary","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization~1useLocalizationDictionary\/fragments","value":[{"kind":"identifier","text":"useLocalizationDictionary"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}