{"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization"],"generated":true,"title":"Global components"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLogger) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/logLevel"],"title":"Type Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/debug(_:file:function:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/error(_:file:function:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/info(_:file:function:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/warning(_:file:function:)"],"title":"Type Methods"}],"variants":[{"paths":["\/documentation\/dotfacecore\/logger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/logger"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger"},"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFLogger","role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"title":"Logger","roleHeading":"Class","modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/Logger/logLevel":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"kind":"text","text":": "},{"text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/logLevel","type":"topic","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/dotfacecore\/logger\/loglevel","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"title":"logLevel","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Logger/debug(_:file:function:)":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"debug:file:function:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/logger\/debug(_:file:function:)","title":"debug(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/debug(_:file:function:)"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/Localization":{"type":"topic","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"kind":"symbol","title":"Localization","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization","url":"\/documentation\/dotfacecore\/localization","role":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/Logger/error(_:file:function:)":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"error:file:function:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/logger\/error(_:file:function:)","title":"error(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/error(_:file:function:)"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrary","kind":"symbol","title":"DotFaceLibrary","role":"symbol","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library initialization."}]},"doc://DotFaceCore/documentation/DotFaceCore/Logger/warning(_:file:function:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"file"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","title":"warning(_:file:function:)","url":"\/documentation\/dotfacecore\/logger\/warning(_:file:function:)","navigatorTitle":[{"text":"warning:file:function:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/warning(_:file:function:)"},"doc://DotFaceCore/documentation/DotFaceCore/Logger":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"role":"symbol","url":"\/documentation\/dotfacecore\/logger","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"kind":"symbol","title":"Logger"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.8.0","type":"text"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/Logger/info(_:file:function:)":{"navigatorTitle":[{"text":"info:file:function:","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"title":"info(_:file:function:)","kind":"symbol","url":"\/documentation\/dotfacecore\/logger\/info(_:file:function:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/info(_:file:function:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"info","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLogger"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFLogger"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFLogger","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/logLevel"]},{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/debug(_:file:function:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/error(_:file:function:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/info(_:file:function:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/warning(_:file:function:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization"],"generated":true,"title":"Global components"}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFLogger","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1logLevel\/title","value":"logLevel"},{"value":[{"text":"logLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1logLevel\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1debug(_:file:function:)\/title","value":"debug:file:function:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"debug:file:function:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1debug(_:file:function:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/title","op":"replace","value":"DOTFLocalization"},{"op":"replace","value":[{"text":"DOTFLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1error(_:file:function:)\/title","value":"error:file:function:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"error:file:function:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1error(_:file:function:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary"},{"op":"replace","value":[{"text":"DotFaceLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1warning(_:file:function:)\/title","value":"warning:file:function:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1warning(_:file:function:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"warning:file:function:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger\/title","value":"DOTFLogger","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger\/fragments","value":[{"text":"DOTFLogger","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1info(_:file:function:)\/title","op":"replace","value":"info:file:function:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1info(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"info:file:function:","kind":"identifier"}],"op":"replace"}]}]}