{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessresult"]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessresult"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"]]},"abstract":[{"type":"text","text":"The final result of the MagnifEye liveness process."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/init(bgrRawImage:face:content:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/bgrRawImage","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/content","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/face"]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","navigatorTitle":[{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"title":"MagnifEyeLivenessResult"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition"],"title":"MagnifEye liveness result"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFMagnifEyeLivenessResult) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult/bgrRawImage":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bgrRawImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bgrRawImage"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessresult\/bgrrawimage","abstract":[{"type":"text","text":"Captured face image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/bgrRawImage","title":"bgrRawImage"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult/init(bgrRawImage:face:content:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessresult\/init(bgrrawimage:face:content:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/init(bgrRawImage:face:content:)","navigatorTitle":[{"text":"initWithBgrRawImage:face:content:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","title":"init(bgrRawImage:face:content:)","kind":"symbol"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult","role":"symbol","title":"MagnifEyeLivenessResult","navigatorTitle":[{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"abstract":[{"type":"text","text":"The final result of the MagnifEye liveness process."}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessresult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessResult"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult/face":{"kind":"symbol","abstract":[{"text":"Detected face.","type":"text"}],"navigatorTitle":[{"text":"face","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessresult\/face","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/face","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"}],"type":"topic","title":"face"},"doc://com.innovatrics.dot.face.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult/description":{"abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessresult\/description","type":"topic"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureDetection":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturedetection","kind":"symbol","abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","title":"FaceAutoCaptureDetection","type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectionPosition":{"abstract":[{"type":"text","text":"The position of the detected face in the image."}],"title":"DetectionPosition","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/detectionposition","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult/content":{"role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessresult\/content","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/content","navigatorTitle":[{"text":"content","kind":"identifier"}],"abstract":[{"type":"text","text":"Binary content for server-side evaluation."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"content"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"type":"topic","title":"content","kind":"symbol"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"title":"MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"DOTFMagnifEyeLivenessResult","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"DOTFMagnifEyeLivenessResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessResult"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/bgrRawImage","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/content","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/face"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/init(bgrRawImage:face:content:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"MagnifEye liveness result","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectionPosition"],"generated":true}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFMagnifEyeLivenessResult"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"bgrRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1bgrRawImage\/title"},{"value":[{"kind":"identifier","text":"bgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1bgrRawImage\/fragments"},{"value":"initWithBgrRawImage:face:content:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1init(bgrRawImage:face:content:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBgrRawImage:face:content:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1init(bgrRawImage:face:content:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/title","value":"DOTFMagnifEyeLivenessResult"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessResult"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1face\/title","value":"face","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1face\/fragments","value":[{"kind":"identifier","text":"face"}],"op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1description\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/title","value":"DOTDetectionPosition","op":"replace"},{"value":[{"text":"DOTDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectionPosition\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1content\/title","value":"content","op":"replace"},{"value":[{"text":"content","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1content\/fragments"},{"op":"replace","value":"DOTFMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"}]}]}