{"seeAlsoSections":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MatchingQualityProvider"}],"title":"MatchingQualityProvider","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMatchingQualityProvider","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"MatchingQualityProvider"}]},"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for matching."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/findQualityAttributeById(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/getQualityAttributes()"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/matchingqualityprovider"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/matchingqualityprovider"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFMatchingQualityProvider) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MatchingQualityProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId":{"role":"symbol","title":"QualityAttributeId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattributeid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/PassiveLivenessQualityProvider":{"role":"symbol","title":"PassiveLivenessQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for passive liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"url":"\/documentation\/dotfacecore\/passivelivenessqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MatchingQualityProvider/findQualityAttributeById(_:)":{"role":"symbol","title":"findQualityAttributeById(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findQualityAttributeById"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFQualityAttributeId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttribute"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" object configured for matching."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/findQualityAttributeById(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"findQualityAttributeById:"}],"url":"\/documentation\/dotfacecore\/matchingqualityprovider\/findqualityattributebyid(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IcaoQualityProvider":{"role":"symbol","title":"IcaoQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IcaoQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for ICAO evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IcaoQualityProvider"}],"url":"\/documentation\/dotfacecore\/icaoqualityprovider"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DefaultQualityAttributeRegistry":{"role":"symbol","title":"DefaultQualityAttributeRegistry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"abstract":[{"type":"text","text":"This class contains default "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" for every "},{"type":"codeVoice","code":"QualityAttributeId"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"url":"\/documentation\/dotfacecore\/defaultqualityattributeregistry"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute":{"role":"symbol","title":"QualityAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}],"url":"\/documentation\/dotfacecore\/qualityattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MatchingQualityProvider/getQualityAttributes()":{"role":"symbol","title":"getQualityAttributes()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getQualityAttributes"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttribute"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Returns set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects configured for matching."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/getQualityAttributes()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"getQualityAttributes"}],"url":"\/documentation\/dotfacecore\/matchingqualityprovider\/getqualityattributes()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MatchingQualityProvider":{"role":"symbol","title":"MatchingQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MatchingQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for matching."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MatchingQualityProvider"}],"url":"\/documentation\/dotfacecore\/matchingqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MatchingQualityProvider/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacecore\/matchingqualityprovider\/init"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider":{"role":"symbol","title":"QualityProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityProvider"}],"abstract":[{"type":"text","text":"Provider of quality attributes configured for specific use case."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityProvider"}],"url":"\/documentation\/dotfacecore\/qualityprovider"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFMatchingQualityProvider"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFMatchingQualityProvider"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMatchingQualityProvider"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/findQualityAttributeById(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/getQualityAttributes()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFMatchingQualityProvider"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/title","value":"DOTFQualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/fragments","value":[{"kind":"identifier","text":"DOTFQualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/title","value":"DOTFPassiveLivenessQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFPassiveLivenessQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider~1findQualityAttributeById(_:)\/title","value":"findQualityAttributeById:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider~1findQualityAttributeById(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"findQualityAttributeById:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/title","value":"DOTFIcaoQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFIcaoQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/title","value":"DOTFDefaultQualityAttributeRegistry"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/fragments","value":[{"kind":"identifier","text":"DOTFDefaultQualityAttributeRegistry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/title","value":"DOTFQualityAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFQualityAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider~1getQualityAttributes()\/title","value":"getQualityAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider~1getQualityAttributes()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getQualityAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/title","value":"DOTFMatchingQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFMatchingQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/title","value":"DOTFQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFQualityProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}