{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPlaceholder) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"sections":[],"abstract":[{"type":"text","text":"Placeholder."}],"variants":[{"paths":["\/documentation\/dotfacecore\/placeholder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/placeholder"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"roleHeading":"Class","title":"Placeholder","externalID":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible"],"anchor":"Classes"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholderHidden":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderHidden","url":"\/documentation\/dotfacecore\/dotplaceholderhidden","role":"symbol","abstract":[{"type":"text","text":"Hidden placeholder."}],"kind":"symbol","fragments":[{"text":"DOTPlaceholderHidden","kind":"identifier"}],"title":"DOTPlaceholderHidden"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholderVisible":{"url":"\/documentation\/dotfacecore\/dotplaceholdervisible","fragments":[{"kind":"identifier","text":"DOTPlaceholderVisible"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Visible placeholder."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible","title":"DOTPlaceholderVisible","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Hidden":{"role":"symbol","navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/placeholder\/hidden","abstract":[{"text":"Hidden placeholder.","type":"text"}],"title":"Placeholder.Hidden","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Hidden","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"url":"\/documentation\/dotfacecore\/placeholder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Placeholder.","type":"text"}],"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"title":"Placeholder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","role":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholder/init":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholder\/init","url":"\/documentation\/dotfacecore\/dotplaceholder\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible","url":"\/documentation\/dotfacecore\/placeholder\/visible","navigatorTitle":[{"kind":"identifier","text":"Visible"}],"type":"topic","title":"Placeholder.Visible","abstract":[{"text":"Visible placeholder.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTPlaceholder","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPlaceholder"}]},{"op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholder\/init"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderHidden","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible"],"type":"inheritedBy","title":"Inherited By"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPlaceholder","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPlaceholder","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPlaceholder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}