{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/placeholdertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/placeholdertype"]}],"sections":[],"abstract":[{"type":"text","text":"Type of placeholder."}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPlaceholderType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"externalID":"c:@M@DotFaceCommons@E@DOTPlaceholderType","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"title":"PlaceholderType","role":"symbol"},"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/circle"],"generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/init(rawValue:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/description"],"generated":true,"title":"Instance Properties"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"references":{"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType":{"kind":"symbol","title":"PlaceholderType","role":"symbol","url":"\/documentation\/dotfacecore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/RawRepresentable-Implementations","url":"\/documentation\/dotfacecore\/placeholdertype\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/init(rawValue:)","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/placeholdertype\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/circle":{"navigatorTitle":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}],"type":"topic","title":"PlaceholderType.circle","kind":"symbol","url":"\/documentation\/dotfacecore\/placeholdertype\/circle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"circle","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/circle","abstract":[{"type":"text","text":"Circular placeholder."}],"role":"symbol"},"doc://DotFaceCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/description":{"type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/placeholdertype\/description","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/description","title":"description"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/dotfacecore\/placeholdertype\/equatable-implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/Equatable-Implementations","role":"collectionGroup","kind":"article","type":"topic","title":"Equatable Implementations"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"DOTPlaceholderType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/circle"],"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPlaceholderType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/title","value":"DOTPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType~1circle\/title","value":"DOTPlaceholderTypeCircle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType~1circle\/fragments","value":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}]}]}]}