{"seeAlsoSections":[{"title":"Style and configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessStyle"}],"title":"SmileLivenessStyle","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessStyle","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"SmileLivenessStyle"}]},"abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/Defaults"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/backgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/detectionLayerColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionBackgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionFont","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionTextColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/overlayColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/placeholderColor"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFSmileLivenessStyle) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/instructionTextColor":{"role":"symbol","title":"instructionTextColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Instruction label text color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionTextColor"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/instructiontextcolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/detectionLayerColor":{"role":"symbol","title":"detectionLayerColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Detection layer color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/detectionLayerColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectionLayerColor"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/detectionlayercolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)":{"role":"symbol","title":"init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/init(backgroundcolor:instructionfont:instructiontextcolor:instructionbackgroundcolor:placeholdercolor:detectionlayercolor:overlaycolor:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessViewController":{"role":"symbol","title":"SmileLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/instructionFont":{"role":"symbol","title":"instructionFont","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[{"type":"text","text":"Instruction label font."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionFont","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionFont"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/instructionfont"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle":{"role":"symbol","title":"SmileLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessStyle"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/Defaults":{"role":"symbol","title":"SmileLivenessStyle.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/defaults"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/overlayColor":{"role":"symbol","title":"overlayColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Overlay color, semi-transparent color is recommended."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/overlayColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"overlayColor"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/overlaycolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/init()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/instructionBackgroundColor":{"role":"symbol","title":"instructionBackgroundColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Instruction background color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionBackgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionBackgroundColor"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/instructionbackgroundcolor"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessConfiguration":{"role":"symbol","title":"SmileLivenessConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the smile liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessConfiguration"}],"url":"\/documentation\/dotfacecore\/smilelivenessconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/placeholderColor":{"role":"symbol","title":"placeholderColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Placeholder color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/placeholderColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"placeholderColor"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/placeholdercolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessStyle/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Background color of top level view."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/backgroundColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"backgroundColor"}],"url":"\/documentation\/dotfacecore\/smilelivenessstyle\/backgroundcolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFSmileLivenessStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFSmileLivenessStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/backgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/detectionLayerColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionBackgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionFont","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/instructionTextColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/overlayColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/placeholderColor"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessStyle\/init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Style and configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessConfiguration"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFSmileLivenessStyle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1instructionTextColor\/title","value":"instructionTextColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1instructionTextColor\/fragments","value":[{"kind":"identifier","text":"instructionTextColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1detectionLayerColor\/title","value":"detectionLayerColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1detectionLayerColor\/fragments","value":[{"kind":"identifier","text":"detectionLayerColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)\/title","value":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1init(backgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBackgroundColor:instructionFont:instructionTextColor:instructionBackgroundColor:placeholderColor:detectionLayerColor:overlayColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1instructionFont\/title","value":"instructionFont"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1instructionFont\/fragments","value":[{"kind":"identifier","text":"instructionFont"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle\/title","value":"DOTFSmileLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1overlayColor\/title","value":"overlayColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1overlayColor\/fragments","value":[{"kind":"identifier","text":"overlayColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1instructionBackgroundColor\/title","value":"instructionBackgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1instructionBackgroundColor\/fragments","value":[{"kind":"identifier","text":"instructionBackgroundColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessConfiguration\/title","value":"DOTFSmileLivenessConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1placeholderColor\/title","value":"placeholderColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1placeholderColor\/fragments","value":[{"kind":"identifier","text":"placeholderColor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1backgroundColor\/title","value":"backgroundColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessStyle~1backgroundColor\/fragments","value":[{"kind":"identifier","text":"backgroundColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}