{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:finished:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:processed:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerCriticalFacePresenceLost(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLoad(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillTransition(_:)"]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(pl)DOTFSmileLivenessViewControllerDelegate","navigatorTitle":[{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Protocol","title":"SmileLivenessViewControllerDelegate"},"abstract":[{"text":"Implement this delegate to the handle smile liveness events.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFSmileLivenessViewControllerDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","title":"SmileLivenessViewControllerDelegate","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to the handle smile liveness events."}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.6.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"role":"symbol","title":"SmileLivenessViewController","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewDidLoad(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"smileLivenessViewControllerViewDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"smileLivenessViewControllerViewDidLoad:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLoad(_:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidload(_:)","abstract":[],"kind":"symbol","type":"topic","title":"smileLivenessViewControllerViewDidLoad(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerCriticalFacePresenceLost(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerCriticalFacePresenceLost(_:)","title":"smileLivenessViewControllerCriticalFacePresenceLost(_:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerCriticalFacePresenceLost","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the face was not detected during the critical part of the smile liveness process."}],"kind":"symbol","navigatorTitle":[{"text":"smileLivenessViewControllerCriticalFacePresenceLost:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollercriticalfacepresencelost(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerNoCameraPermission(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","kind":"typeIdentifier","text":"SmileLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"smileLivenessViewControllerNoCameraPermission:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerNoCameraPermission(_:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollernocamerapermission(_:)","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"kind":"symbol","type":"topic","title":"smileLivenessViewControllerNoCameraPermission(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewDidLayoutSubviews(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerViewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","kind":"typeIdentifier","text":"SmileLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"smileLivenessViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLayoutSubviews(_:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidlayoutsubviews(_:)","abstract":[],"kind":"symbol","type":"topic","title":"smileLivenessViewControllerViewDidLayoutSubviews(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewWillTransition(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileLivenessViewControllerViewWillTransition"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewwilltransition(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillTransition(_:)","navigatorTitle":[{"text":"smileLivenessViewControllerViewWillTransition:","kind":"identifier"}],"title":"smileLivenessViewControllerViewWillTransition(_:)","role":"symbol","type":"topic","abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewController(_:processed:)":{"abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"title":"smileLivenessViewController(_:processed:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:processed:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontroller(_:processed:)","navigatorTitle":[{"text":"smileLivenessViewController:processed:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"smileLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"SmileLivenessViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewDidAppear(_:)":{"title":"smileLivenessViewControllerViewDidAppear(_:)","abstract":[],"required":true,"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidAppear(_:)","kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidappear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerViewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"SmileLivenessViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"smileLivenessViewControllerViewDidAppear:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewController(_:finished:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"smileLivenessViewController:finished:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontroller(_:finished:)","title":"smileLivenessViewController(_:finished:)","abstract":[{"text":"Tells the delegate that the smile liveness process has finished with result.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:finished:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"finished"},{"text":": ","kind":"text"},{"text":"SmileLivenessResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessResult","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewWillDisappear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileLivenessViewControllerViewWillDisappear"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"SmileLivenessViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillDisappear(_:)","abstract":[],"title":"smileLivenessViewControllerViewWillDisappear(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewwilldisappear(_:)","role":"symbol","navigatorTitle":[{"text":"smileLivenessViewControllerViewWillDisappear:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewDidDisappear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"smileLivenessViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"SmileLivenessViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","title":"smileLivenessViewControllerViewDidDisappear(_:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdiddisappear(_:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidDisappear(_:)","navigatorTitle":[{"text":"smileLivenessViewControllerViewDidDisappear:","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewWillAppear(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillAppear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerViewWillAppear"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","kind":"typeIdentifier","text":"SmileLivenessViewController"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewwillappear(_:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"smileLivenessViewControllerViewWillAppear:"}],"title":"smileLivenessViewControllerViewWillAppear(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"DOTFSmileLivenessViewControllerDelegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFSmileLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFSmileLivenessViewControllerDelegate","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:finished:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:processed:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerCriticalFacePresenceLost(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidLoad(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewWillTransition(_:)"]}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFSmileLivenessViewControllerDelegate","kind":"identifier"}]}],"kind":"declarations"}},{"value":"DOTFSmileLivenessViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/fragments"},{"value":"DOTFSmileLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidLoad(_:)\/title","value":"smileLivenessViewControllerViewDidLoad:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"smileLivenessViewControllerViewDidLoad:","kind":"identifier"}],"op":"replace"},{"value":"smileLivenessViewControllerCriticalFacePresenceLost:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerCriticalFacePresenceLost(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerCriticalFacePresenceLost(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerCriticalFacePresenceLost:"}],"op":"replace"},{"op":"replace","value":"smileLivenessViewControllerNoCameraPermission:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerNoCameraPermission(_:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerNoCameraPermission(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerNoCameraPermission:"}],"op":"replace"},{"value":"smileLivenessViewControllerViewDidLayoutSubviews:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidLayoutSubviews(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"smileLivenessViewControllerViewDidLayoutSubviews:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidLayoutSubviews(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillTransition(_:)\/title","op":"replace","value":"smileLivenessViewControllerViewWillTransition:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillTransition(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"smileLivenessViewControllerViewWillTransition:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewController(_:processed:)\/title","value":"smileLivenessViewController:processed:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewController(_:processed:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"smileLivenessViewController:processed:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidAppear(_:)\/title","value":"smileLivenessViewControllerViewDidAppear:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"smileLivenessViewControllerViewDidAppear:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidAppear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewController(_:finished:)\/title","value":"smileLivenessViewController:finished:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewController(_:finished:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewController:finished:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillDisappear(_:)\/title","value":"smileLivenessViewControllerViewWillDisappear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"smileLivenessViewControllerViewWillDisappear:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidDisappear(_:)\/title","value":"smileLivenessViewControllerViewDidDisappear:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewControllerViewDidDisappear:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidDisappear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillAppear(_:)\/title","value":"smileLivenessViewControllerViewWillAppear:"},{"value":[{"text":"- ","kind":"text"},{"text":"smileLivenessViewControllerViewWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewWillAppear(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}