{"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher"],"title":"Non-UI components"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFTemplateMatcher) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TemplateMatcher"}]}]},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"This component requires ","type":"text"},{"type":"codeVoice","code":"DotFaceVerification"},{"text":" module to be active.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/templatematcher"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/templatematcher"]}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can match templates."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher"},"metadata":{"roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFTemplateMatcher","symbolKind":"class","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TemplateMatcher"}],"role":"symbol","title":"TemplateMatcher"},"topicSections":[{"title":"Verification","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template"]},{"title":"Classes","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Result"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/init()"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplate:probeTemplate:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplateBytes:probeTemplateBytes:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error"],"title":"Enumerations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceMatcher"}],"title":"FaceMatcher","role":"symbol","kind":"symbol","abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}],"url":"\/documentation\/dotfacecore\/facematcher","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Result":{"abstract":[{"text":"Template matcher result.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Result","type":"topic","title":"TemplateMatcher.Result","url":"\/documentation\/dotfacecore\/templatematcher\/result","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Result","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Result"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.14.0"}],"role":"collection","title":"DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/init()":{"title":"init()","type":"topic","url":"\/documentation\/dotfacecore\/templatematcher\/init()","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/init()"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error":{"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"title":"TemplateMatcher.Error","kind":"symbol","url":"\/documentation\/dotfacecore\/templatematcher\/error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error","abstract":[{"type":"text","text":"Matching errors."}],"navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"abstract":[{"text":"Face template.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Template","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","url":"\/documentation\/dotfacecore\/template","type":"topic","role":"symbol","navigatorTitle":[{"text":"Template","kind":"identifier"}],"title":"Template","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/match(referenceTemplate:probeTemplate:)":{"abstract":[{"text":"Match reference and probe face templates.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplate:probeTemplate:)","title":"match(referenceTemplate:probeTemplate:)","navigatorTitle":[{"text":"matchWithReferenceTemplate:probeTemplate:error:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/templatematcher\/match(referencetemplate:probetemplate:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"match"},{"text":"(","kind":"text"},{"text":"referenceTemplate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"probeTemplate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","kind":"typeIdentifier","text":"Template"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC","kind":"typeIdentifier","text":"Result"}]},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"title":"TemplateMatcher","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","type":"topic","url":"\/documentation\/dotfacecore\/templatematcher","abstract":[{"text":"Stateless class which can match templates.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TemplateMatcher","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TemplateMatcher","kind":"identifier"}]},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/match(referenceTemplateBytes:probeTemplateBytes:)":{"abstract":[{"text":"Match reference and probe face templates.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplateBytes:probeTemplateBytes:)","title":"match(referenceTemplateBytes:probeTemplateBytes:)","navigatorTitle":[{"text":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/templatematcher\/match(referencetemplatebytes:probetemplatebytes:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplateBytes"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"probeTemplateBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC"}]},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTFTemplateMatcher"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template"],"title":"Verification"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplate:probeTemplate:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplateBytes:probeTemplateBytes:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher"],"title":"Non-UI components"}],"op":"replace"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFTemplateMatcher","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","value":"DOTFFaceMatcher"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title","op":"replace","value":"DOTFTemplate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments","value":[{"text":"DOTFTemplate","kind":"identifier"}],"op":"replace"},{"value":"matchWithReferenceTemplate:probeTemplate:error:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplate:probeTemplate:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"matchWithReferenceTemplate:probeTemplate:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplate:probeTemplate:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTFTemplateMatcher"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplateBytes:probeTemplateBytes:)\/title","value":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplateBytes:probeTemplateBytes:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:","kind":"identifier"}],"op":"replace"}]}]}