{"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValueRange"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFValueRange","navigatorTitle":[{"kind":"identifier","text":"ValueRange"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","title":"ValueRange"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange"},"abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" range, compatible with Objective-C."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFValueRange) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValueRange","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/valuerange"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/valuerange"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/init(min:max:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/max","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/min"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/isEqual(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/resolveStatus(value:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Enumerations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"],"generated":true,"anchor":"Enumerations"}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/min":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/min","title":"min","abstract":[{"text":"Minimal range value.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"min"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","url":"\/documentation\/dotfacecore\/valuerange\/min"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/resolveStatus(value:)":{"title":"resolveStatus(value:)","url":"\/documentation\/dotfacecore\/valuerange\/resolvestatus(value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolveStatus"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore10ValueRangeC6StatusO","text":"Status"}],"type":"topic","kind":"symbol","abstract":[{"text":"Checks the status of ","type":"text"},{"code":"value","type":"codeVoice"},{"text":" with respect to this range.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"resolveStatusWithValue:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/resolveStatus(value:)"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/init(min:max:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(min:max:)","navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:error:"}],"type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/valuerange\/init(min:max:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/init(min:max:)","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/status","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status","abstract":[{"text":"Status of a value with respect to a range.","type":"text"}],"title":"ValueRange.Status","navigatorTitle":[{"text":"Status","kind":"identifier"}]},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/description":{"type":"topic","role":"symbol","title":"description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/description"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/isEqual(_:)":{"kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/isequal(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEqual(_:)"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/hash":{"kind":"symbol","abstract":[],"title":"hash","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/hash"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" range, compatible with Objective-C."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"ValueRange"}],"type":"topic","title":"ValueRange","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValueRange"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","url":"\/documentation\/dotfacecore\/valuerange"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/max":{"title":"max","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/valuerange\/max","abstract":[{"text":"Maximal range value.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/max","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"max","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Error":{"url":"\/documentation\/dotfacecore\/valuerange\/error","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"ValueRange.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFValueRange","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTFValueRange","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFValueRange","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/max","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/min"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/init(min:max:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/isEqual(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/resolveStatus(value:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFValueRange","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"min","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1min\/title"},{"value":[{"kind":"identifier","text":"min"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1min\/fragments"},{"value":"resolveStatusWithValue:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1resolveStatus(value:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"resolveStatusWithValue:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1resolveStatus(value:)\/fragments"},{"value":"initWithMin:max:error:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1init(min:max:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMin:max:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1init(min:max:)\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1description\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1isEqual(_:)\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1hash\/fragments"},{"value":"DOTFValueRange","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title"},{"value":[{"kind":"identifier","text":"DOTFValueRange"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments"},{"value":[{"text":"DOTFValueRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/navigatorTitle"},{"value":"max","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1max\/title"},{"value":[{"text":"max","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1max\/fragments"}]}]}