{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWearablesQuery","navigatorTitle":[{"text":"WearablesQuery","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotFaceCore"}],"title":"WearablesQuery","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WearablesQuery"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/init(evaluateGlasses:evaluateMask:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateGlasses","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateMask"],"title":"Instance Properties"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}],"kind":"symbol","seeAlsoSections":[{"title":"Face evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFWearablesQuery) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WearablesQuery"}]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/dotfacecore\/wearablesquery"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wearablesquery"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery/init()":{"title":"init()","url":"\/documentation\/dotfacecore\/wearablesquery\/init()","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/init()","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}]},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"role":"symbol","kind":"symbol","type":"topic","title":"FaceAttribute","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","url":"\/documentation\/dotfacecore\/faceattribute","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}]},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","abstract":[{"type":"text","text":"Face attribute for the glasses."}],"role":"symbol","type":"topic","title":"Glasses","url":"\/documentation\/dotfacecore\/glasses","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Glasses"}],"navigatorTitle":[{"kind":"identifier","text":"Glasses"}]},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery/init(evaluateGlasses:evaluateMask:)":{"type":"topic","url":"\/documentation\/dotfacecore\/wearablesquery\/init(evaluateglasses:evaluatemask:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/init(evaluateGlasses:evaluateMask:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"evaluateGlasses"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"evaluateMask","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"initWithEvaluateGlasses:evaluateMask:","kind":"identifier"}],"title":"init(evaluateGlasses:evaluateMask:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"role":"symbol","kind":"symbol","title":"FaceImageQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","url":"\/documentation\/dotfacecore\/faceimagequality","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","role":"symbol","title":"HeadPose","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}],"abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"url":"\/documentation\/dotfacecore\/headpose","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","title":"FaceImageQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"kind":"symbol"},"doc://DotFaceCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","url":"\/documentation\/dotfacecore\/facequality","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"title":"FaceQuality","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"title":"WearablesQuery","url":"\/documentation\/dotfacecore\/wearablesquery","abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WearablesQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","role":"symbol","title":"HeadPoseAttribute","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"HeadPoseAttribute","kind":"identifier"}],"abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}],"url":"\/documentation\/dotfacecore\/headposeattribute","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"title":"FaceQualityQuery","url":"\/documentation\/dotfacecore\/facequalityquery","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery/evaluateGlasses":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateGlasses","navigatorTitle":[{"text":"evaluateGlasses","kind":"identifier"}],"title":"evaluateGlasses","type":"topic","abstract":[{"type":"text","text":"Glasses evaluation flag."}],"url":"\/documentation\/dotfacecore\/wearablesquery\/evaluateglasses","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"evaluateGlasses","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery/evaluateMask":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateMask"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/dotfacecore\/wearablesquery\/evaluatemask","abstract":[{"type":"text","text":"Face mask evaluation flag."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"evaluateMask"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateMask","title":"evaluateMask"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"type":"topic","role":"symbol","title":"Wearables","url":"\/documentation\/dotfacecore\/wearables","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Wearables"}],"abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ExpressionQuery","kind":"identifier"}],"title":"ExpressionQuery","url":"\/documentation\/dotfacecore\/expressionquery","abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"url":"\/documentation\/dotfacecore\/eyesexpressionquery","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyesExpressionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}],"title":"EyesExpressionQuery","type":"topic","abstract":[{"text":"Eyes expression query specifies which eye expression face attributes should be evaluated.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseQuery"}],"title":"HeadPoseQuery","url":"\/documentation\/dotfacecore\/headposequery","abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","role":"symbol","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"type":"topic","role":"symbol","title":"Expression","url":"\/documentation\/dotfacecore\/expression","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Expression","kind":"identifier"}],"abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"navigatorTitle":[{"text":"Expression","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"url":"\/documentation\/dotfacecore\/faceaspects","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"title":"FaceAspects","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAspects","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"type":"topic","role":"symbol","title":"EyesExpression","url":"\/documentation\/dotfacecore\/eyesexpression","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyesExpression","kind":"identifier"}],"abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFWearablesQuery"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateGlasses","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/evaluateMask"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery\/init(evaluateGlasses:evaluateMask:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"replace","value":[{"generated":true,"title":"Face evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"]}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFWearablesQuery"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses"},{"value":[{"kind":"identifier","text":"DOTFGlasses"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments"},{"op":"replace","value":"initWithEvaluateGlasses:evaluateMask:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1init(evaluateGlasses:evaluateMask:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1init(evaluateGlasses:evaluateMask:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithEvaluateGlasses:evaluateMask:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","value":"DOTFFaceImageQuality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFHeadPose","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPose"}]},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]},{"value":"DOTFWearablesQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}]},{"op":"replace","value":"DOTFHeadPoseAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery"},{"value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1evaluateGlasses\/title","value":"evaluateGlasses","op":"replace"},{"value":[{"text":"evaluateGlasses","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1evaluateGlasses\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1evaluateMask\/title","op":"replace","value":"evaluateMask"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery~1evaluateMask\/fragments","op":"replace","value":[{"text":"evaluateMask","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","value":"DOTFWearables"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"value":"DOTFEyesExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","value":"DOTFHeadPoseQuery"},{"op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","op":"replace","value":"DOTFExpression"},{"value":[{"text":"DOTFExpression","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments"},{"value":"DOTFFaceAspects","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"op":"replace"},{"value":"DOTFEyesExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFEyesExpression"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}