{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/dependencyidentifiers"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"metadata":{"title":"dependencyIdentifiers","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"externalID":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator(py)dependencyIdentifiers","symbolKind":"property","required":true,"modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":">"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"title":"FingersAutoCaptureFrameParametersValidator","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator","kind":"symbol","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator/dependencyIdentifiers":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/dependencyidentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"required":true,"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title","value":"DOTFGFingersAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]}]}]}