{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/init(value:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/wrappeddouble\/init(value:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/wrappeddouble\/init(value:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","title":"init(value:)","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble(im)initWithValue:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/WrappedDouble/init(value:)":{"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"abstract":[],"role":"symbol","title":"init(value:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/init(value:)","url":"\/documentation\/dotdocument\/wrappeddouble\/init(value:)"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WrappedDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/wrappeddouble","type":"topic","title":"WrappedDouble","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithValue:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"initWithValue:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1init(value:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithValue:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1init(value:)\/fragments","op":"replace"},{"op":"replace","value":"DOTWrappedDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","op":"replace"}]}]}