{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/description"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"modules":[{"name":"DotNfc"}],"role":"symbol","title":"description","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)description","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/corners\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/corners\/description"]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/Corners":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotnfc\/corners","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","title":"Corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}]},"doc://DotNfc/documentation/DotNfc/Corners/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/corners\/description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/description","kind":"symbol","title":"description","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"}],"languages":["occ"]}]},"op":"replace"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments","op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"}]}]}