{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"MultiRangeLivenessViewController.Configuration.Defaults","role":"symbol","roleHeading":"Structure","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC8DefaultsV","navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"symbolKind":"struct"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults"]}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/isDetectionLayerVisible"],"anchor":"Type-Properties","generated":true}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","title":"MultiRangeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/Defaults":{"abstract":[],"title":"MultiRangeLivenessViewController.Configuration.Defaults","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/Defaults/isDetectionLayerVisible":{"abstract":[],"title":"isDetectionLayerVisible","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/isDetectionLayerVisible","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults\/isdetectionlayervisible"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"title":"MultiRangeLivenessViewController.Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"}]}]}