{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createFullFrontalImage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"createFullFrontalImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"createFullFrontalImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"createFullFrontalImage","kind":"identifier"}],"title":"createFullFrontalImage","role":"symbol","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery(py)createFullFrontalImage"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetectionquery\/createfullfrontalimage"]},{"paths":["\/documentation\/dotfacecore\/facedetectionquery\/createfullfrontalimage"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Create an ICAO full frontal image of the face.","type":"text"},{"text":" ","type":"text"},{"text":"If boundaries of the normalized image leak outside of the original image, a white background is applied.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Default value is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/createFullFrontalImage":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/createFullFrontalImage","navigatorTitle":[{"kind":"identifier","text":"createFullFrontalImage"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createFullFrontalImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery\/createfullfrontalimage","abstract":[{"type":"text","text":"Create an ICAO full frontal image of the face."},{"type":"text","text":" "},{"type":"text","text":"If boundaries of the normalized image leak outside of the original image, a white background is applied."},{"text":" ","type":"text"},{"text":"Default value is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"title":"createFullFrontalImage","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"role":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetectionQuery"}],"title":"FaceDetectionQuery","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.6.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"createFullFrontalImage"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"createFullFrontalImage","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"createFullFrontalImage","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1createFullFrontalImage\/title","value":"createFullFrontalImage","op":"replace"},{"value":[{"kind":"identifier","text":"createFullFrontalImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1createFullFrontalImage\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery","op":"replace"},{"op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"}]}]}