{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/faceQuality","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Face image quality query."}],"variants":[{"paths":["\/documentation\/dotfacecore\/facedetectionquery\/facequality"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facedetectionquery\/facequality"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery(py)faceQuality","navigatorTitle":[{"text":"faceQuality","kind":"identifier"}],"role":"symbol","title":"faceQuality","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionQuery"}],"title":"FaceDetectionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facedetectionquery"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/faceQuality":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery\/facequality","abstract":[{"type":"text","text":"Face image quality query."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/faceQuality","title":"faceQuality","navigatorTitle":[{"text":"faceQuality","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"kind":"symbol","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facequalityquery","role":"symbol","title":"FaceQualityQuery","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"faceQuality","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"faceQuality"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","kind":"typeIdentifier","text":"DOTFFaceQualityQuery"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"faceQuality"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"FaceDetectionQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title"},{"value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"},{"op":"replace","value":"faceQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1faceQuality\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1faceQuality\/fragments","value":[{"kind":"identifier","text":"faceQuality"}]},{"value":"DOTFFaceQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}