{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","text":"FaceQualityQuery"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"evaluatePassiveLiveness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"createFullFrontalImage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false, "},{"kind":"externalParam","text":"createTemplate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","symbolKind":"init","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery(im)initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceQualityQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery"},{"text":", ","kind":"text"},{"text":"evaluatePassiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"createFullFrontalImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"createTemplate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/facedetectionquery\/init(quality:evaluatepassiveliveness:createfullfrontalimage:createtemplate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facedetectionquery\/init(quality:evaluatepassiveliveness:createfullfrontalimage:createtemplate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)":{"navigatorTitle":[{"text":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluatePassiveLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"createFullFrontalImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"createTemplate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","title":"init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery\/init(quality:evaluatepassiveliveness:createfullfrontalimage:createtemplate:)","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","title":"FaceQualityQuery","kind":"symbol","url":"\/documentation\/dotfacecore\/facequalityquery","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"kind":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","title":"FaceDetectionQuery","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithQuality:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","text":"DOTFFaceQualityQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"quality"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluatePassiveLiveness:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"evaluatePassiveLiveness"},{"kind":"text","text":" "},{"kind":"identifier","text":"createFullFrontalImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"createFullFrontalImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"createTemplate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"createTemplate"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)\/title","op":"replace","value":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1init(quality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","op":"replace","value":"DOTFFaceQualityQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/navigatorTitle","op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]}]}]}