{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetectionquery\/init(facequality:evaluatepassiveliveness:createfullfrontalimage:createtemplate:)"]},{"paths":["\/documentation\/dotfacecore\/facedetectionquery\/init(facequality:evaluatepassiveliveness:createfullfrontalimage:createtemplate:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/init(faceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"faceQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"},{"kind":"text","text":" = .init(), "},{"text":"evaluatePassiveLiveness","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"createFullFrontalImage"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"createTemplate","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" = false)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithFaceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:"}],"symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery(im)initWithFaceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","modules":[{"name":"DotFaceCore"}],"title":"init(faceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"faceQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluatePassiveLiveness"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createFullFrontalImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"createTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"url":"\/documentation\/dotfacecore\/facedetectionquery","type":"topic","kind":"symbol","title":"FaceDetectionQuery","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetectionQuery"}],"navigatorTitle":[{"kind":"identifier","text":"FaceDetectionQuery"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/init(faceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluatePassiveLiveness"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"createFullFrontalImage"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"createTemplate"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithFaceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}],"role":"symbol","title":"init(faceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","url":"\/documentation\/dotfacecore\/facedetectionquery\/init(facequality:evaluatepassiveliveness:createfullfrontalimage:createtemplate:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/init(faceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)","type":"topic","kind":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"title":"FaceQualityQuery","url":"\/documentation\/dotfacecore\/facequalityquery","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithFaceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFaceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFaceQuality:"},{"text":"(","kind":"text"},{"text":"DOTFFaceQualityQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceQuality"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluatePassiveLiveness:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"evaluatePassiveLiveness","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createFullFrontalImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createFullFrontalImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createTemplate:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"createTemplate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"FaceDetectionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"op":"replace"},{"op":"replace","value":"initWithFaceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1init(faceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1init(faceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithFaceQuality:evaluatePassiveLiveness:createFullFrontalImage:createTemplate:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","op":"replace","value":"DOTFFaceQualityQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}