{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/placeholder"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/placeholder","interfaceLanguage":"swift"},"abstract":[{"text":"Specify the placeholder. Default is ","type":"text"},{"code":".Visible","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","kind":"typeIdentifier","text":"Placeholder","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDPlaceholder"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"placeholder","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Placeholder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDPlaceholder"}],"role":"symbol","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC11placeholderAA11PlaceholderCvp"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/placeholder":{"title":"placeholder","abstract":[{"type":"text","text":"Specify the placeholder. Default is "},{"type":"codeVoice","code":".Visible"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/placeholder","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDPlaceholder","text":"Placeholder","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/placeholder"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Placeholder":{"abstract":[{"text":"Placeholder.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","type":"topic","url":"\/documentation\/dotdocument\/placeholder","title":"Placeholder","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Document Auto Capture component."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","title":"DocumentAutoCaptureViewController.Configuration","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"abstract":[{"text":"UI Document Auto Capture component","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDPlaceholder","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title"},{"op":"replace","value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholder"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}