{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity"]}],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"DotPalmCore"}],"title":"backgroundUniformity","roleHeading":"Instance Property","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC20backgroundUniformityAA0ac10Backgroundh6ModuleE0CSgvp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceBackgroundUniformityModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotfacebackgrounduniformitymoduleconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration","abstract":[{"type":"text","text":"Face background uniformity module."}],"type":"topic","role":"symbol","title":"DotFaceBackgroundUniformityModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/backgroundUniformity":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity","title":"backgroundUniformity","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Face library configuration."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class","abstract":[{"text":"Face library module configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class","title":"DotFaceLibraryConfiguration.Modules"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/title","op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}]}]}