{"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmmoduleid\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","title":"init(rawValue:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"externalID":"s:7DotCore0A12PalmModuleIdO8rawValueACSgSi_tcfc","role":"symbol"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/init(rawValue:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotPalmModuleId":{"abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"type":"topic","role":"symbol","title":"DotPalmModuleId","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotpalmmoduleid"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DotPalmModuleId/init(rawValue:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmModuleId\/init(rawValue:)","url":"\/documentation\/dotdocument\/dotpalmmoduleid\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"init(rawValue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmModuleId\/navigatorTitle","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}