{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator"]]},"abstract":[{"text":"Validate brightness of the detected document.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Frame parameters to validate."}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":" for dark document."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator\/validate(documentautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator\/validate(documentautocaptureframeparameters:)"]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"validate(documentAutoCaptureFrameParameters:)","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooLowValidator(im)validateWithDocumentAutoCaptureFrameParameters:","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator/validate(documentAutoCaptureFrameParameters:)":{"title":"validate(documentAutoCaptureFrameParameters:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/validate(documentautocaptureframeparameters:)","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator\/validate(documentAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate brightness of the detected document."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"abstract":[{"text":"Validate minimum brightness of the detected document.","type":"text"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","role":"symbol","title":"BrightnessTooLowValidator","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","type":"topic","abstract":[{"text":"Information from the detection process about the detected document.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"title":"DocumentAutoCaptureFrameParameters","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","text":"DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"documentAutoCaptureFrameParameters"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"value":"DOTDBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"}]}]}