{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/validate(documentAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Validate if barcode is inside detected document bounds.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Frame parameters to validate."}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" if barcode lies outside document."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeOutsideOfDocumentValidator(im)validateWithDocumentAutoCaptureFrameParameters:","title":"validate(documentAutoCaptureFrameParameters:)","role":"symbol","modules":[{"name":"DotDocument"}]},"variants":[{"paths":["\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator/validate(documentAutoCaptureFrameParameters:)":{"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/validate(documentautocaptureframeparameters:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/validate(documentAutoCaptureFrameParameters:)","abstract":[{"text":"Validate if barcode is inside detected document bounds.","type":"text"}],"title":"validate(documentAutoCaptureFrameParameters:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected document.","type":"text"}],"title":"DocumentAutoCaptureFrameParameters","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator":{"url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator","abstract":[{"text":"Validate if barcode is inside detected document bounds.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator","navigatorTitle":[{"text":"BarcodeOutsideOfDocumentValidator","kind":"identifier"}],"title":"BarcodeOutsideOfDocumentValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeOutsideOfDocumentValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DOTDDocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"documentAutoCaptureFrameParameters","content":[{"inlineContent":[{"text":"Frame parameters to validate.","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" if barcode lies outside document."}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1validate(documentAutoCaptureFrameParameters:)\/title","op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/title","op":"replace","value":"DOTDBarcodeOutsideOfDocumentValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeOutsideOfDocumentValidator"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDBarcodeOutsideOfDocumentValidator"}]}]}]}