{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(cgImage:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"text":") -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithCgImage:","navigatorTitle":[{"text":"createBgraRawImageWithCgImage:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}],"title":"createBgraRawImage(cgImage:)","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(cgimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(cgimage:)"]}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"cgImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory"]]},"references":{"doc://DotNfc/documentation/DotNfc/ImageFactory":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"title":"ImageFactory","url":"\/documentation\/dotnfc\/imagefactory","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory"},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgraRawImage(cgImage:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"title":"createBgraRawImage(cgImage:)","url":"\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(cgimage:)","navigatorTitle":[{"text":"createBgraRawImageWithCgImage:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(cgImage:)"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.2.3","type":"text"}],"role":"collection","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/Image":{"type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"title":"Image","url":"\/documentation\/dotnfc\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBgraRawImageWithCgImage:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"DOTImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImageRef"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cgImage"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTImageFactory","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(cgImage:)\/title","value":"createBgraRawImageWithCgImage:"},{"value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithCgImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle","op":"replace"}]}]}