{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidAppear(_:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidAppear:"}],"required":true,"title":"faceAutoCaptureViewControllerViewDidAppear(_:)","externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate(im)faceAutoCaptureViewControllerViewDidAppear:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController"},{"kind":"text","text":")"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewDidAppear(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"faceAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}],"type":"topic","title":"faceAutoCaptureViewControllerViewDidAppear(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidAppear(_:)","required":true,"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidappear(_:)","role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"navigatorTitle":[{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureViewControllerDelegate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"role":"symbol","title":"BaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","abstract":[{"text":"UI Face Auto Capture component.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceAutoCaptureViewControllerViewDidAppear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewDidAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidAppear(_:)\/title","value":"faceAutoCaptureViewControllerViewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFFaceAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","value":"DOTFBaseFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]}]}]}