{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/licenseBytes"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"symbolKind":"class","modules":[{"name":"DotDocument"}],"roleHeading":"Class","externalID":"c:@M@DotDocument@objc(cs)DotSdkLicenseProxy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"role":"symbol","title":"DotSdkLicenseProxy","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isFaceEnabled":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEnabled","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceenabled","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","title":"isFaceEnabled","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}]},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy":{"kind":"symbol","title":"DotSdkLicenseProxy","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"abstract":[],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/licenseBytes":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseBytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/licensebytes","title":"licenseBytes","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/licenseBytes"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"title":"DotSdkLicenseProxyProtocol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","abstract":[]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isFaceMatchingEnabled":{"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"title":"isFaceMatchingEnabled","role":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isfacematchingenabled","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceMatchingEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","kind":"symbol","abstract":[]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isFaceEyeGazeLivenessScoreEnabled":{"kind":"symbol","title":"isFaceEyeGazeLivenessScoreEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled","abstract":[]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isFacePassiveLivenessEnabled":{"kind":"symbol","title":"isFacePassiveLivenessEnabled","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isfacepassivelivenessenabled","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFacePassiveLivenessEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"type":"topic"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.0.0"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isDocumentEnabled":{"type":"topic","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isdocumentenabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDocumentEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"isDocumentEnabled","navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isDocumentEnabled"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isFaceLiteEnabled":{"abstract":[],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceliteenabled","navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceLiteEnabled","kind":"symbol","title":"isFaceLiteEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isEvaluation":{"type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEvaluation"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isEvaluation","title":"isEvaluation","navigatorTitle":[{"kind":"identifier","text":"isEvaluation"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isevaluation"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isNfcEnabled":{"role":"symbol","type":"topic","kind":"symbol","title":"isNfcEnabled","navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isnfcenabled","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isNfcEnabled","abstract":[]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isRealTimeTransactionReportingEnabled":{"navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isRealTimeTransactionReportingEnabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DotSdkLicenseProxy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/licenseBytes"]}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol"],"title":"Conforms To","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"op":"replace","value":"isFaceEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isFaceEnabled"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceEnabled\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"op":"replace"},{"op":"replace","value":"licenseBytes","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1licenseBytes\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1licenseBytes\/fragments","value":[{"text":"licenseBytes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/title","value":"isFaceMatchingEnabled"},{"value":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},{"value":"isFacePassiveLivenessEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/fragments","value":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isDocumentEnabled\/title","value":"isDocumentEnabled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isDocumentEnabled\/fragments","value":[{"kind":"identifier","text":"isDocumentEnabled"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title","value":"isFaceLiteEnabled","op":"replace"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isEvaluation\/title","value":"isEvaluation","op":"replace"},{"value":[{"kind":"identifier","text":"isEvaluation"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isEvaluation\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isNfcEnabled\/title","op":"replace","value":"isNfcEnabled"},{"value":[{"kind":"identifier","text":"isNfcEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isNfcEnabled\/fragments"},{"value":"isRealTimeTransactionReportingEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/title"},{"value":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/fragments","op":"replace"}]}]}