{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle\/initWithPreview:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPreview:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"DOTFaceAutoCapturePreview"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preview"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureuistateidle\/initwithpreview:"]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiStateIdle(im)initWithPreview:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"}],"title":"initWithPreview:","role":"symbol","navigatorTitle":[{"text":"initWithPreview:","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview","kind":"symbol","title":"FaceAutoCapturePreview","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateIdle":{"abstract":[{"text":"Idle state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active either:","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiStateIdle"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistateidle","role":"symbol","title":"DOTFLFaceAutoCaptureUiStateIdle","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateIdle/initWithPreview:":{"kind":"symbol","title":"initWithPreview:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistateidle\/initwithpreview:","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle\/initWithPreview:","navigatorTitle":[{"text":"initWithPreview:","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","value":"DOTFaceAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace"}]}]}