{"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"title":"preview","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiStateIdle(py)preview","fragments":[{"text":"preview","kind":"identifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"preview","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureuistateidle\/preview"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle"]]},"abstract":[{"type":"text","text":"Preview information."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFaceAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview"},{"text":" * ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle\/preview","interfaceLanguage":"occ"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview","kind":"symbol","title":"FaceAutoCapturePreview","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateIdle/preview":{"fragments":[{"kind":"identifier","text":"preview"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Preview information.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistateidle\/preview","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle\/preview","title":"preview"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateIdle":{"abstract":[{"text":"Idle state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active either:","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiStateIdle"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistateidle","role":"symbol","title":"DOTFLFaceAutoCaptureUiStateIdle","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateIdle"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTFaceAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments"},{"value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}