{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(multiRangeLivenessViewControllerViewDidAppear:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidAppear(_:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessViewControllerViewDidAppear:","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"multiRangeLivenessViewControllerViewDidAppear(_:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidAppear:"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidappear(_:)"]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","role":"symbol","abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"title":"MultiRangeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewDidAppear(_:)":{"role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidAppear(_:)","navigatorTitle":[{"text":"multiRangeLivenessViewControllerViewDidAppear:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidappear(_:)","type":"topic","title":"multiRangeLivenessViewControllerViewDidAppear(_:)","kind":"symbol","required":true},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate":{"title":"MultiRangeLivenessViewControllerDelegate","type":"topic","abstract":[{"text":"Implement this delegate to handle the Multi-Range Liveness events.","type":"text"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"multiRangeLivenessViewControllerViewDidAppear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidAppear:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidAppear:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","kind":"typeIdentifier","text":"DOTFMultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","value":"DOTFMultiRangeLivenessViewController"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle"},{"op":"replace","value":"multiRangeLivenessViewControllerViewDidAppear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidAppear(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewDidAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidAppear(_:)\/fragments"},{"op":"replace","value":"DOTFMultiRangeLivenessViewControllerDelegate","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/title"},{"op":"replace","value":[{"text":"DOTFMultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"DOTFMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]}]}]}