{"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"common"}],"fragments":[{"kind":"identifier","text":"common"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"property","roleHeading":"Instance Property","title":"common","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration(py)common"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"]]},"abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTCommonConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"common"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/common"]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/common"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration/common":{"fragments":[{"kind":"identifier","text":"common"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/common","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/common","abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"type":"topic","title":"common"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"fragments":[{"text":"DOTFLMagnifEyeLivenessConfiguration","kind":"identifier"}],"title":"DOTFLMagnifEyeLivenessConfiguration","type":"topic","abstract":[{"text":"Configuration options for the UI MagnifEye Liveness component.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"title":"CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"url":"\/documentation\/dotfacelite\/commonconfiguration","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title","op":"replace","value":"DOTCommonConfiguration"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle"}]}]}