{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults"]]},"metadata":{"externalID":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC8DefaultsV22cameraPreviewScaleType0A6Camera0olmN0OvpZ","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","roleHeading":"Type Property","title":"cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","text":"CameraPreviewScaleType"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/Defaults":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults","role":"symbol","title":"MultiRangeLivenessViewController.Configuration.Defaults","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults","abstract":[],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"abstract":[{"type":"text","text":"UI component for capturing images suitable for Multi-Range Liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","title":"MultiRangeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","type":"topic","title":"CameraPreviewScaleType","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class/Defaults/cameraPreviewScaleType":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","type":"topic","title":"cameraPreviewScaleType","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"type":"topic","title":"MultiRangeLivenessViewController.Configuration","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the Multi-Range Liveness process.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}]},{"value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]}]}]}