{"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cgimagefactory\/create(image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/cgimagefactory\/create(image:)"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory\/create(image:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"},{"text":") -> ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}]}],"name":"image"}]},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" instance."}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithImage:","title":"create(image:)","symbolKind":"method","modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createWithImage:"}]},"references":{"doc://DotNfc/documentation/DotNfc/CGImageFactory/create(image:)":{"kind":"symbol","navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"title":"create(image:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory\/create(image:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"}],"url":"\/documentation\/dotnfc\/cgimagefactory\/create(image:)"},"doc://DotNfc/documentation/DotNfc/Image":{"abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","title":"Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/CGImageFactory":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/cgimagefactory","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"title":"CGImageFactory","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createWithImage:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@CGImage","text":"CGImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"Input image as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}},{"op":"replace","value":"createWithImage:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory~1create(image:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithImage:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory~1create(image:)\/fragments"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle"},{"op":"replace","value":"DOTCGImageFactory","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/title"},{"op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/fragments"},{"op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/navigatorTitle"}]}]}