{"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"title":"initWithType:","fragments":[{"kind":"text","text":"- "},{"text":"initWithType:","kind":"identifier"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"initWithType:","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholderVisible(im)initWithType:"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/initWithType:"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"initWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","text":"DOTPPlaceholderType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpplaceholdervisible\/initwithtype:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible":{"url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible","title":"DOTPPlaceholderVisible","kind":"symbol","abstract":[{"text":"Visible placeholder.","type":"text"}],"type":"topic","fragments":[{"text":"DOTPPlaceholderVisible","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","url":"\/documentation\/dotpalmcore\/placeholdertype","title":"PlaceholderType","type":"topic","abstract":[{"text":"Type of placeholder.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPlaceholderVisible/initWithType:":{"navigatorTitle":[{"kind":"identifier","text":"initWithType:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPlaceholderVisible\/initWithType:","url":"\/documentation\/dotpalmcore\/dotpplaceholdervisible\/initwithtype:","title":"initWithType:","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTPPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPlaceholderType"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/navigatorTitle","op":"replace","value":[{"text":"DOTPPlaceholderType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}