{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}]}],"abstract":[{"text":"Maximal interval value.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble(py)max","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","title":"max","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"max"}]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/max","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervaldouble\/max"]},{"paths":["\/documentation\/dotnfc\/intervaldouble\/max"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"type":"topic","title":"IntervalDouble","role":"symbol","url":"\/documentation\/dotnfc\/intervaldouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/IntervalDouble/max":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Maximal interval value."}],"navigatorTitle":[{"kind":"identifier","text":"max"}],"type":"topic","title":"max","role":"symbol","url":"\/documentation\/dotnfc\/intervaldouble\/max","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble\/max","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"max","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"max","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/fragments"},{"op":"replace","value":"max","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble~1max\/title"},{"value":[{"kind":"identifier","text":"max"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble~1max\/fragments"}]}]}