{"metadata":{"role":"symbol","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureLeftEyebrowOuterEdge","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyebrowOuterEdge"}],"roleHeading":"Case","symbolKind":"case","title":"FaceFeature.leftEyebrowOuterEdge","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowOuterEdge"}],"modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftEyebrowOuterEdge","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowOuterEdge"},"variants":[{"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyebrowouteredge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/lefteyebrowouteredge"]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Available face features.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeature"}],"url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyebrowOuterEdge":{"role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/facefeature\/lefteyebrowouteredge","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyebrowOuterEdge","kind":"identifier"}],"title":"FaceFeature.leftEyebrowOuterEdge","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowOuterEdge","kind":"symbol","navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyebrowOuterEdge","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTFFaceFeatureLeftEyebrowOuterEdge"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowOuterEdge"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowOuterEdge"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTFFaceFeature","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowOuterEdge\/title","value":"DOTFFaceFeatureLeftEyebrowOuterEdge"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowOuterEdge"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowOuterEdge\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}