{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthCenter"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouthCenter","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthCenter"}],"role":"symbol","title":"FaceFeature.mouthCenter","symbolKind":"case","roleHeading":"Case","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureMouthCenter","modules":[{"name":"DotFaceCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouthCenter","kind":"identifier"}]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthcenter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/mouthcenter"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthCenter":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthCenter","type":"topic","role":"symbol","abstract":[],"title":"FaceFeature.mouthCenter","url":"\/documentation\/dotfacecore\/facefeature\/mouthcenter","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthCenter"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthCenter"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Available face features.","type":"text"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeature"}],"url":"\/documentation\/dotfacecore\/facefeature","title":"FaceFeature","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceFeatureMouthCenter"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureMouthCenter"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTFFaceFeatureMouthCenter","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthCenter\/title","value":"DOTFFaceFeatureMouthCenter"},{"value":[{"text":"DOTFFaceFeatureMouthCenter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthCenter\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}