{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/placeOfBirth"},"abstract":[{"type":"text","text":"Place of birth."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/placeofbirth"]},{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/placeofbirth"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"placeOfBirth","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)placeOfBirth","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeOfBirth"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}],"modules":[{"name":"DotNfc"}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"13.0","beta":false,"deprecated":false}],"role":"symbol","title":"placeOfBirth"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"placeOfBirth","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"references":{"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/placeOfBirth":{"navigatorTitle":[{"text":"placeOfBirth","kind":"identifier"}],"title":"placeOfBirth","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/placeOfBirth","role":"symbol","abstract":[{"type":"text","text":"Place of birth."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"placeOfBirth","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"kind":"symbol","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/placeofbirth"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalPersonalDetails"}],"title":"AdditionalPersonalDetails","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/additionalpersonaldetails"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"placeOfBirth"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"placeOfBirth","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"placeOfBirth"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1placeOfBirth\/title","value":"placeOfBirth"},{"value":[{"text":"placeOfBirth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1placeOfBirth\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"value":"DOTNAdditionalPersonalDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}