{"kind":"symbol","metadata":{"title":"init(lines:td1:)","roleHeading":"Initializer","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone(im)initWithLines:td1:","navigatorTitle":[{"text":"initWithLines:td1:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td1MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone"},{"kind":"text","text":")"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td1:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/machinereadablezone\/init(lines:td1:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/machinereadablezone\/init(lines:td1:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"text":"td1","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Td1MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"]]},"references":{"doc://DotDocument/documentation/DotDocument/MachineReadableZone/init(lines:td1:)":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td1:)","role":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone\/init(lines:td1:)","navigatorTitle":[{"text":"initWithLines:td1:","kind":"identifier"}],"title":"init(lines:td1:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td1"},{"kind":"text","text":": "},{"text":"Td1MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"role":"symbol","kind":"symbol","title":"Td1MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","type":"topic","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/machinereadablezone","title":"MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithLines:td1:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLines:td1:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithLines:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"lines","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td1:"},{"kind":"text","text":"("},{"text":"DOTTd1MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"td1","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td1:)\/title","op":"replace","value":"initWithLines:td1:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td1:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLines:td1:","kind":"identifier"}],"op":"replace"},{"value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","op":"replace"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}