{"abstract":[{"type":"text","text":"Capture mode."}],"kind":"symbol","metadata":{"externalID":"c:@M@DotCapture@E@DOTCaptureMode","role":"symbol","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"symbolKind":"enum","title":"CaptureMode","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/autoCapture","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/waitForRequest"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/description"]},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/capturemode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/capturemode"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCaptureMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotFaceLite/SY":{"identifier":"doc:\/\/DotFaceLite\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/description":{"title":"description","url":"\/documentation\/dotfacelite\/capturemode\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/description"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/autoCapture":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"abstract":[{"text":"Auto capture mode (automatic mode).","type":"text"}],"title":"CaptureMode.autoCapture","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/autoCapture","url":"\/documentation\/dotfacelite\/capturemode\/autocapture","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}]},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/Equatable-Implementations":{"url":"\/documentation\/dotfacelite\/capturemode\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","type":"topic","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/init(rawValue:)":{"type":"topic","kind":"symbol","role":"symbol","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/init(rawValue:)","url":"\/documentation\/dotfacelite\/capturemode\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/waitForRequest":{"url":"\/documentation\/dotfacelite\/capturemode\/waitforrequest","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/waitForRequest","navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"kind":"symbol","title":"CaptureMode.waitForRequest","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}]},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"abstract":[{"type":"text","text":"Capture mode."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"title":"CaptureMode","url":"\/documentation\/dotfacelite\/capturemode","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/RawRepresentable-Implementations":{"url":"\/documentation\/dotfacelite\/capturemode\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","type":"topic","abstract":[]},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTCaptureMode","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/autoCapture","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/waitForRequest"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCaptureMode"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTCaptureModeAutoCapture","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1autoCapture\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1autoCapture\/fragments","value":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1waitForRequest\/title","value":"DOTCaptureModeWaitForRequest","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1waitForRequest\/fragments","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/navigatorTitle","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}