{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategory\/backgroundUniformity","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundUniformity","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategory"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryBackgroundUniformity"}],"title":"DotFaceModuleCategory.backgroundUniformity","role":"symbol","externalID":"c:@M@DotFaceCore@E@DotFaceModuleCategory@DotFaceModuleCategoryBackgroundUniformity","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/backgrounduniformity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/backgrounduniformity"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleCategory":{"navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"kind":"symbol","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" module category.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemodulecategory","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategory","title":"DotFaceModuleCategory","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleCategory/backgroundUniformity":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryBackgroundUniformity"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/backgrounduniformity","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategory\/backgroundUniformity","title":"DotFaceModuleCategory.backgroundUniformity","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceModuleCategoryBackgroundUniformity"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleCategoryBackgroundUniformity","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotFaceModuleCategoryBackgroundUniformity","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","value":"DotFaceModuleCategory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","value":[{"text":"DotFaceModuleCategory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategory~1backgroundUniformity\/title","value":"DotFaceModuleCategoryBackgroundUniformity","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategory~1backgroundUniformity\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleCategoryBackgroundUniformity"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}