{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/verification"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/verification"]},{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/verification"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"DotFaceModuleCategory.verification","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryVerification"}],"role":"symbol","externalID":"c:@M@DotFaceCore@E@DotFaceModuleCategory@DotFaceModuleCategoryVerification","symbolKind":"case"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/verification":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/verification","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/verification","title":"DotFaceModuleCategory.verification","role":"symbol","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verification"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryVerification"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"url":"\/documentation\/dotfacecore\/dotfacemodulecategory","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModuleCategory","kind":"identifier"}],"role":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" module category."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"title":"DotFaceModuleCategory","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DotFaceModuleCategoryVerification","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleCategoryVerification"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotFaceModuleCategoryVerification"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleCategoryVerification","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1verification\/title"},{"op":"replace","value":[{"text":"DotFaceModuleCategoryVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1verification\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","value":"DotFaceModuleCategory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","value":[{"text":"DotFaceModuleCategory","kind":"identifier"}]}]}]}