{"abstract":[{"text":"Face detection balanced module.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationBalanced"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationBalanced\/init"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacedetectionmoduleconfigurationbalanced"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfigurationBalanced","role":"symbol","fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"title":"DotFaceDetectionModuleConfigurationBalanced","navigatorTitle":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration","type":"topic","title":"DotFaceDetectionModuleConfiguration","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection module configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfigurationBalanced/init":{"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfigurationbalanced\/init","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationBalanced\/init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfigurationBalanced":{"abstract":[{"type":"text","text":"Face detection balanced module."}],"fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfigurationbalanced","role":"symbol","kind":"symbol","title":"DotFaceDetectionModuleConfigurationBalanced","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfigurationBalanced"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}