{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/!=(_:_:)"],"anchor":"Operators"}],"variants":[{"paths":["\/documentation\/dotnfc\/imageformat\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/Equatable-Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","type":"topic","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"title":"ImageFormat","url":"\/documentation\/dotnfc\/imageformat","role":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageFormat/!=(_:_:)":{"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/dotnfc\/imageformat\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"patch":[{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}