{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/imageformat\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/hashValue"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/RawRepresentable-Implementations"]]},"sections":[],"metadata":{"title":"hashValue","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"symbolKind":"property","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"DotNfc"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DOTImageFormat","role":"symbol"},"references":{"doc://DotNfc/documentation/DotNfc/ImageFormat/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/RawRepresentable-Implementations","url":"\/documentation\/dotnfc\/imageformat\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations","kind":"article"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotNfc/documentation/DotNfc/ImageFormat/hashValue":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"title":"hashValue","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/hashValue","url":"\/documentation\/dotnfc\/imageformat\/hashvalue","abstract":[]},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotnfc\/imageformat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","type":"topic","abstract":[{"text":"Supported image formats.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]}]}]}