{"variants":[{"paths":["\/documentation\/dotnfc\/imageformat\/jpeg2000"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imageformat\/jpeg2000"]}],"kind":"symbol","metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpeg2000"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNImageFormatJpeg2000"}],"role":"symbol","title":"ImageFormat.jpeg2000","roleHeading":"Case","externalID":"c:@M@DotNfc@E@DOTNImageFormat@DOTNImageFormatJpeg2000","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.0","unavailable":false}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg2000","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"JPEG2000","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}]}]}],"references":{"doc://DotNfc/documentation/DotNfc/ImageFormat/jpeg2000":{"abstract":[{"type":"text","text":"JPEG2000"}],"url":"\/documentation\/dotnfc\/imageformat\/jpeg2000","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg2000","navigatorTitle":[{"kind":"identifier","text":"DOTNImageFormatJpeg2000"}],"role":"symbol","type":"topic","title":"ImageFormat.jpeg2000","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotnfc\/imageformat","abstract":[{"type":"text","text":"Supported image formats."}],"role":"symbol","title":"ImageFormat"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNImageFormatJpeg2000"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNImageFormatJpeg2000"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTNImageFormatJpeg2000","kind":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg2000\/title","value":"DOTNImageFormatJpeg2000","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg2000\/fragments","value":[{"text":"DOTNImageFormatJpeg2000","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","value":"DOTNImageFormat","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNImageFormat"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}