{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat"]]},"abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"rawBgr","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The 3 bytes of color image pixel:"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"0th byte: BB - blue","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"1st byte: GG - green","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"2nd byte: RR - red","type":"text"}]}]}],"type":"unorderedList"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/imageformat\/rawbgr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/imageformat\/rawbgr"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","role":"symbol","title":"ImageFormat.rawBgr","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"roleHeading":"Case","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgr","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/rawBgr"},"references":{"doc://DotNfc/documentation/DotNfc/ImageFormat":{"abstract":[{"text":"Supported image formats.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotnfc\/imageformat","type":"topic","title":"ImageFormat","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageFormat/rawBgr":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}],"abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"role":"symbol","title":"ImageFormat.rawBgr","url":"\/documentation\/dotnfc\/imageformat\/rawbgr","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/rawBgr"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTImageFormatRawBgr"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/navigatorTitle","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1rawBgr\/title","op":"replace","value":"DOTImageFormatRawBgr"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1rawBgr\/fragments","op":"replace","value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}