{"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"createBgraRawImage(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithCgImage:","roleHeading":"Type Method"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"cgImage","content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}],"type":"paragraph"}]}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(cgImage:)"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(cgimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(cgimage:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgraRawImage(cgImage:)":{"url":"\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(cgimage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"title":"createBgraRawImage(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(cgImage:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory":{"url":"\/documentation\/dotfacecore\/imagefactory","abstract":[{"type":"text","text":"Create "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"title":"ImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}]},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"title":"Image","type":"topic","navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"createBgraRawImageWithCgImage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGImageRef","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createBgraRawImageWithCgImage:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(cgImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments"},{"value":"DOTImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"}]}]}