{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression\/init(eyes:mouth:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"eyes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EyesExpression","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression"},{"text":", ","kind":"text"},{"text":"mouth","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","text":"FaceAttribute"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/expression\/init(eyes:mouth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/expression\/init(eyes:mouth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression"]]},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpression(im)initWithEyes:mouth:","navigatorTitle":[{"kind":"identifier","text":"initWithEyes:mouth:"}],"roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"title":"init(eyes:mouth:)","symbolKind":"init","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eyes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyesExpression","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mouth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"?)"}]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"navigatorTitle":[{"kind":"identifier","text":"Expression"}],"url":"\/documentation\/dotfacecore\/expression","type":"topic","abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"role":"symbol","kind":"symbol","title":"Expression","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Expression"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","url":"\/documentation\/dotfacecore\/faceattribute","type":"topic","title":"FaceAttribute"},"doc://DotFaceCore/documentation/DotFaceCore/Expression/init(eyes:mouth:)":{"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/expression\/init(eyes:mouth:)","navigatorTitle":[{"text":"initWithEyes:mouth:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression\/init(eyes:mouth:)","role":"symbol","title":"init(eyes:mouth:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"eyes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EyesExpression","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"mouth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"type":"topic","abstract":[{"type":"text","text":"Eyes expression evaluation result."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/eyesexpression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}],"navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"title":"EyesExpression"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithEyes:mouth:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEyes:mouth:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithEyes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","text":"DOTFEyesExpression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"eyes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mouth:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mouth","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"kind":"identifier","text":"DOTFExpression"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/navigatorTitle","value":[{"text":"DOTFExpression","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression~1init(eyes:mouth:)\/title","value":"initWithEyes:mouth:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression~1init(eyes:mouth:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithEyes:mouth:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","value":"DOTFEyesExpression"},{"value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace"},{"value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/navigatorTitle","op":"replace"}]}]}