{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder\/minSharpness(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/builder\/minsharpness(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","role":"symbol","externalID":"s:11DotDocument0B37AutoCaptureQualityAttributeThresholdsC7BuilderC12minSharpnessyAE0A4Core13WrappedDoubleCSgKF","title":"minSharpness(_:)","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minSharpness","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minSharpness","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"minSharpness","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder","text":"Builder","preciseIdentifier":"s:11DotDocument0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"title":"DocumentAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds/Builder/minSharpness(_:)":{"title":"minSharpness(_:)","abstract":[],"url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/builder\/minsharpness(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minSharpness","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder\/minSharpness(_:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds/Builder":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"navigatorTitle":[{"kind":"identifier","text":"Builder"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/builder","kind":"symbol","title":"DocumentAutoCaptureQualityAttributeThresholds.Builder","role":"symbol"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"type":"topic","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"title":"WrappedDouble","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotdocument\/wrappeddouble"}},"variantOverrides":[{"patch":[{"value":"DOTDDocumentAutoCaptureQualityAttributeThresholds","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}