{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped\/phase"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturephase\/wrapped\/phase"]}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:14DotFingersCore0B16AutoCapturePhaseO7WrappedC5phaseACvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase"}],"title":"phase","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCapturePhase","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/Wrapped":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"kind":"symbol","role":"symbol","title":"FingersAutoCapturePhase.Wrapped","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/wrapped"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/Wrapped/phase":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/wrapped\/phase","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCapturePhase","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","kind":"typeIdentifier"}],"title":"phase","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped\/phase","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCapturePhase"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCapturePhase"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"type":"text","text":"Phase of the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","title":"FingersAutoCapturePhase","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title","value":"DOTFGFingersAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}