{"metadata":{"symbolKind":"property","platforms":[{"beta":false,"introducedAt":"13.0","deprecated":false,"unavailable":false,"name":"iOS"}],"role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lds1eMrtdApplication"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Lds1eMrtdApplication","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile(py)lds1eMrtdApplication","navigatorTitle":[{"kind":"identifier","text":"lds1eMrtdApplication"}],"title":"lds1eMrtdApplication"},"abstract":[{"text":"Raw LDS1 eMRTD application content.","type":"text"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/ldsmasterfile\/lds1emrtdapplication"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/ldsmasterfile\/lds1emrtdapplication"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/lds1eMrtdApplication"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"lds1eMrtdApplication","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","text":"Lds1eMrtdApplication","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile"]]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"title":"TravelDocument","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","type":"topic","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile/lds1eMrtdApplication":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"lds1eMrtdApplication","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication","text":"Lds1eMrtdApplication"}],"type":"topic","url":"\/documentation\/dotnfc\/ldsmasterfile\/lds1emrtdapplication","abstract":[{"text":"Raw LDS1 eMRTD application content.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile\/lds1eMrtdApplication","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"lds1eMrtdApplication"}],"title":"lds1eMrtdApplication"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LdsMasterFile"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"title":"LdsMasterFile","url":"\/documentation\/dotnfc\/ldsmasterfile","type":"topic","navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.7.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"role":"symbol","title":"Lds1eMrtdApplication","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"abstract":[{"text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication","type":"topic","navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"lds1eMrtdApplication","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"lds1eMrtdApplication","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication","text":"DOTNLds1eMrtdApplication"},{"text":" * ","kind":"text"},{"text":"lds1eMrtdApplication","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","value":"lds1eMrtdApplication","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1lds1eMrtdApplication\/title"},{"value":[{"kind":"identifier","text":"lds1eMrtdApplication"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile~1lds1eMrtdApplication\/fragments"},{"value":"DOTNLdsMasterFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","op":"replace","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}]},{"value":"DOTNLds1eMrtdApplication","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}