{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","text":"Configuration","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/init(configuration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/init(configuration:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/init(configuration:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Create new instance of "},{"type":"codeVoice","code":"DocumentAutoCaptureController"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureController(im)initWithConfiguration:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"text":")","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"title":"init(configuration:)","role":"symbol"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","title":"DocumentAutoCaptureController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/init(configuration:)":{"abstract":[{"type":"text","text":"Create new instance of "},{"type":"codeVoice","code":"DocumentAutoCaptureController"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/init(configuration:)","navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/init(configuration:)","title":"init(configuration:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration":{"fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration","type":"topic","title":"DOTDDocumentAutoCaptureControllerConfiguration","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithConfiguration:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureControllerConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1init(configuration:)\/title","op":"replace","value":"initWithConfiguration:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1init(configuration:)\/fragments"}]}]}