{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEnabled"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkLicenseProxyProtocol.isFaceEnabled"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceenabled"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"]]},"metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"title":"isFaceEnabled","externalID":"c:@M@DotPalmCore@objc(cs)DotSdkLicenseProxy(py)isFaceEnabled","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFaceEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"title":"isFaceEnabled"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isFaceEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isFaceEnabled","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEnabled"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DotSdkLicenseProxy","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/title"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceEnabled\/title","value":"isFaceEnabled","op":"replace"},{"value":[{"text":"isFaceEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceEnabled\/fragments","op":"replace"}]}]}