{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isnfcenabled"]},{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isnfcenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isNfcEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isNfcEnabled","navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DotSdkLicenseProxy(py)isNfcEnabled"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isNfcEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isNfcEnabled","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isNfcEnabled","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isNfcEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isNfcEnabled","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isnfcenabled","title":"isNfcEnabled","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"isNfcEnabled","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isNfcEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"isNfcEnabled","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isNfcEnabled\/title","value":"isNfcEnabled"},{"op":"replace","value":[{"text":"isNfcEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isNfcEnabled\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}