{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceLeftEdge"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/faceleftedge"]},{"paths":["\/documentation\/dotfacecore\/facefeature\/faceleftedge"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Case","symbolKind":"case","title":"FaceFeature.faceLeftEdge","externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureFaceLeftEdge","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"faceLeftEdge","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DOTFFaceFeatureFaceLeftEdge","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLeftEdge"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/faceLeftEdge":{"url":"\/documentation\/dotfacecore\/facefeature\/faceleftedge","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceLeftEdge","title":"FaceFeature.faceLeftEdge","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureFaceLeftEdge"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLeftEdge","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"abstract":[{"text":"Available face features.","type":"text"}],"role":"symbol","title":"FaceFeature","kind":"symbol","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeature"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"value":"DOTFFaceFeatureFaceLeftEdge","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFFaceFeatureFaceLeftEdge","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTFFaceFeatureFaceLeftEdge","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTFFaceFeatureFaceLeftEdge","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceLeftEdge\/title"},{"value":[{"text":"DOTFFaceFeatureFaceLeftEdge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceLeftEdge\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}