{"metadata":{"role":"symbol","title":"hash(into:)","extendedModule":"Swift","modules":[{"name":"DotDocument","relatedModules":["Swift"]}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotCore@E@DotFaceModuleId","roleHeading":"Instance Method","symbolKind":"method","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/hash(into:)"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/RawRepresentable-Implementations"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/hash(into:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/dotfacemoduleid\/hash(into:)","title":"hash(into:)","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/RawRepresentable-Implementations":{"type":"topic","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/rawrepresentable-implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/RawRepresentable-Implementations"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId":{"title":"DotFaceModuleId","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotdocument\/dotfacemoduleid","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/title","op":"replace","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/fragments","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/navigatorTitle","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}