{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/document","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotlibraryid\/document"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotlibraryid\/document"]}],"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"text":" identifier.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId"]]},"sections":[],"metadata":{"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdDocument","navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"DotFaceLite"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"document","kind":"identifier"}],"role":"symbol","title":"DotLibraryId.document"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/document":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/document","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdDocument"}],"type":"topic","kind":"symbol","title":"DotLibraryId.document","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"type":"text","text":" identifier."}],"url":"\/documentation\/dotfacelite\/dotlibraryid\/document","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"title":"DotLibraryId","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotfacelite\/dotlibraryid"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"text":"version: 8.9.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdDocument"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdDocument","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1document\/title","op":"replace","value":"DotLibraryIdDocument"},{"value":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1document\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]}]}]}