{"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector"],"generated":true,"title":"Non-UI components"}],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureController","role":"symbol","roleHeading":"Class","symbolKind":"class","modules":[{"name":"DotFaceLite"}],"title":"FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}]},"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller"]},{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceAutoCaptureController) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"languages":["swift"]}]}],"topicSections":[{"title":"Configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"],"title":"Face auto capture process"},{"title":"Validators","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]},{"title":"Classes","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/init(configuration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/configuration-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(bgraRawImage:timestampMillis:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(sample:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Error","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Phase"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DetectionPosition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"url":"\/documentation\/dotfacelite\/detectionposition","title":"DetectionPosition","kind":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.2.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceNotDetectedValidator":{"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceNotDetectedValidator"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","title":"FaceNotDetectedValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"abstract":[{"text":"Validates confidence of the detected face.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooLowValidator":{"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","title":"BrightnessTooLowValidator","role":"symbol","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"abstract":[{"text":"Validate minimum brightness of the detected face.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"title":"FaceAutoCaptureController","type":"topic","kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooLargeValidator":{"url":"\/documentation\/dotfacelite\/sizetoolargevalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SizeTooLargeValidator","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooLargeValidator","title":"SizeTooLargeValidator","role":"symbol","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Error":{"kind":"symbol","abstract":[],"title":"FaceAutoCaptureController.Error","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/error"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/configuration-swift.property":{"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC"}],"title":"configuration","type":"topic","abstract":[{"type":"text","text":"Current configuration."}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/configuration-swift.property"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"abstract":[{"type":"text","text":"The result returned from the processing of one image during the face auto capture process."}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","type":"topic","navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"title":"FaceAutoCaptureController.ProcessingResult"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooHighValidator":{"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","title":"BrightnessTooHighValidator","role":"symbol","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Validate maximum brightness of the detected face.","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","title":"FaceOutOfBoundsValidator","role":"symbol","navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Phase":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Phase","kind":"identifier"}],"role":"symbol","title":"FaceAutoCaptureController.Phase","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/phase","abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Phase","kind":"symbol","navigatorTitle":[{"text":"Phase","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","title":"FaceAutoCaptureDetectionValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"kind":"symbol","abstract":[{"text":"Use this protocol to create face validators.","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureResult":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","url":"\/documentation\/dotfacelite\/faceautocaptureresult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"title":"FaceAutoCaptureResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/process(sample:)":{"abstract":[{"text":"Process an input sample and update the state.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC6SampleC","text":"Sample","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult","kind":"typeIdentifier"}],"role":"symbol","title":"process(sample:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(sample:)","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"processWithSample:error:"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/process(sample:)"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/process(bgraRawImage:timestampMillis:)":{"deprecated":true,"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(bgraRawImage:timestampMillis:)","kind":"symbol","abstract":[{"text":"Process an input image or video frame and update the state.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/process(bgrarawimage:timestampmillis:)","role":"symbol","navigatorTitle":[{"text":"processWithBgraRawImage:timestampMillis:error:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"text":"timestampMillis","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"ProcessingResult","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC","kind":"typeIdentifier"}],"title":"process(bgraRawImage:timestampMillis:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"abstract":[{"text":"Information from the detection process about the detected face.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","title":"FaceAutoCaptureFrameParameters","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SharpnessTooLowValidator":{"url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","title":"SharpnessTooLowValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"abstract":[{"text":"Validate minimum sharpness of the detected face.","type":"text"}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacelite\/faceautocapturedetection","title":"FaceAutoCaptureDetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"title":"SizeTooSmallValidator","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","abstract":[{"type":"text","text":"Validate size of the detected face."}]},"doc://com.innovatrics.dot.face.lite/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Sample":{"abstract":[{"text":"The data sample captured at specific time which serves as an input for the face auto capture process.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sample"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample","title":"FaceAutoCaptureController.Sample","navigatorTitle":[{"kind":"identifier","text":"Sample"}]},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","role":"symbol","title":"FaceAutoCaptureController.Configuration","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/init(configuration:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/init(configuration:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/init(configuration:)","title":"init(configuration:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create new instance of "},{"type":"codeVoice","code":"FaceAutoCaptureController"},{"text":".","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Face auto capture process","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"]},{"title":"Validators","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/configuration-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/init(configuration:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(bgraRawImage:timestampMillis:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/process(sample:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector"],"generated":true,"title":"Non-UI components"}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DOTDetectionPosition","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/fragments"},{"value":"DOTFLFaceNotDetectedValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}],"op":"replace"},{"value":"DOTFLBrightnessTooLowValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","op":"replace"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","value":"DOTFLSizeTooLargeValidator"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1configuration-swift.property\/title","value":"configuration"},{"op":"replace","value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1configuration-swift.property\/fragments"},{"op":"replace","value":"DOTFLBrightnessTooHighValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","op":"replace","value":[{"text":"DOTFLBrightnessTooHighValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","op":"replace","value":"DOTFLFaceOutOfBoundsValidator"},{"op":"replace","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title","value":"DOTFLFaceAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}]},{"op":"replace","value":"DOTFLFaceAutoCaptureResult","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureResult"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","op":"replace"},{"op":"replace","value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace"},{"value":"processWithSample:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(sample:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(sample:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithSample:error:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/title","value":"processWithBgraRawImage:timestampMillis:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"processWithBgraRawImage:timestampMillis:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1process(bgraRawImage:timestampMillis:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","value":"DOTFLFaceAutoCaptureFrameParameters"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title","value":"DOTFLSharpnessTooLowValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTFLSharpnessTooLowValidator","kind":"identifier"}]},{"op":"replace","value":"DOTFLFaceAutoCaptureDetection","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"value":"DOTFLSizeTooSmallValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1init(configuration:)\/title","op":"replace","value":"initWithConfiguration:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1init(configuration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}