{"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/minconfidence:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"minConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTWrappedDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minConfidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"minConfidence:error:","kind":"identifier"}],"navigatorTitle":[{"text":"minConfidence:error:","kind":"identifier"}],"title":"minConfidence:error:","role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder(im)minConfidence:error:"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","title":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","abstract":[],"fragments":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder/minConfidence:error:":{"navigatorTitle":[{"kind":"identifier","text":"minConfidence:error:"}],"abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"minConfidence:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:","title":"minConfidence:error:","kind":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/minconfidence:error:","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","url":"\/documentation\/dotfacecore\/wrappeddouble","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"}]}]}