{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/minUniqueIntensityLevels:error:","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/minuniqueintensitylevels:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"minUniqueIntensityLevels:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"DOTWrappedDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"minUniqueIntensityLevels"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder(im)minUniqueIntensityLevels:error:","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"minUniqueIntensityLevels:error:"}],"title":"minUniqueIntensityLevels:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minUniqueIntensityLevels:error:"}],"role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder","abstract":[],"type":"topic","fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"}],"role":"symbol","title":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/wrappeddouble","title":"WrappedDouble"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder/minUniqueIntensityLevels:error:":{"url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/minuniqueintensitylevels:error:","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/minUniqueIntensityLevels:error:","role":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minUniqueIntensityLevels:error:"}],"navigatorTitle":[{"kind":"identifier","text":"minUniqueIntensityLevels:error:"}],"kind":"symbol","title":"minUniqueIntensityLevels:error:"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}