{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/pitchangleinterval:error:"]}],"metadata":{"title":"pitchAngleInterval:error:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"pitchAngleInterval:error:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"pitchAngleInterval:error:"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder(im)pitchAngleInterval:error:","symbolKind":"method","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/pitchAngleInterval:error:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"pitchAngleInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","text":"DOTIntervalFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat"},{"text":" *) ","kind":"text"},{"text":"pitchAngleInterval","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat":{"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"title":"IntervalFloat","url":"\/documentation\/dotfacecore\/intervalfloat","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder":{"type":"topic","abstract":[],"title":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder/pitchAngleInterval:error:":{"abstract":[],"navigatorTitle":[{"text":"pitchAngleInterval:error:","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"pitchAngleInterval:error:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/pitchangleinterval:error:","title":"pitchAngleInterval:error:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/pitchAngleInterval:error:","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/title"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/fragments"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/navigatorTitle"}]}]}