{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"yawAngleInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTIntervalFloat","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat"},{"text":" *) ","kind":"text"},{"text":"yawAngleInterval","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/yawangleinterval:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/yawAngleInterval:error:"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"kind":"symbol","metadata":{"title":"yawAngleInterval:error:","fragments":[{"text":"- ","kind":"text"},{"text":"yawAngleInterval:error:","kind":"identifier"}],"symbolKind":"method","navigatorTitle":[{"text":"yawAngleInterval:error:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder(im)yawAngleInterval:error:","modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Instance Method"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder":{"kind":"symbol","fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder","title":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder/yawAngleInterval:error:":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/yawAngleInterval:error:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"yawAngleInterval:error:"}],"role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"yawAngleInterval:error:"}],"title":"yawAngleInterval:error:","type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/yawangleinterval:error:"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat":{"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervalfloat","role":"symbol","kind":"symbol","title":"IntervalFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/navigatorTitle","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"}]}]}