{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError"]]},"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","title":"LocalizedError Implementations","roleHeading":"API Collection"},"kind":"article","topicSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/failureReason","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/helpAnchor","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/recoverySuggestion"],"anchor":"Instance-Properties","title":"Instance Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader\/readingerror\/localizederror-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/LocalizedError-Implementations"},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError/helpAnchor":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/helpAnchor","title":"helpAnchor","url":"\/documentation\/dotdocument\/mrzreader\/readingerror\/helpanchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError/recoverySuggestion":{"type":"topic","kind":"symbol","title":"recoverySuggestion","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/recoverySuggestion","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[],"url":"\/documentation\/dotdocument\/mrzreader\/readingerror\/recoverysuggestion"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReadingError","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError","title":"MrzReader.ReadingError","navigatorTitle":[{"text":"ReadingError","kind":"identifier"}],"abstract":[{"text":"Thrown if travel document type resolution, text recognition, or text parsing are unsuccessful.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/readingerror"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError/failureReason":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/failureReason","role":"symbol","kind":"symbol","title":"failureReason","url":"\/documentation\/dotdocument\/mrzreader\/readingerror\/failurereason","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}]}]}]}