{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Case","title":"FaceFeature.noseTip","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseTip"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature@DOTFFaceFeatureNoseTip","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"noseTip","kind":"identifier"}],"symbolKind":"case"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"noseTip"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeature\/nosetip"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature\/nosetip"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/noseTip"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature/noseTip":{"abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facefeature\/nosetip","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature\/noseTip","title":"FaceFeature.noseTip","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"noseTip","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFFaceFeatureNoseTip","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceFeature":{"abstract":[{"text":"Available face features.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceFeature","role":"symbol","url":"\/documentation\/dotfacecore\/facefeature","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"title":"FaceFeature"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceFeatureNoseTip"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureNoseTip"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTFFaceFeatureNoseTip"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1noseTip\/title","op":"replace","value":"DOTFFaceFeatureNoseTip"},{"op":"replace","value":[{"text":"DOTFFaceFeatureNoseTip","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature~1noseTip\/fragments"},{"op":"replace","value":"DOTFFaceFeature","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/title"},{"value":[{"text":"DOTFFaceFeature","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}