{"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentReaderPassword"},{"text":": ","kind":"text"},{"text":"TravelDocumentReaderPassword","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"travelDocumentReaderPassword"}],"modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocumentReaderPasswordWrapper(py)travelDocumentReaderPassword","title":"travelDocumentReaderPassword","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false,"unavailable":false}],"roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/traveldocumentreaderpassword"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/traveldocumentreaderpassword"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentReaderPassword"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","text":"TravelDocumentReaderPassword"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/travelDocumentReaderPassword","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper":{"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPasswordWrapper","kind":"identifier"}],"abstract":[],"title":"TravelDocumentReaderPasswordWrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","navigatorTitle":[{"text":"TravelDocumentReaderPasswordWrapper","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper/travelDocumentReaderPassword":{"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/traveldocumentreaderpassword","title":"travelDocumentReaderPassword","navigatorTitle":[{"kind":"identifier","text":"travelDocumentReaderPassword"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/travelDocumentReaderPassword","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"travelDocumentReaderPassword","kind":"identifier"},{"kind":"text","text":": "},{"text":"TravelDocumentReaderPassword","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"abstract":[{"type":"text","text":"Password for accessing the chip."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","type":"topic","title":"TravelDocumentReaderPassword","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"role":"symbol","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"travelDocumentReaderPassword","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"travelDocumentReaderPassword","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<DOTNTravelDocumentReaderPassword>","preciseIdentifier":"c:Qo@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"travelDocumentReaderPassword"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNTravelDocumentReaderPasswordWrapper","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/title"},{"value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPasswordWrapper"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1travelDocumentReaderPassword\/title","value":"travelDocumentReaderPassword","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1travelDocumentReaderPassword\/fragments","value":[{"text":"travelDocumentReaderPassword","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","value":"DOTNTravelDocumentReaderPassword"},{"value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments"}]}]}