{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules\/initWithBarcode:"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithBarcode:"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(im)initWithBarcode:","symbolKind":"method","role":"symbol","title":"initWithBarcode:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcode:"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBarcode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfigurationModules":{"url":"\/documentation\/dotdocument\/dotdocumentlibraryconfigurationmodules","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules","title":"DotDocumentLibraryConfigurationModules","abstract":[{"text":"Document library module configuration.","type":"text"}],"fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfigurationModules/initWithBarcode:":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules\/initWithBarcode:","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcode:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBarcode:"}],"type":"topic","kind":"symbol","role":"symbol","title":"initWithBarcode:"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentBarcodeModuleConfiguration":{"abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"type":"topic","role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"url":"\/documentation\/dotdocument\/dotdocumentbarcodemoduleconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentBarcodeModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/title"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"}]}]}