{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/palm","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"codeVoice","code":"DotPalmLibrary"},{"type":"text","text":" identifier."}],"metadata":{"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdPalm","role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"title":"DotLibraryId.palm"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/palm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/palm"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"type":"topic","title":"DotLibraryId","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/palm":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotlibraryid\/palm","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/palm","title":"DotLibraryId.palm","kind":"symbol","abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdPalm"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdPalm","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/navigatorTitle"},{"value":"DotLibraryIdPalm","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1palm\/title"},{"value":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId~1palm\/fragments"}]}]}