{"variants":[{"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(bgrrawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(bgrrawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(bgrRawImage:)"},"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Type Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"title":"createBgraRawImage(bgrRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithBgrRawImage:","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object with a "},{"code":".rawBgr","type":"codeVoice"},{"type":"text","text":" format. Terminates if the passed image is not in the correct format."}]}],"name":"bgrRawImage"}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" instance.","type":"text"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgr"},{"type":"text","text":" format as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"references":{"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgraRawImage(bgrRawImage:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(bgrrawimage:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgr"},{"type":"text","text":" format as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(bgrRawImage:)","title":"createBgraRawImage(bgrRawImage:)"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Image":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","title":"Image","url":"\/documentation\/dotnfc\/image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"},"doc://DotNfc/documentation/DotNfc/ImageFactory":{"url":"\/documentation\/dotnfc\/imagefactory","title":"ImageFactory","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory","abstract":[{"type":"text","text":"Create "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBgraRawImageWithBgrRawImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bgrRawImage","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"bgrRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with a "},{"type":"codeVoice","code":".rawBgr"},{"type":"text","text":" format. Terminates if the passed image is not in the correct format."}]}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" instance.","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title","value":"createBgraRawImageWithBgrRawImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"}]}]}