{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = Defaults.minFaceSizeRatio, "},{"kind":"externalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" = Defaults.maxFaceSizeRatio, "},{"kind":"externalParam","text":"isCheckAnimationEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isCheckAnimationEnabled, "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraFacing","text":"CameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"kind":"externalParam","text":"qualityAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute","text":"QualityAttribute"},{"kind":"text","text":"> = MatchingQualityProvider().getQualityAttributes())"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureconfiguration\/init(minfacesizeratio:maxfacesizeratio:ischeckanimationenabled:camerafacing:camerapreviewscaletype:qualityattributes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureconfiguration\/init(minfacesizeratio:maxfacesizeratio:ischeckanimationenabled:camerafacing:camerapreviewscaletype:qualityattributes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/init(minFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isCheckAnimationEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"qualityAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute"},{"kind":"text","text":">)"}],"title":"init(minFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFaceAutoCaptureConfiguration(im)initWithMinFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration":{"role":"symbol","title":"FaceAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/init(minFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:)":{"role":"symbol","title":"init(minFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isCheckAnimationEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraPreviewScaleType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"qualityAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/init(minFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMinFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/init(minfacesizeratio:maxfacesizeratio:ischeckanimationenabled:camerafacing:camerapreviewscaletype:qualityattributes:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute":{"role":"symbol","title":"QualityAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}],"url":"\/documentation\/dotfacecore\/qualityattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.10.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"role":"symbol","title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacecore\/camerafacing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMinFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinFaceSizeRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"minFaceSizeRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxFaceSizeRatio:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":")"},{"kind":"internalParam","text":"maxFaceSizeRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCheckAnimationEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isCheckAnimationEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraFacing","text":"DOTFCameraFacing"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFCameraPreviewScaleType","text":"DOTFCameraPreviewScaleType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAttributes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSet<DOTQualityAttribute *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"qualityAttributes"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/title","value":"DOTFaceAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration~1init(minFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:)\/title","value":"initWithMinFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration~1init(minFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinFaceSizeRatio:maxFaceSizeRatio:isCheckAnimationEnabled:cameraFacing:cameraPreviewScaleType:qualityAttributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/title","value":"DOTQualityAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTFCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTFCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTFCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTFCameraFacing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}