{"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkError.internalError","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/internalError"},"kind":"symbol","metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotNfc"}],"symbolKind":"property","title":"internalError","externalID":"s:6DotNfc27MachineReadableZonePasswordC5ErrorO08internalG0sAD_pSgvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}]},"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"]]},"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"MachineReadableZonePassword.Error"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"title":"MachineReadableZonePassword"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/internalError":{"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/internalerror","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/internalError","title":"internalError","kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"DOTNMachineReadableZonePassword","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}