{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/none"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/loggerloglevel\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/loggerloglevel\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}]}],"metadata":{"symbolKind":"case","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelNone","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"role":"symbol","title":"LoggerLogLevel.none","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"modules":[{"name":"DotFaceLite"}]},"kind":"symbol","abstract":[{"type":"text","text":"Disables logging."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel/none":{"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel\/none","url":"\/documentation\/dotfacelite\/loggerloglevel\/none","abstract":[{"type":"text","text":"Disables logging."}],"type":"topic","title":"LoggerLogLevel.none"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel":{"url":"\/documentation\/dotfacelite\/loggerloglevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","abstract":[{"text":"Available log levels.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTLoggerLogLevelNone","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTLoggerLogLevelNone","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1none\/title","op":"replace"},{"value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel~1none\/fragments","op":"replace"},{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/title","op":"replace"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments","op":"replace"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}