{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory"]]},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"ciImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}]}]},{"name":"ciContext","content":[{"inlineContent":[{"type":"text","text":"CIContext."}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"]}],"sections":[],"metadata":{"roleHeading":"Type Method","externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithCiImage:ciContext:","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"title":"createBgraRawImage(ciImage:ciContext:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/ImageFactory":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"type":"topic","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"url":"\/documentation\/dotnfc\/imagefactory","title":"ImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"text":" as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","role":"symbol","title":"createBgraRawImage(ciImage:ciContext:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"},"doc://DotNfc/documentation/DotNfc/Image":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","type":"topic","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/image"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBgraRawImageWithCiImage:ciContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" *) ","kind":"text"},{"text":"createBgraRawImageWithCiImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":" *) ","kind":"text"},{"text":"ciImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"ciImage","content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"type":"paragraph"}]},{"name":"ciContext","content":[{"type":"paragraph","inlineContent":[{"text":"CIContext.","type":"text"}]}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/navigatorTitle","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title","value":"createBgraRawImageWithCiImage:ciContext:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}