{"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotsdk\/configuration\/init(licensebytes:libraries:transactioncountingtoken:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","text":"Libraries","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration\/init(licenseBytes:libraries:transactionCountingToken:)","interfaceLanguage":"swift"},"metadata":{"title":"init(licenseBytes:libraries:transactionCountingToken:)","externalID":"s:7DotCore0A3SdkC13ConfigurationC12licenseBytes9libraries24transactionCountingTokenAE10Foundation4DataV_AA9LibrariesCSSSgtcfc","roleHeading":"Initializer","modules":[{"name":"DotNfc"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Libraries","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"},{"text":", ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"role":"symbol"},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotSdk/Configuration/init(licenseBytes:libraries:transactionCountingToken:)":{"url":"\/documentation\/dotnfc\/dotsdk\/configuration\/init(licensebytes:libraries:transactioncountingtoken:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration\/init(licenseBytes:libraries:transactionCountingToken:)","title":"init(licenseBytes:libraries:transactionCountingToken:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Libraries","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"},{"text":", ","kind":"text"},{"text":"transactionCountingToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"kind":"symbol","title":"Libraries","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"url":"\/documentation\/dotnfc\/libraries","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotSdk":{"role":"symbol","kind":"symbol","title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"url":"\/documentation\/dotnfc\/dotsdk","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]},"doc://DotNfc/documentation/DotNfc/DotSdk/Configuration":{"url":"\/documentation\/dotnfc\/dotsdk\/configuration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Configuration","title":"DotSdk.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}