{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"RectangleDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/mirrored()"},"kind":"symbol","metadata":{"role":"symbol","extendedModule":"DotCore","title":"mirrored()","modules":[{"name":"DotFaceLite","relatedModules":["DotCore"]}],"roleHeading":"Instance Method","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(im)mirrored","navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/dotfacelite\/rectangledouble\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/rectangledouble\/mirrored()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacelite\/facedetector"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","url":"\/documentation\/dotfacelite\/rectangledouble","kind":"symbol","role":"symbol","title":"RectangleDouble","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble/mirrored()":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/mirrored()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/mirrored()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"title":"mirrored()","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"mirrored"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1mirrored()\/title","value":"mirrored"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1mirrored()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]}]}]}