{"metadata":{"modules":[{"name":"DotFaceLite","relatedModules":["DotCore"]}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zeroRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(cpy)zeroRectangle","roleHeading":"Type Property","title":"zeroRectangle","extendedModule":"DotCore","symbolKind":"property","navigatorTitle":[{"text":"zeroRectangle","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/zeroRectangle"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/rectangledouble\/zerorectangle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/rectangledouble\/zerorectangle"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"title":"RectangleDouble","kind":"symbol","url":"\/documentation\/dotfacelite\/rectangledouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","role":"symbol","type":"topic","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"url":"\/documentation\/dotfacelite\/facedetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","kind":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble/zeroRectangle":{"abstract":[],"type":"topic","title":"zeroRectangle","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble\/zeroRectangle","kind":"symbol","url":"\/documentation\/dotfacelite\/rectangledouble\/zerorectangle","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zeroRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"zeroRectangle","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"zeroRectangle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"zeroRectangle","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"zeroRectangle"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1zeroRectangle\/title","value":"zeroRectangle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble~1zeroRectangle\/fragments","value":[{"kind":"identifier","text":"zeroRectangle"}]}]}]}