{"abstract":[{"type":"text","text":"Available face features."}],"kind":"symbol","metadata":{"role":"symbol","title":"FaceFeature","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceFeature","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DOTFFaceFeature","roleHeading":"Enumeration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFFaceFeature) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/facefeature"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeature"]}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceChinTip","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceLeftEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceRightEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeCenter","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeInnerCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeOuterCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowInnerEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowOuterEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthCenter","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLeftCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLowerEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthRightCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthUpperEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseBottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseLeftBottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseRightBottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseRoot","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseTip","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeCenter","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeInnerCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeOuterCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowInnerEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowOuterEdge"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/description"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH","doc:\/\/com.innovatrics.dot.face.core\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthUpperEdge":{"title":"FaceFeature.mouthUpperEdge","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthUpperEdge","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthUpperEdge"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/facefeature\/mouthupperedge","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthUpperEdge"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/noseRoot":{"url":"\/documentation\/dotfacecore\/facefeature\/noseroot","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseRoot","title":"FaceFeature.noseRoot","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRoot"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseRoot","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyeCenter":{"role":"symbol","url":"\/documentation\/dotfacecore\/facefeature\/righteyecenter","navigatorTitle":[{"text":"DOTFFaceFeatureRightEyeCenter","kind":"identifier"}],"title":"FaceFeature.rightEyeCenter","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeCenter","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeCenter","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyeInnerCorner":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeInnerCorner","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeInnerCorner"}],"navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyeInnerCorner","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature\/lefteyeinnercorner","abstract":[],"role":"symbol","type":"topic","title":"FaceFeature.leftEyeInnerCorner","kind":"symbol"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/dotfacecore\/facefeature\/rawrepresentable-implementations","kind":"article","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"title":"RawRepresentable Implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/Equatable-Implementations":{"url":"\/documentation\/dotfacecore\/facefeature\/equatable-implementations","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyeOuterCorner":{"url":"\/documentation\/dotfacecore\/facefeature\/righteyeoutercorner","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeOuterCorner","title":"FaceFeature.rightEyeOuterCorner","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyeOuterCorner"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeOuterCorner","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/description":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacecore\/facefeature\/description","title":"description","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/description","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/noseRightBottom":{"url":"\/documentation\/dotfacecore\/facefeature\/noserightbottom","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseRightBottom","title":"FaceFeature.noseRightBottom","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRightBottom"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseRightBottom","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyeCenter":{"role":"symbol","title":"FaceFeature.leftEyeCenter","abstract":[],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyeCenter"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeCenter","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeCenter","url":"\/documentation\/dotfacecore\/facefeature\/lefteyecenter"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/faceChinTip":{"title":"FaceFeature.faceChinTip","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceChinTip","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"faceChinTip","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureFaceChinTip"}],"type":"topic","url":"\/documentation\/dotfacecore\/facefeature\/facechintip"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/noseBottom":{"url":"\/documentation\/dotfacecore\/facefeature\/nosebottom","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseBottom","title":"FaceFeature.noseBottom","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseBottom"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseBottom","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyeInnerCorner":{"url":"\/documentation\/dotfacecore\/facefeature\/righteyeinnercorner","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeInnerCorner","title":"FaceFeature.rightEyeInnerCorner","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyeInnerCorner"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyeInnerCorner","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyebrowInnerEdge":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowInnerEdge","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyebrowInnerEdge","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFFaceFeatureRightEyebrowInnerEdge","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature\/righteyebrowinneredge","abstract":[],"role":"symbol","type":"topic","title":"FaceFeature.rightEyebrowInnerEdge","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/faceLeftEdge":{"url":"\/documentation\/dotfacecore\/facefeature\/faceleftedge","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceLeftEdge","title":"FaceFeature.faceLeftEdge","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureFaceLeftEdge"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLeftEdge","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"abstract":[{"text":"Available face features.","type":"text"}],"role":"symbol","title":"FaceFeature","kind":"symbol","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceFeature"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyebrowInnerEdge":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowInnerEdge","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"leftEyebrowInnerEdge","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyebrowInnerEdge","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facefeature\/lefteyebrowinneredge","abstract":[],"role":"symbol","type":"topic","title":"FaceFeature.leftEyebrowInnerEdge","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthCenter":{"navigatorTitle":[{"text":"DOTFFaceFeatureMouthCenter","kind":"identifier"}],"title":"FaceFeature.mouthCenter","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthCenter","kind":"symbol","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facefeature\/mouthcenter","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"mouthCenter","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/noseTip":{"url":"\/documentation\/dotfacecore\/facefeature\/nosetip","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseTip","title":"FaceFeature.noseTip","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureNoseTip"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"noseTip","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyeOuterCorner":{"url":"\/documentation\/dotfacecore\/facefeature\/lefteyeoutercorner","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeOuterCorner","title":"FaceFeature.leftEyeOuterCorner","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyeOuterCorner"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeOuterCorner","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthRightCorner":{"url":"\/documentation\/dotfacecore\/facefeature\/mouthrightcorner","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthRightCorner","title":"FaceFeature.mouthRightCorner","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthRightCorner"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthRightCorner","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/init(rawValue:)":{"url":"\/documentation\/dotfacecore\/facefeature\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/init(rawValue:)","title":"init(rawValue:)","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthLowerEdge":{"url":"\/documentation\/dotfacecore\/facefeature\/mouthloweredge","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLowerEdge","title":"FaceFeature.mouthLowerEdge","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthLowerEdge"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthLowerEdge","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/noseLeftBottom":{"role":"symbol","abstract":[],"type":"topic","kind":"symbol","title":"FaceFeature.noseLeftBottom","navigatorTitle":[{"text":"DOTFFaceFeatureNoseLeftBottom","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"noseLeftBottom"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseLeftBottom","url":"\/documentation\/dotfacecore\/facefeature\/noseleftbottom"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/leftEyebrowOuterEdge":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyebrowOuterEdge","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFFaceFeatureLeftEyebrowOuterEdge","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowOuterEdge","url":"\/documentation\/dotfacecore\/facefeature\/lefteyebrowouteredge","title":"FaceFeature.leftEyebrowOuterEdge","kind":"symbol"},"doc://com.innovatrics.dot.face.core/SY":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/mouthLeftCorner":{"abstract":[],"role":"symbol","kind":"symbol","title":"FaceFeature.mouthLeftCorner","navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureMouthLeftCorner"}],"url":"\/documentation\/dotfacecore\/facefeature\/mouthleftcorner","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouthLeftCorner","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLeftCorner"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/rightEyebrowOuterEdge":{"url":"\/documentation\/dotfacecore\/facefeature\/righteyebrowouteredge","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowOuterEdge","title":"FaceFeature.rightEyebrowOuterEdge","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureRightEyebrowOuterEdge"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightEyebrowOuterEdge","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature/faceRightEdge":{"url":"\/documentation\/dotfacecore\/facefeature\/facerightedge","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceRightEdge","title":"FaceFeature.faceRightEdge","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DOTFFaceFeatureFaceRightEdge"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceRightEdge","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTFFaceFeature"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"DOTFFaceFeature","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceChinTip","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceLeftEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/faceRightEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeCenter","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeInnerCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyeOuterCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowInnerEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/leftEyebrowOuterEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthCenter","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLeftCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthLowerEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthRightCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/mouthUpperEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseBottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseLeftBottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseRightBottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseRoot","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/noseTip","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeCenter","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeInnerCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyeOuterCorner","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowInnerEdge","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature\/rightEyebrowOuterEdge"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFFaceFeature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"DOTFFaceFeatureMouthUpperEdge","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthUpperEdge\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthUpperEdge\/fragments","value":[{"text":"DOTFFaceFeatureMouthUpperEdge","kind":"identifier"}]},{"value":"DOTFFaceFeatureNoseRoot","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseRoot\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRoot"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseRoot\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeCenter\/title","op":"replace","value":"DOTFFaceFeatureRightEyeCenter"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeCenter\/fragments","op":"replace","value":[{"text":"DOTFFaceFeatureRightEyeCenter","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeInnerCorner\/title","value":"DOTFFaceFeatureLeftEyeInnerCorner"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeInnerCorner\/fragments","op":"replace","value":[{"text":"DOTFFaceFeatureLeftEyeInnerCorner","kind":"identifier"}]},{"value":"DOTFFaceFeatureRightEyeOuterCorner","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeOuterCorner\/title","op":"replace"},{"value":[{"text":"DOTFFaceFeatureRightEyeOuterCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeOuterCorner\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseRightBottom\/title","value":"DOTFFaceFeatureNoseRightBottom","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseRightBottom\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureNoseRightBottom"}]},{"op":"replace","value":"DOTFFaceFeatureLeftEyeCenter","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeCenter\/title"},{"op":"replace","value":[{"text":"DOTFFaceFeatureLeftEyeCenter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeCenter\/fragments"},{"op":"replace","value":"DOTFFaceFeatureFaceChinTip","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceChinTip\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceFeatureFaceChinTip"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceChinTip\/fragments"},{"value":"DOTFFaceFeatureNoseBottom","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseBottom\/title"},{"value":[{"text":"DOTFFaceFeatureNoseBottom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseBottom\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeInnerCorner\/title","value":"DOTFFaceFeatureRightEyeInnerCorner"},{"value":[{"text":"DOTFFaceFeatureRightEyeInnerCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyeInnerCorner\/fragments"},{"value":"DOTFFaceFeatureRightEyebrowInnerEdge","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowInnerEdge\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowInnerEdge\/fragments","value":[{"text":"DOTFFaceFeatureRightEyebrowInnerEdge","kind":"identifier"}]},{"value":"DOTFFaceFeatureFaceLeftEdge","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceLeftEdge\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceLeftEdge\/fragments","value":[{"text":"DOTFFaceFeatureFaceLeftEdge","kind":"identifier"}]},{"op":"replace","value":"DOTFFaceFeature","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceFeature"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments"},{"value":"DOTFFaceFeatureLeftEyebrowInnerEdge","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowInnerEdge\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowInnerEdge\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowInnerEdge"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthCenter\/title","value":"DOTFFaceFeatureMouthCenter","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthCenter\/fragments","value":[{"text":"DOTFFaceFeatureMouthCenter","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseTip\/title","value":"DOTFFaceFeatureNoseTip"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseTip\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureNoseTip"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeOuterCorner\/title","value":"DOTFFaceFeatureLeftEyeOuterCorner","op":"replace"},{"value":[{"text":"DOTFFaceFeatureLeftEyeOuterCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyeOuterCorner\/fragments"},{"value":"DOTFFaceFeatureMouthRightCorner","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthRightCorner\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthRightCorner\/fragments","value":[{"text":"DOTFFaceFeatureMouthRightCorner","kind":"identifier"}]},{"value":"DOTFFaceFeatureMouthLowerEdge","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLowerEdge\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLowerEdge\/fragments","value":[{"text":"DOTFFaceFeatureMouthLowerEdge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseLeftBottom\/title","value":"DOTFFaceFeatureNoseLeftBottom"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1noseLeftBottom\/fragments","value":[{"kind":"identifier","text":"DOTFFaceFeatureNoseLeftBottom"}]},{"value":"DOTFFaceFeatureLeftEyebrowOuterEdge","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowOuterEdge\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureLeftEyebrowOuterEdge"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1leftEyebrowOuterEdge\/fragments"},{"value":"DOTFFaceFeatureMouthLeftCorner","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLeftCorner\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1mouthLeftCorner\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceFeatureMouthLeftCorner"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowOuterEdge\/title","value":"DOTFFaceFeatureRightEyebrowOuterEdge","op":"replace"},{"value":[{"text":"DOTFFaceFeatureRightEyebrowOuterEdge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1rightEyebrowOuterEdge\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceRightEdge\/title","value":"DOTFFaceFeatureFaceRightEdge"},{"value":[{"text":"DOTFFaceFeatureFaceRightEdge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature~1faceRightEdge\/fragments"}]}]}