{"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","type":"conformsTo"}],"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/init(left:top:right:bottom:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/bottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/cgRect","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/hash","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/height","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/left","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/points","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/right","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/top","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/width"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/mirrored()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/fullRectangle"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/from(cgRect:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTRectangleDouble) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"title":"RectangleDouble","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTRectangleDouble","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangledouble"]},{"paths":["\/documentation\/dotfacecore\/rectangledouble"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/isEqual(_:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/isEqual(_:)","url":"\/documentation\/dotfacecore\/rectangledouble\/isequal(_:)","kind":"symbol","type":"topic","abstract":[],"title":"isEqual(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/fullRectangle":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"fullRectangle","kind":"identifier"}],"abstract":[],"title":"fullRectangle","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/fullRectangle","url":"\/documentation\/dotfacecore\/rectangledouble\/fullrectangle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullRectangle","kind":"identifier"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/top":{"title":"top","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/top","url":"\/documentation\/dotfacecore\/rectangledouble\/top","kind":"symbol","role":"symbol","abstract":[{"text":"Top edge.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"top"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/points":{"title":"points","url":"\/documentation\/dotfacecore\/rectangledouble\/points","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/points","role":"symbol","navigatorTitle":[{"text":"points","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTPointDouble"},{"text":"]","kind":"text"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/bottom":{"title":"bottom","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotfacecore\/rectangledouble\/bottom","kind":"symbol","abstract":[{"type":"text","text":"Bottom edge."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/bottom"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/init(left:top:right:bottom:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/rectangledouble\/init(left:top:right:bottom:)","navigatorTitle":[{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"title":"init(left:top:right:bottom:)","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/init(left:top:right:bottom:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"left","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"top"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"right"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/height":{"type":"topic","title":"height","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/height","url":"\/documentation\/dotfacecore\/rectangledouble\/height","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"height"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/left":{"title":"left","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/left","url":"\/documentation\/dotfacecore\/rectangledouble\/left","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Left edge."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"left","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/from(cgRect:)":{"navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/from(cgRect:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTRectangleDouble"}],"title":"from(cgRect:)","url":"\/documentation\/dotfacecore\/rectangledouble\/from(cgrect:)","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble","url":"\/documentation\/dotfacecore\/rectangledouble","kind":"symbol","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/right":{"type":"topic","title":"right","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/right","url":"\/documentation\/dotfacecore\/rectangledouble\/right","role":"symbol","abstract":[{"text":"Right edge.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"right","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/mirrored()":{"title":"mirrored()","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/mirrored()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTRectangleDouble"}],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/rectangledouble\/mirrored()","type":"topic","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/rebased(parentRectangle:)":{"type":"topic","title":"rebased(parentRectangle:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/rebased(parentRectangle:)","url":"\/documentation\/dotfacecore\/rectangledouble\/rebased(parentrectangle:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"kind":"text","text":"("},{"text":"parentRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTRectangleDouble"}],"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/hash":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"hash","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/hash","abstract":[],"role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/rectangledouble\/hash","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/description":{"url":"\/documentation\/dotfacecore\/rectangledouble\/description","title":"description","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/description"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/width":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotfacecore\/rectangledouble\/width","navigatorTitle":[{"kind":"identifier","text":"width"}],"title":"width","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/width","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/RectangleDouble/cgRect":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"url":"\/documentation\/dotfacecore\/rectangledouble\/cgrect","title":"cgRect","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/cgRect","navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTRectangleDouble"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/bottom","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/cgRect","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/hash","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/height","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/left","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/points","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/right","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/top","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/width"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/init(left:top:right:bottom:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/mirrored()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/rebased(parentRectangle:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/fullRectangle"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/RectangleDouble\/from(cgRect:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTRectangleDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1isEqual(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"value":"fullRectangle","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1fullRectangle\/title"},{"value":[{"kind":"identifier","text":"fullRectangle"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1fullRectangle\/fragments","op":"replace"},{"value":"top","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1top\/title","op":"replace"},{"value":[{"kind":"identifier","text":"top"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1top\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1points\/title","value":"points","op":"replace"},{"op":"replace","value":[{"text":"points","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1points\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1bottom\/title","value":"bottom","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1bottom\/fragments","value":[{"text":"bottom","kind":"identifier"}],"op":"replace"},{"value":"initWithLeft:top:right:bottom:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1init(left:top:right:bottom:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1init(left:top:right:bottom:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}]},{"op":"replace","value":"height","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1height\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1height\/fragments","op":"replace","value":[{"text":"height","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1left\/title","value":"left","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1left\/fragments","op":"replace","value":[{"text":"left","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1from(cgRect:)\/title","value":"fromCgRect:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromCgRect:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1from(cgRect:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble\/fragments","op":"replace"},{"value":"right","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1right\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1right\/fragments","value":[{"text":"right","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1mirrored()\/title","value":"mirrored"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1mirrored()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1rebased(parentRectangle:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1hash\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1description\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1width\/title","op":"replace","value":"width"},{"value":[{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1width\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1cgRect\/title","value":"cgRect","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1RectangleDouble~1cgRect\/fragments","value":[{"text":"cgRect","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}