{"variants":[{"paths":["\/documentation\/dotfacecore\/validationfloat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/validationfloat"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTValidationFloat) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationFloat","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"]}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValidationFloat\/validate(value:interval:)"],"title":"Type Methods"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValidationFloat"},"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ValidationFloat"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ValidationFloat"}],"title":"ValidationFloat","externalID":"c:@M@DotFaceCore@objc(cs)DOTValidationFloat","role":"symbol"},"references":{"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ValidationFloat/validate(value:interval:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/validationfloat\/validate(value:interval:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalFloat","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValidationFloat\/validate(value:interval:)","title":"validate(value:interval:)","role":"symbol"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ValidationFloat":{"abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"navigatorTitle":[{"text":"ValidationFloat","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/validationfloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationFloat","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValidationFloat","title":"ValidationFloat","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTValidationFloat"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTValidationFloat"}]},{"value":[{"kind":"identifier","text":"DOTValidationFloat"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ValidationFloat\/validate(value:interval:)"]}]},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTValidationFloat","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"validateWithValue:interval:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ValidationFloat~1validate(value:interval:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ValidationFloat~1validate(value:interval:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ValidationFloat\/title","value":"DOTValidationFloat","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ValidationFloat\/fragments","value":[{"kind":"identifier","text":"DOTValidationFloat"}],"op":"replace"}]}]}