{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class","preciseIdentifier":"s:11DotFaceCore8TemplateC7VersionC","text":"Version"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/template\/version-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/template\/version-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/version-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Template version."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Version","preciseIdentifier":"s:11DotFaceCore8TemplateC7VersionC"}],"title":"version","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTTemplate(py)version","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"version"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/version-swift.property":{"role":"symbol","title":"version","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Version","preciseIdentifier":"s:11DotFaceCore8TemplateC7VersionC"}],"abstract":[{"type":"text","text":"Template version."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/version-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"version"}],"url":"\/documentation\/dotfacecore\/template\/version-swift.property"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"role":"symbol","title":"TemplateMatcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplateMatcher"}],"abstract":[{"type":"text","text":"Stateless class which can match templates."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}],"url":"\/documentation\/dotfacecore\/templatematcher"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"role":"symbol","title":"Template","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Template"}],"abstract":[{"type":"text","text":"Face template."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Template"}],"url":"\/documentation\/dotfacecore\/template"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class":{"role":"symbol","title":"Template.Version","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Version"}],"abstract":[{"type":"text","text":"Template compatibility version."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Version"}],"url":"\/documentation\/dotfacecore\/template\/version-swift.class"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTTemplateVersion":{"role":"symbol","title":"DOTTemplateVersion","fragments":[{"kind":"identifier","text":"DOTTemplateVersion"}],"abstract":[{"type":"text","text":"Template compatibility version."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTTemplateVersion","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dottemplateversion"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"version"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"version"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTTemplateVersion","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTTemplateVersion","text":"DOTTemplateVersion"},{"kind":"text","text":" * "},{"kind":"identifier","text":"version"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template~1version-swift.property\/title","value":"version"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template~1version-swift.property\/fragments","value":[{"kind":"identifier","text":"version"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTTemplateMatcher"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"kind":"identifier","text":"DOTTemplateMatcher"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","value":"DOTTemplate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments","value":[{"kind":"identifier","text":"DOTTemplate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}