{"metadata":{"symbolKind":"init","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessResult(im)initWithImage:face:content:","roleHeading":"Initializer","title":"init(image:face:content:)","navigatorTitle":[{"kind":"identifier","text":"initWithImage:face:content:"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult\/init(image:face:content:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessresult\/init(image:face:content:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessresult\/init(image:face:content:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","type":"topic","kind":"symbol","fragments":[{"text":"Face","kind":"identifier"}],"abstract":[{"text":"Detected face in the image.","type":"text"}],"title":"Face","role":"symbol","url":"\/documentation\/dotfacecore\/face"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"url":"\/documentation\/dotfacecore\/facedetector","type":"topic","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessResult/init(image:face:content:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(image:face:content:)","navigatorTitle":[{"text":"initWithImage:face:content:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessresult\/init(image:face:content:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult\/init(image:face:content:)","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"title":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","type":"topic","url":"\/documentation\/dotfacecore\/image","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessResult":{"navigatorTitle":[{"text":"MultiRangeLivenessResult","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult","type":"topic","title":"MultiRangeLivenessResult","url":"\/documentation\/dotfacecore\/multirangelivenessresult","abstract":[{"text":"The final result of the Multi-Range Liveness process.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessResult","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"url":"\/documentation\/dotfacecore\/facedetector\/face","navigatorTitle":[{"text":"Face","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","kind":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"title":"FaceDetector.Face","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImage:face:content:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:content:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Face","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult~1init(image:face:content:)\/title","value":"initWithImage:face:content:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult~1init(image:face:content:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:face:content:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult\/title","value":"DOTFMultiRangeLivenessResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult\/navigatorTitle","value":[{"text":"DOTFMultiRangeLivenessResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}