{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:)"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(im)initWithModules:","title":"init(modules:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"abstract":[{"type":"text","text":"Face library configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","role":"symbol","type":"topic","title":"DotFaceLibraryConfiguration","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules":{"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"abstract":[{"text":"Face library module configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","role":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/init(modules:)":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:)","kind":"symbol","title":"init(modules:)","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Face library module configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","role":"symbol","type":"topic","title":"DotFaceLibraryConfiguration.Modules","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithModules:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"text":"initWithModules:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules","text":"DotFaceLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules"},{"kind":"text","text":" *) "},{"text":"modules","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}