{"variants":[{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/issuingauthority"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/issuingauthority"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"issuingAuthority","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails(py)issuingAuthority","role":"symbol"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/issuingAuthority","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingAuthority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Issuing Authority."}],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/issuingAuthority":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/issuingAuthority","kind":"symbol","title":"issuingAuthority","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingAuthority"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"text":"issuingAuthority","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails\/issuingauthority","abstract":[{"type":"text","text":"Issuing Authority."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"url":"\/documentation\/dotnfc\/additionaldocumentdetails","kind":"symbol","type":"topic","title":"AdditionalDocumentDetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}],"abstract":[{"text":"Contents of DG12 - Additional document details.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"issuingAuthority","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"issuingAuthority"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"issuingAuthority","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"issuingAuthority","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1issuingAuthority\/title"},{"op":"replace","value":[{"text":"issuingAuthority","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1issuingAuthority\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","op":"replace","value":"DOTNAdditionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/navigatorTitle","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}