{"kind":"symbol","abstract":[{"type":"text","text":"License data."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkConfiguration\/licenseBytes"},"metadata":{"modules":[{"name":"DotDocument"}],"title":"licenseBytes","navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DotSdkConfiguration(py)licenseBytes","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/licensebytes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/licensebytes"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkConfiguration"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkConfiguration/licenseBytes":{"kind":"symbol","abstract":[{"type":"text","text":"License data."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"title":"licenseBytes","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkConfiguration\/licenseBytes","url":"\/documentation\/dotdocument\/dotsdkconfiguration\/licensebytes","navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","role":"collection","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkConfiguration":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"url":"\/documentation\/dotdocument\/dotsdkconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkConfiguration","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"title":"DotSdkConfiguration","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"licenseBytes","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"licenseBytes","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"licenseBytes"}]}]},"path":"\/primaryContentSections\/0"},{"value":"licenseBytes","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkConfiguration~1licenseBytes\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkConfiguration~1licenseBytes\/fragments","op":"replace","value":[{"text":"licenseBytes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkConfiguration\/title","op":"replace","value":"DotSdkConfiguration"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkConfiguration\/fragments","value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"op":"replace"}]}]}