{"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","symbolKind":"method","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithLicenseBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"libraries","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transactionCountingToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transactionCountingToken","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration"]]},"variants":[{"paths":["\/documentation\/dotnfc\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/DotSdkConfiguration/initWithLicenseBytes:libraries:transactionCountingToken:":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:","abstract":[],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:"},"doc://DotNfc/documentation/DotNfc/Libraries":{"url":"\/documentation\/dotnfc\/libraries","role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"title":"Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdkConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}],"abstract":[{"text":"The ","type":"text"},{"text":"DotSdk","type":"text"},{"text":" configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotsdkconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration","title":"DotSdkConfiguration"}},"variantOverrides":[{"patch":[{"value":"Libraries","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}