{"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/hashValue"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/hash(into:)"],"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"API Collection","modules":[{"name":"DotFaceCore"}],"role":"collectionGroup","title":"RawRepresentable Implementations"},"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/placeholdertype\/rawrepresentable-implementations"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/hashValue":{"role":"symbol","url":"\/documentation\/dotfacecore\/placeholdertype\/hashvalue","abstract":[],"kind":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"title":"hashValue","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/hashValue"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","abstract":[{"type":"text","text":"Type of placeholder."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotfacecore\/placeholdertype","kind":"symbol","role":"symbol","title":"PlaceholderType"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType/hash(into:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/placeholdertype\/hash(into:)","abstract":[],"kind":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"title":"hash(into:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType\/hash(into:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/title","value":"DOTPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPlaceholderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}