{"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCorners) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/corners"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/corners"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"symbolKind":"class","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@objc(cs)DOTCorners","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"title":"Corners"},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomLeft","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomRight","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/points","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topLeft","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topRight"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/isEqual(_:)","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/mirrored()","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/from(rectangle:)"],"title":"Type Methods"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","title":"Conforms To"}],"references":{"doc://DotNfc/documentation/DotNfc/Corners/from(rectangle:)":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/from(rectangle:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rectangle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"url":"\/documentation\/dotnfc\/corners\/from(rectangle:)","title":"from(rectangle:)","navigatorTitle":[{"text":"fromRectangle:","kind":"identifier"}]},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/Corners/bottomRight":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Bottom right corner point."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomRight","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"url":"\/documentation\/dotnfc\/corners\/bottomright","title":"bottomRight","navigatorTitle":[{"kind":"identifier","text":"bottomRight"}]},"doc://DotNfc/documentation/DotNfc/Corners/mirrored()":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/mirrored()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/corners\/mirrored()","title":"mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Corners/topLeft":{"role":"symbol","kind":"symbol","abstract":[{"text":"Top left corner point.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topLeft","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"}],"url":"\/documentation\/dotnfc\/corners\/topleft","title":"topLeft","navigatorTitle":[{"text":"topLeft","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Corners/rebased(parentRectangle:)":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/rebased(parentRectangle:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners"}],"url":"\/documentation\/dotnfc\/corners\/rebased(parentrectangle:)","title":"rebased(parentRectangle:)","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}]},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/Corners/points":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/points","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"text":": [","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/dotnfc\/corners\/points","title":"points","navigatorTitle":[{"text":"points","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/Corners":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"title":"Corners","url":"\/documentation\/dotnfc\/corners","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"},"doc://DotNfc/documentation/DotNfc/Corners/isEqual(_:)":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/dotnfc\/corners\/isequal(_:)","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/Corners/topRight":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Top right corner point."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topRight","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"},{"text":": ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/corners\/topright","title":"topRight","navigatorTitle":[{"text":"topRight","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","url":"\/documentation\/dotnfc\/corners\/init(topleft:topright:bottomright:bottomleft:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomLeft"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/Corners/hash":{"kind":"symbol","url":"\/documentation\/dotnfc\/corners\/hash","abstract":[],"title":"hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://DotNfc/documentation/DotNfc/Corners/description":{"role":"symbol","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotnfc\/corners\/description","title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotNfc/documentation/DotNfc/Corners/bottomLeft":{"title":"bottomLeft","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"abstract":[{"text":"Bottom left corner point.","type":"text"}],"url":"\/documentation\/dotnfc\/corners\/bottomleft","navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomLeft"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTCorners","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomLeft","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomRight","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/points","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topLeft","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topRight"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/isEqual(_:)","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/mirrored()","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/from(rectangle:)"],"title":"Type Methods"}]},{"value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTCorners"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"fromRectangle:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1from(rectangle:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1from(rectangle:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1bottomRight\/title","value":"bottomRight"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1bottomRight\/fragments","value":[{"text":"bottomRight","kind":"identifier"}]},{"value":"mirrored","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1mirrored()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mirrored"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1mirrored()\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1topLeft\/title","value":"topLeft","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1topLeft\/fragments","value":[{"kind":"identifier","text":"topLeft"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1rebased(parentRectangle:)\/title","op":"replace","value":"rebasedWithParentRectangle:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1rebased(parentRectangle:)\/fragments"},{"value":"points","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1points\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1points\/fragments","op":"replace","value":[{"kind":"identifier","text":"points"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title","value":"DOTCorners","op":"replace"},{"value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1topRight\/title","value":"topRight"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1topRight\/fragments","value":[{"text":"topRight","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}]},{"value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1hash\/title","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1hash\/fragments"},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1description\/title","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1description\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1bottomLeft\/title","value":"bottomLeft","op":"replace"},{"op":"replace","value":[{"text":"bottomLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1bottomLeft\/fragments"}]}]}