{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzstringposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzstringposition"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/endIndex","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/lineIndex","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/startIndex"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/isEqual(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTMrzStringPosition) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"metadata":{"role":"symbol","modules":[{"name":"DotNfc"}],"title":"MrzStringPosition","roleHeading":"Class","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzStringPosition","kind":"identifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition"},"references":{"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/endIndex":{"navigatorTitle":[{"kind":"identifier","text":"endIndex"}],"role":"symbol","url":"\/documentation\/dotnfc\/mrzstringposition\/endindex","type":"topic","abstract":[{"text":"An index of the last character in the MRZ line.","type":"text"}],"title":"endIndex","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"endIndex"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/endIndex"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"url":"\/documentation\/dotnfc\/mrzstringposition","title":"MrzStringPosition","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/startIndex":{"navigatorTitle":[{"kind":"identifier","text":"startIndex"}],"role":"symbol","abstract":[{"type":"text","text":"An index of the first character in the MRZ line."}],"type":"topic","url":"\/documentation\/dotnfc\/mrzstringposition\/startindex","title":"startIndex","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"startIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/startIndex"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/lineIndex":{"navigatorTitle":[{"text":"lineIndex","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzstringposition\/lineindex","title":"lineIndex","abstract":[{"type":"text","text":"An index of the line in MRZ."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lineIndex"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/lineIndex"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/hash":{"type":"topic","url":"\/documentation\/dotnfc\/mrzstringposition\/hash","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/hash","kind":"symbol","title":"hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/init(lineIndex:startIndex:endIndex:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithLineIndex:startIndex:endIndex:"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/mrzstringposition\/init(lineindex:startindex:endindex:)","title":"init(lineIndex:startIndex:endIndex:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"lineIndex","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"startIndex"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"endIndex","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/description":{"url":"\/documentation\/dotnfc\/mrzstringposition\/description","title":"description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/isEqual(_:)":{"abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/isEqual(_:)","title":"isEqual(_:)","url":"\/documentation\/dotnfc\/mrzstringposition\/isequal(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTMrzStringPosition","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/endIndex","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/lineIndex","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/startIndex"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/init(lineIndex:startIndex:endIndex:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/isEqual(_:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTMrzStringPosition","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1endIndex\/title","value":"endIndex"},{"value":[{"kind":"identifier","text":"endIndex"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1endIndex\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title","value":"DOTMrzStringPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1startIndex\/title","value":"startIndex"},{"value":[{"kind":"identifier","text":"startIndex"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1startIndex\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1lineIndex\/title","value":"lineIndex"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1lineIndex\/fragments","value":[{"text":"lineIndex","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1hash\/title","value":"hash"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1init(lineIndex:startIndex:endIndex:)\/title","value":"initWithLineIndex:startIndex:endIndex:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1init(lineIndex:startIndex:endIndex:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithLineIndex:startIndex:endIndex:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1isEqual(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}