{"variants":[{"paths":["\/documentation\/dotpalmcore\/camerapreviewscaletype\/fit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/camerapreviewscaletype\/fit"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fit"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"case","title":"CameraPreviewScaleType.fit","roleHeading":"Case","externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fit"},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType/fit":{"type":"topic","abstract":[{"type":"text","text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds."},{"type":"text","text":" "},{"type":"text","text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process."}],"navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"kind":"symbol","title":"CameraPreviewScaleType.fit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype\/fit","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType\/fit"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","type":"topic","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"kind":"symbol","title":"CameraPreviewScaleType"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTCameraPreviewScaleTypeFit","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCameraPreviewScaleTypeFit","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType~1fit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType~1fit\/fragments","op":"replace"},{"value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}