{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointer"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrarawimage\/bytespointer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bgrarawimage\/bytespointer"]}],"sections":[],"metadata":{"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)bytesPointer","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","role":"symbol","title":"bytesPointer","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"type":"topic","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"role":"symbol","url":"\/documentation\/dotfacelite\/facedetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"title":"FaceDetector","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 8.14.0"}],"title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage/bytesPointer":{"abstract":[],"title":"bytesPointer","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytesPointer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":">","kind":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointer","url":"\/documentation\/dotfacelite\/bgrarawimage\/bytespointer","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"title":"BgraRawImage","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"bytesPointer","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"bytesPointer"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bytesPointer"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"op":"replace","value":"bytesPointer","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage~1bytesPointer\/title"},{"value":[{"kind":"identifier","text":"bytesPointer"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage~1bytesPointer\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace"}]}]}