{"abstract":[{"text":"Do not use this, use ","type":"text"},{"type":"codeVoice","code":"BgraRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgraRawImage"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage"],["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage"]]},"metadata":{"role":"symbol","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage(im)initWithBytesPointer:size:","title":"init(bytesPointer:size:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageSize","text":"ImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrarawimage\/init(bytespointer:size:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bgrarawimage\/init(bytespointer:size:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/init(bytesPointer:size:)"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"kind":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","title":"BgraRawImage","url":"\/documentation\/dotfacelite\/bgrarawimage"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage/init(bytesPointer:size:)":{"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgraRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":"."}],"role":"symbol","title":"init(bytesPointer:size:)","navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":">, "},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ImageSize","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/bgrarawimage\/init(bytespointer:size:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/init(bytesPointer:size:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"version: 8.3.0","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ImageSize":{"kind":"symbol","url":"\/documentation\/dotfacelite\/imagesize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"role":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageSize","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"type":"topic","title":"ImageSize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithBytesPointer:size:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBytesPointer:size:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bytesPointer"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageSize","text":"DOTImageSize","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"value":"DOTFLFaceDetector","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace"},{"value":"initWithBytesPointer:size:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1init(bytesPointer:size:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1init(bytesPointer:size:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageSize\/fragments"}]}]}