{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","title":"isEqual(_:)","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(im)isEqual:"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/isEqual(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone"]]},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone/isEqual(_:)":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/isEqual(_:)","url":"\/documentation\/dotdocument\/td1machinereadablezone\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","title":"Td1MachineReadableZone","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"kind":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"title":"MrzReader","type":"topic","role":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/navigatorTitle","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","value":[{"text":"DOTDMrzReader","kind":"identifier"}]}]}]}