{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/localization\/uselocalizationdictionary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/localization\/uselocalizationdictionary"]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFLocalization(cpy)useLocalizationDictionary","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"useLocalizationDictionary","symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"roleHeading":"Type Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"If you set this to "},{"type":"codeVoice","code":"true"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizationDictionary"},{"type":"text","text":" will be used to localize strings. Default value is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization\/useLocalizationDictionary","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Localization/useLocalizationDictionary":{"kind":"symbol","url":"\/documentation\/dotfacecore\/localization\/uselocalizationdictionary","abstract":[{"text":"If you set this to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", ","type":"text"},{"code":"localizationDictionary","type":"codeVoice"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","title":"useLocalizationDictionary","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization\/useLocalizationDictionary"},"doc://DotFaceCore/documentation/DotFaceCore/Localization":{"url":"\/documentation\/dotfacecore\/localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"title":"Localization","type":"topic","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"useLocalizationDictionary"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"useLocalizationDictionary","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization~1useLocalizationDictionary\/title","op":"replace","value":"useLocalizationDictionary"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization~1useLocalizationDictionary\/fragments","op":"replace","value":[{"text":"useLocalizationDictionary","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/title","op":"replace","value":"DOTFLocalization"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/fragments","op":"replace","value":[{"text":"DOTFLocalization","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/navigatorTitle","op":"replace","value":[{"text":"DOTFLocalization","kind":"identifier"}]}]}]}