{"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.property"]}],"abstract":[{"type":"text","text":"Current style."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"style","kind":"identifier"}],"title":"style","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC5StyleC"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController(py)style","symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC5StyleC","text":"Style"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/style-swift.property"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/style-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"style"}],"title":"style","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC5StyleC"}],"abstract":[{"text":"Current style.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/style-swift.property","kind":"symbol","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Style-swift.class":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"title":"FaceAutoCaptureViewController.Style","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"abstract":[{"text":"Customization options for the face auto capture user interface.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"title":"FaceAutoCaptureViewController"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureStyle":{"title":"DOTFFaceAutoCaptureStyle","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotffaceautocapturestyle","abstract":[{"type":"text","text":"Customization options for the face auto capture user interface."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureStyle","kind":"symbol","fragments":[{"text":"DOTFFaceAutoCaptureStyle","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.14.0"}],"role":"collection","title":"DotFaceCore","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"style","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureStyle","text":"DOTFFaceAutoCaptureStyle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureStyle","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"style","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1style-swift.property\/title","op":"replace","value":"style"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1style-swift.property\/fragments","value":[{"text":"style","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]}]}]}