{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/init(rawValue:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","externalID":"s:7DotCore0A16DocumentModuleIdO8rawValueACSgSi_tcfc","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Initializer"},"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentmoduleid\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId":{"url":"\/documentation\/dotdocument\/dotdocumentmoduleid","abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId","title":"DotDocumentModuleId","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentModuleId/init(rawValue:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"title":"init(rawValue:)","url":"\/documentation\/dotdocument\/dotdocumentmoduleid\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentModuleId\/init(rawValue:)"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotDocumentModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/title"},{"op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/fragments"},{"op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}