{"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezone\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/hash"]}],"metadata":{"title":"hash","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone(py)hash","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotNfc"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/hash"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone"]]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"kind":"symbol","type":"topic","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/hash":{"title":"hash","role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/machinereadablezone\/hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone":{"title":"MachineReadableZone","role":"symbol","type":"topic","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotnfc\/machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"hash","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1hash\/title","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1hash\/fragments"},{"value":"DOTMachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}