{"abstract":[{"text":"Disables logging.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacecore\/loggerloglevel\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel\/none"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/LoggerLogLevel"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"metadata":{"externalID":"c:@M@DotFaceCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelNone","modules":[{"name":"DotFaceCore"}],"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"title":"LoggerLogLevel.none","roleHeading":"Case","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/LoggerLogLevel\/none"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/LoggerLogLevel":{"title":"LoggerLogLevel","abstract":[{"type":"text","text":"Available log levels."}],"url":"\/documentation\/dotfacecore\/loggerloglevel","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/LoggerLogLevel/none":{"abstract":[{"text":"Disables logging.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"none"}],"role":"symbol","url":"\/documentation\/dotfacecore\/loggerloglevel\/none","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/LoggerLogLevel\/none","kind":"symbol","title":"LoggerLogLevel.none","type":"topic","navigatorTitle":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.3.1"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevelNone"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTLoggerLogLevel","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1LoggerLogLevel\/title"},{"op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1LoggerLogLevel\/fragments"},{"value":"DOTLoggerLogLevelNone","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1LoggerLogLevel~1none\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1LoggerLogLevel~1none\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}