{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone"]]},"kind":"symbol","metadata":{"symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)dateOfExpiry","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfExpiry"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"}],"title":"dateOfExpiry"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfExpiry"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/dateofexpiry"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/dateofexpiry"]}],"references":{"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","title":"Td1MachineReadableZone","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotDocument","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","type":"topic","title":"MrzDateElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"text":" with parsed ","type":"text"},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone/dateOfExpiry":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfExpiry","url":"\/documentation\/dotdocument\/td1machinereadablezone\/dateofexpiry","title":"dateOfExpiry"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","title":"MrzReader","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"dateOfExpiry","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"dateOfExpiry","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":" * "},{"text":"dateOfExpiry","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTTd1MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace"},{"value":"DOTMrzDateElementWithCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1dateOfExpiry\/title","value":"dateOfExpiry","op":"replace"},{"value":[{"text":"dateOfExpiry","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1dateOfExpiry\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]}]}]}