{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"FaceAutoCaptureResult"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"title":"result","externalID":"s:11DotFaceLite0B21AutoCaptureControllerC16ProcessingResultC6resultAA0bdeH0CSgvp","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult"]]},"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult\/result"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult\/result","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","kind":"typeIdentifier","text":"FaceAutoCaptureResult"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol","kind":"symbol","type":"topic","title":"FaceAutoCaptureController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult/result":{"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult\/result","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult\/result","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"role":"symbol","title":"result","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"FaceAutoCaptureResult"},{"kind":"text","text":"?"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"role":"symbol","title":"FaceAutoCaptureResult","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureresult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/ProcessingResult":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/ProcessingResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"abstract":[{"type":"text","text":"The result returned from the processing of one image during the face auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/processingresult","role":"symbol","type":"topic","title":"FaceAutoCaptureController.ProcessingResult","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","value":"DOTFLFaceAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}