{"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/passiveLiveness","interfaceLanguage":"occ"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/passiveliveness"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"identifier","text":"passiveLiveness"}],"title":"passiveLiveness","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)passiveLiveness","symbolKind":"property","role":"symbol","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"passiveLiveness"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules","title":"DotFaceLibraryConfigurationModules","type":"topic","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration":{"type":"topic","title":"DotFacePassiveLivenessModuleConfiguration","url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration","role":"symbol","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Face passive liveness module."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfigurationModules/passiveLiveness":{"kind":"symbol","title":"passiveLiveness","abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfigurationModules\/passiveLiveness","url":"\/documentation\/dotnfc\/dotfacelibraryconfigurationmodules\/passiveliveness","fragments":[{"kind":"identifier","text":"passiveLiveness"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/title","op":"replace","value":"DotFacePassiveLivenessModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}