{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules\/detection","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"detection","fragments":[{"text":"detection","kind":"identifier"}],"symbolKind":"property","navigatorTitle":[{"text":"detection","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)detection","modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Instance Property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfigurationModules/detection":{"abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules\/detection","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules\/detection","title":"detection","fragments":[{"text":"detection","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersDetectionModuleConfiguration":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration","kind":"symbol","title":"DotFingersDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfigurationModules":{"kind":"symbol","fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules","title":"DotFingersLibraryConfigurationModules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules","abstract":[{"type":"text","text":"Fingers library module configuration."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}