{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:transformation:"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(im)initWithDetection:transformation:","role":"symbol","title":"initWithDetection:transformation:","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"initWithDetection:transformation:","kind":"identifier"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transformation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"transformation"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersTransformationModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotfingerstransformationmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"kind":"symbol","navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"title":"DotFingersTransformationModuleConfiguration","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfigurationModules":{"kind":"symbol","fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules","title":"DotFingersLibraryConfigurationModules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules","abstract":[{"type":"text","text":"Fingers library module configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfigurationModules/initWithDetection:transformation:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:transformation:","kind":"identifier"}],"type":"topic","role":"symbol","title":"initWithDetection:transformation:","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","navigatorTitle":[{"text":"initWithDetection:transformation:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersDetectionModuleConfiguration":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration","kind":"symbol","title":"DotFingersDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]}},"variantOverrides":[{"patch":[{"value":"DotFingersTransformationModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFingersDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}