{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules"]]},"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)transformation","fragments":[{"text":"transformation","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"transformation"}],"symbolKind":"property","title":"transformation"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules\/transformation"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules\/transformation","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersTransformationModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotfingerstransformationmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"kind":"symbol","navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"title":"DotFingersTransformationModuleConfiguration","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfigurationModules":{"kind":"symbol","fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules","title":"DotFingersLibraryConfigurationModules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules","abstract":[{"type":"text","text":"Fingers library module configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfigurationModules/transformation":{"kind":"symbol","fragments":[{"text":"transformation","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules\/transformation","title":"transformation","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules\/transformation","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/title","op":"replace","value":"DotFingersTransformationModuleConfiguration"},{"value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}