{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/maxpenaltythreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/maxpenaltythreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/maxPenaltyThreshold"},"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"maxPenaltyThreshold","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPenaltyThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDoesNotFitPlaceholderValidator(py)maxPenaltyThreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxPenaltyThreshold"}]},"abstract":[{"type":"text","text":"Current maximal penalty threshold. Penalty value is low when detected document is well aligned with placeholder and vice versa."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPenaltyThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/maxPenaltyThreshold":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/maxPenaltyThreshold","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/maxpenaltythreshold","abstract":[{"type":"text","text":"Current maximal penalty threshold. Penalty value is low when detected document is well aligned with placeholder and vice versa."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxPenaltyThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"maxPenaltyThreshold","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"maxPenaltyThreshold"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"DocumentDoesNotFitPlaceholderValidator"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"maxPenaltyThreshold","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"maxPenaltyThreshold"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"maxPenaltyThreshold","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"maxPenaltyThreshold","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1maxPenaltyThreshold\/title"},{"value":[{"kind":"identifier","text":"maxPenaltyThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1maxPenaltyThreshold\/fragments"},{"value":"DOTDDocumentDoesNotFitPlaceholderValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title"},{"value":[{"text":"DOTDDocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}