{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/validate(documentAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDoesNotFitPlaceholderValidator(im)validateWithDocumentAutoCaptureFrameParameters:","symbolKind":"method","role":"symbol","title":"validate(documentAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method"},"abstract":[{"text":"Validate position of the detected document relative to the placeholder.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Frame parameters to validate.","type":"text"}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" to indicate that the detected document does not fit the placeholder."}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/validate(documentAutoCaptureFrameParameters:)":{"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/validate(documentautocaptureframeparameters:)","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/validate(documentAutoCaptureFrameParameters:)","title":"validate(documentAutoCaptureFrameParameters:)","abstract":[{"text":"Validate position of the detected document relative to the placeholder.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"DocumentDoesNotFitPlaceholderValidator"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentAutoCaptureFrameParameters","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DOTDDocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}],"name":"documentAutoCaptureFrameParameters"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" to indicate that the detected document does not fit the placeholder.","type":"text"}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","value":"DOTDDocumentDoesNotFitPlaceholderValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}