{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class","text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration(im)initWithModules:","title":"init(modules:)","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"modules":[{"name":"DotNfc"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/init(modules:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/init(modules:)"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration","type":"topic","title":"DotFingersLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/init(modules:)":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/init(modules:)","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"kind":"symbol","title":"init(modules:)","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/init(modules:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfigurationModules":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules","role":"symbol","fragments":[{"kind":"identifier","text":"DotFingersLibraryConfigurationModules"}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfigurationmodules","type":"topic","title":"DotFingersLibraryConfigurationModules","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class","type":"topic","title":"DotFingersLibraryConfiguration.Modules","kind":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithModules:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithModules:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithModules:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules","kind":"typeIdentifier","text":"DotFingersLibraryConfigurationModules"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/title","op":"replace","value":"DotFingersLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration~1init(modules:)\/title","op":"replace","value":"initWithModules:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration~1init(modules:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]}]}]}