{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","title":"DotFingersLibraryConfiguration.Modules","roleHeading":"Class","modules":[{"name":"DotNfc"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DotFingersLibraryConfigurationModules) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration"]]},"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"kind":"symbol","topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation"]}],"references":{"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/detection","abstract":[],"title":"detection"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class","type":"topic","title":"DotFingersLibraryConfiguration.Modules","kind":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"text":", ","kind":"text"},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","title":"init(detection:transformation:)","role":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)","abstract":[],"kind":"symbol"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration","type":"topic","title":"DotFingersLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","title":"transformation","role":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]}]}]}