{"variants":[{"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator\/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/identifier","interfaceLanguage":"swift"},"metadata":{"title":"identifier","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotValidValidator(py)identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator/identifier":{"type":"topic","title":"identifier","kind":"symbol","url":"\/documentation\/dotdocument\/mrznotvalidvalidator\/identifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/identifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","url":"\/documentation\/dotdocument\/mrznotvalidvalidator","title":"MrzNotValidValidator","kind":"symbol","abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNotValidValidator","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"identifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTDMrzNotValidValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}]}]}]}