{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/validate(documentAutoCaptureFrameParameters:)"},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotValidValidator(im)validateWithDocumentAutoCaptureFrameParameters:","navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"title":"validate(documentAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator\/validate(documentautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator\/validate(documentautocaptureframeparameters:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Validate MRZ on the detected document.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Frame parameters to validate."}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" for document with invalid MRZ. If MRZ is not present returns ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"paragraph"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"title":"DocumentAutoCaptureFrameParameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator/validate(documentAutoCaptureFrameParameters:)":{"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/validate(documentAutoCaptureFrameParameters:)","url":"\/documentation\/dotdocument\/mrznotvalidvalidator\/validate(documentautocaptureframeparameters:)","title":"validate(documentAutoCaptureFrameParameters:)","kind":"symbol","abstract":[{"text":"Validate MRZ on the detected document.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","url":"\/documentation\/dotdocument\/mrznotvalidvalidator","title":"MrzNotValidValidator","kind":"symbol","abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNotValidValidator","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"Frame parameters to validate.","type":"text"}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" for document with invalid MRZ. If MRZ is not present returns "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle"},{"op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTDMrzNotValidValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/navigatorTitle","value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}]}]}]}