{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captured"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sample"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC11PhotoSampleC","kind":"typeIdentifier","text":"PhotoSample"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"sample","content":[{"type":"paragraph","inlineContent":[{"text":"Captured photo sample. Terminates if ","type":"text"},{"type":"codeVoice","code":"sample.image"},{"text":" property is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}]}]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Call this method once a "},{"type":"codeVoice","code":"ProcessingResult"},{"type":"text","text":" returned from "},{"type":"codeVoice","code":"process(sample:)"},{"type":"text","text":" contains the "},{"type":"codeVoice","code":".captureDepth"},{"type":"text","text":" event."},{"type":"text","text":" "},{"type":"text","text":"The fingers auto capture outcome continues to be delivered through subsequent "},{"type":"codeVoice","code":"process(sample:)"},{"type":"text","text":" calls."}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error if you call this method after the fingers auto capture process has finished."}]}],"name":"Throws","style":"note","type":"aside"}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/captured(sample:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/captured(sample:)"]}],"metadata":{"title":"captured(sample:)","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureController(im)capturedWithSample:error:","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captured","kind":"identifier"},{"kind":"text","text":"("},{"text":"sample","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC11PhotoSampleC","kind":"typeIdentifier","text":"PhotoSample"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"capturedWithSample:error:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"Process a captured photo sample with depth in response to a "},{"type":"codeVoice","code":".captureDepth"},{"type":"text","text":" event and update the state."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/captured(sample:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"role":"symbol","title":"FingersAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureController"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/captured(sample:)":{"role":"symbol","title":"captured(sample:)","navigatorTitle":[{"text":"capturedWithSample:error:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/captured(sample:)","abstract":[{"text":"Process a captured photo sample with depth in response to a ","type":"text"},{"code":".captureDepth","type":"codeVoice"},{"text":" event and update the state.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captured","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PhotoSample","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC11PhotoSampleC"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/captured(sample:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample":{"title":"FingersAutoCaptureController.PhotoSample","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PhotoSample"}],"type":"topic","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"type":"codeVoice","code":".captureDepth"},{"type":"text","text":" event during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerPhotoSample":{"kind":"symbol","title":"DOTFGFingersAutoCaptureControllerPhotoSample","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerphotosample","fragments":[{"text":"DOTFGFingersAutoCaptureControllerPhotoSample","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"type":"text","text":".captureDepth"},{"type":"text","text":" event during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"capturedWithSample:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"capturedWithSample:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"capturedWithSample:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerPhotoSample","text":"DOTFGFingersAutoCaptureControllerPhotoSample","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerPhotoSample"},{"text":" *) ","kind":"text"},{"text":"sample","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"sample","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Captured photo sample. Terminates if "},{"type":"codeVoice","code":"sample.image"},{"type":"text","text":" property is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"YES"},{"type":"text","text":" if the method succeeded, otherwise "},{"type":"codeVoice","code":"NO"},{"type":"text","text":"."}]}],"kind":"content"},"op":"add","path":"\/primaryContentSections\/2"},{"value":"DOTFGFingersAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title"},{"value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle"},{"value":"capturedWithSample:error:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1captured(sample:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"capturedWithSample:error:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1captured(sample:)\/fragments"}]}]}