{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"]]},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError","doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/s5ErrorP","doc:\/\/DotFingersCore\/s8SendableP","doc:\/\/DotFingersCore\/s16SendableMetatypeP"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"FingersAutoCaptureController.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"symbolKind":"enum","externalID":"s:14DotFingersCore0B21AutoCaptureControllerC5ErrorO","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"languages":["swift"]}]}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/capturedSampleFailed(internalError:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/processSampleFailed(internalError:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/errorMessage","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/internalError"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/DotSdkError-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/Error-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/LocalizedError-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error"},"kind":"symbol","references":{"doc://DotFingersCore/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error/capturedSampleFailed(internalError:)":{"title":"FingersAutoCaptureController.Error.capturedSampleFailed(internalError:)","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error\/capturedsamplefailed(internalerror:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"capturedSampleFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/capturedSampleFailed(internalError:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error/internalError":{"type":"topic","kind":"symbol","title":"internalError","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error\/internalerror","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/internalError"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"FingersAutoCaptureController.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error\/localizederror-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/LocalizedError-Implementations","kind":"article"},"doc://DotFingersCore/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/DotFingersCore\/s8SendableP","type":"unresolvable"},"doc://DotFingersCore/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/DotFingersCore\/s5ErrorP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","identifier":"doc:\/\/DotFingersCore\/s16SendableMetatypeP","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"role":"symbol","title":"FingersAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureController"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error/processSampleFailed(internalError:)":{"role":"symbol","title":"FingersAutoCaptureController.Error.processSampleFailed(internalError:)","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error\/processsamplefailed(internalerror:)","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processSampleFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/processSampleFailed(internalError:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error/errorMessage":{"type":"topic","kind":"symbol","title":"errorMessage","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error\/errormessage","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/errorMessage"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkError":{"kind":"symbol","title":"DotSdkError","url":"\/documentation\/dotfingerscore\/dotsdkerror","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error\/error-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/Error-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error/DotSdkError-Implementations":{"role":"collectionGroup","title":"DotSdkError Implementations","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error\/dotsdkerror-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error\/DotSdkError-Implementations","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingersAutoCaptureController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","op":"replace"}]}]}