{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"]]},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/init(detection:selectedFingerTypes:result:phase:events:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/detection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/events","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/phase","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/result","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/selectedFingerTypes"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"s:14DotFingersCore0B21AutoCaptureControllerC16ProcessingResultC","role":"symbol","title":"FingersAutoCaptureController.ProcessingResult","navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"The result returned from the processing of one image during the fingers auto capture process."}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","kind":"relationships"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"],"title":"Fingers auto capture process","generated":true,"anchor":"Fingers-auto-capture-process"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGFingersAutoCaptureControllerProcessingResult) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"title":"FingersAutoCaptureFrameParameters","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information from the detection process about the detected fingers.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample":{"title":"FingersAutoCaptureController.PhotoSample","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PhotoSample"}],"type":"topic","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"type":"codeVoice","code":".captureDepth"},{"type":"text","text":" event during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureEvent":{"role":"symbol","title":"FingersAutoCaptureEvent","type":"topic","abstract":[{"type":"text","text":"An event emitted during the fingers auto capture process."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureEvent","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCaptureEvent","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureevent","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/selectedFingerTypes":{"type":"topic","kind":"symbol","title":"selectedFingerTypes","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/selectedfingertypes","abstract":[{"type":"text","text":"Selected finger types. These finger types have a valid image captured during the process."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedFingerTypes","kind":"identifier"},{"text":": [","kind":"text"},{"text":"FingerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/selectedFingerTypes"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"role":"symbol","title":"FingersAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the fingers auto capture process."}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/events":{"type":"topic","kind":"symbol","title":"events","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/events","abstract":[{"text":"Events emitted while processing the sample.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"events","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCaptureEvent","text":"FingersAutoCaptureEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFingersCore0B16AutoCaptureEventO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/events"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/detection":{"type":"topic","kind":"symbol","title":"detection","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/detection","abstract":[{"type":"text","text":"The result of processing image during the fingers auto capture process."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection","kind":"typeIdentifier","text":"FingersAutoCaptureDetection"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/detection"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Sample":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"title":"FingersAutoCaptureController.Sample","navigatorTitle":[{"text":"Sample","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample","kind":"symbol","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the fingers auto capture process."}]},"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/result":{"role":"symbol","title":"result","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/result","abstract":[{"text":"The final result of the fingers auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","text":"FingersAutoCaptureResult"},{"kind":"text","text":"?"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/result","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"role":"symbol","title":"FingersAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureController"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/phase":{"role":"symbol","title":"phase","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/phase","abstract":[{"type":"text","text":"Current phase of the fingers auto capture process."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","text":"FingersAutoCapturePhase","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/phase","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"kind":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/init(detection:selectedFingerTypes:result:phase:events:)":{"role":"symbol","title":"init(detection:selectedFingerTypes:result:phase:events:)","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection","text":"FingersAutoCaptureDetection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"selectedFingerTypes","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","text":"FingersAutoCaptureResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","text":"FingersAutoCapturePhase","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"events","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCaptureEvent","text":"FingersAutoCaptureEvent","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:14DotFingersCore0B16AutoCaptureEventO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/init(detection:selectedfingertypes:result:phase:events:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/init(detection:selectedFingerTypes:result:phase:events:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult":{"role":"symbol","title":"FingersAutoCaptureController.ProcessingResult","navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"text":"Phase of the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePhase","kind":"identifier"}],"title":"FingersAutoCapturePhase","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title","value":"DOTFGFingersAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/title","value":"DOTFGFingersAutoCaptureEvent"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/fragments","value":[{"text":"DOTFGFingersAutoCaptureEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title","value":"DOTFGFingersAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title","value":"DOTFGDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle","value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","value":"DOTFGFingersAutoCaptureController"},{"value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}]},{"value":"DOTFGFingersAutoCaptureDetection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments","value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title","value":"DOTFGFingersAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]}]}]}