{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/isEqual(_:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"isEqual(_:)","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle(im)isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerbundle\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerbundle\/isequal(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerbundle\/isequal(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/isEqual(_:)","title":"isEqual(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle":{"url":"\/documentation\/dotfingerscore\/fingerbundle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundle"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","title":"FingerBundle","role":"symbol","abstract":[{"text":"Bundle of a finger image with detection data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundle"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isEqual:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1isEqual(_:)\/fragments","op":"replace"},{"value":"DOTFGFingerBundle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/title","op":"replace"},{"value":[{"text":"DOTFGFingerBundle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerBundle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/navigatorTitle","op":"replace"}]}]}