{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"metadata":{"symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)documentNumber","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"title":"documentNumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentNumber"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentNumber"},"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/documentnumber"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/documentnumber"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","type":"topic","title":"MrzElementWithCheckDigit","kind":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","title":"Td2MachineReadableZone","kind":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/documentNumber":{"url":"\/documentation\/dotnfc\/td2machinereadablezone\/documentnumber","role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentNumber","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"}],"abstract":[],"title":"documentNumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"documentNumber","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"documentNumber","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentNumber"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"value":"DOTTd2MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentNumber\/title","value":"documentNumber"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentNumber\/fragments","value":[{"text":"documentNumber","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}