{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class\/camerafacing"]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/cameraFacing","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"title":"cameraFacing","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC12cameraFacing0A6Camera0lK0Ovp","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","text":"CameraFacing"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the Multi-Range Liveness process."}],"title":"MultiRangeLivenessViewController.Configuration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"title":"MultiRangeLivenessViewController","abstract":[{"type":"text","text":"UI component for capturing images suitable for Multi-Range Liveness evaluation."}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"url":"\/documentation\/dotfacecore\/camerafacing","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class/cameraFacing":{"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class\/camerafacing","abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"type":"text","text":"."}],"title":"cameraFacing","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/cameraFacing","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","value":"DOTFMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}]}]}