{"metadata":{"required":true,"navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceLiteEnabled","symbolKind":"property","title":"isFaceLiteEnabled"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfaceliteenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfaceliteenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","type":"topic","title":"DotSdkLicenseProxyProtocol","kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"kind":"symbol","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","type":"topic","title":"isFaceLiteEnabled","abstract":[],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfaceliteenabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isFaceLiteEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/navigatorTitle"},{"op":"replace","value":"isFaceLiteEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments"}]}]}