{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/wrappeddouble\/isequal(_:)"]},{"paths":["\/documentation\/dotpalmcore\/wrappeddouble\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble\/isEqual(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble"]]},"metadata":{"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble(im)isEqual:","role":"symbol","title":"isEqual(_:)","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"kind":"symbol","sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/wrappeddouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"title":"WrappedDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble/isEqual(_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble\/isEqual(_:)","title":"isEqual(_:)","url":"\/documentation\/dotpalmcore\/wrappeddouble\/isequal(_:)","type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"isEqual:"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble~1isEqual(_:)\/fragments"}]}]}