{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"detectionPosition","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/detectionposition"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionPosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"}],"roleHeading":"Instance Property","externalID":"s:11DotPalmCore0B8DetectorC0B0C17detectionPositionAA09DetectionF0Cvp","title":"detectionPosition"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/detectionPosition","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detected corners of the palm."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"url":"\/documentation\/dotpalmcore\/detectionposition","abstract":[{"text":"Position of the palm in the image.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","role":"symbol","title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/detectionPosition":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/detectionposition","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/detectionPosition","kind":"symbol","type":"topic","title":"detectionPosition","role":"symbol","abstract":[{"text":"Detected corners of the palm.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"detectionPosition","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","kind":"typeIdentifier","text":"DetectionPosition"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"title":"PalmDetector.Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","type":"topic","abstract":[{"type":"text","text":"Result of the palm detection process."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"title":"PalmDetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPDetectionPosition"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"}]}]}