{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithRawLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"rawLines"},{"kind":"text","text":" "},{"text":"travelDocumentType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTTravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},{"text":" *) ","kind":"text"},{"text":"travelDocumentType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"machineReadableZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTMachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"machineReadableZone"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzReaderReadingError","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderReadingError","text":"DOTDMrzReaderReadingError","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult\/initWithRawLines:travelDocumentType:machineReadableZone:error:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithRawLines:travelDocumentType:machineReadableZone:error:","kind":"identifier"}],"title":"initWithRawLines:travelDocumentType:machineReadableZone:error:","modules":[{"name":"DotDocument"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"initWithRawLines:travelDocumentType:machineReadableZone:error:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzReaderResult(im)initWithRawLines:travelDocumentType:machineReadableZone:error:"},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotdmrzreaderresult\/initwithrawlines:traveldocumenttype:machinereadablezone:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"kind":"symbol","title":"TravelDocumentTypeWrapper","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone","title":"MachineReadableZone","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDMrzReaderReadingError":{"url":"\/documentation\/dotdocument\/dotdmrzreaderreadingerror","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderReadingError","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DOTDMrzReaderReadingError"}],"title":"DOTDMrzReaderReadingError","abstract":[{"type":"text","text":"Thrown if travel document type resolution, text recognition, or text parsing are unsuccessful."}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDMrzReaderResult":{"url":"\/documentation\/dotdocument\/dotdmrzreaderresult","role":"symbol","type":"topic","fragments":[{"text":"DOTDMrzReaderResult","kind":"identifier"}],"abstract":[{"text":"MRZ reading result.","type":"text"}],"kind":"symbol","title":"DOTDMrzReaderResult","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDMrzReaderResult/initWithRawLines:travelDocumentType:machineReadableZone:error:":{"title":"initWithRawLines:travelDocumentType:machineReadableZone:error:","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult\/initWithRawLines:travelDocumentType:machineReadableZone:error:","type":"topic","kind":"symbol","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithRawLines:travelDocumentType:machineReadableZone:error:","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRawLines:travelDocumentType:machineReadableZone:error:"}],"url":"\/documentation\/dotdocument\/dotdmrzreaderresult\/initwithrawlines:traveldocumenttype:machinereadablezone:error:"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTTravelDocumentTypeWrapper"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTMachineReadableZone"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments"}]}]}