{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/init(modules:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(im)initWithModules:","title":"init(modules:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Palm library configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration","type":"topic","kind":"symbol","title":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Palm library module configuration.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"title":"DotPalmLibraryConfiguration.Modules","navigatorTitle":[{"text":"Modules","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfigurationModules":{"kind":"symbol","url":"\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules","type":"topic","fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"role":"symbol","title":"DotPalmLibraryConfigurationModules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules","abstract":[{"text":"Palm library module configuration.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/init(modules:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/init(modules:)","kind":"symbol","title":"init(modules:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/init(modules:)","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithModules:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithModules:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotPalmLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration~1init(modules:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}],"op":"replace"}]}]}