{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/modules-swift.property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.property"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"modules","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(py)modules","symbolKind":"property","title":"modules","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Module configuration.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","type":"topic","abstract":[{"type":"text","text":"Palm library configuration."}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"kind":"symbol","title":"DotPalmLibraryConfiguration.Modules","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/modules-swift.property":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/modules-swift.property","kind":"symbol","abstract":[{"type":"text","text":"Module configuration."}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"type":"topic","title":"modules"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfigurationModules":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules","kind":"symbol","title":"DotPalmLibraryConfigurationModules","abstract":[{"type":"text","text":"Palm library module configuration."}],"fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfigurationmodules","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"modules"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules","text":"DotPalmLibraryConfigurationModules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration~1modules-swift.property\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration~1modules-swift.property\/fragments","value":[{"kind":"identifier","text":"modules"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}