{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}]}],"name":"image"}]},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}],"kind":"content"}],"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}],"symbolKind":"method","title":"create(image:)","roleHeading":"Type Method","externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithImage:","navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(image:)"]}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"text":" as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(image:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","abstract":[{"text":"version: 9.4.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory/create(image:)":{"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(image:)","navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"title":"create(image:)","url":"\/documentation\/dotpalmcore\/ciimagefactory\/create(image:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/image","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","title":"Image","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"url":"\/documentation\/dotpalmcore\/ciimagefactory","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"role":"symbol","title":"CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createWithImage:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(image:)\/title","value":"createWithImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(image:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace"}]}]}