{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(bgraRawImage:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}],"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":") -> "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"}],"title":"create(bgraRawImage:)","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" instance."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrarawimage:)"]},{"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"role":"symbol","title":"BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotpalmcore\/bgrarawimage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","title":"DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory/create(bgraRawImage:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":") -> "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"type":"topic","title":"create(bgraRawImage:)","kind":"symbol","url":"\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrarawimage:)","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(bgraRawImage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"url":"\/documentation\/dotpalmcore\/ciimagefactory","abstract":[{"text":"Create ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"title":"CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIImageFactory"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"createWithBgraRawImage:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgraRawImage:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"bgraRawImage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"value":"createWithBgraRawImage:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(bgraRawImage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgraRawImage:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","op":"replace","value":"DOTCIImageFactory"},{"value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}