{"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithBgrRawImage:","title":"create(bgrRawImage:)","role":"symbol","roleHeading":"Type Method","modules":[{"name":"DotPalmCore"}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}]},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(bgrRawImage:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier","text":"BgrRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage"},{"kind":"text","text":") -> "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"bgrRawImage"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" instance."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrrawimage:)"]},{"paths":["\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrrawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"title":"CIImageFactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","url":"\/documentation\/dotpalmcore\/ciimagefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}]},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage":{"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","url":"\/documentation\/dotpalmcore\/bgrrawimage"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","abstract":[{"type":"text","text":"version: 8.8.0"}],"role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory/create(bgrRawImage:)":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"title":"create(bgrRawImage:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory\/create(bgrRawImage:)","url":"\/documentation\/dotpalmcore\/ciimagefactory\/create(bgrrawimage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"}],"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"createWithBgrRawImage:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgrRawImage:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"text":"createWithBgrRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","text":"DOTBgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgrRawImage"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments","op":"replace"},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/title"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/fragments"},{"value":"createWithBgrRawImage:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(bgrRawImage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory~1create(bgrRawImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgrRawImage:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}