{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCapturePhase","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Wrapped"},{"kind":"text","text":"?"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/phase","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","externalID":"s:11DotDocument0B18AutoCaptureUiStateC7RunningC5phaseAA0bcD5PhaseO7WrappedCSgvp","role":"symbol","title":"phase","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC"},{"text":"?","kind":"text"}],"modules":[{"name":"DotDocument"}],"symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/running\/phase"]}],"abstract":[{"type":"text","text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be "},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/phase":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/phase","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/phase","title":"phase","abstract":[{"type":"text","text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be "},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCapturePhase","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC"},{"kind":"text","text":"?"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running":{"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running","type":"topic","navigatorTitle":[{"text":"Running","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"abstract":[{"text":"Running state.","type":"text"}],"title":"DocumentAutoCaptureUiState.Running"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"role":"symbol","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureuistate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","title":"DocumentAutoCaptureUiState"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"url":"\/documentation\/dotdocument\/documentautocapturephase","role":"symbol","abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"identifier"}],"type":"topic","title":"DocumentAutoCapturePhase","kind":"symbol","navigatorTitle":[{"text":"DocumentAutoCapturePhase","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/Wrapped":{"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturephase\/wrapped","title":"DocumentAutoCapturePhase.Wrapped","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/Wrapped","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTDDocumentAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle"},{"value":"DOTDDocumentAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title"},{"value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}