{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyIsActive"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotnfclibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotnfclibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary\/verifyIsActive()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Verify that library is initialized."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"role":"symbol","title":"verifyIsActive()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyIsActive"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)DotNfcLibrary(im)verifyIsActiveAndReturnError:","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotNfcLibrary":{"role":"symbol","title":"DotNfcLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibrary"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":" library initialization."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotNfcLibrary"}],"url":"\/documentation\/dotnfc\/dotnfclibrary"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotNfcLibrary/verifyIsActive()":{"role":"symbol","title":"verifyIsActive()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyIsActive"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Verify that library is initialized."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary\/verifyIsActive()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"url":"\/documentation\/dotnfc\/dotnfclibrary\/verifyisactive()"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.5.3"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"verifyIsActiveAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary\/title","value":"DotNfcLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments","value":[{"kind":"identifier","text":"DotNfcLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary~1verifyIsActive()\/title","value":"verifyIsActiveAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary~1verifyIsActive()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}