{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzvalidation\/hashvalue"]}],"sections":[],"metadata":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"extendedModule":"Swift","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"symbolKind":"property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotDocument@E@DOTDMrzValidation","modules":[{"name":"DotDocument","relatedModules":["Swift"]}],"roleHeading":"Instance Property","role":"symbol","title":"hashValue"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/RawRepresentable-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/hashValue","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/MrzValidation/hashValue":{"url":"\/documentation\/dotdocument\/mrzvalidation\/hashvalue","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"hashValue","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/hashValue","type":"topic","abstract":[],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzValidation/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/RawRepresentable-Implementations","url":"\/documentation\/dotdocument\/mrzvalidation\/rawrepresentable-implementations","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","kind":"article"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"type":"topic","title":"MrzValidation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"url":"\/documentation\/dotdocument\/mrzvalidation","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]}]}]}