{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireValidityIfPresent"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotDocument@E@DOTDMrzValidation@DOTDMrzValidationRequireValidityIfPresent","navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationRequireValidityIfPresent"}],"modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requireValidityIfPresent","kind":"identifier"}],"title":"MrzValidation.requireValidityIfPresent","roleHeading":"Case","symbolKind":"case"},"abstract":[{"type":"text","text":"If an MRZ is present, it must be valid."}],"variants":[{"paths":["\/documentation\/dotdocument\/mrzvalidation\/requirevalidityifpresent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzvalidation\/requirevalidityifpresent"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requireValidityIfPresent","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/MrzValidation":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"kind":"symbol","abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"role":"symbol","type":"topic","title":"MrzValidation","url":"\/documentation\/dotdocument\/mrzvalidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"},"doc://DotDocument/documentation/DotDocument/MrzValidation/requireValidityIfPresent":{"type":"topic","url":"\/documentation\/dotdocument\/mrzvalidation\/requirevalidityifpresent","abstract":[{"type":"text","text":"If an MRZ is present, it must be valid."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requireValidityIfPresent","role":"symbol","title":"MrzValidation.requireValidityIfPresent","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"requireValidityIfPresent"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationRequireValidityIfPresent"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDMrzValidationRequireValidityIfPresent","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTDMrzValidationRequireValidityIfPresent","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTDMrzValidationRequireValidityIfPresent","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDMrzValidation","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title"},{"value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments"},{"value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle"},{"value":"DOTDMrzValidationRequireValidityIfPresent","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requireValidityIfPresent\/title"},{"value":[{"text":"DOTDMrzValidationRequireValidityIfPresent","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requireValidityIfPresent\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}