{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requirePresenceAndValidity","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzvalidation\/requirepresenceandvalidity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzvalidation\/requirepresenceandvalidity"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requirePresenceAndValidity","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"DOTDMrzValidationRequirePresenceAndValidity","kind":"identifier"}],"symbolKind":"case","title":"MrzValidation.requirePresenceAndValidity","externalID":"c:@M@DotDocument@E@DOTDMrzValidation@DOTDMrzValidationRequirePresenceAndValidity","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requirePresenceAndValidity","kind":"identifier"}],"modules":[{"name":"DotDocument"}]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"An MRZ must be present and valid."}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"role":"symbol","title":"MrzValidation","kind":"symbol","navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzvalidation"},"doc://DotDocument/documentation/DotDocument/MrzValidation/requirePresenceAndValidity":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/mrzvalidation\/requirepresenceandvalidity","title":"MrzValidation.requirePresenceAndValidity","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation\/requirePresenceAndValidity","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requirePresenceAndValidity","kind":"identifier"}],"navigatorTitle":[{"text":"DOTDMrzValidationRequirePresenceAndValidity","kind":"identifier"}],"abstract":[{"type":"text","text":"An MRZ must be present and valid."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTDMrzValidationRequirePresenceAndValidity","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzValidationRequirePresenceAndValidity"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTDMrzValidationRequirePresenceAndValidity","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTDMrzValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","op":"replace"},{"value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requirePresenceAndValidity\/title","value":"DOTDMrzValidationRequirePresenceAndValidity","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation~1requirePresenceAndValidity\/fragments","value":[{"kind":"identifier","text":"DOTDMrzValidationRequirePresenceAndValidity"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}