{"metadata":{"title":"ImageFormat.jpeg2000","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg2000","roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg2000"}],"role":"symbol","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/imageformat\/jpeg2000"]},{"paths":["\/documentation\/dotfacelite\/imageformat\/jpeg2000"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"JPEG2000 compressed image format","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg2000"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg2000"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imageformat","abstract":[{"type":"text","text":"Supported image formats."}],"navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","role":"symbol","title":"ImageFormat","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/jpeg2000":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imageformat\/jpeg2000","abstract":[{"type":"text","text":"JPEG2000 compressed image format"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg2000","role":"symbol","title":"ImageFormat.jpeg2000","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTImageFormatJpeg2000","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTImageFormat","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title"},{"op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments"},{"op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle"},{"op":"replace","value":"DOTImageFormatJpeg2000","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg2000\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg2000\/fragments"}]}]}