{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"case","roleHeading":"Case","navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgra","title":"ImageFormat.rawBgra"},"kind":"symbol","abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The 4 bytes of color image pixel:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0th byte: BB - blue"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"1st byte: GG - green","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2nd byte: RR - red"}]}]},{"content":[{"inlineContent":[{"text":"3rd byte: 0  - alpha","type":"text"}],"type":"paragraph"}]}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgra","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/rawBgra":{"kind":"symbol","navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"type":"topic","title":"ImageFormat.rawBgra","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgra","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imageformat\/rawbgra"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotfacelite\/imageformat","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"type":"text","text":"Supported image formats."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","type":"topic","title":"ImageFormat"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTImageFormatRawBgra","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFormatRawBgra","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1rawBgra\/title"},{"value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1rawBgra\/fragments"},{"value":"DOTImageFormat","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}