{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/face"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/face"]}],"metadata":{"externalID":"c:@M@DotFaceCore@E@DotLibraryId@DotLibraryIdFace","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdFace","kind":"identifier"}],"role":"symbol","title":"DotLibraryId.face","roleHeading":"Case","symbolKind":"case","modules":[{"name":"DotFaceCore"}]},"abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId\/face","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibraryId":{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"type":"topic","url":"\/documentation\/dotfacecore\/dotlibraryid","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"role":"symbol","title":"DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibraryId/face":{"abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"type":"topic","url":"\/documentation\/dotfacecore\/dotlibraryid\/face","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFace"}],"role":"symbol","title":"DotLibraryId.face","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId\/face","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DotLibraryIdFace","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdFace","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DotLibraryIdFace"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","value":"DotLibraryIdFace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId~1face\/title"},{"op":"replace","value":[{"text":"DotLibraryIdFace","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId~1face\/fragments"}]}]}