{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/faceLite","interfaceLanguage":"swift"},"abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"kind":"symbol","metadata":{"title":"DotLibraryId.faceLite","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"roleHeading":"Case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdFaceLite","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/facelite"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/facelite"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/faceLite":{"title":"DotLibraryId.faceLite","url":"\/documentation\/dotfacecore\/dotlibraryid\/facelite","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/faceLite","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"type":"text","text":" identifier."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"title":"DotLibraryId","url":"\/documentation\/dotfacecore\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId","role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotLibraryIdFaceLite","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotLibraryIdFaceLite"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DotLibraryIdFaceLite","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1faceLite\/title","op":"replace"},{"op":"replace","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1faceLite\/fragments"},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/navigatorTitle"}]}]}