{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdNfc","roleHeading":"Case","title":"DotLibraryId.nfc","navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nfc"}],"symbolKind":"case","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotlibraryid\/nfc"]},{"paths":["\/documentation\/dotfacecore\/dotlibraryid\/nfc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/nfc"},"abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"type":"text","text":" identifier."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId/nfc":{"abstract":[{"code":"DotNfcLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nfc","kind":"identifier"}],"role":"symbol","title":"DotLibraryId.nfc","type":"topic","url":"\/documentation\/dotfacecore\/dotlibraryid\/nfc","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId\/nfc"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibraryId":{"title":"DotLibraryId","type":"topic","role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibraryId","url":"\/documentation\/dotfacecore\/dotlibraryid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotLibraryIdNfc","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdNfc","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1nfc\/title","value":"DotLibraryIdNfc"},{"value":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId~1nfc\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/title","value":"DotLibraryId"},{"value":[{"kind":"identifier","text":"DotLibraryId"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibraryId\/fragments","op":"replace"}]}]}