{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class\/detection"]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"}],"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"detection"},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","abstract":[],"kind":"symbol","role":"symbol","title":"detection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/Modules-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"title":"DotPalmLibraryConfiguration.Modules","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration":{"abstract":[{"text":"Palm library configuration.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotPalmDetectionModuleConfiguration":{"navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"title":"DotPalmDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotpalmdetectionmoduleconfiguration","abstract":[{"text":"Palm detection module configuration.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/title","op":"replace","value":"DotPalmDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]}]}]}