{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running\/selectedFingerTypes","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running\/selectedfingertypes"]}],"abstract":[{"type":"text","text":"Selected finger types. These finger types have a valid image captured during the process."}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:14DotFingersCore0B18AutoCaptureUiStateC7RunningC19selectedFingerTypesSayAA0J4TypeO7WrappedCGvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC"},{"kind":"text","text":"]"}],"title":"selectedFingerTypes","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped"},{"kind":"text","text":"]"}],"languages":["swift"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState":{"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureUiState"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureUiState"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"title":"FingersAutoCaptureUiState","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate","type":"topic","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Running":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"navigatorTitle":[{"text":"Running","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running","abstract":[{"type":"text","text":"Running state."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running","title":"FingersAutoCaptureUiState.Running","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","title":"FingerType","role":"symbol","abstract":[{"text":"Type of detected finger.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/Wrapped":{"url":"\/documentation\/dotfingerscore\/fingertype\/wrapped","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped","title":"FingerType.Wrapped","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Running/selectedFingerTypes":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/running\/selectedfingertypes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectedFingerTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore10FingerTypeO7WrappedC","text":"Wrapped"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Running\/selectedFingerTypes","title":"selectedFingerTypes","role":"symbol","abstract":[{"text":"Selected finger types. These finger types have a valid image captured during the process.","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingersAutoCaptureUiState","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/navigatorTitle","op":"replace"},{"value":"DOTFGFingerType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","op":"replace"}]}]}