{"variants":[{"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/description"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit\/description"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit(py)description","modules":[{"name":"DotDocument"}],"role":"symbol","title":"description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"roleHeading":"Instance Property"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzCheckDigit":{"type":"topic","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"title":"MrzCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"url":"\/documentation\/dotdocument\/mrzcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.3.0"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzCheckDigit/description":{"kind":"symbol","abstract":[],"title":"description","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzcheckdigit\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"description"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/fragments","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit~1description\/fragments","value":[{"text":"description","kind":"identifier"}]}]}]}