{"variants":[{"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/isvalid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzcheckdigit\/isvalid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isValid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isValid","interfaceLanguage":"swift"},"metadata":{"title":"isValid","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isValid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit(py)isValid","navigatorTitle":[{"text":"isValid","kind":"identifier"}],"role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"Denotes whether a checksum of a particular MRZ element is valid."}],"references":{"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"type":"topic","title":"MrzCheckDigit","kind":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit/isValid":{"role":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit\/isvalid","navigatorTitle":[{"text":"isValid","kind":"identifier"}],"title":"isValid","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isValid","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Denotes whether a checksum of a particular MRZ element is valid."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit\/isValid","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isValid"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isValid","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isValid","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title","op":"replace","value":"DOTMrzCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1isValid\/title","op":"replace","value":"isValid"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit~1isValid\/fragments","op":"replace","value":[{"text":"isValid","kind":"identifier"}]}]}]}