{"kind":"symbol","metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)documentNumber","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"documentNumber"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"title":"documentNumber"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/documentnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone\/documentnumber"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/documentNumber"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.7.1","type":"text"}],"type":"topic","role":"collection"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone/documentNumber":{"url":"\/documentation\/dotdocument\/td1machinereadablezone\/documentnumber","kind":"symbol","type":"topic","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"title":"documentNumber","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone\/documentNumber"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"role":"symbol","title":"Td1MachineReadableZone","url":"\/documentation\/dotdocument\/td1machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td1MachineReadableZone"}],"type":"topic","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"title":"MrzElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"type":"topic","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"documentNumber"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"documentNumber","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit"},{"kind":"text","text":" * "},{"text":"documentNumber","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"documentNumber","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1documentNumber\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone~1documentNumber\/fragments","value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace"}]}]}