{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage\/bytesPointer"},"sections":[],"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(py)bytesPointer","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytesPointer","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">"}],"title":"bytesPointer","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"bytesPointer","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointer","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrrawimage\/bytespointer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrrawimage\/bytespointer"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage"]]},"references":{"doc://DotDocument/documentation/DotDocument/BgrRawImage/bytesPointer":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointer"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"bytesPointer","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage\/bytesPointer","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/bgrrawimage\/bytespointer","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.13.0","type":"text"}],"url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/BgrRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"url":"\/documentation\/dotdocument\/bgrrawimage","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"bytesPointer","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"bytesPointer","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bytesPointer"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage~1bytesPointer\/title","value":"bytesPointer"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage~1bytesPointer\/fragments","value":[{"text":"bytesPointer","kind":"identifier"}]},{"op":"replace","value":"DOTBgrRawImage","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/title"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/fragments","op":"replace"}]}]}