{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage\/init(bytesPointer:size:)"},"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":")"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(im)initWithBytesPointer:size:","modules":[{"name":"DotDocument"}],"title":"init(bytesPointer:size:)","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}]},"variants":[{"paths":["\/documentation\/dotdocument\/bgrrawimage\/init(bytespointer:size:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrrawimage\/init(bytespointer:size:)"]}],"sections":[],"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgrRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/ImageSize":{"abstract":[{"type":"text","text":"Image size in pixels."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","title":"ImageSize","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imagesize","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BgrRawImage/init(bytesPointer:size:)":{"title":"init(bytesPointer:size:)","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage\/init(bytesPointer:size:)","kind":"symbol","url":"\/documentation\/dotdocument\/bgrrawimage\/init(bytespointer:size:)","type":"topic","abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgrRawImageFactory"},{"type":"text","text":" to create "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/BgrRawImage":{"title":"BgrRawImage","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImage","kind":"symbol","url":"\/documentation\/dotdocument\/bgrrawimage","type":"topic","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithBytesPointer:size:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBytesPointer:size:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBytesPointer:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier","text":"uint8_t"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bytesPointer"},{"kind":"text","text":" "},{"text":"size:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","text":"DOTImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":" *) ","kind":"text"},{"text":"size","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage~1init(bytesPointer:size:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBytesPointer:size:","kind":"identifier"}]},{"op":"replace","value":"DOTBgrRawImage","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/title"},{"op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImage\/fragments"}]}]}