{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillDisappear(_:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate(im)faceAutoCaptureViewControllerViewWillDisappear:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"faceAutoCaptureViewControllerViewWillDisappear(_:)","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"faceAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillDisappear"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilldisappear(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewWillDisappear(_:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillDisappear(_:)","abstract":[],"title":"faceAutoCaptureViewControllerViewWillDisappear(_:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilldisappear(_:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillDisappear:"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"kind":"symbol","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate","title":"FaceAutoCaptureViewControllerDelegate","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"faceAutoCaptureViewControllerViewWillDisappear:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","text":"DOTFFaceAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"value":"faceAutoCaptureViewControllerViewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillDisappear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillDisappear:"}]},{"op":"replace","value":"DOTFFaceAutoCaptureViewControllerDelegate","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}]}]}]}