{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:uiStateUpdated:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"uiState","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureUiState","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiState","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:uistateupdated:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:uistateupdated:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate(im)faceAutoCaptureViewController:uiStateUpdated:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiState"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"faceAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"title":"faceAutoCaptureViewController(_:uiStateUpdated:)","modules":[{"name":"DotFaceCore"}],"required":true},"sections":[],"abstract":[{"text":"Tells the delegate that the UI state was updated.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"type":"topic","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"title":"FaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureuistate"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewController(_:uiStateUpdated:)":{"abstract":[{"type":"text","text":"Tells the delegate that the UI state was updated."}],"title":"faceAutoCaptureViewController(_:uiStateUpdated:)","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewController:uiStateUpdated:"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:uiStateUpdated:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:uistateupdated:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiStateUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureUiState","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiState"},{"kind":"text","text":")"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","title":"FaceAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate","title":"FaceAutoCaptureViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"type":"topic","title":"BaseFaceAutoCaptureViewController","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceAutoCaptureViewController:uiStateUpdated:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewController:uiStateUpdated:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"faceAutoCaptureViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController","text":"DOTFBaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiStateUpdated:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","text":"DOTFFaceAutoCaptureUiState","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"uiState","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title","op":"replace","value":"DOTFFaceAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureUiState","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:uiStateUpdated:)\/title","op":"replace","value":"faceAutoCaptureViewController:uiStateUpdated:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:uiStateUpdated:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"faceAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title","op":"replace","value":"DOTFFaceAutoCaptureViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFBaseFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}