{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"seeAlsoSections":[{"title":"NFC protocols","generated":true,"anchor":"NFC-protocols","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNAccessControlProtocol) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"The prurpose of Access Control protocol is to establish connection between the device and the NFC chip of the travel document.","type":"text"}]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@DotNfc@E@DOTNAccessControlProtocol","symbolKind":"enum","modules":[{"name":"DotNfc"}],"role":"symbol","title":"AccessControlProtocol","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}]},"variants":[{"paths":["\/documentation\/dotnfc\/accesscontrolprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/accesscontrolprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Access Control protocol.","type":"text"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/bac","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/pace"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/description"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/RawRepresentable-Implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/Equatable-Implementations":{"type":"topic","abstract":[],"kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/equatable-implementations"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"type":"topic","url":"\/documentation\/dotnfc\/accesscontrolprotocol","title":"AccessControlProtocol","navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Access Control protocol."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/pace":{"title":"AccessControlProtocol.pace","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/pace","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/pace","abstract":[{"type":"text","text":"Password Authenticated Connection Establishment"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNAccessControlProtocolPace"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pace"}]},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/bac":{"url":"\/documentation\/dotnfc\/accesscontrolprotocol\/bac","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/bac","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bac"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTNAccessControlProtocolBac"}],"title":"AccessControlProtocol.bac","type":"topic","abstract":[{"type":"text","text":"Basic Access Control"}]},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/init(rawValue:)","abstract":[],"title":"init(rawValue:)","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"url":"\/documentation\/dotnfc\/chipauthenticationstatus","title":"ChipAuthenticationStatus","abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus","title":"DataAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"kind":"symbol","url":"\/documentation\/dotnfc\/authenticationstatus","abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","type":"topic","title":"AuthenticationStatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationStatus"}],"role":"symbol"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","navigatorTitle":[{"text":"AuthenticationProtocol","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationProtocol","kind":"identifier"}],"title":"ChipAuthenticationStatus.AuthenticationProtocol","type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/RawRepresentable-Implementations","type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/description":{"abstract":[],"title":"description","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotNfc\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTNAccessControlProtocol","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/bac","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/pace"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"replace","value":[{"generated":true,"anchor":"NFC-protocols","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus"],"title":"NFC protocols"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNAccessControlProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTNAccessControlProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle"},{"op":"replace","value":"DOTNAccessControlProtocolPace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1pace\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAccessControlProtocolPace"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1pace\/fragments"},{"op":"replace","value":"DOTNAccessControlProtocolBac","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1bac\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAccessControlProtocolBac"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1bac\/fragments"},{"op":"replace","value":"DOTNChipAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title"},{"op":"replace","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments"},{"op":"replace","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle"},{"op":"replace","value":"DOTNDataAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments"},{"op":"replace","value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle"},{"op":"replace","value":"DOTNAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments"},{"op":"replace","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/navigatorTitle"}]}]}