{"abstract":[{"type":"text","text":"Access Control protocol wrapper."}],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNAccessControlProtocolWrapper) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocolWrapper","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper"]},{"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/init(accessControlProtocol:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/accessControlProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/description"],"title":"Instance Properties"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"navigatorTitle":[{"text":"AccessControlProtocolWrapper","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper","modules":[{"name":"DotNfc"}],"platforms":[{"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false,"beta":false}],"title":"AccessControlProtocolWrapper","roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocolWrapper","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper/init(accessControlProtocol:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithAccessControlProtocol:"}],"type":"topic","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/init(accesscontrolprotocol:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accessControlProtocol","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AccessControlProtocol","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/init(accessControlProtocol:)","title":"init(accessControlProtocol:)","kind":"symbol","abstract":[]},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper/description":{"kind":"symbol","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/description","title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper/accessControlProtocol":{"navigatorTitle":[{"text":"accessControlProtocol","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/accesscontrolprotocol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessControlProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","text":"AccessControlProtocol","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/accessControlProtocol","title":"accessControlProtocol","kind":"symbol","abstract":[]},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper":{"kind":"symbol","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper","title":"AccessControlProtocolWrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocolWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AccessControlProtocolWrapper","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Access Control protocol wrapper."}],"role":"symbol"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[],"path":"\/metadata\/platforms","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTNAccessControlProtocolWrapper"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAccessControlProtocolWrapper"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTNAccessControlProtocolWrapper","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/accessControlProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/description"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/init(accessControlProtocol:)"]}]},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTNAccessControlProtocolWrapper"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"initWithAccessControlProtocol:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1init(accessControlProtocol:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithAccessControlProtocol:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1init(accessControlProtocol:)\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1description\/fragments"},{"value":"accessControlProtocol","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1accessControlProtocol\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1accessControlProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"accessControlProtocol"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/title","value":"DOTNAccessControlProtocolWrapper","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/fragments","op":"replace","value":[{"text":"DOTNAccessControlProtocolWrapper","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}