{"seeAlsoSections":[{"title":"NFC protocols","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"role":"symbol","title":"ActiveAuthenticationStatus","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"symbolKind":"enum","externalID":"c:@M@DotNfc@E@DOTNActiveAuthenticationStatus","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"abstract":[{"type":"text","text":"The resulting status of Active Authentication."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH","doc:\/\/com.innovatrics.dot.nfc\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/failed","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/notSupported","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/success"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/dotnfc\/activeauthenticationstatus"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/activeauthenticationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNActiveAuthenticationStatus) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The purpose of Active Authentication is to verify that the travel document is genuine, i.e. it is not a copy."}]}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/success":{"role":"symbol","title":"ActiveAuthenticationStatus.success","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"success"}],"abstract":[{"type":"text","text":"Travel document has passed the Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/success","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatusSuccess"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus\/success"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/activeauthenticationstatus\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/activeauthenticationstatus\/init(rawvalue:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PassiveAuthenticationStatus":{"role":"symbol","title":"PassiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Passive Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/passiveauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/notSupported":{"role":"symbol","title":"ActiveAuthenticationStatus.notSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"abstract":[{"type":"text","text":"Active Authentication is not supported for the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/notSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatusNotSupported"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus\/notsupported"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/failed":{"role":"symbol","title":"ActiveAuthenticationStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"Travel document has not passed the Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatusFailed"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus\/failed"},"doc://com.innovatrics.dot.nfc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SY"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AccessControlProtocol":{"role":"symbol","title":"AccessControlProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"abstract":[{"type":"text","text":"Access Control protocol."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/activeauthenticationstatus\/equatable-implementations"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/activeauthenticationstatus\/description"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus":{"role":"symbol","title":"ActiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus"},"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTNActiveAuthenticationStatus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatus"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatus"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/failed","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/notSupported","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/success"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"NFC protocols","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocol","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PassiveAuthenticationStatus"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNActiveAuthenticationStatus"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1success\/title","value":"DOTNActiveAuthenticationStatusSuccess"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1success\/fragments","value":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatusSuccess"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/title","value":"DOTNPassiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PassiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNPassiveAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1notSupported\/title","value":"DOTNActiveAuthenticationStatusNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1notSupported\/fragments","value":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatusNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1failed\/title","value":"DOTNActiveAuthenticationStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1failed\/fragments","value":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/title","value":"DOTNAccessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/title","value":"DOTNActiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNActiveAuthenticationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}