{"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"13.0"}],"roleHeading":"Class","title":"AdditionalDocumentDetails","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/dateOfIssue","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/endorsementsOrObservations","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/issuingAuthority","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/otherPersonDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationDeviceSerialNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationTime","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/taxOrExitRequirements"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/isEqual(_:)"]}],"sections":[],"seeAlsoSections":[{"title":"Structured content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"generated":true}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNAdditionalDocumentDetails) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionaldocumentdetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionaldocumentdetails"]}],"references":{"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/description","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/description","abstract":[],"type":"topic","kind":"symbol","role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/issuingAuthority":{"navigatorTitle":[{"kind":"identifier","text":"issuingAuthority"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingAuthority"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[{"text":"Issuing Authority.","type":"text"}],"title":"issuingAuthority","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/issuingauthority","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/issuingAuthority"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/hash":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/hash","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/hash","abstract":[],"type":"topic","kind":"symbol","role":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails","title":"AdditionalPersonalDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}]},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/taxOrExitRequirements":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/taxOrExitRequirements","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/taxorexitrequirements","abstract":[{"type":"text","text":"Tax or exit requirements."}],"type":"topic","kind":"symbol","role":"symbol","title":"taxOrExitRequirements","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"taxOrExitRequirements","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"taxOrExitRequirements","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","title":"DotNfc","type":"topic"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/dateOfIssue":{"title":"dateOfIssue","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/dateofissue","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/dateOfIssue","abstract":[{"type":"text","text":"Full date of issue."}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfIssue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dateOfIssue","kind":"identifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/endorsementsOrObservations":{"url":"\/documentation\/dotnfc\/additionaldocumentdetails\/endorsementsorobservations","navigatorTitle":[{"kind":"identifier","text":"endorsementsOrObservations"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"endorsementsOrObservations","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/endorsementsOrObservations","role":"symbol","title":"endorsementsOrObservations","abstract":[{"type":"text","text":"Endorsements or observations."}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"title":"DisplayedSignatureOrUsualMark","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","title":"AdditionalDocumentDetails","url":"\/documentation\/dotnfc\/additionaldocumentdetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"title":"EncodedIdentificationFeaturesFace","role":"symbol","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","kind":"symbol","abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"type":"topic","navigatorTitle":[{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/personalizationTime":{"title":"personalizationTime","role":"symbol","abstract":[{"text":"Date and time of document personalization.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalizationTime"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"personalizationTime"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails\/personalizationtime","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationTime","type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)":{"title":"init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/init(issuingauthority:dateofissue:otherpersondetails:endorsementsorobservations:taxorexitrequirements:personalizationtime:personalizationdeviceserialnumber:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","role":"symbol","navigatorTitle":[{"text":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"issuingAuthority"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"dateOfIssue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"otherPersonDetails"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"endorsementsOrObservations"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"taxOrExitRequirements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"personalizationTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[]},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MachineReadableZoneInformation","kind":"identifier"}],"title":"MachineReadableZoneInformation","role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezoneinformation","kind":"symbol","abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"role":"symbol","title":"TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/personalizationDeviceSerialNumber":{"title":"personalizationDeviceSerialNumber","role":"symbol","abstract":[{"type":"text","text":"Serial number of personalization device."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"personalizationDeviceSerialNumber","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails\/personalizationdeviceserialnumber","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationDeviceSerialNumber","type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/isEqual(_:)":{"title":"isEqual(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/isEqual(_:)","type":"topic","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/isequal(_:)","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","title":"OptionalDetails","url":"\/documentation\/dotnfc\/optionaldetails","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OptionalDetails","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/otherPersonDetails":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/otherPersonDetails","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/otherpersondetails","abstract":[{"text":"Other person(s) details.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"otherPersonDetails","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherPersonDetails"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"otherPersonDetails"}]},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTNAdditionalDocumentDetails","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/dateOfIssue","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/endorsementsOrObservations","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/issuingAuthority","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/otherPersonDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationDeviceSerialNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/personalizationTime","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/taxOrExitRequirements"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/isEqual(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","value":[{"title":"Structured content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"generated":true}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNAdditionalDocumentDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1issuingAuthority\/title","value":"issuingAuthority"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1issuingAuthority\/fragments","op":"replace","value":[{"text":"issuingAuthority","kind":"identifier"}]},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1hash\/fragments","op":"replace"},{"op":"replace","value":"DOTNAdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1taxOrExitRequirements\/title","op":"replace","value":"taxOrExitRequirements"},{"op":"replace","value":[{"text":"taxOrExitRequirements","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1taxOrExitRequirements\/fragments"},{"op":"replace","value":"dateOfIssue","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1dateOfIssue\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1dateOfIssue\/fragments","value":[{"text":"dateOfIssue","kind":"identifier"}]},{"op":"replace","value":"endorsementsOrObservations","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1endorsementsOrObservations\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1endorsementsOrObservations\/fragments","value":[{"kind":"identifier","text":"endorsementsOrObservations"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","op":"replace","value":"DOTNDisplayedSignatureOrUsualMark"},{"value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalDocumentDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","value":"DOTNEncodedIdentificationFeaturesFace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"op":"replace","value":"personalizationTime","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1personalizationTime\/title"},{"value":[{"text":"personalizationTime","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1personalizationTime\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)\/title","value":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","kind":"identifier"}],"op":"replace"},{"value":"DOTNMachineReadableZoneInformation","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1personalizationDeviceSerialNumber\/title","value":"personalizationDeviceSerialNumber","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1personalizationDeviceSerialNumber\/fragments","value":[{"text":"personalizationDeviceSerialNumber","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","value":"DOTNOptionalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1otherPersonDetails\/title","value":"otherPersonDetails"},{"value":[{"kind":"identifier","text":"otherPersonDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1otherPersonDetails\/fragments","op":"replace"}]}]}