{"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails"],"generated":true,"title":"Structured content"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNAdditionalPersonalDetails) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails"]}],"metadata":{"role":"symbol","roleHeading":"Class","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"13.0"}],"navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","title":"AdditionalPersonalDetails","modules":[{"name":"DotNfc"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/address","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/custodyInformation","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/fullDateOfBirth","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/nameOfHolder","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherNames","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherValidTravelDocumentNumbers","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalNumber","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalSummary","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/placeOfBirth","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/profession","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/telephone","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/title"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/isEqual(_:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/profession":{"navigatorTitle":[{"text":"profession","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Profession.","type":"text"}],"role":"symbol","title":"profession","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"profession","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/profession","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/profession"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/personalNumber":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalNumber"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/personalnumber","title":"personalNumber","kind":"symbol","navigatorTitle":[{"text":"personalNumber","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalNumber","abstract":[{"text":"Personal number.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/OptionalDetails":{"navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}],"kind":"symbol","title":"OptionalDetails","role":"symbol","url":"\/documentation\/dotnfc\/optionaldetails","abstract":[{"text":"Contents of DG13 - Optional details.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionalDetails","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/otherValidTravelDocumentNumbers":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherValidTravelDocumentNumbers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?","kind":"text"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/othervalidtraveldocumentnumbers","navigatorTitle":[{"kind":"identifier","text":"otherValidTravelDocumentNumbers"}],"title":"otherValidTravelDocumentNumbers","abstract":[{"type":"text","text":"Other valid travel document numbers."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherValidTravelDocumentNumbers","kind":"symbol","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/isEqual(_:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/isEqual(_:)","kind":"symbol","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/isequal(_:)","type":"topic","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)":{"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/init(nameofholder:othernames:personalnumber:fulldateofbirth:placeofbirth:address:telephone:profession:title:personalsummary:othervalidtraveldocumentnumbers:custodyinformation:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"nameOfHolder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NameOfHolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder"},{"kind":"text","text":"?, "},{"text":"otherNames","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?, "},{"text":"personalNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"fullDateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"placeOfBirth"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"address","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"telephone","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"profession"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"personalSummary"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"otherValidTravelDocumentNumbers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]?, ","kind":"text"},{"text":"custodyInformation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)","title":"init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)","abstract":[],"navigatorTitle":[{"text":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/description","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/description"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/telephone":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"telephone"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/telephone","navigatorTitle":[{"kind":"identifier","text":"telephone"}],"title":"telephone","abstract":[{"type":"text","text":"Telephone"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/telephone","kind":"symbol","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/nameOfHolder":{"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/nameofholder","navigatorTitle":[{"text":"nameOfHolder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"nameOfHolder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NameOfHolder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/nameOfHolder","kind":"symbol","title":"nameOfHolder","abstract":[{"type":"text","text":"Full name of document holder."}],"type":"topic","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/hash":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/hash","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/hash","title":"hash"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation":{"title":"MachineReadableZoneInformation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation","kind":"symbol","navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"navigatorTitle":[{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"kind":"symbol","title":"EncodedIdentificationFeaturesFace","role":"symbol","url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","abstract":[{"text":"Contents of DG2 - Face image.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/title":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/title","navigatorTitle":[{"kind":"identifier","text":"title"}],"title":"title","abstract":[{"type":"text","text":"Title."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/title","kind":"symbol","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","title":"AdditionalPersonalDetails","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdditionalPersonalDetails"}],"navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"type":"topic","url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/otherNames":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherNames","navigatorTitle":[{"text":"otherNames","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"otherNames"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/othernames","type":"topic","role":"symbol","kind":"symbol","title":"otherNames","abstract":[{"type":"text","text":"Other names."}]},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/personalSummary":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"personalSummary","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/personalsummary","title":"personalSummary","kind":"symbol","navigatorTitle":[{"text":"personalSummary","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalSummary","abstract":[{"text":"Personal summary.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalDocumentDetails":{"navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"abstract":[{"text":"Contents of DG12 - Additional document details.","type":"text"}],"title":"AdditionalDocumentDetails","type":"topic","url":"\/documentation\/dotnfc\/additionaldocumentdetails","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/placeOfBirth":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/placeOfBirth","kind":"symbol","title":"placeOfBirth","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"placeOfBirth","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"placeOfBirth"}],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/placeofbirth","abstract":[{"type":"text","text":"Place of birth."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","abstract":[{"text":"Contents of DG7 - Displayed signature or usual mark.","type":"text"}],"type":"topic","title":"DisplayedSignatureOrUsualMark","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/address":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/address","navigatorTitle":[{"kind":"identifier","text":"address"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/address","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"address"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"kind":"symbol","title":"address","role":"symbol","abstract":[{"type":"text","text":"Permanent address."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/custodyInformation":{"abstract":[{"type":"text","text":"Custody information."}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/custodyinformation","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/custodyInformation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"custodyInformation"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"custodyInformation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"custodyInformation"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/fullDateOfBirth":{"kind":"symbol","abstract":[{"text":"Full date of birth.","type":"text"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/fulldateofbirth","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/fullDateOfBirth","navigatorTitle":[{"text":"fullDateOfBirth","kind":"identifier"}],"type":"topic","title":"fullDateOfBirth","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"fullDateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTNAdditionalPersonalDetails","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/address","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/custodyInformation","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/fullDateOfBirth","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/nameOfHolder","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherNames","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherValidTravelDocumentNumbers","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalNumber","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/personalSummary","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/placeOfBirth","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/profession","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/telephone","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/title"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/isEqual(_:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"value":[{"generated":true,"title":"Structured content","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails"]}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"profession","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1profession\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1profession\/fragments","op":"replace","value":[{"text":"profession","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1personalNumber\/title","op":"replace","value":"personalNumber"},{"value":[{"text":"personalNumber","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1personalNumber\/fragments"},{"op":"replace","value":"DOTNOptionalDetails","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/title"},{"value":[{"kind":"identifier","text":"DOTNOptionalDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherValidTravelDocumentNumbers\/title","value":"otherValidTravelDocumentNumbers"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherValidTravelDocumentNumbers\/fragments","value":[{"kind":"identifier","text":"otherValidTravelDocumentNumbers"}]},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1isEqual(_:)\/fragments"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"value":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1init(nameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNameOfHolder:otherNames:personalNumber:fullDateOfBirth:placeOfBirth:address:telephone:profession:title:personalSummary:otherValidTravelDocumentNumbers:custodyInformation:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1description\/title","value":"description","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1description\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1telephone\/title","value":"telephone","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1telephone\/fragments","value":[{"text":"telephone","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"nameOfHolder","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1nameOfHolder\/title"},{"op":"replace","value":[{"text":"nameOfHolder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1nameOfHolder\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1hash\/title","value":"hash","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","op":"replace","value":"DOTNEncodedIdentificationFeaturesFace"},{"value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments"},{"value":"title","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1title\/title"},{"value":[{"kind":"identifier","text":"title"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1title\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTNAdditionalPersonalDetails","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}]},{"op":"replace","value":"DOTNTravelDocument","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherNames\/title","op":"replace","value":"otherNames"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherNames\/fragments","value":[{"kind":"identifier","text":"otherNames"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1personalSummary\/title","value":"personalSummary","op":"replace"},{"op":"replace","value":[{"text":"personalSummary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1personalSummary\/fragments"},{"op":"replace","value":"DOTNAdditionalDocumentDetails","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title"},{"op":"replace","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1placeOfBirth\/title","value":"placeOfBirth","op":"replace"},{"op":"replace","value":[{"text":"placeOfBirth","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1placeOfBirth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1address\/title","op":"replace","value":"address"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1address\/fragments","value":[{"kind":"identifier","text":"address"}]},{"value":"custodyInformation","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1custodyInformation\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1custodyInformation\/fragments","value":[{"text":"custodyInformation","kind":"identifier"}]},{"value":"fullDateOfBirth","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1fullDateOfBirth\/title"},{"value":[{"kind":"identifier","text":"fullDateOfBirth"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1fullDateOfBirth\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}