{"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTBgraRawImageFactory) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImageFactory"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(ciImage:ciContext:)"]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory","modules":[{"name":"DotNfc"}],"title":"BgraRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bgrarawimagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrarawimagefactory"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}],"kind":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"title":"BgraRawImageFactory","url":"\/documentation\/dotnfc\/bgrarawimagefactory","role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory/create(ciImage:ciContext:)":{"title":"create(ciImage:ciContext:)","role":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(ciImage:ciContext:)","url":"\/documentation\/dotnfc\/bgrarawimagefactory\/create(ciimage:cicontext:)","type":"topic","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory/create(cgImage:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(cgImage:)","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"title":"create(cgImage:)","url":"\/documentation\/dotnfc\/bgrarawimagefactory\/create(cgimage:)","role":"symbol","type":"topic"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"DOTBgraRawImageFactory","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTBgraRawImageFactory","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(cgImage:)\/title","op":"replace","value":"createWithCgImage:"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(cgImage:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}