{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/init(bytesPointer:size:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytes","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointer","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointerPacked","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/size"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"variants":[{"paths":["\/documentation\/dotnfc\/bgrarawimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrarawimage"]}],"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage","title":"BgraRawImage","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}]},"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTBgraRawImage) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","interfaceLanguage":"swift"},"references":{"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/BgraRawImage/bytesPointerPacked":{"navigatorTitle":[{"kind":"identifier","text":"bytesPointerPacked"}],"url":"\/documentation\/dotnfc\/bgrarawimage\/bytespointerpacked","kind":"symbol","title":"bytesPointerPacked","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointerPacked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytesPointerPacked","kind":"identifier"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":">"}],"abstract":[],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/BgraRawImage/init(bytesPointer:size:)":{"url":"\/documentation\/dotnfc\/bgrarawimage\/init(bytespointer:size:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/init(bytesPointer:size:)","abstract":[{"text":"Do not use this, use ","type":"text"},{"code":"BgraRawImageFactory","type":"codeVoice"},{"text":" to create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"role":"symbol","title":"init(bytesPointer:size:)","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}]},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/BgraRawImage/bytesPointer":{"url":"\/documentation\/dotnfc\/bgrarawimage\/bytespointer","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointer","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointer"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"kind":"text","text":">"}],"role":"symbol","title":"bytesPointer","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}]},"doc://DotNfc/documentation/DotNfc/BgraRawImage/size":{"role":"symbol","abstract":[],"type":"topic","kind":"symbol","title":"size","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/size","url":"\/documentation\/dotnfc\/bgrarawimage\/size","navigatorTitle":[{"kind":"identifier","text":"size"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"}]},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/@M@DotCore@objc(pl)_RawImage":{"identifier":"doc:\/\/DotNfc\/@M@DotCore@objc(pl)_RawImage","title":"_RawImage","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrarawimage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","type":"topic","kind":"symbol","title":"BgraRawImage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}]},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/BgraRawImage/bytes":{"url":"\/documentation\/dotnfc\/bgrarawimage\/bytes","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytes","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"role":"symbol","title":"bytes","navigatorTitle":[{"text":"bytes","kind":"identifier"}]},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTBgraRawImage","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytes","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointer","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointerPacked","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/size"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/init(bytesPointer:size:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/DotNfc\/@M@DotCore@objc(pl)_RawImage"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTBgraRawImage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"value":"bytesPointerPacked","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointerPacked\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointerPacked\/fragments","value":[{"text":"bytesPointerPacked","kind":"identifier"}]},{"op":"replace","value":"initWithBytesPointer:size:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1init(bytesPointer:size:)\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1init(bytesPointer:size:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"op":"replace"},{"value":"bytesPointer","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointer\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointer\/fragments","op":"replace","value":[{"kind":"identifier","text":"bytesPointer"}]},{"value":"size","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1size\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1size\/fragments","value":[{"text":"size","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytes\/title","value":"bytes"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}