{"metadata":{"symbolKind":"class","modules":[{"name":"DotNfc"}],"roleHeading":"Class","title":"BgrRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImageFactory","kind":"identifier"}]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTBgrRawImageFactory) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/bgrrawimagefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/bgrrawimagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"sections":[],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" from iOS native image types.","type":"text"}],"references":{"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/BgrRawImageFactory":{"title":"BgrRawImageFactory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory","type":"topic","url":"\/documentation\/dotnfc\/bgrrawimagefactory"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/BgrRawImageFactory/create(cgImage:)":{"title":"create(cgImage:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(cgImage:)","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" object.","type":"text"}],"url":"\/documentation\/dotnfc\/bgrrawimagefactory\/create(cgimage:)"},"doc://DotNfc/documentation/DotNfc/BgrRawImageFactory/create(ciImage:ciContext:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"text":" as a ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"role":"symbol","type":"topic","title":"create(ciImage:ciContext:)","url":"\/documentation\/dotnfc\/bgrrawimagefactory\/create(ciimage:cicontext:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(ciImage:ciContext:)"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTBgrRawImageFactory","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}],"path":"\/metadata\/fragments"},{"value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(ciImage:ciContext:)"]}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTBgrRawImageFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTBgrRawImageFactory","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory\/fragments","op":"replace"},{"op":"replace","value":"createWithCgImage:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(cgImage:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(cgImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"}]},{"value":"createWithCiImage:ciContext:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments"}]}]}