{"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"title":"NFC reading","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error"],"anchor":"NFC-reading"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNCardAccessNumberPassword) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"},"abstract":[{"text":"Card Access Number as a password.","type":"text"}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/init(value:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/value"],"anchor":"Instance-Properties"},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"],"anchor":"Enumerations"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"]}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"symbolKind":"class","title":"CardAccessNumberPassword","externalID":"c:@M@DotNfc@objc(cs)DOTNCardAccessNumberPassword","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"role":"symbol","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"title":"CardAccessNumberPassword.Error","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"title":"MachineReadableZonePassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword","type":"topic","navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult":{"kind":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult","role":"symbol","abstract":[{"text":"Result of the NFC Travel Document Reader component.","type":"text"}],"title":"NfcTravelDocumentReaderResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"abstract":[{"text":"Password for accessing the chip.","type":"text"}],"navigatorTitle":[{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword","kind":"symbol","role":"symbol","title":"TravelDocumentReaderPassword","type":"topic"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/value":{"title":"value","type":"topic","abstract":[{"text":"Card Access Number in the 6-digits format.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/value","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/value","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}]},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/description":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/description","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"title":"CardAccessNumberPassword","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","abstract":[{"type":"text","text":"Card Access Number as a password."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CardAccessNumberPassword"}]},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/init(value:)":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/init(value:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/init(value:)","role":"symbol","navigatorTitle":[{"text":"initWithValue:error:","kind":"identifier"}],"title":"init(value:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","role":"symbol","title":"NfcTravelDocumentReader.Error","type":"topic"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTNCardAccessNumberPassword","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/value"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/init(value:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult"],"generated":true,"title":"NFC reading","anchor":"NFC-reading"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNCardAccessNumberPassword"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","op":"replace"},{"value":"DOTNNfcTravelDocumentReaderResult","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderResult"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderResult"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/navigatorTitle","op":"replace"},{"value":"DOTNTravelDocumentReaderPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/navigatorTitle","op":"replace"},{"value":"value","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1value\/title","op":"replace"},{"value":[{"kind":"identifier","text":"value"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1value\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1description\/fragments","op":"replace"},{"value":"DOTNCardAccessNumberPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle","op":"replace"},{"value":"initWithValue:error:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1init(value:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:error:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword~1init(value:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}