{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debuginfo"]},{"paths":["\/documentation\/dotnfc\/debuginfo"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNDebugInfo) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DebugInfo","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"DebugInfo","symbolKind":"class","navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DebugInfo","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Class","platforms":[{"beta":false,"deprecated":false,"introducedAt":"13.0","name":"iOS","unavailable":false}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/accessControlProtocol","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/activeAuthenticationChallenge","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/chipAuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/dataAuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/events","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/ldsMasterFile","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/nfcKey"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/isEqual(_:)"],"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"references":{"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/events":{"kind":"symbol","type":"topic","title":"events","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/events","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/events","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"events"},{"kind":"text","text":": ["},{"text":"DebugEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugEvent"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"events"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/chipAuthenticationStatus":{"kind":"symbol","title":"chipAuthenticationStatus","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/chipAuthenticationStatus","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/chipauthenticationstatus","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"chipAuthenticationStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","text":"ChipAuthenticationStatus"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"chipAuthenticationStatus"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/isEqual(_:)":{"kind":"symbol","title":"isEqual(_:)","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/isEqual(_:)","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/accessControlProtocol":{"kind":"symbol","title":"accessControlProtocol","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/accessControlProtocol","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/accesscontrolprotocol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlProtocol"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper","text":"AccessControlProtocolWrapper"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"accessControlProtocol","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo":{"title":"DebugInfo","url":"\/documentation\/dotnfc\/debuginfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DebugInfo"}],"navigatorTitle":[{"kind":"identifier","text":"DebugInfo"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/ldsMasterFile":{"kind":"symbol","title":"ldsMasterFile","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/ldsMasterFile","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/ldsmasterfile","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ldsMasterFile"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile","kind":"typeIdentifier","text":"LdsMasterFile"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"ldsMasterFile","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/activeAuthenticationChallenge":{"kind":"symbol","title":"activeAuthenticationChallenge","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/activeAuthenticationChallenge","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/activeauthenticationchallenge","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAuthenticationChallenge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"activeAuthenticationChallenge","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/description":{"kind":"symbol","title":"description","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/description","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/nfcKey":{"kind":"symbol","title":"nfcKey","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/nfcKey","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/nfckey","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"nfcKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","text":"NfcKey"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"nfcKey","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/hash":{"kind":"symbol","title":"hash","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/hash","abstract":[],"url":"\/documentation\/dotnfc\/debuginfo\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/dataAuthenticationStatus":{"title":"dataAuthenticationStatus","url":"\/documentation\/dotnfc\/debuginfo\/dataauthenticationstatus","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dataAuthenticationStatus","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","text":"DataAuthenticationStatus"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dataAuthenticationStatus"}],"kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/dataAuthenticationStatus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTNDebugInfo"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNDebugInfo"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNDebugInfo"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/accessControlProtocol","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/activeAuthenticationChallenge","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/chipAuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/dataAuthenticationStatus","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/events","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/ldsMasterFile","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/nfcKey"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/isEqual(_:)"]}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTNDebugInfo","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","value":"events","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1events\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1events\/fragments","value":[{"kind":"identifier","text":"events"}],"op":"replace"},{"op":"replace","value":"chipAuthenticationStatus","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1chipAuthenticationStatus\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1chipAuthenticationStatus\/fragments","value":[{"text":"chipAuthenticationStatus","kind":"identifier"}],"op":"replace"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1accessControlProtocol\/title","op":"replace","value":"accessControlProtocol"},{"value":[{"text":"accessControlProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1accessControlProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo\/title","value":"DOTNDebugInfo","op":"replace"},{"op":"replace","value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1ldsMasterFile\/title","op":"replace","value":"ldsMasterFile"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1ldsMasterFile\/fragments","value":[{"kind":"identifier","text":"ldsMasterFile"}]},{"value":"activeAuthenticationChallenge","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1activeAuthenticationChallenge\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1activeAuthenticationChallenge\/fragments","value":[{"text":"activeAuthenticationChallenge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1description\/title","op":"replace","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1description\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1nfcKey\/title","op":"replace","value":"nfcKey"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1nfcKey\/fragments","value":[{"kind":"identifier","text":"nfcKey"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1hash\/title","op":"replace","value":"hash"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1hash\/fragments"},{"op":"replace","value":"dataAuthenticationStatus","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1dataAuthenticationStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1dataAuthenticationStatus\/fragments","value":[{"text":"dataAuthenticationStatus","kind":"identifier"}]}]}]}