{"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/message","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/timestamp"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/isEqual(_:)"],"title":"Instance Methods"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Class","title":"DebugEvent","externalID":"c:@M@DotNfc@objc(cs)DOTNDebugEvent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DebugEvent","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DebugEvent"}],"symbolKind":"class"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNDebugEvent) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugEvent","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/debugevent"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debugevent"]}],"references":{"doc://DotNfc/documentation/DotNfc/DebugEvent/isEqual(_:)":{"url":"\/documentation\/dotnfc\/debugevent\/isequal(_:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/isEqual(_:)","abstract":[],"title":"isEqual(_:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://DotNfc/documentation/DotNfc/DebugEvent":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugEvent"}],"navigatorTitle":[{"text":"DebugEvent","kind":"identifier"}],"title":"DebugEvent","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","url":"\/documentation\/dotnfc\/debugevent"},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/DebugEvent/hash":{"url":"\/documentation\/dotnfc\/debugevent\/hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/hash","type":"topic","abstract":[],"title":"hash","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/DebugEvent/description":{"url":"\/documentation\/dotnfc\/debugevent\/description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/description","type":"topic","abstract":[],"title":"description","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotNfc/documentation/DotNfc/DebugEvent/timestamp":{"url":"\/documentation\/dotnfc\/debugevent\/timestamp","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/timestamp","abstract":[],"title":"timestamp","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"timestamp","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"timestamp","kind":"identifier"}]},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/documentation/DotNfc/DebugEvent/message":{"url":"\/documentation\/dotnfc\/debugevent\/message","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/message","type":"topic","abstract":[],"title":"message","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"message"}]},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTNDebugEvent"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTNDebugEvent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTNDebugEvent","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/message","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/timestamp"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTNDebugEvent"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1isEqual(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/title","value":"DOTNDebugEvent"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/fragments","op":"replace","value":[{"text":"DOTNDebugEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1hash\/title","value":"hash"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"value":"timestamp","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1timestamp\/title"},{"value":[{"text":"timestamp","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1timestamp\/fragments","op":"replace"},{"op":"replace","value":"message","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1message\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1message\/fragments","value":[{"text":"message","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}