{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Face background uniformity module."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","title":"DotFaceBackgroundUniformityModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceBackgroundUniformityModuleConfiguration":{"abstract":[{"text":"Face background uniformity module.","type":"text"}],"role":"symbol","type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","url":"\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceBackgroundUniformityModuleConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","title":"init","url":"\/documentation\/dotnfc\/dotfacebackgrounduniformitymoduleconfiguration\/init","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration\/init","type":"topic","kind":"symbol","abstract":[]},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},{"op":"add","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceBackgroundUniformityModuleConfiguration\/init"],"title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/title","op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"}]}]}