{"abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"roleHeading":"Class","title":"DotFaceEyeGazeLivenessModuleConfiguration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/DotFaceEyeGazeLivenessModuleConfiguration/init":{"url":"\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration\/init","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration\/init"},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotFaceEyeGazeLivenessModuleConfiguration":{"navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration\/init"],"anchor":"Instance-Methods"}],"op":"add","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle"}]}]}