{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Face expression neutral module."}],"kind":"symbol","metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","title":"DotFaceExpressionNeutralModuleConfiguration","modules":[{"name":"DotNfc"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceExpressionNeutralModuleConfiguration/init":{"abstract":[],"url":"\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration\/init","type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration\/init","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotFaceExpressionNeutralModuleConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"title":"DotFaceExpressionNeutralModuleConfiguration","url":"\/documentation\/dotnfc\/dotfaceexpressionneutralmoduleconfiguration","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration","abstract":[{"type":"text","text":"Face expression neutral module."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceExpressionNeutralModuleConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceExpressionNeutralModuleConfiguration\/init"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"add","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}