{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"paths":["\/documentation\/dotnfc\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"kind":"relationships","type":"conformsTo"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionFast","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/verification"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/description"],"anchor":"Instance-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"title":"DotFaceModuleId","externalID":"c:@M@DotCore@E@DotFaceModuleId","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/RawRepresentable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/dotnfc\/dotfacemoduleid\/rawrepresentable-implementations","type":"topic"},"doc://DotNfc/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/verification":{"title":"DotFaceModuleId.verification","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/verification","url":"\/documentation\/dotnfc\/dotfacemoduleid\/verification","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}]},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/passiveLiveness":{"abstract":[],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/passiveLiveness","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"title":"DotFaceModuleId.passiveLiveness","url":"\/documentation\/dotnfc\/dotfacemoduleid\/passiveliveness","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/backgroundUniformity":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"kind":"symbol","title":"DotFaceModuleId.backgroundUniformity","url":"\/documentation\/dotnfc\/dotfacemoduleid\/backgrounduniformity","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/backgroundUniformity","navigatorTitle":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"title":"DotFaceModuleId","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"url":"\/documentation\/dotnfc\/dotfacemoduleid"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/expressionNeutral":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/expressionNeutral","title":"DotFaceModuleId.expressionNeutral","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"expressionNeutral","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/dotfacemoduleid\/expressionneutral"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/init(rawValue:)":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotnfc\/dotfacemoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/init(rawValue:)"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/Equatable-Implementations":{"abstract":[],"kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/dotnfc\/dotfacemoduleid\/equatable-implementations","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/eyeGazeLiveness":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}],"title":"DotFaceModuleId.eyeGazeLiveness","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"eyeGazeLiveness","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/eyeGazeLiveness","url":"\/documentation\/dotnfc\/dotfacemoduleid\/eyegazeliveness"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/detectionFast":{"url":"\/documentation\/dotnfc\/dotfacemoduleid\/detectionfast","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"role":"symbol","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionFast"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionFast","title":"DotFaceModuleId.detectionFast"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/description":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/description","role":"symbol","url":"\/documentation\/dotnfc\/dotfacemoduleid\/description","title":"description","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/detectionBalanced":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"title":"DotFaceModuleId.detectionBalanced","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionBalanced","url":"\/documentation\/dotnfc\/dotfacemoduleid\/detectionbalanced"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleId","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/detectionFast","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/verification"],"generated":true}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1verification\/title","op":"replace","value":"DotFaceModuleIdVerification"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1verification\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}]},{"op":"replace","value":"DotFaceModuleIdPassiveLiveness","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1passiveLiveness\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1passiveLiveness\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1backgroundUniformity\/title","value":"DotFaceModuleIdBackgroundUniformity"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1backgroundUniformity\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}]},{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"op":"replace","value":"DotFaceModuleIdExpressionNeutral","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1expressionNeutral\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1expressionNeutral\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1eyeGazeLiveness\/title","value":"DotFaceModuleIdEyeGazeLiveness"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1eyeGazeLiveness\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}]},{"op":"replace","value":"DotFaceModuleIdDetectionFast","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1detectionFast\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1detectionFast\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1detectionBalanced\/title","value":"DotFaceModuleIdDetectionBalanced"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId~1detectionBalanced\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}]}]}]}