{"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"metadata":{"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"title":"DotFingersDetectionModuleConfiguration","externalID":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"sections":[],"references":{"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration/init":{"url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration\/init","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"type":"topic","url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration","role":"symbol","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"title":"DotFingersDetectionModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFingersDetectionModuleConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},{"op":"add","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration\/init"],"generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]}]}]}