{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/document","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/face","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/faceLite","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/nfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/palm"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/description"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/RawRepresentable-Implementations"]}],"variants":[{"paths":["\/documentation\/dotnfc\/dotlibraryid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotlibraryid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"roleHeading":"Enumeration","title":"DotLibraryId","externalID":"c:@M@DotCore@E@DotLibraryId","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotLibraryId/document":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/document","url":"\/documentation\/dotnfc\/dotlibraryid\/document","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"code":"DotDocumentLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"title":"DotLibraryId.document","navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/dotnfc\/dotlibraryid\/equatable-implementations","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/Equatable-Implementations"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/face":{"type":"topic","title":"DotLibraryId.face","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid\/face","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdFace","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFaceLibrary"},{"text":" identifier.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/face"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/faceLite":{"type":"topic","title":"DotLibraryId.faceLite","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid\/facelite","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"text":" identifier.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/faceLite"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/nfc":{"type":"topic","title":"DotLibraryId.nfc","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid\/nfc","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"text":" identifier.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/nfc"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.10.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","type":"topic","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/description":{"type":"topic","title":"description","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/description"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/dotnfc\/dotlibraryid\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/RawRepresentable-Implementations"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/init(rawValue:)"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"type":"topic","title":"DotLibraryId","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"},"doc://DotNfc/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/palm":{"type":"topic","title":"DotLibraryId.palm","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid\/palm","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotPalmLibrary"},{"text":" identifier.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/palm"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"DotLibraryId","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/document","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/face","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/faceLite","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/nfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/palm"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1document\/title","value":"DotLibraryIdDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1document\/fragments","op":"replace","value":[{"text":"DotLibraryIdDocument","kind":"identifier"}]},{"value":"DotLibraryIdFace","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1face\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1face\/fragments","value":[{"text":"DotLibraryIdFace","kind":"identifier"}]},{"value":"DotLibraryIdFaceLite","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1faceLite\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1faceLite\/fragments","op":"replace","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1nfc\/title","value":"DotLibraryIdNfc"},{"value":[{"kind":"identifier","text":"DotLibraryIdNfc"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1nfc\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1palm\/title","value":"DotLibraryIdPalm","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1palm\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"op":"replace"}]}]}