{"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary","doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"}],"role":"symbol","modules":[{"name":"DotNfc"}],"title":"DotNfcLibrary","externalID":"c:@M@DotNfc@objc(cs)DotNfcLibrary","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotNfcLibrary","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"DotNfcLibrary","kind":"identifier"}]},"seeAlsoSections":[{"title":"Global components","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotNfcLibrary","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":" library initialization.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/init()"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/id"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/deinitialize()","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/initialize(license:)"],"title":"Instance Methods"},{"title":"Enumerations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error"]}],"references":{"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/documentation/DotNfc/Localization":{"url":"\/documentation\/dotnfc\/localization","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization","kind":"symbol","title":"Localization","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"role":"symbol","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Localization"}]},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","title":"DotNfcLibrary","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibrary","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotNfc"},{"text":" library initialization.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"DotNfcLibrary","kind":"identifier"}]},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/deinitialize()":{"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotnfc\/dotnfclibrary\/deinitialize()","title":"deinitialize()","role":"symbol","type":"topic","abstract":[{"text":"Deinitialize library.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/deinitialize()"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/Error":{"kind":"symbol","title":"DotNfcLibrary.Error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error","role":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/initialize(license:)":{"url":"\/documentation\/dotnfc\/dotnfclibrary\/initialize(license:)","kind":"symbol","abstract":[{"text":"Initialize library with license.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/initialize(license:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"title":"initialize(license:)","type":"topic"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/id":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"id","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/id","url":"\/documentation\/dotnfc\/dotnfclibrary\/id","abstract":[{"text":"The library identifier.","type":"text"}],"title":"id","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary\/init()","role":"symbol","abstract":[],"title":"init()","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/init()"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.15.1"}],"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","role":"collection"},"doc://DotNfc/documentation/DotNfc/Logger":{"url":"\/documentation\/dotnfc\/logger","kind":"symbol","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"role":"symbol","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"title":"Logger","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotLibrary":{"url":"\/documentation\/dotnfc\/dotlibrary","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"kind":"symbol","title":"DotLibrary"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DotNfcLibrary"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotNfcLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DotNfcLibrary","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/id"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/deinitialize()","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/init()","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/initialize(license:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}]},{"op":"replace","value":[{"title":"Global components","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"]}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotNfcLibrary"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/title","value":"DOTNLocalization","op":"replace"},{"op":"replace","value":[{"text":"DOTNLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/title","value":"DotNfcLibrary"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotNfcLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1deinitialize()\/title","value":"deinitializeAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1initialize(license:)\/title","op":"replace","value":"initializeWithLicense:error:"},{"value":[{"text":"- ","kind":"text"},{"text":"initializeWithLicense:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1initialize(license:)\/fragments"},{"op":"replace","value":"id","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1id\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1id\/fragments","value":[{"kind":"identifier","text":"id"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/title","op":"replace","value":"DOTNLogger"},{"value":[{"text":"DOTNLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/fragments","op":"replace"},{"value":"DotLibrary","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/fragments","op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}]}]}]}