{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol"]},{"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/licenseBytes"],"title":"Instance Properties"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"modules":[{"name":"DotNfc"}],"title":"DotSdkLicenseProxyProtocol","role":"symbol","symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"roleHeading":"Protocol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfacematchingenabled","required":true,"navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isFaceMatchingEnabled","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"kind":"symbol","abstract":[],"title":"DotSdkLicenseProxyProtocol","url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"role":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isEvaluation":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isEvaluation","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isevaluation","required":true,"navigatorTitle":[{"kind":"identifier","text":"isEvaluation"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEvaluation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"isEvaluation"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","required":true,"navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isFaceEyeGazeLivenessScoreEnabled","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFacePassiveLivenessEnabled":{"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfacepassivelivenessenabled","role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","kind":"symbol","type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isFacePassiveLivenessEnabled","navigatorTitle":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}]},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"kind":"symbol","required":true,"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceliteenabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"type":"topic","title":"isFaceLiteEnabled","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isNfcEnabled":{"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isnfcenabled","abstract":[],"kind":"symbol","title":"isNfcEnabled","type":"topic","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNfcEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isNfcEnabled","role":"symbol","navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isdocumentenabled","required":true,"navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDocumentEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"isDocumentEnabled"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFaceEnabled":{"kind":"symbol","abstract":[],"title":"isFaceEnabled","required":true,"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceenabled","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/licenseBytes":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/licenseBytes","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/licensebytes","required":true,"navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseBytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"title":"licenseBytes","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","required":true,"navigatorTitle":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","title":"isRealTimeTransactionReportingEnabled"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isPalmEnabled":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isPalmEnabled","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/ispalmenabled","required":true,"navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPalmEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isPalmEnabled","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/licenseBytes"],"title":"Instance Properties"}]},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"isFaceMatchingEnabled","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title","op":"replace"},{"op":"replace","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"op":"replace","value":"isEvaluation","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isEvaluation\/title"},{"value":[{"text":"isEvaluation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isEvaluation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/title","value":"isFacePassiveLivenessEnabled","op":"replace"},{"value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/fragments","op":"replace"},{"value":"isFaceLiteEnabled","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title"},{"value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments"},{"value":"isNfcEnabled","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title"},{"op":"replace","value":[{"text":"isNfcEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments"},{"op":"replace","value":"isDocumentEnabled","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title"},{"value":[{"kind":"identifier","text":"isDocumentEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments"},{"value":"isFaceEnabled","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceEnabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1licenseBytes\/title","value":"licenseBytes","op":"replace"},{"value":[{"kind":"identifier","text":"licenseBytes"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1licenseBytes\/fragments"},{"op":"replace","value":"isRealTimeTransactionReportingEnabled","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments","op":"replace","value":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/title","value":"isPalmEnabled","op":"replace"},{"value":[{"kind":"identifier","text":"isPalmEnabled"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/fragments","op":"replace"}]}]}