{"sections":[],"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/licenseBytes"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxy"]},{"paths":["\/documentation\/dotnfc\/dotsdklicenseproxy"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"title":"Conforms To"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DotSdkLicenseProxy","symbolKind":"class","role":"symbol","title":"DotSdkLicenseProxy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}]}]}],"references":{"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isEvaluation":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEvaluation","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEvaluation","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isEvaluation","role":"symbol","url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isevaluation","abstract":[],"navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isFacePassiveLivenessEnabled":{"url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isfacepassivelivenessenabled","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isFacePassiveLivenessEnabled","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","abstract":[]},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isFaceLiteEnabled":{"title":"isFaceLiteEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceLiteEnabled","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isfaceliteenabled"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy","url":"\/documentation\/dotnfc\/dotsdklicenseproxy","title":"DotSdkLicenseProxy","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isFaceEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceEnabled","navigatorTitle":[{"kind":"identifier","text":"isFaceEnabled"}],"abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isfaceenabled","kind":"symbol","role":"symbol","title":"isFaceEnabled","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.3.1","type":"text"}],"url":"\/documentation\/dotnfc","type":"topic","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol","title":"DotSdkLicenseProxyProtocol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/licenseBytes":{"title":"licenseBytes","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/licenseBytes","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/licensebytes"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isRealTimeTransactionReportingEnabled":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"title":"isRealTimeTransactionReportingEnabled","url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isFaceEyeGazeLivenessScoreEnabled":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled","title":"isFaceEyeGazeLivenessScoreEnabled","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isDocumentEnabled":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDocumentEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isDocumentEnabled","kind":"symbol","role":"symbol","title":"isDocumentEnabled","navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isdocumentenabled","type":"topic","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isFaceMatchingEnabled":{"title":"isFaceMatchingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceMatchingEnabled","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isfacematchingenabled"},"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotSdkLicenseProxy/isNfcEnabled":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotsdklicenseproxy\/isnfcenabled","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isNfcEnabled","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isNfcEnabled"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DotSdkLicenseProxy","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxy\/licenseBytes"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol"],"title":"Conforms To","type":"conformsTo"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"isEvaluation","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isEvaluation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isEvaluation"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isEvaluation\/fragments"},{"value":"isFacePassiveLivenessEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/title","op":"replace"},{"op":"replace","value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title","value":"isFaceLiteEnabled"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceEnabled\/title","op":"replace","value":"isFaceEnabled"},{"value":[{"text":"isFaceEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceEnabled\/fragments","op":"replace"},{"value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"value":"licenseBytes","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1licenseBytes\/title"},{"op":"replace","value":[{"kind":"identifier","text":"licenseBytes"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1licenseBytes\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/title","op":"replace","value":"isRealTimeTransactionReportingEnabled"},{"value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isDocumentEnabled\/title","value":"isDocumentEnabled"},{"value":[{"kind":"identifier","text":"isDocumentEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isDocumentEnabled\/fragments"},{"value":"isFaceMatchingEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/fragments","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isNfcEnabled\/title","value":"isNfcEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotSdkLicenseProxy~1isNfcEnabled\/fragments","value":[{"kind":"identifier","text":"isNfcEnabled"}]}]}]}