{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"paths":["\/documentation\/dotnfc\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/init(format:bytes:size:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/bytes","doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/format","doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/size"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","type":"conformsTo"}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"symbolKind":"class","title":"Image","externalID":"c:@M@DotCore@objc(cs)DOTImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"roleHeading":"Class","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/Image/format":{"url":"\/documentation\/dotnfc\/image\/format","title":"format","kind":"symbol","abstract":[{"text":"Format of the stored image","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"format","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/format","role":"symbol","type":"topic"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/Image":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","url":"\/documentation\/dotnfc\/image","abstract":[],"title":"Image","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Image/init(format:bytes:size:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/init(format:bytes:size:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotnfc\/image\/init(format:bytes:size:)","title":"init(format:bytes:size:)","abstract":[]},"doc://DotNfc/documentation/DotNfc/Image/description":{"abstract":[],"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/description","kind":"symbol","url":"\/documentation\/dotnfc\/image\/description","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/Image/bytes":{"url":"\/documentation\/dotnfc\/image\/bytes","kind":"symbol","abstract":[{"text":"Raw image data.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/bytes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bytes"}],"title":"bytes","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}]},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/Image/size":{"abstract":[{"type":"text","text":"Image size."}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/size","url":"\/documentation\/dotnfc\/image\/size","kind":"symbol","role":"symbol","title":"size","type":"topic"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTImage","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/bytes","doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/format","doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/size"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"format","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1format\/title","op":"replace"},{"value":[{"kind":"identifier","text":"format"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1format\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","value":"DOTImage"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle","op":"replace"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1description\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1bytes\/title","value":"bytes"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}]},{"value":"size","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1size\/title","op":"replace"},{"value":[{"kind":"identifier","text":"size"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image~1size\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}