{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"sections":[],"metadata":{"role":"symbol","title":"ImageFactory","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"roleHeading":"Class"},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imagefactory"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgrRawImage(cgImage:)":{"type":"topic","kind":"symbol","title":"createBgrRawImage(cgImage:)","url":"\/documentation\/dotnfc\/imagefactory\/createbgrrawimage(cgimage:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(cgImage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}]},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/ImageFactory":{"title":"ImageFactory","kind":"symbol","url":"\/documentation\/dotnfc\/imagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"role":"symbol","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}]},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgraRawImage(cgImage:)":{"title":"createBgraRawImage(cgImage:)","kind":"symbol","url":"\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(cgimage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"role":"symbol","navigatorTitle":[{"text":"createBgraRawImageWithCgImage:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}]},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgrRawImage(ciImage:ciContext:)":{"type":"topic","url":"\/documentation\/dotnfc\/imagefactory\/createbgrrawimage(ciimage:cicontext:)","title":"createBgrRawImage(ciImage:ciContext:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"role":"symbol","navigatorTitle":[{"text":"createBgrRawImageWithCiImage:ciContext:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}]},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgraRawImage(bgrRawImage:)":{"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgr"},{"text":" format as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}],"title":"createBgraRawImage(bgrRawImage:)","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(bgrrawimage:)","navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(bgrRawImage:)"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotNfc/documentation/DotNfc/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"type":"topic","url":"\/documentation\/dotnfc\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","title":"createBgraRawImage(ciImage:ciContext:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTImageFactory","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Type-Methods","title":"Type Methods","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFactory"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createBgrRawImageWithCgImage:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgrRawImage(cgImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments"},{"value":"DOTImageFactory","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory\/navigatorTitle"},{"value":"createBgraRawImageWithCgImage:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(cgImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments"},{"value":"createBgrRawImageWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/fragments"},{"value":"createBgraRawImageWithBgrRawImage:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments"},{"value":"createBgraRawImageWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments"}]}]}