{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"IntervalDouble","roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DOTIntervalDouble","symbolKind":"class","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTIntervalDouble) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/intervaldouble"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/intervaldouble"]}],"kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/init(min:max:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/max","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/min"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/isEqual(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/Error"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble/hash":{"abstract":[],"url":"\/documentation\/dotnfc\/intervaldouble\/hash","title":"hash","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble/min":{"abstract":[{"text":"Minimal interval value.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"min","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/min","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"min"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"min","url":"\/documentation\/dotnfc\/intervaldouble\/min"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble","kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/intervaldouble","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble/max":{"title":"max","navigatorTitle":[{"text":"max","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Maximal interval value.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/max","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol","url":"\/documentation\/dotnfc\/intervaldouble\/max"},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble/init(min:max:)":{"title":"init(min:max:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"min","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"max","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotnfc\/intervaldouble\/init(min:max:)","navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:error:"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/init(min:max:)","abstract":[],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble/Error":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/Error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"IntervalDouble.Error","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/intervaldouble\/error","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble/isEqual(_:)":{"title":"isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotnfc\/intervaldouble\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/isEqual(_:)","abstract":[],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalDouble/description":{"kind":"symbol","title":"description","role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/intervaldouble\/description","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"kind":"symbol","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTIntervalDouble","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/max","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/min"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/init(min:max:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalDouble\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTIntervalDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1hash\/title","op":"replace","value":"hash"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1hash\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1min\/title","value":"min","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1min\/fragments","op":"replace","value":[{"text":"min","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1max\/title","op":"replace","value":"max"},{"op":"replace","value":[{"text":"max","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1max\/fragments"},{"value":"initWithMin:max:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1init(min:max:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1init(min:max:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMin:max:error:","kind":"identifier"}],"op":"replace"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1isEqual(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1description\/title","op":"replace","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalDouble~1description\/fragments","value":[{"kind":"identifier","text":"description"}]}]}]}