{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTIntervalFloat) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalFloat","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/intervalfloat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/intervalfloat"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat","symbolKind":"class","modules":[{"name":"DotNfc"}],"title":"IntervalFloat","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}]},"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/init(min:max:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/max","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/min"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/isEqual(_:)"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error"],"title":"Enumerations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error":{"title":"IntervalFloat.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/intervalfloat\/error"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/max":{"abstract":[{"text":"Maximal interval value.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/max","title":"max","url":"\/documentation\/dotnfc\/intervalfloat\/max","role":"symbol","navigatorTitle":[{"text":"max","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat/init(min:max:)":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/init(min:max:)","type":"topic","kind":"symbol","title":"init(min:max:)","url":"\/documentation\/dotnfc\/intervalfloat\/init(min:max:)","role":"symbol","navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/isEqual(_:)":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/isEqual(_:)","type":"topic","kind":"symbol","title":"isEqual(_:)","url":"\/documentation\/dotnfc\/intervalfloat\/isequal(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"url":"\/documentation\/dotnfc\/intervalfloat","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"title":"IntervalFloat","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalFloat","kind":"identifier"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/hash":{"title":"hash","type":"topic","url":"\/documentation\/dotnfc\/intervalfloat\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/hash"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/description":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/description","type":"topic","kind":"symbol","title":"description","url":"\/documentation\/dotnfc\/intervalfloat\/description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat/min":{"abstract":[{"type":"text","text":"Minimal interval value."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/min","title":"min","url":"\/documentation\/dotnfc\/intervalfloat\/min","role":"symbol","navigatorTitle":[{"text":"min","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"min","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}]},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTIntervalFloat","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/max","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/min"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/init(min:max:)","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/isEqual(_:)"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTIntervalFloat","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1max\/title","value":"max","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1max\/fragments","value":[{"kind":"identifier","text":"max"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1init(min:max:)\/title","value":"initWithMin:max:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithMin:max:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1init(min:max:)\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1isEqual(_:)\/fragments"},{"value":"DOTIntervalFloat","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments","op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1hash\/title","value":"hash","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1min\/title","value":"min"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1min\/fragments","value":[{"text":"min","kind":"identifier"}]}]}]}