{"seeAlsoSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"],"anchor":"Raw-content","title":"Raw content","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication","modules":[{"name":"DotNfc"}],"roleHeading":"Class","role":"symbol","title":"Lds1eMrtdApplication","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"identifier"}]},"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/comHeaderAndDataGroupPresenceInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg10SubstanceFeatures","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg11AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg12AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg13OptionalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg14SecurityOptions","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg15ActiveAuthenticationPublicKeyInfo","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg16PersonsToNotify","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg1MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg2EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg3AdditionalIdentificationFeatureFingers","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg4AdditionalIdentificationFeatureIrises","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg5DisplayedPortrait","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg7DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg8DataFeatures","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg9StructureFeatures","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/sodDocumentSecurityObject"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNLds1eMrtdApplication) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"},"sections":[],"abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg15ActiveAuthenticationPublicKeyInfo":{"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg15activeauthenticationpublickeyinfo","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg15ActiveAuthenticationPublicKeyInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg15ActiveAuthenticationPublicKeyInfo","title":"dg15ActiveAuthenticationPublicKeyInfo","abstract":[{"text":"Raw data group DG15.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dg15ActiveAuthenticationPublicKeyInfo"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg1MachineReadableZoneInformation":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"dg1MachineReadableZoneInformation"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg1MachineReadableZoneInformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"}],"title":"dg1MachineReadableZoneInformation","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg1machinereadablezoneinformation","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Raw data group DG1."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg1MachineReadableZoneInformation"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/isEqual(_:)":{"role":"symbol","kind":"symbol","title":"isEqual(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/isequal(_:)"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1eMrtdApplication"}],"navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"title":"Lds1eMrtdApplication","url":"\/documentation\/dotnfc\/lds1emrtdapplication","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg9StructureFeatures":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg9StructureFeatures","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"dg9StructureFeatures","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg9StructureFeatures","role":"symbol","navigatorTitle":[{"text":"dg9StructureFeatures","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg9structurefeatures","abstract":[{"text":"Raw data group DG9.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg11AdditionalPersonalDetails":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg11AdditionalPersonalDetails","abstract":[{"type":"text","text":"Raw data group DG11."}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg11additionalpersonaldetails","type":"topic","kind":"symbol","title":"dg11AdditionalPersonalDetails","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg11AdditionalPersonalDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dg11AdditionalPersonalDetails","kind":"identifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/sodDocumentSecurityObject":{"kind":"symbol","title":"sodDocumentSecurityObject","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/sodDocumentSecurityObject","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/soddocumentsecurityobject","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sodDocumentSecurityObject"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"}],"type":"topic","abstract":[{"text":"Raw data group SOD.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sodDocumentSecurityObject"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg14SecurityOptions":{"role":"symbol","title":"dg14SecurityOptions","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg14SecurityOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg14SecurityOptions","abstract":[{"type":"text","text":"Raw data group DG14."}],"type":"topic","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg14securityoptions","kind":"symbol","navigatorTitle":[{"text":"dg14SecurityOptions","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg12AdditionalDocumentDetails":{"title":"dg12AdditionalDocumentDetails","navigatorTitle":[{"text":"dg12AdditionalDocumentDetails","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg12AdditionalDocumentDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg12additionaldocumentdetails","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg12AdditionalDocumentDetails","abstract":[{"text":"Raw data group DG12.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/hash":{"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/hash","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/hash"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)":{"navigatorTitle":[{"text":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"comHeaderAndDataGroupPresenceInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sodDocumentSecurityObject","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dg1MachineReadableZoneInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dg2EncodedIdentificationFeaturesFace","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dg3AdditionalIdentificationFeatureFingers","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg5DisplayedPortrait","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg8DataFeatures","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg9StructureFeatures","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg10SubstanceFeatures","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg11AdditionalPersonalDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg12AdditionalDocumentDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg13OptionalDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg14SecurityOptions","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/init(comheaderanddatagrouppresenceinformation:soddocumentsecurityobject:dg1machinereadablezoneinformation:dg2encodedidentificationfeaturesface:dg3additionalidentificationfeaturefingers:dg4additionalidentificationfeatureirises:dg5displayedpo-4j37l","title":"init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"role":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg3AdditionalIdentificationFeatureFingers":{"title":"dg3AdditionalIdentificationFeatureFingers","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg3additionalidentificationfeaturefingers","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dg3AdditionalIdentificationFeatureFingers"}],"abstract":[{"text":"Raw data group DG3.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg3AdditionalIdentificationFeatureFingers","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","title":"Lds1ElementaryFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFile"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile","abstract":[{"text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"type":"topic"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg5DisplayedPortrait":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg5DisplayedPortrait","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg5DisplayedPortrait","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"dg5DisplayedPortrait","abstract":[{"type":"text","text":"Raw data group DG5."}],"navigatorTitle":[{"text":"dg5DisplayedPortrait","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg5displayedportrait"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"title":"LdsMasterFile","kind":"symbol","url":"\/documentation\/dotnfc\/ldsmasterfile","type":"topic","abstract":[{"text":"Raw represenation of the whole content stored in the NFC chip of the travel document.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LdsMasterFile"}],"navigatorTitle":[{"kind":"identifier","text":"LdsMasterFile"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg4AdditionalIdentificationFeatureIrises":{"role":"symbol","abstract":[{"type":"text","text":"Raw data group DG4."}],"kind":"symbol","title":"dg4AdditionalIdentificationFeatureIrises","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg4AdditionalIdentificationFeatureIrises"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dg4AdditionalIdentificationFeatureIrises","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg4AdditionalIdentificationFeatureIrises","type":"topic","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg4additionalidentificationfeatureirises"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg2EncodedIdentificationFeaturesFace":{"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg2encodedidentificationfeaturesface","role":"symbol","navigatorTitle":[{"text":"dg2EncodedIdentificationFeaturesFace","kind":"identifier"}],"kind":"symbol","title":"dg2EncodedIdentificationFeaturesFace","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg2EncodedIdentificationFeaturesFace","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg2EncodedIdentificationFeaturesFace","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Raw data group DG2."}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/comHeaderAndDataGroupPresenceInformation":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/comHeaderAndDataGroupPresenceInformation","navigatorTitle":[{"kind":"identifier","text":"comHeaderAndDataGroupPresenceInformation"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/comheaderanddatagrouppresenceinformation","abstract":[{"type":"text","text":"Raw data group COM."}],"title":"comHeaderAndDataGroupPresenceInformation","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"comHeaderAndDataGroupPresenceInformation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg13OptionalDetails":{"abstract":[{"type":"text","text":"Raw data group DG13."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg13OptionalDetails","title":"dg13OptionalDetails","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg13optionaldetails","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg13OptionalDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dg13OptionalDetails","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg8DataFeatures":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg8DataFeatures","kind":"symbol","role":"symbol","title":"dg8DataFeatures","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg8DataFeatures","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dg8DataFeatures","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg8datafeatures","type":"topic","abstract":[{"text":"Raw data group DG8.","type":"text"}]},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg10SubstanceFeatures":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg10SubstanceFeatures","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"dg10SubstanceFeatures","kind":"identifier"}],"type":"topic","title":"dg10SubstanceFeatures","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg10SubstanceFeatures","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg10substancefeatures","abstract":[{"text":"Raw data group DG10.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg16PersonsToNotify":{"navigatorTitle":[{"text":"dg16PersonsToNotify","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Raw data group DG16.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg16personstonotify","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg16PersonsToNotify","type":"topic","title":"dg16PersonsToNotify","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg16PersonsToNotify","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg7DisplayedSignatureOrUsualMark":{"kind":"symbol","abstract":[{"text":"Raw data group DG7.","type":"text"}],"title":"dg7DisplayedSignatureOrUsualMark","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg7displayedsignatureorusualmark","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg7DisplayedSignatureOrUsualMark","role":"symbol","navigatorTitle":[{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg7DisplayedSignatureOrUsualMark","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/description":{"abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/description","title":"description","kind":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1eMrtdApplication"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/comHeaderAndDataGroupPresenceInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg10SubstanceFeatures","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg11AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg12AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg13OptionalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg14SecurityOptions","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg15ActiveAuthenticationPublicKeyInfo","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg16PersonsToNotify","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg1MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg2EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg3AdditionalIdentificationFeatureFingers","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg4AdditionalIdentificationFeatureIrises","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg5DisplayedPortrait","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg7DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg8DataFeatures","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg9StructureFeatures","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/sodDocumentSecurityObject"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/isEqual(_:)"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Raw content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"],"generated":true,"anchor":"Raw-content"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNLds1eMrtdApplication","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg15ActiveAuthenticationPublicKeyInfo\/title","value":"dg15ActiveAuthenticationPublicKeyInfo"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg15ActiveAuthenticationPublicKeyInfo\/fragments","value":[{"text":"dg15ActiveAuthenticationPublicKeyInfo","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg1MachineReadableZoneInformation\/title","value":"dg1MachineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg1MachineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"dg1MachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","value":"DOTNLds1eMrtdApplication"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/navigatorTitle","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg9StructureFeatures\/title","value":"dg9StructureFeatures"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg9StructureFeatures\/fragments","value":[{"text":"dg9StructureFeatures","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg11AdditionalPersonalDetails\/title","value":"dg11AdditionalPersonalDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg11AdditionalPersonalDetails\/fragments","value":[{"text":"dg11AdditionalPersonalDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1sodDocumentSecurityObject\/title","value":"sodDocumentSecurityObject"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1sodDocumentSecurityObject\/fragments","value":[{"text":"sodDocumentSecurityObject","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg14SecurityOptions\/title","value":"dg14SecurityOptions"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg14SecurityOptions\/fragments","value":[{"text":"dg14SecurityOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg12AdditionalDocumentDetails\/title","value":"dg12AdditionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg12AdditionalDocumentDetails\/fragments","value":[{"kind":"identifier","text":"dg12AdditionalDocumentDetails"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)\/title","value":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1init(comHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithComHeaderAndDataGroupPresenceInformation:sodDocumentSecurityObject:dg1MachineReadableZoneInformation:dg2EncodedIdentificationFeaturesFace:dg3AdditionalIdentificationFeatureFingers:dg4AdditionalIdentificationFeatureIrises:dg5DisplayedPortrait:dg7DisplayedSignatureOrUsualMark:dg8DataFeatures:dg9StructureFeatures:dg10SubstanceFeatures:dg11AdditionalPersonalDetails:dg12AdditionalDocumentDetails:dg13OptionalDetails:dg14SecurityOptions:dg15ActiveAuthenticationPublicKeyInfo:dg16PersonsToNotify:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg3AdditionalIdentificationFeatureFingers\/title","value":"dg3AdditionalIdentificationFeatureFingers"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg3AdditionalIdentificationFeatureFingers\/fragments","value":[{"text":"dg3AdditionalIdentificationFeatureFingers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","value":"DOTNLds1ElementaryFile"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg5DisplayedPortrait\/title","value":"dg5DisplayedPortrait"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg5DisplayedPortrait\/fragments","value":[{"kind":"identifier","text":"dg5DisplayedPortrait"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title","value":"DOTNLdsMasterFile"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/navigatorTitle","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg4AdditionalIdentificationFeatureIrises\/title","value":"dg4AdditionalIdentificationFeatureIrises"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg4AdditionalIdentificationFeatureIrises\/fragments","value":[{"kind":"identifier","text":"dg4AdditionalIdentificationFeatureIrises"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg2EncodedIdentificationFeaturesFace\/title","value":"dg2EncodedIdentificationFeaturesFace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg2EncodedIdentificationFeaturesFace\/fragments","value":[{"kind":"identifier","text":"dg2EncodedIdentificationFeaturesFace"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1comHeaderAndDataGroupPresenceInformation\/title","value":"comHeaderAndDataGroupPresenceInformation"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1comHeaderAndDataGroupPresenceInformation\/fragments","value":[{"kind":"identifier","text":"comHeaderAndDataGroupPresenceInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg13OptionalDetails\/title","value":"dg13OptionalDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg13OptionalDetails\/fragments","value":[{"text":"dg13OptionalDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg8DataFeatures\/title","value":"dg8DataFeatures"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg8DataFeatures\/fragments","value":[{"kind":"identifier","text":"dg8DataFeatures"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg10SubstanceFeatures\/title","value":"dg10SubstanceFeatures"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg10SubstanceFeatures\/fragments","value":[{"kind":"identifier","text":"dg10SubstanceFeatures"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg16PersonsToNotify\/title","value":"dg16PersonsToNotify"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg16PersonsToNotify\/fragments","value":[{"kind":"identifier","text":"dg16PersonsToNotify"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg7DisplayedSignatureOrUsualMark\/title","value":"dg7DisplayedSignatureOrUsualMark"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg7DisplayedSignatureOrUsualMark\/fragments","value":[{"kind":"identifier","text":"dg7DisplayedSignatureOrUsualMark"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1description\/fragments","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}