{"seeAlsoSections":[{"title":"Raw content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"],"anchor":"Raw-content","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/init(id:bytes:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/bytes","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/id"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true}],"metadata":{"symbolKind":"class","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"title":"Lds1ElementaryFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFile"}]},"sections":[],"abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfile"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfile"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNLds1ElementaryFile) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFile"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"]]},"references":{"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1eMrtdApplication"}],"title":"Lds1eMrtdApplication","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"abstract":[{"text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication","kind":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/init(id:bytes:)":{"role":"symbol","title":"init(id:bytes:)","abstract":[],"url":"\/documentation\/dotnfc\/lds1elementaryfile\/init(id:bytes:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/init(id:bytes:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Lds1ElementaryFileId","preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithId:bytes:"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/id":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"File identifier."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","kind":"typeIdentifier","text":"Lds1ElementaryFileId"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/id","title":"id","url":"\/documentation\/dotnfc\/lds1elementaryfile\/id","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"id"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"role":"symbol","kind":"symbol","type":"topic","title":"Lds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/lds1elementaryfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFile"}],"navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/bytes":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/bytes","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"title":"bytes","url":"\/documentation\/dotnfc\/lds1elementaryfile\/bytes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bytes"}],"kind":"symbol","abstract":[{"type":"text","text":"File data."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"title":"TravelDocument","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/isEqual(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfile\/isequal(_:)","title":"isEqual(_:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/isEqual(_:)"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/hash":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/hash","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile\/hash","title":"hash","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile/description":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotnfc\/lds1elementaryfile\/description","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/description","title":"description"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"type":"topic","abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"kind":"symbol","url":"\/documentation\/dotnfc\/ldsmasterfile","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LdsMasterFile"}],"navigatorTitle":[{"kind":"identifier","text":"LdsMasterFile"}],"title":"LdsMasterFile"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTNLds1ElementaryFile"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/bytes","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/id"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/init(id:bytes:)","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"anchor":"Raw-content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"],"title":"Raw content"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNLds1ElementaryFile","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","op":"replace","value":"DOTNLds1eMrtdApplication"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1init(id:bytes:)\/title","value":"initWithId:bytes:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1init(id:bytes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithId:bytes:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1id\/title","value":"id","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","value":"DOTNLds1ElementaryFile","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1bytes\/title","value":"bytes","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title","value":"DOTNLdsMasterFile","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments","value":[{"kind":"identifier","text":"DOTNLdsMasterFile"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/navigatorTitle","value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}