{"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/init(document:face:faceLite:nfc:palm:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/document","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/face","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/faceLite","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/nfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/palm"],"anchor":"Instance-Properties"}],"sections":[],"abstract":[{"type":"text","text":"Container for library configurations."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/libraries"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/libraries"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"Libraries","roleHeading":"Class","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"modules":[{"name":"DotNfc"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)Libraries"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"references":{"doc://DotNfc/documentation/DotNfc/Libraries/face":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/face","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Face library configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/libraries\/face","role":"symbol","title":"face","navigatorTitle":[{"text":"face","kind":"identifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Libraries/faceLite":{"type":"topic","abstract":[{"type":"text","text":"Face Lite library configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/faceLite","url":"\/documentation\/dotnfc\/libraries\/facelite","role":"symbol","title":"faceLite","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"faceLite"}],"kind":"symbol"},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/Libraries/palm":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"palm"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/palm","title":"palm","url":"\/documentation\/dotnfc\/libraries\/palm","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"kind":"symbol","title":"Libraries","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"url":"\/documentation\/dotnfc\/libraries","type":"topic"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/Libraries/document":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"text":"?","kind":"text"}],"kind":"symbol","title":"document","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/document","abstract":[{"type":"text","text":"Document library configuration."}],"navigatorTitle":[{"text":"document","kind":"identifier"}],"url":"\/documentation\/dotnfc\/libraries\/document","type":"topic"},"doc://DotNfc/documentation/DotNfc/Libraries/nfc":{"abstract":[{"text":"NFC library configuration.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/nfc","title":"nfc","kind":"symbol","url":"\/documentation\/dotnfc\/libraries\/nfc","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"nfc"}]},"doc://DotNfc/documentation/DotNfc/Libraries/init(document:face:faceLite:nfc:palm:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}],"abstract":[],"kind":"symbol","title":"init(document:face:faceLite:nfc:palm:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/init(document:face:faceLite:nfc:palm:)","type":"topic","url":"\/documentation\/dotnfc\/libraries\/init(document:face:facelite:nfc:palm:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"Libraries","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/document","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/face","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/faceLite","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/nfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/palm"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/init(document:face:faceLite:nfc:palm:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"face","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1face\/title"},{"value":[{"kind":"identifier","text":"face"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1face\/fragments","op":"replace"},{"value":"faceLite","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1faceLite\/title","op":"replace"},{"value":[{"text":"faceLite","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1faceLite\/fragments","op":"replace"},{"value":"palm","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1palm\/title","op":"replace"},{"value":[{"kind":"identifier","text":"palm"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1palm\/fragments","op":"replace"},{"value":"Libraries","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","op":"replace"},{"value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle","op":"replace"},{"value":"document","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1document\/title","op":"replace"},{"value":[{"text":"document","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1document\/fragments","op":"replace"},{"value":"nfc","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1nfc\/title","op":"replace"},{"value":[{"text":"nfc","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1nfc\/fragments","op":"replace"},{"value":"initWithDocument:face:faceLite:nfc:palm:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1init(document:face:faceLite:nfc:palm:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1init(document:face:faceLite:nfc:palm:)\/fragments","op":"replace"}]}]}