{"relationshipsSections":[{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"title":"Conforms To"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"title":"LoggerLogLevel","roleHeading":"Enumeration","modules":[{"name":"DotNfc"}],"role":"symbol"},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/debug","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/error","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/info","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/none","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/warning"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/init(rawValue:)"],"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/description"],"title":"Instance Properties"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"abstract":[{"type":"text","text":"Available log levels."}],"variants":[{"paths":["\/documentation\/dotnfc\/loggerloglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/loggerloglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTLoggerLogLevel) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/debug":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"abstract":[{"type":"text","text":"Logs events suitable for debugging purposes."}],"navigatorTitle":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/loggerloglevel\/debug","title":"LoggerLogLevel.debug","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/debug"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/info":{"title":"LoggerLogLevel.info","abstract":[{"text":"Logs informative events.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/loggerloglevel\/info","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/info","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/none":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"url":"\/documentation\/dotnfc\/loggerloglevel\/none","type":"topic","abstract":[{"type":"text","text":"Disables logging."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/none","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"title":"LoggerLogLevel.none","role":"symbol"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"abstract":[{"text":"Available log levels.","type":"text"}],"navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","url":"\/documentation\/dotnfc\/loggerloglevel","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/Equatable-Implementations":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/Equatable-Implementations","type":"topic","url":"\/documentation\/dotnfc\/loggerloglevel\/equatable-implementations","title":"Equatable Implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/error":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"url":"\/documentation\/dotnfc\/loggerloglevel\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/error","kind":"symbol","type":"topic","title":"LoggerLogLevel.error","role":"symbol","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/warning":{"kind":"symbol","title":"LoggerLogLevel.warning","url":"\/documentation\/dotnfc\/loggerloglevel\/warning","navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/warning","type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/init(rawValue:)","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/loggerloglevel\/init(rawvalue:)"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/description":{"url":"\/documentation\/dotnfc\/loggerloglevel\/description","title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/description","role":"symbol","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/SY":{"identifier":"doc:\/\/DotNfc\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel/RawRepresentable-Implementations":{"abstract":[],"kind":"article","url":"\/documentation\/dotnfc\/loggerloglevel\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevel"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/debug","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/error","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/info","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/none","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel\/warning"]}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTLoggerLogLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1debug\/title","op":"replace","value":"DOTLoggerLogLevelDebug"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1debug\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1info\/title","op":"replace","value":"DOTLoggerLogLevelInfo"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1info\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1none\/title","op":"replace","value":"DOTLoggerLogLevelNone"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1none\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1error\/title","op":"replace","value":"DOTLoggerLogLevelError"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1error\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1warning\/title","op":"replace","value":"DOTLoggerLogLevelWarning"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel~1warning\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}]}]}]}