{"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"seeAlsoSections":[{"title":"Structured content","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"anchor":"Structured-content"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNMachineReadableZoneInformation) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}]}],"kind":"declarations"}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/init(machineReadableZone:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/machineReadableZone"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/isEqual(_:)"],"anchor":"Instance-Methods"}],"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"title":"MachineReadableZoneInformation","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","symbolKind":"class"},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","title":"DisplayedSignatureOrUsualMark","navigatorTitle":[{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation/init(machineReadableZone:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMachineReadableZone:"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/init(machineReadableZone:)","abstract":[],"role":"symbol","title":"init(machineReadableZone:)","type":"topic","url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/init(machinereadablezone:)"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation/hash":{"url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/hash","abstract":[],"type":"topic","title":"hash","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/isequal(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/isEqual(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","title":"isEqual(_:)","abstract":[],"role":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation/description":{"url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/description","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/description","type":"topic","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"url":"\/documentation\/dotnfc\/machinereadablezoneinformation","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZoneInformation"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"kind":"symbol","title":"MachineReadableZoneInformation","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","role":"symbol","abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface","abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"type":"topic","title":"EncodedIdentificationFeaturesFace","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation/machineReadableZone":{"navigatorTitle":[{"text":"machineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/machineReadableZone","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier"}],"type":"topic","title":"machineReadableZone","abstract":[{"text":"Contains parsed MRZ of one specific travel document type.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"url":"\/documentation\/dotnfc\/additionaldocumentdetails","abstract":[{"text":"Contents of DG12 - Additional document details.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","title":"AdditionalDocumentDetails","navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"url":"\/documentation\/dotnfc\/additionalpersonaldetails","abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","role":"symbol","title":"AdditionalPersonalDetails"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"url":"\/documentation\/dotnfc\/optionaldetails","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","title":"OptionalDetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionalDetails"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTNMachineReadableZoneInformation","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/machineReadableZone"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/init(machineReadableZone:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"title":"Structured content","generated":true,"anchor":"Structured-content"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1init(machineReadableZone:)\/title","value":"initWithMachineReadableZone:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1init(machineReadableZone:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMachineReadableZone:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZoneInformation"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title","op":"replace","value":"DOTNEncodedIdentificationFeaturesFace"},{"op":"replace","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments"},{"op":"replace","value":[{"text":"DOTNEncodedIdentificationFeaturesFace","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/navigatorTitle"},{"op":"replace","value":"machineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1machineReadableZone\/title"},{"op":"replace","value":[{"text":"machineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1machineReadableZone\/fragments"},{"value":"DOTNAdditionalDocumentDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title"},{"value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNAdditionalDocumentDetails"}]},{"op":"replace","value":"DOTNAdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails"},{"op":"replace","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/navigatorTitle","op":"replace","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}]}]}]}