{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"abstract":[{"type":"text","text":"Password from Machine Readable Zone."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNMachineReadableZonePassword) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZonePassword"}],"platforms":["iOS"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/init(documentNumber:dateOfExpiry:dateOfBirth:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfBirth","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfExpiry","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/documentNumber"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"],"title":"Enumerations","anchor":"Enumerations","generated":true}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error"],"title":"NFC reading","anchor":"NFC-reading","generated":true}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"title":"MachineReadableZonePassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZonePassword"},"references":{"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/NfcKey":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","type":"topic","kind":"symbol","deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"title":"NfcKey","role":"symbol","url":"\/documentation\/dotnfc\/nfckey","abstract":[{"text":"NFC password created from document number, date of expiry and date of birth of MRZ.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","title":"MachineReadableZonePassword.Error","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.17.1"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/dateOfBirth":{"abstract":[{"type":"text","text":"Date of birth from Machine Readable Zone."}],"type":"topic","navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/dateofbirth","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfBirth","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","title":"dateOfBirth"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","title":"NfcTravelDocumentReader.Error","abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/documentNumber":{"type":"topic","abstract":[{"text":"Document number from Machine Readable Zone.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/documentNumber","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/documentnumber","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"documentNumber","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"documentNumber"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"abstract":[{"type":"text","text":"Password for accessing the chip."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"kind":"symbol","title":"TravelDocumentReaderPassword","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentReaderPassword"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/description":{"abstract":[],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/description","role":"symbol","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderResult"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderResult"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","type":"topic","title":"NfcTravelDocumentReaderResult","abstract":[{"type":"text","text":"Result of the NFC Travel Document Reader component."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/init(documentNumber:dateOfExpiry:dateOfBirth:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/init(documentNumber:dateOfExpiry:dateOfBirth:)","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/init(documentnumber:dateofexpiry:dateofbirth:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:"}],"kind":"symbol","role":"symbol","title":"init(documentNumber:dateOfExpiry:dateOfBirth:)"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"type":"topic","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword","title":"MachineReadableZonePassword","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"title":"CardAccessNumberPassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","role":"symbol","abstract":[{"type":"text","text":"Card Access Number as a password."}],"kind":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"navigatorTitle":[{"kind":"identifier","text":"CardAccessNumberPassword"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/dateOfExpiry":{"type":"topic","abstract":[{"type":"text","text":"Date of expiry from Machine Readable Zone."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfExpiry","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/dateofexpiry","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"dateOfExpiry","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"dateOfExpiry"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTNMachineReadableZonePassword","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfBirth","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/dateOfExpiry","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/documentNumber"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/init(documentNumber:dateOfExpiry:dateOfBirth:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult"],"generated":true,"title":"NFC reading","anchor":"NFC-reading"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNMachineReadableZonePassword"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTNNfcKey","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcKey"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcKey"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/navigatorTitle"},{"op":"replace","value":"dateOfBirth","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfBirth\/title"},{"op":"replace","value":[{"text":"dateOfBirth","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfBirth\/fragments"},{"op":"replace","value":"documentNumber","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1documentNumber\/title"},{"op":"replace","value":[{"kind":"identifier","text":"documentNumber"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1documentNumber\/fragments"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle"},{"op":"replace","value":"DOTNTravelDocumentReaderPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title"},{"op":"replace","value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments"},{"op":"replace","value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1description\/title"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1description\/fragments"},{"op":"replace","value":"DOTNNfcTravelDocumentReaderResult","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/title"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/fragments"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/navigatorTitle"},{"op":"replace","value":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1init(documentNumber:dateOfExpiry:dateOfBirth:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1init(documentNumber:dateOfExpiry:dateOfBirth:)\/fragments"},{"op":"replace","value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle"},{"op":"replace","value":"DOTNCardAccessNumberPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title"},{"op":"replace","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments"},{"op":"replace","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle"},{"op":"replace","value":"dateOfExpiry","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfExpiry\/title"},{"op":"replace","value":[{"text":"dateOfExpiry","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword~1dateOfExpiry\/fragments"}]}]}