{"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td1:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td2:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td3:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/lines","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td1","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td2","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td3"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/isEqual(_:)"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMachineReadableZone) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Class","title":"MachineReadableZone","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}]},"sections":[],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezone"]}],"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZone/hash":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/machinereadablezone\/hash","role":"symbol","title":"hash"},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/machinereadablezone\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","title":"description","type":"topic","role":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/td1":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td1","navigatorTitle":[{"text":"td1","kind":"identifier"}],"abstract":[{"text":"Parsed MRZ of TD1.","type":"text"}],"title":"td1","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td1","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/machinereadablezone\/td1","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/lines":{"url":"\/documentation\/dotnfc\/machinereadablezone\/lines","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/lines","navigatorTitle":[{"text":"lines","kind":"identifier"}],"title":"lines","abstract":[{"type":"text","text":"MRZ lines."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lines","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/isEqual(_:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/isEqual(_:)","role":"symbol","title":"isEqual(_:)","url":"\/documentation\/dotnfc\/machinereadablezone\/isequal(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/td3":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"td3"}],"title":"td3","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td3","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"td3"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone","kind":"typeIdentifier","text":"Td3MachineReadableZone"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/machinereadablezone\/td3","abstract":[{"type":"text","text":"Parsed MRZ of TD3."}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/td2":{"abstract":[{"text":"Parsed MRZ of TD2.","type":"text"}],"url":"\/documentation\/dotnfc\/machinereadablezone\/td2","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td2","title":"td2","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"td2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","text":"Td2MachineReadableZone"},{"kind":"text","text":"?"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"td2"}]},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/init(lines:td2:)":{"abstract":[],"url":"\/documentation\/dotnfc\/machinereadablezone\/init(lines:td2:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td2:)","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"td2","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Td2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(lines:td2:)","navigatorTitle":[{"text":"initWithLines:td2:","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/init(lines:td1:)":{"title":"init(lines:td1:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td1:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td1"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone","kind":"typeIdentifier","text":"Td1MachineReadableZone"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLines:td1:"}],"abstract":[],"url":"\/documentation\/dotnfc\/machinereadablezone\/init(lines:td1:)","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone":{"kind":"symbol","type":"topic","title":"MachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"url":"\/documentation\/dotnfc\/machinereadablezone","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/init(lines:td3:)":{"title":"init(lines:td3:)","abstract":[],"url":"\/documentation\/dotnfc\/machinereadablezone\/init(lines:td3:)","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td3:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td3"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone","kind":"typeIdentifier","text":"Td3MachineReadableZone"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLines:td3:"}]},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTMachineReadableZone"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/lines","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td1","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td2","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td3"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td1:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td2:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td3:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/isEqual(_:)"],"anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTMachineReadableZone","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td1\/title","op":"replace","value":"td1"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td1\/fragments","op":"replace","value":[{"text":"td1","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1lines\/title","op":"replace","value":"lines"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1lines\/fragments","op":"replace","value":[{"text":"lines","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td3\/title","op":"replace","value":"td3"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td3\/fragments","op":"replace","value":[{"kind":"identifier","text":"td3"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td2\/title","op":"replace","value":"td2"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td2\/fragments","op":"replace","value":[{"text":"td2","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td2:)\/title","op":"replace","value":"initWithLines:td2:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td2:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLines:td2:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td1:)\/title","op":"replace","value":"initWithLines:td1:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td1:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLines:td1:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/navigatorTitle","op":"replace","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td3:)\/title","op":"replace","value":"initWithLines:td3:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td3:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithLines:td3:","kind":"identifier"}]}]}]}