{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit"]},{"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTMrzElementWithCheckDigit) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/checkDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/hash"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"},"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","title":"MrzElementWithCheckDigit","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"role":"symbol"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"]},{"kind":"relationships","type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"references":{"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/isEqual(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"title":"isEqual(_:)","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/isEqual(_:)","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"text":" with parsed ","type":"text"},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","type":"topic","title":"MrzDateElementWithCheckDigit","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/description":{"kind":"symbol","type":"topic","title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/checkDigit":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"checkDigit","kind":"identifier"}],"type":"topic","abstract":[{"text":"An object with check digit value and checksum validity flag.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/checkDigit","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/checkdigit","title":"checkDigit","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/hash":{"kind":"symbol","type":"topic","title":"hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/hash","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","title":"MrzElement","url":"\/documentation\/dotnfc\/mrzelement"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/init(value:positions:checkDigit:)":{"kind":"symbol","type":"topic","title":"init(value:positions:checkDigit:)","role":"symbol","navigatorTitle":[{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"positions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"checkDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"role":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","abstract":[{"text":"A ","type":"text"},{"code":"MrzElement","type":"codeVoice"},{"text":" with check digit and checksum validitity information.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"navigatorTitle":[{"kind":"identifier","text":"MrzElementWithCheckDigit"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","title":"MrzElementWithCheckDigit","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTMrzElementWithCheckDigit","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/checkDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/hash"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"]},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"DOTMrzElement"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1isEqual(_:)\/fragments"},{"value":"DOTMrzDateElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments"},{"value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1description\/fragments"},{"value":"checkDigit","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1checkDigit\/title"},{"value":[{"text":"checkDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1checkDigit\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1hash\/fragments"},{"value":"DOTMrzElement","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/navigatorTitle"},{"value":"initWithValue:positions:checkDigit:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:positions:checkDigit:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/fragments"},{"value":"DOTMrzElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title"},{"value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments"},{"value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}