{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:position:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:positions:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/positions","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/value"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/isEqual(_:)"],"title":"Instance Methods"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTMrzElement) ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzelement"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzelement"]}],"metadata":{"symbolKind":"class","externalID":"c:@M@DotNfc@objc(cs)DOTMrzElement","title":"MrzElement","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/init(value:position:)":{"title":"init(value:position:)","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:position:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithValue:position:"}],"kind":"symbol","url":"\/documentation\/dotnfc\/mrzelement\/init(value:position:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/description":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/mrzelement\/description","title":"description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/description"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/positions":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/positions","url":"\/documentation\/dotnfc\/mrzelement\/positions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"positions"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"positions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"text":"]","kind":"text"}],"abstract":[{"type":"text","text":"Positions of the element."}],"title":"positions","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/value":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","abstract":[{"text":"String value of the element.","type":"text"}],"role":"symbol","url":"\/documentation\/dotnfc\/mrzelement\/value","navigatorTitle":[{"kind":"identifier","text":"value"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/value","title":"value"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/hash":{"url":"\/documentation\/dotnfc\/mrzelement\/hash","kind":"symbol","type":"topic","title":"hash","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/hash"},"doc://com.innovatrics.dot.nfc/SH":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/isEqual(_:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotnfc\/mrzelement\/isequal(_:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/isEqual(_:)","abstract":[],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isEqual(_:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElementWithCheckDigit":{"role":"symbol","title":"MrzElementWithCheckDigit","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/mrzelement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"role":"symbol","title":"MrzElement"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/init(value:positions:)":{"kind":"symbol","url":"\/documentation\/dotnfc\/mrzelement\/init(value:positions:)","title":"init(value:positions:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:positions:)","navigatorTitle":[{"text":"initWithValue:positions:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"positions","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"kind":"text","text":"])"}],"type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTMrzElement"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/positions","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/value"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:position:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:positions:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/isEqual(_:)"],"title":"Instance Methods"}]},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTMrzElement","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1init(value:position:)\/title","value":"initWithValue:position:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithValue:position:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1init(value:position:)\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1positions\/title","op":"replace","value":"positions"},{"value":[{"text":"positions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1positions\/fragments"},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1value\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1value\/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1isEqual(_:)\/fragments"},{"value":"DOTMrzElementWithCheckDigit","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"value":"initWithValue:positions:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1init(value:positions:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1init(value:positions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:positions:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}