{"metadata":{"roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"modules":[{"name":"DotNfc"}],"symbolKind":"protocol","role":"symbol","title":"NfcTravelDocumentReaderDelegate","externalID":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Implement this delegate to handle the NFC reading events."}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:failed:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:succeeded:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReaderCanceled(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNNfcTravelDocumentReaderDelegate) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate"]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"abstract":[{"text":"Implement this delegate to handle the NFC reading events.","type":"text"}],"kind":"symbol","title":"NfcTravelDocumentReaderDelegate","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate/nfcTravelDocumentReader(_:failed:)":{"required":true,"title":"nfcTravelDocumentReader(_:failed:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:failed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfcTravelDocumentReader"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","kind":"typeIdentifier","text":"NfcTravelDocumentReader"},{"kind":"text","text":", "},{"text":"failed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NfcTravelDocumentReader","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"text":".","kind":"text"},{"preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC5ErrorC","kind":"typeIdentifier","text":"Error"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that NFC reading has failed with an error."}],"navigatorTitle":[{"text":"nfcTravelDocumentReader:failed:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:failed:)"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate/nfcTravelDocumentReader(_:succeeded:)":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreader(_:succeeded:)","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfcTravelDocumentReader"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","kind":"typeIdentifier","text":"NfcTravelDocumentReader"},{"kind":"text","text":", "},{"kind":"externalParam","text":"succeeded"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderResult","kind":"typeIdentifier","text":"NfcTravelDocumentReaderResult"},{"kind":"text","text":")"}],"abstract":[{"text":"Tells the delegate that NFC reading has finished successfully with a result.","type":"text"}],"kind":"symbol","title":"nfcTravelDocumentReader(_:succeeded:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:succeeded:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"nfcTravelDocumentReader:succeeded:"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate/nfcTravelDocumentReaderCanceled(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NfcTravelDocumentReader","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReaderCanceled(_:)","kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that NFC reading has been canceled by the system dialog cancel button on click event."}],"title":"nfcTravelDocumentReaderCanceled(_:)","role":"symbol","required":true,"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate\/nfctraveldocumentreadercanceled(_:)","navigatorTitle":[{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTNNfcTravelDocumentReaderDelegate","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:failed:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReader(_:succeeded:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate\/nfcTravelDocumentReaderCanceled(_:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTNNfcTravelDocumentReaderDelegate","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/navigatorTitle"},{"op":"replace","value":"nfcTravelDocumentReader:failed:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:failed:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nfcTravelDocumentReader:failed:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:failed:)\/fragments"},{"op":"replace","value":"nfcTravelDocumentReader:succeeded:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:succeeded:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nfcTravelDocumentReader:succeeded:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReader(_:succeeded:)\/fragments"},{"op":"replace","value":"nfcTravelDocumentReaderCanceled:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReaderCanceled(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"nfcTravelDocumentReaderCanceled:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate~1nfcTravelDocumentReaderCanceled(_:)\/fragments"}]}]}