{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNNfcTravelDocumentReader) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader"]}],"kind":"symbol","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","kind":"relationships"}],"seeAlsoSections":[{"title":"Non-UI components","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"roleHeading":"Class","platforms":[{"introducedAt":"13.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false}],"role":"symbol","title":"NfcTravelDocumentReader"},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class"],"title":"Configuration"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate"],"title":"Delegate"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error"],"title":"NFC reading"},{"title":"Classes","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/AccessControlError","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/ChipAuthenticationError","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/NotConnectedError"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/init(configuration:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/configuration-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(nfcKey:activeAuthenticationChallenge:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(password:activeAuthenticationChallenge:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/setDelegate(_:queue:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"url":"\/documentation\/dotnfc\/flattagstructureparser","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlatTagStructureParser"}],"navigatorTitle":[{"text":"FlatTagStructureParser","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse "},{"code":"OptionalDetails.content","type":"codeVoice"},{"text":" of some documents.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","title":"FlatTagStructureParser","type":"topic"},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/AccessControlError":{"type":"topic","title":"NfcTravelDocumentReader.AccessControlError","abstract":[{"type":"text","text":"If access to the chip data is denied either by PACE or BAC protocol."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/accesscontrolerror","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/AccessControlError","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AccessControlError","kind":"identifier"}],"navigatorTitle":[{"text":"AccessControlError","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/init(configuration:)":{"type":"topic","title":"init(configuration:)","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/init(configuration:)","abstract":[{"type":"text","text":"Initialize and configure "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/init(configuration:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}]},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderDelegate":{"type":"topic","title":"NfcTravelDocumentReaderDelegate","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the NFC reading events."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReaderDelegate"}],"navigatorTitle":[{"text":"NfcTravelDocumentReaderDelegate","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"NfcTravelDocumentReader.Error","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error","role":"symbol","abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/setDelegate(_:queue:)":{"type":"topic","title":"setDelegate(_:queue:)","abstract":[{"text":"Set delegate and ","type":"text"},{"type":"codeVoice","code":"DispatchQueue"},{"text":" on which you want to recieve the delegate callbacks. ","type":"text"},{"code":"NfcTravelDocumentReader","type":"codeVoice"},{"type":"text","text":" will hold weak reference to "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"code":"queue","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/setdelegate(_:queue:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/setDelegate(_:queue:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate","text":"NfcTravelDocumentReaderDelegate","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"queue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DispatchQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"setDelegate:queue:","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/read(password:activeAuthenticationChallenge:)":{"type":"topic","title":"read(password:activeAuthenticationChallenge:)","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/read(password:activeauthenticationchallenge:)","abstract":[{"type":"text","text":"Read passport using NFC password."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(password:activeAuthenticationChallenge:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"read"},{"text":"(","kind":"text"},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentReaderPassword","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword"},{"kind":"text","text":", "},{"text":"activeAuthenticationChallenge","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"readWithPassword:activeAuthenticationChallenge:"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/read(nfcKey:activeAuthenticationChallenge:)":{"type":"topic","title":"read(nfcKey:activeAuthenticationChallenge:)","abstract":[{"type":"text","text":"Read passport using NFC key."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/read(nfckey:activeauthenticationchallenge:)","deprecated":true,"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(nfcKey:activeAuthenticationChallenge:)","role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"nfcKey"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","text":"NfcKey","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"activeAuthenticationChallenge","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"readWithNfcKey:activeAuthenticationChallenge:","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class":{"type":"topic","title":"NfcTravelDocumentReader.Configuration","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult":{"type":"topic","title":"NfcTravelDocumentReaderResult","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult","abstract":[{"text":"Result of the NFC Travel Document Reader component.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReaderResult"}],"navigatorTitle":[{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcKey":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"abstract":[{"text":"NFC password created from document number, date of expiry and date of birth of MRZ.","type":"text"}],"role":"symbol","kind":"symbol","deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"type":"topic","title":"NfcKey","url":"\/documentation\/dotnfc\/nfckey"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","title":"DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/configuration-swift.property":{"type":"topic","title":"configuration","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.property","abstract":[{"type":"text","text":"Current configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/configuration-swift.property","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC","text":"Configuration"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/NotConnectedError":{"type":"topic","title":"NfcTravelDocumentReader.NotConnectedError","abstract":[{"type":"text","text":"If NFC reading fails due to an NFC tag connection failure."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/notconnectederror","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/NotConnectedError","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotConnectedError","kind":"identifier"}],"navigatorTitle":[{"text":"NotConnectedError","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"role":"symbol","abstract":[{"type":"text","text":"Password from Machine Readable Zone."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZonePassword"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","title":"MachineReadableZonePassword","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZonePassword"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/ChipAuthenticationError":{"type":"topic","title":"NfcTravelDocumentReader.ChipAuthenticationError","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/chipauthenticationerror","abstract":[{"type":"text","text":"If authentication of the chip using the Chip Authentication protocol fails. Secure connection was not established."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/ChipAuthenticationError","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChipAuthenticationError"}],"navigatorTitle":[{"text":"ChipAuthenticationError","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"type":"topic","title":"CardAccessNumberPassword","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"abstract":[{"type":"text","text":"Card Access Number as a password."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardAccessNumberPassword","kind":"identifier"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderDelegate"],"title":"Delegate"},{"title":"NFC reading","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/configuration-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/init(configuration:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(nfcKey:activeAuthenticationChallenge:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(password:activeAuthenticationChallenge:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/setDelegate(_:queue:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace"},{"value":[{"title":"Non-UI components","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","value":"DOTNFlatTagStructureParser","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments","value":[{"kind":"identifier","text":"DOTNFlatTagStructureParser"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1init(configuration:)\/title","value":"initWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1init(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}],"op":"replace"},{"value":"DOTNNfcTravelDocumentReaderDelegate","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderDelegate"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1setDelegate(_:queue:)\/title","op":"replace","value":"setDelegate:queue:"},{"value":[{"kind":"text","text":"- "},{"text":"setDelegate:queue:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1setDelegate(_:queue:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(password:activeAuthenticationChallenge:)\/title","value":"readWithPassword:activeAuthenticationChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(password:activeAuthenticationChallenge:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"readWithPassword:activeAuthenticationChallenge:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(nfcKey:activeAuthenticationChallenge:)\/title","value":"readWithNfcKey:activeAuthenticationChallenge:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"readWithNfcKey:activeAuthenticationChallenge:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(nfcKey:activeAuthenticationChallenge:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/title","value":"DOTNNfcTravelDocumentReaderResult","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderResult"}]},{"value":"DOTNNfcKey","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title"},{"value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1configuration-swift.property\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace","value":"DOTNMachineReadableZonePassword"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}