{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNfcTravelDocumentReaderErrorType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH","doc:\/\/com.innovatrics.dot.nfc\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"NFC reading error type."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"role":"symbol","title":"NfcTravelDocumentReaderErrorType","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"symbolKind":"enum","externalID":"c:@M@DotNfc@E@DOTNfcTravelDocumentReaderErrorType","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/accessControlError","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/readingError"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"DotNfc provides a component for NFC reading which is easy to integrate into an iOS application. Supported documents are those which implement Machine Readable Travel Document (MRTD) standards as specified by International Civil Aviation Organization (ICAO)."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/init(rawvalue:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/accessControlError":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType.accessControlError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlError"}],"abstract":[{"type":"text","text":"Failed access control indicates that you have invalid NFC key."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/accessControlError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/accesscontrolerror"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SY"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"abstract":[{"type":"text","text":"NFC reading error type."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/equatable-implementations"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/readingError":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType.readingError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"readingError"}],"abstract":[{"type":"text","text":"An error encountered during the NFC reading process."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/readingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeReadingError"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/readingerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTNfcTravelDocumentReaderErrorType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/accessControlError","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/readingError"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1accessControlError\/title","value":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1accessControlError\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/title","value":"DOTNfcTravelDocumentReaderErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1readingError\/title","value":"DOTNfcTravelDocumentReaderErrorTypeReadingError"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1readingError\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeReadingError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}