{"sections":[],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPointInt) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/pointint"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/init(x:y:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/cgPoint","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/x","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/y"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/from(cgPoint:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"title":"PointInt","roleHeading":"Class","symbolKind":"class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTPointInt","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"PointInt","kind":"identifier"}]},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/PointInt/cgPoint":{"type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/cgPoint","title":"cgPoint","kind":"symbol","url":"\/documentation\/dotnfc\/pointint\/cgpoint","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cgPoint"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/PointInt/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/pointint\/isequal(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/isEqual(_:)","title":"isEqual(_:)","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/PointInt/init(x:y:)":{"abstract":[],"title":"init(x:y:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/init(x:y:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"url":"\/documentation\/dotnfc\/pointint\/init(x:y:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","type":"topic"},"doc://DotNfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/PointInt/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/description","type":"topic","abstract":[],"title":"description","kind":"symbol","url":"\/documentation\/dotnfc\/pointint\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/PointInt/hash":{"abstract":[],"title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/pointint\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/hash","role":"symbol"},"doc://DotNfc/documentation/DotNfc/PointInt":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt","navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"title":"PointInt","type":"topic","url":"\/documentation\/dotnfc\/pointint","kind":"symbol","role":"symbol","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/PointInt/x":{"title":"x","abstract":[{"text":"X coordinate.","type":"text"}],"navigatorTitle":[{"text":"x","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/x","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/pointint\/x"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/PointInt/from(cgPoint:)":{"navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/pointint\/from(cgpoint:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/from(cgPoint:)","title":"from(cgPoint:)"},"doc://DotNfc/documentation/DotNfc/PointInt/y":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/y","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotnfc\/pointint\/y","abstract":[{"text":"Y coordinate.","type":"text"}],"title":"y","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"y"}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTPointInt"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/cgPoint","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/x","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/y"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/init(x:y:)","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/isEqual(_:)"]},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/from(cgPoint:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPointInt","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1cgPoint\/title","op":"replace","value":"cgPoint"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1cgPoint\/fragments","value":[{"text":"cgPoint","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1init(x:y:)\/title","value":"initWithX:y:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1init(x:y:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithX:y:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/title","value":"DOTPointInt"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/fragments","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/navigatorTitle","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1x\/title","value":"x"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1x\/fragments","value":[{"text":"x","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1from(cgPoint:)\/title","value":"fromCgPoint:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1from(cgPoint:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1y\/fragments","value":[{"text":"y","kind":"identifier"}]}]}]}