{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTRectangleInt) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleInt"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangleint"]},{"paths":["\/documentation\/dotnfc\/rectangleint"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/init(left:top:right:bottom:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/bottom","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/cgRect","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/height","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/left","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/origin","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/right","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/top","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/width","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/widthToHeightRatio"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/isEqual(_:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/from(cgRect:)"],"title":"Type Methods"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","kind":"relationships"}],"sections":[],"metadata":{"symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleInt","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"modules":[{"name":"DotNfc"}],"title":"RectangleInt"},"references":{"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/RectangleInt/bottom":{"url":"\/documentation\/dotnfc\/rectangleint\/bottom","abstract":[{"type":"text","text":"Bottom edge."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","title":"bottom","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/bottom","navigatorTitle":[{"text":"bottom","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/RectangleInt/from(cgRect:)":{"url":"\/documentation\/dotnfc\/rectangleint\/from(cgrect:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt"}],"title":"from(cgRect:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/from(cgRect:)","navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleInt/isEqual(_:)":{"url":"\/documentation\/dotnfc\/rectangleint\/isequal(_:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","title":"isEqual(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleInt/top":{"url":"\/documentation\/dotnfc\/rectangleint\/top","abstract":[{"type":"text","text":"Top edge."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"top","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","title":"top","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/top","navigatorTitle":[{"kind":"identifier","text":"top"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleInt/widthToHeightRatio":{"url":"\/documentation\/dotnfc\/rectangleint\/widthtoheightratio","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"widthToHeightRatio"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic","title":"widthToHeightRatio","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/widthToHeightRatio","navigatorTitle":[{"kind":"identifier","text":"widthToHeightRatio"}],"role":"symbol"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/RectangleInt/description":{"url":"\/documentation\/dotnfc\/rectangleint\/description","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/RectangleInt/width":{"url":"\/documentation\/dotnfc\/rectangleint\/width","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","title":"width","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/width","navigatorTitle":[{"kind":"identifier","text":"width"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleInt/init(left:top:right:bottom:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"left","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"top"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"right","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottom","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/init(left:top:right:bottom:)","url":"\/documentation\/dotnfc\/rectangleint\/init(left:top:right:bottom:)","title":"init(left:top:right:bottom:)","role":"symbol","navigatorTitle":[{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/documentation/DotNfc/RectangleInt/origin":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/origin","url":"\/documentation\/dotnfc\/rectangleint\/origin","title":"origin","role":"symbol","navigatorTitle":[{"text":"origin","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/RectangleInt/height":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/height","type":"topic","url":"\/documentation\/dotnfc\/rectangleint\/height","title":"height","role":"symbol","navigatorTitle":[{"text":"height","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/RectangleInt/right":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/dotnfc\/rectangleint\/right","navigatorTitle":[{"text":"right","kind":"identifier"}],"abstract":[{"type":"text","text":"Right edge."}],"title":"right","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/right","role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleInt":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"url":"\/documentation\/dotnfc\/rectangleint","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"title":"RectangleInt","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleInt/left":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/left","url":"\/documentation\/dotnfc\/rectangleint\/left","title":"left","role":"symbol","navigatorTitle":[{"text":"left","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Left edge."}]},"doc://DotNfc/documentation/DotNfc/RectangleInt/cgRect":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/cgRect","type":"topic","url":"\/documentation\/dotnfc\/rectangleint\/cgrect","title":"cgRect","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"kind":"symbol","abstract":[]},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/RectangleInt/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/hash","type":"topic","url":"\/documentation\/dotnfc\/rectangleint\/hash","title":"hash","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"DOTRectangleInt","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/bottom","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/cgRect","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/height","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/left","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/origin","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/right","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/top","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/width","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/widthToHeightRatio"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/init(left:top:right:bottom:)","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/from(cgRect:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTRectangleInt"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"bottom","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1bottom\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1bottom\/fragments","value":[{"text":"bottom","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1from(cgRect:)\/title","value":"fromCgRect:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgRect:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1from(cgRect:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"value":"top","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1top\/title","op":"replace"},{"value":[{"text":"top","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1top\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1widthToHeightRatio\/title","op":"replace","value":"widthToHeightRatio"},{"op":"replace","value":[{"text":"widthToHeightRatio","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1widthToHeightRatio\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","value":"width","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1width\/title"},{"value":[{"kind":"identifier","text":"width"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1width\/fragments"},{"value":"initWithLeft:top:right:bottom:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1init(left:top:right:bottom:)\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1init(left:top:right:bottom:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1origin\/title","value":"origin"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1origin\/fragments","value":[{"kind":"identifier","text":"origin"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1height\/title","value":"height"},{"value":[{"text":"height","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1height\/fragments"},{"value":"right","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1right\/title"},{"op":"replace","value":[{"kind":"identifier","text":"right"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1right\/fragments"},{"value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/fragments","op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1left\/title","value":"left"},{"op":"replace","value":[{"text":"left","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1left\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1cgRect\/title","value":"cgRect","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1cgRect\/fragments","op":"replace","value":[{"text":"cgRect","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1hash\/title","value":"hash","op":"replace"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1hash\/fragments"}]}]}