{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}],"title":"Td3MachineReadableZone","externalID":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone","symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Class"},"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/compositeCheckDigit","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfBirth","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfExpiry","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/documentCode","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/hasAllChecksumsValid","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/issuingStateOrOrganization","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/name","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/nationality","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/passportNumber","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/sex"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/isEqual(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTTd3MachineReadableZone) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone"},"abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/sex":{"kind":"symbol","title":"sex","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"}],"role":"symbol","navigatorTitle":[{"text":"sex","kind":"identifier"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/sex","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/sex"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.3.1","type":"text"}],"url":"\/documentation\/dotnfc","type":"topic","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/personalNumberOrOtherOptionalData":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","kind":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone\/personalnumberorotheroptionaldata","title":"personalNumberOrOtherOptionalData","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"personalNumberOrOtherOptionalData"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit"}],"navigatorTitle":[{"text":"personalNumberOrOtherOptionalData","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/isEqual(_:)":{"kind":"symbol","title":"isEqual(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/isequal(_:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/isEqual(_:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/hasAllChecksumsValid":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/hasallchecksumsvalid","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasAllChecksumsValid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"hasAllChecksumsValid","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/hasAllChecksumsValid"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/hash":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/hash","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/hash","title":"hash"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","type":"topic","url":"\/documentation\/dotnfc\/td3machinereadablezone","kind":"symbol","title":"Td3MachineReadableZone","role":"symbol","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/name":{"kind":"symbol","type":"topic","abstract":[],"title":"name","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","text":"MrzNameElement"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"name"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/name","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/name"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/compositeCheckDigit":{"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/td3machinereadablezone\/compositecheckdigit","abstract":[],"title":"compositeCheckDigit","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit"}],"navigatorTitle":[{"kind":"identifier","text":"compositeCheckDigit"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/compositeCheckDigit"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","role":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone\/description","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/description","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/dateOfExpiry":{"type":"topic","title":"dateOfExpiry","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfExpiry","navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateOfExpiry","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone\/dateofexpiry","abstract":[]},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/dateOfBirth":{"type":"topic","title":"dateOfBirth","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/dateofbirth","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfBirth"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/passportNumber":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"passportNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/passportnumber","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/passportNumber","type":"topic","navigatorTitle":[{"text":"passportNumber","kind":"identifier"}],"role":"symbol","title":"passportNumber"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/nationality":{"url":"\/documentation\/dotnfc\/td3machinereadablezone\/nationality","navigatorTitle":[{"text":"nationality","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/nationality","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"}],"role":"symbol","title":"nationality","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/issuingStateOrOrganization":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"}],"title":"issuingStateOrOrganization","kind":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone\/issuingstateororganization","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/issuingStateOrOrganization","abstract":[],"navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/documentCode":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/documentCode","navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"kind":"symbol","title":"documentCode","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/td3machinereadablezone\/documentcode","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","kind":"symbol","navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"documentCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"passportNumber"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"personalNumberOrOtherOptionalData"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)","abstract":[],"title":"init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/compositeCheckDigit","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfBirth","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfExpiry","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/documentCode","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/issuingStateOrOrganization","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/name","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/nationality","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/passportNumber","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/personalNumberOrOtherOptionalData","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/sex"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTTd3MachineReadableZone"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"sex","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1sex\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1sex\/fragments","op":"replace","value":[{"kind":"identifier","text":"sex"}]},{"value":"personalNumberOrOtherOptionalData","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1personalNumberOrOtherOptionalData\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1personalNumberOrOtherOptionalData\/fragments","value":[{"text":"personalNumberOrOtherOptionalData","kind":"identifier"}],"op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1isEqual(_:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1hash\/title","value":"hash"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1hash\/fragments"},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace"},{"value":"name","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1name\/title"},{"op":"replace","value":[{"text":"name","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1name\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1compositeCheckDigit\/title","value":"compositeCheckDigit","op":"replace"},{"value":[{"text":"compositeCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1compositeCheckDigit\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1description\/title","value":"description","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1description\/fragments"},{"value":"dateOfExpiry","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfExpiry\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfExpiry\/fragments","value":[{"text":"dateOfExpiry","kind":"identifier"}]},{"op":"replace","value":"dateOfBirth","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfBirth\/title"},{"value":[{"text":"dateOfBirth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfBirth\/fragments"},{"value":"passportNumber","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1passportNumber\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1passportNumber\/fragments","op":"replace","value":[{"kind":"identifier","text":"passportNumber"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1nationality\/title","value":"nationality"},{"value":[{"text":"nationality","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1nationality\/fragments","op":"replace"},{"value":"issuingStateOrOrganization","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1issuingStateOrOrganization\/title","op":"replace"},{"value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1issuingStateOrOrganization\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1documentCode\/title","value":"documentCode"},{"value":[{"text":"documentCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1documentCode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/fragments"}]}]}