{"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"title":"TravelDocumentReaderPasswordWrapper","symbolKind":"class","navigatorTitle":[{"text":"TravelDocumentReaderPasswordWrapper","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocumentReaderPasswordWrapper","kind":"identifier"}],"platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false}],"roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocumentReaderPasswordWrapper"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNTravelDocumentReaderPasswordWrapper) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentReaderPasswordWrapper"}],"languages":["swift"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/init(travelDocumentReaderPassword:)"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/travelDocumentReaderPassword"],"title":"Instance Properties"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper"]},{"paths":["\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentReaderPasswordWrapper"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentReaderPasswordWrapper"}],"url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper","title":"TravelDocumentReaderPasswordWrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","type":"topic","kind":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper/travelDocumentReaderPassword":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/travelDocumentReaderPassword","role":"symbol","navigatorTitle":[{"text":"travelDocumentReaderPassword","kind":"identifier"}],"title":"travelDocumentReaderPassword","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentReaderPassword","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","text":"TravelDocumentReaderPassword"}],"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/traveldocumentreaderpassword","kind":"symbol"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper/init(travelDocumentReaderPassword:)":{"role":"symbol","navigatorTitle":[{"text":"initWithTravelDocumentReaderPassword:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"travelDocumentReaderPassword","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentReaderPassword","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword"},{"text":")","kind":"text"}],"url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/init(traveldocumentreaderpassword:)","title":"init(travelDocumentReaderPassword:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/init(travelDocumentReaderPassword:)","type":"topic","abstract":[],"kind":"symbol"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/description","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"DOTNTravelDocumentReaderPasswordWrapper","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPasswordWrapper"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPasswordWrapper"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/travelDocumentReaderPassword"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper\/init(travelDocumentReaderPassword:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNTravelDocumentReaderPasswordWrapper","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DOTNTravelDocumentReaderPasswordWrapper","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/title"},{"value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPasswordWrapper"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/fragments"},{"value":"travelDocumentReaderPassword","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1travelDocumentReaderPassword\/title"},{"op":"replace","value":[{"kind":"identifier","text":"travelDocumentReaderPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1travelDocumentReaderPassword\/fragments"},{"op":"replace","value":"initWithTravelDocumentReaderPassword:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1init(travelDocumentReaderPassword:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1init(travelDocumentReaderPassword:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTravelDocumentReaderPassword:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper~1description\/fragments","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}