{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"variants":[{"paths":["\/documentation\/dotnfc\/traveldocumenttypewrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocumenttypewrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/init(travelDocumentType:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/travelDocumentType"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTTravelDocumentTypeWrapper) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wrapped "},{"code":"TravelDocumentType","type":"codeVoice"},{"text":" for Objective-C support.","type":"text"}],"metadata":{"roleHeading":"Class","title":"TravelDocumentTypeWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/TravelDocumentTypeWrapper/travelDocumentType":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"travelDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentType","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"}],"kind":"symbol","title":"travelDocumentType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"travelDocumentType"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/travelDocumentType","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/traveldocumenttypewrapper\/traveldocumenttype"},"doc://DotNfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/TravelDocumentTypeWrapper":{"title":"TravelDocumentTypeWrapper","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper","url":"\/documentation\/dotnfc\/traveldocumenttypewrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Wrapped ","type":"text"},{"code":"TravelDocumentType","type":"codeVoice"},{"type":"text","text":" for Objective-C support."}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocumentTypeWrapper/init(travelDocumentType:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType","text":"TravelDocumentType"},{"text":")","kind":"text"}],"title":"init(travelDocumentType:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithTravelDocumentType:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/init(travelDocumentType:)","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/traveldocumenttypewrapper\/init(traveldocumenttype:)"},"doc://DotNfc/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DOTTravelDocumentTypeWrapper","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/travelDocumentType"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/init(travelDocumentType:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1travelDocumentType\/title","value":"travelDocumentType"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1travelDocumentType\/fragments","value":[{"kind":"identifier","text":"travelDocumentType"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/title","value":"DOTTravelDocumentTypeWrapper","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/fragments","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1init(travelDocumentType:)\/title","value":"initWithTravelDocumentType:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1init(travelDocumentType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTravelDocumentType:","kind":"identifier"}],"op":"replace"}]}]}