{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"},"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","title":"TravelDocument","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"platforms":[{"unavailable":false,"introducedAt":"13.0","beta":false,"name":"iOS","deprecated":false}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"topicSections":[{"title":"Raw content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"],"title":"Structured content"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/accessControlProtocolUsed","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/authenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/debugInfo","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/displayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/encodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsVersion","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/machineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/optionalDetails"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/isEqual(_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/traveldocument"]},{"paths":["\/documentation\/dotnfc\/traveldocument"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTNTravelDocument) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"references":{"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)":{"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument\/init(ldsversion:accesscontrolprotocolused:authenticationstatus:ldsmasterfile:machinereadablezoneinformation:encodedidentificationfeaturesface:displayedsignatureorusualmark:additionalpersonaldetails:additionaldocumentdetails:optionaldetails:-25bwr","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ldsVersion"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"accessControlProtocolUsed"},{"text":": ","kind":"text"},{"text":"AccessControlProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"authenticationStatus"},{"text":": ","kind":"text"},{"text":"AuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus"},{"text":", ","kind":"text"},{"text":"ldsMasterFile","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"LdsMasterFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile"},{"text":", ","kind":"text"},{"text":"machineReadableZoneInformation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation","text":"MachineReadableZoneInformation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"encodedIdentificationFeaturesFace"},{"kind":"text","text":": "},{"text":"EncodedIdentificationFeaturesFace","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"displayedSignatureOrUsualMark"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark","text":"DisplayedSignatureOrUsualMark","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"additionalPersonalDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails","kind":"typeIdentifier","text":"AdditionalPersonalDetails"},{"text":"?, ","kind":"text"},{"text":"additionalDocumentDetails","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","text":"AdditionalDocumentDetails"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"optionalDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","kind":"typeIdentifier","text":"OptionalDetails"},{"kind":"text","text":"?, "},{"text":"debugInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)","title":"init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:","kind":"identifier"}]},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/TravelDocument/hash":{"role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/hash","url":"\/documentation\/dotnfc\/traveldocument\/hash","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/optionalDetails":{"url":"\/documentation\/dotnfc\/traveldocument\/optionaldetails","title":"optionalDetails","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/optionalDetails","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"optionalDetails","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails","text":"OptionalDetails"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"optionalDetails"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"kind":"symbol","title":"Lds1eMrtdApplication","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1eMrtdApplication","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"url":"\/documentation\/dotnfc\/lds1emrtdapplication","role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/encodedIdentificationFeaturesFace":{"abstract":[{"type":"text","text":"Contents of DG2 - Face image."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/encodedIdentificationFeaturesFace","role":"symbol","type":"topic","kind":"symbol","title":"encodedIdentificationFeaturesFace","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"encodedIdentificationFeaturesFace","kind":"identifier"},{"text":": ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNEncodedIdentificationFeaturesFace"}],"navigatorTitle":[{"text":"encodedIdentificationFeaturesFace","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocument\/encodedidentificationfeaturesface"},"doc://DotNfc/documentation/DotNfc/TravelDocument/displayedSignatureOrUsualMark":{"role":"symbol","navigatorTitle":[{"text":"displayedSignatureOrUsualMark","kind":"identifier"}],"type":"topic","title":"displayedSignatureOrUsualMark","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayedSignatureOrUsualMark","kind":"identifier"},{"kind":"text","text":": "},{"text":"DisplayedSignatureOrUsualMark","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"url":"\/documentation\/dotnfc\/traveldocument\/displayedsignatureorusualmark","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/displayedSignatureOrUsualMark","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/accessControlProtocolUsed":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"accessControlProtocolUsed"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/accessControlProtocolUsed","abstract":[{"type":"text","text":"Access Control protocol used to read the document."}],"type":"topic","kind":"symbol","title":"accessControlProtocolUsed","url":"\/documentation\/dotnfc\/traveldocument\/accesscontrolprotocolused","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlProtocolUsed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","text":"AccessControlProtocol"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument/additionalDocumentDetails":{"role":"symbol","navigatorTitle":[{"text":"additionalDocumentDetails","kind":"identifier"}],"type":"topic","title":"additionalDocumentDetails","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalDocumentDetails"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails","text":"AdditionalDocumentDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalDocumentDetails","url":"\/documentation\/dotnfc\/traveldocument\/additionaldocumentdetails","kind":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"type":"topic","title":"TravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","url":"\/documentation\/dotnfc\/traveldocument\/isequal(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/isEqual(_:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OptionalDetails"}],"type":"topic","url":"\/documentation\/dotnfc\/optionaldetails","role":"symbol","navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","kind":"symbol","title":"OptionalDetails","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}]},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/TravelDocument/description":{"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/description","url":"\/documentation\/dotnfc\/traveldocument\/description","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/ldsMasterFile":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ldsMasterFile"}],"type":"topic","title":"ldsMasterFile","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ldsMasterFile","kind":"identifier"},{"kind":"text","text":": "},{"text":"LdsMasterFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLdsMasterFile"}],"abstract":[{"type":"text","text":"Logical data structure master file. Contains raw data read from the document."}],"url":"\/documentation\/dotnfc\/traveldocument\/ldsmasterfile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsMasterFile","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","title":"AdditionalPersonalDetails","url":"\/documentation\/dotnfc\/additionalpersonaldetails","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","abstract":[{"text":"Contents of DG1 - Machine readable zone information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MachineReadableZoneInformation","kind":"identifier"}],"title":"MachineReadableZoneInformation","role":"symbol","type":"topic","navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation"},"doc://DotNfc/documentation/DotNfc/TravelDocument/debugInfo":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/debugInfo","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debugInfo"},{"text":": ","kind":"text"},{"text":"DebugInfo","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"debugInfo"}],"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument\/debuginfo","role":"symbol","abstract":[],"title":"debugInfo"},"doc://DotNfc/documentation/DotNfc/LdsMasterFile":{"url":"\/documentation\/dotnfc\/ldsmasterfile","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LdsMasterFile"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","title":"LdsMasterFile","abstract":[{"type":"text","text":"Raw represenation of the whole content stored in the NFC chip of the travel document."}],"role":"symbol","navigatorTitle":[{"text":"LdsMasterFile","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalDocumentDetails","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails","title":"AdditionalDocumentDetails"},"doc://DotNfc/documentation/DotNfc/TravelDocument/ldsVersion":{"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument\/ldsversion","title":"ldsVersion","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsVersion","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"ldsVersion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"ldsVersion","kind":"identifier"}],"abstract":[{"type":"text","text":"Logical data structure version."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument/authenticationStatus":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"authenticationStatus"}],"type":"topic","title":"authenticationStatus","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"authenticationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus","text":"AuthenticationStatus","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Authentication status of data and chip."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/authenticationStatus","url":"\/documentation\/dotnfc\/traveldocument\/authenticationstatus","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/EncodedIdentificationFeaturesFace":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EncodedIdentificationFeaturesFace"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EncodedIdentificationFeaturesFace","kind":"identifier"}],"title":"EncodedIdentificationFeaturesFace","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","type":"topic","kind":"symbol","abstract":[{"text":"Contents of DG2 - Face image.","type":"text"}],"url":"\/documentation\/dotnfc\/encodedidentificationfeaturesface"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","kind":"symbol","abstract":[{"type":"text","text":"Contents of DG7 - Displayed signature or usual mark."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"title":"DisplayedSignatureOrUsualMark","role":"symbol","type":"topic","navigatorTitle":[{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark"},"doc://DotNfc/documentation/DotNfc/TravelDocument/additionalPersonalDetails":{"url":"\/documentation\/dotnfc\/traveldocument\/additionalpersonaldetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalPersonalDetails","navigatorTitle":[{"text":"additionalPersonalDetails","kind":"identifier"}],"abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"kind":"symbol","type":"topic","role":"symbol","title":"additionalPersonalDetails","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"additionalPersonalDetails","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"AdditionalPersonalDetails","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails"},{"text":"?","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"title":"Lds1ElementaryFile","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"kind":"symbol","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfile","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFile","kind":"identifier"}]},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/TravelDocument/machineReadableZoneInformation":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"machineReadableZoneInformation"}],"type":"topic","title":"machineReadableZoneInformation","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineReadableZoneInformation","kind":"identifier"},{"kind":"text","text":": "},{"text":"MachineReadableZoneInformation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation"}],"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/machineReadableZoneInformation","url":"\/documentation\/dotnfc\/traveldocument\/machinereadablezoneinformation","kind":"symbol"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTNTravelDocument","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/LdsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"],"title":"Raw content"},{"title":"Structured content","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/EncodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/accessControlProtocolUsed","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalDocumentDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/additionalPersonalDetails","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/authenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/debugInfo","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/displayedSignatureOrUsualMark","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/encodedIdentificationFeaturesFace","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsMasterFile","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/ldsVersion","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/machineReadableZoneInformation","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/optionalDetails"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument\/isEqual(_:)"],"title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNTravelDocument"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLdsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1init(ldsVersion:accessControlProtocolUsed:authenticationStatus:ldsMasterFile:machineReadableZoneInformation:encodedIdentificationFeaturesFace:displayedSignatureOrUsualMark:additionalPersonalDetails:additionalDocumentDetails:optionalDetails:debugInfo:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1hash\/title","value":"hash","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1optionalDetails\/title","value":"optionalDetails"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1optionalDetails\/fragments","value":[{"text":"optionalDetails","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","value":"DOTNLds1eMrtdApplication","op":"replace"},{"value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1encodedIdentificationFeaturesFace\/title","value":"encodedIdentificationFeaturesFace","op":"replace"},{"value":[{"kind":"identifier","text":"encodedIdentificationFeaturesFace"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1encodedIdentificationFeaturesFace\/fragments"},{"value":"displayedSignatureOrUsualMark","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1displayedSignatureOrUsualMark\/title"},{"op":"replace","value":[{"text":"displayedSignatureOrUsualMark","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1displayedSignatureOrUsualMark\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1accessControlProtocolUsed\/title","value":"accessControlProtocolUsed"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1accessControlProtocolUsed\/fragments","value":[{"text":"accessControlProtocolUsed","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalDocumentDetails\/title","value":"additionalDocumentDetails","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalDocumentDetails\/fragments","op":"replace","value":[{"text":"additionalDocumentDetails","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","op":"replace","value":"DOTNOptionalDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNOptionalDetails"}]},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1description\/title","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1description\/fragments"},{"value":"ldsMasterFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsMasterFile\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsMasterFile\/fragments","op":"replace","value":[{"text":"ldsMasterFile","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTNAdditionalPersonalDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}]},{"op":"replace","value":"DOTNMachineReadableZoneInformation","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1debugInfo\/title","value":"debugInfo"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1debugInfo\/fragments","value":[{"text":"debugInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/title","value":"DOTNLdsMasterFile"},{"value":[{"text":"DOTNLdsMasterFile","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LdsMasterFile\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]},{"op":"replace","value":"ldsVersion","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsVersion\/title"},{"value":[{"text":"ldsVersion","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1ldsVersion\/fragments"},{"value":"authenticationStatus","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1authenticationStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1authenticationStatus\/fragments","value":[{"text":"authenticationStatus","kind":"identifier"}]},{"value":"DOTNEncodedIdentificationFeaturesFace","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1EncodedIdentificationFeaturesFace\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNEncodedIdentificationFeaturesFace"}]},{"value":"DOTNDisplayedSignatureOrUsualMark","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title"},{"value":[{"text":"DOTNDisplayedSignatureOrUsualMark","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments"},{"value":"additionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalPersonalDetails\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1additionalPersonalDetails\/fragments","value":[{"text":"additionalPersonalDetails","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"machineReadableZoneInformation","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1machineReadableZoneInformation\/title"},{"value":[{"text":"machineReadableZoneInformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument~1machineReadableZoneInformation\/fragments"}]}]}