{"abstract":[{"text":"Travel document type according to ICAO Doc 9303 specification.","type":"text"}],"metadata":{"externalID":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"symbolKind":"enum","title":"TravelDocumentType","roleHeading":"Enumeration","modules":[{"name":"DotNfc"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentType"}],"role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/s12CaseIterableP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td1","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td2","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td3"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/init(rawValue:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/lineLength","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/numberOfLines","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/scale","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/widthToHeightRatio"],"anchor":"Instance-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/traveldocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTTravelDocumentType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentType"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/init(rawValue:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/traveldocumenttype\/init(rawvalue:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/init(rawValue:)","abstract":[],"type":"topic","title":"init(rawValue:)"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType":{"title":"TravelDocumentType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/traveldocumenttype","role":"symbol","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/numberOfLines":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/numberOfLines","title":"numberOfLines","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttype\/numberoflines","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfLines","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/description":{"title":"description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/dotnfc\/traveldocumenttype\/description","role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/description"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/td1":{"navigatorTitle":[{"text":"DOTTravelDocumentTypeTd1","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td1","title":"TravelDocumentType.td1","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttype\/td1","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td1","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/lineLength":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/lineLength","title":"lineLength","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttype\/linelength","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lineLength","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/td2":{"navigatorTitle":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}],"title":"TravelDocumentType.td2","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttype\/td2","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td2"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td2","type":"topic"},"doc://DotNfc/SY":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY","title":"Swift.RawRepresentable"},"doc://DotNfc/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/scale":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/scale","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/dotnfc\/traveldocumenttype\/scale","title":"scale"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/dotnfc\/traveldocumenttype\/rawrepresentable-implementations","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/td3":{"navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}],"title":"TravelDocumentType.td3","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttype\/td3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"td3"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td3","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/widthToHeightRatio":{"kind":"symbol","title":"widthToHeightRatio","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic","url":"\/documentation\/dotnfc\/traveldocumenttype\/widthtoheightratio","role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/widthToHeightRatio"},"doc://DotNfc/documentation/DotNfc/TravelDocumentType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/dotnfc\/traveldocumenttype\/equatable-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/Equatable-Implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTTravelDocumentType","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td1","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td2","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType\/td3"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTTravelDocumentType"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTTravelDocumentType","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/title"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/fragments"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/navigatorTitle"},{"value":"DOTTravelDocumentTypeTd1","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td1\/title"},{"value":[{"text":"DOTTravelDocumentTypeTd1","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td1\/fragments"},{"value":"DOTTravelDocumentTypeTd2","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td2\/title"},{"value":[{"text":"DOTTravelDocumentTypeTd2","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td2\/fragments"},{"value":"DOTTravelDocumentTypeTd3","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td3\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType~1td3\/fragments","value":[{"text":"DOTTravelDocumentTypeTd3","kind":"identifier"}],"op":"replace"}]}]}