{"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/init(value:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/isEqual(_:)"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTWrappedFloat) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}]}]}],"metadata":{"modules":[{"name":"DotNfc"}],"title":"WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedFloat"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat","roleHeading":"Class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/wrappedfloat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/wrappedfloat"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"type":"text","text":"Wrapped "},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/documentation/DotNfc/WrappedFloat/hash":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/hash","title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","url":"\/documentation\/dotnfc\/wrappedfloat\/hash","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/WrappedFloat/description":{"url":"\/documentation\/dotnfc\/wrappedfloat\/description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/description","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description","abstract":[],"kind":"symbol"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/WrappedFloat":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedFloat"}],"title":"WrappedFloat","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/wrappedfloat","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":" value for Objective-C support.","type":"text"}]},"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/WrappedFloat/isEqual(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/wrappedfloat\/isequal(_:)","abstract":[]},"doc://DotNfc/documentation/DotNfc/WrappedFloat/value":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"kind":"symbol","type":"topic","title":"value","role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/wrappedfloat\/value","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/value","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/WrappedFloat/init(value:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/wrappedfloat\/init(value:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/init(value:)","type":"topic","title":"init(value:)","role":"symbol"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTWrappedFloat","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/init(value:)","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/isEqual(_:)"]}],"path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTWrappedFloat"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1hash\/title","op":"replace"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1hash\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat\/fragments","value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1isEqual(_:)\/fragments"},{"value":"value","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1value\/title","op":"replace"},{"value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1value\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1init(value:)\/title","value":"initWithValue:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithValue:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1init(value:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}