{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Balanced"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","role":"symbol","symbolKind":"init","modules":[{"name":"DotPalmCore"}],"externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC8BalancedCAEycfc","roleHeading":"Initializer"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/balanced\/init()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Balanced\/init()"},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration/Balanced/init()":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"type":"topic","role":"symbol","title":"init()","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/balanced\/init()","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Balanced\/init()"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration/Balanced":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration\/Balanced","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration\/balanced","navigatorTitle":[{"text":"Balanced","kind":"identifier"}],"abstract":[{"text":"Face detection balanced module.","type":"text"}],"kind":"symbol","type":"topic","title":"DotFaceDetectionModuleConfiguration.Balanced","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration","role":"symbol","abstract":[{"text":"Face detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","title":"DotFaceDetectionModuleConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DotFaceDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}