{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/imageformat\/jpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/imageformat\/jpeg"]}],"kind":"symbol","abstract":[{"text":"JPEG compressed image format","type":"text"}],"metadata":{"role":"symbol","roleHeading":"Case","symbolKind":"case","title":"ImageFormat.jpeg","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg","navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/jpeg":{"url":"\/documentation\/dotfacelite\/imageformat\/jpeg","abstract":[{"text":"JPEG compressed image format","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"type":"topic","title":"ImageFormat.jpeg","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"kind":"symbol","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"title":"ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Supported image formats."}],"type":"topic","url":"\/documentation\/dotfacelite\/imageformat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTImageFormatJpeg","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTImageFormatJpeg","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg\/title"},{"op":"replace","value":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg\/fragments"},{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle","op":"replace"}]}]}