{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat(py)value","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"role":"symbol","title":"value","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat\/value"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/wrappedfloat\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/wrappedfloat\/value"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat":{"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WrappedFloat","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"WrappedFloat","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"url":"\/documentation\/dotfacelite\/wrappedfloat"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat/value":{"role":"symbol","title":"value","type":"topic","navigatorTitle":[{"text":"value","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/wrappedfloat\/value","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat\/value","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"value","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/title","op":"replace","value":"DOTWrappedFloat"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat~1value\/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}