{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplateBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeTemplateBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/Result","kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"referenceTemplateBytes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference template as "},{"code":"Data","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Probe template as "},{"code":"Data","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"probeTemplateBytes"}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Result with matching score.","type":"text"}]}]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFTemplateMatcher(im)matchWithReferenceTemplateBytes:probeTemplateBytes:error:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"match"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplateBytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"probeTemplateBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC"}],"title":"match(referenceTemplateBytes:probeTemplateBytes:)"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplateBytes:probeTemplateBytes:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/templatematcher\/match(referencetemplatebytes:probetemplatebytes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/templatematcher\/match(referencetemplatebytes:probetemplatebytes:)"]}],"abstract":[{"type":"text","text":"Match reference and probe face templates."}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFTemplateMatcherResult":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotftemplatematcherresult","type":"topic","abstract":[{"type":"text","text":"Template matcher result."}],"fragments":[{"text":"DOTFTemplateMatcherResult","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFTemplateMatcherResult","title":"DOTFTemplateMatcherResult","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","title":"TemplateMatcher","navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateMatcher","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/templatematcher","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can match templates."}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher/Result":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/Result","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotfacecore\/templatematcher\/result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Result","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Template matcher result.","type":"text"}],"type":"topic","title":"TemplateMatcher.Result"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher/match(referenceTemplateBytes:probeTemplateBytes:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/templatematcher\/match(referencetemplatebytes:probetemplatebytes:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplateBytes:probeTemplateBytes:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"match"},{"kind":"text","text":"("},{"text":"referenceTemplateBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeTemplateBytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC","text":"Result"}],"navigatorTitle":[{"kind":"identifier","text":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:"}],"abstract":[{"type":"text","text":"Match reference and probe face templates."}],"title":"match(referenceTemplateBytes:probeTemplateBytes:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFTemplateMatcherResult","text":"DOTFTemplateMatcherResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplateMatcherResult"},{"kind":"text","text":" *) "},{"text":"matchWithReferenceTemplateBytes:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"referenceTemplateBytes","kind":"internalParam"},{"kind":"text","text":" "},{"text":"probeTemplateBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"probeTemplateBytes","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTFTemplateMatcher"},{"value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplateBytes:probeTemplateBytes:)\/title","value":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplateBytes:probeTemplateBytes:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"matchWithReferenceTemplateBytes:probeTemplateBytes:error:","kind":"identifier"}]}]}]}