{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPalmEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"navigatorTitle":[{"text":"isPalmEnabled","kind":"identifier"}],"title":"isPalmEnabled","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPalmEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isPalmEnabled","required":true,"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isPalmEnabled","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/ispalmenabled"]},{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/ispalmenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isPalmEnabled":{"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/ispalmenabled","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPalmEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isPalmEnabled","title":"isPalmEnabled"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isPalmEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isPalmEnabled"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPalmEnabled"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/title","op":"replace","value":"isPalmEnabled"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isPalmEnabled"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}]}]}