{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DotSdkLicenseProxy(py)isFaceEyeGazeLivenessScoreEnabled","symbolKind":"property","title":"isFaceEyeGazeLivenessScoreEnabled","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled"},"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkLicenseProxyProtocol.isFaceEyeGazeLivenessScoreEnabled","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","abstract":[{"text":"version: 8.4.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFaceEyeGazeLivenessScoreEnabled":{"abstract":[],"title":"isFaceEyeGazeLivenessScoreEnabled","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy":{"url":"\/documentation\/dotfacelite\/dotsdklicenseproxy","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"title":"DotSdkLicenseProxy"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"isFaceEyeGazeLivenessScoreEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}