{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessCorner@DOTFEyeGazeLivenessCornerTopRight","symbolKind":"case","roleHeading":"Case","title":"EyeGazeLivenessCorner.topRight","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerTopRight"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topRight"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/topright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenesscorner\/topright"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessCorner"]]},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessCorner":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessCorner","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessCorner","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenesscorner","title":"EyeGazeLivenessCorner","role":"symbol","abstract":[{"text":"Eye gaze liveness corner.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCorner"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessCorner/topRight":{"type":"topic","title":"EyeGazeLivenessCorner.topRight","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscorner\/topright","navigatorTitle":[{"text":"DOTFEyeGazeLivenessCornerTopRight","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessCorner\/topRight"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"DOTFEyeGazeLivenessCornerTopRight","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"DOTFEyeGazeLivenessCornerTopRight","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTFEyeGazeLivenessCornerTopRight","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/title","value":"DOTFEyeGazeLivenessCorner","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessCorner\/fragments","value":[{"text":"DOTFEyeGazeLivenessCorner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topRight\/title","value":"DOTFEyeGazeLivenessCornerTopRight"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessCorner~1topRight\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornerTopRight"}],"op":"replace"}]}]}