{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold"]}],"metadata":{"title":"faceDetectionConfidenceThreshold","navigatorTitle":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"role":"symbol","symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(py)faceDetectionConfidenceThreshold"},"abstract":[{"type":"text","text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval "},{"code":"[0.0, 1.0]","type":"codeVoice"},{"type":"text","text":". Default value is "},{"code":"0.06","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","kind":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","abstract":[{"text":"Face library configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/faceDetectionConfidenceThreshold":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold","type":"topic","navigatorTitle":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}],"abstract":[{"text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval ","type":"text"},{"type":"codeVoice","code":"[0.0, 1.0]"},{"text":". Default value is ","type":"text"},{"type":"codeVoice","code":"0.06"},{"text":".","type":"text"}],"title":"faceDetectionConfidenceThreshold","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"faceDetectionConfidenceThreshold","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/title","op":"replace","value":"faceDetectionConfidenceThreshold"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/fragments","op":"replace","value":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}]}]}]}