{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult\/face","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult"]]},"kind":"symbol","abstract":[{"text":"Face detection result.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","text":"Face"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessResult(py)face","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"}],"title":"face","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"face"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessresult\/face"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessresult\/face"]}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","title":"FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessResult":{"navigatorTitle":[{"text":"MultiRangeLivenessResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessResult","kind":"identifier"}],"abstract":[{"text":"The final result of the Multi-Range Liveness process.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessresult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult","title":"MultiRangeLivenessResult","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"abstract":[{"type":"text","text":"Detected face."}],"title":"FaceDetector.Face","type":"topic","url":"\/documentation\/dotfacelite\/facedetector\/face","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Face","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"title":"DOTFLFaceDetectorFace","abstract":[{"type":"text","text":"Detected face."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","url":"\/documentation\/dotfacelite\/dotflfacedetectorface","fragments":[{"text":"DOTFLFaceDetectorFace","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessResult/face":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult\/face","abstract":[{"text":"Face detection result.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","text":"Face"}],"title":"face","url":"\/documentation\/dotfacelite\/multirangelivenessresult\/face","navigatorTitle":[{"kind":"identifier","text":"face"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"face","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"face"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace","text":"DOTFLFaceDetectorFace","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"face","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","op":"replace"},{"value":"DOTFLMultiRangeLivenessResult","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessResult"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessResult"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult\/navigatorTitle","op":"replace"},{"value":"face","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult~1face\/title","op":"replace"},{"value":[{"kind":"identifier","text":"face"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult~1face\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}