{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotnfc\/nfckey\/error\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotNfc"}],"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false}],"symbolKind":"property","title":"internalError","externalID":"s:6DotNfc0B3KeyC5ErrorO08internalD0sAD_pSgvp"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.internalError","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/internalError"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use classes of `TravelDocumentReaderPassword` protocol instead.)"}],"type":"paragraph"}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/NfcKey":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcKey","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","deprecated":true,"abstract":[{"text":"NFC password created from document number, date of expiry and date of birth of MRZ.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/nfckey","kind":"symbol","role":"symbol","title":"NfcKey"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","deprecated":true,"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/nfckey\/error","kind":"symbol","role":"symbol","title":"NfcKey.Error"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.15.0","type":"text"}],"title":"DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/internalError":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/internalError","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error\/internalerror","deprecated":true,"kind":"symbol","title":"internalError","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"kind":"identifier","text":"DOTNNfcKey"}]},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}