{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculateWidthToHeightRatio()"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)calculateWidthToHeightRatio","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"role":"symbol","title":"calculateWidthToHeightRatio()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]},"sections":[],"abstract":[{"type":"text","text":"Calculate width to height ratio."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imagesize\/calculatewidthtoheightratio()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/imagesize\/calculatewidthtoheightratio()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageSize/calculateWidthToHeightRatio()":{"title":"calculateWidthToHeightRatio()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"abstract":[{"text":"Calculate width to height ratio.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize\/calculateWidthToHeightRatio()","url":"\/documentation\/dotfacecore\/imagesize\/calculatewidthtoheightratio()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"abstract":[{"text":"Image size in pixels.","type":"text"}],"title":"ImageSize","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/imagesize","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"calculateWidthToHeightRatio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1calculateWidthToHeightRatio()\/title","op":"replace","value":"calculateWidthToHeightRatio"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize~1calculateWidthToHeightRatio()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateWidthToHeightRatio"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}