{"metadata":{"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationCAEycfc","title":"init()","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","platforms":[]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init()"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Create the MagnifEye liveness configuration with default values.","type":"text"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","abstract":[{"text":"Configuration options for the UI MagnifEye Liveness component.","type":"text"}],"title":"MagnifEyeLivenessViewController.Configuration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class/init()":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init()","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init()","type":"topic","abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration with default values."}],"kind":"symbol","role":"symbol","deprecated":true,"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"deprecated":true,"role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","title":"MagnifEyeLivenessViewController","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFLMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]}]}]}