{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/fullDateOfBirth","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"fullDateOfBirth","role":"symbol","modules":[{"name":"DotNfc"}],"platforms":[{"introducedAt":"13.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"fullDateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fullDateOfBirth"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)fullDateOfBirth"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"abstract":[{"text":"Full date of birth.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"fullDateOfBirth","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/fulldateofbirth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/fulldateofbirth"]}],"references":{"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/fullDateOfBirth":{"type":"topic","kind":"symbol","title":"fullDateOfBirth","abstract":[{"type":"text","text":"Full date of birth."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullDateOfBirth"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"fullDateOfBirth","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/fullDateOfBirth","role":"symbol","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/fulldateofbirth"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocument","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"title":"TravelDocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"title":"AdditionalPersonalDetails","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"abstract":[{"text":"Contents of DG11 - Additional personal details.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/additionalpersonaldetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"fullDateOfBirth"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"fullDateOfBirth","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"fullDateOfBirth"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"fullDateOfBirth","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1fullDateOfBirth\/title"},{"value":[{"text":"fullDateOfBirth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1fullDateOfBirth\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"},{"value":"DOTNAdditionalPersonalDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}]}]}]}