{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/SizeTooSmallValidator"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/SizeTooSmallValidator\/identifier","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/identifier"]}],"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"sections":[],"kind":"symbol","metadata":{"title":"identifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooSmallValidator(py)identifier","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol"},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureController","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"title":"PalmAutoCaptureController","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/SizeTooSmallValidator/identifier":{"type":"topic","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"identifier","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/identifier","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/SizeTooSmallValidator\/identifier"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/SizeTooSmallValidator":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","title":"SizeTooSmallValidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"identifier","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"identifier","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"value":"identifier","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1SizeTooSmallValidator~1identifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1SizeTooSmallValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","value":"DOTPSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"op":"replace"}]}]}