{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/initialize(license:)"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(cs)DotFaceLiteLibrary(im)initializeWithLicense:error:","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"title":"initialize(license:)","symbolKind":"method"},"abstract":[{"text":"Initialize library with license.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DotSdkLicenseProxyProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" license."}]}],"name":"license"}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary\/initialize(license:)"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotFaceLiteLibrary":{"title":"DotFaceLiteLibrary","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":" library initialization."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfacelitelibrary","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibrary"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"role":"symbol","title":"DotSdkLicenseProxyProtocol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotFaceLiteLibrary/initialize(license:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Initialize library with license."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/initialize(license:)","role":"symbol","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/initialize(license:)","type":"topic","title":"initialize(license:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initializeWithLicense:error:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"initializeWithLicense:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@DotFaceLite@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier","text":"id<DotSdkLicenseProxyProtocol>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"license"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DotFaceLiteLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title"},{"value":[{"kind":"identifier","text":"DotFaceLiteLibrary"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1initialize(license:)\/title","value":"initializeWithLicense:error:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithLicense:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1initialize(license:)\/fragments"}]}]}