{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/isEqual(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(im)isEqual:","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"object","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/wrappedfloat\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/wrappedfloat\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}],"kind":"symbol","role":"symbol","title":"WrappedFloat","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":" value for Objective-C support.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"type":"topic","url":"\/documentation\/dotfingerscore\/wrappedfloat"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/wrappedfloat\/isequal(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/isEqual(_:)","title":"isEqual(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isEqual:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTWrappedFloat","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/fragments","op":"replace"},{"value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/navigatorTitle","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1isEqual(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}