{"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/error\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"LocalizedError Implementations","roleHeading":"API Collection","modules":[{"name":"DotDocument"}],"role":"collectionGroup"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error\/LocalizedError-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error\/failureReason","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error\/helpAnchor","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error\/recoverySuggestion"],"title":"Instance Properties","anchor":"Instance-Properties"}],"kind":"article","references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","abstract":[{"text":"Configuration of the document auto capture non-UI component.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"DocumentAutoCaptureController.Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/Error":{"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/error","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"DocumentAutoCaptureController.Configuration.Error","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/Error/helpAnchor":{"type":"topic","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error\/helpAnchor","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/error\/helpanchor","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/Error/recoverySuggestion":{"type":"topic","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error\/recoverySuggestion","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/error\/recoverysuggestion","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/Error/failureReason":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/Error\/failureReason","title":"failureReason","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/error\/failurereason"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}