{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"id"}],"title":"id","symbolKind":"property","externalID":"c:@M@DotNfc@objc(pl)DotLibrary(py)id","role":"symbol","required":true,"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId"}],"modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/dotlibrary\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotlibrary\/id"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/id","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibraryId","preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"type":"topic","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/dotlibrary"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibraryId":{"url":"\/documentation\/dotnfc\/dotlibraryid","title":"DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibraryId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"type":"topic","role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" library identifier.","type":"text"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"text":"version: 8.4.1","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotLibrary/id":{"url":"\/documentation\/dotnfc\/dotlibrary\/id","abstract":[],"title":"id","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId","kind":"typeIdentifier"}],"required":true,"navigatorTitle":[{"text":"id","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibrary\/id","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotLibraryId","text":"DotLibraryId","preciseIdentifier":"c:@M@DotNfc@E@DotLibraryId"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/title"},{"value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"value":"id","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1id\/title","op":"replace"},{"value":[{"text":"id","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotLibrary~1id\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}