{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzdate\/isequal(_:)"]},{"paths":["\/documentation\/dotdocument\/mrzdate\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"title":"isEqual(_:)","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate(im)isEqual:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/isEqual(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"title":"MrzDate","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzDate","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","url":"\/documentation\/dotdocument\/mrzdate","abstract":[{"text":"Date parsed from Machine Readable Zone.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzDate/isEqual(_:)":{"url":"\/documentation\/dotdocument\/mrzdate\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/isEqual(_:)","abstract":[],"title":"isEqual(_:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"value":"DOTMrzDate","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title"},{"value":[{"text":"DOTMrzDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1isEqual(_:)\/title","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}