{"metadata":{"title":"init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)","roleHeading":"Initializer","symbolKind":"init","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds14validationMode13mrzValidation23isDetectionLayerVisible0Q12TorchEnabled0q5VideodV012cameraFacing0X16PreviewScaleType15placeholderType0q6CamerazT0AESSSg_AE07QualitykL0CAA0pN0OAA03MrzP0OS3b0A6Camera06CameraY0OAX06CameraZ9ScaleTypeOAA15PlaceholderTypeOSbtcfc","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"validationMode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"mrzValidation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderType"},{"kind":"text","text":": "},{"text":"PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:iscamerapreviewvisible:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"text":": ","kind":"text"},{"text":"QualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","kind":"typeIdentifier"},{"kind":"text","text":" = QualityAttributeThresholdPresets.standard.build(), "},{"text":"validationMode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"kind":"text","text":" = Defaults.validationMode, "},{"text":"mrzValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":" = Defaults.mrzValidation, ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = Defaults.isVideoCaptureEnabled, "},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","kind":"typeIdentifier","text":"CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"kind":"externalParam","text":"placeholderType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","text":"PlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.placeholderType, "},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isCameraPreviewVisible)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"type":"topic","abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"title":"MrzValidation","url":"\/documentation\/dotdocument\/mrzvalidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","type":"topic","abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"kind":"symbol","title":"ValidationMode","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationMode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","url":"\/documentation\/dotdocument\/validationmode","role":"symbol","navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/placeholdertype","title":"PlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"url":"\/documentation\/dotdocument\/camerapreviewscaletype","role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"title":"CameraPreviewScaleType"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:placeholdertype:iscamerapreviewvisible:)","role":"symbol","abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"validationMode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","kind":"typeIdentifier","text":"ValidationMode"},{"kind":"text","text":", "},{"text":"mrzValidation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"kind":"text","text":", "},{"text":"placeholderType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","title":"init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:isCameraPreviewVisible:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","title":"DocumentAutoCaptureViewController.Configuration","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"kind":"symbol","url":"\/documentation\/dotdocument\/camerafacing","type":"topic","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","op":"replace"},{"value":"DOTDValidationMode","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTDValidationMode"}]},{"value":"DOTDPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title"},{"op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments"}]}]}