{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"Initializer","symbolKind":"init","title":"init(format:bytes:size:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"s:7DotCore5ImageC6format5bytes4sizeAcA0C6FormatO_10Foundation4DataVAA0C4SizeCtcfc"},"variants":[{"paths":["\/documentation\/dotfacecore\/image\/init(format:bytes:size:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/init(format:bytes:size:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat","url":"\/documentation\/dotfacecore\/imageformat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat"},"doc://DotFaceCore/documentation/DotFaceCore/Image/init(format:bytes:size:)":{"title":"init(format:bytes:size:)","url":"\/documentation\/dotfacecore\/image\/init(format:bytes:size:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image\/init(format:bytes:size:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","abstract":[{"type":"text","text":"Image size in pixels."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/imagesize","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"url":"\/documentation\/dotfacecore\/image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","title":"Image","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/navigatorTitle","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}