{"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"roleHeading":"Instance Method","extendedModule":"DotCore","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"title":"mirrored()","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(im)mirrored"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/mirrored()","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/corners\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/corners\/mirrored()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier","text":"Corners"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Corners/mirrored()":{"url":"\/documentation\/dotfacecore\/corners\/mirrored()","title":"mirrored()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/mirrored()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/Corners":{"url":"\/documentation\/dotfacecore\/corners","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"type":"topic","abstract":[{"type":"text","text":"Four detected corners in an image."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"kind":"symbol","title":"Corners"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mirrored","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTCorners","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"mirrored","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1mirrored()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1mirrored()\/fragments"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/title"},{"value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/fragments"},{"value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/navigatorTitle"}]}]}