{"abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotnfc\/mrzcheckdigit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/mrzcheckdigit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzCheckDigit"}],"symbolKind":"class","modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Class","title":"MrzCheckDigit","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/init(value:isValid:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isValid","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/value"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTMrzCheckDigit) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"references":{"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/isValid":{"type":"topic","abstract":[{"type":"text","text":"Denotes whether a checksum of a particular MRZ element is valid."}],"url":"\/documentation\/dotnfc\/mrzcheckdigit\/isvalid","title":"isValid","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isValid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isValid","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isValid"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/isEqual(_:)":{"url":"\/documentation\/dotnfc\/mrzcheckdigit\/isequal(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isEqual(_:)"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/init(value:isValid:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithValue:isValid:"}],"abstract":[],"title":"init(value:isValid:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/init(value:isValid:)","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/mrzcheckdigit\/init(value:isvalid:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isValid","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/description":{"role":"symbol","title":"description","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/mrzcheckdigit\/description"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzcheckdigit","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"title":"MrzCheckDigit","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/value":{"url":"\/documentation\/dotnfc\/mrzcheckdigit\/value","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"A string value of the check digit belonging to a particular MRZ element."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/value","title":"value","type":"topic","navigatorTitle":[{"text":"value","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","url":"\/documentation\/dotnfc\/mrzcheckdigit\/hash","title":"hash","type":"topic","kind":"symbol","abstract":[]},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isValid","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/value"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/init(value:isValid:)","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTMrzCheckDigit","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isValid\/title","value":"isValid"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isValid\/fragments","value":[{"text":"isValid","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1init(value:isValid:)\/title","value":"initWithValue:isValid:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1init(value:isValid:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:isValid:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/navigatorTitle","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1value\/fragments","value":[{"kind":"identifier","text":"value"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]}]}]}