{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangledouble"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/rectangledouble"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble","roleHeading":"Class"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTRectangleDouble) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/init(left:top:right:bottom:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/bottom","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/cgRect","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/height","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/left","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/points","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/right","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/top","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/width","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/widthToHeightRatio"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/isEqual(_:)","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/mirrored()","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/rebased(parentRectangle:)"],"anchor":"Instance-Methods","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/fullRectangle","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/zeroRectangle"],"anchor":"Type-Properties","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/from(cgRect:)"],"anchor":"Type-Methods","generated":true}],"references":{"doc://DotNfc/documentation/DotNfc/RectangleDouble/cgRect":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"title":"cgRect","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/cgRect","kind":"symbol","url":"\/documentation\/dotnfc\/rectangledouble\/cgrect","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}]},"doc://DotNfc/documentation/DotNfc/RectangleDouble/widthToHeightRatio":{"title":"widthToHeightRatio","url":"\/documentation\/dotnfc\/rectangledouble\/widthtoheightratio","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"widthToHeightRatio"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/widthToHeightRatio","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/from(cgRect:)":{"title":"from(cgRect:)","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/from(cgRect:)","url":"\/documentation\/dotnfc\/rectangledouble\/from(cgrect:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}]},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/rebased(parentRectangle:)":{"title":"rebased(parentRectangle:)","abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/rebased(parentRectangle:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"url":"\/documentation\/dotnfc\/rectangledouble\/rebased(parentrectangle:)","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/description":{"url":"\/documentation\/dotnfc\/rectangledouble\/description","abstract":[],"title":"description","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/init(left:top:right:bottom:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/init(left:top:right:bottom:)","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/rectangledouble\/init(left:top:right:bottom:)","title":"init(left:top:right:bottom:)","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/height":{"url":"\/documentation\/dotnfc\/rectangledouble\/height","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/height","title":"height","kind":"symbol","navigatorTitle":[{"text":"height","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/bottom":{"navigatorTitle":[{"text":"bottom","kind":"identifier"}],"kind":"symbol","title":"bottom","url":"\/documentation\/dotnfc\/rectangledouble\/bottom","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/bottom","role":"symbol","abstract":[{"text":"Bottom edge.","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/RectangleDouble/points":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":"]"}],"title":"points","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/points","navigatorTitle":[{"text":"points","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/rectangledouble\/points","kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/zeroRectangle":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"zeroRectangle"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/zeroRectangle","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/rectangledouble\/zerorectangle","title":"zeroRectangle","kind":"symbol"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/hash":{"url":"\/documentation\/dotnfc\/rectangledouble\/hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/hash","kind":"symbol","type":"topic","title":"hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[]},"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"url":"\/documentation\/dotnfc\/rectangledouble","role":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","title":"RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/width":{"title":"width","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"width"}],"url":"\/documentation\/dotnfc\/rectangledouble\/width","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/width","type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/right":{"navigatorTitle":[{"text":"right","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","abstract":[{"type":"text","text":"Right edge."}],"url":"\/documentation\/dotnfc\/rectangledouble\/right","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/right","role":"symbol","title":"right"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/left":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"left","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/rectangledouble\/left","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/left","abstract":[{"type":"text","text":"Left edge."}],"title":"left"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/top":{"url":"\/documentation\/dotnfc\/rectangledouble\/top","abstract":[{"text":"Top edge.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/top","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"top","type":"topic","navigatorTitle":[{"kind":"identifier","text":"top"}]},"doc://DotNfc/documentation/DotNfc/RectangleDouble/fullRectangle":{"type":"topic","kind":"symbol","title":"fullRectangle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"navigatorTitle":[{"text":"fullRectangle","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/rectangledouble\/fullrectangle","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/fullRectangle"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/mirrored()":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}],"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/mirrored()","title":"mirrored()","url":"\/documentation\/dotnfc\/rectangledouble\/mirrored()","navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"type":"topic"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/RectangleDouble/isEqual(_:)":{"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"title":"isEqual(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/isEqual(_:)","url":"\/documentation\/dotnfc\/rectangledouble\/isequal(_:)","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTRectangleDouble","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/bottom","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/cgRect","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/height","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/left","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/points","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/right","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/top","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/width","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/widthToHeightRatio"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/init(left:top:right:bottom:)","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/isEqual(_:)","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/mirrored()","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/rebased(parentRectangle:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/fullRectangle","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/zeroRectangle"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/from(cgRect:)"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTRectangleDouble"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"cgRect","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1cgRect\/title"},{"value":[{"text":"cgRect","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1cgRect\/fragments"},{"value":"widthToHeightRatio","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1widthToHeightRatio\/title"},{"value":[{"text":"widthToHeightRatio","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1widthToHeightRatio\/fragments"},{"value":"fromCgRect:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1from(cgRect:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgRect:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1from(cgRect:)\/fragments"},{"value":"rebasedWithParentRectangle:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1rebased(parentRectangle:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1rebased(parentRectangle:)\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1description\/fragments"},{"value":"initWithLeft:top:right:bottom:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1init(left:top:right:bottom:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1init(left:top:right:bottom:)\/fragments"},{"value":"height","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1height\/title"},{"value":[{"kind":"identifier","text":"height"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1height\/fragments"},{"value":"bottom","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1bottom\/title"},{"value":[{"text":"bottom","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1bottom\/fragments"},{"value":"points","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1points\/title"},{"value":[{"text":"points","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1points\/fragments"},{"value":"zeroRectangle","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1zeroRectangle\/title"},{"value":[{"kind":"identifier","text":"zeroRectangle"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1zeroRectangle\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1hash\/fragments"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/navigatorTitle"},{"value":"width","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1width\/title"},{"value":[{"kind":"identifier","text":"width"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1width\/fragments"},{"value":"right","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1right\/title"},{"value":[{"text":"right","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1right\/fragments"},{"value":"left","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1left\/title"},{"value":[{"text":"left","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1left\/fragments"},{"value":"top","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1top\/title"},{"value":[{"kind":"identifier","text":"top"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1top\/fragments"},{"value":"fullRectangle","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1fullRectangle\/title"},{"value":[{"kind":"identifier","text":"fullRectangle"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1fullRectangle\/fragments"},{"value":"mirrored","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1mirrored()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1mirrored()\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1isEqual(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}