{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chipAuthenticationStatus"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debuginfo\/chipauthenticationstatus"]},{"paths":["\/documentation\/dotnfc\/debuginfo\/chipauthenticationstatus"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/chipAuthenticationStatus","interfaceLanguage":"swift"},"metadata":{"title":"chipAuthenticationStatus","platforms":[{"deprecated":false,"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)chipAuthenticationStatus","navigatorTitle":[{"text":"chipAuthenticationStatus","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"chipAuthenticationStatus"},{"kind":"text","text":": "},{"text":"ChipAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property"},"references":{"doc://DotNfc/documentation/DotNfc/DebugInfo":{"title":"DebugInfo","url":"\/documentation\/dotnfc\/debuginfo","kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","navigatorTitle":[{"kind":"identifier","text":"DebugInfo"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DebugInfo","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"kind":"symbol","title":"ChipAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}]},"doc://DotNfc/documentation/DotNfc/DebugInfo/chipAuthenticationStatus":{"role":"symbol","title":"chipAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/chipAuthenticationStatus","url":"\/documentation\/dotnfc\/debuginfo\/chipauthenticationstatus","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"chipAuthenticationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","text":"ChipAuthenticationStatus"},{"text":"?","kind":"text"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"chipAuthenticationStatus"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.15.0","type":"text"}],"title":"DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"chipAuthenticationStatus","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"chipAuthenticationStatus","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus","text":"DOTNChipAuthenticationStatus"},{"text":" * ","kind":"text"},{"text":"chipAuthenticationStatus","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"DOTNDebugInfo","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]},{"op":"replace","value":"chipAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1chipAuthenticationStatus\/title"},{"value":[{"kind":"identifier","text":"chipAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1chipAuthenticationStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}