{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dataAuthenticationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DataAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/dataAuthenticationStatus","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dataAuthenticationStatus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DataAuthenticationStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus"},{"kind":"text","text":"?"}],"title":"dataAuthenticationStatus","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","platforms":[{"deprecated":false,"introducedAt":"13.0","unavailable":false,"name":"iOS","beta":false}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)dataAuthenticationStatus","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"dataAuthenticationStatus","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debuginfo\/dataauthenticationstatus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debuginfo\/dataauthenticationstatus"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.15.0","type":"text"}],"title":"DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DebugInfo":{"title":"DebugInfo","url":"\/documentation\/dotnfc\/debuginfo","kind":"symbol","abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","navigatorTitle":[{"kind":"identifier","text":"DebugInfo"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DebugInfo","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus","abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"title":"DataAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataAuthenticationStatus"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DebugInfo/dataAuthenticationStatus":{"role":"symbol","title":"dataAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/dataAuthenticationStatus","url":"\/documentation\/dotnfc\/debuginfo\/dataauthenticationstatus","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataAuthenticationStatus"},{"text":": ","kind":"text"},{"text":"DataAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"dataAuthenticationStatus","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dataAuthenticationStatus"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"dataAuthenticationStatus","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTNDataAuthenticationStatus","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus"},{"kind":"text","text":" * "},{"text":"dataAuthenticationStatus","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"DOTNDebugInfo","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","value":"DOTNDataAuthenticationStatus","op":"replace"},{"value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1dataAuthenticationStatus\/title","value":"dataAuthenticationStatus","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1dataAuthenticationStatus\/fragments","value":[{"text":"dataAuthenticationStatus","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}