{"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTWrappedDouble) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/wrappeddouble"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/wrappeddouble"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"WrappedDouble","symbolKind":"class","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/init(value:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/value"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/WrappedDouble/value":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/value","title":"value","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/wrappeddouble\/value","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"value"}]},"doc://DotDocument/documentation/DotDocument/WrappedDouble/init(value:)":{"abstract":[],"title":"init(value:)","kind":"symbol","url":"\/documentation\/dotdocument\/wrappeddouble\/init(value:)","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/init(value:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value for Objective-C support.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","title":"WrappedDouble","type":"topic","url":"\/documentation\/dotdocument\/wrappeddouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}]},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/WrappedDouble/hash":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/wrappeddouble\/hash","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash"},"doc://DotDocument/documentation/DotDocument/WrappedDouble/isEqual(_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/isEqual(_:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotdocument\/wrappeddouble\/isequal(_:)","abstract":[]},"doc://DotDocument/documentation/DotDocument/WrappedDouble/description":{"abstract":[],"title":"description","role":"symbol","url":"\/documentation\/dotdocument\/wrappeddouble\/description","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTWrappedDouble"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/value"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/init(value:)","doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble\/isEqual(_:)"],"title":"Instance Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTWrappedDouble"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1value\/title","value":"value","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1value\/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1init(value:)\/title","value":"initWithValue:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1init(value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"}]}]}