{"abstract":[{"type":"text","text":"Create new "},{"code":"BaseDocumentAutoCaptureViewController","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"createWithBaseConfiguration:"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController"}],"modules":[{"name":"DotDocument"}],"symbolKind":"method","roleHeading":"Type Method","title":"create(baseConfiguration:)","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController(cm)createWithBaseConfiguration:"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","text":"Configuration","kind":"typeIdentifier"},{"text":" = .init()) -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"baseConfiguration","content":[{"inlineContent":[{"text":"Configure the capture process.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/create(baseconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/create(baseconfiguration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/create(baseConfiguration:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"BaseDocumentAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}]},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"kind":"symbol","role":"symbol","type":"topic","title":"BaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/create(baseConfiguration:)":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/create(baseConfiguration:)","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/create(baseconfiguration:)","abstract":[{"text":"Create new ","type":"text"},{"code":"BaseDocumentAutoCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","text":"BaseDocumentAutoCaptureViewController"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createWithBaseConfiguration:"}],"title":"create(baseConfiguration:)"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"type":"topic","kind":"symbol","role":"symbol","title":"DOTDBaseDocumentAutoCaptureConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"fragments":[{"text":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createWithBaseConfiguration:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithBaseConfiguration:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureViewController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","text":"DOTDBaseDocumentAutoCaptureViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithBaseConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","text":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"baseConfiguration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"baseConfiguration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the capture process."}]}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDBaseDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTDBaseDocumentAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1create(baseConfiguration:)\/title","op":"replace","value":"createWithBaseConfiguration:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController~1create(baseConfiguration:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBaseConfiguration:"}]}]}]}