{"variants":[{"paths":["\/documentation\/dotdocument\/localization\/localizationdictionary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/localization\/localizationdictionary"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You also need to set "},{"code":"useLocalizationDictionary","type":"codeVoice"},{"type":"text","text":" flag to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]}],"style":"note"}]}],"abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"metadata":{"modules":[{"name":"DotDocument"}],"role":"symbol","title":"localizationDictionary","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]?"}],"navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDLocalization(cpy)localizationDictionary","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/localizationDictionary"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Localization"]]},"references":{"doc://DotDocument/documentation/DotDocument/Localization":{"type":"topic","role":"symbol","title":"Localization","url":"\/documentation\/dotdocument\/localization","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"navigatorTitle":[{"text":"Localization","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotDocument","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Localization/localizationDictionary":{"navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Localization\/localizationDictionary","kind":"symbol","type":"topic","abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"url":"\/documentation\/dotdocument\/localization\/localizationdictionary","title":"localizationDictionary","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"localizationDictionary","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"localizationDictionary","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"localizationDictionary"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/title","value":"DOTDLocalization"},{"op":"replace","value":[{"text":"DOTDLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1localizationDictionary\/title","value":"localizationDictionary","op":"replace"},{"value":[{"kind":"identifier","text":"localizationDictionary"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Localization~1localizationDictionary\/fragments","op":"replace"}]}]}