{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization\/useLocalizationDictionary"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization"]]},"variants":[{"paths":["\/documentation\/dotdocument\/localization\/uselocalizationdictionary"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/localization\/uselocalizationdictionary"]}],"abstract":[{"text":"If you set this to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", ","type":"text"},{"code":"localizationDictionary","type":"codeVoice"},{"type":"text","text":" will be used to localize strings. Default value is "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","roleHeading":"Type Property","title":"useLocalizationDictionary","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDLocalization(cpy)useLocalizationDictionary"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/Localization/useLocalizationDictionary":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"useLocalizationDictionary","kind":"identifier"}],"url":"\/documentation\/dotdocument\/localization\/uselocalizationdictionary","abstract":[{"text":"If you set this to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":", "},{"type":"codeVoice","code":"localizationDictionary"},{"type":"text","text":" will be used to localize strings. Default value is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"title":"useLocalizationDictionary","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization\/useLocalizationDictionary"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Localization":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"url":"\/documentation\/dotdocument\/localization","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"title":"Localization","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"useLocalizationDictionary"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"useLocalizationDictionary"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"useLocalizationDictionary","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"useLocalizationDictionary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization~1useLocalizationDictionary\/title"},{"value":[{"kind":"identifier","text":"useLocalizationDictionary"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization~1useLocalizationDictionary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization\/title","value":"DOTDLocalization"},{"value":[{"text":"DOTDLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization\/fragments"}]}]}