{"sections":[],"metadata":{"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)description","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/description","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/description"]}],"references":{"doc://DotDocument/documentation/DotDocument/CameraConfiguration":{"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration","role":"symbol","title":"CameraConfiguration","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/cameraconfiguration"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration/description":{"title":"description","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/description","kind":"symbol","url":"\/documentation\/dotdocument\/cameraconfiguration\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1description\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}