{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/previewScaleType","interfaceLanguage":"swift"},"abstract":[{"text":"Preview scale type. Default is ","type":"text"},{"code":".fit","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/previewscaletype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/cameraconfiguration\/previewscaletype"]}],"metadata":{"symbolKind":"property","title":"previewScaleType","navigatorTitle":[{"kind":"identifier","text":"previewScaleType"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)previewScaleType","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}]},"references":{"doc://DotDocument/documentation/DotDocument/CameraConfiguration/previewScaleType":{"type":"topic","url":"\/documentation\/dotdocument\/cameraconfiguration\/previewscaletype","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Preview scale type. Default is ","type":"text"},{"code":".fit","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/previewScaleType","role":"symbol","navigatorTitle":[{"text":"previewScaleType","kind":"identifier"}],"title":"previewScaleType"},"doc://DotDocument/documentation/DotDocument/CameraPreviewScaleType":{"title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","url":"\/documentation\/dotdocument\/camerapreviewscaletype","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/CameraConfiguration":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"url":"\/documentation\/dotdocument\/cameraconfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"previewScaleType","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"previewScaleType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"previewScaleType"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"previewScaleType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1previewScaleType\/title"},{"value":[{"text":"previewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1previewScaleType\/fragments"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/title"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraPreviewScaleType\/navigatorTitle"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/title"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}