{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"feature","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","text":"FaceFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint"]]},"abstract":[{"text":"Face feature.","type":"text"}],"metadata":{"role":"symbol","title":"feature","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"feature"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"feature"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceFeature","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceFeaturePoint(py)feature"},"variants":[{"paths":["\/documentation\/dotfacecore\/facefeaturepoint\/feature"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeaturepoint\/feature"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/feature","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint/feature":{"abstract":[{"type":"text","text":"Face feature."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facefeaturepoint\/feature","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"feature","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceFeature","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature"}],"title":"feature","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"feature"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/feature"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint":{"url":"\/documentation\/dotfacecore\/facefeaturepoint","title":"FaceFeaturePoint","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceFeaturePoint","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceFeaturePoint"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint","kind":"symbol","abstract":[{"text":"Face feature point contains face feature, point and score.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeature":{"type":"topic","url":"\/documentation\/dotfacecore\/facefeature","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","abstract":[{"type":"text","text":"Available face features."}],"title":"FaceFeature","navigatorTitle":[{"text":"FaceFeature","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"FaceFeature","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"feature","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"feature","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeature","text":"DOTFFaceFeature","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature"},{"kind":"text","text":" "},{"kind":"identifier","text":"feature"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"feature","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1feature\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1feature\/fragments","value":[{"kind":"identifier","text":"feature"}],"op":"replace"},{"op":"replace","value":"DOTFFaceFeaturePoint","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint\/fragments","value":[{"text":"DOTFFaceFeaturePoint","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/title","value":"DOTFFaceFeature"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeature\/fragments","op":"replace","value":[{"text":"DOTFFaceFeature","kind":"identifier"}]}]}]}