{"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:timestampMillis:"}],"navigatorTitle":[{"text":"initWithImage:timestampMillis:","kind":"identifier"}],"title":"initWithImage:timestampMillis:","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerSample(im)initWithImage:timestampMillis:"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timestampMillis:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"timestampMillis","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample\/initWithImage:timestampMillis:","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample\/initwithimage:timestampmillis:"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerSample/initWithImage:timestampMillis:":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:timestampMillis:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:timestampMillis:"}],"title":"initWithImage:timestampMillis:","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample\/initwithimage:timestampmillis:","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample\/initWithImage:timestampMillis:"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerSample":{"url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerSample"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the document auto capture process."}],"title":"DOTDDocumentAutoCaptureControllerSample","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Image":{"url":"\/documentation\/dotdocument\/image","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"title":"Image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}