{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isRealTimeTransactionReportingEnabled","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isRealTimeTransactionReportingEnabled","navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"kind":"symbol","title":"DotSdkLicenseProxyProtocol","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"title":"isRealTimeTransactionReportingEnabled","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"required":true,"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.6.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isRealTimeTransactionReportingEnabled","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title","value":"isRealTimeTransactionReportingEnabled"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}]}]}]}