{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/defaultMinConfidenceThreshold","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator"]]},"metadata":{"roleHeading":"Type Property","title":"defaultMinConfidenceThreshold","role":"symbol","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinConfidenceThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentNotDetectedValidator(cpy)defaultMinConfidenceThreshold"},"abstract":[{"type":"text","text":"Default threshold is 0.9."}],"variants":[{"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/defaultminconfidencethreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/defaultminconfidencethreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/defaultMinConfidenceThreshold":{"abstract":[{"text":"Default threshold is 0.9.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"defaultMinConfidenceThreshold","navigatorTitle":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/defaultMinConfidenceThreshold","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/defaultminconfidencethreshold","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"kind":"symbol","title":"DocumentNotDetectedValidator","abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"defaultMinConfidenceThreshold","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinConfidenceThreshold"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"defaultMinConfidenceThreshold","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1defaultMinConfidenceThreshold\/title","op":"replace"},{"value":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1defaultMinConfidenceThreshold\/fragments","op":"replace"},{"value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","op":"replace"},{"value":"DOTDDocumentNotDetectedValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","op":"replace"},{"value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","op":"replace"},{"value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}