{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/width","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"width","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"width"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(py)width"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize"]]},"sections":[],"abstract":[{"type":"text","text":"Image width in pixels."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imagesize\/width"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imagesize\/width"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/ImageSize":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","abstract":[{"type":"text","text":"Image size in pixels."}],"url":"\/documentation\/dotnfc\/imagesize","kind":"symbol","role":"symbol","title":"ImageSize","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}]},"doc://DotNfc/documentation/DotNfc/ImageSize/width":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"width"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[{"type":"text","text":"Image width in pixels."}],"url":"\/documentation\/dotnfc\/imagesize\/width","title":"width","kind":"symbol","type":"topic","navigatorTitle":[{"text":"width","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/width"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.15.0","type":"text"}],"title":"DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"width","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"width","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments"},{"value":"width","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1width\/title"},{"value":[{"text":"width","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1width\/fragments"}]}]}