{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"title":"logLevel","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLLogger(cpy)logLevel","roleHeading":"Type Property","role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/logger\/loglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/logger\/loglevel"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"LoggerLogLevel","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/logLevel","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/LoggerLogLevel":{"url":"\/documentation\/dotfacelite\/loggerloglevel","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","title":"LoggerLogLevel","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"abstract":[{"text":"Available log levels.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Logger/logLevel":{"navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/logger\/loglevel","kind":"symbol","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"title":"logLevel","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/logLevel","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}]},"doc://DotFaceLite/documentation/DotFaceLite/Logger":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/logger","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"title":"Logger"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"logLevel","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"logLevel"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"DOTLoggerLogLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments","op":"replace"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1LoggerLogLevel\/navigatorTitle","op":"replace"},{"value":"logLevel","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1logLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"logLevel"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1logLevel\/fragments","op":"replace"},{"value":"DOTFLLogger","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/title","op":"replace"},{"value":[{"text":"DOTFLLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/fragments","op":"replace"},{"value":[{"text":"DOTFLLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}