{"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/bgraRawImage","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/deviceTiltAngles","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/face","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/validatorIdentifiers"],"title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturedetection"]},{"paths":["\/documentation\/dotfacelite\/faceautocapturedetection"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"title":"Face auto capture process","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController"],["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"],["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"title":"Conforms To"}],"metadata":{"title":"FaceAutoCaptureDetection","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}]},"abstract":[{"type":"text","text":"The result of the image processing during the face auto capture process."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceAutoCaptureDetection) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection/description":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"title":"description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturedetection\/description"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DetectionPosition":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"url":"\/documentation\/dotfacelite\/detectionposition","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","role":"symbol","kind":"symbol","title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"title":"MagnifEyeLivenessViewController","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection/face":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection\/face","abstract":[{"text":"Face detection result.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/face","kind":"symbol","type":"topic","role":"symbol","title":"face","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"face","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection/init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection\/init(bgrarawimage:face:devicetiltangles:validatoridentifiers:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles"},{"kind":"text","text":"?, "},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)","title":"init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)","role":"symbol","navigatorTitle":[{"text":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetection","kind":"symbol","title":"FaceAutoCaptureDetection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","type":"topic","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection/bgraRawImage":{"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturedetection\/bgrarawimage","title":"bgraRawImage","abstract":[{"text":"Detection image.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/bgraRawImage","navigatorTitle":[{"kind":"identifier","text":"bgraRawImage"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection/deviceTiltAngles":{"abstract":[{"text":"Tilt angles of the device.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceTiltAngles"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TiltAngles","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deviceTiltAngles"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetection\/devicetiltangles","title":"deviceTiltAngles","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/deviceTiltAngles"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","title":"FaceAutoCaptureFrameParameters","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected face."}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","title":"FaceAutoCaptureController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","role":"symbol"},"doc://com.innovatrics.dot.face.lite/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection/validatorIdentifiers":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection\/validatoridentifiers","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validatorIdentifiers"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"abstract":[{"text":"Validator identifiers for which the validation has failed.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/validatorIdentifiers","navigatorTitle":[{"text":"validatorIdentifiers","kind":"identifier"}],"title":"validatorIdentifiers","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureResult":{"navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"title":"FaceAutoCaptureResult","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"url":"\/documentation\/dotfacelite\/faceautocaptureresult","kind":"symbol","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTFLFaceAutoCaptureDetection","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/bgraRawImage","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/deviceTiltAngles","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/face","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/validatorIdentifiers"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)"]}]},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"],"title":"Face auto capture process"}]},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"value":[{"text":"DOTDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/fragments"},{"value":"DOTFLMagnifEyeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1face\/title","op":"replace","value":"face"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1face\/fragments","value":[{"text":"face","kind":"identifier"}]},{"op":"replace","value":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection","op":"replace"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1bgraRawImage\/title","value":"bgraRawImage","op":"replace"},{"value":[{"kind":"identifier","text":"bgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1bgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1deviceTiltAngles\/title","value":"deviceTiltAngles","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1deviceTiltAngles\/fragments","op":"replace","value":[{"kind":"identifier","text":"deviceTiltAngles"}]},{"value":"DOTFLFaceAutoCaptureFrameParameters","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"value":"DOTFLFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1validatorIdentifiers\/title","value":"validatorIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1validatorIdentifiers\/fragments","value":[{"kind":"identifier","text":"validatorIdentifiers"}]},{"op":"replace","value":"DOTFLFaceAutoCaptureResult","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments"}]}]}