{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/corners"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/corners"]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"class","title":"Corners","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTCorners"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCorners) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomRight","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/points","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topRight"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/isEqual(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/mirrored()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/rebased(parentRectangle:)"]},{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/from(rectangle:)"]}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Corners/topRight":{"role":"symbol","title":"topRight","url":"\/documentation\/dotfacecore\/corners\/topright","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topRight","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"navigatorTitle":[{"text":"topRight","kind":"identifier"}],"abstract":[{"text":"Top right corner point.","type":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/points":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/points","navigatorTitle":[{"kind":"identifier","text":"points"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/corners\/points","abstract":[],"title":"points"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/hash":{"role":"symbol","url":"\/documentation\/dotfacecore\/corners\/hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/hash","kind":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","abstract":[]},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/from(rectangle:)":{"role":"symbol","title":"from(rectangle:)","url":"\/documentation\/dotfacecore\/corners\/from(rectangle:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/from(rectangle:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"text":"rectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}],"abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/topLeft":{"role":"symbol","title":"topLeft","url":"\/documentation\/dotfacecore\/corners\/topleft","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topLeft","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"topLeft","kind":"identifier"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"text":"topLeft","kind":"identifier"}],"abstract":[{"text":"Top left corner point.","type":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/mirrored()":{"role":"symbol","kind":"symbol","title":"mirrored()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/mirrored()","url":"\/documentation\/dotfacecore\/corners\/mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Corners/rebased(parentRectangle:)":{"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/rebased(parentRectangle:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/corners\/rebased(parentrectangle:)","title":"rebased(parentRectangle:)","abstract":[]},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/bottomLeft":{"navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"title":"bottomLeft","url":"\/documentation\/dotfacecore\/corners\/bottomleft","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomLeft","abstract":[{"text":"Bottom left corner point.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/Corners/description":{"role":"symbol","title":"description","url":"\/documentation\/dotfacecore\/corners\/description","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"role":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","url":"\/documentation\/dotfacecore\/corners\/init(topleft:topright:bottomright:bottomleft:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomRight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/bottomRight":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomRight","title":"bottomRight","type":"topic","url":"\/documentation\/dotfacecore\/corners\/bottomright","navigatorTitle":[{"text":"bottomRight","kind":"identifier"}],"abstract":[{"type":"text","text":"Bottom right corner point."}]},"doc://DotFaceCore/documentation/DotFaceCore/Corners/isEqual(_:)":{"url":"\/documentation\/dotfacecore\/corners\/isequal(_:)","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isEqual(_:)","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/isEqual(_:)","role":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/Corners":{"role":"symbol","url":"\/documentation\/dotfacecore\/corners","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","kind":"symbol","title":"Corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Four detected corners in an image."}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTCorners"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]},{"value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomRight","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/points","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topLeft","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/topRight"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/isEqual(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/mirrored()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/from(rectangle:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCorners","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1topRight\/title","value":"topRight"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1topRight\/fragments","value":[{"text":"topRight","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1points\/title","value":"points","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1points\/fragments","value":[{"text":"points","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1hash\/title","value":"hash"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1hash\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1from(rectangle:)\/title","value":"fromRectangle:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1from(rectangle:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1topLeft\/title","value":"topLeft"},{"value":[{"text":"topLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1topLeft\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1mirrored()\/title","value":"mirrored"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mirrored"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1mirrored()\/fragments","op":"replace"},{"op":"replace","value":"rebasedWithParentRectangle:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1rebased(parentRectangle:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1rebased(parentRectangle:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"bottomLeft","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomLeft\/title"},{"value":[{"text":"bottomLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomLeft\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1description\/title","op":"replace","value":"description"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1description\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomRight\/title","value":"bottomRight","op":"replace"},{"value":[{"text":"bottomRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomRight\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1isEqual(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/title","value":"DOTCorners"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}