{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate"]}],"abstract":[{"text":"Implement this delegate to handle the face auto capture events.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"title":"FaceAutoCaptureViewControllerDelegate","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:captured:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:processed:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillTransition(_:)"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFFaceAutoCaptureViewControllerDelegate) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewDidDisappear(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidDisappear(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidDisappear:"}],"title":"faceAutoCaptureViewControllerViewDidDisappear(_:)","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdiddisappear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceAutoCaptureViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewDidLoad(_:)":{"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidload(_:)","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidLoad:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"faceAutoCaptureViewControllerViewDidLoad","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLoad(_:)","kind":"symbol","abstract":[],"title":"faceAutoCaptureViewControllerViewDidLoad(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewDidAppear(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidAppear(_:)","kind":"symbol","required":true,"title":"faceAutoCaptureViewControllerViewDidAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidAppear:"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidappear(_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"text":")","kind":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewController(_:captured:)":{"type":"topic","title":"faceAutoCaptureViewController(_:captured:)","abstract":[{"type":"text","text":"Tells the delegate that the face was captured. This callback is called after the component has stopped."}],"kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"captured"},{"kind":"text","text":": "},{"text":"FaceAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewController:captured:"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:captured:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:captured:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewWillDisappear(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillDisappear(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillDisappear:"}],"title":"faceAutoCaptureViewControllerViewWillDisappear(_:)","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilldisappear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerNoCameraPermission(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerNoCameraPermission","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","kind":"typeIdentifier","text":"FaceAutoCaptureViewController"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"faceAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"kind":"symbol","title":"faceAutoCaptureViewControllerNoCameraPermission(_:)","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerNoCameraPermission(_:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollernocamerapermission(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewWillTransition(_:)":{"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwilltransition(_:)","abstract":[],"title":"faceAutoCaptureViewControllerViewWillTransition(_:)","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillTransition(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillTransition"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"text":"faceAutoCaptureViewControllerViewWillTransition:","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewWillAppear(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillAppear(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillAppear:"}],"title":"faceAutoCaptureViewControllerViewWillAppear(_:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewwillappear(_:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"text":")","kind":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"kind":"symbol","title":"FaceAutoCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidLayoutSubviews:"}],"title":"faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidlayoutsubviews(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceAutoCaptureViewControllerViewDidLayoutSubviews","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewController(_:processed:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:processed:)","kind":"symbol","required":true,"title":"faceAutoCaptureViewController(_:processed:)","navigatorTitle":[{"text":"faceAutoCaptureViewController:processed:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:processed:)","type":"topic","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"FaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"text":")","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"DOTFFaceAutoCaptureViewControllerDelegate","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:captured:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:processed:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewWillTransition(_:)"]}]},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidDisappear(_:)\/title","op":"replace","value":"faceAutoCaptureViewControllerViewDidDisappear:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidDisappear:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidLoad(_:)\/title","value":"faceAutoCaptureViewControllerViewDidLoad:"},{"value":[{"kind":"text","text":"- "},{"text":"faceAutoCaptureViewControllerViewDidLoad:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidLoad(_:)\/fragments"},{"value":"faceAutoCaptureViewControllerViewDidAppear:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidAppear(_:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidAppear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidAppear:"}]},{"op":"replace","value":"faceAutoCaptureViewController:captured:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:captured:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:captured:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewController:captured:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillDisappear(_:)\/title","value":"faceAutoCaptureViewControllerViewWillDisappear:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillDisappear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"faceAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}]},{"value":"faceAutoCaptureViewControllerNoCameraPermission:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerNoCameraPermission(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerNoCameraPermission(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"faceAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}]},{"value":"faceAutoCaptureViewControllerViewWillTransition:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillTransition(_:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillTransition(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewWillTransition:"}],"op":"replace"},{"value":"faceAutoCaptureViewControllerViewWillAppear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillAppear(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewWillAppear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"faceAutoCaptureViewControllerViewWillAppear:","kind":"identifier"}]},{"value":"DOTFFaceAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title"},{"value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments","op":"replace"},{"value":"DOTFFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"value":"faceAutoCaptureViewControllerViewDidLayoutSubviews:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidLayoutSubviews:"}]},{"value":"faceAutoCaptureViewController:processed:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:processed:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:processed:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"faceAutoCaptureViewController:processed:","kind":"identifier"}]}]}]}