{"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"cameraFacing","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC12cameraFacing0A6Camera0kJ0Ovp","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}],"symbolKind":"property"},"abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".back"},{"text":".","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/camerafacing"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/cameraFacing","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/cameraFacing":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/camerafacing","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/cameraFacing","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"code":".back","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","title":"cameraFacing","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/camerafacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"title":"PalmAutoCaptureViewController","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","type":"topic","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"title":"PalmAutoCaptureViewController.Configuration","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}