{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/cameraPreviewScaleType"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTCameraPreviewScaleType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"property","modules":[{"name":"DotPalmCore"}],"title":"cameraPreviewScaleType","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}],"role":"symbol","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC22cameraPreviewScaleTypeAA06CamerajkL0Ovp"},"abstract":[{"text":"Specify camera preview scale type. Default is ","type":"text"},{"type":"codeVoice","code":".fit"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/camerapreviewscaletype"]}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/CameraPreviewScaleType":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"title":"CameraPreviewScaleType"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"type":"topic","title":"PalmAutoCaptureViewController.Configuration","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","kind":"symbol","title":"PalmAutoCaptureViewController","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/cameraPreviewScaleType":{"type":"topic","title":"cameraPreviewScaleType","abstract":[{"type":"text","text":"Specify camera preview scale type. Default is "},{"type":"codeVoice","code":".fit"},{"type":"text","text":"."}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/camerapreviewscaletype","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/cameraPreviewScaleType","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTCameraPreviewScaleType"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"value":"DOTPPalmAutoCaptureViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}