{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC11descriptionSSvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"description"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/description"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/description"},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/description","kind":"symbol","title":"description","abstract":[],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/description"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"title":"PalmAutoCaptureViewController","role":"symbol","abstract":[{"type":"text","text":"UI Palm Auto Capture component."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"abstract":[{"type":"text","text":"Configuration options for the UI Palm Auto Capture component."}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","type":"topic","title":"PalmAutoCaptureViewController.Configuration","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTPPalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle"}]}]}