{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","text":"QualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"text":" = QualityAttributeThresholdPresets.standard.build(), ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" = PalmAutoCaptureController.Configuration.Defaults\n                .minValidFramesInRowToStartCandidateSelection, ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" = PalmAutoCaptureController.Configuration.Defaults.candidateSelectionDurationMillis, ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isVideoCaptureEnabled, "},{"text":"cameraFacing","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","kind":"typeIdentifier"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"text":" = Defaults.cameraPreviewScaleType, ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = Defaults.isCameraPreviewVisible, ","kind":"text"},{"kind":"externalParam","text":"placeholderType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","kind":"typeIdentifier","text":"PlaceholderType"},{"kind":"text","text":" = Defaults.placeholderType) "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","title":"init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:)","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds44minValidFramesInRowToStartCandidateSelection09candidateV14DurationMillis23isDetectionLayerVisible0Z12TorchEnabled0z5VideoE7Enabled12cameraFacing22cameraPreviewScaleType0Z20CameraPreviewVisible15placeholderTypeAESSSg_AE07QualitylM0CS2iS3b0A6Camera12CameraFacingOAT22CameraPreviewScaleTypeOSbAA15PlaceholderTypeOtKcfc","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placeholderType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisib-9medy"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"title":"PalmAutoCaptureViewController.Configuration","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"title":"PalmAutoCaptureViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","kind":"symbol","abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"text":"QualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"text":", ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placeholderType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","text":"PlaceholderType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:)","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisib-9medy","abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"kind":"symbol","role":"symbol","title":"init(sessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:placeholderType:)"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","role":"symbol","title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"QualityAttributeThresholds","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/camerafacing","role":"symbol","title":"CameraFacing"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"text":"Represents the type of placeholder used in palm auto-capture UI.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","url":"\/documentation\/dotpalmcore\/placeholdertype","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlaceholderType","kind":"identifier"}],"title":"PlaceholderType","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"value":"DOTPPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTPPlaceholderType"}]}]}]}