{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"text":"QualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"},{"kind":"text","text":" = QualityAttributeThresholdPresets.standard.build(), "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"isTorchEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = Defaults.isVideoCaptureEnabled, ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType, "},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = Defaults.isCameraPreviewVisible)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class"]]},"sections":[],"metadata":{"roleHeading":"Initializer","title":"init(sessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isCameraPreviewVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC12sessionToken26qualityAttributeThresholds23isDetectionLayerVisible0N12TorchEnabled0n5VideoeS012cameraFacing0U16PreviewScaleType0n6CamerawQ0AESSSg_AE07QualitylM0CS3b0aZ00zV0OAQ0zwxY0OSbtcfc","modules":[{"name":"DotPalmCore"}],"symbolKind":"init","role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/init(sessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/init(sessiontoken:qualityattributethresholds:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"kind":"text","text":": "},{"text":"QualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"text":", ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"type":"topic","title":"init(sessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/init(sessionToken:qualityAttributeThresholds:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","type":"topic","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"title":"PalmAutoCaptureViewController.Configuration","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/camerafacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.11.0","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"title":"PalmAutoCaptureViewController","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"kind":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"title":"CameraPreviewScaleType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/camerapreviewscaletype","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","type":"topic","abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}