{"metadata":{"modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"roleHeading":"Instance Property","title":"configuration","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController(py)configuration"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/configuration-swift.property","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.property"]}],"abstract":[{"type":"text","text":"Current configuration."}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration options for the UI Palm Auto Capture component.","type":"text"}],"kind":"symbol","title":"PalmAutoCaptureViewController.Configuration","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"type":"topic","kind":"symbol","title":"PalmAutoCaptureViewController","abstract":[{"text":"UI Palm Auto Capture component.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","abstract":[{"text":"Configuration options for the UI Palm Auto Capture component.","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureConfiguration"}],"type":"topic","title":"DOTPPalmAutoCaptureConfiguration","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/configuration-swift.property":{"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"}],"abstract":[{"text":"Current configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/configuration-swift.property","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.property","title":"configuration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotPalmCore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"configuration","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"configuration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","text":"DOTPPalmAutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPPalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"configuration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1configuration-swift.property\/title","op":"replace"},{"value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1configuration-swift.property\/fragments","op":"replace"}]}]}