{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewDidLoad()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewdidload()"]},{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"viewDidLoad()","modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController(im)viewDidLoad","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/viewDidLoad()":{"abstract":[],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewdidload()","kind":"symbol","type":"topic","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewDidLoad()"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","title":"PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewDidLoad()\/title","value":"viewDidLoad"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"value":"DOTPPalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"}]}]}