{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"title":"viewWillDisappear(_:)","roleHeading":"Instance Method","externalID":"c:@CM@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController(im)viewWillDisappear:","extendedModule":"DotPalmCore","role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewwilldisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewwilldisappear(_:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewWillDisappear(_:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","title":"DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"title":"PalmAutoCaptureViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureViewController","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/viewWillDisappear(_:)":{"abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewwilldisappear(_:)","role":"symbol","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"title":"viewWillDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewWillDisappear(_:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"viewWillDisappear:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewWillDisappear:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}