{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(cgImage:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}]}],"kind":"declarations"},{"parameters":[{"name":"cgImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/imagefactory\/createbgrrawimage(cgimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/imagefactory\/createbgrrawimage(cgimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgrRawImageWithCgImage:","roleHeading":"Type Method","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"symbolKind":"method","navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"role":"symbol","title":"createBgrRawImage(cgImage:)"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory":{"url":"\/documentation\/dotfacelite\/imagefactory","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"kind":"symbol","title":"ImageFactory","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" from iOS native image types.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgrRawImage(cgImage:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imagefactory\/createbgrrawimage(cgimage:)","title":"createBgrRawImage(cgImage:)"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfacelite\/image","title":"Image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createBgrRawImageWithCgImage:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","kind":"typeIdentifier","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImageRef"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgrRawImage(cgImage:)\/title","value":"createBgrRawImageWithCgImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"}]}]}