{"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init(threshold:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"threshold"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotDocument"}],"symbolKind":"init","title":"init(threshold:)","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooLowValidator(im)initWithThreshold:error:","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator"]]},"variants":[{"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/brightnesstoolowvalidator\/init(threshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator/init(threshold:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator\/init(threshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"threshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol","url":"\/documentation\/dotdocument\/brightnesstoolowvalidator\/init(threshold:)","title":"init(threshold:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.3.2"}],"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator","title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithThreshold:error:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithThreshold:"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"threshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"initWithThreshold:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1init(threshold:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithThreshold:error:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator~1init(threshold:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","op":"replace","value":"DOTDBrightnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}