{"variants":[{"paths":["\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:istorchenabled:isvideocaptureenabled:camerafacing:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:query:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","title":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(im)initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:"},"abstract":[{"text":"Create the eye gaze liveness configuration.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTIntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","text":"DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transitionDurationMillis:"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"text":"transitionDurationMillis","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transitionType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessTransitionType","text":"DOTFEyeGazeLivenessTransitionType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"transitionType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"corners:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DOTFWrappedEyeGazeLivenessCorner *>"},{"text":" *) ","kind":"text"},{"text":"corners","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minValidSamplesCount:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"minValidSamplesCount","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"objectImage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"objectImage","kind":"internalParam"},{"kind":"text","text":" "},{"text":"objectImageSize:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"objectImageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"query:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"typeIdentifier","text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"kind":"text","text":" *) "},{"text":"query","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessTransitionType":{"url":"\/documentation\/dotfacecore\/dotfeyegazelivenesstransitiontype","abstract":[{"text":"Eye gaze liveness available corner transition types.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","fragments":[{"text":"DOTFEyeGazeLivenessTransitionType","kind":"identifier"}],"title":"DOTFEyeGazeLivenessTransitionType","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"title":"FaceDetectionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.17.0","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","title":"CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"url":"\/documentation\/dotfacecore\/camerafacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:"}],"abstract":[{"text":"Create the eye gaze liveness configuration.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","kind":"identifier"}],"title":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:istorchenabled:isvideocaptureenabled:camerafacing:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:query:error:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"role":"symbol","fragments":[{"text":"DOTFEyeGazeLivenessConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","title":"DOTFEyeGazeLivenessConfiguration","abstract":[{"type":"text","text":"Configuration options for the eye gaze liveness process."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","title":"IntervalDouble","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"FaceDetectionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}]}]}