{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCommon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","text":"DOTCommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","text":"DOTCameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","text":"DOTFFaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLibraryComponent"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDurationMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"transitionDurationMillis"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","text":"DOTFEyeGazeLivenessTransitionType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessTransitionType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"transitionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"corners:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<DOTFWrappedEyeGazeLivenessCorner *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"corners"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minValidSamplesCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"objectImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"objectImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"objectImageSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"objectImageSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(im)initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:","navigatorTitle":[{"text":"initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:error:"]}],"abstract":[{"text":"Create the eye gaze liveness configuration.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.1.0"}],"title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","title":"CommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/commonconfiguration","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","url":"\/documentation\/dotfacecore\/cameraconfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"role":"symbol","title":"CameraConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","role":"symbol","abstract":[{"text":"Configuration options for the UI Eye Gaze Liveness component.","type":"text"}],"title":"DOTFEyeGazeLivenessConfiguration","fragments":[{"text":"DOTFEyeGazeLivenessConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessTransitionType":{"fragments":[{"text":"DOTFEyeGazeLivenessTransitionType","kind":"identifier"}],"type":"topic","title":"DOTFEyeGazeLivenessTransitionType","url":"\/documentation\/dotfacecore\/dotfeyegazelivenesstransitiontype","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","kind":"symbol","abstract":[{"type":"text","text":"Eye gaze liveness available corner transition types."}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","kind":"symbol","title":"FaceLibraryComponentConfiguration","role":"symbol","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"abstract":[{"text":"Configuration for face library components.","type":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration/initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:","title":"initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:"}],"abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:error:","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:camera:faceLibraryComponent:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:error:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle"}]}]}