{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:query:error:"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration"]]},"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"DotFaceCore"}],"title":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(im)initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"kind":"text","text":" "},{"text":"faceSizeRatioInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier","text":"DOTIntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":" *) "},{"text":"faceSizeRatioInterval","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transitionDurationMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"transitionDurationMillis","kind":"internalParam"},{"kind":"text","text":" "},{"text":"transitionType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessTransitionType","text":"DOTFEyeGazeLivenessTransitionType"},{"kind":"text","text":") "},{"text":"transitionType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"corners:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTFWrappedEyeGazeLivenessCorner *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"corners"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minValidSamplesCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"minValidSamplesCount"},{"kind":"text","text":" "},{"text":"objectImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"objectImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"objectImageSize:"},{"kind":"text","text":"("},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"objectImageSize","kind":"internalParam"},{"kind":"text","text":" "},{"text":"query:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"FaceDetectionQuery","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"query"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"title":"IntervalDouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","type":"topic","url":"\/documentation\/dotfacecore\/intervaldouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessTransitionType":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotfeyegazelivenesstransitiontype","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","abstract":[{"type":"text","text":"Eye gaze liveness available corner transition types."}],"fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessTransitionType"}],"title":"DOTFEyeGazeLivenessTransitionType"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"url":"\/documentation\/dotfacecore\/facedetectionquery","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"title":"FaceDetectionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionQuery"}],"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"title":"CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacecore\/camerafacing","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:":{"kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:"}],"url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:minvalidsamplescount:objectimage:objectimagesize:query:error:","abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"title":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:minValidSamplesCount:objectImage:objectImageSize:query:error:","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"role":"symbol","fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessConfiguration"}],"title":"DOTFEyeGazeLivenessConfiguration","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","abstract":[{"text":"Configuration options for the eye gaze liveness process.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"value":"FaceDetectionQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title"},{"value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments"}]}]}