{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateYaw"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"evaluateYaw","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Yaw evaluation flag.","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"evaluateYaw","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Instance Property","title":"evaluateYaw","externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery(py)evaluateYaw","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"evaluateYaw"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/headposequery\/evaluateyaw"]},{"paths":["\/documentation\/dotfacecore\/headposequery\/evaluateyaw"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseQuery/evaluateYaw":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateYaw"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluateYaw","url":"\/documentation\/dotfacecore\/headposequery\/evaluateyaw","abstract":[{"type":"text","text":"Yaw evaluation flag."}],"kind":"symbol","title":"evaluateYaw","type":"topic","navigatorTitle":[{"kind":"identifier","text":"evaluateYaw"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseQuery":{"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"HeadPoseQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headposequery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","role":"symbol","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"title":"HeadPoseQuery","abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"evaluateYaw","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"evaluateYaw","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateYaw"}]}],"kind":"declarations"}},{"value":"evaluateYaw","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluateYaw\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluateYaw\/fragments","value":[{"kind":"identifier","text":"evaluateYaw"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace","value":"DOTFHeadPoseQuery"},{"value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"}]}]}