{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(image:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"text":") -> ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"Input image as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"type":"paragraph"}]}]},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/cgimagefactory\/create(image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cgimagefactory\/create(image:)"]}],"metadata":{"roleHeading":"Type Method","navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"}],"symbolKind":"method","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithImage:","title":"create(image:)"},"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory/create(image:)":{"navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"title":"create(image:)","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory\/create(image:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}],"url":"\/documentation\/dotfacecore\/cgimagefactory\/create(image:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfacecore\/image","abstract":[],"title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory":{"url":"\/documentation\/dotfacecore\/cgimagefactory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","title":"CGImageFactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"createWithImage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithImage:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"CGImageRef","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") "},{"kind":"identifier","text":"createWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createWithImage:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(image:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory~1create(image:)\/fragments"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}