{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"day","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/day"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"day"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate(py)day","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"day"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzdate\/day"]},{"paths":["\/documentation\/dotdocument\/mrzdate\/day"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"url":"\/documentation\/dotdocument\/mrzdate","kind":"symbol","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"title":"MrzDate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzDate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDate"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzDate/day":{"abstract":[],"url":"\/documentation\/dotdocument\/mrzdate\/day","navigatorTitle":[{"kind":"identifier","text":"day"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"day","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/day","title":"day"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"day"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"day","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"day"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTMrzDate","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","value":[{"text":"DOTMrzDate","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1day\/title","op":"replace","value":"day"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1day\/fragments","op":"replace","value":[{"text":"day","kind":"identifier"}]}]}]}