{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate"]]},"variants":[{"paths":["\/documentation\/dotdocument\/mrzdate\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzdate\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"description","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate(py)description","modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/description","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","url":"\/documentation\/dotdocument\/mrzdate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"type":"topic","title":"MrzDate","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzDate/description":{"type":"topic","url":"\/documentation\/dotdocument\/mrzdate\/description","title":"description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/description","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","op":"replace","value":"DOTMrzDate"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzDate"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTMrzDate"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}