{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/mrzdate\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzdate\/hash"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate"]]},"metadata":{"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate(py)hash","symbolKind":"property","modules":[{"name":"DotDocument"}],"role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/hash","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/MrzDate/hash":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzdate\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate\/hash","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzDate":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzdate","kind":"symbol","title":"MrzDate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1hash\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","value":"DOTMrzDate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","value":[{"text":"DOTMrzDate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}