{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/expressionquery\/evaluatemouth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/expressionquery\/evaluatemouth"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"evaluateMouth","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"evaluateMouth"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery(py)evaluateMouth","title":"evaluateMouth","symbolKind":"property","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Mouth evaluation flag."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"evaluateMouth","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/evaluateMouth"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"url":"\/documentation\/dotfacecore\/expressionquery","title":"ExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","role":"symbol","navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExpressionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.12.1"}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery/evaluateMouth":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/evaluateMouth","navigatorTitle":[{"text":"evaluateMouth","kind":"identifier"}],"abstract":[{"type":"text","text":"Mouth evaluation flag."}],"type":"topic","url":"\/documentation\/dotfacecore\/expressionquery\/evaluatemouth","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluateMouth"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"evaluateMouth"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"evaluateMouth","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"evaluateMouth"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"evaluateMouth","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1evaluateMouth\/title","value":"evaluateMouth"},{"value":[{"kind":"identifier","text":"evaluateMouth"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1evaluateMouth\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}