{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning"]]},"abstract":[{"type":"text","text":"Detection information. If the process has just started and no camera image has been processed yet, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/detection"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","text":"DOTFLFaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"kind":"text","text":";"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/detection"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"detection"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiStateRunning(py)detection","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"detection","fragments":[{"kind":"identifier","text":"detection"}]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning/detection":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/detection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/detection","role":"symbol","title":"detection","type":"topic","abstract":[{"type":"text","text":"Detection information. If the process has just started and no camera image has been processed yet, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"fragments":[{"kind":"identifier","text":"detection"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"type":"topic","title":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection","abstract":[{"type":"text","text":"The result of the image processing during the face auto capture process."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"DOTFLFaceAutoCaptureUiStateRunning","kind":"identifier"}],"title":"DOTFLFaceAutoCaptureUiStateRunning"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTFLFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}