{"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration(im)init","symbolKind":"method","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Method","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/dotpalmdetectionmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration\/init","interfaceLanguage":"occ"},"references":{"doc://DotNfc/documentation/DotNfc/DotPalmDetectionModuleConfiguration/init":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/dotnfc\/dotpalmdetectionmoduleconfiguration\/init","role":"symbol","abstract":[],"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration\/init"},"doc://DotNfc/documentation/DotNfc/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotnfc\/dotpalmdetectionmoduleconfiguration","kind":"symbol","abstract":[{"text":"Palm detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration","role":"symbol","navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"title":"DotPalmDetectionModuleConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}