{"abstract":[{"type":"text","text":"Initialize with default threshold."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Initializer","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceNotDetectedValidator(im)init","symbolKind":"init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator\/init()"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"title":"FaceAutoCaptureController","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init()","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"navigatorTitle":[{"text":"FaceNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceNotDetectedValidator"}],"abstract":[{"type":"text","text":"Validates confidence of the detected face."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","title":"FaceNotDetectedValidator"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","type":"topic","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.0"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"init","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"replace","value":"DOTFLFaceNotDetectedValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}