{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bytesPointerPacked","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":">","kind":"text"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)bytesPointerPacked","navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}],"role":"symbol","title":"bytesPointerPacked"},"variants":[{"paths":["\/documentation\/dotdocument\/bgrarawimage\/bytespointerpacked"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrarawimage\/bytespointerpacked"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointerPacked","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage\/bytesPointerPacked"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"]]},"references":{"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","title":"BgraRawImage","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"title":"DocumentDetector","url":"\/documentation\/dotdocument\/documentdetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://DotDocument/documentation/DotDocument/BgraRawImage/bytesPointerPacked":{"navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}],"title":"bytesPointerPacked","role":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/bgrarawimage\/bytespointerpacked","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointerPacked"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"kind":"text","text":">"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage\/bytesPointerPacked"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"bytesPointerPacked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bytesPointerPacked"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@uint32_t","kind":"typeIdentifier","text":"uint32_t"},{"kind":"text","text":" * "},{"text":"bytesPointerPacked","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage~1bytesPointerPacked\/title","value":"bytesPointerPacked"},{"value":[{"text":"bytesPointerPacked","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage~1bytesPointerPacked\/fragments"}]}]}