{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:position:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzStringPosition","kind":"typeIdentifier","text":"MrzStringPosition"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/mrzelement\/init(value:position:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzelement\/init(value:position:)"]}],"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"position","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzStringPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:position:"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@DotNfc@objc(cs)DOTMrzElement(im)initWithValue:position:","title":"init(value:position:)"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzStringPosition":{"navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"type":"topic","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"title":"MrzStringPosition","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzStringPosition","url":"\/documentation\/dotnfc\/mrzstringposition","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzStringPosition","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"url":"\/documentation\/dotnfc\/mrzelement","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"title":"MrzElement","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement/init(value:position:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithValue:position:"}],"role":"symbol","title":"init(value:position:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement\/init(value:position:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"text":"MrzStringPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition"},{"text":")","kind":"text"}],"url":"\/documentation\/dotnfc\/mrzelement\/init(value:position:)","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.0.0"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithValue:position:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:position:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"position:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzStringPosition","text":"DOTMrzStringPosition","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"position","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzStringPosition\/title","op":"replace","value":"DOTMrzStringPosition"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzStringPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"value":"initWithValue:position:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1init(value:position:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:position:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement~1init(value:position:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}