{"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration\/initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration(im)initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:","kind":"identifier"}],"title":"initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration\/initwithcommon:authoritycertificatesurl:pollingoption:_debuginfoenabled:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"DOTCommonConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration"},{"kind":"text","text":" *) "},{"text":"common","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"authorityCertificatesUrl:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"authorityCertificatesUrl","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pollingOption:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNNfcTravelDocumentReaderConfigurationPollingOption","text":"DOTNNfcTravelDocumentReaderConfigurationPollingOption","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfigurationPollingOption"},{"text":") ","kind":"text"},{"text":"pollingOption","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"_debugInfoEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"_debugInfoEnabled","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration"]]},"references":{"doc://DotNfc/documentation/DotNfc/CommonConfiguration":{"title":"CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/commonconfiguration","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfigurationPollingOption":{"fragments":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderConfigurationPollingOption"}],"title":"DOTNNfcTravelDocumentReaderConfigurationPollingOption","abstract":[{"text":"Polling option specifies which travel documents can be detected.","type":"text"}],"url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfigurationpollingoption","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfigurationPollingOption","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfiguration/initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:":{"abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:"}],"url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration\/initwithcommon:authoritycertificatesurl:pollingoption:_debuginfoenabled:","title":"initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration\/initWithCommon:authorityCertificatesUrl:pollingOption:_debugInfoEnabled:","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfiguration":{"title":"DOTNNfcTravelDocumentReaderConfiguration","abstract":[{"text":"Configuration options for ","type":"text"},{"text":"NfcTravelDocumentReader","type":"text"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration","fragments":[{"text":"DOTNNfcTravelDocumentReaderConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/title","op":"replace","value":"DOTCommonConfiguration"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/navigatorTitle","op":"replace"}]}]}