{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/commonconfiguration\/init(sessiontoken:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/commonconfiguration\/init(sessiontoken:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/init(sessionToken:)"},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration(im)initWithSessionToken:","symbolKind":"init","title":"init(sessionToken:)","navigatorTitle":[{"text":"initWithSessionToken:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/CommonConfiguration":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration","title":"CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/commonconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/CommonConfiguration/init(sessionToken:)":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/init(sessionToken:)","url":"\/documentation\/dotnfc\/commonconfiguration\/init(sessiontoken:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:"}],"title":"init(sessionToken:)","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithSessionToken:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithSessionToken:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1init(sessionToken:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1init(sessionToken:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}