{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/localizedDescription"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/intervalfloat\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Error.localizedDescription"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotPalmCore","relatedModules":["Swift"]}],"title":"localizedDescription","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"extendedModule":"Swift","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"8.0","deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"8.0","deprecated":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"8.0"},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"10.10","deprecated":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"9.0"},{"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"2.0","unavailable":false}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error/localizedDescription":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotpalmcore\/intervalfloat\/error\/localizeddescription","abstract":[],"kind":"symbol","title":"localizedDescription","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/localizedDescription","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat":{"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","kind":"symbol","title":"IntervalFloat","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/intervalfloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error","kind":"symbol","title":"IntervalFloat.Error","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/intervalfloat\/error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/navigatorTitle","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}