{"variants":[{"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBarcode:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"barcode"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcode:"}],"navigatorTitle":[{"text":"initWithBarcode:","kind":"identifier"}],"title":"initWithBarcode:","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(im)initWithBarcode:","roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules\/initWithBarcode:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfigurationModules/initWithBarcode:":{"abstract":[],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBarcode:"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:","navigatorTitle":[{"kind":"identifier","text":"initWithBarcode:"}],"title":"initWithBarcode:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules\/initWithBarcode:","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentBarcodeModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotdocumentbarcodemoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"kind":"symbol","title":"DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfigurationModules":{"abstract":[{"type":"text","text":"Document library module configuration."}],"kind":"symbol","fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules","title":"DotDocumentLibraryConfigurationModules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}