{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"Configuration","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC"},{"text":" = .init(), ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"Style","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Style-swift.class","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier"},{"kind":"text","text":" = .init())"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the palm auto capture process."}]}],"name":"configuration"},{"name":"style","content":[{"type":"paragraph","inlineContent":[{"text":"Customize user interface.","type":"text"}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"New instance of "},{"type":"codeVoice","code":"PalmAutoCaptureViewController"},{"type":"text","text":"."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/init(configuration:style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/init(configuration:style:)"]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"init(configuration:style:)","symbolKind":"init","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController(im)initWithConfiguration:style:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Configuration","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC5StyleC","text":"Style"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol"},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/init(configuration:style:)"},"abstract":[{"text":"Create new ","type":"text"},{"code":"PalmAutoCaptureViewController","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"PalmAutoCaptureViewController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","type":"topic","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/init(configuration:style:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/init(configuration:style:)","abstract":[{"type":"text","text":"Create new "},{"code":"PalmAutoCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/init(configuration:style:)","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"title":"init(configuration:style:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Style","preciseIdentifier":"s:11DotPalmCore0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","title":"PalmAutoCaptureViewController","role":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"title":"DOTPPalmAutoCaptureConfiguration","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureConfiguration"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DOTPPalmAutoCaptureStyle":{"abstract":[{"text":"Customization options for the palm auto capture user interface.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocapturestyle","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureStyle","kind":"symbol","title":"DOTPPalmAutoCaptureStyle","fragments":[{"text":"DOTPPalmAutoCaptureStyle","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/Style-swift.class":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/style-swift.class","title":"PalmAutoCaptureViewController.Style","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Style"}],"abstract":[{"text":"Customization options for the palm auto capture user interface.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Style-swift.class","type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithConfiguration:style:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:style:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration","text":"DOTPPalmAutoCaptureConfiguration","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style:"},{"kind":"text","text":"("},{"text":"DOTPPalmAutoCaptureStyle","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureStyle","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureStyle","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"initWithConfiguration:style:","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1init(configuration:style:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1init(configuration:style:)\/fragments"},{"op":"replace","value":"DOTPPalmAutoCaptureViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}