{"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration(im)init","symbolKind":"method","roleHeading":"Instance Method","title":"init","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration\/init"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfingersdetectionmoduleconfiguration\/init"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration","title":"DotFingersDetectionModuleConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersDetectionModuleConfiguration/init":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersdetectionmoduleconfiguration\/init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}