{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/dependencyidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/dependencyidentifiers"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator"]]},"kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"dependencyIdentifiers","externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeOutsideOfDocumentValidator(py)dependencyIdentifiers"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator/dependencyIdentifiers":{"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator\/dependencyIdentifiers","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"title":"dependencyIdentifiers","url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator\/dependencyidentifiers","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeOutsideOfDocumentValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"BarcodeOutsideOfDocumentValidator","navigatorTitle":[{"text":"BarcodeOutsideOfDocumentValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator","abstract":[{"text":"Validate if barcode is inside detected document bounds.","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"dependencyIdentifiers","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1dependencyIdentifiers\/title"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator~1dependencyIdentifiers\/fragments"},{"value":"DOTDBarcodeOutsideOfDocumentValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/title"},{"value":[{"text":"DOTDBarcodeOutsideOfDocumentValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/fragments"},{"value":[{"text":"DOTDBarcodeOutsideOfDocumentValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/navigatorTitle"}]}]}