{"variants":[{"paths":["\/documentation\/dotfacecore\/templatematcher\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/templatematcher\/init()"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/init()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFTemplateMatcher(im)init"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"title":"TemplateMatcher","url":"\/documentation\/dotfacecore\/templatematcher","abstract":[{"type":"text","text":"Stateless class which can match templates."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplateMatcher"}],"navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 8.15.2","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/init()":{"abstract":[],"url":"\/documentation\/dotfacecore\/templatematcher\/init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"init","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTFTemplateMatcher","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher~1init()\/fragments"}]}]}