{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Back facing camera."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/camerafacing\/back"]},{"paths":["\/documentation\/dotdocument\/camerafacing\/back"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/back"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Case","role":"symbol","externalID":"c:@M@DotCamera@E@DOTCameraFacing@DOTCameraFacingBack","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"title":"CameraFacing.back","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingBack"}]},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/CameraFacing":{"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"type":"topic","role":"symbol","title":"CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","url":"\/documentation\/dotdocument\/camerafacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/CameraFacing/back":{"abstract":[{"text":"Back facing camera.","type":"text"}],"type":"topic","role":"symbol","title":"CameraFacing.back","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/back","url":"\/documentation\/dotdocument\/camerafacing\/back","navigatorTitle":[{"text":"DOTCameraFacingBack","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.13.0","type":"text"}],"url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraFacingBack"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1back\/title","value":"DOTCameraFacingBack","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1back\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}