{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/Equatable-Implementations"},"variants":[{"paths":["\/documentation\/dotdocument\/camerafacing\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing"]]},"sections":[],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"DotDocument"}],"roleHeading":"API Collection"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/!=(_:_:)"],"anchor":"Operators","title":"Operators","generated":true}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/CameraFacing/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/!=(_:_:)","role":"symbol","type":"topic","title":"!=(_:_:)","abstract":[],"url":"\/documentation\/dotdocument\/camerafacing\/!=(_:_:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing","type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","url":"\/documentation\/dotdocument\/camerafacing","role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/navigatorTitle","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}