{"metadata":{"role":"symbol","navigatorTitle":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"front","kind":"identifier"}],"externalID":"c:@M@DotCamera@E@DOTCameraFacing@DOTCameraFacingFront","title":"CameraFacing.front","symbolKind":"case"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/front","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing"]]},"abstract":[{"text":"Front facing camera.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/camerafacing\/front"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/camerafacing\/front"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"url":"\/documentation\/dotdocument\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","title":"CameraFacing"},"doc://DotDocument/documentation/DotDocument/CameraFacing/front":{"url":"\/documentation\/dotdocument\/camerafacing\/front","role":"symbol","abstract":[{"text":"Front facing camera.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/front","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"front","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"kind":"symbol","title":"CameraFacing.front"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTCameraFacingFront","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacingFront"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"value":"DOTCameraFacingFront","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1front\/title"},{"value":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing~1front\/fragments"}]}]}