{"metadata":{"navigatorTitle":[{"text":"palmAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiStateUpdated"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiState","text":"PalmAutoCaptureUiState"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"role":"symbol","externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate(im)palmAutoCaptureViewController:uiStateUpdated:","symbolKind":"method","title":"palmAutoCaptureViewController(_:uiStateUpdated:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"palmAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","text":"BasePalmAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiStateUpdated"},{"kind":"text","text":" "},{"kind":"internalParam","text":"uiState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiState","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","text":"PalmAutoCaptureUiState"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:uiStateUpdated:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontroller(_:uistateupdated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontroller(_:uistateupdated:)"]}],"kind":"symbol","abstract":[{"text":"Tells the delegate that the UI state was updated.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","title":"BasePalmAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"kind":"symbol","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate/palmAutoCaptureViewController(_:uiStateUpdated:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"palmAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"uiStateUpdated"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureUiState","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Tells the delegate that the UI state was updated.","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate\/palmautocaptureviewcontroller(_:uistateupdated:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate\/palmAutoCaptureViewController(_:uiStateUpdated:)","title":"palmAutoCaptureViewController(_:uiStateUpdated:)","navigatorTitle":[{"text":"palmAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewControllerDelegate","kind":"identifier"}],"abstract":[{"text":"Implement this delegate to handle the palm auto capture events.","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontrollerdelegate","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewControllerDelegate","title":"PalmAutoCaptureViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewControllerDelegate"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","title":"PalmAutoCaptureUiState","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"kind":"symbol","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"palmAutoCaptureViewController:uiStateUpdated:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewController:uiStateUpdated:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"palmAutoCaptureViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","text":"DOTPBasePalmAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiStateUpdated:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiState","text":"DOTPPalmAutoCaptureUiState"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uiState"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace","value":"DOTPBasePalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewController(_:uiStateUpdated:)\/title","op":"replace","value":"palmAutoCaptureViewController:uiStateUpdated:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate~1palmAutoCaptureViewController(_:uiStateUpdated:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"palmAutoCaptureViewController:uiStateUpdated:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/title","op":"replace","value":"DOTPPalmAutoCaptureViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","op":"replace","value":"DOTPPalmAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}]}]}]}