{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator"]]},"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"metadata":{"title":"identifier","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceOutOfBoundsValidator(py)identifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/identifier","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/identifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceoutofboundsvalidator\/identifier"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","type":"topic","title":"FaceOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.2.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator/identifier":{"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator\/identifier","type":"topic","title":"identifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator\/identifier","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"identifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","value":"DOTFLFaceOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/navigatorTitle","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]}]}]}