{"metadata":{"symbolKind":"property","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"text":".","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"?","kind":"text"}],"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection(py)palm","title":"palm","navigatorTitle":[{"text":"palm","kind":"identifier"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","kind":"typeIdentifier","text":"PalmDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","kind":"typeIdentifier","text":"Palm"},{"kind":"text","text":"?"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection\/palm","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturedetection\/palm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturedetection\/palm"]}],"kind":"symbol","abstract":[{"text":"Detected palm, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the palm was not detected in the image.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","type":"topic","title":"PalmDetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"title":"DOTPPalmDetectorPalm","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","role":"symbol","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"kind":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Palm"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","title":"PalmDetector.Palm","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","abstract":[{"type":"text","text":"Result of the palm detection process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection/palm":{"url":"\/documentation\/dotpalmcore\/palmautocapturedetection\/palm","navigatorTitle":[{"kind":"identifier","text":"palm"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmDetector","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Palm"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection\/palm","type":"topic","title":"palm","kind":"symbol","abstract":[{"type":"text","text":"Detected palm, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the palm was not detected in the image."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"title":"PalmAutoCaptureDetection","url":"\/documentation\/dotpalmcore\/palmautocapturedetection","role":"symbol","abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"palm","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"palm"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","text":"DOTPPalmDetectorPalm","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm"},{"text":" * ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle","op":"replace"},{"value":"palm","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection~1palm\/title","op":"replace"},{"value":[{"kind":"identifier","text":"palm"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection~1palm\/fragments","op":"replace"},{"value":"DOTPPalmAutoCaptureDetection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle","op":"replace"}]}]}