{"abstract":[{"type":"text","text":"Tells the delegate that the face was captured."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewController(_:captured:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceSimpleCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"text":"FaceSimpleCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"captured","kind":"externalParam"},{"kind":"text","text":" "},{"text":"result","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceSimpleCaptureResult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureResult"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"platforms":[],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewController"},{"kind":"text","text":"("},{"text":"FaceSimpleCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captured"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureResult","text":"FaceSimpleCaptureResult"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceCore"}],"title":"faceSimpleCaptureViewController(_:captured:)","role":"symbol","externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate(im)faceSimpleCaptureViewController:captured:","navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewController:captured:"}],"roleHeading":"Instance Method","required":true},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontroller(_:captured:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontroller(_:captured:)"]}],"deprecationSummary":[{"inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}],"type":"paragraph"}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureResult":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","title":"FaceSimpleCaptureResult","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceSimpleCaptureResult","kind":"identifier"}],"abstract":[{"text":"The final result of the face simple capture process.","type":"text"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureresult"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewController(_:captured:)":{"type":"topic","abstract":[{"text":"Tells the delegate that the face was captured.","type":"text"}],"required":true,"role":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontroller(_:captured:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","text":"FaceSimpleCaptureViewController"},{"text":", ","kind":"text"},{"text":"captured","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureResult","text":"FaceSimpleCaptureResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"deprecated":true,"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewController(_:captured:)","title":"faceSimpleCaptureViewController(_:captured:)","navigatorTitle":[{"text":"faceSimpleCaptureViewController:captured:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewControllerDelegate","kind":"identifier"}],"deprecated":true,"navigatorTitle":[{"text":"FaceSimpleCaptureViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","abstract":[{"text":"Implement this delegate to handle the face simple capture events.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate","role":"symbol","title":"FaceSimpleCaptureViewControllerDelegate"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing face images."}],"role":"symbol","kind":"symbol","title":"FaceSimpleCaptureViewController","deprecated":true,"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"faceSimpleCaptureViewController:captured:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"faceSimpleCaptureViewController:captured:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewController:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","text":"DOTFFaceSimpleCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"captured:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureResult","text":"DOTFFaceSimpleCaptureResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"DOTFFaceSimpleCaptureResult","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureResult\/fragments","value":[{"text":"DOTFFaceSimpleCaptureResult","kind":"identifier"}],"op":"replace"},{"value":"faceSimpleCaptureViewController:captured:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewController(_:captured:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewController(_:captured:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"faceSimpleCaptureViewController:captured:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title","value":"DOTFFaceSimpleCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewControllerDelegate","kind":"identifier"}]},{"value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","op":"replace"}]}]}