{"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/invalidBounds"],"title":"Enumeration Cases"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/errorMessage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/internalError"],"title":"Instance Properties"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/DotSdkError-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/Error-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/LocalizedError-Implementations"],"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/intervaldouble\/error"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkError","doc:\/\/DotPalmCore\/10Foundation14LocalizedErrorP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/s5ErrorP","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/s8SendableP","doc:\/\/DotPalmCore\/s16SendableMetatypeP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"roleHeading":"Enumeration","modules":[{"name":"DotPalmCore"}],"externalID":"s:7DotCore14IntervalDoubleC5ErrorO","role":"symbol","symbolKind":"enum","title":"IntervalDouble.Error"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/Equatable-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/equatable-implementations","abstract":[]},"doc://DotPalmCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/invalidBounds":{"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidBounds"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/invalidBounds","type":"topic","title":"IntervalDouble.Error.invalidBounds","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/invalidbounds","kind":"symbol"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s8SendableP"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotpalmcore\/intervaldouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","title":"IntervalDouble","type":"topic","kind":"symbol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/DotSdkError-Implementations":{"url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/dotsdkerror-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/DotSdkError-Implementations","title":"DotSdkError Implementations","kind":"article","abstract":[]},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/LocalizedError-Implementations":{"abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/LocalizedError-Implementations","type":"topic","title":"LocalizedError Implementations","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/localizederror-implementations","kind":"article"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/errorMessage":{"title":"errorMessage","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/errormessage","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/errorMessage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/Error-Implementations":{"title":"Error Implementations","url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/error-implementations","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/Error-Implementations","kind":"article","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkError":{"title":"DotSdkError","url":"\/documentation\/dotpalmcore\/dotsdkerror","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkError","navigatorTitle":[{"kind":"identifier","text":"DotSdkError"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkError"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","identifier":"doc:\/\/DotPalmCore\/10Foundation14LocalizedErrorP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error":{"title":"IntervalDouble.Error","url":"\/documentation\/dotpalmcore\/intervaldouble\/error","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble/Error/internalError":{"url":"\/documentation\/dotpalmcore\/intervaldouble\/error\/internalerror","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble\/Error\/internalError","type":"topic","title":"internalError","kind":"symbol","abstract":[]},"doc://DotPalmCore/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/DotPalmCore\/s5ErrorP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/navigatorTitle","op":"replace"}]}]}