{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/placeholdertype\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"description","externalID":"s:14DotFingersCore15PlaceholderTypeO11descriptionSSvp","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"symbolKind":"property","modules":[{"name":"DotFingersCore"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/description","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/description":{"role":"symbol","title":"description","url":"\/documentation\/dotfingerscore\/placeholdertype\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/description","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType":{"type":"topic","kind":"symbol","title":"PlaceholderType","url":"\/documentation\/dotfingerscore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"}},"variantOverrides":[{"patch":[{"value":"DOTFGPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/title"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}