{"variants":[{"paths":["\/documentation\/dotfacecore\/pointint\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/pointint\/isequal(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DOTPointInt(im)isEqual:","title":"isEqual(_:)","role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/isEqual(_:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/PointInt":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt","url":"\/documentation\/dotfacecore\/pointint","navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"type":"topic","title":"PointInt","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/PointInt/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","title":"isEqual(_:)","role":"symbol","url":"\/documentation\/dotfacecore\/pointint\/isequal(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointInt\/isEqual(_:)","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"isEqual:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/title","value":"DOTPointInt"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/fragments","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt\/navigatorTitle","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointInt~1isEqual(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}