{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage\/size","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"size"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(py)size","symbolKind":"property","title":"size","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"_RawImage.size"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/bgrrawimage\/size"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/bgrrawimage\/size"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage/size":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage\/size","kind":"symbol","navigatorTitle":[{"text":"size","kind":"identifier"}],"abstract":[],"role":"symbol","title":"size","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"url":"\/documentation\/dotfacecore\/bgrrawimage\/size"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","url":"\/documentation\/dotfacecore\/bgrrawimage","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"role":"symbol","title":"BgrRawImage"},"doc://DotFaceCore/documentation/DotFaceCore/ImageSize":{"type":"topic","kind":"symbol","title":"ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"size"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"size"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"DOTImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageSize","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"size"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage~1size\/title","op":"replace","value":"size"},{"op":"replace","value":[{"kind":"identifier","text":"size"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage~1size\/fragments"},{"value":"DOTBgrRawImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}