{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/errorDescription"},"sections":[],"metadata":{"extendedModule":"DotCore","roleHeading":"Instance Property","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"errorDescription","role":"symbol","externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:11DotDocument0aB7LibraryC5ErrorO"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/error\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/LocalizedError-Implementations"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/Error/errorDescription":{"title":"errorDescription","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/error\/errordescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/errorDescription","kind":"symbol","type":"topic","abstract":[]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/Error/LocalizedError-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"LocalizedError Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/LocalizedError-Implementations","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/error\/localizederror-implementations"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/Error":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/error","title":"DotDocumentLibrary.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibrary","kind":"identifier"}],"title":"DotDocumentLibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","type":"topic","url":"\/documentation\/dotdocument\/dotdocumentlibrary","role":"symbol","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title","op":"replace","value":"DotDocumentLibrary"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibrary"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibrary","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}