{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/recoverySuggestion","interfaceLanguage":"swift"},"metadata":{"title":"recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","modules":[{"relatedModules":["Foundation"],"name":"DotDocument"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false,"introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false,"introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false,"introducedAt":"10.10"},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false,"introducedAt":"9.0"},{"unavailable":false,"deprecated":false,"name":"watchOS","beta":false,"introducedAt":"2.0"}],"externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:11DotDocument0aB7LibraryC5ErrorO","role":"symbol","roleHeading":"Instance Property","extendedModule":"Foundation"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/error\/recoverysuggestion"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/LocalizedError-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"text":".","type":"text"}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/Error/LocalizedError-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","abstract":[],"title":"LocalizedError Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/LocalizedError-Implementations","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/error\/localizederror-implementations"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/Error/recoverySuggestion":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error\/recoverySuggestion","title":"recoverySuggestion","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/error\/recoverysuggestion"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibrary","kind":"identifier"}],"title":"DotDocumentLibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","type":"topic","url":"\/documentation\/dotdocument\/dotdocumentlibrary","role":"symbol","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/Error":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/error","title":"DotDocumentLibrary.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title","value":"DotDocumentLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/navigatorTitle","value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}