{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble\/value"},"variants":[{"paths":["\/documentation\/dotpalmcore\/wrappeddouble\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/wrappeddouble\/value"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"value","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble(py)value","modules":[{"name":"DotPalmCore"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"value","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","url":"\/documentation\/dotpalmcore\/wrappeddouble","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WrappedDouble","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.1","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble/value":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble\/value","title":"value","url":"\/documentation\/dotpalmcore\/wrappeddouble\/value","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"value"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"value","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/title","op":"replace","value":"DOTWrappedDouble"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble~1value\/title","value":"value"},{"op":"replace","value":[{"kind":"identifier","text":"value"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble~1value\/fragments"}]}]}