{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"},{"kind":"text","text":" = .init(facing: .front), "},{"kind":"externalParam","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration"},{"kind":"text","text":" = try! .init(\n                faceSizeRatioInterval: Defaults.faceSizeRatioInterval,\n                query: .init()\n            ), "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init(common:camera:facelibrarycomponent:isdetectionlayervisible:)"]}],"sections":[],"metadata":{"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceLibraryComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","externalID":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC13ConfigurationC6common6camera20faceLibraryComponent23isDetectionLayerVisibleAE0aC006CommonI0C_0A7Capture06CameraI0CAA0bmnI0CSbtcfc","symbolKind":"init","modules":[{"name":"DotFaceCore"}],"title":"init(common:camera:faceLibraryComponent:isDetectionLayerVisible:)","platforms":[]},"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init(common:camera:faceLibraryComponent:isDetectionLayerVisible:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"title":"CommonConfiguration","type":"topic","url":"\/documentation\/dotfacecore\/commonconfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"title":"MagnifEyeLivenessViewController.Configuration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"url":"\/documentation\/dotfacecore\/cameraconfiguration","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"title":"CameraConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class/init(common:camera:faceLibraryComponent:isDetectionLayerVisible:)":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/init(common:camera:faceLibraryComponent:isDetectionLayerVisible:)","abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"deprecated":true,"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/init(common:camera:facelibrarycomponent:isdetectionlayervisible:)","role":"symbol","type":"topic","title":"init(common:camera:faceLibraryComponent:isDetectionLayerVisible:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":", ","kind":"text"},{"text":"faceLibraryComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}],"title":"FaceLibraryComponentConfiguration","navigatorTitle":[{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for face library components.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"type":"topic","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"kind":"symbol","title":"MagnifEyeLivenessViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"}]}]}