{"variants":[{"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/isEqual(_:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"method","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"roleHeading":"Instance Method","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(im)isEqual:"},"references":{"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/isEqual(_:)":{"url":"\/documentation\/dotdocument\/autocaptureconfiguration\/isequal(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","title":"isEqual(_:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/isEqual(_:)"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"abstract":[{"type":"text","text":"Configuration for auto capture components."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"title":"AutoCaptureConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/autocaptureconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}]}]}