{"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration(im)init","symbolKind":"method","modules":[{"name":"DotPalmCore"}],"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration\/init"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfaceexpressionneutralmoduleconfiguration\/init"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration"]]},"sections":[],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceExpressionNeutralModuleConfiguration/init":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration\/init","type":"topic","url":"\/documentation\/dotpalmcore\/dotfaceexpressionneutralmoduleconfiguration\/init","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceExpressionNeutralModuleConfiguration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"title":"DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration","type":"topic","url":"\/documentation\/dotpalmcore\/dotfaceexpressionneutralmoduleconfiguration","abstract":[{"text":"Face expression neutral module.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"}]}]}