{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error\/failedToLoadSystemConstants","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"s:7DotCore0A3SdkC5ErrorO27failedToLoadSystemConstantsyA2EmF","modules":[{"name":"DotFaceLite"}],"title":"DotSdk.Error.failedToLoadSystemConstants","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"symbolKind":"case","roleHeading":"Case"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdk\/error\/failedtoloadsystemconstants"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Error/failedToLoadSystemConstants":{"type":"topic","url":"\/documentation\/dotfacelite\/dotsdk\/error\/failedtoloadsystemconstants","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error\/failedToLoadSystemConstants","kind":"symbol","title":"DotSdk.Error.failedToLoadSystemConstants","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"DotSdk","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","url":"\/documentation\/dotfacelite\/dotsdk","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Error":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"DotSdk.Error","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error","url":"\/documentation\/dotfacelite\/dotsdk\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotSdk","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/navigatorTitle"}]}]}