{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration"]]},"sections":[],"topicSections":[{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/defaults"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"BasePalmAutoCaptureViewController.Configuration.Defaults","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Structure","externalID":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV","symbolKind":"struct"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","navigatorTitle":[{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","type":"topic","role":"symbol","title":"BasePalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration/Defaults/minValidSamplesInRowToStartCandidateSelection":{"abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection","role":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/defaults\/minvalidsamplesinrowtostartcandidateselection","kind":"symbol","title":"minValidSamplesInRowToStartCandidateSelection","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"type":"topic","title":"BasePalmAutoCaptureViewController.Configuration","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration/Defaults/candidateSelectionDurationMillis":{"kind":"symbol","title":"candidateSelectionDurationMillis","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/defaults\/candidateselectiondurationmillis","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration/Defaults":{"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults","navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/defaults","kind":"symbol","title":"BasePalmAutoCaptureViewController.Configuration.Defaults","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace","value":"DOTPBasePalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}