{"variants":[{"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","metadata":{"externalID":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC11descriptionSSvp","title":"description","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration/description":{"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/description","role":"symbol","type":"topic","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"kind":"symbol","title":"BasePalmAutoCaptureViewController.Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","navigatorTitle":[{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","title":"BasePalmAutoCaptureViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace","value":"DOTPBasePalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}