{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg13"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg13"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"sections":[],"kind":"symbol","metadata":{"role":"symbol","platforms":[{"introducedAt":"13.0","name":"iOS","deprecated":false,"beta":false,"unavailable":false}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg13","modules":[{"name":"DotNfc"}],"title":"Lds1ElementaryFileId.dg13","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg13"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg13"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"dg13","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"File identifier for data group 13. Data group 13 contains optional details."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg13"},"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg13":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"dg13","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg13"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg13","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg13","kind":"symbol","abstract":[{"type":"text","text":"File identifier for data group 13. Data group 13 contains optional details."}],"title":"Lds1ElementaryFileId.dg13"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid","role":"symbol","title":"Lds1ElementaryFileId","abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DOTNLds1ElementaryFileIdDg13","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTNLds1ElementaryFileIdDg13","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTNLds1ElementaryFileIdDg13","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNLds1ElementaryFileIdDg13","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg13\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg13\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg13"}],"op":"replace"},{"value":"DOTNLds1ElementaryFileId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title"},{"value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}