{"kind":"symbol","seeAlsoSections":[{"generated":true,"title":"UI components","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"]}],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)UIViewController"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSCoding","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSExtensionRequestHandling","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH","doc:\/\/com.innovatrics.dot.face.lite\/s8SendableP","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIAppearanceContainer","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIContentContainer","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIFocusEnvironment","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIStateRestoring","doc:\/\/com.innovatrics.dot.face.lite\/5UIKit23UITraitChangeObservableP","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UITraitEnvironment","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLMagnifEyeLivenessViewController) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class"],"title":"Style and configuration"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"],"title":"Delegate"},{"title":"MagnifEye liveness result","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/init(configuration:style:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/configuration-swift.property","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/delegate","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/style-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/start()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/stopAsync(onStopped:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidAppear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidDisappear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLoad()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillAppear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillTransition(to:with:)"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewDidLoad()":{"title":"viewDidLoad()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"abstract":[],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewdidload()","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLoad()","type":"topic","role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DetectionPosition":{"title":"DetectionPosition","url":"\/documentation\/dotfacelite\/detectionposition","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/delegate":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate","text":"MagnifEyeLivenessViewControllerDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/delegate","abstract":[{"type":"text","text":"Set this delegate to handle the MagnifEye liveness events."}],"role":"symbol","title":"delegate","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/delegate"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewWillTransition(to:with:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillTransition(to:with:)","kind":"symbol","title":"viewWillTransition(to:with:)","abstract":[],"navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewwilltransition(to:with:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewWillDisappear(_:)":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewwilldisappear(_:)","title":"viewWillDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/stopAsync(onStopped:)":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/stopasync(onstopped:)","title":"stopAsync(onStopped:)","navigatorTitle":[{"text":"stopAsyncOnStopped:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/stopAsync(onStopped:)","type":"topic","role":"symbol","abstract":[{"text":"Stop the MagnifEye liveness process asynchronously. The ","type":"text"},{"type":"codeVoice","code":"onStopped"},{"text":" callback is called after the process has stopped.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopAsync","kind":"identifier"},{"kind":"text","text":"("},{"text":"onStopped","kind":"externalParam"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/style-swift.property":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.property","title":"style","navigatorTitle":[{"kind":"identifier","text":"style"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/style-swift.property","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Current style."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC"}]},"doc://com.innovatrics.dot.face.lite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewDidAppear(_:)":{"title":"viewDidAppear(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidAppear(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewdidappear(_:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/configuration-swift.property":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/configuration-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.property","title":"configuration","role":"symbol","abstract":[{"type":"text","text":"Current configuration."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"configuration","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewDidDisappear(_:)":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewdiddisappear(_:)","title":"viewDidDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidDisappear(_:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidDisappear","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIContentContainer":{"type":"unresolvable","title":"UIKit.UIContentContainer","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIContentContainer"},"doc://com.innovatrics.dot.face.lite/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/5UIKit23UITraitChangeObservableP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewWillAppear(_:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillAppear(_:)","abstract":[],"role":"symbol","title":"viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewwillappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}]},"doc://com.innovatrics.dot.face.lite/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)UIViewController"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIUserActivityRestoring"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIStateRestoring"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Style-swift.class":{"title":"MagnifEyeLivenessViewController.Style","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class","abstract":[{"text":"Customization options for the MagnifEye liveness user interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIFocusEnvironment"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSCoding"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","title":"MagnifEyeLivenessViewController.Configuration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/init(configuration:style:)":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/init(configuration:style:)","title":"init(configuration:style:)","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/init(configuration:style:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"MagnifEyeLivenessViewController"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.innovatrics.dot.face.lite/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/start()":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/start()","title":"start()","navigatorTitle":[{"text":"start","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/start()","type":"topic","role":"symbol","abstract":[{"text":"Start the MagnifEye liveness process.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.innovatrics.dot.face.lite/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacelite\/faceautocapturedetection","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","title":"FaceAutoCaptureDetection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate":{"abstract":[{"type":"text","text":"Implement this delegate to handle the MagnifEye liveness events."}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate","title":"MagnifEyeLivenessViewControllerDelegate"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessResult":{"title":"MagnifEyeLivenessResult","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessresult","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessResult"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessResult"}],"abstract":[{"text":"The final result of the MagnifEye liveness process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","title":"MagnifEyeLivenessViewController","role":"symbol","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]},"doc://com.innovatrics.dot.face.lite/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewDidLayoutSubviews()":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewdidlayoutsubviews()","title":"viewDidLayoutSubviews()","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","type":"topic","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","type":"topic","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s8SendableP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","abstract":[{"text":"version: 8.4.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"],"title":"Delegate"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition"],"title":"MagnifEye liveness result"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/configuration-swift.property","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/delegate","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/style-swift.property"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/init(configuration:style:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/start()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/stopAsync(onStopped:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidAppear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidDisappear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLoad()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillAppear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillDisappear(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewWillTransition(to:with:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)UIViewController"],"type":"inheritsFrom","title":"Inherits From"}]},{"value":[{"generated":true,"title":"UI components","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"]}],"path":"\/seeAlsoSections","op":"replace"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"},{"text":" : ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidLoad()\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/title","value":"DOTDetectionPosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1delegate\/title","value":"delegate"},{"value":[{"kind":"identifier","text":"delegate"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1delegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewWillDisappear(_:)\/title","value":"viewWillDisappear:"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewWillDisappear(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1stopAsync(onStopped:)\/title","op":"replace","value":"stopAsyncOnStopped:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAsyncOnStopped:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1stopAsync(onStopped:)\/fragments"},{"value":"style","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1style-swift.property\/title"},{"value":[{"kind":"identifier","text":"style"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1style-swift.property\/fragments"},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidAppear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}]},{"value":"configuration","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1configuration-swift.property\/title"},{"op":"replace","value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1configuration-swift.property\/fragments"},{"value":"viewDidDisappear:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidDisappear(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewWillAppear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewWillAppear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1init(configuration:style:)\/title","op":"replace","value":"initWithConfiguration:style:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1start()\/title","value":"start"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1start()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"start"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}],"op":"replace"},{"value":"DOTFLMagnifEyeLivenessViewControllerDelegate","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/fragments"},{"value":"DOTFLMagnifEyeLivenessResult","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/title"},{"op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessResult","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","value":"viewDidLayoutSubviews","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidLayoutSubviews()\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidLayoutSubviews()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFLFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]}]}]}