{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator"]]},"sections":[],"metadata":{"role":"symbol","required":true,"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"title":"validate(documentAutoCaptureFrameParameters:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureFrameParametersValidator(im)validateWithDocumentAutoCaptureFrameParameters:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Current frame parameters.","type":"text"}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" to indicate failed validation.","type":"text"}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/validate(documentAutoCaptureFrameParameters:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator\/validate(documentautocaptureframeparameters:)"]},{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Validate current frame parameters."}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator":{"title":"DocumentAutoCaptureFrameParametersValidator","role":"symbol","abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParametersValidator"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParametersValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator","url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"type":"topic","title":"DocumentAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParametersValidator/validate(documentAutoCaptureFrameParameters:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParametersValidator\/validate(documentAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate current frame parameters."}],"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"required":true,"role":"symbol","title":"validate(documentAutoCaptureFrameParameters:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparametersvalidator\/validate(documentautocaptureframeparameters:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Current frame parameters."}]}],"name":"documentAutoCaptureFrameParameters"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" to indicate failed validation.","type":"text"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"value":"DOTDDocumentAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace"},{"value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","op":"replace"},{"value":"DOTDDocumentAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle","op":"replace"},{"value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1validate(documentAutoCaptureFrameParameters:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParametersValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","op":"replace"}]}]}