{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"],"type":"inheritedBy"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSCoding","doc:\/\/DotPalmCore\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotPalmCore\/objc(pl)UIAppearanceContainer","doc:\/\/DotPalmCore\/objc(pl)UIContentContainer","doc:\/\/DotPalmCore\/objc(pl)UIFocusEnvironment","doc:\/\/DotPalmCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotPalmCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotPalmCore\/objc(pl)UIStateRestoring","doc:\/\/DotPalmCore\/5UIKit23UITraitChangeObservableP","doc:\/\/DotPalmCore\/objc(pl)UITraitEnvironment","doc:\/\/DotPalmCore\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPBasePalmAutoCaptureViewController) "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This component requires the ","type":"text"},{"type":"codeVoice","code":"DotPalmDetection"},{"text":" module to be active.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"kind":"symbol","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}],"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"class","title":"BasePalmAutoCaptureViewController","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"roleHeading":"Class","navigatorTitle":[{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}]},"sections":[],"topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/baseConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/delegate"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/requestCapture()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/start()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/stop()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillTransition(to:with:)"],"generated":true},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/create(baseConfiguration:)"],"generated":true}],"references":{"doc://DotPalmCore/objc(cs)UIViewController":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewWillDisappear(_:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillDisappear(_:)","kind":"symbol","title":"viewWillDisappear(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewwilldisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillAppear(_:)","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewwillappear(_:)","kind":"symbol"},"doc://DotPalmCore/objc(pl)UIContentContainer":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/delegate":{"title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureViewControllerDelegate"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/delegate","type":"topic","abstract":[{"type":"text","text":"Set this delegate to handle the palm auto capture events."}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/delegate","navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewDidDisappear(_:)":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewdiddisappear(_:)","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidDisappear(_:)","title":"viewDidDisappear(_:)"},"doc://DotPalmCore/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/DotPalmCore\/objc(pl)UIAppearanceContainer"},"doc://DotPalmCore/objc(pl)NSCoding":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://DotPalmCore/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/DotPalmCore\/objc(pl)UIUserActivityRestoring"},"doc://DotPalmCore/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewDidLayoutSubviews()":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidLayoutSubviews()","title":"viewDidLayoutSubviews()","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewdidlayoutsubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"title":"PalmAutoCaptureViewController","kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","abstract":[{"text":"UI Palm Auto Capture component.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/create(baseConfiguration:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier"}],"kind":"symbol","title":"create(baseConfiguration:)","abstract":[{"text":"Create new ","type":"text"},{"code":"BasePalmAutoCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/create(baseConfiguration:)","navigatorTitle":[{"text":"createWithBaseConfiguration:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/create(baseconfiguration:)"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/requestCapture()":{"type":"topic","title":"requestCapture()","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/requestCapture()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/requestcapture()","navigatorTitle":[{"text":"requestCapture","kind":"identifier"}]},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewDidAppear(_:)":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"title":"viewDidAppear(_:)","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewdidappear(_:)"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/start()":{"abstract":[{"type":"text","text":"Start the palm auto capture process."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/start()","title":"start()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"start","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/start()"},"doc://DotPalmCore/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/DotPalmCore\/objc(pl)UIResponderStandardEditActions"},"doc://DotPalmCore/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/DotPalmCore\/5UIKit23UITraitChangeObservableP"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/stop()":{"abstract":[{"type":"text","text":"Stop the palm auto capture process."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"type":"topic","title":"stop()","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/stop()","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","role":"symbol","title":"BasePalmAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewWillTransition(to:with:)":{"type":"topic","kind":"symbol","abstract":[],"title":"viewWillTransition(to:with:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewwilltransition(to:with:)","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillTransition(to:with:)"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","title":"BasePalmAutoCaptureViewController","navigatorTitle":[{"text":"BasePalmAutoCaptureViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","kind":"symbol","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}]},"doc://DotPalmCore/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/DotPalmCore\/objc(pl)UIPasteConfigurationSupporting"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/baseConfiguration":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"baseConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Current configuration."}],"navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/baseConfiguration","kind":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/baseconfiguration","title":"baseConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/viewDidLoad()":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidLoad()","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/viewdidload()","title":"viewDidLoad()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]},"doc://DotPalmCore/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/DotPalmCore\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://DotPalmCore/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/DotPalmCore\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTPBasePalmAutoCaptureViewController"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/baseConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/delegate"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/requestCapture()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/start()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/stop()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/viewWillTransition(to:with:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/create(baseConfiguration:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)UIViewController"]},{"title":"Inherited By","kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewWillDisappear(_:)\/title","op":"replace","value":"viewWillDisappear:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewWillDisappear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewWillAppear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1delegate\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidDisappear(_:)\/title","op":"replace","value":"viewDidDisappear:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidDisappear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidLayoutSubviews()\/title","op":"replace","value":"viewDidLayoutSubviews"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidLayoutSubviews()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLayoutSubviews"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","op":"replace","value":"DOTPPalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1create(baseConfiguration:)\/title","op":"replace","value":"createWithBaseConfiguration:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1create(baseConfiguration:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBaseConfiguration:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1requestCapture()\/title","op":"replace","value":"requestCapture"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1requestCapture()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestCapture"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidAppear(_:)\/title","op":"replace","value":"viewDidAppear:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidAppear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1start()\/title","op":"replace","value":"start"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1start()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1stop()\/title","op":"replace","value":"stop"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1stop()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewWillTransition(to:with:)\/title","op":"replace","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewWillTransition(to:with:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace","value":"DOTPBasePalmAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1baseConfiguration\/title","op":"replace","value":"baseConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1baseConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"baseConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidLoad()\/title","op":"replace","value":"viewDidLoad"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1viewDidLoad()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}