{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration"]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","symbolKind":"class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"roleHeading":"Class","title":"DotDocumentLibraryConfiguration","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},"abstract":[{"text":"Document library configuration.","type":"text"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Document library configuration."}],"title":"DotDocumentLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/init","url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/init","title":"init","abstract":[],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotDocumentLibraryConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/init"],"generated":true,"title":"Instance Methods"}],"op":"add","path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotDocumentLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/title"},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/fragments"},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}