{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPSizeTooLargeValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}]}]}],"kind":"symbol","metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooLargeValidator","title":"SizeTooLargeValidator","symbolKind":"class","role":"symbol","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"roleHeading":"Class"},"sections":[],"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init(maxEdgeLengthToImageShorterSideRatioThreshold:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/maxEdgeLengthToImageShorterSideRatioThreshold"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/validate(palmAutoCaptureFrameParameters:)"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/defaultMaxEdgeLengthToImageShorterSideRatioThreshold"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"seeAlsoSections":[{"title":"Validators","anchor":"Validators","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/init()":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/init()","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init()","title":"init()"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/dependencyIdentifiers":{"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/dependencyIdentifiers","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"type":"topic","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"title":"dependencyIdentifiers","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/dependencyidentifiers"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","type":"topic","abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"title":"BrightnessTooHighValidator","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","type":"topic","abstract":[{"text":"Validate whether the size of the detected palm is too large.","type":"text"}],"kind":"symbol","title":"SizeTooLargeValidator","role":"symbol","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"abstract":[{"type":"text","text":"Validate minimum brightness of the detected palm."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","type":"topic","role":"symbol","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/maxEdgeLengthToImageShorterSideRatioThreshold":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/maxEdgeLengthToImageShorterSideRatioThreshold","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"maxEdgeLengthToImageShorterSideRatioThreshold","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/maxedgelengthtoimageshortersideratiothreshold","navigatorTitle":[{"kind":"identifier","text":"maxEdgeLengthToImageShorterSideRatioThreshold"}],"abstract":[{"type":"text","text":"Current maximal edge length to image shorter side ratio threshold."}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"title":"PalmOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","type":"topic","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/init(maxEdgeLengthToImageShorterSideRatioThreshold:)":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"title":"init(maxEdgeLengthToImageShorterSideRatioThreshold:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init(maxEdgeLengthToImageShorterSideRatioThreshold:)","navigatorTitle":[{"text":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/init(maxedgelengthtoimageshortersideratiothreshold:)"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","kind":"symbol","abstract":[{"text":"Validates confidence of the detected palm.","type":"text"}],"navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","role":"symbol","type":"topic","title":"PalmNotDetectedValidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","title":"SizeTooSmallValidator","abstract":[{"text":"Validate whether the size of the detected palm is too small.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","kind":"symbol","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/validate(palmAutoCaptureFrameParameters:)":{"type":"topic","abstract":[{"text":"Validate size of the detected palm.","type":"text"}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/validate(palmautocaptureframeparameters:)","title":"validate(palmAutoCaptureFrameParameters:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/validate(palmAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator","title":"PalmAutoCaptureFrameParametersValidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/defaultMaxEdgeLengthToImageShorterSideRatioThreshold":{"type":"topic","abstract":[{"type":"text","text":"Default threshold."}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/defaultmaxedgelengthtoimageshortersideratiothreshold","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/defaultMaxEdgeLengthToImageShorterSideRatioThreshold","kind":"symbol","role":"symbol","title":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","navigatorTitle":[{"kind":"identifier","text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"title":"PalmAutoCaptureController","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/identifier":{"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"title":"identifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/identifier","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/identifier"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTPSizeTooLargeValidator","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/maxEdgeLengthToImageShorterSideRatioThreshold"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/init(maxEdgeLengthToImageShorterSideRatioThreshold:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/validate(palmAutoCaptureFrameParameters:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/defaultMaxEdgeLengthToImageShorterSideRatioThreshold"],"generated":true,"anchor":"Type-Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator"],"type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"generated":true,"anchor":"Validators","title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPSizeTooLargeValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1init()\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1init()\/fragments"},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1dependencyIdentifiers\/title"},{"op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1dependencyIdentifiers\/fragments"},{"op":"replace","value":"DOTPBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments"},{"op":"replace","value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/navigatorTitle"},{"op":"replace","value":"DOTPSizeTooLargeValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title"},{"op":"replace","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments"},{"op":"replace","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/navigatorTitle"},{"op":"replace","value":"DOTPBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments"},{"op":"replace","value":[{"text":"DOTPBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/navigatorTitle"},{"op":"replace","value":"maxEdgeLengthToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1maxEdgeLengthToImageShorterSideRatioThreshold\/title"},{"op":"replace","value":[{"text":"maxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1maxEdgeLengthToImageShorterSideRatioThreshold\/fragments"},{"op":"replace","value":"DOTPPalmOutOfBoundsValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title"},{"op":"replace","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/navigatorTitle"},{"op":"replace","value":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1init(maxEdgeLengthToImageShorterSideRatioThreshold:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMaxEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1init(maxEdgeLengthToImageShorterSideRatioThreshold:)\/fragments"},{"op":"replace","value":"DOTPPalmNotDetectedValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title"},{"op":"replace","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/navigatorTitle"},{"op":"replace","value":"DOTPSizeTooSmallValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title"},{"op":"replace","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/navigatorTitle"},{"op":"replace","value":"DOTPSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/navigatorTitle"},{"op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1validate(palmAutoCaptureFrameParameters:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","value":"DOTPPalmAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle"},{"op":"replace","value":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1defaultMaxEdgeLengthToImageShorterSideRatioThreshold\/title"},{"op":"replace","value":[{"text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1defaultMaxEdgeLengthToImageShorterSideRatioThreshold\/fragments"},{"op":"replace","value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1identifier\/title"},{"op":"replace","value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1identifier\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}