{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imageformat\/jpeg"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/imageformat\/jpeg"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg"},"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg","role":"symbol","symbolKind":"case","title":"ImageFormat.jpeg"},"abstract":[{"text":"JPEG compressed image format","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc/ImageFormat/jpeg":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"url":"\/documentation\/dotnfc\/imageformat\/jpeg","abstract":[{"type":"text","text":"JPEG compressed image format"}],"kind":"symbol","title":"ImageFormat.jpeg","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/jpeg"},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"abstract":[{"type":"text","text":"Supported image formats."}],"title":"ImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotnfc\/imageformat","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}]},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTImageFormatJpeg"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTImageFormatJpeg","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg\/title","value":"DOTImageFormatJpeg"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat~1jpeg\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}