{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Format of the stored image","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"}]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"format","role":"symbol","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DOTImage(py)format","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"format"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/format","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/image\/format"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/image\/format"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"url":"\/documentation\/dotfacelite\/imageformat","kind":"symbol","title":"ImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"role":"symbol","title":"Image","kind":"symbol","url":"\/documentation\/dotfacelite\/image","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","abstract":[],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Image/format":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Format of the stored image"}],"url":"\/documentation\/dotfacelite\/image\/format","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"format","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/format","title":"format","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","title":"FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"format","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"format"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImageFormat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFormat","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle"},{"value":"format","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1format\/title"},{"value":[{"kind":"identifier","text":"format"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1format\/fragments"},{"value":"DOTFLFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}