{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Face library configuration."}],"metadata":{"title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"symbolKind":"class","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},"topicSections":[{"title":"Classes","generated":true,"anchor":"Classes","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/modules-swift.property"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"references":{"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Face library module configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"title":"DotFaceLibraryConfiguration.Modules"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/init(modules:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:)","title":"init(modules:)","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"kind":"symbol"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/faceDetectionConfidenceThreshold":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold","type":"topic","navigatorTitle":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}],"abstract":[{"text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval ","type":"text"},{"type":"codeVoice","code":"[0.0, 1.0]"},{"text":". Default value is ","type":"text"},{"type":"codeVoice","code":"0.06"},{"text":".","type":"text"}],"title":"faceDetectionConfidenceThreshold","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/modules-swift.property":{"title":"modules","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"}],"navigatorTitle":[{"kind":"identifier","text":"modules"}],"type":"topic","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.property","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/modules-swift.property","role":"symbol","abstract":[{"type":"text","text":"Module configuration."}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)","type":"topic","title":"init(modules:faceDetectionConfidenceThreshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","kind":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","abstract":[{"text":"Face library configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/modules-swift.property"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithModules:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:)\/fragments"},{"value":"faceDetectionConfidenceThreshold","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/title"},{"value":[{"kind":"identifier","text":"faceDetectionConfidenceThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/fragments"},{"value":"modules","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1modules-swift.property\/title"},{"value":[{"kind":"identifier","text":"modules"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1modules-swift.property\/fragments"},{"value":"initWithModules:faceDetectionConfidenceThreshold:error:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments"},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle"}]}]}