{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary"]]},"metadata":{"title":"init()","externalID":"c:@M@DotNfc@objc(cs)DotNfcLibrary(im)init","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"introducedAt":"13.0","beta":false}],"role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"DotNfc"}],"symbolKind":"init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotnfc\/dotnfclibrary\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary\/init()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/init()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotNfcLibrary":{"title":"DotNfcLibrary","role":"symbol","type":"topic","navigatorTitle":[{"text":"DotNfcLibrary","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotNfc","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotNfcLibrary","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotnfclibrary","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/init()":{"title":"init()","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/init()","url":"\/documentation\/dotnfc\/dotnfclibrary\/init()","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"init","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/title","op":"replace","value":"DotNfcLibrary"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments","value":[{"text":"DotNfcLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1init()\/title","op":"replace","value":"init"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary~1init()\/fragments"}]}]}