{"kind":"symbol","abstract":[{"type":"text","text":"Raw data group DG10."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg10substancefeatures"]},{"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg10substancefeatures"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg10SubstanceFeatures"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg10SubstanceFeatures","interfaceLanguage":"swift"},"metadata":{"title":"dg10SubstanceFeatures","platforms":[{"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.0","unavailable":false}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg10SubstanceFeatures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"dg10SubstanceFeatures"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg10SubstanceFeatures"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1eMrtdApplication":{"navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}],"type":"topic","title":"Lds1eMrtdApplication","role":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1eMrtdApplication","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"url":"\/documentation\/dotnfc\/traveldocument","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","type":"topic","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1eMrtdApplication/dg10SubstanceFeatures":{"url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg10substancefeatures","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg10SubstanceFeatures","title":"dg10SubstanceFeatures","navigatorTitle":[{"kind":"identifier","text":"dg10SubstanceFeatures"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg10SubstanceFeatures"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Raw data group DG10."}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFile":{"navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFile"}],"type":"topic","title":"Lds1ElementaryFile","role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfile","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"dg10SubstanceFeatures"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dg10SubstanceFeatures"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFile","kind":"typeIdentifier","text":"DOTNLds1ElementaryFile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dg10SubstanceFeatures"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title","value":"DOTNLds1eMrtdApplication"},{"value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"},{"value":"dg10SubstanceFeatures","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg10SubstanceFeatures\/title"},{"value":[{"text":"dg10SubstanceFeatures","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg10SubstanceFeatures\/fragments"},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}