{"kind":"symbol","abstract":[{"text":"Raw data group DG11.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg11AdditionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication"]]},"metadata":{"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNLds1eMrtdApplication(py)dg11AdditionalPersonalDetails","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg11AdditionalPersonalDetails"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"Lds1ElementaryFile"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","title":"dg11AdditionalPersonalDetails","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"dg11AdditionalPersonalDetails","kind":"identifier"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg11AdditionalPersonalDetails"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg11additionalpersonaldetails"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1emrtdapplication\/dg11additionalpersonaldetails"]}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication/dg11AdditionalPersonalDetails":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg11AdditionalPersonalDetails","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Lds1ElementaryFile","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Raw data group DG11."}],"role":"symbol","title":"dg11AdditionalPersonalDetails","url":"\/documentation\/dotnfc\/lds1emrtdapplication\/dg11additionalpersonaldetails","navigatorTitle":[{"text":"dg11AdditionalPersonalDetails","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication\/dg11AdditionalPersonalDetails"},"doc://DotNfc/documentation/DotNfc/Lds1eMrtdApplication":{"kind":"symbol","url":"\/documentation\/dotnfc\/lds1emrtdapplication","type":"topic","abstract":[{"type":"text","text":"Raw representation of Logical Data Structure version 1 eMRTD application stored in the NFC chip of the travel document."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1eMrtdApplication","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1eMrtdApplication"}],"role":"symbol","title":"Lds1eMrtdApplication","navigatorTitle":[{"kind":"identifier","text":"Lds1eMrtdApplication"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFile":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Lds1ElementaryFile","kind":"identifier"}],"role":"symbol","title":"Lds1ElementaryFile","abstract":[{"type":"text","text":"Raw representation of a single file in Logical Data Structure version 1 stored in the NFC chip of the travel document."}],"navigatorTitle":[{"text":"Lds1ElementaryFile","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfile"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"dg11AdditionalPersonalDetails","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"dg11AdditionalPersonalDetails"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNLds1ElementaryFile","text":"DOTNLds1ElementaryFile","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFile"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dg11AdditionalPersonalDetails"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"dg11AdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg11AdditionalPersonalDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"dg11AdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication~1dg11AdditionalPersonalDetails\/fragments"},{"op":"replace","value":"DOTNLds1eMrtdApplication","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/title"},{"op":"replace","value":[{"text":"DOTNLds1eMrtdApplication","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1eMrtdApplication"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1eMrtdApplication\/navigatorTitle"},{"op":"replace","value":"DOTNLds1ElementaryFile","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFile"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/fragments"},{"op":"replace","value":[{"text":"DOTNLds1ElementaryFile","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFile\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}